SUEWS: gis_data Module Reference
gis_data Module Reference
Variables
real(kind(1d0)) areaunir
real(kind(1d0)) areair
real(kind(1d0)) bldgh
real(kind(1d0)) faibldg
real(kind(1d0)) faitree
real(kind(1d0)) faievetree
real(kind(1d0)) faidectree
real(kind(1d0)) grassfractionirrigated
real(kind(1d0)) pavedfractionirrigated
real(kind(1d0)) treeh
real(kind(1d0)) evetreeh
real(kind(1d0)) dectreeh
real(kind(1d0)) treefractionirrigated
real(kind(1d0)) veg_fr
real(kind(1d0)) vegfraction
real(kind(1d0)) impervfraction
real(kind(1d0)) pervfraction
real(kind(1d0)) nonwaterfraction
real(kind(1d0)) areazh
integer idgis
integer itgis
integer veg_type = 1
Variable Documentation
areair
real(kind(1d0)) gis_data::areair
Definition at line 1394 of file suews_ctrl_const.f95.
areaunir
real(kind(1d0)) gis_data::areaunir
Definition at line 1394 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: areaunir, &                   !Unirrigated area
                      areair, &                     !Irrigated area
                      bldgH, &                      !Mean building height
                      FAIbldg, &                    !Frontal area fraction of buildings
                      FAItree, &                    !Frontal area fraction of trees
                      FAIEveTree, &                    !Frontal area fraction of evergreen trees
                      FAIDecTree, &                    !Frontal area fraction of deciduous trees
                      grassfractionirrigated, &     !Irrigated grass fraction for LUMPS
                      pavedfractionirrigated, &     !Irrigated paved area fraction for LUMPS
                      TreeH, &                      !Mean tree height
                      EveTreeH, &                     !Height of evergreen trees
                      DecTreeH, &                     !Height of deciduous trees
                      treefractionirrigated, &      !Irrigated tree fraction for LUMPS
                      veg_fr, &                     !Vegetation fraction from land area
                      !- For LUMPS - dependent on user choice    & water
                      vegfraction, &               ! sum of vegetation -not including water
                      impervfraction, &             ! sum of surface cover fractions for impervious surfaces
                      pervfraction, &               ! sum of surface cover fractions for pervious surfaces
                      nonwaterfraction, &           ! sum of surface cover fractions for all except water surfaces
                      areazh                       !=(sfr(BldgSurf)+sfr(ConifSurf)+sfr(DecidSurf)) !Total area of buildings and trees
areazh
real(kind(1d0)) gis_data::areazh
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().
bldgh
real(kind(1d0)) gis_data::bldgh
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate(), initialstate(), suews_calculations(), and suews_translate().
dectreeh
real(kind(1d0)) gis_data::dectreeh
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
evetreeh
real(kind(1d0)) gis_data::evetreeh
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
faibldg
real(kind(1d0)) gis_data::faibldg
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
faidectree
real(kind(1d0)) gis_data::faidectree
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
faievetree
real(kind(1d0)) gis_data::faievetree
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
faitree
real(kind(1d0)) gis_data::faitree
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().
grassfractionirrigated
real(kind(1d0)) gis_data::grassfractionirrigated
Definition at line 1394 of file suews_ctrl_const.f95.
idgis
integer gis_data::idgis
Definition at line 1415 of file suews_ctrl_const.f95.
    INTEGER:: idgis, &      !Time integers used in the code
              itgis, &      !
              Veg_type = 1    !Defines how vegetation is calculated for LUMPS
impervfraction
real(kind(1d0)) gis_data::impervfraction
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().
itgis
integer gis_data::itgis
Definition at line 1415 of file suews_ctrl_const.f95.
nonwaterfraction
real(kind(1d0)) gis_data::nonwaterfraction
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().
pavedfractionirrigated
real(kind(1d0)) gis_data::pavedfractionirrigated
Definition at line 1394 of file suews_ctrl_const.f95.
pervfraction
real(kind(1d0)) gis_data::pervfraction
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().
treefractionirrigated
real(kind(1d0)) gis_data::treefractionirrigated
Definition at line 1394 of file suews_ctrl_const.f95.
treeh
real(kind(1d0)) gis_data::treeh
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().
veg_fr
real(kind(1d0)) gis_data::veg_fr
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().
veg_type
integer gis_data::veg_type = 1
Definition at line 1415 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
vegfraction
real(kind(1d0)) gis_data::vegfraction
Definition at line 1394 of file suews_ctrl_const.f95.
Referenced by suews_translate().