SUEWS: meteo Module Reference
meteo Module Reference
Functions/Subroutines
real(kind(1d0)) function sat_vap_press (TK, P)
real(kind(1d0)) function sos_dryair (TK)
real(kind(1d0)) function potential_temp (TK, P)
real(kind(1d0)) function latentheat_v (TK)
real(kind(1d0)) function latentheat_m (TK)
real(kind(1d0)) function spec_heat_dryair (TK)
real(kind(1d0)) function spec_heat_vapor (TK, RH)
real(kind(1d0)) function heatcapacity_air (TK, RH, P)
real(kind(1d0)) function density_moist (TVK, P)
real(kind(1d0)) function density_vapor (TK, RH, P)
real(kind(1d0)) function density_dryair (TK, P)
real(kind(1d0)) function density_gas (TK, PP, MOLMASS)
real(kind(1d0)) function partial_pressure (TK, N)
real(kind(1d0)) function scale_height (TK)
real(kind(1d0)) function vaisala_brunt_f (TK)
real(kind(1d0)) function sat_vap_press_x (Temp_c, PRESS_hPa, from, dectime)
real(kind(1d0)) function sat_vap_pressice (Temp_c, PRESS_hPa, from, dectime)
real(kind(1d0)) function spec_hum_def (vpd_hPa, press_hPa)
real(kind(1d0)) function spec_heat_beer (Temp_C, rh, rho_v, rho_d)
real(kind(1d0)) function lat_vap (Temp_C, Ea_hPa, Press_hPa, cp, dectime)
real(kind(1d0)) function lat_vapsublim (Temp_C, Ea_hPa, Press_hPa, cp)
real(kind(1d0)) function psyc_const (cp, Press_hPa, lv_J_kg)
real(kind(1d0)) function dewpoint (ea_hPa)
real(kind(1d0)) function slope_svp (temp_C)
real(kind(1d0)) function slopeice_svp (temp_C)
real(kind(1d0)) function qsatf (T, PMB)
real(kind(1d0)) function rh2qa (RH, pres_hPa, Ta_degC)
real(kind(1d0)) function qa2rh (qa, pres_hPa, Ta_degC)
Variables
real(kind(1d0)), parameter rad2deg = 57.29577951
real(kind(1d0)), parameter deg2rad = 0.017453292
real(kind(1d0)), parameter molmass_air = 0.028965
real(kind(1d0)), parameter molmass_co2 = 0.04401
real(kind(1d0)), parameter molmass_h2o = 0.0180153
real(kind(1d0)), parameter mu_h2o = MOLMASS_AIR/MOLMASS_H2O
real(kind(1d0)), parameter mu_co2 = MOLMASS_AIR/MOLMASS_CO2
real(kind(1d0)), parameter r_dry_mol = 8.31451
real(kind(1d0)), parameter r_dry_mass = R_DRY_MOL/MOLMASS_AIR
real(kind(1d0)), parameter epsil = 0.62197
real(kind(1d0)), parameter kb = 1.3807E-25
real(kind(1d0)), parameter avogadro = 6.02252E23
Function/Subroutine Documentation
density_dryair()
real(kind(1d0)) function meteo::density_dryair (real(kind(1d0)) TK, real(kind(1d0)) P)
Definition at line 111 of file suews_util_meteo.f95.
       REAL(KIND(1d0)) ::TK, P
       density_dryair = p*100./(r_dry_mass*tk)
References r_dry_mass.
Referenced by heatcapacity_air().
density_gas()
real(kind(1d0)) function meteo::density_gas (real(kind(1d0)) TK, real(kind(1d0)) PP, real(kind(1d0)) MOLMASS)
Definition at line 116 of file suews_util_meteo.f95.
       !DENSITY FOR IDEAL GAS SPECIES GIVEN ITS PARTIAL PRESSURE (hPa) AND MOLAR MASS (kg)
       REAL(KIND(1d0)) ::TK, PP, MOLMASS
       density_gas = pp*molmass/(r_dry_mol*tk)
References r_dry_mol.
density_moist()
real(kind(1d0)) function meteo::density_moist (real(kind(1d0)) TVK, real(kind(1d0)) P)
Definition at line 96 of file suews_util_meteo.f95.
       ! density of moist air FROM VIRTUAL TEMPERATURE
       !TVK = VIRTUAL TEMPERATURE (K)
       != = PRESSURE (hPa)
       REAL(KIND(1d0)) ::TVK, P
       density_moist = p*100./(r_dry_mass*tvk)
References r_dry_mass.
density_vapor()
real(kind(1d0)) function meteo::density_vapor (real(kind(1d0)) TK, real(kind(1d0)) RH, real(kind(1d0)) P)
Definition at line 104 of file suews_util_meteo.f95.
       !WATER VAPOR DENSITY
       REAL(KIND(1d0))    ::TK, P, RH, EA
       ea = sat_vap_press(tk, p)*rh/100.
       density_vapor = (ea*100.*epsil)/(r_dry_mass*tk)
References epsil, r_dry_mass, and sat_vap_press().
Referenced by heatcapacity_air().
dewpoint()
real(kind(1d0)) function meteo::dewpoint (real(kind(1d0)) ea_hPa)
Definition at line 431 of file suews_util_meteo.f95.
       ! ea = vapor pressure (hPa)
       ! td = dewpoint (oC)
       !calculates dewpoint in degC from
       ! http://www.atd.ucar.edu/weather_fl/dewpoint.html
       !     dewpoint = (237.3 * ln(e_vp/6.1078)) / (17.27 - (ln(e_vp/6.1078)))
       REAL(KIND(1d0))::ea_hPa, temp_C_dew
       temp_c_dew = (237.3*log(ea_hpa/6.1078))/(17.27 - (log(ea_hpa/6.1078)))
heatcapacity_air()
real(kind(1d0)) function meteo::heatcapacity_air (real(kind(1d0)) TK, real(kind(1d0)) RH, real(kind(1d0)) P)
Definition at line 85 of file suews_util_meteo.f95.
       REAL(KIND(1d0)) ::TK, RH, P
       REAL(KIND(1d0)) ::RHO_D, RHO_V
       REAL(KIND(1d0)) ::CPD, CPV
       rho_d = density_dryair(tk, p)
       rho_v = density_vapor(tk, rh, p)
       cpd = spec_heat_dryair(tk)
       cpv = spec_heat_vapor(tk, rh)
       heatcapacity_air = rho_d*cpd + rho_v*cpv
References density_dryair(), density_vapor(), spec_heat_dryair(), and spec_heat_vapor().
Referenced by estm_module::estm().
lat_vap()
real(kind(1d0)) function meteo::lat_vap (real(kind(1d0)) Temp_C, real(kind(1d0)) Ea_hPa, real(kind(1d0)) Press_hPa, real(kind(1d0)) cp, real(kind(1d0)) dectime)
Definition at line 275 of file suews_util_meteo.f95.
       !Input: Air temperature, Water vapour pressure, Air pressure, heat capacity
       !Output: latent heat of vaporization
       ! USE time
       ! USE SnowMod
       ! USE defaultnotUsed
       IMPLICIT NONE
       REAL(KIND(1d0))::cp, lv_J_kg, ea_fix, tw, &
                         incr, es_tw, psyc, ea_est, press_hpa, ea_hpa, temp_c, dectime!,Temp_K
       ! REAL(KIND(1d0))::sat_vap_press,psyc_const ! functions
       LOGICAL:: switch1 = .false., switch2 = .false.!,debug=.true.
       INTEGER:: ii, from = 2
       REAL(KIND(1d0)), PARAMETER::notUsed = -55.55
       ea_fix = ea_hpa
       !if(debug) write(*,*)Temp_C, 'LV'
       !Temp_K=temp_C+273.16
       !lv=1.91846E6*(Temp_K/(Temp_K-33.91))**2
       lv_j_kg = (2500.25 - 2.365*temp_c)*1000  !First guess for lv in units J/kg
       tw = temp_c/2.  !First estimate for wet bulb temperature
       incr = 3.
       DO ii = 1, 100
          IF (press_hpa < 900) THEN
             CALL errorhint(45, 'function Lat_vap', press_hpa, notused, ii)
          ENDIF
          ! if(debug.and.dectime>55.13.and.dectime<55.2)write(35,*)'% 1',Tw
          es_tw = sat_vap_press_x(tw, press_hpa, from, dectime)  !Calculate saturation vapour pressure in hPa
          !if(debug.and.dectime>55.13.and.dectime<55.2)write(35,*)'% 2',Tw
          IF (press_hpa < 900) THEN
             CALL errorhint(45, 'function Lat_vap - 2', press_hpa, notused, ii)
          ENDIF
          psyc = psyc_const(cp, press_hpa, lv_j_kg) !in units hPa/K
          IF (press_hpa < 900) THEN
             CALL errorhint(45, 'function Lat _vap -31', press_hpa, notused, ii)
          ENDIF
          ea_est = es_tw - psyc*(temp_c - tw)
          lv_j_kg = (2500.25 - 2.365*tw)*1e3
          IF (switch1 .AND. switch2) THEN
             incr = incr/10.
             switch1 = .false.
             switch2 = .false.
          ENDIF
          IF (abs(ea_est - ea_fix) < 0.001000) THEN
             RETURN
          ELSEIF (ea_est > ea_fix) THEN
             tw = tw - incr
             switch1 = .true.
          ELSEIF (ea_est < ea_fix) THEN
             tw = tw + incr
             switch2 = .true.
          ENDIF
       ENDDO
       RETURN
References errorhint(), psyc_const(), and sat_vap_press_x().
Referenced by atmmoiststab_module::lumps_cal_atmmoist().
lat_vapsublim()
real(kind(1d0)) function meteo::lat_vapsublim (real(kind(1d0)) Temp_C, real(kind(1d0)) Ea_hPa, real(kind(1d0)) Press_hPa, real(kind(1d0)) cp)
Definition at line 346 of file suews_util_meteo.f95.
       !Input: Air temperature, Water vapour pressure, Air pressure, heat capacity
       !Output: latent heat of sublimation in units J/kg
       ! USE time
       IMPLICIT NONE
       REAL(KIND(1d0))::lvS_J_kg, temp_C, tw, incr, Ea_hPa, Press_hPa, cp
       ! REAL(KIND(1d0))::ea_fix,es_tw,psyc,ea_est,Temp_K
       ! REAL(KIND(1d0))::sat_vap_pressIce,psyc_const ! functions
       ! LOGICAL:: switch1=.FALSE.,switch2=.FALSE.!,debug=.true.
       ! INTEGER:: ii,from=2
       !Latent heat for sublimation
       !From Rogers&Yau (A short course in cloud physics), Wikipedia
       ! ea_fix=ea_hPa
       lvs_j_kg = (2834.1 - 0.29*temp_c)*1e3 !First guess for Ls in J/kg
       tw = temp_c/2.  !First estimate for wet bulb temperature
       incr = 3.
       press_hpa = press_hpa
       ea_hpa = ea_hpa
       cp = cp
       !DO ii=1,100
       !    es_tw=sat_vap_pressIce(Tw,Press_hPa,from)  !Calculate saturation vapour pressure in hPa
       ! psyc=psyc_const(cp,Press_hPa,lv_J_kg)
       !   ea_est=es_tw-psyc*(temp_C-tw)
       !  lvS_J_kg=(2834.1-0.29*tw)*1e3
       !   IF(switch1.AND.switch2)THEN
       !      incr=incr/10.
       !     switch1=.FALSE.
       !     switch2=.FALSE.
       !    ENDIF
       !   IF(ABS(ea_est-ea_fix)<0.001)THEN
       !     RETURN
       !   ELSEIF(ea_est > ea_fix)THEN
       !      tw=tw-incr
       !      switch1=.TRUE.
       !   ELSEIF(ea_est< ea_fix)THEN
       !      tw=tw+incr
       !      switch2=.TRUE.
       !    ENDIF
       !   ENDDO
       ! RETURN
Referenced by atmmoiststab_module::lumps_cal_atmmoist().
latentheat_m()
real(kind(1d0)) function meteo::latentheat_m (real(kind(1d0)) TK)
Definition at line 63 of file suews_util_meteo.f95.
       !LATENT HEAT OF MELTING (J/kg) VALID BELOW 0C BOLTON(1980)
       !TK = ABSOLUTE TEMPERATURE
       REAL(KIND(1d0)) ::TK, TC
       tc = tk - 273.15
       latentheat_m = 3.3358e5 + tc*(2030.-10.46*tc)
latentheat_v()
real(kind(1d0)) function meteo::latentheat_v (real(kind(1d0)) TK)
Definition at line 56 of file suews_util_meteo.f95.
       !LATENT HEAT OF VAPORIZATION (J/kg) BOLTON(1980)
       !TK = ABSOLUTE TEMPERATURE
       REAL(KIND(1d0)) ::TK
       latentheat_v = 2.501e6 - 2370.*(tk - 273.15)
partial_pressure()
real(kind(1d0)) function meteo::partial_pressure (real(kind(1d0)) TK, real(kind(1d0)) N)
Definition at line 122 of file suews_util_meteo.f95.
       !PARTIAL PRESSURE OF IDEAL GAS (hPa)
       REAL(KIND(1d0)) ::TK, N !N IS THE NUMBER DENSITY IN mol/m3
       partial_pressure = n*kb*tk
References kb.
potential_temp()
real(kind(1d0)) function meteo::potential_temp (real(kind(1d0)) TK, real(kind(1d0)) P)
Definition at line 49 of file suews_util_meteo.f95.
       !TK = ABSOLUTE TEMPERATURE
       !P  = PRESS (hPa)
       REAL(KIND(1d0))    ::TK, P
       potential_temp = tk*(1000./p)**0.286
psyc_const()
real(kind(1d0)) function meteo::psyc_const (real(kind(1d0)) cp, real(kind(1d0)) Press_hPa, real(kind(1d0)) lv_J_kg)
Definition at line 407 of file suews_util_meteo.f95.
       USE gas
       IMPLICIT NONE
       REAL(KIND(1d0))::cp, lv_J_kg, press_hPa, psyc_hpa
       ! cp for moist air (shuttleworth p 4.13)
       IF (cp*press_hpa < 900 .OR. lv_j_kg < 10000) THEN
          CALL errorhint(19, &
                         'in psychrometric constant calculation:  cp [J kg-1 K-1], p [hPa], Lv [J kg-1]', &
                         cp, press_hpa, int(lv_j_kg))
       ENDIF
       psyc_hpa = (cp*press_hpa)/(epsil*lv_j_kg)
       !    if(debug)write(*,*)psyc_hpa, 'g',cp,press_HPa,lv
       ! LV MJKg-1
       !www.cimis.water.ca.gov/infoEotPmEquation.jsp
       !psyc_hPa=(0.00163*(Press_hPa/10)/LV)*10
       ! write(*,*)psyc_hpa
       !psyc=psyc*100.! convert into Pa
References gas::epsil, and errorhint().
Referenced by lat_vap(), and lumps_cal_qhqe().
qa2rh()
real(kind(1d0)) function meteo::qa2rh (real(kind(1d0)), intent(in) qa, real(kind(1d0)), intent(in) pres_hPa, real(kind(1d0)), intent(in) Ta_degC)
Definition at line 534 of file suews_util_meteo.f95.
       ! convert specific humidity to relative humidity
       ! TS 31 Jul 2018: initial version
       ! Brutasert (2005) section 2.1.2, eqn 2.2, 2.4 and 2.5.
       REAL(KIND(1d0)), INTENT(in) :: qa       ! specific humidity in (g kg-1)
       REAL(KIND(1D0)), INTENT(in) :: pres_hPa ! atmospheric pressure in hPa
       REAL(KIND(1D0)), INTENT(in) :: Ta_degC  ! air temperature in degC
       REAL(KIND(1D0))             :: RH       ! relative humidity in decimal
       REAL(KIND(1d0))    ::es ! saturation vapour pressure in hPa
       REAL(KIND(1d0))    ::ea ! vapour pressure in hPa
       REAL(KIND(1d0))    ::qa_kgkg !specific humidity in (kg kg-1)
       qa_kgkg = qa/1000
       es = sat_vap_press(ta_degc + 273.15, pres_hpa)
       ea = 500*pres_hpa*qa_kgkg/(311 + 189*qa_kgkg)
       ! qa=0.622*ea/(pres_hPa-0.378*ea)*1000 ! eqn 2.2, 2.4 and 2.5.
       rh = ea/es ! Brutasert (2005) section 2.1.2, eqn 2.3
References sat_vap_press().
Referenced by suews_driver::suews_cal_diagnostics().
qsatf()
real(kind(1d0)) function meteo::qsatf (real(kind(1d0)) T, real(kind(1d0)) PMB)
Definition at line 493 of file suews_util_meteo.f95.
       !       MRR, 1987
       ! AT TEMPERATURE T (DEG C) AND PRESSURE PMB (MB), GET SATURATION SPECIFIC
       !       HUMIDITY (KG/KG) FROM TETEN FORMULA
       REAL(KIND(1D0))::T, es, qsat, PMB
       REAL(KIND(1D0)), PARAMETER:: &
          !Teten coefficients
          a = 6.106, &
          b = 17.27, &
          c = 237.3, &
          molar = 0.028965, & !Dry air molar fraction in kg/mol
          molar_wat_vap = 0.0180153 !Molar fraction of water vapor in kg/mol
       IF (t > 55) THEN
          CALL errorhint(34, 'Function qsatf', t, 0.00d0, -55)
       ENDIF
       es = a*dexp(b*t/(c + t))
       qsat = (molar_wat_vap/molar)*es/pmb!(rmh2o/rmair)*ES/PMB
References errorhint().
rh2qa()
real(kind(1d0)) function meteo::rh2qa (real(kind(1d0)), intent(in) RH, real(kind(1d0)), intent(in) pres_hPa, real(kind(1d0)), intent(in) Ta_degC)
Definition at line 516 of file suews_util_meteo.f95.
       ! convert relative humidity to specific humidity
       ! TS 31 Jul 2018: initial version
       ! Brutasert (2005) section 2.1.2, eqn 2.2, 2.4 and 2.5.
       REAL(KIND(1D0)), INTENT(in) :: RH ! relative humidity in decimal
       REAL(KIND(1D0)), INTENT(in) :: pres_hPa ! atmospheric pressure in hPa
       REAL(KIND(1D0)), INTENT(in) :: Ta_degC ! air temperature in degC
       REAL(KIND(1d0)) ::es ! saturation vapour pressure in hPa
       REAL(KIND(1d0)) ::ea ! vapour pressure in hPa
       REAL(KIND(1d0)) ::qa ! specific humidity in (g kg-1)
       es = sat_vap_press(ta_degc + 273.15, pres_hpa)
       ea = es*rh ! Brutasert (2005) section 2.1.2, eqn 2.3
       qa = 0.622*ea/(pres_hpa - 0.378*ea)*1000 ! eqn 2.2, 2.4 and 2.5.
References sat_vap_press().
Referenced by suews_driver::suews_cal_diagnostics().
sat_vap_press()
real(kind(1d0)) function meteo::sat_vap_press (real(kind(1d0)) TK, real(kind(1d0)) P)
Definition at line 27 of file suews_util_meteo.f95.
       !c sg sept 99 f90
       !c     This uses eqns from Buck (1981) JAM 20, 1527-1532
       !c     units T (K) e (mb) P (mb)
       !c     f corrects for the fact that we are not dealing with pure water
       REAL(KIND(1d0))    :: TK, P, TC, es, e, f
       tc = tk - 273.15
       IF (tc == 0) THEN
          tc = 0.001
       ENDIF
       !Valid for 50>T>-40
       e = 6.1121*exp(((18.729 - tc/227.3)*tc)/(tc + 257.87))
       f = 1.00072 + p*(3.2e-6 + 5.9e-10*tc**2)
       es = e*f
Referenced by density_vapor(), qa2rh(), and rh2qa().
sat_vap_press_x()
real(kind(1d0)) function meteo::sat_vap_press_x (real(kind(1d0)) Temp_c, real(kind(1d0)) PRESS_hPa, integer from, real(kind(1d0)) dectime)
Definition at line 149 of file suews_util_meteo.f95.
       ! USE time
       ! USE defaultnotUsed
       IMPLICIT NONE
       REAL(KIND(1d0))::temp_C, press_hpa, dectime!,pw
       REAL(KIND(1d0))::e_mb, f, press_kpa, es_hPA
       INTEGER:: from, iv
       INTEGER, PARAMETER::notUsedI = -55
       es_hpa = 1000 ! initialise as 1000
       !If air temperature between -0.001 -
       IF (abs(temp_c) < 0.001000) THEN
          IF (from == 1) THEN  ! not from determining Tw
             iv = int(press_hpa)
             CALL errorhint(29, 'Function sat_vap_press: temp_C, dectime,press_Hpa = ', temp_c, dectime, iv)
          ENDIF
          temp_c = 0.001000
       ENDIF
       press_kpa = press_hpa/10
       IF (temp_c < 50 .AND. temp_c > -40) THEN
          !e_mb=6.1121*EXP(((18.729-Temp_C/227.3)*Temp_C)/(Temp_C+257.87)) !Old one
          !f=1.00072+Press_hPa*(3.2E-6+5.9D-10*Temp_C**2)
          IF (temp_c >= 0.001000) THEN
             e_mb = 6.1121*exp(((18.678 - temp_c/234.5)*temp_c)/(temp_c + 257.14))
             f = 1.00072 + press_kpa*(3.2e-6 + 5.9e-10*temp_c**2)
             es_hpa = e_mb*f
          ELSEIF (temp_c <= -0.001000) THEN
             e_mb = 6.1115*exp(((23.036 - temp_c/333.7)*temp_c)/(temp_c + 279.82))
             f = 1.00022 + press_kpa*(3.83e-6 + 6.4e-10*temp_c**2)
             es_hpa = e_mb*f
          ENDIF
       ELSE
          CALL errorhint(28, 'FUNCTION sat_vap_press: [Temperature is out of range], Temp_C,dectime', temp_c, dectime, notusedi)
       ENDIF
       RETURN
References errorhint().
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), lat_vap(), atmmoiststab_module::lumps_cal_atmmoist(), and bluews_module::nbl().
sat_vap_pressice()
real(kind(1d0)) function meteo::sat_vap_pressice (real(kind(1d0)) Temp_c, real(kind(1d0)) PRESS_hPa, integer from, real(kind(1d0)) dectime)
Definition at line 196 of file suews_util_meteo.f95.
       ! USE time
       ! USE defaultnotUsed
       IMPLICIT NONE
       REAL(KIND(1d0))::e_mb, f, temp_C, press_hpa, press_kpa, es_hPA, dectime!,pw
       INTEGER:: from, iv
       INTEGER, PARAMETER::notUsedI = -55
       !If air temperature between -0.001 -
       IF (abs(temp_c) < 0.001000) THEN
          IF (from == 1) THEN  ! not from determining Tw
             iv = int(press_hpa)
             CALL errorhint(29, 'Function sat_vap_press: temp_C, dectime,press_Hpa = ', temp_c, dectime, iv)
          ENDIF
          temp_c = 0.001000
       ENDIF
       press_kpa = press_hpa/10
       IF (temp_c < 50 .AND. temp_c > -40) THEN
          e_mb = 6.1115*exp(((23.036 - temp_c/333.7)*temp_c)/(temp_c + 279.82))
          f = 1.00022 + press_kpa*(3.83e-6 + 6.4e-10*temp_c**2) !In hPa
          es_hpa = e_mb*f
       ELSE
          CALL errorhint(28, 'FUNCTION sat_vap_press: [Temperature is out of range], Temp_C,dectime', temp_c, dectime, notusedi)
       ENDIF
       RETURN
References errorhint().
Referenced by snow_module::evap_suews_snow().
scale_height()
real(kind(1d0)) function meteo::scale_height (real(kind(1d0)) TK)
Definition at line 128 of file suews_util_meteo.f95.
       REAL(KIND(1d0)) ::TK
       !SCALE HEIGHT FOR DRY ATMOSPHERE IN km BEER (1991)
       scale_height = r_dry_mol*tk/(molmass_air*9.81)
References molmass_air, and r_dry_mol.
Referenced by vaisala_brunt_f().
slope_svp()
real(kind(1d0)) function meteo::slope_svp (real(kind(1d0)) temp_C)
Definition at line 442 of file suews_util_meteo.f95.
       !COEFFICENTS FOR CALCULATING desat/dT
       !Slope of the saturation vapor pressure vst air temperature curve
       IMPLICIT NONE
       REAL(KIND(1d0)):: b1, b2, b3, b4, b5, b6, b7, S_hPa, temp_C
       b1 = 4.438099984d-1
       b2 = 2.857002636d-2
       b3 = 7.938054040d-4
       b4 = 1.215215065d-5
       b5 = 1.036561403d-7
       b6 = 3.532421810d-10
       b7 = -7.090244804d-13
       !     s - slope of saturation vapour pressure curve - Lowe (1977) -T (K)
       !     mb /K
       s_hpa = b1 + temp_c*(b2 + temp_c*(b3 + temp_c*(b4 + temp_c*(b5 + temp_c*(b6 + b7*temp_c)))))
       ! write(*,*)'s',s_hpa,temp_C
       !s_Pa=s_Pa*100  ! Pa/K
       !www.cimis.water.ca.gov/infoEotPmEquation.jsp
       ! s_hPa=(((4099 *(es_hPa/10))/(Temp_C+273.3)**2))*10
       ! if(debug)write(*,*)s_hpa
       RETURN
Referenced by lumps_cal_qhqe().
slopeice_svp()
real(kind(1d0)) function meteo::slopeice_svp (real(kind(1d0)) temp_C)
Definition at line 469 of file suews_util_meteo.f95.
       !COEFFICENTS FOR CALCULATING desat/dT
       !Slope of the saturation vapor pressure vst air temperature curve
       IMPLICIT NONE
       REAL(KIND(1d0)):: b1, b2, b3, b4, b5, b6, b7, S_hPa, temp_C
       b1 = 5.030305237d-1
       b2 = 3.773255020d-2
       b3 = 1.267995369d-3
       b4 = 2.477563108d-5
       b5 = 3.005693132d-7
       b6 = 2.158542548d-9
       b7 = 7.131097725d-12
       ! s - slope of saturation vapour pressure curve - Lowe (1977) -T (K)
       ! mb /K
       s_hpa = b1 + temp_c*(b2 + temp_c*(b3 + temp_c*(b4 + temp_c*(b5 + temp_c*(b6 + b7*temp_c)))))
       RETURN
Referenced by lumps_cal_qhqe().
sos_dryair()
real(kind(1d0)) function meteo::sos_dryair (real(kind(1d0)) TK)
Definition at line 43 of file suews_util_meteo.f95.
       !SPEED OF SOUND IN DRY AIR, BEER (1991)
       REAL(KIND(1d0)) ::TK
       sos_dryair = sqrt(1.4*r_dry_mol*tk/(molmass_air*1000.))
References molmass_air, and r_dry_mol.
spec_heat_beer()
real(kind(1d0)) function meteo::spec_heat_beer (real(kind(1d0)) Temp_C, real(kind(1d0)) rh, real(kind(1d0)) rho_v, real(kind(1d0)) rho_d)
Definition at line 242 of file suews_util_meteo.f95.
       ! Input: Air temperature, relative humidity, water vapour and dry air densities
       ! Output: heat capacity in units J kg-1 K-1
       ! Reference: Tom Beer, CSIRO, 1990. Applied Environmetrics Meteorological Tables.
       ! Can be found from SG:s office from Atmmos Moist map
       !-------------------------------------------------------------------------------
       ! USE defaultnotUsed
       IMPLICIT NONE
       REAL(KIND(1d0))::cp, cpd, cpm, rho_v, rho_d, rh, temp_C
       !Garratt equation a20 (1992)
       cpd = 1005.0 + ((temp_c + 23.16)**2)/3364.0 !Changed from 23.15 to 23.16
       !Beer (1990) for water vapor
       cpm = 1859 + 0.13*rh + (19.3 + 0.569*rh)*(temp_c/100.) + &
             (10.+0.5*rh)*(temp_c/100.)**2
       IF (abs(rho_d) < 0.000100 .OR. abs(rho_v) < 0.000100 .OR. abs(rho_d + rho_v) < 0.000100) THEN
          CALL errorhint(42, 'spec-heat_beer', rho_v, rho_d, int(temp_c))
       ENDIF
       cp = cpd*(rho_d/(rho_d + rho_v)) + cpm*(rho_v/(rho_d + rho_v))
       !   print*,"cp: ",cp,cpd,rho_d,rho_v,cpm,rh
References errorhint().
Referenced by atmmoiststab_module::lumps_cal_atmmoist().
spec_heat_dryair()
real(kind(1d0)) function meteo::spec_heat_dryair (real(kind(1d0)) TK)
Definition at line 71 of file suews_util_meteo.f95.
       ! BEER (1991) APPLIED ENVIRONMETRICS METEOROLOGICAL TABLES
       REAL(KIND(1d0)) ::TK, TC
       tc = tk - 273.15
       spec_heat_dryair = 1005.+((tc + 23.15)**2)/3364.
Referenced by heatcapacity_air().
spec_heat_vapor()
real(kind(1d0)) function meteo::spec_heat_vapor (real(kind(1d0)) TK, real(kind(1d0)) RH)
Definition at line 78 of file suews_util_meteo.f95.
       ! BEER (1991) APPLIED ENVIRONMETRICS METEOROLOGICAL TABLES
       REAL(KIND(1d0)) ::TK, TC_100, RH
       tc_100 = (tk - 273.15)/100.
       spec_heat_vapor = 1859.+0.13*rh + (19.3 + 0.569*rh)*tc_100 + (10.+0.5*rh)*tc_100**2
Referenced by heatcapacity_air().
spec_hum_def()
real(kind(1d0)) function meteo::spec_hum_def (real(kind(1d0)) vpd_hPa, real(kind(1d0)) press_hPa)
Definition at line 233 of file suews_util_meteo.f95.
       ! USE gas
       IMPLICIT NONE
       REAL(KIND(1d0))           :: press_hPa, vpd_hPa, dq
       REAL(KIND(1d0)), PARAMETER :: epsil_gkg = 621.97 !ratio molecular weight of water vapor/dry air in g/kg
       dq = epsil_gkg*vpd_hpa/press_hpa ! Phd Thesis II.13 p 196
Referenced by atmmoiststab_module::lumps_cal_atmmoist().
vaisala_brunt_f()
real(kind(1d0)) function meteo::vaisala_brunt_f (real(kind(1d0)) TK)
Definition at line 134 of file suews_util_meteo.f95.
       !BEER (1991)
       REAL(KIND(1d0)) ::TK
       vaisala_brunt_f = sqrt(0.4/1.4*9.81/scale_height(tk))
References scale_height().
Variable Documentation
avogadro
real(kind(1d0)), parameter meteo::avogadro = 6.02252E23
Definition at line 21 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  AVOGADRO = 6.02252e23              ! AVOGADRO'S NUMBER (molecules/mol)
deg2rad
real(kind(1d0)), parameter meteo::deg2rad = 0.017453292
Definition at line 9 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  DEG2RAD = 0.017453292
epsil
real(kind(1d0)), parameter meteo::epsil = 0.62197
Definition at line 19 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  EPSIL = 0.62197
Referenced by density_vapor().
kb
real(kind(1d0)), parameter meteo::kb = 1.3807E-25
Definition at line 20 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  KB = 1.3807e-25                    ! BOLTZMANN'S CONSTANT (m^3 MB K^-1)=R/A
Referenced by partial_pressure().
molmass_air
real(kind(1d0)), parameter meteo::molmass_air = 0.028965
Definition at line 11 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  MOLMASS_AIR = 0.028965             ! kg for 1 mol dry air
Referenced by scale_height(), and sos_dryair().
molmass_co2
real(kind(1d0)), parameter meteo::molmass_co2 = 0.04401
Definition at line 12 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  MOLMASS_CO2 = 0.04401              ! kg for 1 mol CO2
molmass_h2o
real(kind(1d0)), parameter meteo::molmass_h2o = 0.0180153
Definition at line 13 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  MOLMASS_H2O = 0.0180153            ! kg for 1 mol water vapor
mu_co2
real(kind(1d0)), parameter meteo::mu_co2 = MOLMASS_AIR/MOLMASS_CO2
Definition at line 15 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  MU_CO2 = molmass_air/molmass_co2   ! mol air/mol CO2
mu_h2o
real(kind(1d0)), parameter meteo::mu_h2o = MOLMASS_AIR/MOLMASS_H2O
Definition at line 14 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  MU_H2O = molmass_air/molmass_h2o   ! mol air/mol H2O
r_dry_mass
real(kind(1d0)), parameter meteo::r_dry_mass = R_DRY_MOL/MOLMASS_AIR
Definition at line 17 of file suews_util_meteo.f95.
    REAL(KIND(1D0)), PARAMETER ::  R_DRY_MASS = r_dry_mol/molmass_air ! J/K/kg GAS CONSTANT
Referenced by density_dryair(), density_moist(), and density_vapor().
r_dry_mol
real(kind(1d0)), parameter meteo::r_dry_mol = 8.31451
Definition at line 16 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  R_DRY_MOL = 8.31451                ! J/K/mol gas constant
Referenced by density_gas(), scale_height(), and sos_dryair().
rad2deg
real(kind(1d0)), parameter meteo::rad2deg = 57.29577951
Definition at line 8 of file suews_util_meteo.f95.
    REAL(KIND(1d0)), PARAMETER ::  RAD2DEG = 57.29577951