SUEWS: initialcond Module Reference
initialcond Module Reference
Variables
real(kind(1d0)) laiinitialevetr
real(kind(1d0)) laiinitialdectr
real(kind(1d0)) laiinitialgrass
real(kind(1d0)) porosity0
real(kind(1d0)) decidcap0
real(kind(1d0)) albdectr0
real(kind(1d0)) albevetr0
real(kind(1d0)) albgrass0
real(kind(1d0)) temp_c0
real(kind(1d0)) gdd_1_0
real(kind(1d0)) gdd_2_0
real(kind(1d0)) soilstorepavedstate
real(kind(1d0)) soilstorebldgsstate
real(kind(1d0)) soilstoreevetrstate
real(kind(1d0)) soilstoredectrstate
real(kind(1d0)) soilstoregrassstate
real(kind(1d0)) soilstorebsoilstate
real(kind(1d0)) snowwaterpavedstate
real(kind(1d0)) snowwaterbldgsstate
real(kind(1d0)) snowwaterevetrstate
real(kind(1d0)) snowwaterdectrstate
real(kind(1d0)) snowwatergrassstate
real(kind(1d0)) snowwaterbsoilstate
real(kind(1d0)) snowwaterwaterstate
real(kind(1d0)) snowpackpaved
real(kind(1d0)) snowpackbldgs
real(kind(1d0)) snowpackevetr
real(kind(1d0)) snowpackdectr
real(kind(1d0)) snowpackgrass
real(kind(1d0)) snowpackbsoil
real(kind(1d0)) snowpackwater
real(kind(1d0)) snowalb0
integer id_prev
Variable Documentation
albdectr0
real(kind(1d0)) initialcond::albdectr0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
albevetr0
real(kind(1d0)) initialcond::albevetr0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
albgrass0
real(kind(1d0)) initialcond::albgrass0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
decidcap0
real(kind(1d0)) initialcond::decidcap0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
gdd_1_0
real(kind(1d0)) initialcond::gdd_1_0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
gdd_2_0
real(kind(1d0)) initialcond::gdd_2_0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
id_prev
integer initialcond::id_prev
Definition at line 1623 of file suews_ctrl_const.f95.
    INTEGER::ID_Prev
Referenced by initialstate().
laiinitialdectr
real(kind(1d0)) initialcond::laiinitialdectr
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
laiinitialevetr
real(kind(1d0)) initialcond::laiinitialevetr
Definition at line 1589 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::LAIinitialEveTr, &
                      LAIinitialDecTr, &
                      LAIinitialGrass, &
                      porosity0, &
                      DecidCap0, &
                      albDecTr0, &
                      albEveTr0, &
                      albGrass0, &
                      Temp_C0, &
                      GDD_1_0, &
                      GDD_2_0, &
                      SoilStorePavedState, &
                      SoilStoreBldgsState, &
                      SoilStoreEveTrState, &
                      SoilStoreDecTrstate, &
                      SoilStoreGrassState, &
                      SoilStoreBSoilState, &
                      SnowWaterPavedState, &
                      SnowWaterBldgsState, &
                      SnowWaterEveTrState, &
                      SnowWaterDecTrState, &
                      SnowWaterGrassState, &
                      SnowWaterBSoilState, &
                      SnowWaterWaterstate, &
                      SnowPackPaved, &
                      SnowPackBldgs, &
                      SnowPackEveTr, &
                      SnowPackDecTr, &
                      SnowPackGrass, &
                      SnowPackBSoil, &
                      SnowPackWater, &
                      SnowAlb0!,&
Referenced by checkinitial(), and initialstate().
laiinitialgrass
real(kind(1d0)) initialcond::laiinitialgrass
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
porosity0
real(kind(1d0)) initialcond::porosity0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
snowalb0
real(kind(1d0)) initialcond::snowalb0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
snowpackbldgs
real(kind(1d0)) initialcond::snowpackbldgs
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowpackbsoil
real(kind(1d0)) initialcond::snowpackbsoil
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowpackdectr
real(kind(1d0)) initialcond::snowpackdectr
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowpackevetr
real(kind(1d0)) initialcond::snowpackevetr
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowpackgrass
real(kind(1d0)) initialcond::snowpackgrass
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowpackpaved
real(kind(1d0)) initialcond::snowpackpaved
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowpackwater
real(kind(1d0)) initialcond::snowpackwater
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
snowwaterbldgsstate
real(kind(1d0)) initialcond::snowwaterbldgsstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowwaterbsoilstate
real(kind(1d0)) initialcond::snowwaterbsoilstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowwaterdectrstate
real(kind(1d0)) initialcond::snowwaterdectrstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowwaterevetrstate
real(kind(1d0)) initialcond::snowwaterevetrstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowwatergrassstate
real(kind(1d0)) initialcond::snowwatergrassstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowwaterpavedstate
real(kind(1d0)) initialcond::snowwaterpavedstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
snowwaterwaterstate
real(kind(1d0)) initialcond::snowwaterwaterstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by initialstate().
soilstorebldgsstate
real(kind(1d0)) initialcond::soilstorebldgsstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
soilstorebsoilstate
real(kind(1d0)) initialcond::soilstorebsoilstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
soilstoredectrstate
real(kind(1d0)) initialcond::soilstoredectrstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
soilstoreevetrstate
real(kind(1d0)) initialcond::soilstoreevetrstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
soilstoregrassstate
real(kind(1d0)) initialcond::soilstoregrassstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
soilstorepavedstate
real(kind(1d0)) initialcond::soilstorepavedstate
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().
temp_c0
real(kind(1d0)) initialcond::temp_c0
Definition at line 1589 of file suews_ctrl_const.f95.
Referenced by checkinitial(), and initialstate().