SUEWS: sues_data Module Reference
sues_data Module Reference
Variables
integer tstep
integer tstep_prev
integer nsh
integer nsd
integer nsdorig
integer t_interval
integer nper
integer nperestm
real(kind(1d0)) nsh_real
real(kind(1d0)) tstep_real
real(kind(1d0)) nper_real
real(kind(1d0)) nperestm_real
real(kind(1d0)) halftimestep
integer stabilitymethod
integer roughlenheatmethod
integer in
integer is
integer aerodynamicresistancemethod = 2
integer ie_start
integer ie_end
real(kind(1d0)), dimension(2) surplusevap
real(kind(1d0)) flowchange
real(kind(1d0)) pipecapacity
real(kind(1d0)) runofftowater
real(kind(1d0)) smcap
real(kind(1d0)) soildensity
real(kind(1d0)) soildepthmeas
real(kind(1d0)) soilrocks
real(kind(1d0)) surfacearea
real(kind(1d0)) surfacearea_ha
real(kind(1d0)) waterbodytype
real(kind(1d0)) waterstorcap
real(kind(1d0)) wuareaevetr_m2
real(kind(1d0)) wuareadectr_m2
real(kind(1d0)) wuareagrass_m2
real(kind(1d0)) wuareatotal_m2
real(kind(1d0)) wu_evetr
real(kind(1d0)) wu_dectr
real(kind(1d0)) wu_grass
real(kind(1d0)) additionalwater
real(kind(1d0)) ch_per_interval
real(kind(1d0)) chsnow_per_interval
real(kind(1d0)) di_dt
real(kind(1d0)) dr_per_interval
real(kind(1d0)) ev_per_interval
real(kind(1d0)) surf_chang_per_tstep
real(kind(1d0)) tot_chang_per_tstep
real(kind(1d0)) nwstate_per_tstep
real(kind(1d0)) state_per_tstep
real(kind(1d0)) drain_per_tstep
real(kind(1d0)) runoff_per_tstep
real(kind(1d0)) runoffsoil_per_tstep
real(kind(1d0)) ev_per_tstep
real(kind(1d0)) qe_per_tstep
real(kind(1d0)) p_mm
real(kind(1d0)) pin
real(kind(1d0)) planf
real(kind(1d0)) rb
real(kind(1d0)) runoffagimpervious
real(kind(1d0)) runoffagveg
real(kind(1d0)) runoffwaterbody
real(kind(1d0)) runoffpipes
real(kind(1d0)) runoffagimpervious_m3
real(kind(1d0)) runoffagveg_m3
real(kind(1d0)) runoffwaterbody_m3
real(kind(1d0)) runoffpipes_m3
real(kind(1d0)) runoff_per_interval
real(kind(1d0)) addimpervious
real(kind(1d0)) addveg
real(kind(1d0)) addwaterbody
real(kind(1d0)) addpipes
real(kind(1d0)) runoffsoil_per_interval
real(kind(1d0)) qe_per_interval
real(kind(1d0)) soilmoistcap
real(kind(1d0)) soilstate
real(kind(1d0)) st_per_interval
real(kind(1d0)) surpluswaterbody
real(kind(1d0)) tlv_sub
real(kind(1d0)) overuse = 0
real(kind(1d0)) zh
real(kind(1d0)) h
real(kind(1d0)) l_mod
real(kind(1d0)) psim
real(kind(1d0)) psyh
real(kind(1d0)) ra
real(kind(1d0)) rasnow
real(kind(1d0)) tstar
real(kind(1d0)) ustar
real(kind(1d0)) z0_gis
real(kind(1d0)) resistsurf
real(kind(1d0)) gdq
real(kind(1d0)) qnm
real(kind(1d0)) gq
real(kind(1d0)) gtemp
real(kind(1d0)) gl
real(kind(1d0)) sdp
real(kind(1d0)) smd
real(kind(1d0)) vsmd
real(kind(1d0)) gs
real(kind(1d0)) gsc
real(kind(1d0)) rss
real(kind(1d0)) vdrc
real(kind(1d0)) numpm
real(kind(1d0)) sp
real(kind(1d0)) sae
real(kind(1d0)) ev
real(kind(1d0)) rst
real(kind(1d0)) qeph
real(kind(1d0)) qeout
real(kind(1d0)), dimension(:), allocatable qhforcbl
real(kind(1d0)), dimension(:), allocatable qeforcbl
integer qh_choice
real(kind(1d0)) ext_wu
real(kind(1d0)) faut
real(kind(1d0)) int_wu
real(kind(1d0)) irrfracconif
real(kind(1d0)) irrfracdecid
real(kind(1d0)) irrfracgrass
real(kind(1d0)) internalwateruse_h
real(kind(1d0)), dimension(7) daywatper
real(kind(1d0)), dimension(7) daywat
real(kind(1d0)), dimension(0:23, 2) wuprofm_24hr
real(kind(1d0)), dimension(0:23, 2) wuprofa_24hr
real(kind(1d0)), dimension(3) ie_a
real(kind(1d0)), dimension(3) ie_m
Variable Documentation
addimpervious
real(kind(1d0)) sues_data::addimpervious
Definition at line 1476 of file suews_ctrl_const.f95.
additionalwater
real(kind(1d0)) sues_data::additionalwater
Definition at line 1476 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::AdditionalWater, &     !Water flow from other grids
                      ch_per_interval, &     !Change in state per interval
                      chSnow_per_interval, & !Change in snow state per interval
                      dI_dt, &               !Water flow between two stores
                      dr_per_interval, &     !Drainage per interval
                      ev_per_interval, &     !Evaporation per interval
                      surf_chang_per_tstep, & !Change in surface state per timestep [mm] (for whole surface)
                      tot_chang_per_tstep, &  !Change in surface and SoilState per timestep [mm] (for whole surface)
                      NWstate_per_tstep, &     !State per timestep [mm] (for whole surface, excluding water body)
                      state_per_tstep, &     !State per timestep [mm] (for whole surface)
                      drain_per_tstep, &     !Drainage per timestep [mm] (for whole surface, excluding water body)
                      runoff_per_tstep, &     !Runoff per timestep [mm] (for whole surface)
                      runoffSoil_per_tstep, & !Runoff to deep soil per timestep [mm] (for whole surface, excluding water body)
                      ev_per_tstep, &     !Evaporation per timestep [mm] (for whole surface)
                      qe_per_tstep, &     !QE [W m-2] (for whole surface)
                      p_mm, &                !Inputs to surface water balance
                      pin, &                 !Rain per time interval
                      planF, &               !Areally weighted frontal area fraction
                      rb, &                  !Boundary layer resistance
                      ! Water leaving each grid for grid-to-grid connectivity
                      runoffagimpervious, &     !Above ground runoff from impervious surface [mm] for whole surface area
                      runoffagveg, &            !Above ground runoff from vegetated surfaces [mm] for whole surface area
                      runoffwaterbody, &        !Above ground runoff from water surface [mm] for whole surface area
                      runoffpipes, &            !Runoff in pipes [mm] for whole surface area
                      runoffagimpervious_m3, &  !Volume of above ground runoff from impervious surface [m3]
                      runoffagveg_m3, &         !Volume of above ground runoff from vegetated surfaces [m3]
                      runoffwaterbody_m3, &     !Volume of above ground runoff from water surface [m3]
                      runoffpipes_m3, &         !Volume of runoff in pipes [m3]
                      runoff_per_interval, &  ! Total water transported to each grid for grid-to-grid connectivity
                      addimpervious, &      !Water from impervious surfaces of other grids [mm] for whole surface area
                      addveg, &             !Water from vegetated surfaces of other grids [mm] for whole surface area
                      addwaterbody, &       !Water from water surface of other grids [mm] for whole surface area
                      addpipes, &           !Water in pipes from other grids [mm] for whole surface area
                      runoffsoil_per_interval, &
                      qe_per_interval, &     !latent heat per interval
                      soilmoistcap, &
                      soilstate, &        !Area-averaged soil moisture [mm] for whole surface
                      st_per_interval, &!Surface state per interval
                      surpluswaterbody, &  !Extra runoff that goes to water body [mm] as specified by RunoffToWater
                      tlv_sub, &
                      overuse = 0, &
                      zh               !Areally weighted roughness element height
addpipes
real(kind(1d0)) sues_data::addpipes
Definition at line 1476 of file suews_ctrl_const.f95.
addveg
real(kind(1d0)) sues_data::addveg
Definition at line 1476 of file suews_ctrl_const.f95.
addwaterbody
real(kind(1d0)) sues_data::addwaterbody
Definition at line 1476 of file suews_ctrl_const.f95.
aerodynamicresistancemethod
integer sues_data::aerodynamicresistancemethod = 2
Definition at line 1447 of file suews_ctrl_const.f95.
    INTEGER::AerodynamicResistanceMethod = 2 !The method used to calculate aerodynamic resistance
Referenced by suews_calculations().
ch_per_interval
real(kind(1d0)) sues_data::ch_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
chsnow_per_interval
real(kind(1d0)) sues_data::chsnow_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
daywat
real(kind(1d0)), dimension(7) sues_data::daywat
Definition at line 1567 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
daywatper
real(kind(1d0)), dimension(7) sues_data::daywatper
Definition at line 1567 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(7)::DayWatPer, &  !% of houses following daily water
                                    DayWat       !Days of watering allowed
Referenced by initialstate(), suews_calculations(), and suews_translate().
di_dt
real(kind(1d0)) sues_data::di_dt
Definition at line 1476 of file suews_ctrl_const.f95.
dr_per_interval
real(kind(1d0)) sues_data::dr_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
drain_per_tstep
real(kind(1d0)) sues_data::drain_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
ev
real(kind(1d0)) sues_data::ev
Definition at line 1545 of file suews_ctrl_const.f95.
ev_per_interval
real(kind(1d0)) sues_data::ev_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
ev_per_tstep
real(kind(1d0)) sues_data::ev_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
ext_wu
real(kind(1d0)) sues_data::ext_wu
Definition at line 1558 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: ext_wu, &         !External water use for the model timestep [mm] (over whole study area)
                      Faut, &           !Fraction of irrigated area using automatic irrigation
                      int_wu, &         !Internal water use for the model timestep [mm] (over whole study area)
                      IrrFracConif, &  !Fraction of evergreen trees which are irrigated
                      IrrFracDecid, &  !Fraction of deciduous trees which are irrigated
                      IrrFracGrass, &  !Fraction of grass which is irrigated
                      InternalWaterUse_h !Internal water use [mm h-1]
faut
real(kind(1d0)) sues_data::faut
Definition at line 1558 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
flowchange
real(kind(1d0)) sues_data::flowchange
Definition at line 1456 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::FlowChange, &         !Difference between the input and output flow in the water body
                      PipeCapacity, &       !Capacity of pipes to transfer water
                      RunoffToWater, &      !Fraction of surface runoff going to water body
                      SmCap, &              !Volumetric/gravimetric soil moisture capacity
                      SoilDensity, &        !Bulk density of soil
                      SoilDepthMeas, &      !Soil depth of the measured soil moisture
                      SoilRocks, &          !Fraction of rocks in soil
                      SurfaceArea, &        !Surface area of the study area [m2]
                      SurfaceArea_ha, &     !Surface area of the study area [ha]
                      WaterBodyType, &      !If water body type is pond/lake (=1) or river (=2)
                      WaterStorCap, &       !Capacity of water body when surface is wet
                      WUAreaEveTr_m2, &     !Water use area (evergreen trees) [m2]
                      WUAreaDecTr_m2, &     !Water use area (deciduous trees) [m2]
                      WUAreaGrass_m2, &     !Water use area (grass) [m2]
                      WUAreaTotal_m2, &     !Water use area (total) [m2]
                      wu_EveTr, &              !Water use for evergreen trees/shrubs [mm]
                      wu_DecTr, &              !Water use for deciduous trees/shrubs [mm]
                      wu_Grass                !Water use for grass [mm]
Referenced by suews_calculations(), and suews_translate().
gdq
real(kind(1d0)) sues_data::gdq
Definition at line 1531 of file suews_ctrl_const.f95.
gl
real(kind(1d0)) sues_data::gl
Definition at line 1531 of file suews_ctrl_const.f95.
gq
real(kind(1d0)) sues_data::gq
Definition at line 1531 of file suews_ctrl_const.f95.
gs
real(kind(1d0)) sues_data::gs
Definition at line 1531 of file suews_ctrl_const.f95.
gsc
real(kind(1d0)) sues_data::gsc
Definition at line 1531 of file suews_ctrl_const.f95.
gtemp
real(kind(1d0)) sues_data::gtemp
Definition at line 1531 of file suews_ctrl_const.f95.
h
real(kind(1d0)) sues_data::h
Definition at line 1520 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::H, &          !Kinematic sensible heat flux [K m s-1] used to calculate friction velocity
                      l_mod, &      !Monin-Obukhov length (either measured or modelled)
                      psim, &       !Stability function of momentum
                      psyh, &       !Stability function of heat
                      RA, &         !Aerodynamic resistance
                      RAsnow, &     !Aerodynamic resistance over snow
                      TStar, &      !T*
                      UStar, &      !Friction velocity
                      z0_gis       !Roughness length for momentum from gis input file
halftimestep
real(kind(1d0)) sues_data::halftimestep
Definition at line 1437 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: halftimestep   !In decimal time based on interval
Referenced by metdisagg::disaggregatemet(), and overallruncontrol().
ie_a
real(kind(1d0)), dimension(3) sues_data::ie_a
Definition at line 1572 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(3)::Ie_a, Ie_m   !Coefficients for automatic and manual irrigation models
Referenced by initialstate(), suews_calculations(), and suews_translate().
ie_end
integer sues_data::ie_end
Definition at line 1449 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
ie_m
real(kind(1d0)), dimension(3) sues_data::ie_m
Definition at line 1572 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
ie_start
integer sues_data::ie_start
Definition at line 1449 of file suews_ctrl_const.f95.
    INTEGER::Ie_start, &   !Starting time of water use (DOY)
              Ie_end       !Ending time of water use (DOY)
Referenced by initialstate(), suews_calculations(), and suews_translate().
in
integer sues_data::in
Definition at line 1443 of file suews_ctrl_const.f95.
    INTEGER:: in
int_wu
real(kind(1d0)) sues_data::int_wu
Definition at line 1558 of file suews_ctrl_const.f95.
internalwateruse_h
real(kind(1d0)) sues_data::internalwateruse_h
Definition at line 1558 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
irrfracconif
real(kind(1d0)) sues_data::irrfracconif
Definition at line 1558 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
irrfracdecid
real(kind(1d0)) sues_data::irrfracdecid
Definition at line 1558 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
irrfracgrass
real(kind(1d0)) sues_data::irrfracgrass
Definition at line 1558 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
is
integer sues_data::is
Definition at line 1444 of file suews_ctrl_const.f95.
    INTEGER:: is      !Integer to count over surface types
Referenced by bluews_module::cbl(), and bluews_module::cbl_initial().
l_mod
real(kind(1d0)) sues_data::l_mod
Definition at line 1520 of file suews_ctrl_const.f95.
nper
integer sues_data::nper
Definition at line 1425 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), and suews_program().
nper_real
real(kind(1d0)) sues_data::nper_real
Definition at line 1433 of file suews_ctrl_const.f95.
Referenced by suews_program().
nperestm
integer sues_data::nperestm
Definition at line 1425 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), and suews_program().
nperestm_real
real(kind(1d0)) sues_data::nperestm_real
Definition at line 1433 of file suews_ctrl_const.f95.
Referenced by suews_program().
nsd
integer sues_data::nsd
Definition at line 1425 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), metdisagg::disaggregatemet(), overallruncontrol(), and suews_program().
nsdorig
integer sues_data::nsdorig
Definition at line 1425 of file suews_ctrl_const.f95.
Referenced by suews_program().
nsh
integer sues_data::nsh
Definition at line 1425 of file suews_ctrl_const.f95.
Referenced by initialstate(), overallruncontrol(), ctrl_output::suews_output_agg(), ctrl_output::suews_output_nc_grp(), ctrl_output::suews_output_txt_grp(), and suews_program().
nsh_real
real(kind(1d0)) sues_data::nsh_real
Definition at line 1433 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: nsh_real, &   !nsh cast as a real for use in calculations
                      tstep_real, &   !tstep cast as a real for use in calculations
                      Nper_real, NperESTM_real   !Nper as real
Referenced by bluews_module::cbl(), nextinitial(), and overallruncontrol().
numpm
real(kind(1d0)) sues_data::numpm
Definition at line 1545 of file suews_ctrl_const.f95.
nwstate_per_tstep
real(kind(1d0)) sues_data::nwstate_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
overuse
real(kind(1d0)) sues_data::overuse = 0
Definition at line 1476 of file suews_ctrl_const.f95.
p_mm
real(kind(1d0)) sues_data::p_mm
Definition at line 1476 of file suews_ctrl_const.f95.
pin
real(kind(1d0)) sues_data::pin
Definition at line 1476 of file suews_ctrl_const.f95.
pipecapacity
real(kind(1d0)) sues_data::pipecapacity
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
planf
real(kind(1d0)) sues_data::planf
Definition at line 1476 of file suews_ctrl_const.f95.
Referenced by initialstate().
psim
real(kind(1d0)) sues_data::psim
Definition at line 1520 of file suews_ctrl_const.f95.
psyh
real(kind(1d0)) sues_data::psyh
Definition at line 1520 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
qe_per_interval
real(kind(1d0)) sues_data::qe_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
qe_per_tstep
real(kind(1d0)) sues_data::qe_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
qeforcbl
real(kind(1d0)), dimension(:), allocatable sues_data::qeforcbl
Definition at line 1554 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
qeout
real(kind(1d0)) sues_data::qeout
Definition at line 1545 of file suews_ctrl_const.f95.
qeph
real(kind(1d0)) sues_data::qeph
Definition at line 1545 of file suews_ctrl_const.f95.
qh_choice
integer sues_data::qh_choice
Definition at line 1555 of file suews_ctrl_const.f95.
    INTEGER:: qh_choice        ! selection of qh use to drive CBL growth 1=Suews 2=lumps 3=obs
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::cbl_readinputdata(), and bluews_module::nbl().
qhforcbl
real(kind(1d0)), dimension(:), allocatable sues_data::qhforcbl
Definition at line 1554 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: qhforCBL, qeforCBL   ! Stores previous timestep qh and qe for CBL model. Added by HCW 21 Mar 2017
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
qnm
real(kind(1d0)) sues_data::qnm
Definition at line 1531 of file suews_ctrl_const.f95.
ra
real(kind(1d0)) sues_data::ra
Definition at line 1520 of file suews_ctrl_const.f95.
rasnow
real(kind(1d0)) sues_data::rasnow
Definition at line 1520 of file suews_ctrl_const.f95.
rb
real(kind(1d0)) sues_data::rb
Definition at line 1476 of file suews_ctrl_const.f95.
resistsurf
real(kind(1d0)) sues_data::resistsurf
Definition at line 1531 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::resistsurf, & !Surface resistance
                      gdq, &        !G(dq)
                      qnm, &        !QMAX/(QMAX+G2)
                      gq, &         !G(Q*)
                      gtemp, &      !G(T)
                      gl, &         !G(LAI)
                      sdp, &        !S1/G6+S2
                      smd, &        !Soil moisture deficit of the soil surface layer
                      vsmd, &       !Soil moisture deficit for vegetated surfaces only (QUESTION: what about BSoil?)
                      gs, &         !G(Soil moisture deficit)
                      gsc, &        !Surface Layer Conductance
                      rss          !Surface resistance after wet/partially wet adjustment
roughlenheatmethod
integer sues_data::roughlenheatmethod
Definition at line 1440 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_calculations().
rss
real(kind(1d0)) sues_data::rss
Definition at line 1531 of file suews_ctrl_const.f95.
rst
real(kind(1d0)) sues_data::rst
Definition at line 1545 of file suews_ctrl_const.f95.
runoff_per_interval
real(kind(1d0)) sues_data::runoff_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
runoff_per_tstep
real(kind(1d0)) sues_data::runoff_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
runoffagimpervious
real(kind(1d0)) sues_data::runoffagimpervious
Definition at line 1476 of file suews_ctrl_const.f95.
runoffagimpervious_m3
real(kind(1d0)) sues_data::runoffagimpervious_m3
Definition at line 1476 of file suews_ctrl_const.f95.
runoffagveg
real(kind(1d0)) sues_data::runoffagveg
Definition at line 1476 of file suews_ctrl_const.f95.
runoffagveg_m3
real(kind(1d0)) sues_data::runoffagveg_m3
Definition at line 1476 of file suews_ctrl_const.f95.
runoffpipes
real(kind(1d0)) sues_data::runoffpipes
Definition at line 1476 of file suews_ctrl_const.f95.
runoffpipes_m3
real(kind(1d0)) sues_data::runoffpipes_m3
Definition at line 1476 of file suews_ctrl_const.f95.
runoffsoil_per_interval
real(kind(1d0)) sues_data::runoffsoil_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
runoffsoil_per_tstep
real(kind(1d0)) sues_data::runoffsoil_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
runofftowater
real(kind(1d0)) sues_data::runofftowater
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
runoffwaterbody
real(kind(1d0)) sues_data::runoffwaterbody
Definition at line 1476 of file suews_ctrl_const.f95.
runoffwaterbody_m3
real(kind(1d0)) sues_data::runoffwaterbody_m3
Definition at line 1476 of file suews_ctrl_const.f95.
sae
real(kind(1d0)) sues_data::sae
Definition at line 1545 of file suews_ctrl_const.f95.
sdp
real(kind(1d0)) sues_data::sdp
Definition at line 1531 of file suews_ctrl_const.f95.
smcap
real(kind(1d0)) sues_data::smcap
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), suews_initializemetdata(), and suews_translate().
smd
real(kind(1d0)) sues_data::smd
Definition at line 1531 of file suews_ctrl_const.f95.
soildensity
real(kind(1d0)) sues_data::soildensity
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), suews_initializemetdata(), and suews_translate().
soildepthmeas
real(kind(1d0)) sues_data::soildepthmeas
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), suews_initializemetdata(), and suews_translate().
soilmoistcap
real(kind(1d0)) sues_data::soilmoistcap
Definition at line 1476 of file suews_ctrl_const.f95.
soilrocks
real(kind(1d0)) sues_data::soilrocks
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), suews_initializemetdata(), and suews_translate().
soilstate
real(kind(1d0)) sues_data::soilstate
Definition at line 1476 of file suews_ctrl_const.f95.
sp
real(kind(1d0)) sues_data::sp
Definition at line 1545 of file suews_ctrl_const.f95.
st_per_interval
real(kind(1d0)) sues_data::st_per_interval
Definition at line 1476 of file suews_ctrl_const.f95.
stabilitymethod
integer sues_data::stabilitymethod
Definition at line 1440 of file suews_ctrl_const.f95.
    INTEGER:: StabilityMethod, &   !Defines stability functions used (set in RunControl)
              RoughLenHeatMethod     !Defines method for calculating roughness length for heat (set in RunControl)
Referenced by overallruncontrol(), and suews_calculations().
state_per_tstep
real(kind(1d0)) sues_data::state_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
surf_chang_per_tstep
real(kind(1d0)) sues_data::surf_chang_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
surfacearea
real(kind(1d0)) sues_data::surfacearea
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
surfacearea_ha
real(kind(1d0)) sues_data::surfacearea_ha
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by suews_translate().
surplusevap
real(kind(1d0)), dimension(2) sues_data::surplusevap
Definition at line 1452 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(2):: SurplusEvap !Surplus for evaporation in 5 min timestep
surpluswaterbody
real(kind(1d0)) sues_data::surpluswaterbody
Definition at line 1476 of file suews_ctrl_const.f95.
t_interval
integer sues_data::t_interval
Definition at line 1425 of file suews_ctrl_const.f95.
Referenced by overallruncontrol().
tlv_sub
real(kind(1d0)) sues_data::tlv_sub
Definition at line 1476 of file suews_ctrl_const.f95.
tot_chang_per_tstep
real(kind(1d0)) sues_data::tot_chang_per_tstep
Definition at line 1476 of file suews_ctrl_const.f95.
tstar
real(kind(1d0)) sues_data::tstar
Definition at line 1520 of file suews_ctrl_const.f95.
tstep
integer sues_data::tstep
Definition at line 1425 of file suews_ctrl_const.f95.
    INTEGER:: tstep, &    !Timestep [s] at which the model is run (set in RunControl)
              tstep_prev, &    !Timestep [s] of previous timestamp !NB: not used by SUEWS, but by WRF-SUEWS for adaptive time step
              nsh, &      !Number of timesteps per hour
              nsd, &      !Number of timesteps per day
              nsdorig, &  !Number of timesteps per day for original met forcing file
              t_interval, &   !Number of seconds in an hour [s] (now set in OverallRunControl)
              Nper, NperESTM   ! Number of model time-steps per input resolution (ResolutionFilesIn/Tstep)
Referenced by bluews_module::cbl(), metdisagg::disaggregateestm(), metdisagg::disaggregatemet(), overallruncontrol(), suews_calculations(), estm_module::suews_getestmdata(), suews_initializemetdata(), ctrl_output::suews_output(), and suews_program().
tstep_prev
integer sues_data::tstep_prev
Definition at line 1425 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_calculations().
tstep_real
real(kind(1d0)) sues_data::tstep_real
Definition at line 1433 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), estm_module::suews_getestmdata(), and suews_initializemetdata().
ustar
real(kind(1d0)) sues_data::ustar
Definition at line 1520 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
vdrc
real(kind(1d0)) sues_data::vdrc
Definition at line 1545 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  vdrc, &     !Second term up in calculation of E
                      numPM, &    !Numerator of PM equation
                      sp, &       !Term in calculation of E
                      sae, &      !Same
                      ev, &       !Evaporation
                      rst, &      !Flag in SUEWS_Evap (gets set to 1 if surface dry; 0 if surface wet)
                      qeph, &     !Latent heat flux (W m^-2)
                      qeOut      !Latent heat flux [W m-2]
vsmd
real(kind(1d0)) sues_data::vsmd
Definition at line 1531 of file suews_ctrl_const.f95.
waterbodytype
real(kind(1d0)) sues_data::waterbodytype
Definition at line 1456 of file suews_ctrl_const.f95.
waterstorcap
real(kind(1d0)) sues_data::waterstorcap
Definition at line 1456 of file suews_ctrl_const.f95.
wu_dectr
real(kind(1d0)) sues_data::wu_dectr
Definition at line 1456 of file suews_ctrl_const.f95.
wu_evetr
real(kind(1d0)) sues_data::wu_evetr
Definition at line 1456 of file suews_ctrl_const.f95.
wu_grass
real(kind(1d0)) sues_data::wu_grass
Definition at line 1456 of file suews_ctrl_const.f95.
wuareadectr_m2
real(kind(1d0)) sues_data::wuareadectr_m2
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by suews_translate().
wuareaevetr_m2
real(kind(1d0)) sues_data::wuareaevetr_m2
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by suews_translate().
wuareagrass_m2
real(kind(1d0)) sues_data::wuareagrass_m2
Definition at line 1456 of file suews_ctrl_const.f95.
Referenced by suews_translate().
wuareatotal_m2
real(kind(1d0)) sues_data::wuareatotal_m2
Definition at line 1456 of file suews_ctrl_const.f95.
wuprofa_24hr
real(kind(1d0)), dimension(0:23, 2) sues_data::wuprofa_24hr
Definition at line 1569 of file suews_ctrl_const.f95.
wuprofm_24hr
real(kind(1d0)), dimension(0:23, 2) sues_data::wuprofm_24hr
Definition at line 1569 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: WUProfM_24hr, &   !Hourly profiles for water use (manual irrigation)
                                          WUProfA_24hr   !Hourly profiles for water use (automatic irrigation)
z0_gis
real(kind(1d0)) sues_data::z0_gis
Definition at line 1520 of file suews_ctrl_const.f95.
zh
real(kind(1d0)) sues_data::zh
Definition at line 1476 of file suews_ctrl_const.f95.
Referenced by initialstate().