SUEWS: atmmoiststab_module Module Reference
atmmoiststab_module Module Reference
Functions/Subroutines
subroutine lumps_cal_atmmoist (Temp_C, Press_hPa, avRh, dectime, lv_J_kg, lvS_J_kg, es_hPa, Ea_hPa, VPd_hpa, VPD_Pa, dq, dens_dry, avcp, air_dens)
subroutine stab_lumps (StabilityMethod, dectime, zzd, z0m, zdm, avU1, Temp_C, H_init, L_MOD, TStar, UStar, zL)
real(kind(1d0)) function stab_fn_mom (StabilityMethod, ZL, zl_f)
real(kind(1d0)) function stab_phi_mom (StabilityMethod, ZL, zl_f)
real(kind(1d0)) function stab_fn_heat (StabilityMethod, ZL, zl_f)
real(kind(1d0)) function stab_fn_rou (z, zstar)
Function/Subroutine Documentation
lumps_cal_atmmoist()
subroutine atmmoiststab_module::lumps_cal_atmmoist (real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), intent(in) avRh, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(out) lv_J_kg, real(kind(1d0)), intent(out) lvS_J_kg, real(kind(1d0)), intent(out) es_hPa, real(kind(1d0)), intent(out) Ea_hPa, real(kind(1d0)), intent(out) VPd_hpa, real(kind(1d0)), intent(out) VPD_Pa, real(kind(1d0)), intent(out) dq, real(kind(1d0)), intent(out) dens_dry, real(kind(1d0)), intent(out) avcp, real(kind(1d0)), intent(out) air_dens)
Definition at line 12 of file suews_phys_atmmoiststab.f95.
       USE meteo, ONLY: &
          sat_vap_press_x, spec_heat_beer, &
          lat_vap, lat_vapsublim, spec_hum_def
       IMPLICIT NONE
       REAL(KIND(1d0))::vap_dens
       REAL(KIND(1d0)), INTENT(in):: &
          temp_c, &
          press_hpa, &
          avrh, dectime
       REAL(KIND(1d0)), INTENT(out):: &
          lv_j_kg, &!Latent heat of vaporization in [J kg-1]
          lvs_j_kg, &!Latent heat of sublimation in J/kg
          es_hpa, &!Saturation vapour pressure over water in hPa
          ea_hpa, &!Vapour pressure of water in hPa
          vpd_hpa, & !vapour pressure deficit in hPa
          vpd_pa, & !vapour pressure deficit in Pa
          dq, &!Specific humidity deficit in g/kg
          dens_dry, & !Vap density or absolute humidity         (kg/m3)
          avcp, &!specific heat capacity in J kg-1 K-1
          air_dens!Air density in kg/m3
       REAL(KIND(1d0)), PARAMETER:: &
          !  comp          = 0.9995, &
          !  epsil         = 0.62197,&           !ratio molecular weight of water vapor/dry air (kg/mol/kg/mol)
          !  epsil_gkg     = 621.97, &           !ratio molecular weight of water vapor/dry air in g/kg
          !  dry_gas       = 8.31451,&           !Dry gas constant (J/k/mol)
          !  gas_ct_wat    = 461.05,&            !Gas constant for water (J/kg/K)
          !  molar         = 0.028965,&          !Dry air molar fraction in kg/mol
          !  molar_wat_vap = 0.0180153,&         !Molar fraction of water vapor in kg/mol
          gas_ct_dry = 8.31451/0.028965, &  !j/kg/k=dry_gas/molar
          gas_ct_wv = 8.31451/0.0180153 !j/kg/kdry_gas/molar_wat_vap
       !  waterDens     = 999.8395            !Density of water in 0 cel deg
       INTEGER::from = 1
       !Saturation vapour pressure over water in hPa
       es_hpa = sat_vap_press_x(temp_c, press_hpa, from, dectime) ! dectime is more or less unnecessary here
       !Vapour pressure of water in hPa
       ea_hpa = avrh/100*es_hpa
       ! if(debug.and.dectime>55.13.and.dectime<55.2)write(35,*)'%',Temp_C
       vpd_hpa = es_hpa - ea_hpa           !vapour pressure deficit in hPa
       vpd_pa = (es_hpa*100) - (ea_hpa*100)!vapour pressure deficit in Pa
       dq = spec_hum_def(vpd_hpa, press_hpa) !Specific humidity deficit in g/kg
       !Vap density or absolute humidity         (kg/m3)
       vap_dens = (ea_hpa*100/((temp_c + 273.16)*gas_ct_wv))
       !density Dry Air Beer(1990)        kg/m3
       dens_dry = ((press_hpa - ea_hpa)*100)/(gas_ct_dry*(273.16 + temp_c))
       !Air density in kg/m3
       air_dens = (press_hpa*100)/(gas_ct_dry*(temp_c + 273.16))
       !Calculate specific heat capacity in J kg-1 K-1
       avcp = spec_heat_beer(temp_c, avrh, vap_dens, dens_dry)
       !Latent heat of vaporization in [J kg-1]
       lv_j_kg = lat_vap(temp_c, ea_hpa, press_hpa, avcp, dectime)
       !Latent heat of sublimation in J/kg
       IF (temp_c < 0.000) THEN
          lvs_j_kg = lat_vapsublim(temp_c, ea_hpa, press_hpa, avcp)
       ELSE
          lvs_j_kg = 2834000
       ENDIF
       !if(debug)write(*,*)lv_J_kg,Temp_C,'lv2'
       IF (press_hpa < 900) THEN
          CALL errorhint(46, 'Function LUMPS_cal_AtmMoist', press_hpa, -55.55d0, -55)
       ENDIF
       RETURN
References errorhint(), meteo::lat_vap(), meteo::lat_vapsublim(), meteo::sat_vap_press_x(), meteo::spec_heat_beer(), and meteo::spec_hum_def().
Referenced by suews_driver::suews_cal_biogenco2(), and suews_driver::suews_cal_main().
stab_fn_heat()
real(kind(1d0)) function atmmoiststab_module::stab_fn_heat (integer StabilityMethod, real(kind(1d0)) ZL, real(kind(1d0)) zl_f)
Definition at line 389 of file suews_phys_atmmoiststab.f95.
       ! USE mod_k
       IMPLICIT NONE
       REAL(KIND(1d0)), PARAMETER :: &
          !  k=0.4,&             !Von Karman's contant
          !  k2=0.16,&           !Power of Van Karman's contant
          neut_limit = 0.001000 !Limit for neutral stability
       !  notUsedI=-55
       REAL(KIND(1d0)):: zl, zl_f, psyh, x
       INTEGER :: StabilityMethod
       IF (abs(zl) < neut_limit) THEN      !Neutral
          psyh = 0
       ELSEIF (zl < -neut_limit) THEN     ! Unstable
          IF (stabilitymethod == 3) THEN
             !campbell & norman eqn 7.26
             psyh = 0.6*(2)*log((1 + (1 - 16*zl_f)**0.5)/2)
          ELSE
             IF (stabilitymethod == 4) THEN ! Businger et al (1971) modifed  Hogstrom (1988)
                x = 0.95*(1.-11.6*zl_f)**(-0.5)
             ELSEIF (stabilitymethod == 7) THEN
                x = (1 - (28.*zl))**0.25
             ELSEIF (stabilitymethod == 2) THEN ! Dyer 1974 X=(1.-(16.*ZL))**(0.5)modified Hosgstrom
                x = 0.95*(1.-15.2*zl_f)**0.5
             ENDIF
             psyh = 2*log((1 + x**2)/2)
          ENDIF
       ELSE IF (zl > neut_limit) THEN    !Stable
          IF (zl <= 1) THEN ! weak/moderate stable
             IF (stabilitymethod == 4) THEN !Businger et al (1971) modifed  Hogstrom (1988)
                ! psyh=0.95+(7.8*zl_f) ! this is NOT the integral form but the stability function, TS 13 Jun 2017
                psyh = (-7.8)*zl_f   ! this is the integral form, TS 13 Jun 2017
             ELSE !Dyer (1974)  PSYH=(-5)*ZL        modifed  Hogstrom (1988)
                psyh = (-4.5)*zl_f
             ENDIF
          ELSE !zL>1, very stable. otherwise psyh would be too large. TS 13 Jun 2017
             ! adopt the form as Brutasert (1982) eqn 4.58. but following the coeffs. of the above eqns
             IF (stabilitymethod == 4) THEN !Businger et al (1971) modifed  Hogstrom (1988)
                psyh = (-7.8)*(1 + log(zl_f))
             ELSE !Dyer (1974)  PSYH=(-5)*ZL        modifed  Hogstrom (1988)
                psyh = (-4.5)*(1 + log(zl_f))
             ENDIF
          END IF
       ENDIF
       RETURN
Referenced by aerodynamicresistance(), and suews_driver::diagsfc().
stab_fn_mom()
real(kind(1d0)) function atmmoiststab_module::stab_fn_mom (integer StabilityMethod, real(kind(1d0)) ZL, real(kind(1d0)) zl_f)
Definition at line 248 of file suews_phys_atmmoiststab.f95.
       !     StabilityMethod = 1-4 -
       !     PSYM - stability FUNCTION for momentum
       !Modified by LJ Mar 2010
       !Input:Used stability method, stability (z-d)/L, zeta (either (z-d)/L or z0/L)
       ! USE mod_z
       ! USE mod_k
       IMPLICIT NONE
       REAL(KIND(1d0)), PARAMETER :: &
          !  k=0.4,&             !Von Karman's contant
          !  k2=0.16,&           !Power of Van Karman's contant
          neut_limit = 0.001000 !Limit for neutral stability
       !  notUsedI=-55
       REAL(KIND(1d0)):: piover2, psym, zl, zl_f, x, x2
       INTEGER ::StabilityMethod
       piover2 = acos(-1.)/2.
       !PRINT*,StabilityMethod,zl,"stab_fn_mom:"
       IF (abs(zl) < neut_limit) THEN
          psym = 0
       ELSEIF (zl < -neut_limit) THEN    !Unstable
          IF (stabilitymethod == 1) THEN     !    Jensen et al 1984 - Van Ulden & Holtslag (1985) p 1206&
             psym = ((1.-16.*zl_f)**0.25) - 1
          ELSEIF (stabilitymethod == 2) THEN !Dyer (1974)(1-16z/L)**.25' k=0.41  mod. Hogstrom (1988)v15.2
             x = (1.-(15.2*zl_f))**0.25
             x2 = log((1 + (x**2.))/2.)
             psym = (2.*log((1 + x)/2.)) + x2 - (2.*atan(x)) + piover2
          ELSEIF (stabilitymethod == 3) THEN ! Kondo (1975) adopted by Campbell & Norman eqn 7.26 p 97
             psym = 0.6*(2)*log((1 + (1 - 16*zl_f)**0.5)/2)
          ELSEIF (stabilitymethod == 4) THEN !Businger et al (1971) modifed  Hogstrom (1988)
             x = (1 - 19.3*zl_f)**(-0.25)
             x2 = log((1 + (x**2.))/2.)
             psym = (2.*log((1 + x)/2.)) + x2 - (2.*atan(x)) + piover2
          ELSEIF (stabilitymethod == 7) THEN ! Dyer & Bradley (1982) (1-28z/L)**.25' k=0.4
             x = (1 - (28.*zl_f))**0.25  ! NT: changed + to - (bug -> checked reference)
             x2 = log((1 + x**2.)/2.)
             psym = (2.*log((1 + x)/2.)) + x2 - (2.*atan(x)) + piover2
          ELSEIF (stabilitymethod == 5) THEN ! Zilitinkevich & Chalikov (1968) modified Hogstrom (1988)
             IF (zl_f >= -0.16) THEN
                x = 1 + 1.38*zl_f
             ELSE
                x = 0.42*(-1)*zl_f**0.333
             ENDIF
             x2 = log((1 + (x**2.))/2.)
             psym = (2.*log((1 + x)/2.)) + x2 - (2.*atan(x)) + piover2
          ELSEIF (stabilitymethod == 6) THEN !     Foken and Skeib (1983)
             IF (zl_f >= 0.06) THEN
                x = 1
             ELSE
                x = ((-1)*zl_f/0.06)**0.25
             ENDIF
             x2 = log((1 + (x**2.))/2.)
             psym = (2.*log((1 + x)/2.)) + x2 - (2.*atan(x)) + piover2
          ENDIF
       ELSEIF (zl > neut_limit) THEN            !Stable
          IF (stabilitymethod == 1) THEN         !Dyer (1974) k=0.35 x=1+5*zl Mod. Hogstrom (1988)
             psym = (-4.8)*zl_f
          ELSEIF (stabilitymethod == 2) THEN     !Van Ulden & Holtslag (1985) p 1206
             IF (zl_f > 1000.) THEN
                zl_f = 1000.
             END IF
             psym = (-17.*(1.-exp(-0.29*zl_f)))
          ELSEIF (stabilitymethod == 4) THEN ! Businger et al (1971) modifed  Hogstrom (1988)
             ! psym=1+6*zl_f  ! this is NOT the integral form but the stability function, TS 13 Jun 2017
             psym = (-6)*zl_f   ! this is the integral form, TS 13 Jun 2017
          ELSEIF (stabilitymethod == 3) THEN ! Kondo (1975) adopted by Campbell & Norman eqn 7.26 p 97
             psym = (-6)*log(1 + zl_f)
          ENDIF
       ENDIF
       RETURN
Referenced by aerodynamicresistance(), suews_driver::diagsfc(), stab_lumps(), and windprofile().
stab_fn_rou()
real(kind(1d0)) function atmmoiststab_module::stab_fn_rou (real(kind(1d0)) z, real(kind(1d0)) zstar)
Definition at line 445 of file suews_phys_atmmoiststab.f95.
       IMPLICIT NONE
       REAL(KIND(1d0))::alpha, zeta, z, psys, zstar, alpha1
       !     z wind speed height - z_d
       !     zstar height of the roughness sublayer
       !     eqn (a4) using alpha=0.5 alpha1=0.7
       alpha = 0.5
       alpha1 = 0.7
       zeta = z/zstar
       psys = (alpha - 1)*log(zeta) - (alpha*alpha1)*(1 - zeta) - (alpha*alpha1**2) &
              *(1 - zeta**2)/6.-(alpha*alpha1**3)*(1 - zeta**3)/24.
       RETURN
stab_lumps()
subroutine atmmoiststab_module::stab_lumps (integer, intent(in) StabilityMethod, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(in) zzd, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) zdm, real(kind(1d0)), intent(in) avU1, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) H_init, real(kind(1d0)), intent(out) L_MOD, real(kind(1d0)), intent(out) TStar, real(kind(1d0)), intent(out) UStar, real(kind(1d0)), intent(out) zL)
Definition at line 118 of file suews_phys_atmmoiststab.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in):: StabilityMethod
       REAL(KIND(1d0)), INTENT(in)::dectime !Decimal time
       REAL(KIND(1d0)), INTENT(in)::zzd     !Active measurement height (meas. height-displac. height)
       REAL(KIND(1d0)), INTENT(in)::z0m     !Aerodynamic roughness length
       REAL(KIND(1d0)), INTENT(in)::zdm     !Displacement height
       REAL(KIND(1d0)), INTENT(in)::avU1    !Average wind speed
       REAL(KIND(1d0)), INTENT(in)::Temp_C    !Air temperature
       REAL(KIND(1d0)), INTENT(in)::H_init    !Kinematic sensible heat flux [K m s-1] used to calculate friction velocity
       REAL(KIND(1d0)), INTENT(out)::L_MOD!Obukhov length
       REAL(KIND(1d0)), INTENT(out)::TStar!T*
       REAL(KIND(1d0)), INTENT(out)::UStar!Friction velocity
       REAL(KIND(1d0)), INTENT(out)::zL ! Stability scale
       ! REAL(KIND(1d0)),INTENT(out)::psim   !Stability function of momentum
       REAL(KIND(1d0))::G_T_K, &
                         kuz, &
                         lold, &
                         psim, &
                         z0l, &
                         psimz0, &
                         h
       REAL(KIND(1d0)), PARAMETER :: &
          k = 0.4, &             !Von Karman's contant
          grav = 9.80665  !g - gravity - physics today august 1987
       INTEGER, PARAMETER ::   notUsedI = -55
       INTEGER :: i
       LOGICAL :: debug = .false.
       IF (debug) WRITE (*, *) stabilitymethod, z0m, avu1, h_init, ustar, l_mod
       g_t_k = (grav/(temp_c + 273.16))*k !gravity constant/(Temperature*Von Karman Constant)
       kuz = k*avu1                     !Von Karman constant*mean wind speed
       IF (zzd < 0) CALL errorhint(32, &
                                   'Windspeed Ht too low relative to zdm [Stability calc]- values [z-zdm, zdm]', &
                                   zzd, zdm, notusedi)
       ustar = kuz/log(zzd/z0m)      !Initial setting of u* and calc. of L_MOD (neutral situation)
       IF (abs(h_init) < 0.001) THEN    ! prevent zero TStar
          h = 0.001
       ELSE
          h = h_init
       END IF
       tstar = (-h/ustar)
       l_mod = (ustar**2)/(g_t_k*tstar)
       IF (log(zzd/z0m) < 0.001000) THEN
          ! PRINT*, 1/(z0m-z0m)
          CALL errorhint(17, 'In stability subroutine, (z-zd) < z0.', zzd, z0m, notusedi)
       ENDIF
       i = 1
       lold = -999.
       DO WHILE ((abs(lold - l_mod) > 0.01).AND.(i < 330)) !NT: add error threshold !Iteration starts
          lold = l_mod
          zl = zzd/l_mod
          z0l = z0m/l_mod  !z0m roughness length
          ! IF (z  L>2)THEN
          !    CALL ErrorHint(73,'LUMPS_atmos_functions_stab.f95: stability scale (z/L), UStar',zL,UStar,notUsedI)
          !    RETURN !MO-theory not necessarily valid above zL>2. Still causes problematic UStar values and correct limit might be 0.3.
          !    !Needs more investigations.
          ! END IF
          psim = stab_fn_mom(stabilitymethod, zl, zl)
          psimz0 = stab_fn_mom(stabilitymethod, zl, z0l)
          ustar = kuz/(log(zzd/z0m) - psim + psimz0) !Friction velocity in non-neutral situation
          tstar = (-h/ustar)
          l_mod = (ustar**2)/(g_t_k*tstar)
          ! IF(UStar<0.001000)THEN       !If u* too small
          !    UStar=KUZ/(LOG(Zzd/z0m))
          !    PRINT*, 'UStar info',UStar,KUZ,(LOG(Zzd/z0m)),Zzd,z0m
          !    CALL ErrorHint(30,'SUBROUTINE STAB_lumps:[ u*< 0.001] zl,dectime',zl,dectime,notUsedI)
          !    CALL ErrorHint(30,'SUBROUTINE STAB_lumps:[ u*< 0.001] z0l,UStar',z0l,UStar,notUsedI)
          !    CALL ErrorHint(30,'SUBROUTINE STAB_lumps:[ u*< 0.001] psim,psimz0',psim,psimz0,notUsedI)
          !    CALL ErrorHint(30,'SUBROUTINE STAB_lumps:[ u*< 0.001] AVU1,log(zzd/z0m)',AVU1,LOG(zzd/z0m),notUsedI)
          !
          !    ! RETURN
          ! ENDIF
          i = i + 1
       ENDDO
       IF (abs(l_mod) > 1e6) l_mod = l_mod/abs(l_mod)*1e6
       ! limit zL to be within [-5,2]
       IF (zl < -5 .OR. zl > 2) THEN
          zl = min(2., max(-5., zl))
          ! limit other output variables as well as z/L
          l_mod = zzd/zl
          z0l = z0m/l_mod
          psim = stab_fn_mom(stabilitymethod, zl, zl)
          psimz0 = stab_fn_mom(stabilitymethod, zl, z0l)
          ! TS 01 Aug 2018: set a low limit at 0.15 m/s (Schumann 1987, BLM)
          ! to prevent potential issues in other stability-related calcualtions
          ustar = max(0.15, kuz/(log(zzd/z0m) - psim + psimz0))
          tstar = (-h/ustar)
       END IF
       ! TS: limit UStar and TStar to reasonable values
       ! 02 Aug 2018: set a low limit at 0.15 m/s (Schumann 1987, BLM)
       ustar = max(0.15, ustar)
       tstar = (-h/ustar)
       IF (ustar < 0.0001) THEN       !If u* still too small after iteration, then force quit simulation and write out error info
          ! UStar=KUZ/(LOG(Zzd/z0m))
          print *, 'UStar', ustar, kuz, (log(zzd/z0m)), zzd, z0m
          CALL errorhint(30, 'SUBROUTINE STAB_lumps:[ u*< 0.0001] zl,dectime', zl, dectime, notusedi)
          CALL errorhint(30, 'SUBROUTINE STAB_lumps:[ u*< 0.0001] z0l,UStar', z0l, ustar, notusedi)
          CALL errorhint(30, 'SUBROUTINE STAB_lumps:[ u*< 0.0001] psim,psimz0', psim, psimz0, notusedi)
          CALL errorhint(30, 'SUBROUTINE STAB_lumps:[ u*< 0.0001] AVU1,log(zzd/z0m)', avu1, log(zzd/z0m), notusedi)
          ! RETURN
       ENDIF
       ! if ( L_MOD<-990 ) then
       !   print*, 'L_MOD too low',L_MOD
       !   print*, 1/(L_MOD-L_MOD)
       !
       ! end if
References errorhint(), and stab_fn_mom().
Referenced by suews_driver::diagsfc(), suews_driver::suews_cal_resistance(), and windprofile().
stab_phi_mom()
real(kind(1d0)) function atmmoiststab_module::stab_phi_mom (integer StabilityMethod, real(kind(1d0)) ZL, real(kind(1d0)) zl_f)
Definition at line 328 of file suews_phys_atmmoiststab.f95.
       !     StabilityMethod = 1-4 -
       !     phi - stability FUNCTION for momentum
       !Modified by NT May 2019 !!!!! check if all are correct!
       !Input:Used stability method, stability (z-d)/L, zeta (either (z-d)/L or z0/L)
       IMPLICIT NONE
       REAL(KIND(1d0)), PARAMETER :: &
          !  k=0.4,&             !Von Karman's contant
          !  k2=0.16,&           !Power of Van Karman's contant
          neut_limit = 0.001000 !Limit for neutral stability
       !  notUsedI=-55
       REAL(KIND(1d0)):: phim, zl, zl_f
       INTEGER ::StabilityMethod
       IF (abs(zl) < neut_limit) THEN
          phim = 0
       ELSEIF (zl < -neut_limit) THEN    !Unstable
          IF (stabilitymethod == 1) THEN     !    Jensen et al 1984 - Van Ulden & Holtslag (1985) p 1206&
             phim = ((1.-16.*zl_f)**(-0.25))
          ELSEIF (stabilitymethod == 2) THEN !Dyer (1974)(1-16z/L)**.25' k=0.41  mod. Hogstrom (1988)v15.2
             phim = (1.-(15.2*zl_f))**(-0.25)
          ELSEIF (stabilitymethod == 3) THEN ! Kondo (1975) adopted by Campbell & Norman eqn 7.26 p 97
             phim = ((1.-16.*zl_f)**(-0.25))
          ELSEIF (stabilitymethod == 4) THEN !Businger et al (1971) modifed  Hogstrom (1988)
             phim = (1.-19.*zl_f)**(-0.25)
          ELSEIF (stabilitymethod == 7) THEN ! Dyer & Bradley (1982) (1-28z/L)**.25' k=0.4
             phim = (1.-(28.*zl_f))**(-0.25)
          ELSEIF (stabilitymethod == 5) THEN ! Zilitinkevich & Chalikov (1968) modified Hogstrom (1988)
             IF (zl_f >= -0.16) THEN
                phim = 1 + 1.38*zl_f
             ELSE
                phim = 0.42*(-1)*zl_f*(-0.333)
             ENDIF
          ELSEIF (stabilitymethod == 6) THEN !     Foken and Skeib (1983)
             IF (zl_f >= 0.06) THEN
                phim = 1
             ELSE
                phim = ((-1)*zl_f/0.06)**(-0.25)
             ENDIF
          ENDIF
       ELSEIF (zl > neut_limit) THEN            !Stable
          IF (stabilitymethod == 1) THEN         !Dyer (1974) k=0.35 x=1+5*zl Mod. Hogstrom (1988)
             phim = 1.+(4.8)*zl_f
          ELSEIF (stabilitymethod == 2) THEN     !Van Ulden & Holtslag (1985) p 1206 ! NT: have no function for phim
             phim = 1.+(4.8)*zl_f
          ELSEIF (stabilitymethod == 4) THEN ! Businger et al (1971) modifed  Hogstrom (1988)
             phim = 1 + 6*zl_f
          ELSEIF (stabilitymethod == 3) THEN ! Kondo (1975) adopted by Campbell & Norman eqn 7.26 p 97  !!NT: checked
             phim = 1.+6.*zl_f/(1.+zl_f)  !!NT: checked reference and updated
          ENDIF
       ENDIF
       RETURN
Referenced by windprofile().