SUEWS: cbl_module Module Reference
cbl_module Module Reference
Variables
integer entrainmenttype
integer co2_included
integer initialdata_use
integer sondeflag
integer isubs
integer, dimension(366) cblday = 0
character(len=200), dimension(366) filesonde = ""
character(len=200) initialdatafilename
real(kind(1d0)) wsb
real(kind(1d0)), dimension(1:10) cbldata
real(kind(1d0)), dimension(:, :), allocatable inicbldata
integer zmax
integer neqn = 6
integer icblcount
integer nlineindata
real(kind(1d0)) c2k = 273.16
real(kind(1d0)) usbl
real(kind(1d0)) ftbl
real(kind(1d0)) fqbl
real(kind(1d0)) fcbl
real(kind(1d0)) gamt
real(kind(1d0)) gamq
real(kind(1d0)) gamc
real(kind(1d0)) tpp
real(kind(1d0)) qpp
real(kind(1d0)) cp0
real(kind(1d0)) alpha3
real(kind(1d0)) blh_m
real(kind(1d0)) blh1_m
real(kind(1d0)) cm
real(kind(1d0)) gamt_km
real(kind(1d0)) gamq_gkgm
real(kind(1d0)) gamq_kgkgm
real(kind(1d0)) tm_c
real(kind(1d0)) tm_k
real(kind(1d0)) tmp_k
real(kind(1d0)) tp_c
real(kind(1d0)) tp_k
real(kind(1d0)) tpp_k
real(kind(1d0)) febl_kgkgms
real(kind(1d0)) fhbl_kms
real(kind(1d0)) qm_gkg
real(kind(1d0)) qm_kgkg
real(kind(1d0)) qp_gkg
real(kind(1d0)) qp_kgkg
real(kind(1d0)) qpp_kgkg
real(kind(1d0)), dimension(0:500, 2) gtheta
real(kind(1d0)), dimension(0:500, 2) ghum
real(kind(1d0)), dimension(6) y
Variable Documentation
alpha3
real(kind(1d0)) cbl_module::alpha3
Definition at line 1210 of file suews_ctrl_const.f95.
    REAL(KIND(1D0))::alpha3, &
                      blh_m, &    ! Boundary layer height(m)
                      blh1_m, &
                      cm, &       ! CO2 concentration in CBL
                      !cp0,gamc,& !
                      gamt_km, &  ! Vertical gradient of theta (K/m)
                      gamq_gkgm, &! Vertical gradient of specific humidity (g/kg/m)
                      gamq_kgkgm, &! Vertical gradient of specific humidity (kg/kg/m)
                      !fcbl,&
                      tm_c, &     ! Potential temperature in CBL (degree Celsius)
                      tm_k, &     ! Potential temperature in CBL (K)
                      tmp_k, &
                      tp_c, &     ! Potential temperature just above Boundary layer height(degree Celsius)
                      tp_k, &     ! Potential temperature just above Boundary layer height(K)
                      tpp_k, &
                      febl_kgkgms, &! Kinematic latent heat flux((kg/kg)*m/s)
                      fhbl_kms, &   ! Kinematic sensible heat flux(K*m/s)
                      qm_gkg, &   ! Specific humidity in CBL(g/kg)
                      qm_kgkg, &  ! Specific humidity in CBL(kg/kg)
                      qp_gkg, &   ! Specific humidity above Boundary layer height(g/kg)
                      qp_kgkg, &  ! Specific humidity above Boundary layer height(kg/kg)
                      qpp_kgkg
Referenced by bluews_module::diff().
blh1_m
real(kind(1d0)) cbl_module::blh1_m
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl().
blh_m
real(kind(1d0)) cbl_module::blh_m
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::gamma_sonde(), and bluews_module::nbl().
c2k
real(kind(1d0)) cbl_module::c2k = 273.16
Definition at line 1206 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::C2K = 273.16
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
cbldata
real(kind(1d0)), dimension(1:10) cbl_module::cbldata
Definition at line 1198 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(1:10):: cbldata
Referenced by bluews_module::cbl(), and bluews_module::diff().
cblday
integer, dimension(366) cbl_module::cblday = 0
Definition at line 1193 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(366)::cblday = 0
Referenced by bluews_module::cbl_readinputdata().
cm
real(kind(1d0)) cbl_module::cm
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl().
co2_included
integer cbl_module::co2_included
Definition at line 1186 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), and bluews_module::cbl_readinputdata().
cp0
real(kind(1d0)) cbl_module::cp0
Definition at line 1208 of file suews_ctrl_const.f95.
entrainmenttype
integer cbl_module::entrainmenttype
Definition at line 1186 of file suews_ctrl_const.f95.
    INTEGER::EntrainmentType, &  ! Entrainment type choice
              CO2_included, &     ! CO2 included
              InitialData_use, &  ! 1 read initial data, 0 do not
              !qh_choice,&        ! selection of qh use to drive CBL growth 1=Suews 2=lumps 3=obs  ! moved to sues_data
              sondeflag, &      ! 1 read sonde or vertical profile data in 0 do not
              isubs          ! 1 include subsidence in equations
Referenced by bluews_module::cbl_readinputdata(), and bluews_module::diff().
fcbl
real(kind(1d0)) cbl_module::fcbl
Definition at line 1208 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_readinputdata(), and bluews_module::diff().
febl_kgkgms
real(kind(1d0)) cbl_module::febl_kgkgms
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), and bluews_module::diff().
fhbl_kms
real(kind(1d0)) cbl_module::fhbl_kms
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), and bluews_module::diff().
filesonde
character(len=200), dimension(366) cbl_module::filesonde = ""
Definition at line 1195 of file suews_ctrl_const.f95.
    CHARACTER(len=200), DIMENSION(366)::FileSonde = ""
Referenced by bluews_module::cbl_readinputdata(), and bluews_module::sonde().
fqbl
real(kind(1d0)) cbl_module::fqbl
Definition at line 1208 of file suews_ctrl_const.f95.
ftbl
real(kind(1d0)) cbl_module::ftbl
Definition at line 1208 of file suews_ctrl_const.f95.
gamc
real(kind(1d0)) cbl_module::gamc
Definition at line 1208 of file suews_ctrl_const.f95.
gamq
real(kind(1d0)) cbl_module::gamq
Definition at line 1208 of file suews_ctrl_const.f95.
gamq_gkgm
real(kind(1d0)) cbl_module::gamq_gkgm
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl_initial(), and bluews_module::nbl().
gamq_kgkgm
real(kind(1d0)) cbl_module::gamq_kgkgm
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::diff(), bluews_module::gamma_sonde(), and bluews_module::nbl().
gamt
real(kind(1d0)) cbl_module::gamt
Definition at line 1208 of file suews_ctrl_const.f95.
gamt_km
real(kind(1d0)) cbl_module::gamt_km
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::diff(), bluews_module::gamma_sonde(), and bluews_module::nbl().
ghum
real(kind(1d0)), dimension(0:500, 2) cbl_module::ghum
Definition at line 1233 of file suews_ctrl_const.f95.
Referenced by bluews_module::gamma_sonde().
gtheta
real(kind(1d0)), dimension(0:500, 2) cbl_module::gtheta
Definition at line 1233 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(0:500, 2):: gtheta, ghum ! Vertical gradient of theta and specific humidity from sonde data
Referenced by bluews_module::gamma_sonde().
icblcount
integer cbl_module::icblcount
Definition at line 1202 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::cbl_readinputdata(), and bluews_module::nbl().
inicbldata
real(kind(1d0)), dimension(:, :), allocatable cbl_module::inicbldata
Definition at line 1199 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::IniCBLdata
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::cbl_readinputdata(), and bluews_module::nbl().
initialdata_use
integer cbl_module::initialdata_use
Definition at line 1186 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl_initial(), bluews_module::cbl_readinputdata(), and bluews_module::nbl().
initialdatafilename
character(len=200) cbl_module::initialdatafilename
Definition at line 1196 of file suews_ctrl_const.f95.
    CHARACTER(len=200)::InitialDataFileName
Referenced by bluews_module::cbl_readinputdata().
isubs
integer cbl_module::isubs
Definition at line 1186 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl_readinputdata(), and bluews_module::diff().
neqn
integer cbl_module::neqn = 6
Definition at line 1202 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl().
nlineindata
integer cbl_module::nlineindata
Definition at line 1202 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl_initial(), bluews_module::cbl_readinputdata(), and bluews_module::nbl().
qm_gkg
real(kind(1d0)) cbl_module::qm_gkg
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
qm_kgkg
real(kind(1d0)) cbl_module::qm_kgkg
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
qp_gkg
real(kind(1d0)) cbl_module::qp_gkg
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl_initial(), and bluews_module::nbl().
qp_kgkg
real(kind(1d0)) cbl_module::qp_kgkg
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::diff(), and bluews_module::nbl().
qpp
real(kind(1d0)) cbl_module::qpp
Definition at line 1208 of file suews_ctrl_const.f95.
qpp_kgkg
real(kind(1d0)) cbl_module::qpp_kgkg
Definition at line 1210 of file suews_ctrl_const.f95.
sondeflag
integer cbl_module::sondeflag
Definition at line 1186 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::cbl_readinputdata(), bluews_module::gamma_sonde(), and bluews_module::nbl().
tm_c
real(kind(1d0)) cbl_module::tm_c
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
tm_k
real(kind(1d0)) cbl_module::tm_k
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::diff(), and bluews_module::nbl().
tmp_k
real(kind(1d0)) cbl_module::tmp_k
Definition at line 1210 of file suews_ctrl_const.f95.
tp_c
real(kind(1d0)) cbl_module::tp_c
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
tp_k
real(kind(1d0)) cbl_module::tp_k
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::diff(), and bluews_module::nbl().
tpp
real(kind(1d0)) cbl_module::tpp
Definition at line 1208 of file suews_ctrl_const.f95.
tpp_k
real(kind(1d0)) cbl_module::tpp_k
Definition at line 1210 of file suews_ctrl_const.f95.
Referenced by bluews_module::diff().
usbl
real(kind(1d0)) cbl_module::usbl
Definition at line 1208 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)):: usbl, ftbl, fqbl, fcbl, gamt, gamq, gamc, tpp, qpp, cp0!,tk
wsb
real(kind(1d0)) cbl_module::wsb
Definition at line 1197 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)):: wsb       ! subsidence velocity
Referenced by bluews_module::cbl_readinputdata(), and bluews_module::diff().
y
real(kind(1d0)), dimension(6) cbl_module::y
Definition at line 1234 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(6)::y  ! NT set from 4 to 6
Referenced by bluews_module::cbl().
zmax
integer cbl_module::zmax
Definition at line 1202 of file suews_ctrl_const.f95.
    INTEGER::zmax, &
              nEqn = 6, &  !NT changed from 4 to 6
              icblcount, &
              nlineindata
Referenced by bluews_module::gamma_sonde().