SUEWS: allocatearray Module Reference
allocatearray Module Reference
Variables
integer, parameter maxnumberofgrids = 90000
integer, parameter maxlinesmet = 8640
integer, parameter ncolumnssiteselect = 101
integer, parameter ncolumnsnonveg = 24
integer, parameter ncolumnsveg = 38
integer, parameter ncolumnswater = 22
integer, parameter ncolumnssnow = 25
integer, parameter ncolumnssoil = 9
integer, parameter ncolumnsconductance = 13
integer, parameter ncolumnsohmcoefficients = 4
integer, parameter ncolumnsestmcoefficients = 52
integer, parameter ncolumnsanthropogenic = 39
integer, parameter ncolumnsirrigation = 25
integer, parameter ncolumnsprofiles = 25
integer, parameter ncolumnswgwaterdist = 10
integer, parameter ncolumnsbiogen = 9
integer, parameter ncolumnsmetforcingdata = 24
integer, parameter ncolsestmdata = 13
integer, parameter ncolumnsdataoutsuews = 87
integer, parameter ncolumnsdataoutsnow = 102
integer, parameter ncolumnsdataoutsol = 31
integer, parameter ncolumnsdataoutbl = 22
integer, parameter ncolumnsdataoutestm = 32
integer, parameter ncolumnsdataoutdailystate = 46
integer, parameter ncolumnsdataoutrsl = 35
character(len=20), dimension(ncolumnssiteselect) headersiteselect_file
character(len=20), dimension(ncolumnsnonveg) headernonveg_file
character(len=20), dimension(ncolumnsnonveg) headernonveg_reqd
character(len=20), dimension(ncolumnsveg) headerveg_file
character(len=20), dimension(ncolumnsveg) headerveg_reqd
character(len=20), dimension(ncolumnswater) headerwater_file
character(len=20), dimension(ncolumnswater) headerwater_reqd
character(len=20), dimension(ncolumnssnow) headersnow_file
character(len=20), dimension(ncolumnssnow) headersnow_reqd
character(len=20), dimension(ncolumnssoil) headersoil_file
character(len=20), dimension(ncolumnssoil) headersoil_reqd
character(len=20), dimension(ncolumnsconductance) headercond_file
character(len=20), dimension(ncolumnsconductance) headercond_reqd
character(len=20), dimension(ncolumnsohmcoefficients) headerohmcoefficients_file
character(len=20), dimension(ncolumnsohmcoefficients) headerohmcoefficients_reqd
character(len=20), dimension(ncolumnsestmcoefficients) headerestmcoefficients_file
character(len=20), dimension(ncolumnsestmcoefficients) headerestmcoefficients_reqd
character(len=20), dimension(ncolumnsanthropogenic) headeranthropogenic_file
character(len=20), dimension(ncolumnsanthropogenic) headeranthropogenic_reqd
character(len=20), dimension(ncolumnsirrigation) headerirrigation_file
character(len=20), dimension(ncolumnsirrigation) headerirrigation_reqd
character(len=20), dimension(ncolumnsprofiles) headerprofiles_file
character(len=20), dimension(ncolumnsprofiles) headerprofiles_reqd
character(len=20), dimension(ncolumnswgwaterdist) headerwgwaterdist_file
character(len=20), dimension(ncolumnswgwaterdist) headerwgwaterdist_reqd
character(len=20), dimension(ncolumnsbiogen) headerbiogen_file
character(len=20), dimension(ncolumnsbiogen) headerbiogen_reqd
integer, dimension(:), allocatable usecolumnsdataout
character(len=14 *ncolumnsdataoutsuews) headeruse
character(len=14 *ncolumnsdataoutsuews) formatuse
character(len=14 *ncolumnsdataoutsuews) headerusenosep
character(len=14 *ncolumnsdataoutsuews) formatusenosep
character(len=52 *ncolumnsdataoutsuews) longnmuse
character(len=14 *ncolumnsdataoutsuews) unitsuse
character(len=3 *ncolumnsdataoutsuews) aggreguse
character(len=4 *ncolumnsdataoutsuews) colnosuse
real(kind(1d0)), dimension(:, :), allocatable siteselect
real(kind(1d0)), dimension(:, :), allocatable nonveg_coeff
real(kind(1d0)), dimension(:, :), allocatable veg_coeff
real(kind(1d0)), dimension(:, :), allocatable water_coeff
real(kind(1d0)), dimension(:, :), allocatable snow_coeff
real(kind(1d0)), dimension(:, :), allocatable soil_coeff
real(kind(1d0)), dimension(:, :), allocatable conductance_coeff
real(kind(1d0)), dimension(:, :), allocatable ohmcoefficients_coeff
real(kind(1d0)), dimension(:, :), allocatable estmcoefficients_coeff
real(kind(1d0)), dimension(:, :), allocatable anthropogenic_coeff
real(kind(1d0)), dimension(:, :), allocatable irrigation_coeff
real(kind(1d0)), dimension(:, :), allocatable profiles_coeff
real(kind(1d0)), dimension(:, :), allocatable wgwaterdist_coeff
real(kind(1d0)), dimension(:, :), allocatable biogen_coeff
integer, dimension(:), allocatable grididmatrix
integer, dimension(:), allocatable grididmatrix0
real(kind(1d0)), dimension(:, :), allocatable surfacechar
real(kind(1d0)), dimension(:, :, :), allocatable metforcingdata
real(kind(1d0)), dimension(:, :), allocatable metforcingdata_grid
real(kind(1d0)), dimension(:, :, :), allocatable estmforcingdata
real(kind(1d0)), dimension(:, :), allocatable modeldailystate
real(kind(1d0)), dimension(:), allocatable dailystatefirstopen
real(kind(1d0)), dimension(:, :, :), allocatable modeloutputdata
real(kind(1d0)), dimension(:, :, :), allocatable dataoutsuews
real(kind(1d0)), dimension(:, :, :), allocatable dataoutrsl
real(kind(1d0)), dimension(:, :, :), allocatable dataoutbl
real(kind(1d0)), dimension(:, :, :), allocatable dataoutsol
real(kind(1d0)), dimension(:, :, :), allocatable dataoutsnow
real(kind(1d0)), dimension(:, :, :), allocatable dataoutestm
real(kind(1d0)), dimension(:, :, :), allocatable dataoutdailystate
real(kind(1d0)), dimension(5) datetimeline
real(kind(1d0)), dimension(ncolumnsdataoutsuews - 5) dataoutlinesuews
real(kind(1d0)), dimension(ncolumnsdataoutsnow - 5) dataoutlinesnow
real(kind(1d0)), dimension(ncolumnsdataoutrsl - 5) dataoutlinersl
real(kind(1d0)), dimension(ncolumnsdataoutdailystate - 5) dailystateline
real(kind(1d0)), dimension(:, :), allocatable metfordisagg
real(kind(1d0)), dimension(:), allocatable metfordisaggprev
real(kind(1d0)), dimension(:), allocatable metfordisaggnext
real(kind(1d0)), dimension(:, :), allocatable estmfordisagg
real(kind(1d0)), dimension(:), allocatable estmfordisaggprev
real(kind(1d0)), dimension(:), allocatable estmfordisaggnext
real(kind(1d0)), dimension(0:23, 2) ahprof_24hr
real(kind(1d0)), dimension(0:23, 2) humactivity_24hr
real(kind(1d0)), dimension(0:23, 2) traffprof_24hr
real(kind(1d0)), dimension(0:23, 2) popprof_24hr
real(kind(1d0)), dimension(0:23, 2) wuprofm_24hr
real(kind(1d0)), dimension(0:23, 2) wuprofa_24hr
real(kind(1d0)), dimension(:, :), allocatable ts5mindata
real(kind(1d0)), dimension(:), allocatable ts5mindata_ir
real(kind(1d0)), dimension(:), allocatable tair24hr
real(kind(1d0)), dimension(27) dataoutlineestm
integer ctp_enusewd = 1
integer ctp_enusewe = 2
integer ctp_wumanuwd = 3
integer ctp_wumanuwe = 4
integer ctp_wuautowd = 5
integer ctp_wuautowe = 6
integer ctp_snowcwd = 7
integer ctp_snowcwe = 8
integer ctp_humactivitywd = 9
integer ctp_humactivitywe = 10
integer ctp_traffprofwd = 11
integer ctp_traffprofwe = 12
integer ctp_popprofwd = 13
integer ctp_popprofwe = 14
integer, parameter nsurf = 7
integer, parameter nvegsurf = 3
integer, parameter nsurfincsnow = nsurf + 1
integer, parameter pavsurf = 1
integer, parameter bldgsurf = 2
integer, parameter conifsurf = 3
integer, parameter decidsurf = 4
integer, parameter grasssurf = 5
integer, parameter bsoilsurf = 6
integer, parameter watersurf = 7
integer, parameter excesssurf = 8
integer, parameter nsurfdonotreceivedrainage = 0
integer, parameter ivconif = 1
integer, parameter ivdecid = 2
integer, parameter ivgrass = 3
real(kind(1d0)), dimension(nsurf) sfr
real(kind(1d0)), dimension(nsurf) addwater
real(kind(1d0)), dimension(nsurf) addwaterrunoff
real(kind(1d0)), dimension(nsurf) chang
real(kind(1d0)), dimension(nsurf) drain
real(kind(1d0)), dimension(nsurf) evap
real(kind(1d0)), dimension(nsurf) runoff
real(kind(1d0)), dimension(nsurf) runoffsoil
real(kind(1d0)), dimension(nsurf) smd_nsurf
real(kind(1d0)), dimension(nsurf) smd_nsurfout
real(kind(1d0)), dimension(nsurf) soilstore_id
real(kind(1d0)), dimension(nsurf) soilstoreold
real(kind(1d0)), dimension(nsurf) state_id
real(kind(1d0)), dimension(nsurf) stateout
real(kind(1d0)), dimension(nsurf) stateold
real(kind(1d0)), dimension(nsurf) rss_nsurf
real(kind(1d0)), dimension(nsurf) wetthresh
real(kind(1d0)), dimension(nsurf) statelimit
real(kind(1d0)), dimension(1) waterdepth
real(kind(1d0)), dimension(nsurf) sathydraulicconduct
real(kind(1d0)), dimension(nsurf) soildepth
real(kind(1d0)), dimension(nsurf) soilstorecap
real(kind(1d0)), dimension(nsurf+1, nsurf - 1) waterdist
real(kind(1d0)), dimension(6, nsurf) storedrainprm
integer, parameter ndays = 366
real(kind(1d0)), dimension(5) gdd_id
real(kind(1d0)), dimension(5) gdd_id_prev
real(kind(1d0)), dimension(12) hdd_id
real(kind(1d0)), dimension(9) wuday_id
real(kind(1d0)), dimension(9) wuday_id_prev
real(kind(1d0)), dimension(nvegsurf) lai_id
real(kind(1d0)), dimension(nvegsurf) lai_id_prev
real(kind(1d0)) albmin_dectr
real(kind(1d0)) albmax_dectr
real(kind(1d0)) capmin_dec
real(kind(1d0)) capmax_dec
real(kind(1d0)) pormin_dec
real(kind(1d0)) pormax_dec
real(kind(1d0)) albmin_evetr
real(kind(1d0)) albmax_evetr
real(kind(1d0)) albmin_grass
real(kind(1d0)) albmax_grass
real(kind(1d0)), dimension(5, maxnumberofgrids) gdd_id_grids
real(kind(1d0)), dimension(12, maxnumberofgrids) hdd_id_grids
real(kind(1d0)), dimension(9, maxnumberofgrids) wuday_id_grids
real(kind(1d0)), dimension(nvegsurf, maxnumberofgrids) lai_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) decidcap_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) albdectr_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) albevetr_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) albgrass_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) porosity_id_grids
real(kind(1d0)) decidcap_id
real(kind(1d0)) albdectr_id
real(kind(1d0)) albevetr_id
real(kind(1d0)) albgrass_id
real(kind(1d0)) porosity_id
real(kind(1d0)) xbo
real(kind(1d0)), dimension(nvegsurf) baset
real(kind(1d0)), dimension(nvegsurf) basete
real(kind(1d0)), dimension(nvegsurf) gddfull
real(kind(1d0)), dimension(nvegsurf) sddfull
real(kind(1d0)), dimension(nvegsurf) laimin
real(kind(1d0)), dimension(nvegsurf) laimax
real(kind(1d0)), dimension(nvegsurf) maxconductance
real(kind(1d0)), dimension(4, nvegsurf) laipower
integer, dimension(nvegsurf) laitype
real(kind(1d0)), dimension(nvegsurf) biogenco2code
real(kind(1d0)), dimension(nvegsurf) alpha_bioco2
real(kind(1d0)), dimension(nvegsurf) beta_bioco2
real(kind(1d0)), dimension(nvegsurf) theta_bioco2
real(kind(1d0)), dimension(nvegsurf) alpha_enh_bioco2
real(kind(1d0)), dimension(nvegsurf) beta_enh_bioco2
real(kind(1d0)), dimension(nvegsurf) resp_a
real(kind(1d0)), dimension(nvegsurf) resp_b
real(kind(1d0)), dimension(nvegsurf) min_res_bioco2
real(kind(1d0)), dimension(nsurf) alb
real(kind(1d0)), dimension(nsurf) emis
real(kind(1d0)) bulkalbedo
real(kind(1d0)), dimension(nsurf) tsurf_ind
real(kind(1d0)), dimension(nsurf) tsurf_ind_snow
real(kind(1d0)), dimension(nsurf) tsurf_ind_nosnow
real(kind(1d0)), dimension(nsurf) kup_ind
real(kind(1d0)), dimension(nsurf) kup_ind_snow
real(kind(1d0)), dimension(nsurf) kup_ind_nosnow
real(kind(1d0)), dimension(nsurf) lup_ind
real(kind(1d0)), dimension(nsurf) lup_ind_snow
real(kind(1d0)), dimension(nsurf) lup_ind_nosnow
real(kind(1d0)), dimension(nsurf) qn1_ind
real(kind(1d0)), dimension(nsurf) qn1_ind_snow
real(kind(1d0)), dimension(nsurf) qn1_ind_nosnow
real(kind(1d0)) narp_lat
real(kind(1d0)) narp_long
real(kind(1d0)) narp_year
real(kind(1d0)) narp_tz
real(kind(1d0)) narp_alb_snow
real(kind(1d0)) narp_emis_snow
real(kind(1d0)) narp_trans_site
real(kind(1d0)), dimension(365) narp_g
integer narp_nperhour
real(kind(1d0)), dimension(:), allocatable narp_kdown_hr
real(kind(1d0)), parameter deg2rad = 0.017453292
real(kind(1d0)), parameter rad2deg = 57.29577951
real(kind(1d0)), parameter sigma_sb = 5.67E-8
real(kind(1d0)), dimension(nsurf+1, 4, 3) ohm_coef
real(kind(1d0)), dimension(nsurf+1) ohm_threshsw
real(kind(1d0)), dimension(nsurf+1) ohm_threshwd
real(kind(1d0)) a1
real(kind(1d0)) a2
real(kind(1d0)) a3
real(kind(1d0)), dimension(:), allocatable qn1_av_grids
real(kind(1d0)), dimension(:), allocatable qn1_s_av_grids
real(kind(1d0)), dimension(:), allocatable dqndt_grids
real(kind(1d0)), dimension(:), allocatable dqnsdt_grids
real(kind(1d0)) qn1_av
real(kind(1d0)) dqndt
real(kind(1d0)) qn1_s_av
real(kind(1d0)) dqnsdt
real(kind(1d0)), dimension(nsurf) changsnow
real(kind(1d0)), dimension(nsurf) maxsnowvol
real(kind(1d0)), dimension(nsurf) snowwater
real(kind(1d0)), dimension(nsurf) ev_snow
real(kind(1d0)), dimension(nsurf) mw_ind
real(kind(1d0)), dimension(nsurf) mw_indday
real(kind(1d0)), dimension(nsurf) runoffsnow
real(kind(1d0)), dimension(nsurf) snowdens
real(kind(1d0)), dimension(nsurf) snowfrac
real(kind(1d0)), dimension(nsurf) icefrac
real(kind(1d0)), dimension(nsurf) snowinit
real(kind(1d0)), dimension(nsurf) snowdepth
real(kind(1d0)), dimension(nsurf) snowtosurf
real(kind(1d0)), dimension(nsurf) volswe
real(kind(1d0)), dimension(nsurf) statefraction
real(kind(1d0)), dimension(nsurf) freezmelt
real(kind(1d0)), dimension(nsurf) qm_freezstate
real(kind(1d0)), dimension(nsurf) freezstate
real(kind(1d0)), dimension(nsurf) freezstatevol
real(kind(1d0)), dimension(nsurf) qm_melt
real(kind(1d0)), dimension(nsurf) qm_rain
real(kind(1d0)), dimension(nsurf) rainonsnow
real(kind(1d0)), dimension(nsurf) snowpacklimit
real(kind(1d0)), dimension(nsurf) deltaqi
real(kind(1d0)), dimension(nsurf) snowpack
real(kind(1d0)), dimension(nsurf) snowpackold
integer, dimension(nsurf) heig
integer, dimension(nsurf) snowcoverforms
integer, dimension(nsurf) snowcalcswitch = 0
integer, parameter nconns = 8
real(kind(1d0)), dimension(nconns) gridtofrac
real(kind(1d0)), dimension(nconns) gridto
real(kind(1d0)), dimension(maxnumberofgrids) a1anohm
real(kind(1d0)), dimension(maxnumberofgrids) a2anohm
real(kind(1d0)), dimension(maxnumberofgrids) a3anohm
real(kind(1d0)), dimension(maxnumberofgrids) mahanohm
real(kind(1d0)), dimension(maxnumberofgrids) boanohmstart
real(kind(1d0)), dimension(maxnumberofgrids) boanohmend
real(kind(1d0)), dimension(nsurf) cpanohm
real(kind(1d0)), dimension(nsurf) kkanohm
real(kind(1d0)), dimension(nsurf) chanohm
real(kind(1d0)), dimension(5, nsurfincsnow) zsurf_suewssurfs
real(kind(1d0)), dimension(5, nsurfincsnow) ksurf_suewssurfs
real(kind(1d0)), dimension(5, nsurfincsnow) rsurf_suewssurfs
integer cc
integer, parameter ccendsi = ncolumnsSiteSelect
integer, dimension(nsurf) c_albmin = (/(cc, cc=ccEndSI + 0*nsurf + 1, ccEndSI + 0*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_albmax = (/(cc, cc=ccEndSI + 1*nsurf + 1, ccEndSI + 1*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_emis = (/(cc, cc=ccEndSI + 2*nsurf + 1, ccEndSI + 2*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_stormin = (/(cc, cc=ccEndSI + 3*nsurf + 1, ccEndSI + 3*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_stormax = (/(cc, cc=ccEndSI + 4*nsurf + 1, ccEndSI + 4*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wetthresh = (/(cc, cc=ccEndSI + 5*nsurf + 1, ccEndSI + 5*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_statelimit = (/(cc, cc=ccEndSI + 6*nsurf + 1, ccEndSI + 6*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_dreq = (/(cc, cc=ccEndSI + 7*nsurf + 1, ccEndSI + 7*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_drcoef1 = (/(cc, cc=ccEndSI + 8*nsurf + 1, ccEndSI + 8*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_drcoef2 = (/(cc, cc=ccEndSI + 9*nsurf + 1, ccEndSI + 9*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_soiltcode = (/(cc, cc=ccEndSI + 10*nsurf + 1, ccEndSI + 10*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_snowlimpat = (/(cc, cc=ccEndSI + 11*nsurf + 1, ccEndSI + 11*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_snowlimrem = (/(cc, cc=ccEndSI + 12*nsurf + 1, ccEndSI + 12*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_cpanohm = (/(cc, cc=ccEndSI + 13*nsurf + 1, ccEndSI + 13*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_kkanohm = (/(cc, cc=ccEndSI + 14*nsurf + 1, ccEndSI + 14*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_chanohm = (/(cc, cc=ccEndSI + 15*nsurf + 1, ccEndSI + 15*nsurf + nsurf, 1)/)
integer, parameter ccendi = (ccEndSI + 15*nsurf + nsurf)
integer, dimension(nvegsurf) c_baset = (/(cc, cc=ccEndI + 0*nvegsurf + 1, ccEndI + 0*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_basete = (/(cc, cc=ccEndI + 1*nvegsurf + 1, ccEndI + 1*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_gddfull = (/(cc, cc=ccEndI + 2*nvegsurf + 1, ccEndI + 2*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_sddfull = (/(cc, cc=ccEndI + 3*nvegsurf + 1, ccEndI + 3*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_laimin = (/(cc, cc=ccEndI + 4*nvegsurf + 1, ccEndI + 4*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_laimax = (/(cc, cc=ccEndI + 5*nvegsurf + 1, ccEndI + 5*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_porositymin = (/(cc, cc=ccEndI + 6*nvegsurf + 1, ccEndI + 6*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_porositymax = (/(cc, cc=ccEndI + 7*nvegsurf + 1, ccEndI + 7*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_gsmax = (/(cc, cc=ccEndI + 8*nvegsurf + 1, ccEndI + 8*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_laieq = (/(cc, cc=ccEndI + 9*nvegsurf + 1, ccEndI + 9*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_leafgp1 = (/(cc, cc=ccEndI + 10*nvegsurf + 1, ccEndI + 10*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_leafgp2 = (/(cc, cc=ccEndI + 11*nvegsurf + 1, ccEndI + 11*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_leafop1 = (/(cc, cc=ccEndI + 12*nvegsurf + 1, ccEndI + 12*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_leafop2 = (/(cc, cc=ccEndI + 13*nvegsurf + 1, ccEndI + 13*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_biogenco2code = (/(cc, cc=ccEndI + 14*nvegsurf + 1, ccEndI + 14*nvegsurf + nvegsurf, 1)/)
integer, parameter ccendp = (ccEndI + 14*nvegsurf + nvegsurf)
integer c_waterdepth = (ccEndP + 1)
integer, parameter ccendw = (ccEndP + 1)
integer c_snowrmfactor = (ccEndW + 1)
integer c_snowtmfactor = (ccEndW + 2)
integer c_snowalbmin = (ccEndW + 3)
integer c_snowalbmax = (ccEndW + 4)
integer c_snowemis = (ccEndW + 6)
integer c_snowtau_a = (ccEndW + 7)
integer c_snowtau_f = (ccEndW + 8)
integer c_snowplimalb = (ccEndW + 9)
integer c_snowsdmin = (ccEndW + 10)
integer c_snowsdmax = (ccEndW + 11)
integer c_snowtau_r = (ccEndW + 12)
integer c_snowcrwmin = (ccEndW + 13)
integer c_snowcrwmax = (ccEndW + 14)
integer c_snowplimsnow = (ccEndW + 15)
integer, parameter ccendsn = (ccEndW + 15)
integer, dimension(nsurf) c_soildepth = (/(cc, cc=ccEndSn + 0*nsurf + 1, ccEndSn + 0*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_soilstcap = (/(cc, cc=ccEndSn + 1*nsurf + 1, ccEndSn + 1*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_ksat = (/(cc, cc=ccEndSn + 2*nsurf + 1, ccEndSn + 2*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_soildens = (/(cc, cc=ccEndSn + 3*nsurf + 1, ccEndSn + 3*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_soilinfrate = (/(cc, cc=ccEndSn + 4*nsurf + 1, ccEndSn + 4*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_obssmdepth = (/(cc, cc=ccEndSn + 5*nsurf + 1, ccEndSn + 5*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_obssmmax = (/(cc, cc=ccEndSn + 6*nsurf + 1, ccEndSn + 6*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_obssnrfrac = (/(cc, cc=ccEndSn + 7*nsurf + 1, ccEndSn + 7*nsurf + nsurf, 1)/)
integer, parameter ccendso = (ccEndSn + 7*nsurf + nsurf)
integer c_gsg1 = (ccEndSo + 1)
integer c_gsg2 = (ccEndSo + 2)
integer c_gsg3 = (ccEndSo + 3)
integer c_gsg4 = (ccEndSo + 4)
integer c_gsg5 = (ccEndSo + 5)
integer c_gsg6 = (ccEndSo + 6)
integer c_gsth = (ccEndSo + 7)
integer c_gstl = (ccEndSo + 8)
integer c_gss1 = (ccEndSo + 9)
integer c_gss2 = (ccEndSo + 10)
integer c_gskmax = (ccEndSo + 11)
integer c_gsmodel = (ccEndSo + 12)
integer, parameter ccendgs = (ccEndSo + 12)
integer, dimension(nsurfincsnow) c_ohmcode_swet = (/(cc, cc=ccEndGs + 0*nsurfIncSnow + 1, ccEndGs + 0*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_ohmcode_sdry = (/(cc, cc=ccEndGs + 1*nsurfIncSnow + 1, ccEndGs + 1*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_ohmcode_wwet = (/(cc, cc=ccEndGs + 2*nsurfIncSnow + 1, ccEndGs + 2*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_ohmcode_wdry = (/(cc, cc=ccEndGs + 3*nsurfIncSnow + 1, ccEndGs + 3*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a1_swet = (/(cc, cc=ccEndGs + 4*nsurfIncSnow + 1, ccEndGs + 4*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a2_swet = (/(cc, cc=ccEndGs + 5*nsurfIncSnow + 1, ccEndGs + 5*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a3_swet = (/(cc, cc=ccEndGs + 6*nsurfIncSnow + 1, ccEndGs + 6*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a1_sdry = (/(cc, cc=ccEndGs + 7*nsurfIncSnow + 1, ccEndGs + 7*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a2_sdry = (/(cc, cc=ccEndGs + 8*nsurfIncSnow + 1, ccEndGs + 8*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a3_sdry = (/(cc, cc=ccEndGs + 9*nsurfIncSnow + 1, ccEndGs + 9*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a1_wwet = (/(cc, cc=ccEndGs + 10*nsurfIncSnow + 1, ccEndGs + 10*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a2_wwet = (/(cc, cc=ccEndGs + 11*nsurfIncSnow + 1, ccEndGs + 11*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a3_wwet = (/(cc, cc=ccEndGs + 12*nsurfIncSnow + 1, ccEndGs + 12*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a1_wdry = (/(cc, cc=ccEndGs + 13*nsurfIncSnow + 1, ccEndGs + 13*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a2_wdry = (/(cc, cc=ccEndGs + 14*nsurfIncSnow + 1, ccEndGs + 14*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_a3_wdry = (/(cc, cc=ccEndGs + 15*nsurfIncSnow + 1, ccEndGs + 15*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_ohmthresh_sw = (/(cc, cc=ccEndGs + 16*nsurfIncSnow + 1, ccEndGs + 16*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_ohmthresh_wd = (/(cc, cc=ccEndGs + 17*nsurfIncSnow + 1, ccEndGs + 17*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_estmcode = (/(cc, cc=ccEndGs + 18*nsurfIncSnow + 1, ccEndGs + 18*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, parameter ccendo = (ccEndGs + 18*nsurfIncSnow + nsurfIncSnow)
integer c_basethdd = (ccEndO + 1)
integer c_qf_a1 = (ccEndO + 2)
integer c_qf_b1 = (ccEndO + 3)
integer c_qf_c1 = (ccEndO + 4)
integer c_qf_a2 = (ccEndO + 5)
integer c_qf_b2 = (ccEndO + 6)
integer c_qf_c2 = (ccEndO + 7)
integer c_ahmin_wd = (ccEndO + 8)
integer c_ahmin_we = (ccEndO + 9)
integer c_ahslopeheating_wd = (ccEndO + 10)
integer c_ahslopeheating_we = (ccEndO + 11)
integer c_ahslopecooling_wd = (ccEndO + 12)
integer c_ahslopecooling_we = (ccEndO + 13)
integer c_tcriticheating_we = (ccEndO + 14)
integer c_tcriticheating_wd = (ccEndO + 15)
integer c_tcriticcooling_we = (ccEndO + 16)
integer c_tcriticcooling_wd = (ccEndO + 17)
integer c_enprofwd = (ccEndO + 18)
integer c_enprofwe = (ccEndO + 19)
integer c_co2mwd = (ccEndO + 20)
integer c_co2mwe = (ccEndO + 21)
integer c_traffprofwd = (ccEndO + 22)
integer c_traffprofwe = (ccEndO + 23)
integer c_popprofwd = (ccEndO + 24)
integer c_popprofwe = (ccEndO + 25)
integer c_minqfmetab = (ccEndO + 26)
integer c_maxqfmetab = (ccEndO + 27)
integer c_minfcmetab = (ccEndO + 28)
integer c_maxfcmetab = (ccEndO + 29)
integer c_frpddwe = (ccEndO + 30)
integer c_frfossilfuel_heat = (ccEndO + 31)
integer c_frfossilfuel_nonheat = (ccEndO + 32)
integer c_ef_umolco2perj = (ccEndO + 33)
integer c_enef_v_jkm = (ccEndO + 34)
integer c_fcef_v_kgkmwd = (ccEndO + 35)
integer c_fcef_v_kgkmwe = (ccEndO + 36)
integer c_co2pointsource = (ccEndO + 37)
integer c_trafficunits = (ccEndO + 38)
integer, parameter ccenda = (ccEndO + 38)
integer c_iestart = (ccEndA + 1)
integer c_ieend = (ccEndA + 2)
integer c_intwu = (ccEndA + 3)
integer c_faut = (ccEndA + 4)
integer, dimension(3) c_ie_a = (/(cc, cc=ccEndA + 4 + 0*3 + 1, ccEndA + 4 + 0*3 + 3, 1)/)
integer, dimension(3) c_ie_m = (/(cc, cc=ccEndA + 4 + 1*3 + 1, ccEndA + 4 + 1*3 + 3, 1)/)
integer, dimension(7) c_daywat = (/(cc, cc=ccEndA + 10 + 0*7 + 1, ccEndA + 10 + 0*7 + 7, 1)/)
integer, dimension(7) c_daywatper = (/(cc, cc=ccEndA + 10 + 1*7 + 1, ccEndA + 10 + 1*7 + 7, 1)/)
integer, parameter ccendir = (ccEndA + 10 + 1*7 + 7)
integer, dimension(24) c_hrprofenusewd = (/(cc, cc=ccEndIr + 0*24 + 1, ccEndIr + 0*24 + 24, 1)/)
integer, dimension(24) c_hrprofenusewe = (/(cc, cc=ccEndIr + 1*24 + 1, ccEndIr + 1*24 + 24, 1)/)
integer, dimension(24) c_hrprofwumanuwd = (/(cc, cc=ccEndIr + 2*24 + 1, ccEndIr + 2*24 + 24, 1)/)
integer, dimension(24) c_hrprofwumanuwe = (/(cc, cc=ccEndIr + 3*24 + 1, ccEndIr + 3*24 + 24, 1)/)
integer, dimension(24) c_hrprofwuautowd = (/(cc, cc=ccEndIr + 4*24 + 1, ccEndIr + 4*24 + 24, 1)/)
integer, dimension(24) c_hrprofwuautowe = (/(cc, cc=ccEndIr + 5*24 + 1, ccEndIr + 5*24 + 24, 1)/)
integer, dimension(24) c_hrprofsnowcwd = (/(cc, cc=ccEndIr + 6*24 + 1, ccEndIr + 6*24 + 24, 1)/)
integer, dimension(24) c_hrprofsnowcwe = (/(cc, cc=ccEndIr + 7*24 + 1, ccEndIr + 7*24 + 24, 1)/)
integer, dimension(24) c_hrprofhumactivitywd = (/(cc, cc=ccEndIr + 8*24 + 1, ccEndIr + 8*24 + 24, 1)/)
integer, dimension(24) c_hrprofhumactivitywe = (/(cc, cc=ccEndIr + 9*24 + 1, ccEndIr + 9*24 + 24, 1)/)
integer, dimension(24) c_hrproftraffwd = (/(cc, cc=ccEndIr + 10*24 + 1, ccEndIr + 10*24 + 24, 1)/)
integer, dimension(24) c_hrproftraffwe = (/(cc, cc=ccEndIr + 11*24 + 1, ccEndIr + 11*24 + 24, 1)/)
integer, dimension(24) c_hrprofpopwd = (/(cc, cc=ccEndIr + 12*24 + 1, ccEndIr + 12*24 + 24, 1)/)
integer, dimension(24) c_hrprofpopwe = (/(cc, cc=ccEndIr + 13*24 + 1, ccEndIr + 13*24 + 24, 1)/)
integer, parameter ccendpr = (ccEndIr + 13*24 + 24)
integer, dimension(nsurf) c_wgtopaved = (/(cc, cc=ccEndPr + 0*nsurf + 1, ccEndPr + 0*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtobldgs = (/(cc, cc=ccEndPr + 1*nsurf + 1, ccEndPr + 1*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtoevetr = (/(cc, cc=ccEndPr + 2*nsurf + 1, ccEndPr + 2*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtodectr = (/(cc, cc=ccEndPr + 3*nsurf + 1, ccEndPr + 3*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtograss = (/(cc, cc=ccEndPr + 4*nsurf + 1, ccEndPr + 4*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtobsoil = (/(cc, cc=ccEndPr + 5*nsurf + 1, ccEndPr + 5*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtowater = (/(cc, cc=ccEndPr + 6*nsurf + 1, ccEndPr + 6*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtorunoff = (/(cc, cc=ccEndPr + 7*nsurf + 1, ccEndPr + 7*nsurf + nsurf, 1)/)
integer, dimension(nsurf) c_wgtosoilstore = (/(cc, cc=ccEndPr + 8*nsurf + 1, ccEndPr + 8*nsurf + nsurf, 1)/)
integer, parameter cbendwg = (ccEndPr + 8*nsurf + nsurf)
integer, dimension(nvegsurf) c_alpha_bioco2 = (/(cc, cc=cBEndWG + 0*nvegsurf + 1, cBEndWG + 0*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_beta_bioco2 = (/(cc, cc=cBEndWG + 1*nvegsurf + 1, cBEndWG + 1*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_theta_bioco2 = (/(cc, cc=cBEndWG + 2*nvegsurf + 1, cBEndWG + 2*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_alpha_enh_bioco2 = (/(cc, cc=cBEndWG + 3*nvegsurf + 1, cBEndWG + 3*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_beta_enh_bioco2 = (/(cc, cc=cBEndWG + 4*nvegsurf + 1, cBEndWG + 4*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_resp_a = (/(cc, cc=cBEndWG + 5*nvegsurf + 1, cBEndWG + 5*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_resp_b = (/(cc, cc=cBEndWG + 6*nvegsurf + 1, cBEndWG + 6*nvegsurf + nvegsurf, 1)/)
integer, dimension(nvegsurf) c_min_res_bioco2 = (/(cc, cc=cBEndWG + 7*nvegsurf + 1, cBEndWG + 7*nvegsurf + nvegsurf, 1)/)
integer, parameter ccendb = (cBEndWG + 7*nvegsurf + nvegsurf)
integer, dimension(nsurfincsnow) c_surf_thick1 = (/(cc, cc=ccEndB+ 0*nsurfIncSnow+1,ccEndB+ 0*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_k1 = (/(cc, cc=ccEndB + 1*nsurfIncSnow + 1, ccEndB + 1*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_rhocp1 = (/(cc, cc=ccEndB+ 2*nsurfIncSnow+1,ccEndB+ 2*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_thick2 = (/(cc, cc=ccEndB+ 3*nsurfIncSnow+1,ccEndB+ 3*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_k2 = (/(cc, cc=ccEndB + 4*nsurfIncSnow + 1, ccEndB + 4*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_rhocp2 = (/(cc, cc=ccEndB+ 5*nsurfIncSnow+1,ccEndB+ 5*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_thick3 = (/(cc, cc=ccEndB+ 6*nsurfIncSnow+1,ccEndB+ 6*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_k3 = (/(cc, cc=ccEndB + 7*nsurfIncSnow + 1, ccEndB + 7*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_rhocp3 = (/(cc, cc=ccEndB+ 8*nsurfIncSnow+1,ccEndB+ 8*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_thick4 = (/(cc, cc=ccEndB+ 9*nsurfIncSnow+1,ccEndB+ 9*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_k4 = (/(cc, cc=ccEndB + 10*nsurfIncSnow + 1, ccEndB + 10*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_rhocp4 = (/(cc, cc=ccEndB+11*nsurfIncSnow+1,ccEndB+11*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_thick5 = (/(cc, cc=ccEndB+12*nsurfIncSnow+1,ccEndB+12*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_k5 = (/(cc, cc=ccEndB + 13*nsurfIncSnow + 1, ccEndB + 13*nsurfIncSnow + nsurfIncSnow, 1)/)
integer, dimension(nsurfincsnow) c_surf_rhocp5 = (/(cc, cc=ccEndB+14*nsurfIncSnow+1,ccEndB+14*nsurfIncSnow+nsurfIncSnow, 1)/)
integer, parameter ccendestmb = (ccEndB + 14*nsurfIncSnow + nsurfIncSnow)
integer c_wall_thick1 = (ccEndESTMB + 1)
integer c_wall_k1 = (ccEndESTMB + 2)
integer c_wall_rhocp1 = (ccEndESTMB + 3)
integer c_wall_thick2 = (ccEndESTMB + 4)
integer c_wall_k2 = (ccEndESTMB + 5)
integer c_wall_rhocp2 = (ccEndESTMB + 6)
integer c_wall_thick3 = (ccEndESTMB + 7)
integer c_wall_k3 = (ccEndESTMB + 8)
integer c_wall_rhocp3 = (ccEndESTMB + 9)
integer c_wall_thick4 = (ccEndESTMB + 10)
integer c_wall_k4 = (ccEndESTMB + 11)
integer c_wall_rhocp4 = (ccEndESTMB + 12)
integer c_wall_thick5 = (ccEndESTMB + 13)
integer c_wall_k5 = (ccEndESTMB + 14)
integer c_wall_rhocp5 = (ccEndESTMB + 15)
integer c_internal_thick1 = (ccEndESTMB + 16)
integer c_internal_k1 = (ccEndESTMB + 17)
integer c_internal_rhocp1 = (ccEndESTMB + 18)
integer c_internal_thick2 = (ccEndESTMB + 19)
integer c_internal_k2 = (ccEndESTMB + 20)
integer c_internal_rhocp2 = (ccEndESTMB + 21)
integer c_internal_thick3 = (ccEndESTMB + 22)
integer c_internal_k3 = (ccEndESTMB + 23)
integer c_internal_rhocp3 = (ccEndESTMB + 24)
integer c_internal_thick4 = (ccEndESTMB + 25)
integer c_internal_k4 = (ccEndESTMB + 26)
integer c_internal_rhocp4 = (ccEndESTMB + 27)
integer c_internal_thick5 = (ccEndESTMB + 28)
integer c_internal_k5 = (ccEndESTMB + 29)
integer c_internal_rhocp5 = (ccEndESTMB + 30)
integer c_nroom = (ccEndESTMB + 31)
integer c_alb_ibld = (ccEndESTMB + 32)
integer c_em_ibld = (ccEndESTMB + 33)
integer c_ch_iwall = (ccEndESTMB + 34)
integer c_ch_iroof = (ccEndESTMB + 35)
integer c_ch_ibld = (ccEndESTMB + 36)
integer, parameter ccendestmm = (ccEndESTMB + 36)
integer, dimension(3) c_surf_thick1_paved = (/(cc, cc=ccEndESTMM + 0*3 + 1, ccEndESTMM + 0*3 + 3, 1)/)
integer, dimension(3) c_surf_k1_paved = (/(cc, cc=ccEndESTMM + 1*3 + 1, ccEndESTMM + 1*3 + 3, 1)/)
integer, dimension(3) c_surf_rhocp1_paved = (/(cc, cc=ccEndESTMM + 2*3 + 1, ccEndESTMM + 2*3 + 3, 1)/)
integer, dimension(3) c_surf_thick2_paved = (/(cc, cc=ccEndESTMM + 3*3 + 1, ccEndESTMM + 3*3 + 3, 1)/)
integer, dimension(3) c_surf_k2_paved = (/(cc, cc=ccEndESTMM + 4*3 + 1, ccEndESTMM + 4*3 + 3, 1)/)
integer, dimension(3) c_surf_rhocp2_paved = (/(cc, cc=ccEndESTMM + 5*3 + 1, ccEndESTMM + 5*3 + 3, 1)/)
integer, dimension(3) c_surf_thick3_paved = (/(cc, cc=ccEndESTMM + 6*3 + 1, ccEndESTMM + 6*3 + 3, 1)/)
integer, dimension(3) c_surf_k3_paved = (/(cc, cc=ccEndESTMM + 7*3 + 1, ccEndESTMM + 7*3 + 3, 1)/)
integer, dimension(3) c_surf_rhocp3_paved = (/(cc, cc=ccEndESTMM + 8*3 + 1, ccEndESTMM + 8*3 + 3, 1)/)
integer, dimension(3) c_surf_thick4_paved = (/(cc, cc=ccEndESTMM + 9*3 + 1, ccEndESTMM + 9*3 + 3, 1)/)
integer, dimension(3) c_surf_k4_paved = (/(cc, cc=ccEndESTMM + 10*3 + 1, ccEndESTMM + 10*3 + 3, 1)/)
integer, dimension(3) c_surf_rhocp4_paved = (/(cc, cc=ccEndESTMM + 11*3 + 1, ccEndESTMM + 11*3 + 3, 1)/)
integer, dimension(3) c_surf_thick5_paved = (/(cc, cc=ccEndESTMM + 12*3 + 1, ccEndESTMM + 12*3 + 3, 1)/)
integer, dimension(3) c_surf_k5_paved = (/(cc, cc=ccEndESTMM + 13*3 + 1, ccEndESTMM + 13*3 + 3, 1)/)
integer, dimension(3) c_surf_rhocp5_paved = (/(cc, cc=ccEndESTMM + 14*3 + 1, ccEndESTMM + 14*3 + 3, 1)/)
integer, parameter ccendestmmp = (ccEndESTMM + 14*3 + 3)
integer, dimension(5) c_surf_thick1_bldgs = (/(cc, cc=ccEndESTMMP + 0*5 + 1, ccEndESTMMP + 0*5 + 5, 1)/)
integer, dimension(5) c_surf_k1_bldgs = (/(cc, cc=ccEndESTMMP + 1*5 + 1, ccEndESTMMP + 1*5 + 5, 1)/)
integer, dimension(5) c_surf_rhocp1_bldgs = (/(cc, cc=ccEndESTMMP + 2*5 + 1, ccEndESTMMP + 2*5 + 5, 1)/)
integer, dimension(5) c_surf_thick2_bldgs = (/(cc, cc=ccEndESTMMP + 3*5 + 1, ccEndESTMMP + 3*5 + 5, 1)/)
integer, dimension(5) c_surf_k2_bldgs = (/(cc, cc=ccEndESTMMP + 4*5 + 1, ccEndESTMMP + 4*5 + 5, 1)/)
integer, dimension(5) c_surf_rhocp2_bldgs = (/(cc, cc=ccEndESTMMP + 5*5 + 1, ccEndESTMMP + 5*5 + 5, 1)/)
integer, dimension(5) c_surf_thick3_bldgs = (/(cc, cc=ccEndESTMMP + 6*5 + 1, ccEndESTMMP + 6*5 + 5, 1)/)
integer, dimension(5) c_surf_k3_bldgs = (/(cc, cc=ccEndESTMMP + 7*5 + 1, ccEndESTMMP + 7*5 + 5, 1)/)
integer, dimension(5) c_surf_rhocp3_bldgs = (/(cc, cc=ccEndESTMMP + 8*5 + 1, ccEndESTMMP + 8*5 + 5, 1)/)
integer, dimension(5) c_surf_thick4_bldgs = (/(cc, cc=ccEndESTMMP + 9*5 + 1, ccEndESTMMP + 9*5 + 5, 1)/)
integer, dimension(5) c_surf_k4_bldgs = (/(cc, cc=ccEndESTMMP + 10*5 + 1, ccEndESTMMP + 10*5 + 5, 1)/)
integer, dimension(5) c_surf_rhocp4_bldgs = (/(cc, cc=ccEndESTMMP + 11*5 + 1, ccEndESTMMP + 11*5 + 5, 1)/)
integer, dimension(5) c_surf_thick5_bldgs = (/(cc, cc=ccEndESTMMP + 12*5 + 1, ccEndESTMMP + 12*5 + 5, 1)/)
integer, dimension(5) c_surf_k5_bldgs = (/(cc, cc=ccEndESTMMP + 13*5 + 1, ccEndESTMMP + 13*5 + 5, 1)/)
integer, dimension(5) c_surf_rhocp5_bldgs = (/(cc, cc=ccEndESTMMP + 14*5 + 1, ccEndESTMMP + 14*5 + 5, 1)/)
integer, dimension(5) c_wall_thick1_bldgs = (/(cc, cc=ccEndESTMMP + 15*5 + 1, ccEndESTMMP + 15*5 + 5, 1)/)
integer, dimension(5) c_wall_k1_bldgs = (/(cc, cc=ccEndESTMMP + 16*5 + 1, ccEndESTMMP + 16*5 + 5, 1)/)
integer, dimension(5) c_wall_rhocp1_bldgs = (/(cc, cc=ccEndESTMMP + 17*5 + 1, ccEndESTMMP + 17*5 + 5, 1)/)
integer, dimension(5) c_wall_thick2_bldgs = (/(cc, cc=ccEndESTMMP + 18*5 + 1, ccEndESTMMP + 18*5 + 5, 1)/)
integer, dimension(5) c_wall_k2_bldgs = (/(cc, cc=ccEndESTMMP + 19*5 + 1, ccEndESTMMP + 19*5 + 5, 1)/)
integer, dimension(5) c_wall_rhocp2_bldgs = (/(cc, cc=ccEndESTMMP + 20*5 + 1, ccEndESTMMP + 20*5 + 5, 1)/)
integer, dimension(5) c_wall_thick3_bldgs = (/(cc, cc=ccEndESTMMP + 21*5 + 1, ccEndESTMMP + 21*5 + 5, 1)/)
integer, dimension(5) c_wall_k3_bldgs = (/(cc, cc=ccEndESTMMP + 22*5 + 1, ccEndESTMMP + 22*5 + 5, 1)/)
integer, dimension(5) c_wall_rhocp3_bldgs = (/(cc, cc=ccEndESTMMP + 23*5 + 1, ccEndESTMMP + 23*5 + 5, 1)/)
integer, dimension(5) c_wall_thick4_bldgs = (/(cc, cc=ccEndESTMMP + 24*5 + 1, ccEndESTMMP + 24*5 + 5, 1)/)
integer, dimension(5) c_wall_k4_bldgs = (/(cc, cc=ccEndESTMMP + 25*5 + 1, ccEndESTMMP + 25*5 + 5, 1)/)
integer, dimension(5) c_wall_rhocp4_bldgs = (/(cc, cc=ccEndESTMMP + 26*5 + 1, ccEndESTMMP + 26*5 + 5, 1)/)
integer, dimension(5) c_wall_thick5_bldgs = (/(cc, cc=ccEndESTMMP + 27*5 + 1, ccEndESTMMP + 27*5 + 5, 1)/)
integer, dimension(5) c_wall_k5_bldgs = (/(cc, cc=ccEndESTMMP + 28*5 + 1, ccEndESTMMP + 28*5 + 5, 1)/)
integer, dimension(5) c_wall_rhocp5_bldgs = (/(cc, cc=ccEndESTMMP + 29*5 + 1, ccEndESTMMP + 29*5 + 5, 1)/)
integer, dimension(5) c_internal_thick1_bldgs = (/(cc, cc=ccEndESTMMP + 30*5 + 1, ccEndESTMMP + 30*5 + 5, 1)/)
integer, dimension(5) c_internal_k1_bldgs = (/(cc, cc=ccEndESTMMP + 31*5 + 1, ccEndESTMMP + 31*5 + 5, 1)/)
integer, dimension(5) c_internal_rhocp1_bldgs = (/(cc, cc=ccEndESTMMP + 32*5 + 1, ccEndESTMMP + 32*5 + 5, 1)/)
integer, dimension(5) c_internal_thick2_bldgs = (/(cc, cc=ccEndESTMMP + 33*5 + 1, ccEndESTMMP + 33*5 + 5, 1)/)
integer, dimension(5) c_internal_k2_bldgs = (/(cc, cc=ccEndESTMMP + 34*5 + 1, ccEndESTMMP + 34*5 + 5, 1)/)
integer, dimension(5) c_internal_rhocp2_bldgs = (/(cc, cc=ccEndESTMMP + 35*5 + 1, ccEndESTMMP + 35*5 + 5, 1)/)
integer, dimension(5) c_internal_thick3_bldgs = (/(cc, cc=ccEndESTMMP + 36*5 + 1, ccEndESTMMP + 36*5 + 5, 1)/)
integer, dimension(5) c_internal_k3_bldgs = (/(cc, cc=ccEndESTMMP + 37*5 + 1, ccEndESTMMP + 37*5 + 5, 1)/)
integer, dimension(5) c_internal_rhocp3_bldgs = (/(cc, cc=ccEndESTMMP + 38*5 + 1, ccEndESTMMP + 38*5 + 5, 1)/)
integer, dimension(5) c_internal_thick4_bldgs = (/(cc, cc=ccEndESTMMP + 39*5 + 1, ccEndESTMMP + 39*5 + 5, 1)/)
integer, dimension(5) c_internal_k4_bldgs = (/(cc, cc=ccEndESTMMP + 40*5 + 1, ccEndESTMMP + 40*5 + 5, 1)/)
integer, dimension(5) c_internal_rhocp4_bldgs = (/(cc, cc=ccEndESTMMP + 41*5 + 1, ccEndESTMMP + 41*5 + 5, 1)/)
integer, dimension(5) c_internal_thick5_bldgs = (/(cc, cc=ccEndESTMMP + 42*5 + 1, ccEndESTMMP + 42*5 + 5, 1)/)
integer, dimension(5) c_internal_k5_bldgs = (/(cc, cc=ccEndESTMMP + 43*5 + 1, ccEndESTMMP + 43*5 + 5, 1)/)
integer, dimension(5) c_internal_rhocp5_bldgs = (/(cc, cc=ccEndESTMMP + 44*5 + 1, ccEndESTMMP + 44*5 + 5, 1)/)
integer, dimension(5) c_nroom_bldgs = (ccEndESTMMP + 44*5 + 5 + 1)
integer, dimension(5) c_alb_ibld_bldgs = (ccEndESTMMP + 44*5 + 5 + 2)
integer, dimension(5) c_em_ibld_bldgs = (ccEndESTMMP + 44*5 + 5 + 3)
integer, dimension(5) c_ch_iwall_bldgs = (ccEndESTMMP + 44*5 + 5 + 4)
integer, dimension(5) c_ch_iroof_bldgs = (ccEndESTMMP + 44*5 + 5 + 5)
integer, dimension(5) c_ch_ibld_bldgs = (ccEndESTMMP + 44*5 + 5 + 6)
integer, parameter maxncols_c = (ccEndESTMMP + 44*5 + 5 + 6)
integer, parameter ccmod = 32
integer, dimension(nsurf) cmod_state = (/(cc, cc=ccMOD + 0*nsurf + 1, ccMOD + 0*nsurf + nsurf, 1)/)
integer, dimension(nsurf) cmod_soilstate = (/(cc, cc=ccMOD + 1*nsurf + 1, ccMOD + 1*nsurf + nsurf, 1)/)
integer, dimension(nsurf) cmod_snowwaterstate = (/(cc, cc=ccMOD + 2*nsurf + 1, ccMOD + 2*nsurf + nsurf, 1)/)
integer, dimension(nsurf) cmod_snowpack = (/(cc, cc=ccMOD + 3*nsurf + 1, ccMOD + 3*nsurf + nsurf, 1)/)
integer, dimension(nsurf) cmod_snowfrac = (/(cc, cc=ccMOD + 4*nsurf + 1, ccMOD + 4*nsurf + nsurf, 1)/)
integer, dimension(nsurf) cmod_snowdens = (/(cc, cc=ccMOD + 5*nsurf + 1, ccMOD + 5*nsurf + nsurf, 1)/)
integer, parameter maxncols_cmod = ccMOD + 5*nsurf + nsurf
integer, parameter ccmds = 30
integer, dimension(nsurf) cmds_snowdens = (/(cc, cc=ccMDS + 0*nsurf + 1, ccMDS + 0*nsurf + nsurf, 1)/)
integer, parameter maxncols_cmds = ccMDS + 0*nsurf + nsurf
integer, parameter cts_iy = 1
integer, parameter cts_id = 2
integer, parameter cts_it = 3
integer, parameter cts_imin = 4
integer, parameter cts_tiair = 5
integer, parameter cts_tsurf = 6
integer, parameter cts_troof = 7
integer, parameter cts_troad = 8
integer, parameter cts_twall = 9
integer, parameter cts_twall_n = 10
integer, parameter cts_twall_e = 11
integer, parameter cts_twall_s = 12
integer, parameter cts_twall_w = 13
Variable Documentation
a1
real(kind(1d0)) allocatearray::a1
Definition at line 387 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: a1, a2, a3   !OHM coefficients, a1 [-]; a2 [h]; a3 [W m-2]
a1anohm
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::a1anohm
Definition at line 444 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids) :: a1AnOHM, a2AnOHM, a3AnOHM ! OHM coefficients, a1 [-]; a2 [h]; a3 [W m-2]
a2
real(kind(1d0)) allocatearray::a2
Definition at line 387 of file suews_ctrl_const.f95.
a2anohm
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::a2anohm
Definition at line 444 of file suews_ctrl_const.f95.
a3
real(kind(1d0)) allocatearray::a3
Definition at line 387 of file suews_ctrl_const.f95.
a3anohm
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::a3anohm
Definition at line 444 of file suews_ctrl_const.f95.
addwater
real(kind(1d0)), dimension(nsurf) allocatearray::addwater
Definition at line 203 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: AddWater       !Water from other surfaces (WGWaterDist in SUEWS_ReDistributeWater.f95) [mm]
addwaterrunoff
real(kind(1d0)), dimension(nsurf) allocatearray::addwaterrunoff
Definition at line 204 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: AddWaterRunoff !Fraction of water going to runoff/sub-surface soil (WGWaterDist) [-]
aggreguse
character(len=3*ncolumnsdataoutsuews) allocatearray::aggreguse
Definition at line 92 of file suews_ctrl_const.f95.
    CHARACTER(len=3*ncolumnsDataOutSUEWS):: AggregUse
ahprof_24hr
real(kind(1d0)), dimension(0:23, 2) allocatearray::ahprof_24hr
Definition at line 151 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: AHProf_24hr     !Anthropogenic heat profiles for (1)weekdays / (2)weekends
Referenced by suews_calculations(), and suews_translate().
alb
real(kind(1d0)), dimension(nsurf) allocatearray::alb
Definition at line 353 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: alb    !Albedo of each surface type [-]
Referenced by estm_module::estm_translate(), suews_calculations(), and suews_translate().
albdectr_id
real(kind(1d0)) allocatearray::albdectr_id
Definition at line 300 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)) :: albDecTr_id
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
albdectr_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::albdectr_id_grids
Definition at line 294 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids):: albDecTr_id_grids
Referenced by suews_translate(), and suews_translateback().
albevetr_id
real(kind(1d0)) allocatearray::albevetr_id
Definition at line 301 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)) :: albEveTr_id
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
albevetr_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::albevetr_id_grids
Definition at line 295 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids):: albEveTr_id_grids
Referenced by suews_translate(), and suews_translateback().
albgrass_id
real(kind(1d0)) allocatearray::albgrass_id
Definition at line 302 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)) :: albGrass_id
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
albgrass_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::albgrass_id_grids
Definition at line 296 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids):: albGrass_id_grids
Referenced by suews_translate(), and suews_translateback().
albmax_dectr
real(kind(1d0)) allocatearray::albmax_dectr
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
albmax_evetr
real(kind(1d0)) allocatearray::albmax_evetr
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
albmax_grass
real(kind(1d0)) allocatearray::albmax_grass
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
albmin_dectr
real(kind(1d0)) allocatearray::albmin_dectr
Definition at line 263 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: AlbMin_DecTr, &   !Min albedo for deciduous trees [-]
                      AlbMax_DecTr, &   !Max albedo for deciduous trees [-]
                      CapMin_dec, &   !Min storage capacity for deciduous trees [mm] (from input information)
                      CapMax_dec, &   !Max storage capacity for deciduous trees [mm] (from input information)
                      PorMin_dec, &  !Min porosity for deciduous trees
                      PorMax_dec, &    !Max porosity for deciduous trees
                      AlbMin_EveTr, &   !Min albedo for evergreen trees [-]
                      AlbMax_EveTr, &   !Max albedo for evergreen trees [-]
                      AlbMin_Grass, &   !Min albedo for grass [-]
                      AlbMax_Grass     !Max albedo for grass [-]
Referenced by suews_calculations(), and suews_translate().
albmin_evetr
real(kind(1d0)) allocatearray::albmin_evetr
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
albmin_grass
real(kind(1d0)) allocatearray::albmin_grass
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
alpha_bioco2
real(kind(1d0)), dimension(nvegsurf) allocatearray::alpha_bioco2
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
alpha_enh_bioco2
real(kind(1d0)), dimension(nvegsurf) allocatearray::alpha_enh_bioco2
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
anthropogenic_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::anthropogenic_coeff
Definition at line 105 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Anthropogenic_Coeff       !Coefficients for AnthropogenicEmissions
Referenced by codematchanthropogenic(), initializesurfacecharacteristics(), and overallruncontrol().
baset
real(kind(1d0)), dimension(nvegsurf) allocatearray::baset
Definition at line 324 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: BaseT            !Base temperature for growing degree days [degC]
Referenced by suews_calculations(), and suews_translate().
basete
real(kind(1d0)), dimension(nvegsurf) allocatearray::basete
Definition at line 325 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: BaseTe           !Base temperature for senescence degree days [degC]
Referenced by suews_calculations(), and suews_translate().
beta_bioco2
real(kind(1d0)), dimension(nvegsurf) allocatearray::beta_bioco2
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
beta_enh_bioco2
real(kind(1d0)), dimension(nvegsurf) allocatearray::beta_enh_bioco2
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
biogen_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::biogen_coeff
Definition at line 109 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Biogen_Coeff              !Coefficients for BiogenCO2
Referenced by codematchbiogen(), initializesurfacecharacteristics(), and overallruncontrol().
biogenco2code
real(kind(1d0)), dimension(nvegsurf) allocatearray::biogenco2code
Definition at line 336 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: BiogenCO2Code, &    !Biogenic CO2 Code for SUEWS_BiogenCO2.txt
                                           alpha_bioCO2, &
                                           beta_bioCO2, &
                                           theta_bioCO2, &
                                           alpha_enh_bioCO2, &
                                           beta_enh_bioCO2, &
                                           resp_a, &
                                           resp_b, &
                                           min_res_bioCO2
bldgsurf
integer, parameter allocatearray::bldgsurf = 2
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by checkinitial(), codematchestm_class(), estm_module::estm_translate(), initializesurfacecharacteristics(), initialstate(), nextinitial(), snow_module::snowdepletioncurve(), suews_driver::suews_cal_qs(), suews_driver::suews_cal_surf(), and suews_translate().
boanohmend
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::boanohmend
Definition at line 447 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids) :: BoAnOHMEnd              ! final Bo for interation [-]
boanohmstart
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::boanohmstart
Definition at line 446 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids) :: BoAnOHMStart            ! initial Bo for interation [-]
bsoilsurf
integer, parameter allocatearray::bsoilsurf = 6
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by checkinitial(), estm_module::estm_translate(), initializesurfacecharacteristics(), initialstate(), nextinitial(), suews_driver::suews_cal_main(), and suews_translate().
bulkalbedo
real(kind(1d0)) allocatearray::bulkalbedo
Definition at line 356 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: bulkalbedo !Bulk albedo for whole surface (areally-weighted)
c_a1_sdry
integer, dimension(nsurfincsnow) allocatearray::c_a1_sdry = (/(cc, cc=ccEndGs + 7*nsurfIncSnow + 1, ccEndGs + 7*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 580 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a1_SDry = (/(cc, cc=ccendgs + 7*nsurfincsnow + 1, &
                                                      ccendgs + 7*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a1 (summer dry)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a1_swet
integer, dimension(nsurfincsnow) allocatearray::c_a1_swet = (/(cc, cc=ccEndGs + 4*nsurfIncSnow + 1, ccEndGs + 4*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 574 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a1_SWet = (/(cc, cc=ccendgs + 4*nsurfincsnow + 1, &
                                                      ccendgs + 4*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a1 (summer wet)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a1_wdry
integer, dimension(nsurfincsnow) allocatearray::c_a1_wdry = (/(cc, cc=ccEndGs + 13*nsurfIncSnow + 1, ccEndGs + 13*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 592 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a1_WDry = (/(cc, cc=ccendgs + 13*nsurfincsnow + 1, &
                                                      ccendgs + 13*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a1 (winter dry)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a1_wwet
integer, dimension(nsurfincsnow) allocatearray::c_a1_wwet = (/(cc, cc=ccEndGs + 10*nsurfIncSnow + 1, ccEndGs + 10*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 586 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a1_WWet = (/(cc, cc=ccendgs + 10*nsurfincsnow + 1, &
                                                      ccendgs + 10*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a1 (winter wet)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a2_sdry
integer, dimension(nsurfincsnow) allocatearray::c_a2_sdry = (/(cc, cc=ccEndGs + 8*nsurfIncSnow + 1, ccEndGs + 8*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 582 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a2_SDry = (/(cc, cc=ccendgs + 8*nsurfincsnow + 1, &
                                                      ccendgs + 8*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a2 (summer dry)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a2_swet
integer, dimension(nsurfincsnow) allocatearray::c_a2_swet = (/(cc, cc=ccEndGs + 5*nsurfIncSnow + 1, ccEndGs + 5*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 576 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a2_SWet = (/(cc, cc=ccendgs + 5*nsurfincsnow + 1, &
                                                      ccendgs + 5*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a2 (summer wet)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a2_wdry
integer, dimension(nsurfincsnow) allocatearray::c_a2_wdry = (/(cc, cc=ccEndGs + 14*nsurfIncSnow + 1, ccEndGs + 14*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 594 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a2_WDry = (/(cc, cc=ccendgs + 14*nsurfincsnow + 1, &
                                                      ccendgs + 14*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a2 (winter dry)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a2_wwet
integer, dimension(nsurfincsnow) allocatearray::c_a2_wwet = (/(cc, cc=ccEndGs + 11*nsurfIncSnow + 1, ccEndGs + 11*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 588 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a2_WWet = (/(cc, cc=ccendgs + 11*nsurfincsnow + 1, &
                                                      ccendgs + 11*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a2 (winter wet)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a3_sdry
integer, dimension(nsurfincsnow) allocatearray::c_a3_sdry = (/(cc, cc=ccEndGs + 9*nsurfIncSnow + 1, ccEndGs + 9*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 584 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a3_SDry = (/(cc, cc=ccendgs + 9*nsurfincsnow + 1, &
                                                      ccendgs + 9*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a3 (summer dry)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a3_swet
integer, dimension(nsurfincsnow) allocatearray::c_a3_swet = (/(cc, cc=ccEndGs + 6*nsurfIncSnow + 1, ccEndGs + 6*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 578 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a3_SWet = (/(cc, cc=ccendgs + 6*nsurfincsnow + 1, &
                                                      ccendgs + 6*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a3 (summer wet)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a3_wdry
integer, dimension(nsurfincsnow) allocatearray::c_a3_wdry = (/(cc, cc=ccEndGs + 15*nsurfIncSnow + 1, ccEndGs + 15*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 596 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a3_WDry = (/(cc, cc=ccendgs + 15*nsurfincsnow + 1, &
                                                      ccendgs + 15*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a3 (winter dry)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_a3_wwet
integer, dimension(nsurfincsnow) allocatearray::c_a3_wwet = (/(cc, cc=ccEndGs + 12*nsurfIncSnow + 1, ccEndGs + 12*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 590 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_a3_WWet = (/(cc, cc=ccendgs + 12*nsurfincsnow + 1, &
                                                      ccendgs + 12*nsurfincsnow + nsurfincsnow, 1)/)  !OHM a3 (winter wet)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ahmin_wd
integer allocatearray::c_ahmin_wd = (ccEndO + 8)
Definition at line 619 of file suews_ctrl_const.f95.
    INTEGER :: c_AHMin_WD = (ccendo + 8)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ahmin_we
integer allocatearray::c_ahmin_we = (ccEndO + 9)
Definition at line 620 of file suews_ctrl_const.f95.
    INTEGER :: c_AHMin_WE = (ccendo + 9)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ahslopecooling_wd
integer allocatearray::c_ahslopecooling_wd = (ccEndO + 12)
Definition at line 623 of file suews_ctrl_const.f95.
    INTEGER :: c_AHSlopeCooling_WD = (ccendo + 12)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ahslopecooling_we
integer allocatearray::c_ahslopecooling_we = (ccEndO + 13)
Definition at line 624 of file suews_ctrl_const.f95.
    INTEGER :: c_AHSlopeCooling_WE = (ccendo + 13)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ahslopeheating_wd
integer allocatearray::c_ahslopeheating_wd = (ccEndO + 10)
Definition at line 621 of file suews_ctrl_const.f95.
    INTEGER :: c_AHSlopeHeating_WD = (ccendo + 10)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ahslopeheating_we
integer allocatearray::c_ahslopeheating_we = (ccEndO + 11)
Definition at line 622 of file suews_ctrl_const.f95.
    INTEGER :: c_AHSlopeHeating_WE = (ccendo + 11)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_alb_ibld
integer allocatearray::c_alb_ibld = (ccEndESTMB + 32)
Definition at line 764 of file suews_ctrl_const.f95.
    INTEGER:: c_alb_ibld = (ccendestmb + 32)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_alb_ibld_bldgs
integer, dimension(5) allocatearray::c_alb_ibld_bldgs = (ccEndESTMMP + 44*5 + 5 + 2)
Definition at line 836 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_alb_ibld_Bldgs = (ccendestmmp + 44*5 + 5 + 2)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_albmax
integer, dimension(nsurf) allocatearray::c_albmax = (/(cc, cc=ccEndSI + 1*nsurf + 1, ccEndSI + 1*nsurf + nsurf, 1)/)
Definition at line 467 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_AlbMax = (/(cc, cc=ccendsi + 1*nsurf + 1, ccendsi + 1*nsurf + nsurf, 1)/)  !Max. albedo
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_albmin
integer, dimension(nsurf) allocatearray::c_albmin = (/(cc, cc=ccEndSI + 0*nsurf + 1, ccEndSI + 0*nsurf + nsurf, 1)/)
Definition at line 466 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_AlbMin = (/(cc, cc=ccendsi + 0*nsurf + 1, ccendsi + 0*nsurf + nsurf, 1)/)  !Min. albedo
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_alpha_bioco2
integer, dimension(nvegsurf) allocatearray::c_alpha_bioco2 = (/(cc, cc=cBEndWG + 0*nvegsurf + 1, cBEndWG + 0*nvegsurf + nvegsurf, 1)/)
Definition at line 701 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_alpha_bioCO2 = (/(cc, cc=cbendwg + 0*nvegsurf + 1, cbendwg + 0*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_alpha_enh_bioco2
integer, dimension(nvegsurf) allocatearray::c_alpha_enh_bioco2 = (/(cc, cc=cBEndWG + 3*nvegsurf + 1, cBEndWG + 3*nvegsurf + nvegsurf, 1)/)
Definition at line 704 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_alpha_enh_bioCO2 = (/(cc, cc=cbendwg + 3*nvegsurf + 1, cbendwg + 3*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_baset
integer, dimension(nvegsurf) allocatearray::c_baset = (/(cc, cc=ccEndI + 0*nvegsurf + 1, ccEndI + 0*nvegsurf + nvegsurf, 1)/)
Definition at line 491 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_BaseT = (/(cc, cc=ccendi + 0*nvegsurf + 1, ccendi + 0*nvegsurf + nvegsurf, 1)/) !Base temp. for leaf-on
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_basete
integer, dimension(nvegsurf) allocatearray::c_basete = (/(cc, cc=ccEndI + 1*nvegsurf + 1, ccEndI + 1*nvegsurf + nvegsurf, 1)/)
Definition at line 492 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_BaseTe = (/(cc, cc=ccendi + 1*nvegsurf + 1, ccendi + 1*nvegsurf + nvegsurf, 1)/) !Base temp. for leaf-off
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_basethdd
integer allocatearray::c_basethdd = (ccEndO + 1)
Definition at line 612 of file suews_ctrl_const.f95.
    INTEGER :: c_BaseTHDD = (ccendo + 1)
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_beta_bioco2
integer, dimension(nvegsurf) allocatearray::c_beta_bioco2 = (/(cc, cc=cBEndWG + 1*nvegsurf + 1, cBEndWG + 1*nvegsurf + nvegsurf, 1)/)
Definition at line 702 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_beta_bioCO2 = (/(cc, cc=cbendwg + 1*nvegsurf + 1, cbendwg + 1*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_beta_enh_bioco2
integer, dimension(nvegsurf) allocatearray::c_beta_enh_bioco2 = (/(cc, cc=cBEndWG + 4*nvegsurf + 1, cBEndWG + 4*nvegsurf + nvegsurf, 1)/)
Definition at line 705 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_beta_enh_bioCO2 = (/(cc, cc=cbendwg + 4*nvegsurf + 1, cbendwg + 4*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_biogenco2code
integer, dimension(nvegsurf) allocatearray::c_biogenco2code = (/(cc, cc=ccEndI + 14*nvegsurf + 1, ccEndI + 14*nvegsurf + nvegsurf, 1)/)
Definition at line 505 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_BiogenCO2Code = (/(cc, cc=ccendi + 14*nvegsurf + 1, ccendi + 14*nvegsurf + nvegsurf, 1)/) !Biogenic CO2 Code
Referenced by initializesurfacecharacteristics().
c_ch_ibld
integer allocatearray::c_ch_ibld = (ccEndESTMB + 36)
Definition at line 768 of file suews_ctrl_const.f95.
    INTEGER:: c_CH_ibld = (ccendestmb + 36)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ch_ibld_bldgs
integer, dimension(5) allocatearray::c_ch_ibld_bldgs = (ccEndESTMMP + 44*5 + 5 + 6)
Definition at line 840 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_CH_ibld_Bldgs = (ccendestmmp + 44*5 + 5 + 6)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ch_iroof
integer allocatearray::c_ch_iroof = (ccEndESTMB + 35)
Definition at line 767 of file suews_ctrl_const.f95.
    INTEGER:: c_CH_iroof = (ccendestmb + 35)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ch_iroof_bldgs
integer, dimension(5) allocatearray::c_ch_iroof_bldgs = (ccEndESTMMP + 44*5 + 5 + 5)
Definition at line 839 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_CH_iroof_Bldgs = (ccendestmmp + 44*5 + 5 + 5)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ch_iwall
integer allocatearray::c_ch_iwall = (ccEndESTMB + 34)
Definition at line 766 of file suews_ctrl_const.f95.
    INTEGER:: c_CH_iwall = (ccendestmb + 34)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ch_iwall_bldgs
integer, dimension(5) allocatearray::c_ch_iwall_bldgs = (ccEndESTMMP + 44*5 + 5 + 4)
Definition at line 838 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_CH_iwall_Bldgs = (ccendestmmp + 44*5 + 5 + 4)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_chanohm
integer, dimension(nsurf) allocatearray::c_chanohm = (/(cc, cc=ccEndSI + 15*nsurf + 1, ccEndSI + 15*nsurf + nsurf, 1)/)
Definition at line 485 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_ChAnOHM = (/(cc, cc=ccendsi + 15*nsurf + 1, ccendsi + 15*nsurf + nsurf, 1)/) !bulk transfer coef., AnOHM TS
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_co2mwd
integer allocatearray::c_co2mwd = (ccEndO + 20)
Definition at line 631 of file suews_ctrl_const.f95.
    INTEGER :: c_CO2mWD = (ccendo + 20)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_co2mwe
integer allocatearray::c_co2mwe = (ccEndO + 21)
Definition at line 632 of file suews_ctrl_const.f95.
    INTEGER :: c_CO2mWE = (ccendo + 21)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_co2pointsource
integer allocatearray::c_co2pointsource = (ccEndO + 37)
Definition at line 648 of file suews_ctrl_const.f95.
    INTEGER :: c_CO2PointSource = (ccendo + 37)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_cpanohm
integer, dimension(nsurf) allocatearray::c_cpanohm = (/(cc, cc=ccEndSI + 13*nsurf + 1, ccEndSI + 13*nsurf + nsurf, 1)/)
Definition at line 483 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_CpAnOHM = (/(cc, cc=ccendsi + 13*nsurf + 1, ccendsi + 13*nsurf + nsurf, 1)/) !heat capacity, AnOHM TS
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_daywat
integer, dimension(7) allocatearray::c_daywat = (/(cc, cc=ccEndA + 10 + 0*7 + 1, ccEndA + 10 + 0*7 + 7, 1)/)
Definition at line 661 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(7):: c_DayWat = (/(cc, cc=ccenda + 10 + 0*7 + 1, ccenda + 10 + 0*7 + 7, 1)/)  ! Irrigation allowed on each day
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_daywatper
integer, dimension(7) allocatearray::c_daywatper = (/(cc, cc=ccEndA + 10 + 1*7 + 1, ccEndA + 10 + 1*7 + 7, 1)/)
Definition at line 662 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(7):: c_DayWatPer = (/(cc, cc=ccenda + 10 + 1*7 + 1, ccenda + 10 + 1*7 + 7, 1)/)  ! Fraction properties using irrigation allowed on each day
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_drcoef1
integer, dimension(nsurf) allocatearray::c_drcoef1 = (/(cc, cc=ccEndSI + 8*nsurf + 1, ccEndSI + 8*nsurf + nsurf, 1)/)
Definition at line 474 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_DrCoef1 = (/(cc, cc=ccendsi + 8*nsurf + 1, ccendsi + 8*nsurf + nsurf, 1)/)  !Drainage coef. 1
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_drcoef2
integer, dimension(nsurf) allocatearray::c_drcoef2 = (/(cc, cc=ccEndSI + 9*nsurf + 1, ccEndSI + 9*nsurf + nsurf, 1)/)
Definition at line 475 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_DrCoef2 = (/(cc, cc=ccendsi + 9*nsurf + 1, ccendsi + 9*nsurf + nsurf, 1)/)  !Drainage coef. 2
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_dreq
integer, dimension(nsurf) allocatearray::c_dreq = (/(cc, cc=ccEndSI + 7*nsurf + 1, ccEndSI + 7*nsurf + nsurf, 1)/)
Definition at line 473 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_DrEq = (/(cc, cc=ccendsi + 7*nsurf + 1, ccendsi + 7*nsurf + nsurf, 1)/)  !Drainage equation
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ef_umolco2perj
integer allocatearray::c_ef_umolco2perj = (ccEndO + 33)
Definition at line 644 of file suews_ctrl_const.f95.
    INTEGER :: c_EF_umolCO2perJ = (ccendo + 33)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_em_ibld
integer allocatearray::c_em_ibld = (ccEndESTMB + 33)
Definition at line 765 of file suews_ctrl_const.f95.
    INTEGER:: c_em_ibld = (ccendestmb + 33)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_em_ibld_bldgs
integer, dimension(5) allocatearray::c_em_ibld_bldgs = (ccEndESTMMP + 44*5 + 5 + 3)
Definition at line 837 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_em_ibld_Bldgs = (ccendestmmp + 44*5 + 5 + 3)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_emis
integer, dimension(nsurf) allocatearray::c_emis = (/(cc, cc=ccEndSI + 2*nsurf + 1, ccEndSI + 2*nsurf + nsurf, 1)/)
Definition at line 468 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_Emis = (/(cc, cc=ccendsi + 2*nsurf + 1, ccendsi + 2*nsurf + nsurf, 1)/)  !Emissivity
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_enef_v_jkm
integer allocatearray::c_enef_v_jkm = (ccEndO + 34)
Definition at line 645 of file suews_ctrl_const.f95.
    INTEGER :: c_EnEF_v_Jkm = (ccendo + 34)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_enprofwd
integer allocatearray::c_enprofwd = (ccEndO + 18)
Definition at line 629 of file suews_ctrl_const.f95.
    INTEGER :: c_EnProfWD = (ccendo + 18)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_enprofwe
integer allocatearray::c_enprofwe = (ccEndO + 19)
Definition at line 630 of file suews_ctrl_const.f95.
    INTEGER :: c_EnProfWE = (ccendo + 19)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_estmcode
integer, dimension(nsurfincsnow) allocatearray::c_estmcode = (/(cc, cc=ccEndGs + 18*nsurfIncSnow + 1, ccEndGs + 18*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 605 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_ESTMCode = (/(cc, cc=ccendgs + 18*nsurfincsnow + 1, &
                                                       ccendgs + 18*nsurfincsnow + nsurfincsnow, 1)/)  !ESTM code
Referenced by codematchestm(), initializesurfacecharacteristics(), and suews_translate().
c_faut
integer allocatearray::c_faut = (ccEndA + 4)
Definition at line 658 of file suews_ctrl_const.f95.
    INTEGER :: c_Faut = (ccenda + 4)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_fcef_v_kgkmwd
integer allocatearray::c_fcef_v_kgkmwd = (ccEndO + 35)
Definition at line 646 of file suews_ctrl_const.f95.
    INTEGER :: c_FcEF_v_kgkmWD = (ccendo + 35)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_fcef_v_kgkmwe
integer allocatearray::c_fcef_v_kgkmwe = (ccEndO + 36)
Definition at line 647 of file suews_ctrl_const.f95.
    INTEGER :: c_FcEF_v_kgkmWE = (ccendo + 36)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_frfossilfuel_heat
integer allocatearray::c_frfossilfuel_heat = (ccEndO + 31)
Definition at line 642 of file suews_ctrl_const.f95.
    INTEGER :: c_FrFossilFuel_Heat = (ccendo + 31)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_frfossilfuel_nonheat
integer allocatearray::c_frfossilfuel_nonheat = (ccEndO + 32)
Definition at line 643 of file suews_ctrl_const.f95.
    INTEGER :: c_FrFossilFuel_NonHeat = (ccendo + 32)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_frpddwe
integer allocatearray::c_frpddwe = (ccEndO + 30)
Definition at line 641 of file suews_ctrl_const.f95.
    INTEGER :: c_FrPDDwe = (ccendo + 30)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gddfull
integer, dimension(nvegsurf) allocatearray::c_gddfull = (/(cc, cc=ccEndI + 2*nvegsurf + 1, ccEndI + 2*nvegsurf + nvegsurf, 1)/)
Definition at line 493 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_GDDFull = (/(cc, cc=ccendi + 2*nvegsurf + 1, ccendi + 2*nvegsurf + nvegsurf, 1)/) !GDD for full LAI
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_gsg1
integer allocatearray::c_gsg1 = (ccEndSo + 1)
Definition at line 549 of file suews_ctrl_const.f95.
    INTEGER:: c_GsG1 = (ccendso + 1)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsg2
integer allocatearray::c_gsg2 = (ccEndSo + 2)
Definition at line 550 of file suews_ctrl_const.f95.
    INTEGER:: c_GsG2 = (ccendso + 2)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsg3
integer allocatearray::c_gsg3 = (ccEndSo + 3)
Definition at line 551 of file suews_ctrl_const.f95.
    INTEGER:: c_GsG3 = (ccendso + 3)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsg4
integer allocatearray::c_gsg4 = (ccEndSo + 4)
Definition at line 552 of file suews_ctrl_const.f95.
    INTEGER:: c_GsG4 = (ccendso + 4)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsg5
integer allocatearray::c_gsg5 = (ccEndSo + 5)
Definition at line 553 of file suews_ctrl_const.f95.
    INTEGER:: c_GsG5 = (ccendso + 5)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsg6
integer allocatearray::c_gsg6 = (ccEndSo + 6)
Definition at line 554 of file suews_ctrl_const.f95.
    INTEGER:: c_GsG6 = (ccendso + 6)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gskmax
integer allocatearray::c_gskmax = (ccEndSo + 11)
Definition at line 559 of file suews_ctrl_const.f95.
    INTEGER:: c_GsKmax = (ccendso + 11)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsmax
integer, dimension(nvegsurf) allocatearray::c_gsmax = (/(cc, cc=ccEndI + 8*nvegsurf + 1, ccEndI + 8*nvegsurf + nvegsurf, 1)/)
Definition at line 499 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_GsMax = (/(cc, cc=ccendi + 8*nvegsurf + 1, ccendi + 8*nvegsurf + nvegsurf, 1)/) !Max. conductance
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsmodel
integer allocatearray::c_gsmodel = (ccEndSo + 12)
Definition at line 560 of file suews_ctrl_const.f95.
    INTEGER:: c_gsModel = (ccendso + 12)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gss1
integer allocatearray::c_gss1 = (ccEndSo + 9)
Definition at line 557 of file suews_ctrl_const.f95.
    INTEGER:: c_GsS1 = (ccendso + 9)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gss2
integer allocatearray::c_gss2 = (ccEndSo + 10)
Definition at line 558 of file suews_ctrl_const.f95.
    INTEGER:: c_GsS2 = (ccendso + 10)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gsth
integer allocatearray::c_gsth = (ccEndSo + 7)
Definition at line 555 of file suews_ctrl_const.f95.
    INTEGER:: c_GsTH = (ccendso + 7)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_gstl
integer allocatearray::c_gstl = (ccEndSo + 8)
Definition at line 556 of file suews_ctrl_const.f95.
    INTEGER:: c_GsTL = (ccendso + 8)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofenusewd
integer, dimension(24) allocatearray::c_hrprofenusewd = (/(cc, cc=ccEndIr + 0*24 + 1, ccEndIr + 0*24 + 24, 1)/)
Definition at line 668 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfEnUseWD = (/(cc, cc=ccendir + 0*24 + 1, ccendir + 0*24 + 24, 1)/)  ! Energy use, weekdays
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofenusewe
integer, dimension(24) allocatearray::c_hrprofenusewe = (/(cc, cc=ccEndIr + 1*24 + 1, ccEndIr + 1*24 + 24, 1)/)
Definition at line 669 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfEnUseWE = (/(cc, cc=ccendir + 1*24 + 1, ccendir + 1*24 + 24, 1)/)  ! Energy use, weekends
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofhumactivitywd
integer, dimension(24) allocatearray::c_hrprofhumactivitywd = (/(cc, cc=ccEndIr + 8*24 + 1, ccEndIr + 8*24 + 24, 1)/)
Definition at line 676 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfHumActivityWD = (/(cc, cc=ccendir + 8*24 + 1, ccendir + 8*24 + 24, 1)/)  ! Human activity, weekdays
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofhumactivitywe
integer, dimension(24) allocatearray::c_hrprofhumactivitywe = (/(cc, cc=ccEndIr + 9*24 + 1, ccEndIr + 9*24 + 24, 1)/)
Definition at line 677 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfHumActivityWE = (/(cc, cc=ccendir + 9*24 + 1, ccendir + 9*24 + 24, 1)/)  ! Human activity, weekends
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofpopwd
integer, dimension(24) allocatearray::c_hrprofpopwd = (/(cc, cc=ccEndIr + 12*24 + 1, ccEndIr + 12*24 + 24, 1)/)
Definition at line 680 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfPopWD = (/(cc, cc=ccendir + 12*24 + 1, ccendir + 12*24 + 24, 1)/) ! Population, weekdays
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofpopwe
integer, dimension(24) allocatearray::c_hrprofpopwe = (/(cc, cc=ccEndIr + 13*24 + 1, ccEndIr + 13*24 + 24, 1)/)
Definition at line 681 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfPopWE = (/(cc, cc=ccendir + 13*24 + 1, ccendir + 13*24 + 24, 1)/) ! Population, weekends
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofsnowcwd
integer, dimension(24) allocatearray::c_hrprofsnowcwd = (/(cc, cc=ccEndIr + 6*24 + 1, ccEndIr + 6*24 + 24, 1)/)
Definition at line 674 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfSnowCWD = (/(cc, cc=ccendir + 6*24 + 1, ccendir + 6*24 + 24, 1)/)  ! Snow clearing, weekdays
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofsnowcwe
integer, dimension(24) allocatearray::c_hrprofsnowcwe = (/(cc, cc=ccEndIr + 7*24 + 1, ccEndIr + 7*24 + 24, 1)/)
Definition at line 675 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfSnowCWE = (/(cc, cc=ccendir + 7*24 + 1, ccendir + 7*24 + 24, 1)/)  ! Snow clearing, weekends
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrproftraffwd
integer, dimension(24) allocatearray::c_hrproftraffwd = (/(cc, cc=ccEndIr + 10*24 + 1, ccEndIr + 10*24 + 24, 1)/)
Definition at line 678 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfTraffWD = (/(cc, cc=ccendir + 10*24 + 1, ccendir + 10*24 + 24, 1)/) ! Traffic, weekdays
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrproftraffwe
integer, dimension(24) allocatearray::c_hrproftraffwe = (/(cc, cc=ccEndIr + 11*24 + 1, ccEndIr + 11*24 + 24, 1)/)
Definition at line 679 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfTraffWE = (/(cc, cc=ccendir + 11*24 + 1, ccendir + 11*24 + 24, 1)/) ! Traffic, weekends
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofwuautowd
integer, dimension(24) allocatearray::c_hrprofwuautowd = (/(cc, cc=ccEndIr + 4*24 + 1, ccEndIr + 4*24 + 24, 1)/)
Definition at line 672 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfWUAutoWD = (/(cc, cc=ccendir + 4*24 + 1, ccendir + 4*24 + 24, 1)/)  ! Water use, automatic, weekdays
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofwuautowe
integer, dimension(24) allocatearray::c_hrprofwuautowe = (/(cc, cc=ccEndIr + 5*24 + 1, ccEndIr + 5*24 + 24, 1)/)
Definition at line 673 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfWUAutoWE = (/(cc, cc=ccendir + 5*24 + 1, ccendir + 5*24 + 24, 1)/)  ! Water use, automatic, weekends
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofwumanuwd
integer, dimension(24) allocatearray::c_hrprofwumanuwd = (/(cc, cc=ccEndIr + 2*24 + 1, ccEndIr + 2*24 + 24, 1)/)
Definition at line 670 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfWUManuWD = (/(cc, cc=ccendir + 2*24 + 1, ccendir + 2*24 + 24, 1)/)  ! Water use, manual, weekdays
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_hrprofwumanuwe
integer, dimension(24) allocatearray::c_hrprofwumanuwe = (/(cc, cc=ccEndIr + 3*24 + 1, ccEndIr + 3*24 + 24, 1)/)
Definition at line 671 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(24):: c_HrProfWUManuWE = (/(cc, cc=ccendir + 3*24 + 1, ccendir + 3*24 + 24, 1)/)  ! Water use, manual, weekends
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ie_a
integer, dimension(3) allocatearray::c_ie_a = (/(cc, cc=ccEndA + 4 + 0*3 + 1, ccEndA + 4 + 0*3 + 3, 1)/)
Definition at line 659 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Ie_a = (/(cc, cc=ccenda + 4 + 0*3 + 1, ccenda + 4 + 0*3 + 3, 1)/)  ! Automatic irrigation coeffs
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ie_m
integer, dimension(3) allocatearray::c_ie_m = (/(cc, cc=ccEndA + 4 + 1*3 + 1, ccEndA + 4 + 1*3 + 3, 1)/)
Definition at line 660 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Ie_m = (/(cc, cc=ccenda + 4 + 1*3 + 1, ccenda + 4 + 1*3 + 3, 1)/)  ! Manual irrigation coeffs
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ieend
integer allocatearray::c_ieend = (ccEndA + 2)
Definition at line 656 of file suews_ctrl_const.f95.
    INTEGER :: c_IeEnd = (ccenda + 2)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_iestart
integer allocatearray::c_iestart = (ccEndA + 1)
Definition at line 655 of file suews_ctrl_const.f95.
    INTEGER :: c_IeStart = (ccenda + 1)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k1
integer allocatearray::c_internal_k1 = (ccEndESTMB + 17)
Definition at line 749 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_k1 = (ccendestmb + 17)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k1_bldgs
integer, dimension(5) allocatearray::c_internal_k1_bldgs = (/(cc, cc=ccEndESTMMP + 31*5 + 1, ccEndESTMMP + 31*5 + 5, 1)/)
Definition at line 821 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_k1_Bldgs = (/(cc, cc=ccendestmmp + 31*5 + 1, ccendestmmp + 31*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k2
integer allocatearray::c_internal_k2 = (ccEndESTMB + 20)
Definition at line 752 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_k2 = (ccendestmb + 20)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k2_bldgs
integer, dimension(5) allocatearray::c_internal_k2_bldgs = (/(cc, cc=ccEndESTMMP + 34*5 + 1, ccEndESTMMP + 34*5 + 5, 1)/)
Definition at line 824 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_k2_Bldgs = (/(cc, cc=ccendestmmp + 34*5 + 1, ccendestmmp + 34*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k3
integer allocatearray::c_internal_k3 = (ccEndESTMB + 23)
Definition at line 755 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_k3 = (ccendestmb + 23)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k3_bldgs
integer, dimension(5) allocatearray::c_internal_k3_bldgs = (/(cc, cc=ccEndESTMMP + 37*5 + 1, ccEndESTMMP + 37*5 + 5, 1)/)
Definition at line 827 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_k3_Bldgs = (/(cc, cc=ccendestmmp + 37*5 + 1, ccendestmmp + 37*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k4
integer allocatearray::c_internal_k4 = (ccEndESTMB + 26)
Definition at line 758 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_k4 = (ccendestmb + 26)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k4_bldgs
integer, dimension(5) allocatearray::c_internal_k4_bldgs = (/(cc, cc=ccEndESTMMP + 40*5 + 1, ccEndESTMMP + 40*5 + 5, 1)/)
Definition at line 830 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_k4_Bldgs = (/(cc, cc=ccendestmmp + 40*5 + 1, ccendestmmp + 40*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k5
integer allocatearray::c_internal_k5 = (ccEndESTMB + 29)
Definition at line 761 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_k5 = (ccendestmb + 29)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_k5_bldgs
integer, dimension(5) allocatearray::c_internal_k5_bldgs = (/(cc, cc=ccEndESTMMP + 43*5 + 1, ccEndESTMMP + 43*5 + 5, 1)/)
Definition at line 833 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_k5_Bldgs = (/(cc, cc=ccendestmmp + 43*5 + 1, ccendestmmp + 43*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp1
integer allocatearray::c_internal_rhocp1 = (ccEndESTMB + 18)
Definition at line 750 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_rhoCp1 = (ccendestmb + 18)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp1_bldgs
integer, dimension(5) allocatearray::c_internal_rhocp1_bldgs = (/(cc, cc=ccEndESTMMP + 32*5 + 1, ccEndESTMMP + 32*5 + 5, 1)/)
Definition at line 822 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_rhoCp1_Bldgs = (/(cc, cc=ccendestmmp + 32*5 + 1, ccendestmmp + 32*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp2
integer allocatearray::c_internal_rhocp2 = (ccEndESTMB + 21)
Definition at line 753 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_rhoCp2 = (ccendestmb + 21)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp2_bldgs
integer, dimension(5) allocatearray::c_internal_rhocp2_bldgs = (/(cc, cc=ccEndESTMMP + 35*5 + 1, ccEndESTMMP + 35*5 + 5, 1)/)
Definition at line 825 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_rhoCp2_Bldgs = (/(cc, cc=ccendestmmp + 35*5 + 1, ccendestmmp + 35*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp3
integer allocatearray::c_internal_rhocp3 = (ccEndESTMB + 24)
Definition at line 756 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_rhoCp3 = (ccendestmb + 24)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp3_bldgs
integer, dimension(5) allocatearray::c_internal_rhocp3_bldgs = (/(cc, cc=ccEndESTMMP + 38*5 + 1, ccEndESTMMP + 38*5 + 5, 1)/)
Definition at line 828 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_rhoCp3_Bldgs = (/(cc, cc=ccendestmmp + 38*5 + 1, ccendestmmp + 38*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp4
integer allocatearray::c_internal_rhocp4 = (ccEndESTMB + 27)
Definition at line 759 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_rhoCp4 = (ccendestmb + 27)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp4_bldgs
integer, dimension(5) allocatearray::c_internal_rhocp4_bldgs = (/(cc, cc=ccEndESTMMP + 41*5 + 1, ccEndESTMMP + 41*5 + 5, 1)/)
Definition at line 831 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_rhoCp4_Bldgs = (/(cc, cc=ccendestmmp + 41*5 + 1, ccendestmmp + 41*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp5
integer allocatearray::c_internal_rhocp5 = (ccEndESTMB + 30)
Definition at line 762 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_rhoCp5 = (ccendestmb + 30)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_rhocp5_bldgs
integer, dimension(5) allocatearray::c_internal_rhocp5_bldgs = (/(cc, cc=ccEndESTMMP + 44*5 + 1, ccEndESTMMP + 44*5 + 5, 1)/)
Definition at line 834 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_rhoCp5_Bldgs = (/(cc, cc=ccendestmmp + 44*5 + 1, ccendestmmp + 44*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick1
integer allocatearray::c_internal_thick1 = (ccEndESTMB + 16)
Definition at line 748 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_thick1 = (ccendestmb + 16)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick1_bldgs
integer, dimension(5) allocatearray::c_internal_thick1_bldgs = (/(cc, cc=ccEndESTMMP + 30*5 + 1, ccEndESTMMP + 30*5 + 5, 1)/)
Definition at line 820 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_thick1_Bldgs = (/(cc, cc=ccendestmmp + 30*5 + 1, ccendestmmp + 30*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick2
integer allocatearray::c_internal_thick2 = (ccEndESTMB + 19)
Definition at line 751 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_thick2 = (ccendestmb + 19)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick2_bldgs
integer, dimension(5) allocatearray::c_internal_thick2_bldgs = (/(cc, cc=ccEndESTMMP + 33*5 + 1, ccEndESTMMP + 33*5 + 5, 1)/)
Definition at line 823 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_thick2_Bldgs = (/(cc, cc=ccendestmmp + 33*5 + 1, ccendestmmp + 33*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick3
integer allocatearray::c_internal_thick3 = (ccEndESTMB + 22)
Definition at line 754 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_thick3 = (ccendestmb + 22)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick3_bldgs
integer, dimension(5) allocatearray::c_internal_thick3_bldgs = (/(cc, cc=ccEndESTMMP + 36*5 + 1, ccEndESTMMP + 36*5 + 5, 1)/)
Definition at line 826 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_thick3_Bldgs = (/(cc, cc=ccendestmmp + 36*5 + 1, ccendestmmp + 36*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick4
integer allocatearray::c_internal_thick4 = (ccEndESTMB + 25)
Definition at line 757 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_thick4 = (ccendestmb + 25)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick4_bldgs
integer, dimension(5) allocatearray::c_internal_thick4_bldgs = (/(cc, cc=ccEndESTMMP + 39*5 + 1, ccEndESTMMP + 39*5 + 5, 1)/)
Definition at line 829 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_thick4_Bldgs = (/(cc, cc=ccendestmmp + 39*5 + 1, ccendestmmp + 39*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick5
integer allocatearray::c_internal_thick5 = (ccEndESTMB + 28)
Definition at line 760 of file suews_ctrl_const.f95.
    INTEGER:: c_Internal_thick5 = (ccendestmb + 28)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_internal_thick5_bldgs
integer, dimension(5) allocatearray::c_internal_thick5_bldgs = (/(cc, cc=ccEndESTMMP + 42*5 + 1, ccEndESTMMP + 42*5 + 5, 1)/)
Definition at line 832 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Internal_thick5_Bldgs = (/(cc, cc=ccendestmmp + 42*5 + 1, ccendestmmp + 42*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_intwu
integer allocatearray::c_intwu = (ccEndA + 3)
Definition at line 657 of file suews_ctrl_const.f95.
    INTEGER :: c_IntWU = (ccenda + 3)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_kkanohm
integer, dimension(nsurf) allocatearray::c_kkanohm = (/(cc, cc=ccEndSI + 14*nsurf + 1, ccEndSI + 14*nsurf + nsurf, 1)/)
Definition at line 484 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_KkAnOHM = (/(cc, cc=ccendsi + 14*nsurf + 1, ccendsi + 14*nsurf + nsurf, 1)/) !heat conductivity, AnOHM TS
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ksat
integer, dimension(nsurf) allocatearray::c_ksat = (/(cc, cc=ccEndSn + 2*nsurf + 1, ccEndSn + 2*nsurf + nsurf, 1)/)
Definition at line 538 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_KSat = (/(cc, cc=ccendsn + 2*nsurf + 1, ccendsn + 2*nsurf + nsurf, 1)/)  ! Saturated hydraulic conductivity
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_laieq
integer, dimension(nvegsurf) allocatearray::c_laieq = (/(cc, cc=ccEndI + 9*nvegsurf + 1, ccEndI + 9*nvegsurf + nvegsurf, 1)/)
Definition at line 500 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_LAIEq = (/(cc, cc=ccendi + 9*nvegsurf + 1, ccendi + 9*nvegsurf + nvegsurf, 1)/) !LAI equation
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_laimax
integer, dimension(nvegsurf) allocatearray::c_laimax = (/(cc, cc=ccEndI + 5*nvegsurf + 1, ccEndI + 5*nvegsurf + nvegsurf, 1)/)
Definition at line 496 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_LAIMax = (/(cc, cc=ccendi + 5*nvegsurf + 1, ccendi + 5*nvegsurf + nvegsurf, 1)/) !Max. LAI
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_laimin
integer, dimension(nvegsurf) allocatearray::c_laimin = (/(cc, cc=ccEndI + 4*nvegsurf + 1, ccEndI + 4*nvegsurf + nvegsurf, 1)/)
Definition at line 495 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_LAIMin = (/(cc, cc=ccendi + 4*nvegsurf + 1, ccendi + 4*nvegsurf + nvegsurf, 1)/) !Min. LAI
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_leafgp1
integer, dimension(nvegsurf) allocatearray::c_leafgp1 = (/(cc, cc=ccEndI + 10*nvegsurf + 1, ccEndI + 10*nvegsurf + nvegsurf, 1)/)
Definition at line 501 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_LeafGP1 = (/(cc, cc=ccendi + 10*nvegsurf + 1, ccendi + 10*nvegsurf + nvegsurf, 1)/) !Leaf growth power 1
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_leafgp2
integer, dimension(nvegsurf) allocatearray::c_leafgp2 = (/(cc, cc=ccEndI + 11*nvegsurf + 1, ccEndI + 11*nvegsurf + nvegsurf, 1)/)
Definition at line 502 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_LeafGP2 = (/(cc, cc=ccendi + 11*nvegsurf + 1, ccendi + 11*nvegsurf + nvegsurf, 1)/) !Leaf growth power 2
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_leafop1
integer, dimension(nvegsurf) allocatearray::c_leafop1 = (/(cc, cc=ccEndI + 12*nvegsurf + 1, ccEndI + 12*nvegsurf + nvegsurf, 1)/)
Definition at line 503 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_LeafOP1 = (/(cc, cc=ccendi + 12*nvegsurf + 1, ccendi + 12*nvegsurf + nvegsurf, 1)/) !Leaf-off power 1
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_leafop2
integer, dimension(nvegsurf) allocatearray::c_leafop2 = (/(cc, cc=ccEndI + 13*nvegsurf + 1, ccEndI + 13*nvegsurf + nvegsurf, 1)/)
Definition at line 504 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_LeafOP2 = (/(cc, cc=ccendi + 13*nvegsurf + 1, ccendi + 13*nvegsurf + nvegsurf, 1)/) !Leaf-off power 2
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_maxfcmetab
integer allocatearray::c_maxfcmetab = (ccEndO + 29)
Definition at line 640 of file suews_ctrl_const.f95.
    INTEGER :: c_MaxFCMetab = (ccendo + 29)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_maxqfmetab
integer allocatearray::c_maxqfmetab = (ccEndO + 27)
Definition at line 638 of file suews_ctrl_const.f95.
    INTEGER :: c_MaxQFMetab = (ccendo + 27)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_min_res_bioco2
integer, dimension(nvegsurf) allocatearray::c_min_res_bioco2 = (/(cc, cc=cBEndWG + 7*nvegsurf + 1, cBEndWG + 7*nvegsurf + nvegsurf, 1)/)
Definition at line 708 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_min_res_bioCO2 = (/(cc, cc=cbendwg + 7*nvegsurf + 1, cbendwg + 7*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_minfcmetab
integer allocatearray::c_minfcmetab = (ccEndO + 28)
Definition at line 639 of file suews_ctrl_const.f95.
    INTEGER :: c_MinFCMetab = (ccendo + 28)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_minqfmetab
integer allocatearray::c_minqfmetab = (ccEndO + 26)
Definition at line 637 of file suews_ctrl_const.f95.
    INTEGER :: c_MinQFMetab = (ccendo + 26)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_nroom
integer allocatearray::c_nroom = (ccEndESTMB + 31)
Definition at line 763 of file suews_ctrl_const.f95.
    INTEGER:: c_nroom = (ccendestmb + 31)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_nroom_bldgs
integer, dimension(5) allocatearray::c_nroom_bldgs = (ccEndESTMMP + 44*5 + 5 + 1)
Definition at line 835 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_nroom_Bldgs = (ccendestmmp + 44*5 + 5 + 1)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_obssmdepth
integer, dimension(nsurf) allocatearray::c_obssmdepth = (/(cc, cc=ccEndSn + 5*nsurf + 1, ccEndSn + 5*nsurf + nsurf, 1)/)
Definition at line 541 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_ObsSMDepth = (/(cc, cc=ccendsn + 5*nsurf + 1, ccendsn + 5*nsurf + nsurf, 1)/)  ! Depth of SM obs
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_obssmmax
integer, dimension(nsurf) allocatearray::c_obssmmax = (/(cc, cc=ccEndSn + 6*nsurf + 1, ccEndSn + 6*nsurf + nsurf, 1)/)
Definition at line 542 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_ObsSMMax = (/(cc, cc=ccendsn + 6*nsurf + 1, ccendsn + 6*nsurf + nsurf, 1)/)  ! Obs maximum SM [kg kg-1 OR m3 m-3]
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_obssnrfrac
integer, dimension(nsurf) allocatearray::c_obssnrfrac = (/(cc, cc=ccEndSn + 7*nsurf + 1, ccEndSn + 7*nsurf + nsurf, 1)/)
Definition at line 543 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_ObsSNRFrac = (/(cc, cc=ccendsn + 7*nsurf + 1, ccendsn + 7*nsurf + nsurf, 1)/)  ! Obs fraction of soil without rocks
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ohmcode_sdry
integer, dimension(nsurfincsnow) allocatearray::c_ohmcode_sdry = (/(cc, cc=ccEndGs + 1*nsurfIncSnow + 1, ccEndGs + 1*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 568 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_OHMCode_SDry = (/(cc, cc=ccendgs + 1*nsurfincsnow + 1, &
                                                           ccendgs + 1*nsurfincsnow + nsurfincsnow, 1)/)  !OHM code (summer dry)
Referenced by codematchohm(), and initializesurfacecharacteristics().
c_ohmcode_swet
integer, dimension(nsurfincsnow) allocatearray::c_ohmcode_swet = (/(cc, cc=ccEndGs + 0*nsurfIncSnow + 1, ccEndGs + 0*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 566 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_OHMCode_SWet = (/(cc, cc=ccendgs + 0*nsurfincsnow + 1, &
                                                           ccendgs + 0*nsurfincsnow + nsurfincsnow, 1)/)  !OHM code (summer wet)
Referenced by codematchohm(), and initializesurfacecharacteristics().
c_ohmcode_wdry
integer, dimension(nsurfincsnow) allocatearray::c_ohmcode_wdry = (/(cc, cc=ccEndGs + 3*nsurfIncSnow + 1, ccEndGs + 3*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 572 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_OHMCode_WDry = (/(cc, cc=ccendgs + 3*nsurfincsnow + 1, &
                                                           ccendgs + 3*nsurfincsnow + nsurfincsnow, 1)/)  !OHM code (winter dry)
Referenced by codematchohm(), and initializesurfacecharacteristics().
c_ohmcode_wwet
integer, dimension(nsurfincsnow) allocatearray::c_ohmcode_wwet = (/(cc, cc=ccEndGs + 2*nsurfIncSnow + 1, ccEndGs + 2*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 570 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_OHMCode_WWet = (/(cc, cc=ccendgs + 2*nsurfincsnow + 1, &
                                                           ccendgs + 2*nsurfincsnow + nsurfincsnow, 1)/)  !OHM code (winter wet)
Referenced by codematchohm(), and initializesurfacecharacteristics().
c_ohmthresh_sw
integer, dimension(nsurfincsnow) allocatearray::c_ohmthresh_sw = (/(cc, cc=ccEndGs + 16*nsurfIncSnow + 1, ccEndGs + 16*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 599 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_OHMThresh_SW = (/(cc, cc=ccendgs + 16*nsurfincsnow + 1, &
                                                           ccendgs + 16*nsurfincsnow + nsurfincsnow, 1)/)  !OHM Threshold (summer/winter)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_ohmthresh_wd
integer, dimension(nsurfincsnow) allocatearray::c_ohmthresh_wd = (/(cc, cc=ccEndGs + 17*nsurfIncSnow + 1, ccEndGs + 17*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 601 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurfIncSnow):: c_OHMThresh_WD = (/(cc, cc=ccendgs + 17*nsurfincsnow + 1, &
                                                           ccendgs + 17*nsurfincsnow + nsurfincsnow, 1)/)  !OHM Threshold (wet/dry)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_popprofwd
integer allocatearray::c_popprofwd = (ccEndO + 24)
Definition at line 635 of file suews_ctrl_const.f95.
    INTEGER :: c_PopProfWD = (ccendo + 24)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_popprofwe
integer allocatearray::c_popprofwe = (ccEndO + 25)
Definition at line 636 of file suews_ctrl_const.f95.
    INTEGER :: c_PopProfWE = (ccendo + 25)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_porositymax
integer, dimension(nvegsurf) allocatearray::c_porositymax = (/(cc, cc=ccEndI + 7*nvegsurf + 1, ccEndI + 7*nvegsurf + nvegsurf, 1)/)
Definition at line 498 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_PorosityMax = (/(cc, cc=ccendi + 7*nvegsurf + 1, ccendi + 7*nvegsurf + nvegsurf, 1)/) !Max. Porosity
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_porositymin
integer, dimension(nvegsurf) allocatearray::c_porositymin = (/(cc, cc=ccEndI + 6*nvegsurf + 1, ccEndI + 6*nvegsurf + nvegsurf, 1)/)
Definition at line 497 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_PorosityMin = (/(cc, cc=ccendi + 6*nvegsurf + 1, ccendi + 6*nvegsurf + nvegsurf, 1)/) !Min. Porosity
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_qf_a1
integer allocatearray::c_qf_a1 = (ccEndO + 2)
Definition at line 613 of file suews_ctrl_const.f95.
    INTEGER :: c_QF_A1 = (ccendo + 2)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_qf_a2
integer allocatearray::c_qf_a2 = (ccEndO + 5)
Definition at line 616 of file suews_ctrl_const.f95.
    INTEGER :: c_QF_A2 = (ccendo + 5)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_qf_b1
integer allocatearray::c_qf_b1 = (ccEndO + 3)
Definition at line 614 of file suews_ctrl_const.f95.
    INTEGER :: c_QF_B1 = (ccendo + 3)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_qf_b2
integer allocatearray::c_qf_b2 = (ccEndO + 6)
Definition at line 617 of file suews_ctrl_const.f95.
    INTEGER :: c_QF_B2 = (ccendo + 6)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_qf_c1
integer allocatearray::c_qf_c1 = (ccEndO + 4)
Definition at line 615 of file suews_ctrl_const.f95.
    INTEGER :: c_QF_C1 = (ccendo + 4)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_qf_c2
integer allocatearray::c_qf_c2 = (ccEndO + 7)
Definition at line 618 of file suews_ctrl_const.f95.
    INTEGER :: c_QF_C2 = (ccendo + 7)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_resp_a
integer, dimension(nvegsurf) allocatearray::c_resp_a = (/(cc, cc=cBEndWG + 5*nvegsurf + 1, cBEndWG + 5*nvegsurf + nvegsurf, 1)/)
Definition at line 706 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_resp_a = (/(cc, cc=cbendwg + 5*nvegsurf + 1, cbendwg + 5*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_resp_b
integer, dimension(nvegsurf) allocatearray::c_resp_b = (/(cc, cc=cBEndWG + 6*nvegsurf + 1, cBEndWG + 6*nvegsurf + nvegsurf, 1)/)
Definition at line 707 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_resp_b = (/(cc, cc=cbendwg + 6*nvegsurf + 1, cbendwg + 6*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_sddfull
integer, dimension(nvegsurf) allocatearray::c_sddfull = (/(cc, cc=ccEndI + 3*nvegsurf + 1, ccEndI + 3*nvegsurf + nvegsurf, 1)/)
Definition at line 494 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(NVegSurf):: c_SDDFull = (/(cc, cc=ccendi + 3*nvegsurf + 1, ccendi + 3*nvegsurf + nvegsurf, 1)/) !SDD for start of leaf-fall
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_snowalbmax
integer allocatearray::c_snowalbmax = (ccEndW + 4)
Definition at line 519 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowAlbMax = (ccendw + 4)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowalbmin
integer allocatearray::c_snowalbmin = (ccEndW + 3)
Definition at line 518 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowAlbMin = (ccendw + 3)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowcrwmax
integer allocatearray::c_snowcrwmax = (ccEndW + 14)
Definition at line 529 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowCRWMax = (ccendw + 14)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowcrwmin
integer allocatearray::c_snowcrwmin = (ccEndW + 13)
Definition at line 528 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowCRWMin = (ccendw + 13)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowemis
integer allocatearray::c_snowemis = (ccEndW + 6)
Definition at line 521 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowEmis = (ccendw + 6)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowlimpat
integer, dimension(nsurf) allocatearray::c_snowlimpat = (/(cc, cc=ccEndSI + 11*nsurf + 1, ccEndSI + 11*nsurf + nsurf, 1)/)
Definition at line 479 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_SnowLimPat = (/(cc, cc=ccendsi + 11*nsurf + 1, ccendsi + 11*nsurf + nsurf, 1)/) !Snow limit for patchiness
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowlimrem
integer, dimension(nsurf) allocatearray::c_snowlimrem = (/(cc, cc=ccEndSI + 12*nsurf + 1, ccEndSI + 12*nsurf + nsurf, 1)/)
Definition at line 481 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_SnowLimRem = (/(cc, cc=ccendsi + 12*nsurf + 1, ccendsi + 12*nsurf + nsurf, 1)/) !Snow limit for removal
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowplimalb
integer allocatearray::c_snowplimalb = (ccEndW + 9)
Definition at line 524 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowPLimAlb = (ccendw + 9)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowplimsnow
integer allocatearray::c_snowplimsnow = (ccEndW + 15)
Definition at line 530 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowPLimSnow = (ccendw + 15)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowrmfactor
integer allocatearray::c_snowrmfactor = (ccEndW + 1)
Definition at line 516 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowRMFactor = (ccendw + 1)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowsdmax
integer allocatearray::c_snowsdmax = (ccEndW + 11)
Definition at line 526 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowSDMax = (ccendw + 11)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowsdmin
integer allocatearray::c_snowsdmin = (ccEndW + 10)
Definition at line 525 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowSDMin = (ccendw + 10)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowtau_a
integer allocatearray::c_snowtau_a = (ccEndW + 7)
Definition at line 522 of file suews_ctrl_const.f95.
    INTEGER:: c_Snowtau_a = (ccendw + 7)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowtau_f
integer allocatearray::c_snowtau_f = (ccEndW + 8)
Definition at line 523 of file suews_ctrl_const.f95.
    INTEGER:: c_Snowtau_f = (ccendw + 8)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowtau_r
integer allocatearray::c_snowtau_r = (ccEndW + 12)
Definition at line 527 of file suews_ctrl_const.f95.
    INTEGER:: c_Snowtau_r = (ccendw + 12)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_snowtmfactor
integer allocatearray::c_snowtmfactor = (ccEndW + 2)
Definition at line 517 of file suews_ctrl_const.f95.
    INTEGER:: c_SnowTMFactor = (ccendw + 2)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_soildens
integer, dimension(nsurf) allocatearray::c_soildens = (/(cc, cc=ccEndSn + 3*nsurf + 1, ccEndSn + 3*nsurf + nsurf, 1)/)
Definition at line 539 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_SoilDens = (/(cc, cc=ccendsn + 3*nsurf + 1, ccendsn + 3*nsurf + nsurf, 1)/)  ! Soil Density
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_soildepth
integer, dimension(nsurf) allocatearray::c_soildepth = (/(cc, cc=ccEndSn + 0*nsurf + 1, ccEndSn + 0*nsurf + nsurf, 1)/)
Definition at line 536 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_SoilDepth = (/(cc, cc=ccendsn + 0*nsurf + 1, ccendsn + 0*nsurf + nsurf, 1)/)  ! Volumetric SM capacity
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_soilinfrate
integer, dimension(nsurf) allocatearray::c_soilinfrate = (/(cc, cc=ccEndSn + 4*nsurf + 1, ccEndSn + 4*nsurf + nsurf, 1)/)
Definition at line 540 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_SoilInfRate = (/(cc, cc=ccendsn + 4*nsurf + 1, ccendsn + 4*nsurf + nsurf, 1)/)  ! Soil infiltration rate
Referenced by initializesurfacecharacteristics().
c_soilstcap
integer, dimension(nsurf) allocatearray::c_soilstcap = (/(cc, cc=ccEndSn + 1*nsurf + 1, ccEndSn + 1*nsurf + nsurf, 1)/)
Definition at line 537 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_SoilStCap = (/(cc, cc=ccendsn + 1*nsurf + 1, ccendsn + 1*nsurf + nsurf, 1)/)  ! Volumetric SM capacity
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_soiltcode
integer, dimension(nsurf) allocatearray::c_soiltcode = (/(cc, cc=ccEndSI + 10*nsurf + 1, ccEndSI + 10*nsurf + nsurf, 1)/)
Definition at line 476 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_SoilTCode = (/(cc, cc=ccendsi + 10*nsurf + 1, ccendsi + 10*nsurf + nsurf, 1)/)  !Soil type code
Referenced by initializesurfacecharacteristics().
c_statelimit
integer, dimension(nsurf) allocatearray::c_statelimit = (/(cc, cc=ccEndSI + 6*nsurf + 1, ccEndSI + 6*nsurf + nsurf, 1)/)
Definition at line 472 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_StateLimit = (/(cc, cc=ccendsi + 6*nsurf + 1, ccendsi + 6*nsurf + nsurf, 1)/)  !Limit for surface state [mm]
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_stormax
integer, dimension(nsurf) allocatearray::c_stormax = (/(cc, cc=ccEndSI + 4*nsurf + 1, ccEndSI + 4*nsurf + nsurf, 1)/)
Definition at line 470 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_StorMax = (/(cc, cc=ccendsi + 4*nsurf + 1, ccendsi + 4*nsurf + nsurf, 1)/)  !Max. storage capacity (canopy)
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_stormin
integer, dimension(nsurf) allocatearray::c_stormin = (/(cc, cc=ccEndSI + 3*nsurf + 1, ccEndSI + 3*nsurf + nsurf, 1)/)
Definition at line 469 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_StorMin = (/(cc, cc=ccendsi + 3*nsurf + 1, ccendsi + 3*nsurf + nsurf, 1)/)  !Min. storage capacity (canopy)
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_surf_k1
integer, dimension(nsurfincsnow) allocatearray::c_surf_k1 = (/(cc, cc=ccEndB + 1*nsurfIncSnow + 1, ccEndB + 1*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 716 of file suews_ctrl_const.f95.
   INTEGER, DIMENSION(nsurfIncSnow):: c_Surf_k1 = (/(cc, cc=ccendb + 1*nsurfincsnow + 1, ccendb + 1*nsurfincsnow + nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k1_bldgs
integer, dimension(5) allocatearray::c_surf_k1_bldgs = (/(cc, cc=ccEndESTMMP + 1*5 + 1, ccEndESTMMP + 1*5 + 5, 1)/)
Definition at line 791 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_k1_Bldgs = (/(cc, cc=ccendestmmp + 1*5 + 1, ccendestmmp + 1*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k1_paved
integer, dimension(3) allocatearray::c_surf_k1_paved = (/(cc, cc=ccEndESTMM + 1*3 + 1, ccEndESTMM + 1*3 + 3, 1)/)
Definition at line 773 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_k1_Paved = (/(cc, cc=ccendestmm + 1*3 + 1, ccendestmm + 1*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k2
integer, dimension(nsurfincsnow) allocatearray::c_surf_k2 = (/(cc, cc=ccEndB + 4*nsurfIncSnow + 1, ccEndB + 4*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 719 of file suews_ctrl_const.f95.
   INTEGER, DIMENSION(nsurfIncSnow):: c_Surf_k2 = (/(cc, cc=ccendb + 4*nsurfincsnow + 1, ccendb + 4*nsurfincsnow + nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k2_bldgs
integer, dimension(5) allocatearray::c_surf_k2_bldgs = (/(cc, cc=ccEndESTMMP + 4*5 + 1, ccEndESTMMP + 4*5 + 5, 1)/)
Definition at line 794 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_k2_Bldgs = (/(cc, cc=ccendestmmp + 4*5 + 1, ccendestmmp + 4*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k2_paved
integer, dimension(3) allocatearray::c_surf_k2_paved = (/(cc, cc=ccEndESTMM + 4*3 + 1, ccEndESTMM + 4*3 + 3, 1)/)
Definition at line 776 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_k2_Paved = (/(cc, cc=ccendestmm + 4*3 + 1, ccendestmm + 4*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k3
integer, dimension(nsurfincsnow) allocatearray::c_surf_k3 = (/(cc, cc=ccEndB + 7*nsurfIncSnow + 1, ccEndB + 7*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 722 of file suews_ctrl_const.f95.
   INTEGER, DIMENSION(nsurfIncSnow):: c_Surf_k3 = (/(cc, cc=ccendb + 7*nsurfincsnow + 1, ccendb + 7*nsurfincsnow + nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k3_bldgs
integer, dimension(5) allocatearray::c_surf_k3_bldgs = (/(cc, cc=ccEndESTMMP + 7*5 + 1, ccEndESTMMP + 7*5 + 5, 1)/)
Definition at line 797 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_k3_Bldgs = (/(cc, cc=ccendestmmp + 7*5 + 1, ccendestmmp + 7*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k3_paved
integer, dimension(3) allocatearray::c_surf_k3_paved = (/(cc, cc=ccEndESTMM + 7*3 + 1, ccEndESTMM + 7*3 + 3, 1)/)
Definition at line 779 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_k3_Paved = (/(cc, cc=ccendestmm + 7*3 + 1, ccendestmm + 7*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k4
integer, dimension(nsurfincsnow) allocatearray::c_surf_k4 = (/(cc, cc=ccEndB + 10*nsurfIncSnow + 1, ccEndB + 10*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 725 of file suews_ctrl_const.f95.
 INTEGER, DIMENSION(nsurfIncSnow):: c_Surf_k4 = (/(cc, cc=ccendb + 10*nsurfincsnow + 1, ccendb + 10*nsurfincsnow + nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k4_bldgs
integer, dimension(5) allocatearray::c_surf_k4_bldgs = (/(cc, cc=ccEndESTMMP + 10*5 + 1, ccEndESTMMP + 10*5 + 5, 1)/)
Definition at line 800 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_k4_Bldgs = (/(cc, cc=ccendestmmp + 10*5 + 1, ccendestmmp + 10*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k4_paved
integer, dimension(3) allocatearray::c_surf_k4_paved = (/(cc, cc=ccEndESTMM + 10*3 + 1, ccEndESTMM + 10*3 + 3, 1)/)
Definition at line 782 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_k4_Paved = (/(cc, cc=ccendestmm + 10*3 + 1, ccendestmm + 10*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k5
integer, dimension(nsurfincsnow) allocatearray::c_surf_k5 = (/(cc, cc=ccEndB + 13*nsurfIncSnow + 1, ccEndB + 13*nsurfIncSnow + nsurfIncSnow, 1)/)
Definition at line 728 of file suews_ctrl_const.f95.
 INTEGER, DIMENSION(nsurfIncSnow):: c_Surf_k5 = (/(cc, cc=ccendb + 13*nsurfincsnow + 1, ccendb + 13*nsurfincsnow + nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k5_bldgs
integer, dimension(5) allocatearray::c_surf_k5_bldgs = (/(cc, cc=ccEndESTMMP + 13*5 + 1, ccEndESTMMP + 13*5 + 5, 1)/)
Definition at line 803 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_k5_Bldgs = (/(cc, cc=ccendestmmp + 13*5 + 1, ccendestmmp + 13*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_k5_paved
integer, dimension(3) allocatearray::c_surf_k5_paved = (/(cc, cc=ccEndESTMM + 13*3 + 1, ccEndESTMM + 13*3 + 3, 1)/)
Definition at line 785 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_k5_Paved = (/(cc, cc=ccendestmm + 13*3 + 1, ccendestmm + 13*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp1
integer, dimension(nsurfincsnow) allocatearray::c_surf_rhocp1 = (/(cc, cc=ccEndB+ 2*nsurfIncSnow+1,ccEndB+ 2*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 717 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_rhoCp1  = (/(cc, cc=ccendb+ 2*nsurfincsnow+1,ccendb+ 2*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp1_bldgs
integer, dimension(5) allocatearray::c_surf_rhocp1_bldgs = (/(cc, cc=ccEndESTMMP + 2*5 + 1, ccEndESTMMP + 2*5 + 5, 1)/)
Definition at line 792 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_rhoCp1_Bldgs = (/(cc, cc=ccendestmmp + 2*5 + 1, ccendestmmp + 2*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp1_paved
integer, dimension(3) allocatearray::c_surf_rhocp1_paved = (/(cc, cc=ccEndESTMM + 2*3 + 1, ccEndESTMM + 2*3 + 3, 1)/)
Definition at line 774 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_rhoCp1_Paved = (/(cc, cc=ccendestmm + 2*3 + 1, ccendestmm + 2*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp2
integer, dimension(nsurfincsnow) allocatearray::c_surf_rhocp2 = (/(cc, cc=ccEndB+ 5*nsurfIncSnow+1,ccEndB+ 5*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 720 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_rhoCp2  = (/(cc, cc=ccendb+ 5*nsurfincsnow+1,ccendb+ 5*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp2_bldgs
integer, dimension(5) allocatearray::c_surf_rhocp2_bldgs = (/(cc, cc=ccEndESTMMP + 5*5 + 1, ccEndESTMMP + 5*5 + 5, 1)/)
Definition at line 795 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_rhoCp2_Bldgs = (/(cc, cc=ccendestmmp + 5*5 + 1, ccendestmmp + 5*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp2_paved
integer, dimension(3) allocatearray::c_surf_rhocp2_paved = (/(cc, cc=ccEndESTMM + 5*3 + 1, ccEndESTMM + 5*3 + 3, 1)/)
Definition at line 777 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_rhoCp2_Paved = (/(cc, cc=ccendestmm + 5*3 + 1, ccendestmm + 5*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp3
integer, dimension(nsurfincsnow) allocatearray::c_surf_rhocp3 = (/(cc, cc=ccEndB+ 8*nsurfIncSnow+1,ccEndB+ 8*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 723 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_rhoCp3  = (/(cc, cc=ccendb+ 8*nsurfincsnow+1,ccendb+ 8*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp3_bldgs
integer, dimension(5) allocatearray::c_surf_rhocp3_bldgs = (/(cc, cc=ccEndESTMMP + 8*5 + 1, ccEndESTMMP + 8*5 + 5, 1)/)
Definition at line 798 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_rhoCp3_Bldgs = (/(cc, cc=ccendestmmp + 8*5 + 1, ccendestmmp + 8*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp3_paved
integer, dimension(3) allocatearray::c_surf_rhocp3_paved = (/(cc, cc=ccEndESTMM + 8*3 + 1, ccEndESTMM + 8*3 + 3, 1)/)
Definition at line 780 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_rhoCp3_Paved = (/(cc, cc=ccendestmm + 8*3 + 1, ccendestmm + 8*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp4
integer, dimension(nsurfincsnow) allocatearray::c_surf_rhocp4 = (/(cc, cc=ccEndB+11*nsurfIncSnow+1,ccEndB+11*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 726 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_rhoCp4  = (/(cc, cc=ccendb+11*nsurfincsnow+1,ccendb+11*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp4_bldgs
integer, dimension(5) allocatearray::c_surf_rhocp4_bldgs = (/(cc, cc=ccEndESTMMP + 11*5 + 1, ccEndESTMMP + 11*5 + 5, 1)/)
Definition at line 801 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_rhoCp4_Bldgs = (/(cc, cc=ccendestmmp + 11*5 + 1, ccendestmmp + 11*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp4_paved
integer, dimension(3) allocatearray::c_surf_rhocp4_paved = (/(cc, cc=ccEndESTMM + 11*3 + 1, ccEndESTMM + 11*3 + 3, 1)/)
Definition at line 783 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_rhoCp4_Paved = (/(cc, cc=ccendestmm + 11*3 + 1, ccendestmm + 11*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp5
integer, dimension(nsurfincsnow) allocatearray::c_surf_rhocp5 = (/(cc, cc=ccEndB+14*nsurfIncSnow+1,ccEndB+14*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 729 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_rhoCp5  = (/(cc, cc=ccendb+14*nsurfincsnow+1,ccendb+14*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp5_bldgs
integer, dimension(5) allocatearray::c_surf_rhocp5_bldgs = (/(cc, cc=ccEndESTMMP + 14*5 + 1, ccEndESTMMP + 14*5 + 5, 1)/)
Definition at line 804 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_rhoCp5_Bldgs = (/(cc, cc=ccendestmmp + 14*5 + 1, ccendestmmp + 14*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_rhocp5_paved
integer, dimension(3) allocatearray::c_surf_rhocp5_paved = (/(cc, cc=ccEndESTMM + 14*3 + 1, ccEndESTMM + 14*3 + 3, 1)/)
Definition at line 786 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_rhoCp5_Paved = (/(cc, cc=ccendestmm + 14*3 + 1, ccendestmm + 14*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick1
integer, dimension(nsurfincsnow) allocatearray::c_surf_thick1 = (/(cc, cc=ccEndB+ 0*nsurfIncSnow+1,ccEndB+ 0*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 715 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_thick1  = (/(cc, cc=ccendb+ 0*nsurfincsnow+1,ccendb+ 0*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick1_bldgs
integer, dimension(5) allocatearray::c_surf_thick1_bldgs = (/(cc, cc=ccEndESTMMP + 0*5 + 1, ccEndESTMMP + 0*5 + 5, 1)/)
Definition at line 790 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_thick1_Bldgs = (/(cc, cc=ccendestmmp + 0*5 + 1, ccendestmmp + 0*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick1_paved
integer, dimension(3) allocatearray::c_surf_thick1_paved = (/(cc, cc=ccEndESTMM + 0*3 + 1, ccEndESTMM + 0*3 + 3, 1)/)
Definition at line 772 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_thick1_Paved = (/(cc, cc=ccendestmm + 0*3 + 1, ccendestmm + 0*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick2
integer, dimension(nsurfincsnow) allocatearray::c_surf_thick2 = (/(cc, cc=ccEndB+ 3*nsurfIncSnow+1,ccEndB+ 3*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 718 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_thick2  = (/(cc, cc=ccendb+ 3*nsurfincsnow+1,ccendb+ 3*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick2_bldgs
integer, dimension(5) allocatearray::c_surf_thick2_bldgs = (/(cc, cc=ccEndESTMMP + 3*5 + 1, ccEndESTMMP + 3*5 + 5, 1)/)
Definition at line 793 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_thick2_Bldgs = (/(cc, cc=ccendestmmp + 3*5 + 1, ccendestmmp + 3*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick2_paved
integer, dimension(3) allocatearray::c_surf_thick2_paved = (/(cc, cc=ccEndESTMM + 3*3 + 1, ccEndESTMM + 3*3 + 3, 1)/)
Definition at line 775 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_thick2_Paved = (/(cc, cc=ccendestmm + 3*3 + 1, ccendestmm + 3*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick3
integer, dimension(nsurfincsnow) allocatearray::c_surf_thick3 = (/(cc, cc=ccEndB+ 6*nsurfIncSnow+1,ccEndB+ 6*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 721 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_thick3  = (/(cc, cc=ccendb+ 6*nsurfincsnow+1,ccendb+ 6*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick3_bldgs
integer, dimension(5) allocatearray::c_surf_thick3_bldgs = (/(cc, cc=ccEndESTMMP + 6*5 + 1, ccEndESTMMP + 6*5 + 5, 1)/)
Definition at line 796 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_thick3_Bldgs = (/(cc, cc=ccendestmmp + 6*5 + 1, ccendestmmp + 6*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick3_paved
integer, dimension(3) allocatearray::c_surf_thick3_paved = (/(cc, cc=ccEndESTMM + 6*3 + 1, ccEndESTMM + 6*3 + 3, 1)/)
Definition at line 778 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_thick3_Paved = (/(cc, cc=ccendestmm + 6*3 + 1, ccendestmm + 6*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick4
integer, dimension(nsurfincsnow) allocatearray::c_surf_thick4 = (/(cc, cc=ccEndB+ 9*nsurfIncSnow+1,ccEndB+ 9*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 724 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_thick4  = (/(cc, cc=ccendb+ 9*nsurfincsnow+1,ccendb+ 9*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick4_bldgs
integer, dimension(5) allocatearray::c_surf_thick4_bldgs = (/(cc, cc=ccEndESTMMP + 9*5 + 1, ccEndESTMMP + 9*5 + 5, 1)/)
Definition at line 799 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_thick4_Bldgs = (/(cc, cc=ccendestmmp + 9*5 + 1, ccendestmmp + 9*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick4_paved
integer, dimension(3) allocatearray::c_surf_thick4_paved = (/(cc, cc=ccEndESTMM + 9*3 + 1, ccEndESTMM + 9*3 + 3, 1)/)
Definition at line 781 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_thick4_Paved = (/(cc, cc=ccendestmm + 9*3 + 1, ccendestmm + 9*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick5
integer, dimension(nsurfincsnow) allocatearray::c_surf_thick5 = (/(cc, cc=ccEndB+12*nsurfIncSnow+1,ccEndB+12*nsurfIncSnow+nsurfIncSnow, 1)/)
Definition at line 727 of file suews_ctrl_const.f95.
   INTEGER,DIMENSION(nsurfIncSnow):: c_Surf_thick5  = (/(cc, cc=ccendb+12*nsurfincsnow+1,ccendb+12*nsurfincsnow+nsurfincsnow, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick5_bldgs
integer, dimension(5) allocatearray::c_surf_thick5_bldgs = (/(cc, cc=ccEndESTMMP + 12*5 + 1, ccEndESTMMP + 12*5 + 5, 1)/)
Definition at line 802 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Surf_thick5_Bldgs = (/(cc, cc=ccendestmmp + 12*5 + 1, ccendestmmp + 12*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_surf_thick5_paved
integer, dimension(3) allocatearray::c_surf_thick5_paved = (/(cc, cc=ccEndESTMM + 12*3 + 1, ccEndESTMM + 12*3 + 3, 1)/)
Definition at line 784 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(3):: c_Surf_thick5_Paved = (/(cc, cc=ccendestmm + 12*3 + 1, ccendestmm + 12*3 + 3, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_tcriticcooling_wd
integer allocatearray::c_tcriticcooling_wd = (ccEndO + 17)
Definition at line 628 of file suews_ctrl_const.f95.
    INTEGER :: c_TCriticCooling_WD = (ccendo + 17)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_tcriticcooling_we
integer allocatearray::c_tcriticcooling_we = (ccEndO + 16)
Definition at line 627 of file suews_ctrl_const.f95.
    INTEGER :: c_TCriticCooling_WE = (ccendo + 16)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_tcriticheating_wd
integer allocatearray::c_tcriticheating_wd = (ccEndO + 15)
Definition at line 626 of file suews_ctrl_const.f95.
    INTEGER :: c_TCriticHeating_WD = (ccendo + 15)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_tcriticheating_we
integer allocatearray::c_tcriticheating_we = (ccEndO + 14)
Definition at line 625 of file suews_ctrl_const.f95.
    INTEGER :: c_TCriticHeating_WE = (ccendo + 14)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_theta_bioco2
integer, dimension(nvegsurf) allocatearray::c_theta_bioco2 = (/(cc, cc=cBEndWG + 2*nvegsurf + 1, cBEndWG + 2*nvegsurf + nvegsurf, 1)/)
Definition at line 703 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: c_theta_bioCO2 = (/(cc, cc=cbendwg + 2*nvegsurf + 1, cbendwg + 2*nvegsurf + nvegsurf, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_trafficunits
integer allocatearray::c_trafficunits = (ccEndO + 38)
Definition at line 649 of file suews_ctrl_const.f95.
    INTEGER :: c_TrafficUnits = (ccendo + 38)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_traffprofwd
integer allocatearray::c_traffprofwd = (ccEndO + 22)
Definition at line 633 of file suews_ctrl_const.f95.
    INTEGER :: c_TraffProfWD = (ccendo + 22)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_traffprofwe
integer allocatearray::c_traffprofwe = (ccEndO + 23)
Definition at line 634 of file suews_ctrl_const.f95.
    INTEGER :: c_TraffProfWE = (ccendo + 23)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k1
integer allocatearray::c_wall_k1 = (ccEndESTMB + 2)
Definition at line 734 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_k1 = (ccendestmb + 2)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k1_bldgs
integer, dimension(5) allocatearray::c_wall_k1_bldgs = (/(cc, cc=ccEndESTMMP + 16*5 + 1, ccEndESTMMP + 16*5 + 5, 1)/)
Definition at line 806 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_k1_Bldgs = (/(cc, cc=ccendestmmp + 16*5 + 1, ccendestmmp + 16*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k2
integer allocatearray::c_wall_k2 = (ccEndESTMB + 5)
Definition at line 737 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_k2 = (ccendestmb + 5)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k2_bldgs
integer, dimension(5) allocatearray::c_wall_k2_bldgs = (/(cc, cc=ccEndESTMMP + 19*5 + 1, ccEndESTMMP + 19*5 + 5, 1)/)
Definition at line 809 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_k2_Bldgs = (/(cc, cc=ccendestmmp + 19*5 + 1, ccendestmmp + 19*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k3
integer allocatearray::c_wall_k3 = (ccEndESTMB + 8)
Definition at line 740 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_k3 = (ccendestmb + 8)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k3_bldgs
integer, dimension(5) allocatearray::c_wall_k3_bldgs = (/(cc, cc=ccEndESTMMP + 22*5 + 1, ccEndESTMMP + 22*5 + 5, 1)/)
Definition at line 812 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_k3_Bldgs = (/(cc, cc=ccendestmmp + 22*5 + 1, ccendestmmp + 22*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k4
integer allocatearray::c_wall_k4 = (ccEndESTMB + 11)
Definition at line 743 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_k4 = (ccendestmb + 11)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k4_bldgs
integer, dimension(5) allocatearray::c_wall_k4_bldgs = (/(cc, cc=ccEndESTMMP + 25*5 + 1, ccEndESTMMP + 25*5 + 5, 1)/)
Definition at line 815 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_k4_Bldgs = (/(cc, cc=ccendestmmp + 25*5 + 1, ccendestmmp + 25*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k5
integer allocatearray::c_wall_k5 = (ccEndESTMB + 14)
Definition at line 746 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_k5 = (ccendestmb + 14)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_k5_bldgs
integer, dimension(5) allocatearray::c_wall_k5_bldgs = (/(cc, cc=ccEndESTMMP + 28*5 + 1, ccEndESTMMP + 28*5 + 5, 1)/)
Definition at line 818 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_k5_Bldgs = (/(cc, cc=ccendestmmp + 28*5 + 1, ccendestmmp + 28*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp1
integer allocatearray::c_wall_rhocp1 = (ccEndESTMB + 3)
Definition at line 735 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_rhoCp1 = (ccendestmb + 3)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp1_bldgs
integer, dimension(5) allocatearray::c_wall_rhocp1_bldgs = (/(cc, cc=ccEndESTMMP + 17*5 + 1, ccEndESTMMP + 17*5 + 5, 1)/)
Definition at line 807 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_rhoCp1_Bldgs = (/(cc, cc=ccendestmmp + 17*5 + 1, ccendestmmp + 17*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp2
integer allocatearray::c_wall_rhocp2 = (ccEndESTMB + 6)
Definition at line 738 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_rhoCp2 = (ccendestmb + 6)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp2_bldgs
integer, dimension(5) allocatearray::c_wall_rhocp2_bldgs = (/(cc, cc=ccEndESTMMP + 20*5 + 1, ccEndESTMMP + 20*5 + 5, 1)/)
Definition at line 810 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_rhoCp2_Bldgs = (/(cc, cc=ccendestmmp + 20*5 + 1, ccendestmmp + 20*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp3
integer allocatearray::c_wall_rhocp3 = (ccEndESTMB + 9)
Definition at line 741 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_rhoCp3 = (ccendestmb + 9)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp3_bldgs
integer, dimension(5) allocatearray::c_wall_rhocp3_bldgs = (/(cc, cc=ccEndESTMMP + 23*5 + 1, ccEndESTMMP + 23*5 + 5, 1)/)
Definition at line 813 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_rhoCp3_Bldgs = (/(cc, cc=ccendestmmp + 23*5 + 1, ccendestmmp + 23*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp4
integer allocatearray::c_wall_rhocp4 = (ccEndESTMB + 12)
Definition at line 744 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_rhoCp4 = (ccendestmb + 12)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp4_bldgs
integer, dimension(5) allocatearray::c_wall_rhocp4_bldgs = (/(cc, cc=ccEndESTMMP + 26*5 + 1, ccEndESTMMP + 26*5 + 5, 1)/)
Definition at line 816 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_rhoCp4_Bldgs = (/(cc, cc=ccendestmmp + 26*5 + 1, ccendestmmp + 26*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp5
integer allocatearray::c_wall_rhocp5 = (ccEndESTMB + 15)
Definition at line 747 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_rhoCp5 = (ccendestmb + 15)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_rhocp5_bldgs
integer, dimension(5) allocatearray::c_wall_rhocp5_bldgs = (/(cc, cc=ccEndESTMMP + 29*5 + 1, ccEndESTMMP + 29*5 + 5, 1)/)
Definition at line 819 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_rhoCp5_Bldgs = (/(cc, cc=ccendestmmp + 29*5 + 1, ccendestmmp + 29*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick1
integer allocatearray::c_wall_thick1 = (ccEndESTMB + 1)
Definition at line 733 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_thick1 = (ccendestmb + 1)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick1_bldgs
integer, dimension(5) allocatearray::c_wall_thick1_bldgs = (/(cc, cc=ccEndESTMMP + 15*5 + 1, ccEndESTMMP + 15*5 + 5, 1)/)
Definition at line 805 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_thick1_Bldgs = (/(cc, cc=ccendestmmp + 15*5 + 1, ccendestmmp + 15*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick2
integer allocatearray::c_wall_thick2 = (ccEndESTMB + 4)
Definition at line 736 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_thick2 = (ccendestmb + 4)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick2_bldgs
integer, dimension(5) allocatearray::c_wall_thick2_bldgs = (/(cc, cc=ccEndESTMMP + 18*5 + 1, ccEndESTMMP + 18*5 + 5, 1)/)
Definition at line 808 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_thick2_Bldgs = (/(cc, cc=ccendestmmp + 18*5 + 1, ccendestmmp + 18*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick3
integer allocatearray::c_wall_thick3 = (ccEndESTMB + 7)
Definition at line 739 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_thick3 = (ccendestmb + 7)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick3_bldgs
integer, dimension(5) allocatearray::c_wall_thick3_bldgs = (/(cc, cc=ccEndESTMMP + 21*5 + 1, ccEndESTMMP + 21*5 + 5, 1)/)
Definition at line 811 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_thick3_Bldgs = (/(cc, cc=ccendestmmp + 21*5 + 1, ccendestmmp + 21*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick4
integer allocatearray::c_wall_thick4 = (ccEndESTMB + 10)
Definition at line 742 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_thick4 = (ccendestmb + 10)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick4_bldgs
integer, dimension(5) allocatearray::c_wall_thick4_bldgs = (/(cc, cc=ccEndESTMMP + 24*5 + 1, ccEndESTMMP + 24*5 + 5, 1)/)
Definition at line 814 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_thick4_Bldgs = (/(cc, cc=ccendestmmp + 24*5 + 1, ccendestmmp + 24*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick5
integer allocatearray::c_wall_thick5 = (ccEndESTMB + 13)
Definition at line 745 of file suews_ctrl_const.f95.
    INTEGER:: c_Wall_thick5 = (ccendestmb + 13)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wall_thick5_bldgs
integer, dimension(5) allocatearray::c_wall_thick5_bldgs = (/(cc, cc=ccEndESTMMP + 27*5 + 1, ccEndESTMMP + 27*5 + 5, 1)/)
Definition at line 817 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: c_Wall_thick5_Bldgs = (/(cc, cc=ccendestmmp + 27*5 + 1, ccendestmmp + 27*5 + 5, 1)/)
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_waterdepth
integer allocatearray::c_waterdepth = (ccEndP + 1)
Definition at line 510 of file suews_ctrl_const.f95.
    INTEGER:: c_WaterDepth = (ccendp + 1)
Referenced by initializesurfacecharacteristics(), initialstate(), and suews_translate().
c_wetthresh
integer, dimension(nsurf) allocatearray::c_wetthresh = (/(cc, cc=ccEndSI + 5*nsurf + 1, ccEndSI + 5*nsurf + nsurf, 1)/)
Definition at line 471 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WetThresh = (/(cc, cc=ccendsi + 5*nsurf + 1, ccendsi + 5*nsurf + nsurf, 1)/)  !Threshold for wet evaporation [mm]
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtobldgs
integer, dimension(nsurf) allocatearray::c_wgtobldgs = (/(cc, cc=ccEndPr + 1*nsurf + 1, ccEndPr + 1*nsurf + nsurf, 1)/)
Definition at line 688 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToBldgs = (/(cc, cc=ccendpr + 1*nsurf + 1, ccendpr + 1*nsurf + nsurf, 1)/) !Water dist to Bldgs
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtobsoil
integer, dimension(nsurf) allocatearray::c_wgtobsoil = (/(cc, cc=ccEndPr + 5*nsurf + 1, ccEndPr + 5*nsurf + nsurf, 1)/)
Definition at line 692 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToBSoil = (/(cc, cc=ccendpr + 5*nsurf + 1, ccendpr + 5*nsurf + nsurf, 1)/) !Water dist to BSoil
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtodectr
integer, dimension(nsurf) allocatearray::c_wgtodectr = (/(cc, cc=ccEndPr + 3*nsurf + 1, ccEndPr + 3*nsurf + nsurf, 1)/)
Definition at line 690 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToDecTr = (/(cc, cc=ccendpr + 3*nsurf + 1, ccendpr + 3*nsurf + nsurf, 1)/) !Water dist to DecTr
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtoevetr
integer, dimension(nsurf) allocatearray::c_wgtoevetr = (/(cc, cc=ccEndPr + 2*nsurf + 1, ccEndPr + 2*nsurf + nsurf, 1)/)
Definition at line 689 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToEveTr = (/(cc, cc=ccendpr + 2*nsurf + 1, ccendpr + 2*nsurf + nsurf, 1)/) !Water dist to EveTr
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtograss
integer, dimension(nsurf) allocatearray::c_wgtograss = (/(cc, cc=ccEndPr + 4*nsurf + 1, ccEndPr + 4*nsurf + nsurf, 1)/)
Definition at line 691 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToGrass = (/(cc, cc=ccendpr + 4*nsurf + 1, ccendpr + 4*nsurf + nsurf, 1)/) !Water dist to Grass
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtopaved
integer, dimension(nsurf) allocatearray::c_wgtopaved = (/(cc, cc=ccEndPr + 0*nsurf + 1, ccEndPr + 0*nsurf + nsurf, 1)/)
Definition at line 687 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToPaved = (/(cc, cc=ccendpr + 0*nsurf + 1, ccendpr + 0*nsurf + nsurf, 1)/) !Water dist to Paved
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtorunoff
integer, dimension(nsurf) allocatearray::c_wgtorunoff = (/(cc, cc=ccEndPr + 7*nsurf + 1, ccEndPr + 7*nsurf + nsurf, 1)/)
Definition at line 694 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToRunoff = (/(cc, cc=ccendpr + 7*nsurf + 1, ccendpr + 7*nsurf + nsurf, 1)/) !Water dist to runoff
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtosoilstore
integer, dimension(nsurf) allocatearray::c_wgtosoilstore = (/(cc, cc=ccEndPr + 8*nsurf + 1, ccEndPr + 8*nsurf + nsurf, 1)/)
Definition at line 695 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToSoilStore = (/(cc, cc=ccendpr + 8*nsurf + 1, ccendpr + 8*nsurf + nsurf, 1)/) !Water dist to sub-surface soil
Referenced by initializesurfacecharacteristics(), and suews_translate().
c_wgtowater
integer, dimension(nsurf) allocatearray::c_wgtowater = (/(cc, cc=ccEndPr + 6*nsurf + 1, ccEndPr + 6*nsurf + nsurf, 1)/)
Definition at line 693 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: c_WGToWater = (/(cc, cc=ccendpr + 6*nsurf + 1, ccendpr + 6*nsurf + nsurf, 1)/) !Water dist to Water
Referenced by initializesurfacecharacteristics(), and suews_translate().
capmax_dec
real(kind(1d0)) allocatearray::capmax_dec
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
capmin_dec
real(kind(1d0)) allocatearray::capmin_dec
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
cbendwg
integer, parameter allocatearray::cbendwg = (ccEndPr + 8*nsurf + nsurf)
Definition at line 698 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cBEndWG = (ccendpr + 8*nsurf + nsurf)
cc
integer allocatearray::cc
Definition at line 462 of file suews_ctrl_const.f95.
    INTEGER:: cc    !Column counter
ccenda
integer, parameter allocatearray::ccenda = (ccEndO + 38)
Definition at line 652 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndA = (ccendo + 38)
ccendb
integer, parameter allocatearray::ccendb = (cBEndWG + 7*nvegsurf + nvegsurf)
Definition at line 711 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndB = (cbendwg + 7*nvegsurf + nvegsurf)
ccendestmb
integer, parameter allocatearray::ccendestmb = (ccEndB + 14*nsurfIncSnow + nsurfIncSnow)
Definition at line 731 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndESTMB = (ccendb + 14*nsurfincsnow + nsurfincsnow)
ccendestmm
integer, parameter allocatearray::ccendestmm = (ccEndESTMB + 36)
Definition at line 770 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndESTMM = (ccendestmb + 36)
ccendestmmp
integer, parameter allocatearray::ccendestmmp = (ccEndESTMM + 14*3 + 3)
Definition at line 788 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndESTMMP = (ccendestmm + 14*3 + 3)
ccendgs
integer, parameter allocatearray::ccendgs = (ccEndSo + 12)
Definition at line 563 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndGs = (ccendso + 12)
ccendi
integer, parameter allocatearray::ccendi = (ccEndSI + 15*nsurf + nsurf)
Definition at line 488 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndI = (ccendsi + 15*nsurf + nsurf) !add columns for AnOHM, AnOHM TS
ccendir
integer, parameter allocatearray::ccendir = (ccEndA + 10 + 1*7 + 7)
Definition at line 665 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndIr = (ccenda + 10 + 1*7 + 7)
ccendo
integer, parameter allocatearray::ccendo = (ccEndGs + 18*nsurfIncSnow + nsurfIncSnow)
Definition at line 609 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndO = (ccendgs + 18*nsurfincsnow + nsurfincsnow)
ccendp
integer, parameter allocatearray::ccendp = (ccEndI + 14*nvegsurf + nvegsurf)
Definition at line 507 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndP = (ccendi + 14*nvegsurf + nvegsurf)
ccendpr
integer, parameter allocatearray::ccendpr = (ccEndIr + 13*24 + 24)
Definition at line 684 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndPr = (ccendir + 13*24 + 24)
ccendsi
integer, parameter allocatearray::ccendsi = ncolumnsSiteSelect
Definition at line 463 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndSI = ncolumnssiteselect
ccendsn
integer, parameter allocatearray::ccendsn = (ccEndW + 15)
Definition at line 533 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndSn = (ccendw + 15)
ccendso
integer, parameter allocatearray::ccendso = (ccEndSn + 7*nsurf + nsurf)
Definition at line 546 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndSo = (ccendsn + 7*nsurf + nsurf)
ccendw
integer, parameter allocatearray::ccendw = (ccEndP + 1)
Definition at line 513 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccEndW = (ccendp + 1)
ccmds
integer, parameter allocatearray::ccmds = 30
Definition at line 862 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccMDS = 30
ccmod
integer, parameter allocatearray::ccmod = 32
Definition at line 848 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ccMOD = 32
chang
real(kind(1d0)), dimension(nsurf) allocatearray::chang
Definition at line 206 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: chang          !Change in state [mm]
changsnow
real(kind(1d0)), dimension(nsurf) allocatearray::changsnow
Definition at line 401 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: changSnow, &       !Change in snowpack in mm
                                        maxSnowVol, &      !! Maximum snow volume
                                        SnowWater, &  !!Liquid water in the snow pack of ith surface
                                        ev_snow, &          !!Evaporation from snowpack in mm
                                        mw_ind, &           !Melt water from individual surface in mm
                                        mw_indDay, &        !!Melt water per day from each surface type in m3
                                        runoffSnow, &       !!Runoff from snowpack in mm and in m3
                                        SnowDens, &        !Density of snow
                                        SnowFrac, &         !!Surface fraction of snow cover
                                        iceFrac, &
                                        snowInit, &
                                        snowDepth, &       !Depth of snow in cm
                                        SnowToSurf, &      !Meltwater flowing from snow to surface
                                        volSWE, &
                                        StateFraction, &   !Fraction of state that can freeze
                                        freezMelt, &       !Amount of freezing meltwater in mm for the ith surface area
                                        Qm_freezState, &   !Heat by freezing of surface state
                                        freezState, &      !Amount of freezing state in mm for the ith surface area
                                        FreezStateVol, &
                                        Qm_melt, &         !Heat consumption by snow melt
                                        Qm_rain, &         !Heat by rain falling on snow
                                        rainOnSnow, &      !Liquid precipitation falling on snow ()
                                        SnowPackLimit, &
                                        deltaQi
chanohm
real(kind(1d0)), dimension(nsurf) allocatearray::chanohm
Definition at line 450 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: chAnOHM ! bulk transfer coef. [-]
Referenced by suews_calculations(), and suews_translate().
cmds_snowdens
integer, dimension(nsurf) allocatearray::cmds_snowdens = (/(cc, cc=ccMDS + 0*nsurf + 1, ccMDS + 0*nsurf + nsurf, 1)/)
Definition at line 863 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: cMDS_SnowDens = (/(cc, cc=ccmds + 0*nsurf + 1, ccmds + 0*nsurf + nsurf, 1)/)  !Snow density
Referenced by initialstate(), suews_translate(), and suews_translateback().
cmod_snowdens
integer, dimension(nsurf) allocatearray::cmod_snowdens = (/(cc, cc=ccMOD + 5*nsurf + 1, ccMOD + 5*nsurf + nsurf, 1)/)
Definition at line 854 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: cMOD_SnowDens = (/(cc, cc=ccmod + 5*nsurf + 1, ccmod + 5*nsurf + nsurf, 1)/)  !Snow density
cmod_snowfrac
integer, dimension(nsurf) allocatearray::cmod_snowfrac = (/(cc, cc=ccMOD + 4*nsurf + 1, ccMOD + 4*nsurf + nsurf, 1)/)
Definition at line 853 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: cMOD_SnowFrac = (/(cc, cc=ccmod + 4*nsurf + 1, ccmod + 4*nsurf + nsurf, 1)/)  !Snow fraction
Referenced by initialstate(), suews_translate(), and suews_translateback().
cmod_snowpack
integer, dimension(nsurf) allocatearray::cmod_snowpack = (/(cc, cc=ccMOD + 3*nsurf + 1, ccMOD + 3*nsurf + nsurf, 1)/)
Definition at line 852 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: cMOD_SnowPack = (/(cc, cc=ccmod + 3*nsurf + 1, ccmod + 3*nsurf + nsurf, 1)/)  !SWE
Referenced by initialstate(), suews_translate(), and suews_translateback().
cmod_snowwaterstate
integer, dimension(nsurf) allocatearray::cmod_snowwaterstate = (/(cc, cc=ccMOD + 2*nsurf + 1, ccMOD + 2*nsurf + nsurf, 1)/)
Definition at line 851 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: cMOD_SnowWaterState = (/(cc, cc=ccmod + 2*nsurf + 1, ccmod + 2*nsurf + nsurf, 1)/)  !Liquid (melted) water
Referenced by initialstate(), suews_translate(), and suews_translateback().
cmod_soilstate
integer, dimension(nsurf) allocatearray::cmod_soilstate = (/(cc, cc=ccMOD + 1*nsurf + 1, ccMOD + 1*nsurf + nsurf, 1)/)
Definition at line 850 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: cMOD_SoilState = (/(cc, cc=ccmod + 1*nsurf + 1, ccmod + 1*nsurf + nsurf, 1)/)  !Below ground state (soil store)
Referenced by initialstate(), suews_translate(), and suews_translateback().
cmod_state
integer, dimension(nsurf) allocatearray::cmod_state = (/(cc, cc=ccMOD + 0*nsurf + 1, ccMOD + 0*nsurf + nsurf, 1)/)
Definition at line 849 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: cMOD_State = (/(cc, cc=ccmod + 0*nsurf + 1, ccmod + 0*nsurf + nsurf, 1)/)  !Above ground state
Referenced by initialstate(), suews_translate(), and suews_translateback().
colnosuse
character(len=4*ncolumnsdataoutsuews) allocatearray::colnosuse
Definition at line 93 of file suews_ctrl_const.f95.
    CHARACTER(len=4*ncolumnsDataOutSUEWS):: ColNosUse
conductance_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::conductance_coeff
Definition at line 102 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Conductance_Coeff         !Coefficients for conductances
Referenced by codematchconductance(), initializesurfacecharacteristics(), and overallruncontrol().
conifsurf
integer, parameter allocatearray::conifsurf = 3
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by checkinitial(), estm_module::estm_translate(), initializesurfacecharacteristics(), initialstate(), nextinitial(), suews_driver::suews_cal_main(), suews_driver::suews_cal_qn(), suews_driver::suews_cal_surf(), and suews_translate().
cpanohm
real(kind(1d0)), dimension(nsurf) allocatearray::cpanohm
Definition at line 448 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: cpAnOHM ! heat capacity [J m-3 K-1]
Referenced by suews_calculations(), and suews_translate().
ctp_enusewd
integer allocatearray::ctp_enusewd = 1
Definition at line 165 of file suews_ctrl_const.f95.
    INTEGER:: cTP_EnUseWD = 1, &
              ctp_enusewe = 2, &
              ctp_wumanuwd = 3, &
              ctp_wumanuwe = 4, &
              ctp_wuautowd = 5, &
              ctp_wuautowe = 6, &
              ctp_snowcwd = 7, &
              ctp_snowcwe = 8, &
              ctp_humactivitywd = 9, &
              ctp_humactivitywe = 10, &
              ctp_traffprofwd = 11, &
              ctp_traffprofwe = 12, &
              ctp_popprofwd = 13, &
              ctp_popprofwe = 14
ctp_enusewe
integer allocatearray::ctp_enusewe = 2
Definition at line 165 of file suews_ctrl_const.f95.
ctp_humactivitywd
integer allocatearray::ctp_humactivitywd = 9
Definition at line 165 of file suews_ctrl_const.f95.
ctp_humactivitywe
integer allocatearray::ctp_humactivitywe = 10
Definition at line 165 of file suews_ctrl_const.f95.
ctp_popprofwd
integer allocatearray::ctp_popprofwd = 13
Definition at line 165 of file suews_ctrl_const.f95.
ctp_popprofwe
integer allocatearray::ctp_popprofwe = 14
Definition at line 165 of file suews_ctrl_const.f95.
ctp_snowcwd
integer allocatearray::ctp_snowcwd = 7
Definition at line 165 of file suews_ctrl_const.f95.
ctp_snowcwe
integer allocatearray::ctp_snowcwe = 8
Definition at line 165 of file suews_ctrl_const.f95.
ctp_traffprofwd
integer allocatearray::ctp_traffprofwd = 11
Definition at line 165 of file suews_ctrl_const.f95.
ctp_traffprofwe
integer allocatearray::ctp_traffprofwe = 12
Definition at line 165 of file suews_ctrl_const.f95.
ctp_wuautowd
integer allocatearray::ctp_wuautowd = 5
Definition at line 165 of file suews_ctrl_const.f95.
ctp_wuautowe
integer allocatearray::ctp_wuautowe = 6
Definition at line 165 of file suews_ctrl_const.f95.
ctp_wumanuwd
integer allocatearray::ctp_wumanuwd = 3
Definition at line 165 of file suews_ctrl_const.f95.
ctp_wumanuwe
integer allocatearray::ctp_wumanuwe = 4
Definition at line 165 of file suews_ctrl_const.f95.
cts_id
integer, parameter allocatearray::cts_id = 2
Definition at line 872 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_id = 2
cts_imin
integer, parameter allocatearray::cts_imin = 4
Definition at line 874 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_imin = 4
cts_it
integer, parameter allocatearray::cts_it = 3
Definition at line 873 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_it = 3
cts_iy
integer, parameter allocatearray::cts_iy = 1
Definition at line 871 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_iy = 1
cts_tiair
integer, parameter allocatearray::cts_tiair = 5
Definition at line 875 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Tiair = 5
Referenced by estm_module::estm_translate().
cts_troad
integer, parameter allocatearray::cts_troad = 8
Definition at line 878 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Troad = 8
Referenced by estm_module::estm_translate().
cts_troof
integer, parameter allocatearray::cts_troof = 7
Definition at line 877 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Troof = 7
Referenced by estm_module::estm_translate().
cts_tsurf
integer, parameter allocatearray::cts_tsurf = 6
Definition at line 876 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Tsurf = 6
cts_twall
integer, parameter allocatearray::cts_twall = 9
Definition at line 879 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Twall = 9
Referenced by estm_module::estm_translate().
cts_twall_e
integer, parameter allocatearray::cts_twall_e = 11
Definition at line 881 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Twall_e = 11
cts_twall_n
integer, parameter allocatearray::cts_twall_n = 10
Definition at line 880 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Twall_n = 10
cts_twall_s
integer, parameter allocatearray::cts_twall_s = 12
Definition at line 882 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Twall_s = 12
cts_twall_w
integer, parameter allocatearray::cts_twall_w = 13
Definition at line 883 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: cTs_Twall_w = 13
dailystatefirstopen
real(kind(1d0)), dimension(:), allocatable allocatearray::dailystatefirstopen
Definition at line 119 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: DailyStateFirstOpen
Referenced by suews_program().
dailystateline
real(kind(1d0)), dimension(ncolumnsdataoutdailystate - 5) allocatearray::dailystateline
Definition at line 134 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutDailyState - 5)::DailyStateLine   ! output of DailyState results per each timestep
Referenced by suews_calculations().
dataoutbl
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::dataoutbl
Definition at line 123 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: dataOutBL            !CBL output matrix
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::nbl(), ctrl_output::suews_output_nc_grp(), ctrl_output::suews_output_txt_grp(), and suews_program().
dataoutdailystate
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::dataoutdailystate
Definition at line 127 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: dataOutDailyState    !DailyState output array
Referenced by suews_calculations(), ctrl_output::suews_output_nc_grp(), ctrl_output::suews_output_txt_grp(), and suews_program().
dataoutestm
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::dataoutestm
Definition at line 126 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: dataOutESTM          !ESTM output matrix
Referenced by suews_calculations(), ctrl_output::suews_output_nc_grp(), ctrl_output::suews_output_txt_grp(), and suews_program().
dataoutlineestm
real(kind(1d0)), dimension(27) allocatearray::dataoutlineestm
Definition at line 162 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(27)  :: dataOutLineESTM !ESTM output for the current timestep and grid
Referenced by suews_calculations().
dataoutlinersl
real(kind(1d0)), dimension(ncolumnsdataoutrsl - 5) allocatearray::dataoutlinersl
Definition at line 133 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutRSL - 5)      ::dataOutLineRSL  ! output of snow results per each timestep
Referenced by suews_calculations().
dataoutlinesnow
real(kind(1d0)), dimension(ncolumnsdataoutsnow - 5) allocatearray::dataoutlinesnow
Definition at line 132 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutSnow - 5)      ::dataOutLineSnow  ! output of snow results per each timestep
Referenced by suews_calculations().
dataoutlinesuews
real(kind(1d0)), dimension(ncolumnsdataoutsuews - 5) allocatearray::dataoutlinesuews
Definition at line 131 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutSUEWS - 5)     ::dataOutLineSUEWS ! output of SUEWS results per each timestep
Referenced by suews_calculations().
dataoutrsl
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::dataoutrsl
Definition at line 122 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: dataOutRSL              !Main data output matrix
Referenced by suews_calculations(), ctrl_output::suews_output_txt_grp(), and suews_program().
dataoutsnow
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::dataoutsnow
Definition at line 125 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: dataOutSnow          !Main data output matrix
Referenced by suews_calculations(), ctrl_output::suews_output_nc_grp(), ctrl_output::suews_output_txt_grp(), and suews_program().
dataoutsol
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::dataoutsol
Definition at line 124 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: dataOutSOL           !SOLWEIG POI output matrix
Referenced by ctrl_output::suews_output_nc_grp(), ctrl_output::suews_output_txt_grp(), and suews_program().
dataoutsuews
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::dataoutsuews
Definition at line 121 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: dataOutSUEWS              !Main data output matrix
Referenced by suews_calculations(), ctrl_output::suews_output_nc_grp(), ctrl_output::suews_output_txt_grp(), and suews_program().
datetimeline
real(kind(1d0)), dimension(5) allocatearray::datetimeline
Definition at line 130 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(5)                          ::datetimeLine     ! output of datetime info per each timestep
Referenced by suews_calculations().
decidcap_id
real(kind(1d0)) allocatearray::decidcap_id
Definition at line 299 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)) :: DecidCap_id
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
decidcap_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::decidcap_id_grids
Definition at line 293 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids):: DecidCap_id_grids
Referenced by suews_translate(), and suews_translateback().
decidsurf
integer, parameter allocatearray::decidsurf = 4
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by checkinitial(), estm_module::estm_translate(), initializesurfacecharacteristics(), initialstate(), nextinitial(), suews_driver::suews_cal_main(), suews_driver::suews_cal_qn(), suews_driver::suews_cal_surf(), and suews_translate().
deg2rad
real(kind(1d0)), parameter allocatearray::deg2rad = 0.017453292
Definition at line 379 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), PARAMETER   :: DEG2RAD = 0.017453292, &
                                    rad2deg = 57.29577951, &
                                    sigma_sb = 5.67e-8
deltaqi
real(kind(1d0)), dimension(nsurf) allocatearray::deltaqi
Definition at line 401 of file suews_ctrl_const.f95.
dqndt
real(kind(1d0)) allocatearray::dqndt
Definition at line 395 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), suews_translate(), and suews_translateback().
dqndt_grids
real(kind(1d0)), dimension(:), allocatable allocatearray::dqndt_grids
Definition at line 394 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE::dqndt_grids, dqnsdt_grids
Referenced by suews_program(), suews_translate(), and suews_translateback().
dqnsdt
real(kind(1d0)) allocatearray::dqnsdt
Definition at line 396 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), suews_translate(), and suews_translateback().
dqnsdt_grids
real(kind(1d0)), dimension(:), allocatable allocatearray::dqnsdt_grids
Definition at line 394 of file suews_ctrl_const.f95.
Referenced by suews_program(), suews_translate(), and suews_translateback().
drain
real(kind(1d0)), dimension(nsurf) allocatearray::drain
Definition at line 207 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: drain          !Drainage of each surface type [mm]
emis
real(kind(1d0)), dimension(nsurf) allocatearray::emis
Definition at line 354 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: emis   !Emissivity of each surface type [-]
Referenced by estm_module::estm_translate(), suews_calculations(), and suews_translate().
estmcoefficients_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::estmcoefficients_coeff
Definition at line 104 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::ESTMCoefficients_Coeff    !Coefficients for ESTMCoefficients   ! S.O. 04 Feb 2016
Referenced by codematchestm(), codematchestm_class(), initializesurfacecharacteristics(), and overallruncontrol().
estmforcingdata
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::estmforcingdata
Definition at line 117 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: ESTMForcingData      !Array for ESTM forcing data
Referenced by metdisagg::disaggregateestm(), estm_module::estm_translate(), estm_module::suews_getestmdata(), suews_program(), and suews_translate().
estmfordisagg
real(kind(1d0)), dimension(:, :), allocatable allocatearray::estmfordisagg
Definition at line 139 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE:: ESTMForDisagg           !Array for original ESTM forcing data (for disaggregation)
Referenced by metdisagg::disaggregateestm().
estmfordisaggnext
real(kind(1d0)), dimension(:), allocatable allocatearray::estmfordisaggnext
Definition at line 140 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm().
estmfordisaggprev
real(kind(1d0)), dimension(:), allocatable allocatearray::estmfordisaggprev
Definition at line 140 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: ESTMForDisaggPrev, ESTMForDisaggNext !Stores last and next row of ESTM data
Referenced by metdisagg::disaggregateestm().
ev_snow
real(kind(1d0)), dimension(nsurf) allocatearray::ev_snow
Definition at line 401 of file suews_ctrl_const.f95.
evap
real(kind(1d0)), dimension(nsurf) allocatearray::evap
Definition at line 208 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: evap           !Evaporation from each surface type [mm]
excesssurf
integer, parameter allocatearray::excesssurf = 8
Definition at line 186 of file suews_ctrl_const.f95.
formatuse
character(len=14*ncolumnsdataoutsuews) allocatearray::formatuse
Definition at line 89 of file suews_ctrl_const.f95.
formatusenosep
character(len=14*ncolumnsdataoutsuews) allocatearray::formatusenosep
Definition at line 89 of file suews_ctrl_const.f95.
freezmelt
real(kind(1d0)), dimension(nsurf) allocatearray::freezmelt
Definition at line 401 of file suews_ctrl_const.f95.
freezstate
real(kind(1d0)), dimension(nsurf) allocatearray::freezstate
Definition at line 401 of file suews_ctrl_const.f95.
freezstatevol
real(kind(1d0)), dimension(nsurf) allocatearray::freezstatevol
Definition at line 401 of file suews_ctrl_const.f95.
gdd_id
real(kind(1d0)), dimension(5) allocatearray::gdd_id
Definition at line 251 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5)        :: GDD_id, GDD_id_prev     !Growing Degree Days (see SUEWS_DailyState.f95)
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
gdd_id_grids
real(kind(1d0)), dimension(5, maxnumberofgrids) allocatearray::gdd_id_grids
Definition at line 281 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, MaxNumberOfGrids):: GDD_id_grids
Referenced by suews_translate(), and suews_translateback().
gdd_id_prev
real(kind(1d0)), dimension(5) allocatearray::gdd_id_prev
Definition at line 251 of file suews_ctrl_const.f95.
Referenced by suews_translate().
gddfull
real(kind(1d0)), dimension(nvegsurf) allocatearray::gddfull
Definition at line 326 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: GDDFull          !Growing degree days needed for full capacity [degC]
Referenced by suews_calculations(), and suews_translate().
grasssurf
integer, parameter allocatearray::grasssurf = 5
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by checkinitial(), estm_module::estm_translate(), initializesurfacecharacteristics(), initialstate(), nextinitial(), suews_driver::suews_cal_main(), suews_driver::suews_cal_qn(), suews_driver::suews_cal_surf(), and suews_translate().
grididmatrix
integer, dimension(:), allocatable allocatearray::grididmatrix
Definition at line 112 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(:), ALLOCATABLE:: GridIDmatrix         !Array containing GridIDs in SiteSelect after sorting
Referenced by ctrl_output::filename_gen(), and suews_program().
grididmatrix0
integer, dimension(:), allocatable allocatearray::grididmatrix0
Definition at line 113 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(:), ALLOCATABLE:: GridIDmatrix0        !Array containing GridIDs in SiteSelect in the original order
Referenced by suews_program().
gridto
real(kind(1d0)), dimension(nconns) allocatearray::gridto
Definition at line 438 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nconns):: GridTo       !Grid that water moves to
gridtofrac
real(kind(1d0)), dimension(nconns) allocatearray::gridtofrac
Definition at line 437 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nconns):: GridToFrac   !Fraction of water moving to the grid specified in GridTo [-]
hdd_id
real(kind(1d0)), dimension(12) allocatearray::hdd_id
Definition at line 252 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(12)       :: HDD_id
Referenced by initialstate(), nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
hdd_id_grids
real(kind(1d0)), dimension(12, maxnumberofgrids) allocatearray::hdd_id_grids
Definition at line 282 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(12, MaxNumberOfGrids):: HDD_id_grids
Referenced by suews_translate(), and suews_translateback().
headeranthropogenic_file
character(len=20), dimension(ncolumnsanthropogenic) allocatearray::headeranthropogenic_file
Definition at line 75 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsAnthropogenic)::     HeaderAnthropogenic_File       !Header for QF
Referenced by inputheadercheck(), and overallruncontrol().
headeranthropogenic_reqd
character(len=20), dimension(ncolumnsanthropogenic) allocatearray::headeranthropogenic_reqd
Definition at line 76 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsAnthropogenic)::     HeaderAnthropogenic_Reqd       !Expected header for QF
Referenced by inputheadercheck().
headerbiogen_file
character(len=20), dimension(ncolumnsbiogen) allocatearray::headerbiogen_file
Definition at line 83 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsBiogen)::            HeaderBiogen_File              !Header for Biogen
Referenced by inputheadercheck(), and overallruncontrol().
headerbiogen_reqd
character(len=20), dimension(ncolumnsbiogen) allocatearray::headerbiogen_reqd
Definition at line 84 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsBiogen)::            HeaderBiogen_Reqd              !Expected header for Biogen
Referenced by inputheadercheck().
headercond_file
character(len=20), dimension(ncolumnsconductance) allocatearray::headercond_file
Definition at line 69 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsConductance)::       HeaderCond_File                !Header for conductances
Referenced by inputheadercheck(), and overallruncontrol().
headercond_reqd
character(len=20), dimension(ncolumnsconductance) allocatearray::headercond_reqd
Definition at line 70 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsConductance)::       HeaderCond_Reqd                !Expected header for conductances
Referenced by inputheadercheck().
headerestmcoefficients_file
character(len=20), dimension(ncolumnsestmcoefficients) allocatearray::headerestmcoefficients_file
Definition at line 73 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsESTMCoefficients)::  HeaderESTMCoefficients_File    !Header for soils            ! S.O. 04 Feb 2016
Referenced by inputheadercheck(), and overallruncontrol().
headerestmcoefficients_reqd
character(len=20), dimension(ncolumnsestmcoefficients) allocatearray::headerestmcoefficients_reqd
Definition at line 74 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsESTMCoefficients)::  HeaderESTMCoefficients_Reqd    !Expected header for soils   ! S.O. 04 Feb 2016
Referenced by inputheadercheck().
headerirrigation_file
character(len=20), dimension(ncolumnsirrigation) allocatearray::headerirrigation_file
Definition at line 77 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsIrrigation)::        HeaderIrrigation_File          !Header for Irrigation
Referenced by inputheadercheck(), and overallruncontrol().
headerirrigation_reqd
character(len=20), dimension(ncolumnsirrigation) allocatearray::headerirrigation_reqd
Definition at line 78 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsIrrigation)::        HeaderIrrigation_Reqd          !Expected header for Irrigation
Referenced by inputheadercheck().
headernonveg_file
character(len=20), dimension(ncolumnsnonveg) allocatearray::headernonveg_file
Definition at line 59 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsNonVeg)::            HeaderNonVeg_File              !Header for the nonveg surface
Referenced by inputheadercheck(), and overallruncontrol().
headernonveg_reqd
character(len=20), dimension(ncolumnsnonveg) allocatearray::headernonveg_reqd
Definition at line 60 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsNonVeg)::            HeaderNonVeg_Reqd              !Expected header for the nonveg surface
Referenced by inputheadercheck().
headerohmcoefficients_file
character(len=20), dimension(ncolumnsohmcoefficients) allocatearray::headerohmcoefficients_file
Definition at line 71 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsOHMCoefficients)::   HeaderOHMCoefficients_File     !Header for soils
Referenced by inputheadercheck(), and overallruncontrol().
headerohmcoefficients_reqd
character(len=20), dimension(ncolumnsohmcoefficients) allocatearray::headerohmcoefficients_reqd
Definition at line 72 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsOHMCoefficients)::   HeaderOHMCoefficients_Reqd     !Expected header for soils
Referenced by inputheadercheck().
headerprofiles_file
character(len=20), dimension(ncolumnsprofiles) allocatearray::headerprofiles_file
Definition at line 79 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsProfiles)::          HeaderProfiles_File            !Header for Profiles
Referenced by inputheadercheck(), and overallruncontrol().
headerprofiles_reqd
character(len=20), dimension(ncolumnsprofiles) allocatearray::headerprofiles_reqd
Definition at line 80 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsProfiles)::          HeaderProfiles_Reqd            !Expected header for Profiles
Referenced by inputheadercheck().
headersiteselect_file
character(len=20), dimension(ncolumnssiteselect) allocatearray::headersiteselect_file
Definition at line 58 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsSiteSelect)::        HeaderSiteSelect_File          !Header for SiteSelect.txt
Referenced by overallruncontrol().
headersnow_file
character(len=20), dimension(ncolumnssnow) allocatearray::headersnow_file
Definition at line 65 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsSnow)::              HeaderSnow_File                !Header for Snow surface
Referenced by inputheadercheck(), and overallruncontrol().
headersnow_reqd
character(len=20), dimension(ncolumnssnow) allocatearray::headersnow_reqd
Definition at line 66 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsSnow)::              HeaderSnow_Reqd                !Expected header for Snow surface
Referenced by inputheadercheck().
headersoil_file
character(len=20), dimension(ncolumnssoil) allocatearray::headersoil_file
Definition at line 67 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsSoil)::              HeaderSoil_File                !Header for soils
Referenced by inputheadercheck(), and overallruncontrol().
headersoil_reqd
character(len=20), dimension(ncolumnssoil) allocatearray::headersoil_reqd
Definition at line 68 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsSoil)::              HeaderSoil_Reqd                !Expected header for soils
Referenced by inputheadercheck().
headeruse
character(len=14*ncolumnsdataoutsuews) allocatearray::headeruse
Definition at line 89 of file suews_ctrl_const.f95.
    CHARACTER(len=14*ncolumnsDataOutSUEWS):: HeaderUse, FormatUse, HeaderUseNoSep, FormatUseNoSep    !Header and format in correct form
headerusenosep
character(len=14*ncolumnsdataoutsuews) allocatearray::headerusenosep
Definition at line 89 of file suews_ctrl_const.f95.
headerveg_file
character(len=20), dimension(ncolumnsveg) allocatearray::headerveg_file
Definition at line 61 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsVeg)::               HeaderVeg_File                 !Header for the veg surface
Referenced by inputheadercheck(), and overallruncontrol().
headerveg_reqd
character(len=20), dimension(ncolumnsveg) allocatearray::headerveg_reqd
Definition at line 62 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsVeg)::               HeaderVeg_Reqd                 !Expected header for the veg surface
Referenced by inputheadercheck().
headerwater_file
character(len=20), dimension(ncolumnswater) allocatearray::headerwater_file
Definition at line 63 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsWater)::             HeaderWater_File               !Header for water surface
Referenced by inputheadercheck(), and overallruncontrol().
headerwater_reqd
character(len=20), dimension(ncolumnswater) allocatearray::headerwater_reqd
Definition at line 64 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsWater)::             HeaderWater_Reqd               !Expected header for water surface
Referenced by inputheadercheck().
headerwgwaterdist_file
character(len=20), dimension(ncolumnswgwaterdist) allocatearray::headerwgwaterdist_file
Definition at line 81 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsWGWaterDist)::       HeaderWGWaterDist_File         !Header for Profiles
Referenced by inputheadercheck(), and overallruncontrol().
headerwgwaterdist_reqd
character(len=20), dimension(ncolumnswgwaterdist) allocatearray::headerwgwaterdist_reqd
Definition at line 82 of file suews_ctrl_const.f95.
    CHARACTER(len=20), DIMENSION(ncolumnsWGWaterDist)::       HeaderWGWaterDist_Reqd         !Expected header for Profiles
Referenced by inputheadercheck().
heig
integer, dimension(nsurf) allocatearray::heig
Definition at line 428 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nsurf):: heiG, &                    !snow layer height
                                snowCoverForms, &
                                snowCalcSwitch = 0          !Defines if snow related balance is made
humactivity_24hr
real(kind(1d0)), dimension(0:23, 2) allocatearray::humactivity_24hr
Definition at line 152 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: HumActivity_24hr   !Human actvity profiles for (1)weekdays / (2)weekends
Referenced by suews_calculations(), and suews_translate().
icefrac
real(kind(1d0)), dimension(nsurf) allocatearray::icefrac
Definition at line 401 of file suews_ctrl_const.f95.
Referenced by initialstate(), and suews_calculations().
irrigation_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::irrigation_coeff
Definition at line 106 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Irrigation_Coeff          !Coefficients for Irrigation
Referenced by codematchirrigation(), initializesurfacecharacteristics(), and overallruncontrol().
ivconif
integer, parameter allocatearray::ivconif = 1
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by initializesurfacecharacteristics(), initialstate(), nextinitial(), normalizevegchar(), suews_driver::suews_cal_main(), suews_translate(), and dailystate_module::update_veg_x().
ivdecid
integer, parameter allocatearray::ivdecid = 2
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by initializesurfacecharacteristics(), initialstate(), nextinitial(), normalizevegchar(), suews_driver::suews_cal_main(), suews_translate(), and dailystate_module::update_veg_x().
ivgrass
integer, parameter allocatearray::ivgrass = 3
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by initializesurfacecharacteristics(), initialstate(), nextinitial(), normalizevegchar(), suews_driver::suews_cal_main(), suews_translate(), and dailystate_module::update_veg_x().
kkanohm
real(kind(1d0)), dimension(nsurf) allocatearray::kkanohm
Definition at line 449 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: kkAnOHM ! thermal conductivity [W m-1 K-1]
Referenced by suews_calculations(), and suews_translate().
ksurf_suewssurfs
real(kind(1d0)), dimension(5, nsurfincsnow) allocatearray::ksurf_suewssurfs
Definition at line 454 of file suews_ctrl_const.f95.
Referenced by suews_translate().
kup_ind
real(kind(1d0)), dimension(nsurf) allocatearray::kup_ind
Definition at line 362 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: kup_ind, &          !Outgoing shortwave radiation for each surface [W m-2]
                                        kup_ind_snow, &     !Outgoing shortwave radiation for each snow surface [W m-2]
                                        kup_ind_nosnow
kup_ind_nosnow
real(kind(1d0)), dimension(nsurf) allocatearray::kup_ind_nosnow
Definition at line 362 of file suews_ctrl_const.f95.
kup_ind_snow
real(kind(1d0)), dimension(nsurf) allocatearray::kup_ind_snow
Definition at line 362 of file suews_ctrl_const.f95.
lai_id
real(kind(1d0)), dimension(nvegsurf) allocatearray::lai_id
Definition at line 254 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf) :: LAI_id, LAI_id_prev     !LAI for each veg surface [m2 m-2]
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
lai_id_grids
real(kind(1d0)), dimension(nvegsurf, maxnumberofgrids) allocatearray::lai_id_grids
Definition at line 284 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf, MaxNumberOfGrids):: LAI_id_grids
Referenced by suews_translate(), and suews_translateback().
lai_id_prev
real(kind(1d0)), dimension(nvegsurf) allocatearray::lai_id_prev
Definition at line 254 of file suews_ctrl_const.f95.
laimax
real(kind(1d0)), dimension(nvegsurf) allocatearray::laimax
Definition at line 329 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: LAIMax           !Max LAI  [m2 m-2]
Referenced by checkinitial(), suews_calculations(), and suews_translate().
laimin
real(kind(1d0)), dimension(nvegsurf) allocatearray::laimin
Definition at line 328 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: LAIMin           !Min LAI [m2 m-2]
Referenced by checkinitial(), suews_calculations(), and suews_translate().
laipower
real(kind(1d0)), dimension(4, nvegsurf) allocatearray::laipower
Definition at line 331 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(4, nvegsurf):: LAIPower       !Coeffs for LAI equation: 1,2 - leaf growth; 3,4 - leaf off
Referenced by suews_calculations(), and suews_translate().
laitype
integer, dimension(nvegsurf) allocatearray::laitype
Definition at line 333 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(nvegsurf):: LAIType                  !LAI equation to use: original (0) or new (1)
Referenced by suews_calculations(), and suews_translate().
longnmuse
character(len=52*ncolumnsdataoutsuews) allocatearray::longnmuse
Definition at line 90 of file suews_ctrl_const.f95.
    CHARACTER(len=52*ncolumnsDataOutSUEWS):: LongNmUse
lup_ind
real(kind(1d0)), dimension(nsurf) allocatearray::lup_ind
Definition at line 365 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: lup_ind, &          !Outgoing longwave radiation for each surface [W m-2]
                                        lup_ind_snow, &     !Outgoing longwave radiation for each snow surface [W m-2]
                                        lup_ind_nosnow
lup_ind_nosnow
real(kind(1d0)), dimension(nsurf) allocatearray::lup_ind_nosnow
Definition at line 365 of file suews_ctrl_const.f95.
lup_ind_snow
real(kind(1d0)), dimension(nsurf) allocatearray::lup_ind_snow
Definition at line 365 of file suews_ctrl_const.f95.
mahanohm
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::mahanohm
Definition at line 445 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids) :: mAHAnOHM                ! daily mean AH [W m-2]
maxconductance
real(kind(1d0)), dimension(nvegsurf) allocatearray::maxconductance
Definition at line 330 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: MaxConductance   !Max conductance [mm s-1]
Referenced by suews_calculations(), and suews_translate().
maxlinesmet
integer, parameter allocatearray::maxlinesmet = 8640
Definition at line 28 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: MaxLinesMet = 8640        !Max no. lines to read in one go (for all grids, ie MaxLinesMet/NumberOfGrids each)
Referenced by suews_program().
maxncols_c
integer, parameter allocatearray::maxncols_c = (ccEndESTMMP + 44*5 + 5 + 6)
Definition at line 843 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: MaxNCols_c = (ccendestmmp + 44*5 + 5 + 6)
Referenced by suews_program().
maxncols_cmds
integer, parameter allocatearray::maxncols_cmds = ccMDS + 0*nsurf + nsurf
Definition at line 866 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: MaxNCols_cMDS = ccmds + 0*nsurf + nsurf
Referenced by suews_program().
maxncols_cmod
integer, parameter allocatearray::maxncols_cmod = ccMOD + 5*nsurf + nsurf
Definition at line 857 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: MaxNCols_cMOD = ccmod + 5*nsurf + nsurf
Referenced by suews_program().
maxnumberofgrids
integer parameter allocatearray::maxnumberofgrids = 90000
Definition at line 24 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: MaxNumberOfGrids = 90000   !Max no. grids   !TS changed to 90000 for large-scale simulation based on netCDF IO
Referenced by suews_program().
maxsnowvol
real(kind(1d0)), dimension(nsurf) allocatearray::maxsnowvol
Definition at line 401 of file suews_ctrl_const.f95.
metforcingdata
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::metforcingdata
Definition at line 115 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: MetForcingData      !Array for meteorological forcing data
Referenced by metdisagg::disaggregatemet(), initialstate(), suews_initializemetdata(), suews_program(), and suews_translate().
metforcingdata_grid
real(kind(1d0)), dimension(:, :), allocatable allocatearray::metforcingdata_grid
Definition at line 116 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE  :: MetForcingData_grid !Array for meteorological forcing data of one grid used by AnOHM
Referenced by suews_calculations(), suews_program(), and suews_translate().
metfordisagg
real(kind(1d0)), dimension(:, :), allocatable allocatearray::metfordisagg
Definition at line 136 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE:: MetForDisagg           !Array for original met forcing data (for disaggregation)
Referenced by metdisagg::disaggregatemet().
metfordisaggnext
real(kind(1d0)), dimension(:), allocatable allocatearray::metfordisaggnext
Definition at line 137 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet().
metfordisaggprev
real(kind(1d0)), dimension(:), allocatable allocatearray::metfordisaggprev
Definition at line 137 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: MetForDisaggPrev, MetForDisaggNext !Stores last and next row of met data
Referenced by metdisagg::disaggregatemet().
min_res_bioco2
real(kind(1d0)), dimension(nvegsurf) allocatearray::min_res_bioco2
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
modeldailystate
real(kind(1d0)), dimension(:, :), allocatable allocatearray::modeldailystate
Definition at line 118 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE:: ModelDailyState      !DailyState array
Referenced by initialstate(), suews_program(), suews_translate(), and suews_translateback().
modeloutputdata
real(kind(1d0)), dimension(:, :, :), allocatable allocatearray::modeloutputdata
Definition at line 120 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :, :), ALLOCATABLE:: ModelOutputData      !Output data matrix
Referenced by initialstate(), suews_program(), suews_translate(), and suews_translateback().
mw_ind
real(kind(1d0)), dimension(nsurf) allocatearray::mw_ind
Definition at line 401 of file suews_ctrl_const.f95.
mw_indday
real(kind(1d0)), dimension(nsurf) allocatearray::mw_indday
Definition at line 401 of file suews_ctrl_const.f95.
narp_alb_snow
real(kind(1d0)) allocatearray::narp_alb_snow
Definition at line 373 of file suews_ctrl_const.f95.
narp_emis_snow
real(kind(1d0)) allocatearray::narp_emis_snow
Definition at line 373 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
narp_g
real(kind(1d0)), dimension(365) allocatearray::narp_g
Definition at line 375 of file suews_ctrl_const.f95.
    REAL(KIND(1D0))             :: NARP_G(365)   !!QUESTION: Should this be NDays? - HCW
narp_kdown_hr
real(kind(1d0)), dimension(:), allocatable allocatearray::narp_kdown_hr
Definition at line 377 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), ALLOCATABLE :: NARP_KDOWN_HR(:)
narp_lat
real(kind(1d0)) allocatearray::narp_lat
Definition at line 373 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))             :: NARP_LAT, NARP_LONG, NARP_YEAR, NARP_TZ, &
                                   NARP_ALB_SNOW, NARP_EMIS_SNOW, NARP_TRANS_SITE
Referenced by suews_translate().
narp_long
real(kind(1d0)) allocatearray::narp_long
Definition at line 373 of file suews_ctrl_const.f95.
Referenced by suews_translate().
narp_nperhour
integer allocatearray::narp_nperhour
Definition at line 376 of file suews_ctrl_const.f95.
    INTEGER                     :: NARP_NPERHOUR
narp_trans_site
real(kind(1d0)) allocatearray::narp_trans_site
Definition at line 373 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
narp_tz
real(kind(1d0)) allocatearray::narp_tz
Definition at line 373 of file suews_ctrl_const.f95.
Referenced by suews_translate().
narp_year
real(kind(1d0)) allocatearray::narp_year
Definition at line 373 of file suews_ctrl_const.f95.
Referenced by suews_translate().
ncolsestmdata
integer, parameter allocatearray::ncolsestmdata = 13
Definition at line 46 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolsESTMdata = 13             !ESTM input file (_ESTM_Ts_data.txt))
Referenced by metdisagg::disaggregateestm(), estm_module::estm_translate(), estm_module::suews_getestmdata(), suews_program(), and suews_translate().
ncolumnsanthropogenic
integer, parameter allocatearray::ncolumnsanthropogenic = 39
Definition at line 40 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsAnthropogenic = 39     !SUEWS_AnthropogenicEmission.txt
Referenced by overallruncontrol().
ncolumnsbiogen
integer, parameter allocatearray::ncolumnsbiogen = 9
Definition at line 44 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsBiogen = 9             !SUEWS_BiogenCO2.txt
Referenced by overallruncontrol().
ncolumnsconductance
integer, parameter allocatearray::ncolumnsconductance = 13
Definition at line 37 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsConductance = 13       !SUEWS_Conductance.txt
Referenced by overallruncontrol().
ncolumnsdataoutbl
integer, parameter allocatearray::ncolumnsdataoutbl = 22
Definition at line 49 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::nbl(), and suews_program().
ncolumnsdataoutdailystate
integer, parameter allocatearray::ncolumnsdataoutdailystate = 46
Definition at line 49 of file suews_ctrl_const.f95.
Referenced by suews_program(), and dailystate_module::suews_update_dailystate().
ncolumnsdataoutestm
integer, parameter allocatearray::ncolumnsdataoutestm = 32
Definition at line 49 of file suews_ctrl_const.f95.
ncolumnsdataoutrsl
integer, parameter allocatearray::ncolumnsdataoutrsl = 35
Definition at line 49 of file suews_ctrl_const.f95.
Referenced by suews_program().
ncolumnsdataoutsnow
integer, parameter allocatearray::ncolumnsdataoutsnow = 102
Definition at line 49 of file suews_ctrl_const.f95.
Referenced by suews_program().
ncolumnsdataoutsol
integer, parameter allocatearray::ncolumnsdataoutsol = 31
Definition at line 49 of file suews_ctrl_const.f95.
Referenced by suews_program().
ncolumnsdataoutsuews
integer, parameter allocatearray::ncolumnsdataoutsuews = 87
Definition at line 49 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsDataOutSUEWS = 87, &    !Main output file (_5.txt). dataOutSUEWS created in SUEWS_Calculations.f95
                         ncolumnsdataoutsnow = 102, &
                         ncolumnsdataoutsol = 31, &
                         ncolumnsdataoutbl = 22, &
                         ncolumnsdataoutestm = 32, &
                         ncolumnsdataoutdailystate = 46, &
                         ncolumnsdataoutrsl = 35
Referenced by suews_program().
ncolumnsestmcoefficients
integer, parameter allocatearray::ncolumnsestmcoefficients = 52
Definition at line 39 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsESTMCoefficients = 52  !SUEWS_ESTMCoefficients.txt ! S.O. 04 Feb 2016
Referenced by overallruncontrol().
ncolumnsirrigation
integer, parameter allocatearray::ncolumnsirrigation = 25
Definition at line 41 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsIrrigation = 25        !SUEWS_Irrigation.txt
Referenced by overallruncontrol().
ncolumnsmetforcingdata
integer, parameter allocatearray::ncolumnsmetforcingdata = 24
Definition at line 45 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsMetForcingData = 24    !Meteorological forcing file (_data.txt)
Referenced by metdisagg::disaggregatemet(), and suews_program().
ncolumnsnonveg
integer, parameter allocatearray::ncolumnsnonveg = 24
Definition at line 32 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsNonVeg = 24            !SUEWS_NonVeg.txt
Referenced by overallruncontrol().
ncolumnsohmcoefficients
integer, parameter allocatearray::ncolumnsohmcoefficients = 4
Definition at line 38 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsOHMCoefficients = 4    !SUEWS_OHMCoefficients.txt
Referenced by overallruncontrol().
ncolumnsprofiles
integer, parameter allocatearray::ncolumnsprofiles = 25
Definition at line 42 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsProfiles = 25          !SUEWS_Profiles.txt
Referenced by overallruncontrol().
ncolumnssiteselect
integer, parameter allocatearray::ncolumnssiteselect = 101
Definition at line 31 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsSiteSelect = 101       !SUEWS_SiteSelect.txt
Referenced by initializesurfacecharacteristics(), and overallruncontrol().
ncolumnssnow
integer, parameter allocatearray::ncolumnssnow = 25
Definition at line 35 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsSnow = 25              !SUEWS_Snow.txt
Referenced by overallruncontrol().
ncolumnssoil
integer, parameter allocatearray::ncolumnssoil = 9
Definition at line 36 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsSoil = 9               !SUEWS_Soil.txt
Referenced by overallruncontrol().
ncolumnsveg
integer, parameter allocatearray::ncolumnsveg = 38
Definition at line 33 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsVeg = 38               !SUEWS_Veg.txt
Referenced by overallruncontrol().
ncolumnswater
integer, parameter allocatearray::ncolumnswater = 22
Definition at line 34 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsWater = 22             !SUEWS_Water.txt
Referenced by overallruncontrol().
ncolumnswgwaterdist
integer, parameter allocatearray::ncolumnswgwaterdist = 10
Definition at line 43 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ncolumnsWGWaterDist = 10       !SUEWS_WithinGridWaterDist.txt
Referenced by overallruncontrol().
nconns
integer, parameter allocatearray::nconns = 8
Definition at line 436 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: nconns = 8   !Number of grids for between-grid connections
ndays
integer, parameter allocatearray::ndays = 366
Definition at line 244 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: ndays = 366   !Max no. days in a year used to specify size of daily arrays
Referenced by suews_program().
nonveg_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::nonveg_coeff
Definition at line 97 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::NonVeg_Coeff              !Coefficients for the nonveg surfaces
Referenced by codematchnonveg(), initializesurfacecharacteristics(), and overallruncontrol().
nsurf
integer, parameter allocatearray::nsurf = 7
Definition at line 182 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: nsurf = 7                !Total number of surfaces
Referenced by initializesurfacecharacteristics(), dailystate_module::suews_cal_dailystate(), suews_driver::suews_cal_main(), suews_driver::suews_cal_qe(), suews_driver::suews_cal_qn(), suews_driver::suews_cal_water(), suews_translate(), and suews_translateback().
nsurfdonotreceivedrainage
integer, parameter allocatearray::nsurfdonotreceivedrainage = 0
Definition at line 186 of file suews_ctrl_const.f95.
nsurfincsnow
integer, parameter allocatearray::nsurfincsnow = nsurf + 1
Definition at line 184 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: nsurfIncSnow = nsurf + 1   !Number of surfaces + snow
Referenced by suews_translate().
nvegsurf
integer, parameter allocatearray::nvegsurf = 3
Definition at line 183 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: NVegSurf = 3             !Number of surfaces that are vegetated
Referenced by suews_driver::suews_cal_main(), suews_translate(), and dailystate_module::update_gddlai_x().
ohm_coef
real(kind(1d0)), dimension(nsurf + 1, 4, 3) allocatearray::ohm_coef
Definition at line 385 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf + 1, 4, 3):: OHM_coef   !Array for OHM coefficients
Referenced by suews_calculations(), and suews_translate().
ohm_threshsw
real(kind(1d0)), dimension(nsurf + 1) allocatearray::ohm_threshsw
Definition at line 386 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf + 1)::     OHM_threshSW, OHM_threshWD   !Arrays for OHM thresholds
Referenced by suews_calculations(), and suews_translate().
ohm_threshwd
real(kind(1d0)), dimension(nsurf + 1) allocatearray::ohm_threshwd
Definition at line 386 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
ohmcoefficients_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::ohmcoefficients_coeff
Definition at line 103 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::OHMCoefficients_Coeff     !Coefficients for OHMCoefficients
Referenced by codematchohm(), initializesurfacecharacteristics(), and overallruncontrol().
pavsurf
integer, parameter allocatearray::pavsurf = 1
Definition at line 186 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER:: PavSurf = 1, &   !When all surfaces considered together (1-7)
                         bldgsurf = 2, &
                         conifsurf = 3, &
                         decidsurf = 4, &
                         grasssurf = 5, &   !New surface classes: Grass = 5th/7 surfaces
                         bsoilsurf = 6, &   !New surface classes: Bare soil = 6th/7 surfaces
                         watersurf = 7, &
                         excesssurf = 8, &   !Runoff or subsurface soil in WGWaterDist
                         nsurfdonotreceivedrainage = 0, &   !Number of surfaces that do not receive drainage water (green roof)
                         ivconif = 1, &     !When only vegetated surfaces considered (1-3)
                         ivdecid = 2, &
                         ivgrass = 3
Referenced by checkinitial(), codematchestm_class(), estm_module::estm_translate(), initializesurfacecharacteristics(), initialstate(), nextinitial(), snow_module::snowdepletioncurve(), suews_driver::suews_cal_surf(), and suews_translate().
popprof_24hr
real(kind(1d0)), dimension(0:23, 2) allocatearray::popprof_24hr
Definition at line 154 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: PopProf_24hr   !Population profiles for (1)weekdays / (2)weekends
Referenced by suews_calculations(), and suews_translate().
pormax_dec
real(kind(1d0)) allocatearray::pormax_dec
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
pormin_dec
real(kind(1d0)) allocatearray::pormin_dec
Definition at line 263 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
porosity_id
real(kind(1d0)) allocatearray::porosity_id
Definition at line 303 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)) :: porosity_id
Referenced by initialstate(), nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
porosity_id_grids
real(kind(1d0)), dimension(maxnumberofgrids) allocatearray::porosity_id_grids
Definition at line 297 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(MaxNumberOfGrids):: porosity_id_grids
Referenced by suews_translate(), and suews_translateback().
profiles_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::profiles_coeff
Definition at line 107 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Profiles_Coeff            !Coefficients for Profiles
Referenced by codematchprof(), initializesurfacecharacteristics(), and overallruncontrol().
qm_freezstate
real(kind(1d0)), dimension(nsurf) allocatearray::qm_freezstate
Definition at line 401 of file suews_ctrl_const.f95.
qm_melt
real(kind(1d0)), dimension(nsurf) allocatearray::qm_melt
Definition at line 401 of file suews_ctrl_const.f95.
qm_rain
real(kind(1d0)), dimension(nsurf) allocatearray::qm_rain
Definition at line 401 of file suews_ctrl_const.f95.
qn1_av
real(kind(1d0)) allocatearray::qn1_av
Definition at line 395 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::qn1_av, dqndt
Referenced by suews_calculations(), suews_translate(), and suews_translateback().
qn1_av_grids
real(kind(1d0)), dimension(:), allocatable allocatearray::qn1_av_grids
Definition at line 393 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE::qn1_av_grids, qn1_s_av_grids
Referenced by suews_program(), suews_translate(), and suews_translateback().
qn1_ind
real(kind(1d0)), dimension(nsurf) allocatearray::qn1_ind
Definition at line 368 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: qn1_ind, &          !Net all-wave radiation for each surface [W m-2]
                                        qn1_ind_snow, &     !Net all-wave radiation for each snow surface [W m-2]
                                        qn1_ind_nosnow
qn1_ind_nosnow
real(kind(1d0)), dimension(nsurf) allocatearray::qn1_ind_nosnow
Definition at line 368 of file suews_ctrl_const.f95.
qn1_ind_snow
real(kind(1d0)), dimension(nsurf) allocatearray::qn1_ind_snow
Definition at line 368 of file suews_ctrl_const.f95.
qn1_s_av
real(kind(1d0)) allocatearray::qn1_s_av
Definition at line 396 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::qn1_s_av, dqnsdt
Referenced by suews_calculations(), suews_translate(), and suews_translateback().
qn1_s_av_grids
real(kind(1d0)), dimension(:), allocatable allocatearray::qn1_s_av_grids
Definition at line 393 of file suews_ctrl_const.f95.
Referenced by suews_program(), suews_translate(), and suews_translateback().
rad2deg
real(kind(1d0)), parameter allocatearray::rad2deg = 57.29577951
Definition at line 379 of file suews_ctrl_const.f95.
rainonsnow
real(kind(1d0)), dimension(nsurf) allocatearray::rainonsnow
Definition at line 401 of file suews_ctrl_const.f95.
resp_a
real(kind(1d0)), dimension(nvegsurf) allocatearray::resp_a
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
resp_b
real(kind(1d0)), dimension(nvegsurf) allocatearray::resp_b
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
rss_nsurf
real(kind(1d0)), dimension(nsurf) allocatearray::rss_nsurf
Definition at line 218 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(nsurf):: rss_nsurf      !Surface resistance after wet/partially wet adjustment for each surface
rsurf_suewssurfs
real(kind(1d0)), dimension(5, nsurfincsnow) allocatearray::rsurf_suewssurfs
Definition at line 454 of file suews_ctrl_const.f95.
Referenced by suews_translate().
runoff
real(kind(1d0)), dimension(nsurf) allocatearray::runoff
Definition at line 209 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: runoff         !Runoff from each surface type [mm]
runoffsnow
real(kind(1d0)), dimension(nsurf) allocatearray::runoffsnow
Definition at line 401 of file suews_ctrl_const.f95.
runoffsoil
real(kind(1d0)), dimension(nsurf) allocatearray::runoffsoil
Definition at line 210 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: runoffSoil     !Soil runoff from each soil sub-surface [mm]
sathydraulicconduct
real(kind(1d0)), dimension(nsurf) allocatearray::sathydraulicconduct
Definition at line 226 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: SatHydraulicConduct !Saturated hydraulic conductivity for each soil subsurface [mm s-1]
Referenced by suews_calculations(), and suews_translate().
sddfull
real(kind(1d0)), dimension(nvegsurf) allocatearray::sddfull
Definition at line 327 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nvegsurf):: SDDFull          !Senescence degree days needed to initiate leaf off [degC]
Referenced by suews_calculations(), and suews_translate().
sfr
real(kind(1d0)), dimension(nsurf) allocatearray::sfr
Definition at line 199 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: sfr   !Surface fractions [-]
Referenced by estm_module::estm_translate(), initialstate(), suews_calculations(), and suews_translate().
sigma_sb
real(kind(1d0)), parameter allocatearray::sigma_sb = 5.67E-8
Definition at line 379 of file suews_ctrl_const.f95.
siteselect
real(kind(1d0)), dimension(:, :), allocatable allocatearray::siteselect
Definition at line 96 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::SiteSelect                !Stores info from SiteSelect.txt
Referenced by codematchanthropogenic(), codematchconductance(), codematchdist(), codematchirrigation(), codematchnonveg(), codematchsnow(), codematchveg(), codematchwater(), initializesurfacecharacteristics(), overallruncontrol(), and suews_program().
smd_nsurf
real(kind(1d0)), dimension(nsurf) allocatearray::smd_nsurf
Definition at line 211 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: smd_nsurf      !Soil moisture deficit of each sub-surface [mm]
smd_nsurfout
real(kind(1d0)), dimension(nsurf) allocatearray::smd_nsurfout
Definition at line 212 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: smd_nsurfOut   !Soil moisture deficit of each sub-surface (written out) [mm]
snow_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::snow_coeff
Definition at line 100 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Snow_Coeff                !Coefficients for snow
Referenced by codematchsnow(), initializesurfacecharacteristics(), and overallruncontrol().
snowcalcswitch
integer, dimension(nsurf) allocatearray::snowcalcswitch = 0
Definition at line 428 of file suews_ctrl_const.f95.
snowcoverforms
integer, dimension(nsurf) allocatearray::snowcoverforms
Definition at line 428 of file suews_ctrl_const.f95.
snowdens
real(kind(1d0)), dimension(nsurf) allocatearray::snowdens
Definition at line 401 of file suews_ctrl_const.f95.
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
snowdepth
real(kind(1d0)), dimension(nsurf) allocatearray::snowdepth
Definition at line 401 of file suews_ctrl_const.f95.
snowfrac
real(kind(1d0)), dimension(nsurf) allocatearray::snowfrac
Definition at line 401 of file suews_ctrl_const.f95.
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
snowinit
real(kind(1d0)), dimension(nsurf) allocatearray::snowinit
Definition at line 401 of file suews_ctrl_const.f95.
snowpack
real(kind(1d0)), dimension(nsurf) allocatearray::snowpack
Definition at line 426 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: snowPack, &        !Amount of snow on each surface in mm
                                        snowPackOld
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
snowpacklimit
real(kind(1d0)), dimension(nsurf) allocatearray::snowpacklimit
Definition at line 401 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowpackold
real(kind(1d0)), dimension(nsurf) allocatearray::snowpackold
Definition at line 426 of file suews_ctrl_const.f95.
snowtosurf
real(kind(1d0)), dimension(nsurf) allocatearray::snowtosurf
Definition at line 401 of file suews_ctrl_const.f95.
snowwater
real(kind(1d0)), dimension(nsurf) allocatearray::snowwater
Definition at line 401 of file suews_ctrl_const.f95.
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
soil_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::soil_coeff
Definition at line 101 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Soil_Coeff                !Coefficients for soil
Referenced by codematchsoil(), initializesurfacecharacteristics(), and overallruncontrol().
soildepth
real(kind(1d0)), dimension(nsurf) allocatearray::soildepth
Definition at line 227 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: SoilDepth           !Depth of sub-surface soil store for each surface [mm]
Referenced by suews_calculations(), and suews_translate().
soilstore_id
real(kind(1d0)), dimension(nsurf) allocatearray::soilstore_id
Definition at line 213 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: soilstore_id      !Soil moisture of each surface type [mm]
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
soilstorecap
real(kind(1d0)), dimension(nsurf) allocatearray::soilstorecap
Definition at line 228 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: SoilStoreCap        !Capacity of soil store for each surface [mm]
Referenced by checkinitial(), suews_calculations(), and suews_translate().
soilstoreold
real(kind(1d0)), dimension(nsurf) allocatearray::soilstoreold
Definition at line 214 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: soilstoreOld   !Soil moisture of each surface type from previous timestep [mm]
state_id
real(kind(1d0)), dimension(nsurf) allocatearray::state_id
Definition at line 215 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: state_id          !Wetness status of each surface type [mm]
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
statefraction
real(kind(1d0)), dimension(nsurf) allocatearray::statefraction
Definition at line 401 of file suews_ctrl_const.f95.
statelimit
real(kind(1d0)), dimension(nsurf) allocatearray::statelimit
Definition at line 221 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: StateLimit     !Limit for state_id of each surface type [mm] (specified in input files)
Referenced by suews_calculations(), and suews_translate().
stateold
real(kind(1d0)), dimension(nsurf) allocatearray::stateold
Definition at line 217 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: stateOld       !Wetness status of each surface type from previous timestep [mm]
stateout
real(kind(1d0)), dimension(nsurf) allocatearray::stateout
Definition at line 216 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: stateOut       !Wetness status of each surface type (written out) [mm]
storedrainprm
real(kind(1d0)), dimension(6, nsurf) allocatearray::storedrainprm
Definition at line 234 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(6, nsurf):: StoreDrainPrm   !Storage capacities and drainage equation info for each surface
Referenced by suews_calculations(), and suews_translate().
surfacechar
real(kind(1d0)), dimension(:, :), allocatable allocatearray::surfacechar
Definition at line 114 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE:: SurfaceChar          !Array for surface characteristics
Referenced by codematchbiogen(), codematchestm(), codematchestm_class(), codematchohm(), codematchprof(), codematchsoil(), metdisagg::disaggregatemet(), initializesurfacecharacteristics(), initialstate(), normalizevegchar(), suews_program(), and suews_translate().
tair24hr
real(kind(1d0)), dimension(:), allocatable allocatearray::tair24hr
Definition at line 161 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), ALLOCATABLE, DIMENSION(:)  :: Tair24HR
Referenced by estm_module::estm_translate(), suews_calculations(), and suews_program().
theta_bioco2
real(kind(1d0)), dimension(nvegsurf) allocatearray::theta_bioco2
Definition at line 336 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
traffprof_24hr
real(kind(1d0)), dimension(0:23, 2) allocatearray::traffprof_24hr
Definition at line 153 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: TraffProf_24hr   !Traffic profiles for (1)weekdays / (2)weekends
Referenced by suews_calculations(), and suews_translate().
ts5mindata
real(kind(1d0)), dimension(:, :), allocatable allocatearray::ts5mindata
Definition at line 159 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), ALLOCATABLE, DIMENSION(:, :):: Ts5mindata   !surface temperature input data
Referenced by estm_module::estm_translate(), suews_program(), and suews_translate().
ts5mindata_ir
real(kind(1d0)), dimension(:), allocatable allocatearray::ts5mindata_ir
Definition at line 160 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), ALLOCATABLE, DIMENSION(:)  :: ts5mindata_ir !=ts5mindata(ir,:), ts input for the current timestep
Referenced by suews_calculations(), suews_program(), and suews_translate().
tsurf_ind
real(kind(1d0)), dimension(nsurf) allocatearray::tsurf_ind
Definition at line 359 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: Tsurf_ind, &        !Surface temperature for each surface [degC]
                                        Tsurf_ind_snow, &   !Snow surface temperature for each surface [degC]
                                        Tsurf_ind_nosnow
tsurf_ind_nosnow
real(kind(1d0)), dimension(nsurf) allocatearray::tsurf_ind_nosnow
Definition at line 359 of file suews_ctrl_const.f95.
tsurf_ind_snow
real(kind(1d0)), dimension(nsurf) allocatearray::tsurf_ind_snow
Definition at line 359 of file suews_ctrl_const.f95.
unitsuse
character(len=14*ncolumnsdataoutsuews) allocatearray::unitsuse
Definition at line 91 of file suews_ctrl_const.f95.
    CHARACTER(len=14*ncolumnsDataOutSUEWS):: UnitsUse
usecolumnsdataout
integer, dimension(:), allocatable allocatearray::usecolumnsdataout
Definition at line 87 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(:), ALLOCATABLE:: UseColumnsDataOut       !Column numbers used to select output variables
Referenced by suews_program().
veg_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::veg_coeff
Definition at line 98 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Veg_Coeff                 !Coefficients for the veg surfaces
Referenced by codematchveg(), initializesurfacecharacteristics(), and overallruncontrol().
volswe
real(kind(1d0)), dimension(nsurf) allocatearray::volswe
Definition at line 401 of file suews_ctrl_const.f95.
water_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::water_coeff
Definition at line 99 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::Water_Coeff               !Coefficients for the water surface
Referenced by codematchwater(), initializesurfacecharacteristics(), and overallruncontrol().
waterdepth
real(kind(1d0)), dimension(1) allocatearray::waterdepth
Definition at line 223 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(1)::     WaterDepth     !Depth of open water
Referenced by suews_translate().
waterdist
real(kind(1d0)), dimension(nsurf + 1, nsurf - 1) allocatearray::waterdist
Definition at line 231 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf + 1, nsurf - 1)::WaterDist !Within-grid water distribution to other surfaces and runoff/soil store [-]
Referenced by suews_calculations(), and suews_translate().
watersurf
integer, parameter allocatearray::watersurf = 7
Definition at line 186 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate(), initializesurfacecharacteristics(), initialstate(), nextinitial(), snow_module::snowdepletioncurve(), suews_driver::suews_cal_qe(), suews_driver::suews_cal_qs(), suews_driver::suews_cal_surf(), suews_driver::suews_cal_water(), and suews_translate().
wetthresh
real(kind(1d0)), dimension(nsurf) allocatearray::wetthresh
Definition at line 220 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(nsurf):: WetThresh      !When state_id > WetThresh, RS=0 limit in SUEWS_evap [mm] (specified in input files)
Referenced by suews_calculations(), and suews_translate().
wgwaterdist_coeff
real(kind(1d0)), dimension(:, :), allocatable allocatearray::wgwaterdist_coeff
Definition at line 108 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:, :), ALLOCATABLE::WGWaterDist_Coeff         !Coefficients for WithinGridWaterDist
Referenced by codematchdist(), initializesurfacecharacteristics(), and overallruncontrol().
wuday_id
real(kind(1d0)), dimension(9) allocatearray::wuday_id
Definition at line 253 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(9)        :: WUDay_id, WUDay_id_prev !Daily water use for EveTr, DecTr, Grass [mm] (see SUEWS_DailyState.f95)
Referenced by initialstate(), suews_calculations(), suews_translate(), and suews_translateback().
wuday_id_grids
real(kind(1d0)), dimension(9, maxnumberofgrids) allocatearray::wuday_id_grids
Definition at line 283 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(9, MaxNumberOfGrids):: WUDay_id_grids
Referenced by suews_translate(), and suews_translateback().
wuday_id_prev
real(kind(1d0)), dimension(9) allocatearray::wuday_id_prev
Definition at line 253 of file suews_ctrl_const.f95.
wuprofa_24hr
real(kind(1d0)), dimension(0:23, 2) allocatearray::wuprofa_24hr
Definition at line 156 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: WUProfA_24Hr
Referenced by suews_calculations(), and suews_translate().
wuprofm_24hr
real(kind(1d0)), dimension(0:23, 2) allocatearray::wuprofm_24hr
Definition at line 155 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: WUProfM_24Hr
Referenced by suews_calculations(), and suews_translate().
xbo
real(kind(1d0)) allocatearray::xbo
Definition at line 313 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: xBo ! daily Bowen ratio
zsurf_suewssurfs
real(kind(1d0)), dimension(5, nsurfincsnow) allocatearray::zsurf_suewssurfs
Definition at line 454 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, nsurfIncSnow):: zSurf_SUEWSsurfs, &
                                                  kSurf_SUEWSsurfs, &
                                                  rSurf_SUEWSsurfs
Referenced by suews_translate().