SUEWS: suews_driver Module Reference
suews_driver Module Reference
Functions/Subroutines
subroutine suews_cal_main (AerodynamicResistanceMethod, AH_MIN, AHProf_24hr, AH_SLOPE_Cooling, AH_SLOPE_Heating, alb, AlbMax_DecTr, AlbMax_EveTr, AlbMax_Grass, AlbMin_DecTr, AlbMin_EveTr, AlbMin_Grass, alpha_bioCO2, alpha_enh_bioCO2, alt, avkdn, avRh, avU1, BaseT, BaseTe, BaseTHDD, beta_bioCO2, beta_enh_bioCO2, bldgH, CapMax_dec, CapMin_dec, chAnOHM, CO2PointSource, cpAnOHM, CRWmax, CRWmin, DayWat, DayWatPer, DecTreeH, Diagnose, DiagQN, DiagQS, DRAINRT, dt_since_start, dqndt, qn1_av, dqnsdt, qn1_s_av, EF_umolCO2perJ, emis, EmissionsMethod, EnEF_v_Jkm, endDLS, EveTreeH, FAIBldg, FAIDecTree, FAIEveTree, Faut, FcEF_v_kgkm, fcld_obs, FlowChange, FrFossilFuel_Heat, FrFossilFuel_NonHeat, G1, G2, G3, G4, G5, G6, GDD_id, GDDFull, Gridiv, gsModel, HDD_id, HumActivity_24hr, IceFrac, id, Ie_a, Ie_end, Ie_m, Ie_start, imin, InternalWaterUse_h, IrrFracConif, IrrFracDecid, IrrFracGrass, isec, it, EvapMethod, iy, kkAnOHM, Kmax, LAI_id, LAICalcYes, LAIMax, LAIMin, LAI_obs, LAIPower, LAIType, lat, ldown_obs, lng, MaxConductance, MaxFCMetab, MaxQFMetab, SnowWater, MetForcingData_grid, MinFCMetab, MinQFMetab, min_res_bioCO2, NARP_EMIS_SNOW, NARP_TRANS_SITE, NetRadiationMethod, NumCapita, OHM_coef, OHMIncQF, OHM_threshSW, OHM_threshWD, PipeCapacity, PopDensDaytime, PopDensNighttime, PopProf_24hr, PorMax_dec, PorMin_dec, Precip, PrecipLimit, PrecipLimitAlb, Press_hPa, QF0_BEU, Qf_A, Qf_B, Qf_C, qn1_obs, qh_obs, qs_obs, qf_obs, RadMeltFact, RAINCOVER, RainMaxRes, resp_a, resp_b, RoughLenHeatMethod, RoughLenMomMethod, RunoffToWater, S1, S2, SatHydraulicConduct, SDDFull, sfr, SMDMethod, SnowAlb, SnowAlbMax, SnowAlbMin, SnowPackLimit, SnowDens, SnowDensMax, SnowDensMin, SnowfallCum, snowFrac, SnowLimBldg, SnowLimPaved, snowFrac_obs, SnowPack, SnowProf_24hr, snowUse, SoilDepth, soilstore_id, SoilStoreCap, StabilityMethod, startDLS, state_id, StateLimit, StorageHeatMethod, StoreDrainPrm, SurfaceArea, Tair24HR, tau_a, tau_f, tau_r, T_CRITIC_Cooling, T_CRITIC_Heating, Temp_C, TempMeltFact, TH, theta_bioCO2, timezone, TL, TrafficRate, TrafficUnits, TraffProf_24hr, Ts5mindata_ir, tstep, tstep_prev, veg_type, WaterDist, WaterUseMethod, WetThresh, wu_m3, WUDay_id, DecidCap_id, albDecTr_id, albEveTr_id, albGrass_id, porosity_id, WUProfA_24hr, WUProfM_24hr, xsmd, Z, z0m_in, zdm_in, datetimeLine, dataOutLineSUEWS, dataOutLineSnow, dataOutLineESTM, dataoutLineRSL, DailyStateLine)
subroutine suews_cal_anthropogenicemission (AH_MIN, AHProf_24hr, AH_SLOPE_Cooling, AH_SLOPE_Heating, CO2PointSource, dayofWeek_id, Diagnose, DLS, EF_umolCO2perJ, EmissionsMethod, EnEF_v_Jkm, FcEF_v_kgkm, FrFossilFuel_Heat, FrFossilFuel_NonHeat, HDD_id, HumActivity_24hr, id, imin, it, MaxFCMetab, MaxQFMetab, MinFCMetab, MinQFMetab, nsh, NumCapita, PopDensDaytime, PopDensNighttime, PopProf_24hr, QF, QF0_BEU, Qf_A, Qf_B, Qf_C, QF_obs, QF_SAHP, sfr, snowFrac, SurfaceArea, T_CRITIC_Cooling, T_CRITIC_Heating, Temp_C, TrafficRate, TrafficUnits, TraffProf_24hr, Fc_anthro, Fc_build, Fc_metab, Fc_point, Fc_traff)
subroutine suews_cal_biogenco2 (alpha_bioCO2, alpha_enh_bioCO2, avkdn, avRh, beta_bioCO2, beta_enh_bioCO2, BSoilSurf, ConifSurf, DecidSurf, dectime, Diagnose, EmissionsMethod, Fc_anthro, G1, G2, G3, G4, G5, G6, gfunc, GrassSurf, gsmodel, id, it, ivConif, ivDecid, ivGrass, Kmax, LAI_id, LAIMin, LAIMax, MaxConductance, min_res_bioCO2, nsurf, NVegSurf, Press_hPa, resp_a, resp_b, S1, S2, sfr, SMDMethod, snowFrac, t2_C, Temp_C, theta_bioCO2, TH, TL, vsmd, xsmd, Fc, Fc_biogen, Fc_photo, Fc_respi)
subroutine suews_cal_qn (NetRadiationMethod, snowUse, Diagnose, snowFrac_obs, ldown_obs, fcld_obs, dectime, ZENITH_deg, avKdn, Temp_C, avRH, ea_hPa, qn1_obs, SnowAlb, DiagQN, NARP_TRANS_SITE, NARP_EMIS_SNOW, IceFrac, sfr, emis, alb, albDecTr_id, DecidCap_id, albEveTr_id, albGrass_id, StoreDrainPrm, snowFrac, ldown, fcld, qn1, qn1_snowfree, qn1_S, kclear, kup, lup, tsurf, qn1_ind_snow, kup_ind_snow, Tsurf_ind_snow, Tsurf_ind)
subroutine suews_cal_qs (StorageHeatMethod, qs_obs, OHMIncQF, Gridiv, id, tstep, dt_since_start, Diagnose, sfr, OHM_coef, OHM_threshSW, OHM_threshWD, soilstore_id, SoilStoreCap, state_id, nsh, SnowUse, DiagQS, HDD_id, MetForcingData_grid, Ts5mindata_ir, qf, qn1, avkdn, avu1, temp_c, zenith_deg, avrh, press_hpa, ldown, bldgh, alb, emis, cpAnOHM, kkAnOHM, chAnOHM, EmissionsMethod, Tair24HR, qn1_av, dqndt, qn1_s_av, dqnsdt, StoreDrainPrm, qn1_S, snowFrac, dataOutLineESTM, qs, deltaQi, a1, a2, a3)
subroutine suews_cal_water (Diagnose, snowUse, NonWaterFraction, addPipes, addImpervious, addVeg, addWaterBody, state_id, soilstore_id, sfr, StoreDrainPrm, WaterDist, nsh_real, drain_per_tstep, drain, AddWaterRunoff, AdditionalWater, runoffPipes, runoff_per_interval, AddWater, stateOld, soilstoreOld)
subroutine suews_init_qh (qh_obs, avdens, avcp, h_mod, qn1, dectime, H_init)
subroutine suews_cal_qe (Diagnose, tstep, imin, it, EvapMethod, snowCalcSwitch, dayofWeek_id, CRWmin, CRWmax, dectime, lvS_J_kg, lv_j_kg, avdens, avRh, Press_hPa, Temp_C, RAsnow, psyc_hPa, avcp, sIce_hPa, PervFraction, vegfraction, addimpervious, qn1_snowfree, qf, qs, vpd_hPa, s_hPa, ResistSurf, RA, rb, snowdensmin, precip, PipeCapacity, RunoffToWater, NonWaterFraction, wu_EveTr, wu_DecTr, wu_Grass, addVeg, addWaterBody, SnowLimPaved, SnowLimBldg, SurfaceArea, FlowChange, drain, WetThresh, stateOld, mw_ind, SoilStoreCap, rainonsnow, freezmelt, freezstate, freezstatevol, Qm_Melt, Qm_rain, Tsurf_ind, sfr, StateLimit, AddWater, addwaterrunoff, StoreDrainPrm, SnowPackLimit, SnowProf_24hr, runoff_per_interval, state_id, soilstore_id, SnowPack, snowFrac, SnowWater, iceFrac, SnowDens, runoffSnow, runoff, runoffSoil, chang, changSnow, snowDepth, SnowToSurf, ev_snow, SnowRemoval, evap, rss_nsurf, p_mm, qe, state_per_tstep, NWstate_per_tstep, qeOut, swe, ev, chSnow_per_interval, ev_per_tstep, qe_per_tstep, runoff_per_tstep, surf_chang_per_tstep, runoffPipes, mwstore, runoffwaterbody, runoffAGveg, runoffAGimpervious, runoffWaterBody_m3, runoffPipes_m3)
subroutine suews_cal_qh (QHMethod, qn1, qf, QmRain, qeOut, qs, QmFreez, qm, avdens, avcp, tsurf, Temp_C, RA, qh, qh_residual, qh_resist)
subroutine suews_cal_resistance (StabilityMethod, Diagnose, AerodynamicResistanceMethod, RoughLenHeatMethod, snowUse, id, it, gsModel, SMDMethod, qh_obs, avdens, avcp, h_mod, qn1, dectime, zzd, z0m, zdm, avU1, Temp_C, VegFraction, avkdn, Kmax, G1, G2, G3, G4, G5, G6, S1, S2, TH, TL, dq, xsmd, vsmd, MaxConductance, LAIMax, LAI_id, snowFrac, sfr, UStar, TStar, L_mod, zL, gsc, ResistSurf, RA, RAsnow, rb)
subroutine suews_update_outputline (AdditionalWater, alb, avkdn, avU10_ms, azimuth, chSnow_per_interval, dectime, drain_per_tstep, E_mod, ev_per_tstep, ext_wu, Fc, Fc_build, fcld, Fc_metab, Fc_photo, Fc_respi, Fc_point, Fc_traff, FlowChange, h_mod, id, imin, int_wu, it, iy, kup, LAI_id, ldown, l_mod, lup, mwh, MwStore, nsh_real, NWstate_per_tstep, Precip, q2_gkg, qeOut, qf, qh, qh_resist, Qm, QmFreez, QmRain, qn1, qn1_S, qn1_snowfree, qs, RA, resistsurf, RH2, runoffAGimpervious, runoffAGveg, runoff_per_tstep, runoffPipes, runoffSoil_per_tstep, runoffWaterBody, sfr, smd, smd_nsurf, SnowAlb, SnowRemoval, state_id, state_per_tstep, surf_chang_per_tstep, swe, t2_C, tskin_C, tot_chang_per_tstep, tsurf, UStar, wu_DecTr, wu_EveTr, wu_Grass, z0m, zdm, zenith_deg, datetimeLine, dataOutLineSUEWS)
subroutine suews_update_output (SnowUse, storageheatmethod, ReadLinesMetdata, NumberOfGrids, ir, gridiv, datetimeLine, dataOutLineSUEWS, dataOutLineSnow, dataOutLineESTM, dataoutLineURSL, dataOutSUEWS, dataOutSnow, dataOutESTM, dataOutRSL)
subroutine suews_cal_diagnostics (dectime, avU1, Temp_C, avRH, Press_hPa, qh, qe, VegFraction, zMeas, z0m, zdm, RA, avdens, avcp, lv_J_kg, tstep_real, RoughLenHeatMethod, StabilityMethod, avU10_ms, t2_C, q2_gkg, tskin_C, RH2)
subroutine suews_cal_surf (sfr, vegfraction, ImpervFraction, PervFraction, NonWaterFraction)
subroutine diagsfc (opt, zMeas, xMeas, xFlux, zDiag, xDiag, VegFraction, z0m, zd, avdens, avcp, lv_J_kg, avU1, Temp_C, qh, RoughLenHeatMethod, StabilityMethod, tstep_real, dectime)
elemental real(kind(1d0)) function set_nan (x)
real(kind(1d0)) function square (x)
real function square_real (x)
subroutine output_name_n (i, name, group, aggreg)
subroutine output_size (nVar)
subroutine suews_cal_multitsteps (MetForcingBlock, len_sim, AerodynamicResistanceMethod, AH_MIN, AHProf_24hr, AH_SLOPE_Cooling, AH_SLOPE_Heating, alb, AlbMax_DecTr, AlbMax_EveTr, AlbMax_Grass, AlbMin_DecTr, AlbMin_EveTr, AlbMin_Grass, alpha_bioCO2, alpha_enh_bioCO2, alt, BaseT, BaseTe, BaseTHDD, beta_bioCO2, beta_enh_bioCO2, bldgH, CapMax_dec, CapMin_dec, chAnOHM, CO2PointSource, cpAnOHM, CRWmax, CRWmin, DayWat, DayWatPer, DecTreeH, Diagnose, DiagQN, DiagQS, DRAINRT, dt_since_start, dqndt, qn1_av, dqnsdt, qn1_s_av, EF_umolCO2perJ, emis, EmissionsMethod, EnEF_v_Jkm, endDLS, EveTreeH, FAIBldg, FAIDecTree, FAIEveTree, Faut, FcEF_v_kgkm, FlowChange, FrFossilFuel_Heat, FrFossilFuel_NonHeat, G1, G2, G3, G4, G5, G6, GDD_id, GDDFull, Gridiv, gsModel, HDD_id, HumActivity_24hr, IceFrac, Ie_a, Ie_end, Ie_m, Ie_start, InternalWaterUse_h, IrrFracConif, IrrFracDecid, IrrFracGrass, EvapMethod, kkAnOHM, Kmax, LAI_id, LAICalcYes, LAIMax, LAIMin, LAIPower, LAIType, lat, lng, MaxConductance, MaxFCMetab, MaxQFMetab, SnowWater, MinFCMetab, MinQFMetab, min_res_bioCO2, NARP_EMIS_SNOW, NARP_TRANS_SITE, NetRadiationMethod, NumCapita, OHM_coef, OHMIncQF, OHM_threshSW, OHM_threshWD, PipeCapacity, PopDensDaytime, PopDensNighttime, PopProf_24hr, PorMax_dec, PorMin_dec, PrecipLimit, PrecipLimitAlb, QF0_BEU, Qf_A, Qf_B, Qf_C, RadMeltFact, RAINCOVER, RainMaxRes, resp_a, resp_b, RoughLenHeatMethod, RoughLenMomMethod, RunoffToWater, S1, S2, SatHydraulicConduct, SDDFull, sfr, SMDMethod, SnowAlb, SnowAlbMax, SnowAlbMin, SnowPackLimit, SnowDens, SnowDensMax, SnowDensMin, SnowfallCum, snowFrac, SnowLimBldg, SnowLimPaved, SnowPack, SnowProf_24hr, snowUse, SoilDepth, soilstore_id, SoilStoreCap, StabilityMethod, startDLS, state_id, StateLimit, StorageHeatMethod, StoreDrainPrm, SurfaceArea, Tair24HR, tau_a, tau_f, tau_r, T_CRITIC_Cooling, T_CRITIC_Heating, TempMeltFact, TH, theta_bioCO2, timezone, TL, TrafficRate, TrafficUnits, TraffProf_24hr, Ts5mindata_ir, tstep, tstep_prev, veg_type, WaterDist, WaterUseMethod, WetThresh, WUDay_id, DecidCap_id, albDecTr_id, albEveTr_id, albGrass_id, porosity_id, WUProfA_24hr, WUProfM_24hr, Z, z0m_in, zdm_in, dataOutBlockSUEWS, dataOutBlockSnow, dataOutBlockESTM, dataOutBlockRSL, DailyStateBlock)
subroutine suews_cal_sunposition (year, idectime, UTC, locationlatitude, locationlongitude, locationaltitude, sunazimuth, sunzenith)
Function/Subroutine Documentation
diagsfc()
subroutine suews_driver::diagsfc (integer, intent(in) opt, real(kind(1d0)), intent(in) zMeas, real(kind(1d0)), intent(in) xMeas, real(kind(1d0)), intent(in) xFlux, real(kind(1d0)), intent(in) zDiag, real(kind(1d0)), intent(out) xDiag, real(kind(1d0)), intent(in) VegFraction, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) zd, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) lv_J_kg, real(kind(1d0)), intent(in) avU1, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) qh, integer, intent(in) RoughLenHeatMethod, integer, intent(in) StabilityMethod, real(kind(1d0)), intent(in) tstep_real, real(kind(1d0)), intent(in) dectime)
Definition at line 2284 of file suews_ctrl_driver.f95.
       ! TS 31 Jul 2018: removed dependence on surface variables (Tsurf, qsat)
       ! TS 26 Jul 2018: improved the calculation logic
       ! TS 05 Sep 2017: improved interface
       ! TS 20 May 2017: calculate surface-level diagonostics
       IMPLICIT NONE
       REAL(KIND(1d0)), INTENT(in) :: dectime
       REAL(KIND(1d0)), INTENT(in) :: qh ! sensible heat flux
       REAL(KIND(1d0)), INTENT(in) :: z0m, avdens, avcp, lv_J_kg, tstep_real
       REAL(KIND(1d0)), INTENT(in) :: avU1, Temp_C ! atmospheric level variables
       REAL(KIND(1d0)), INTENT(in) :: zDiag ! height for diagonostics
       REAL(KIND(1d0)), INTENT(in) :: zMeas! height for measurement
       REAL(KIND(1d0)), INTENT(in) :: zd ! displacement height
       REAL(KIND(1d0)), INTENT(in) :: xMeas ! measurement at height
       REAL(KIND(1d0)), INTENT(in) :: xFlux!
       REAL(KIND(1d0)), INTENT(in) :: VegFraction ! vegetation fraction
       INTEGER, INTENT(in)         :: opt ! 0 for momentum, 1 for temperature, 2 for humidity
       INTEGER, INTENT(in)         :: RoughLenHeatMethod, StabilityMethod
       REAL(KIND(1d0)), INTENT(out):: xDiag
       REAL(KIND(1d0)) :: L_mod
       REAL(KIND(1d0)) :: psymz0, psyhzDiag, psyhzMeas, psyhz0, psymzDiag ! stability correction functions
       REAL(KIND(1d0)) :: z0h, cal_z0V ! Roughness length for heat
       REAL(KIND(1d0)) :: zDiagzd! height for diagnositcs
       REAL(KIND(1d0)) :: zMeaszd
       REAL(KIND(1d0)) :: tlv, H_kms, TStar, zL, UStar
       REAL(KIND(1d0)), PARAMETER :: muu = 1.46e-5 !molecular viscosity
       REAL(KIND(1d0)), PARAMETER :: nan = -999
       REAL(KIND(1d0)), PARAMETER :: zdm = 0 ! assuming Displacement height is ZERO
       REAL(KIND(1d0)), PARAMETER::k = 0.4
       tlv = lv_j_kg/tstep_real !Latent heat of vapourisation per timestep
       zdiagzd = zdiag + z0m ! height at hgtX assuming Displacement height is ZERO; set lower limit as z0 to prevent arithmetic error, zd=0
       ! get !Kinematic sensible heat flux [K m s-1] used to calculate friction velocity
       CALL suews_init_qh( &
          qh, avdens, avcp, qh, 0d0, dectime, & ! use qh as qh_obs to initialise H_init
          h_kms)!output
       ! redo the calculation for stability correction
       CALL stab_lumps( &
          ! input
          stabilitymethod, &
          dectime, & !Decimal time
          zdiagzd, &     !Active measurement height (meas. height-displac. height)
          z0m, &     !Aerodynamic roughness length
          zdm, &     !Displacement height
          avu1, &    !Average wind speed
          temp_c, &  !Air temperature
          h_kms, & !Kinematic sensible heat flux [K m s-1] used to calculate friction velocity
          ! output:
          l_mod, & !Obukhov length
          tstar, & !T*
          ustar, & !Friction velocity
          zl)!Stability scale
       !***************************************************************
       ! log-law based stability corrections:
       ! Roughness length for heat
       z0h = cal_z0v(roughlenheatmethod, z0m, vegfraction, ustar)
       ! stability correction functions
       ! momentum:
       psymzdiag = stab_fn_mom(stabilitymethod, zdiagzd/l_mod, zdiagzd/l_mod)
       ! psymz2=stab_fn_mom(StabilityMethod,z2zd/L_mod,z2zd/L_mod)
       psymz0 = stab_fn_mom(stabilitymethod, z0m/l_mod, z0m/l_mod)
       ! heat and vapor: assuming both are the same
       ! psyhz2=stab_fn_heat(StabilityMethod,z2zd/L_mod,z2zd/L_mod)
       psyhz0 = stab_fn_heat(stabilitymethod, z0h/l_mod, z0h/l_mod)
       !***************************************************************
       SELECT CASE (opt)
       CASE (0) ! wind (momentum) at hgtX=10 m
          zdiagzd = zdiag + z0m! set lower limit as z0h to prevent arithmetic error, zd=0
          ! stability correction functions
          ! momentum:
          psymzdiag = stab_fn_mom(stabilitymethod, zdiagzd/l_mod, zdiagzd/l_mod)
          psymz0 = stab_fn_mom(stabilitymethod, z0m/l_mod, z0m/l_mod)
          xdiag = ustar/k*(log(zdiagzd/z0m) - psymzdiag + psymz0) ! Brutsaert (2005), p51, eq.2.54
       CASE (1) ! temperature at hgtX=2 m
          zmeaszd = zmeas - zd
          zdiagzd = zdiag + z0h! set lower limit as z0h to prevent arithmetic error, zd=0
          ! heat and vapor: assuming both are the same
          psyhzmeas = stab_fn_heat(stabilitymethod, zmeaszd/l_mod, zmeaszd/l_mod)
          psyhzdiag = stab_fn_heat(stabilitymethod, zdiagzd/l_mod, zdiagzd/l_mod)
          ! psyhz0=stab_fn_heat(StabilityMethod,z0h/L_mod,z0h/L_mod)
          xdiag = xmeas + xflux/(k*ustar*avdens*avcp)*(log(zmeaszd/zdiagzd) - (psyhzmeas - psyhzdiag)) ! Brutsaert (2005), p51, eq.2.55
          !  IF ( ABS((LOG(z2zd/z0h)-psyhz2+psyhz0))>10 ) THEN
          !     PRINT*, '#####################################'
          !     PRINT*, 'xSurf',xSurf
          !     PRINT*, 'xFlux',xFlux
          !     PRINT*, 'k*us*avdens*avcp',k*us*avdens*avcp
          !     PRINT*, 'k',k
          !     PRINT*, 'us',us
          !     PRINT*, 'avdens',avdens
          !     PRINT*, 'avcp',avcp
          !     PRINT*, 'xFlux/X',xFlux/(k*us*avdens*avcp)
          !     PRINT*, 'stab',(LOG(z2zd/z0h)-psyhz2+psyhz0)
          !     PRINT*, 'LOG(z2zd/z0h)',LOG(z2zd/z0h)
          !     PRINT*, 'z2zd',z2zd,'L_mod',L_mod,'z0h',z0h
          !     PRINT*, 'z2zd/L_mod',z2zd/L_mod
          !     PRINT*, 'psyhz2',psyhz2
          !     PRINT*, 'psyhz0',psyhz0
          !     PRINT*, 'psyhz2-psyhz0',psyhz2-psyhz0
          !     PRINT*, 'xDiag',xDiag
          !     PRINT*, '*************************************'
          !  END IF
       CASE (2) ! humidity at hgtX=2 m
          zmeaszd = zmeas - zd
          zdiagzd = zdiag + z0h! set lower limit as z0h to prevent arithmetic error, zd=0
          ! heat and vapor: assuming both are the same
          psyhzmeas = stab_fn_heat(stabilitymethod, zmeaszd/l_mod, zmeaszd/l_mod)
          psyhzdiag = stab_fn_heat(stabilitymethod, zdiagzd/l_mod, zdiagzd/l_mod)
          ! psyhz0=stab_fn_heat(StabilityMethod,z0h/L_mod,z0h/L_mod)
          xdiag = xmeas + xflux/(k*ustar*avdens*tlv)*(log(zmeaszd/zdiagzd) - (psyhzmeas - psyhzdiag)) ! Brutsaert (2005), p51, eq.2.56
       END SELECT
References atmmoiststab_module::stab_fn_heat(), atmmoiststab_module::stab_fn_mom(), atmmoiststab_module::stab_lumps(), and suews_init_qh().
Referenced by suews_cal_diagnostics().
output_name_n()
subroutine suews_driver::output_name_n (integer, intent(in) i, character(len=15), intent(out) name, character(len=15), intent(out) group, character(len=15), intent(out) aggreg)
Definition at line 2456 of file suews_ctrl_driver.f95.
       ! used by f2py module `SuPy` to handle output names
       IMPLICIT NONE
       ! the dimension is potentially incorrect,
       ! which should be consistent with that in output module
       INTEGER, INTENT(in) :: i
       CHARACTER(len=15), INTENT(out) :: name, group, aggreg
       INTEGER :: nVar
       nvar = SIZE(varlistall, dim=1)
       IF (i < nvar .AND. i > 0) THEN
          name = trim(varlistall(i)%header)
          group = trim(varlistall(i)%group)
          aggreg = trim(varlistall(i)%aggreg)
       ELSE
          name = ''
          group = ''
          aggreg = ''
       END IF
References ctrl_output::varlistall.
output_size()
subroutine suews_driver::output_size (integer, intent(out) nVar)
Definition at line 2478 of file suews_ctrl_driver.f95.
       ! used by f2py module `SuPy` to get size of the output list
       IMPLICIT NONE
       ! the dimension is potentially incorrect,
       ! which should be consistent with that in output module
       INTEGER, INTENT(out) :: nVar
       nvar = SIZE(varlistall, dim=1)
References ctrl_output::varlistall.
set_nan()
elemental real(kind(1d0)) function suews_driver::set_nan (real(kind(1d0)), intent(in) x)
Definition at line 2415 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL(KIND(1d0)), PARAMETER::pNAN = 30000 ! 30000 to prevent water_state being filtered out as it can be large
       REAL(KIND(1d0)), PARAMETER::NAN = -999
       REAL(KIND(1d0)), INTENT(in)::x
       REAL(KIND(1d0))::xx
       IF (abs(x) > pnan) THEN
          xx = nan
       ELSE
          xx = x
       ENDIF
Referenced by suews_update_output().
square()
real(kind(1d0)) function suews_driver::square (real(kind(1d0)), intent(in) x)
Definition at line 2432 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL(KIND(1d0)), PARAMETER::pNAN = 9999
       REAL(KIND(1d0)), PARAMETER::NAN = -999
       REAL(KIND(1d0)), INTENT(in)::x
       REAL(KIND(1d0))::xx
       xx = x**2 + nan/pnan
       xx = x**2
square_real()
real function suews_driver::square_real (real, intent(in) x)
Definition at line 2444 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL, PARAMETER::pNAN = 9999
       REAL, PARAMETER::NAN = -999
       REAL, INTENT(in)::x
       REAL::xx
       xx = x**2 + nan/pnan
       xx = x**2
suews_cal_anthropogenicemission()
subroutine suews_driver::suews_cal_anthropogenicemission (real(kind(1d0)), dimension(2), intent(in) AH_MIN, real(kind(1d0)), dimension(0:23, 2), intent(in) AHProf_24hr, real(kind(1d0)), dimension(2), intent(in) AH_SLOPE_Cooling, real(kind(1d0)), dimension(2), intent(in) AH_SLOPE_Heating, real(kind(1d0)), intent(in) CO2PointSource, integer, dimension(3), intent(in) dayofWeek_id, integer, intent(in) Diagnose, integer, intent(in) DLS, real(kind(1d0)), intent(in) EF_umolCO2perJ, integer, intent(in) EmissionsMethod, real(kind(1d0)), intent(in) EnEF_v_Jkm, real(kind(1d0)), dimension(2), intent(in) FcEF_v_kgkm, real(kind(1d0)), intent(in) FrFossilFuel_Heat, real(kind(1d0)), intent(in) FrFossilFuel_NonHeat, real(kind(1d0)), dimension(6, 2), intent(in) HDD_id, real(kind(1d0)), dimension(0:23, 2), intent(in) HumActivity_24hr, integer, intent(in) id, integer, intent(in) imin, integer, intent(in) it, real(kind(1d0)), intent(in) MaxFCMetab, real(kind(1d0)), intent(in) MaxQFMetab, real(kind(1d0)), intent(in) MinFCMetab, real(kind(1d0)), intent(in) MinQFMetab, integer, intent(in) nsh, real(kind(1d0)), dimension(2), intent(in) NumCapita, real(kind(1d0)), dimension(2), intent(in) PopDensDaytime, real(kind(1d0)), intent(in) PopDensNighttime, real(kind(1d0)), dimension(0:23, 2), intent(in) PopProf_24hr, real(kind(1d0)), intent(out) QF, real(kind(1d0)), dimension(2), intent(in) QF0_BEU, real(kind(1d0)), dimension(2), intent(in) Qf_A, real(kind(1d0)), dimension(2), intent(in) Qf_B, real(kind(1d0)), dimension(2), intent(in) Qf_C, real(kind(1d0)), intent(in) QF_obs, real(kind(1d0)), intent(out) QF_SAHP, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(in) snowFrac, real(kind(1d0)), intent(in) SurfaceArea, real(kind(1d0)), dimension(2), intent(in) T_CRITIC_Cooling, real(kind(1d0)), dimension(2), intent(in) T_CRITIC_Heating, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), dimension(2), intent(in) TrafficRate, real(kind(1d0)), intent(in) TrafficUnits, real(kind(1d0)), dimension(0:23, 2), intent(in) TraffProf_24hr, real(kind(1d0)), intent(out) Fc_anthro, real(kind(1d0)), intent(out) Fc_build, real(kind(1d0)), intent(out) Fc_metab, real(kind(1d0)), intent(out) Fc_point, real(kind(1d0)), intent(out) Fc_traff)
Definition at line 813 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in)::Diagnose
       INTEGER, INTENT(in)::DLS
       INTEGER, INTENT(in)::EmissionsMethod
       INTEGER, INTENT(in)::id
       INTEGER, INTENT(in)::it
       INTEGER, INTENT(in)::imin
       INTEGER, INTENT(in)::nsh
       INTEGER, DIMENSION(3), INTENT(in)::dayofWeek_id
       REAL(KIND(1d0)), DIMENSION(6, 2), INTENT(in)::HDD_id
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::AH_MIN
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::AH_SLOPE_Heating
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::AH_SLOPE_Cooling
       REAL(KIND(1D0)), DIMENSION(2), INTENT(in)::FcEF_v_kgkm
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::NumCapita
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::PopDensDaytime
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::QF0_BEU
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::Qf_A
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::Qf_B
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::Qf_C
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::T_CRITIC_Heating
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::T_CRITIC_Cooling
       REAL(KIND(1d0)), DIMENSION(2), INTENT(in)::TrafficRate
       REAL(KIND(1d0)), DIMENSION(0:23, 2), INTENT(in)::AHProf_24hr
       REAL(KIND(1d0)), DIMENSION(0:23, 2), INTENT(in)::HumActivity_24hr
       REAL(KIND(1d0)), DIMENSION(0:23, 2), INTENT(in)::TraffProf_24hr
       REAL(KIND(1d0)), DIMENSION(0:23, 2), INTENT(in)::PopProf_24hr
       REAL(KIND(1D0)), INTENT(in)::CO2PointSource
       REAL(KIND(1D0)), INTENT(in)::EF_umolCO2perJ
       REAL(KIND(1D0)), INTENT(in)::EnEF_v_Jkm
       REAL(KIND(1D0)), INTENT(in)::FrFossilFuel_Heat
       REAL(KIND(1D0)), INTENT(in)::FrFossilFuel_NonHeat
       REAL(KIND(1D0)), INTENT(in)::MaxFCMetab
       REAL(KIND(1D0)), INTENT(in)::MaxQFMetab
       REAL(KIND(1D0)), INTENT(in)::MinFCMetab
       REAL(KIND(1D0)), INTENT(in)::MinQFMetab
       REAL(KIND(1D0)), INTENT(in)::PopDensNighttime
       REAL(KIND(1D0)), INTENT(in)::QF_obs
       REAL(KIND(1D0)), INTENT(in)::Temp_C
       REAL(KIND(1D0)), INTENT(in)::TrafficUnits
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::snowFrac
       REAL(KIND(1D0)), INTENT(IN)::SurfaceArea
       REAL(KIND(1D0)), INTENT(out)::Fc_anthro
       REAL(KIND(1D0)), INTENT(out)::Fc_build
       REAL(KIND(1D0)), INTENT(out)::Fc_metab
       REAL(KIND(1D0)), INTENT(out)::Fc_point
       REAL(KIND(1D0)), INTENT(out)::Fc_traff
       REAL(KIND(1D0)), INTENT(out)::QF
       REAL(KIND(1D0)), INTENT(out)::QF_SAHP
       INTEGER, PARAMETER :: notUsedI = -999
       REAL(KIND(1D0)), PARAMETER::notUsed = -999
       IF (emissionsmethod == 0) THEN ! use observed qf
          qf = qf_obs
       ELSEIF ((emissionsmethod > 0 .AND. emissionsmethod <= 6) .OR. emissionsmethod >= 11) THEN
          CALL anthropogenicemissions( &
             co2pointsource, emissionsmethod, &
             id, it, imin, dls, nsh, dayofweek_id, &
             ef_umolco2perj, fcef_v_kgkm, enef_v_jkm, trafficunits, &
             frfossilfuel_heat, frfossilfuel_nonheat, &
             minfcmetab, maxfcmetab, minqfmetab, maxqfmetab, &
             numcapita, popdensdaytime, popdensnighttime, &
             temp_c, hdd_id, qf_a, qf_b, qf_c, &
             ah_min, ah_slope_heating, ah_slope_cooling, &
             t_critic_heating, t_critic_cooling, &
             trafficrate, &
             qf0_beu, qf_sahp, &
             fc_anthro, fc_metab, fc_traff, fc_build, fc_point, &
             ahprof_24hr, humactivity_24hr, traffprof_24hr, popprof_24hr, surfacearea)
       ELSE
          CALL errorhint(73, 'RunControl.nml:EmissionsMethod unusable', notused, notused, emissionsmethod)
       ENDIF
       IF (emissionsmethod >= 1) qf = qf_sahp
       IF (emissionsmethod >= 0 .AND. emissionsmethod <= 6) THEN
          fc_anthro = 0
          fc_metab = 0
          fc_traff = 0
          fc_build = 0
          fc_point = 0
       ENDIF
References anthropogenicemissions(), and errorhint().
Referenced by suews_cal_main().
suews_cal_biogenco2()
subroutine suews_driver::suews_cal_biogenco2 (real(kind(1d0)), dimension(nvegsurf), intent(in) alpha_bioCO2, real(kind(1d0)), dimension(nvegsurf), intent(in) alpha_enh_bioCO2, real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) avRh, real(kind(1d0)), dimension(nvegsurf), intent(in) beta_bioCO2, real(kind(1d0)), dimension(nvegsurf), intent(in) beta_enh_bioCO2, integer, intent(in) BSoilSurf, integer, intent(in) ConifSurf, integer, intent(in) DecidSurf, real(kind(1d0)), intent(in) dectime, integer, intent(in) Diagnose, integer, intent(in) EmissionsMethod, real(kind(1d0)), intent(in) Fc_anthro, real(kind(1d0)), intent(in) G1, real(kind(1d0)), intent(in) G2, real(kind(1d0)), intent(in) G3, real(kind(1d0)), intent(in) G4, real(kind(1d0)), intent(in) G5, real(kind(1d0)), intent(in) G6, real(kind(1d0)), intent(in) gfunc, integer, intent(in) GrassSurf, integer, intent(in) gsmodel, integer, intent(in) id, integer, intent(in) it, integer, intent(in) ivConif, integer, intent(in) ivDecid, integer, intent(in) ivGrass, real(kind(1d0)), intent(in) Kmax, real(kind(1d0)), dimension(nvegsurf), intent(in) LAI_id, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMin, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMax, real(kind(1d0)), dimension(3), intent(in) MaxConductance, real(kind(1d0)), dimension(nvegsurf), intent(in) min_res_bioCO2, integer, intent(in) nsurf, integer, intent(in) NVegSurf, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), dimension(nvegsurf), intent(in) resp_a, real(kind(1d0)), dimension(nvegsurf), intent(in) resp_b, real(kind(1d0)), intent(in) S1, real(kind(1d0)), intent(in) S2, real(kind(1d0)), dimension(nsurf), intent(in) sfr, integer, intent(in) SMDMethod, real(kind(1d0)), dimension(nsurf), intent(in) snowFrac, real(kind(1d0)), intent(in) t2_C, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), dimension(nvegsurf), intent(in) theta_bioCO2, real(kind(1d0)), intent(in) TH, real(kind(1d0)), intent(in) TL, real(kind(1d0)), intent(in) vsmd, real(kind(1d0)), intent(in) xsmd, real(kind(1d0)), intent(out) Fc, real(kind(1d0)), intent(out) Fc_biogen, real(kind(1d0)), intent(out) Fc_photo, real(kind(1d0)), intent(out) Fc_respi)
Definition at line 918 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::alpha_bioCO2
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::alpha_enh_bioCO2
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::beta_bioCO2
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::beta_enh_bioCO2
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::LAI_id
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::LAIMin
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::LAIMax
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::min_res_bioCO2
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::resp_a
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::resp_b
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(in)::theta_bioCO2
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::snowFrac
       REAL(KIND(1d0)), DIMENSION(3), INTENT(in)::MaxConductance
       INTEGER, INTENT(in)::BSoilSurf
       INTEGER, INTENT(in)::ConifSurf
       INTEGER, INTENT(in)::DecidSurf
       INTEGER, INTENT(in)::Diagnose
       INTEGER, INTENT(in)::EmissionsMethod
       INTEGER, INTENT(in)::GrassSurf
       INTEGER, INTENT(in)::gsmodel
       INTEGER, INTENT(in)::id
       INTEGER, INTENT(in)::it
       INTEGER, INTENT(in)::ivConif
       INTEGER, INTENT(in)::ivDecid
       INTEGER, INTENT(in)::ivGrass
       INTEGER, INTENT(in)::nsurf
       INTEGER, INTENT(in)::NVegSurf
       INTEGER, INTENT(in)::SMDMethod
       REAL(KIND(1d0)), INTENT(in)::avkdn
       REAL(KIND(1d0)), INTENT(in)::avRh
       REAL(KIND(1d0)), INTENT(in)::dectime
       REAL(KIND(1d0)), INTENT(in)::Fc_anthro
       REAL(KIND(1d0)), INTENT(in)::G1
       REAL(KIND(1d0)), INTENT(in)::G2
       REAL(KIND(1d0)), INTENT(in)::G3
       REAL(KIND(1d0)), INTENT(in)::G4
       REAL(KIND(1d0)), INTENT(in)::G5
       REAL(KIND(1d0)), INTENT(in)::G6
       REAL(KIND(1d0)), INTENT(in)::gfunc
       REAL(KIND(1d0)), INTENT(in)::Kmax
       REAL(KIND(1d0)), INTENT(in)::Press_hPa
       REAL(KIND(1d0)), INTENT(in)::S1
       REAL(KIND(1d0)), INTENT(in)::S2
       REAL(KIND(1d0)), INTENT(in)::t2_C
       REAL(KIND(1d0)), INTENT(in)::Temp_C
       REAL(KIND(1d0)), INTENT(in)::TH
       REAL(KIND(1d0)), INTENT(in)::TL
       REAL(KIND(1d0)), INTENT(in)::vsmd
       REAL(KIND(1d0)), INTENT(in)::xsmd
       REAL(KIND(1d0)), INTENT(out)::Fc_biogen
       REAL(KIND(1d0)), INTENT(out)::Fc_photo
       REAL(KIND(1d0)), INTENT(out)::Fc_respi
       REAL(KIND(1d0)), INTENT(out)::Fc
       REAL(KIND(1d0))::gfunc2
       REAL(KIND(1d0))::dq
       REAL(KIND(1d0))::t2
       REAL(KIND(1d0))::dummy1
       REAL(KIND(1d0))::dummy2
       REAL(KIND(1d0))::dummy3
       REAL(KIND(1d0))::dummy4
       REAL(KIND(1d0))::dummy5
       REAL(KIND(1d0))::dummy6
       REAL(KIND(1d0))::dummy7
       REAL(KIND(1d0))::dummy8
       REAL(KIND(1d0))::dummy9
       REAL(KIND(1d0))::dummy10
       REAL(KIND(1d0))::dummy11
       IF (emissionsmethod >= 11) THEN
          IF (gsmodel == 3 .OR. gsmodel == 4) THEN ! With modelled 2 meter temperature
             ! Call LUMPS_cal_AtmMoist for dq and SurfaceResistance for gfunc with 2 meter temperature
             ! If modelled 2 meter temperature is too different from measured air temperature then
             ! use temp_c
             IF (abs(temp_c - t2_c) > 5) THEN
                t2 = temp_c
             ELSE
                t2 = t2_c
             ENDIF
             CALL lumps_cal_atmmoist( &
                t2, press_hpa, avrh, dectime, &! input:
                dummy1, dummy2, &! output:
                dummy3, dummy4, dummy5, dummy6, dq, dummy7, dummy8, dummy9)
             CALL surfaceresistance( &
                id, it, &! input:
                smdmethod, snowfrac, sfr, avkdn, t2, dq, xsmd, vsmd, maxconductance, &
                laimax, lai_id, gsmodel, kmax, &
                g1, g2, g3, g4, g5, g6, th, tl, s1, s2, &
                gfunc2, dummy10, dummy11)! output:
          ENDIF
          ! Calculate CO2 fluxes from biogenic components
          IF (diagnose == 1) WRITE (*, *) 'Calling CO2_biogen...'
          CALL co2_biogen( &
             alpha_bioco2, alpha_enh_bioco2, avkdn, beta_bioco2, beta_enh_bioco2, bsoilsurf, &! input:
             conifsurf, decidsurf, dectime, emissionsmethod, gfunc, gfunc2, grasssurf, gsmodel, &
             id, it, ivconif, ivdecid, ivgrass, lai_id, laimin, laimax, min_res_bioco2, nsurf, &
             nvegsurf, resp_a, resp_b, sfr, snowfrac, t2, temp_c, theta_bioco2, &
             fc_biogen, fc_photo, fc_respi)! output:
       ENDIF
       IF (emissionsmethod >= 0 .AND. emissionsmethod <= 6) THEN
          fc_biogen = 0
          fc_photo = 0
          fc_respi = 0
       ENDIF
       fc = fc_anthro + fc_biogen
References co2_biogen(), atmmoiststab_module::lumps_cal_atmmoist(), and surfaceresistance().
Referenced by suews_cal_main().
suews_cal_diagnostics()
subroutine suews_driver::suews_cal_diagnostics (real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(in) avU1, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) avRH, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), intent(in) qh, real(kind(1d0)), intent(in) qe, real(kind(1d0)), intent(in) VegFraction, real(kind(1d0)), intent(in) zMeas, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) zdm, real(kind(1d0)), intent(in) RA, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) lv_J_kg, real(kind(1d0)), intent(in) tstep_real, integer, intent(in) RoughLenHeatMethod, integer, intent(in) StabilityMethod, real(kind(1d0)), intent(out) avU10_ms, real(kind(1d0)), intent(out) t2_C, real(kind(1d0)), intent(out) q2_gkg, real(kind(1d0)), intent(out) tskin_C, real(kind(1d0)), intent(out) RH2)
Definition at line 2196 of file suews_ctrl_driver.f95.
       ! TS 03 Aug 2018: added limit on q2 by restricting RH2_max to 100%
       ! TS 31 Jul 2018: removed dependence on surface variables (Tsurf, qsat)
       ! TS 26 Jul 2018: improved the calculation logic
       ! TS 05 Sep 2017: improved interface
       ! TS 20 May 2017: calculate surface-level diagonostics
       IMPLICIT NONE
       REAL(KIND(1d0)), INTENT(in) ::dectime
       REAL(KIND(1d0)), INTENT(in) ::avU1, Temp_C, avRH
       REAL(KIND(1d0)), INTENT(in) ::qh
       REAL(KIND(1d0)), INTENT(in) ::Press_hPa, qe
       REAL(KIND(1d0)), INTENT(in) :: VegFraction, z0m, RA, avdens, avcp, lv_J_kg, tstep_real
       REAL(KIND(1d0)), INTENT(in) :: zMeas! height for measurement
       REAL(KIND(1d0)), INTENT(in) :: zdm ! displacement height
       ! INTEGER,INTENT(in)         :: opt ! 0 for momentum, 1 for temperature, 2 for humidity
       INTEGER, INTENT(in)         :: RoughLenHeatMethod, StabilityMethod
       REAL(KIND(1d0)), INTENT(out):: avU10_ms, t2_C, q2_gkg, tskin_C, RH2
       REAL(KIND(1d0))::qa_gkg
       REAL(KIND(1d0)), PARAMETER::k = 0.4
       ! wind speed:
       CALL diagsfc( &
          0, &
          zmeas, avu1, 0d0, 10d0, avu10_ms, &
          vegfraction, &
          z0m, zdm, avdens, avcp, lv_j_kg, &
          avu1, temp_c, qh, &
          roughlenheatmethod, stabilitymethod, tstep_real, dectime)
       ! temperature at 2 m agl:
       CALL diagsfc( &
          1, &
          zmeas, temp_c, qh, 2d0, t2_c, &
          vegfraction, &
          z0m, zdm, avdens, avcp, lv_j_kg, &
          avu1, temp_c, qh, &
          roughlenheatmethod, stabilitymethod, tstep_real, dectime)
       ! skin temperature:
       tskin_c = qh/(avdens*avcp)*ra + temp_c
       ! humidity:
       qa_gkg = rh2qa(avrh/100, press_hpa, temp_c)
       CALL diagsfc( &
          2, &
          zmeas, qa_gkg, qe, 2d0, q2_gkg, &
          vegfraction, &
          z0m, zdm, avdens, avcp, lv_j_kg, &
          avu1, temp_c, qh, &
          roughlenheatmethod, stabilitymethod, tstep_real, dectime)
       ! re-examine if the diagnostic RH2 > 100% ?
       rh2 = qa2rh(q2_gkg, press_hpa, temp_c)
       IF (rh2 > 1) THEN
          ! if so, limit RH2 to 100%
          rh2 = 1d0
          ! and adjust the diagnostic q2_gkg
          q2_gkg = rh2qa(rh2, press_hpa, temp_c)
       END IF
References diagsfc(), meteo::qa2rh(), and meteo::rh2qa().
Referenced by suews_cal_main().
suews_cal_main()
subroutine suews_driver::suews_cal_main (integer, intent(in) AerodynamicResistanceMethod, real(kind(1d0)), dimension(2), intent(in) AH_MIN, real(kind(1d0)), dimension(0:23, 2), intent(in) AHProf_24hr, real(kind(1d0)), dimension(2), intent(in) AH_SLOPE_Cooling, real(kind(1d0)), dimension(2), intent(in) AH_SLOPE_Heating, real(kind(1d0)), dimension(nsurf), intent(inout) alb, real(kind(1d0)), intent(in) AlbMax_DecTr, real(kind(1d0)), intent(in) AlbMax_EveTr, real(kind(1d0)), intent(in) AlbMax_Grass, real(kind(1d0)), intent(in) AlbMin_DecTr, real(kind(1d0)), intent(in) AlbMin_EveTr, real(kind(1d0)), intent(in) AlbMin_Grass, real(kind(1d0)), dimension(nvegsurf), intent(in) alpha_bioCO2, real(kind(1d0)), dimension(nvegsurf), intent(in) alpha_enh_bioCO2, real(kind(1d0)), intent(in) alt, real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) avRh, real(kind(1d0)), intent(in) avU1, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseT, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseTe, real(kind(1d0)), intent(in) BaseTHDD, real(kind(1d0)), dimension(nvegsurf), intent(in) beta_bioCO2, real(kind(1d0)), dimension(nvegsurf), intent(in) beta_enh_bioCO2, real(kind(1d0)), intent(in) bldgH, real(kind(1d0)), intent(in) CapMax_dec, real(kind(1d0)), intent(in) CapMin_dec, real(kind(1d0)), dimension(nsurf), intent(in) chAnOHM, real(kind(1d0)), intent(in) CO2PointSource, real(kind(1d0)), dimension(nsurf), intent(in) cpAnOHM, real(kind(1d0)), intent(in) CRWmax, real(kind(1d0)), intent(in) CRWmin, real(kind(1d0)), dimension(7), intent(in) DayWat, real(kind(1d0)), dimension(7), intent(in) DayWatPer, real(kind(1d0)), intent(in) DecTreeH, integer, intent(in) Diagnose, integer, intent(in) DiagQN, integer, intent(in) DiagQS, real(kind(1d0)), intent(in) DRAINRT, integer, intent(in) dt_since_start, real(kind(1d0)), intent(inout) dqndt, real(kind(1d0)), intent(inout) qn1_av, real(kind(1d0)), intent(inout) dqnsdt, real(kind(1d0)), intent(inout) qn1_s_av, real(kind(1d0)), intent(in) EF_umolCO2perJ, real(kind(1d0)), dimension(nsurf), intent(in) emis, integer, intent(in) EmissionsMethod, real(kind(1d0)), intent(in) EnEF_v_Jkm, integer, intent(in) endDLS, real(kind(1d0)), intent(in) EveTreeH, real(kind(1d0)), intent(in) FAIBldg, real(kind(1d0)), intent(in) FAIDecTree, real(kind(1d0)), intent(in) FAIEveTree, real(kind(1d0)), intent(in) Faut, real(kind(1d0)), dimension(2), intent(in) FcEF_v_kgkm, real(kind(1d0)), intent(in) fcld_obs, real(kind(1d0)), intent(in) FlowChange, real(kind(1d0)), intent(in) FrFossilFuel_Heat, real(kind(1d0)), intent(in) FrFossilFuel_NonHeat, real(kind(1d0)), intent(in) G1, real(kind(1d0)), intent(in) G2, real(kind(1d0)), intent(in) G3, real(kind(1d0)), intent(in) G4, real(kind(1d0)), intent(in) G5, real(kind(1d0)), intent(in) G6, real(kind(1d0)), dimension(5), intent(inout) GDD_id, real(kind(1d0)), dimension(nvegsurf), intent(in) GDDFull, integer, intent(in) Gridiv, integer, intent(in) gsModel, real(kind(1d0)), dimension(12), intent(inout) HDD_id, real(kind(1d0)), dimension(0:23, 2), intent(in) HumActivity_24hr, real(kind(1d0)), dimension(nsurf), intent(inout) IceFrac, integer, intent(in) id, real(kind(1d0)), dimension(3), intent(in) Ie_a, integer, intent(in) Ie_end, real(kind(1d0)), dimension(3), intent(in) Ie_m, integer, intent(in) Ie_start, integer, intent(in) imin, real(kind(1d0)), intent(in) InternalWaterUse_h, real(kind(1d0)), intent(in) IrrFracConif, real(kind(1d0)), intent(in) IrrFracDecid, real(kind(1d0)), intent(in) IrrFracGrass, integer, intent(in) isec, integer, intent(in) it, integer, intent(in) EvapMethod, integer, intent(in) iy, real(kind(1d0)), dimension(nsurf), intent(in) kkAnOHM, real(kind(1d0)), intent(in) Kmax, real(kind(1d0)), dimension(nvegsurf), intent(inout) LAI_id, integer, intent(in) LAICalcYes, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMax, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMin, real(kind(1d0)), intent(in) LAI_obs, real(kind(1d0)), dimension(4, nvegsurf), intent(in) LAIPower, integer, dimension(nvegsurf), intent(in) LAIType, real(kind(1d0)), intent(in) lat, real(kind(1d0)), intent(in) ldown_obs, real(kind(1d0)), intent(in) lng, real(kind(1d0)), dimension(3), intent(in) MaxConductance, real(kind(1d0)), intent(in) MaxFCMetab, real(kind(1d0)), intent(in) MaxQFMetab, real(kind(1d0)), dimension(nsurf), intent(inout) SnowWater, real(kind(1d0)), dimension(:, :), intent(in) MetForcingData_grid, real(kind(1d0)), intent(in) MinFCMetab, real(kind(1d0)), intent(in) MinQFMetab, real(kind(1d0)), dimension(nvegsurf), intent(in) min_res_bioCO2, real(kind(1d0)), intent(in) NARP_EMIS_SNOW, real(kind(1d0)), intent(in) NARP_TRANS_SITE, integer, intent(in) NetRadiationMethod, real(kind(1d0)), dimension(2), intent(in) NumCapita, real(kind(1d0)), dimension(nsurf + 1, 4, 3), intent(in) OHM_coef, integer, intent(in) OHMIncQF, real(kind(1d0)), dimension(nsurf + 1), intent(in) OHM_threshSW, real(kind(1d0)), dimension(nsurf + 1), intent(in) OHM_threshWD, real(kind(1d0)), intent(in) PipeCapacity, real(kind(1d0)), dimension(2), intent(in) PopDensDaytime, real(kind(1d0)), intent(in) PopDensNighttime, real(kind(1d0)), dimension(0:23, 2), intent(in) PopProf_24hr, real(kind(1d0)), intent(in) PorMax_dec, real(kind(1d0)), intent(in) PorMin_dec, real(kind(1d0)), intent(in) Precip, real(kind(1d0)), intent(in) PrecipLimit, real(kind(1d0)), intent(in) PrecipLimitAlb, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), dimension(2), intent(in) QF0_BEU, real(kind(1d0)), dimension(2), intent(in) Qf_A, real(kind(1d0)), dimension(2), intent(in) Qf_B, real(kind(1d0)), dimension(2), intent(in) Qf_C, real(kind(1d0)), intent(in) qn1_obs, real(kind(1d0)), intent(in) qh_obs, real(kind(1d0)), intent(in) qs_obs, real(kind(1d0)), intent(in) qf_obs, real(kind(1d0)), intent(in) RadMeltFact, real(kind(1d0)), intent(in) RAINCOVER, real(kind(1d0)), intent(in) RainMaxRes, real(kind(1d0)), dimension(nvegsurf), intent(in) resp_a, real(kind(1d0)), dimension(nvegsurf), intent(in) resp_b, integer, intent(in) RoughLenHeatMethod, integer, intent(in) RoughLenMomMethod, real(kind(1d0)), intent(in) RunoffToWater, real(kind(1d0)), intent(in) S1, real(kind(1d0)), intent(in) S2, real(kind(1d0)), dimension(nsurf), intent(in) SatHydraulicConduct, real(kind(1d0)), dimension(nvegsurf), intent(in) SDDFull, real(kind(1d0)), dimension(nsurf), intent(in) sfr, integer, intent(in) SMDMethod, real(kind(1d0)), intent(inout) SnowAlb, real(kind(1d0)), intent(in) SnowAlbMax, real(kind(1d0)), intent(in) SnowAlbMin, real(kind(1d0)), dimension(nsurf), intent(in) SnowPackLimit, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens, real(kind(1d0)), intent(in) SnowDensMax, real(kind(1d0)), intent(in) SnowDensMin, real(kind(1d0)), intent(inout) SnowfallCum, real(kind(1d0)), dimension(nsurf), intent(inout) snowFrac, real(kind(1d0)), intent(in) SnowLimBldg, real(kind(1d0)), intent(in) SnowLimPaved, real(kind(1d0)), intent(in) snowFrac_obs, real(kind(1d0)), dimension(nsurf), intent(inout) SnowPack, real(kind(1d0)), dimension(0:23, 2), intent(in) SnowProf_24hr, integer, intent(in) snowUse, real(kind(1d0)), dimension(nsurf), intent(in) SoilDepth, real(kind(1d0)), dimension(nsurf), intent(inout) soilstore_id, real(kind(1d0)), dimension(nsurf), intent(in) SoilStoreCap, integer, intent(in) StabilityMethod, integer, intent(in) startDLS, real(kind(1d0)), dimension(nsurf), intent(inout) state_id, real(kind(1d0)), dimension(nsurf), intent(in) StateLimit, integer, intent(in) StorageHeatMethod, real(kind(1d0)), dimension(6, nsurf), intent(inout) StoreDrainPrm, real(kind(1d0)), intent(in) SurfaceArea, real(kind(1d0)), dimension(24*3600/tstep), intent(inout) Tair24HR, real(kind(1d0)), intent(in) tau_a, real(kind(1d0)), intent(in) tau_f, real(kind(1d0)), intent(in) tau_r, real(kind(1d0)), dimension(2), intent(in) T_CRITIC_Cooling, real(kind(1d0)), dimension(2), intent(in) T_CRITIC_Heating, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) TempMeltFact, real(kind(1d0)), intent(in) TH, real(kind(1d0)), dimension(nvegsurf), intent(in) theta_bioCO2, real(kind(1d0)), intent(in) timezone, real(kind(1d0)), intent(in) TL, real(kind(1d0)), dimension(2), intent(in) TrafficRate, real(kind(1d0)), intent(in) TrafficUnits, real(kind(1d0)), dimension(0:23, 2), intent(in) TraffProf_24hr, real(kind(1d0)), dimension(:), intent(in) Ts5mindata_ir, integer, intent(in) tstep, integer, intent(in) tstep_prev, integer, intent(in) veg_type, real(kind(1d0)), dimension(nsurf + 1, nsurf - 1), intent(in) WaterDist, integer, intent(in) WaterUseMethod, real(kind(1d0)), dimension(nsurf), intent(in) WetThresh, real(kind(1d0)), intent(in) wu_m3, real(kind(1d0)), dimension(9), intent(inout) WUDay_id, real(kind(1d0)), intent(inout) DecidCap_id, real(kind(1d0)), intent(inout) albDecTr_id, real(kind(1d0)), intent(inout) albEveTr_id, real(kind(1d0)), intent(inout) albGrass_id, real(kind(1d0)), intent(inout) porosity_id, real(kind(1d0)), dimension(0:23, 2), intent(in) WUProfA_24hr, real(kind(1d0)), dimension(0:23, 2), intent(in) WUProfM_24hr, real(kind(1d0)), intent(in) xsmd, real(kind(1d0)), intent(in) Z, real(kind(1d0)), intent(in) z0m_in, real(kind(1d0)), intent(in) zdm_in, real(kind(1d0)), dimension(5), intent(out) datetimeLine, real(kind(1d0)), dimension(ncolumnsdataoutsuews - 5), intent(out) dataOutLineSUEWS, real(kind(1d0)), dimension(ncolumnsdataoutsnow - 5), intent(out) dataOutLineSnow, real(kind(1d0)), dimension(ncolumnsdataoutestm - 5), intent(out) dataOutLineESTM, real(kind(1d0)), dimension(ncolumnsdataoutrsl - 5), intent(out) dataoutLineRSL, real(kind(1d0)), dimension(ncolumnsdataoutdailystate - 5), intent(out) DailyStateLine)
Definition at line 73 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       ! ########################################################################################
       ! input variables
       INTEGER, INTENT(IN)::AerodynamicResistanceMethod
       INTEGER, INTENT(IN)::Diagnose
       INTEGER, INTENT(IN)::DiagQN
       INTEGER, INTENT(IN)::DiagQS
       INTEGER, INTENT(IN)::startDLS
       INTEGER, INTENT(IN)::endDLS
       INTEGER, INTENT(IN)::EmissionsMethod
       INTEGER, INTENT(IN)::Gridiv
       INTEGER, INTENT(IN)::gsModel
       INTEGER, INTENT(IN)::id
       INTEGER, INTENT(IN)::Ie_end
       INTEGER, INTENT(IN)::Ie_start
       INTEGER, INTENT(IN)::isec
       INTEGER, INTENT(IN)::imin
       INTEGER, INTENT(IN)::it
       INTEGER, INTENT(IN)::EvapMethod
       INTEGER, INTENT(IN)::iy
       INTEGER, INTENT(IN)::LAICalcYes
       INTEGER, INTENT(IN)::NetRadiationMethod
       INTEGER, INTENT(IN)::OHMIncQF
       INTEGER, INTENT(IN)::RoughLenHeatMethod
       INTEGER, INTENT(IN)::RoughLenMomMethod
       INTEGER, INTENT(IN)::SMDMethod
       INTEGER, INTENT(IN)::snowUse
       INTEGER, INTENT(IN)::StabilityMethod
       INTEGER, INTENT(IN)::StorageHeatMethod
       INTEGER, INTENT(IN)::tstep
       INTEGER, INTENT(IN)::tstep_prev ! tstep size of the previous step
       INTEGER, INTENT(in)::dt_since_start ! time since simulation starts [s]
       INTEGER, INTENT(IN)::veg_type
       INTEGER, INTENT(IN)::WaterUseMethod
       REAL(KIND(1D0)), INTENT(IN)::AlbMax_DecTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMax_EveTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMax_Grass
       REAL(KIND(1D0)), INTENT(IN)::AlbMin_DecTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMin_EveTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMin_Grass
       REAL(KIND(1D0)), INTENT(IN)::alt
       REAL(KIND(1D0)), INTENT(IN)::avkdn
       REAL(KIND(1D0)), INTENT(IN)::avRh
       REAL(KIND(1D0)), INTENT(IN)::avU1
       REAL(KIND(1D0)), INTENT(IN)::BaseTHDD
       REAL(KIND(1D0)), INTENT(IN)::bldgH
       REAL(KIND(1D0)), INTENT(IN)::CapMax_dec
       REAL(KIND(1D0)), INTENT(IN)::CapMin_dec
       REAL(KIND(1D0)), INTENT(IN)::CO2PointSource
       REAL(KIND(1D0)), INTENT(IN)::CRWmax
       REAL(KIND(1D0)), INTENT(IN)::CRWmin
       REAL(KIND(1D0)), INTENT(IN)::DecTreeH
       REAL(KIND(1D0)), INTENT(IN)::DRAINRT
       REAL(KIND(1D0)), INTENT(IN)::EF_umolCO2perJ
       REAL(KIND(1D0)), INTENT(IN)::EnEF_v_Jkm
       REAL(KIND(1D0)), INTENT(IN)::EveTreeH
       REAL(KIND(1D0)), INTENT(IN)::FAIBldg
       REAL(KIND(1D0)), INTENT(IN)::FAIDecTree
       REAL(KIND(1D0)), INTENT(IN)::FAIEveTree
       REAL(KIND(1D0)), INTENT(IN)::Faut
       REAL(KIND(1D0)), INTENT(IN)::fcld_obs
       REAL(KIND(1D0)), INTENT(IN)::FlowChange
       REAL(KIND(1D0)), INTENT(IN)::FrFossilFuel_Heat
       REAL(KIND(1D0)), INTENT(IN)::FrFossilFuel_NonHeat
       REAL(KIND(1D0)), INTENT(IN)::G1
       REAL(KIND(1D0)), INTENT(IN)::G2
       REAL(KIND(1D0)), INTENT(IN)::G3
       REAL(KIND(1D0)), INTENT(IN)::G4
       REAL(KIND(1D0)), INTENT(IN)::G5
       REAL(KIND(1D0)), INTENT(IN)::G6
       REAL(KIND(1D0)), INTENT(IN)::InternalWaterUse_h
       REAL(KIND(1D0)), INTENT(IN)::IrrFracConif
       REAL(KIND(1D0)), INTENT(IN)::IrrFracDecid
       REAL(KIND(1D0)), INTENT(IN)::IrrFracGrass
       REAL(KIND(1D0)), INTENT(IN)::Kmax
       REAL(KIND(1D0)), INTENT(IN)::LAI_obs
       REAL(KIND(1D0)), INTENT(IN)::lat
       REAL(KIND(1D0)), INTENT(IN)::ldown_obs
       REAL(KIND(1D0)), INTENT(IN)::lng
       REAL(KIND(1D0)), INTENT(IN)::MaxFCMetab
       REAL(KIND(1D0)), INTENT(IN)::MaxQFMetab
       REAL(KIND(1D0)), INTENT(IN)::MinFCMetab
       REAL(KIND(1D0)), INTENT(IN)::MinQFMetab
       REAL(KIND(1D0)), INTENT(IN)::NARP_EMIS_SNOW
       REAL(KIND(1D0)), INTENT(IN)::NARP_TRANS_SITE
       REAL(KIND(1D0)), INTENT(IN)::PipeCapacity
       REAL(KIND(1D0)), INTENT(IN)::PopDensNighttime
       REAL(KIND(1D0)), INTENT(IN)::PorMax_dec
       REAL(KIND(1D0)), INTENT(IN)::PorMin_dec
       REAL(KIND(1D0)), INTENT(IN)::Precip
       REAL(KIND(1D0)), INTENT(IN)::PrecipLimit
       REAL(KIND(1D0)), INTENT(IN)::PrecipLimitAlb
       REAL(KIND(1D0)), INTENT(IN)::Press_hPa
       REAL(KIND(1D0)), INTENT(IN)::qh_obs
       REAL(KIND(1D0)), INTENT(IN)::qn1_obs
       REAL(KIND(1D0)), INTENT(IN)::qs_obs
       REAL(KIND(1D0)), INTENT(IN)::qf_obs
       REAL(KIND(1D0)), INTENT(IN)::RadMeltFact
       REAL(KIND(1D0)), INTENT(IN)::RAINCOVER
       REAL(KIND(1D0)), INTENT(IN)::RainMaxRes
       REAL(KIND(1D0)), INTENT(IN)::RunoffToWater
       REAL(KIND(1D0)), INTENT(IN)::S1
       REAL(KIND(1D0)), INTENT(IN)::S2
       REAL(KIND(1D0)), INTENT(IN)::SnowAlbMax
       REAL(KIND(1D0)), INTENT(IN)::SnowAlbMin
       REAL(KIND(1D0)), INTENT(IN)::SnowDensMax
       REAL(KIND(1D0)), INTENT(IN)::SnowDensMin
       REAL(KIND(1D0)), INTENT(IN)::SnowLimBldg
       REAL(KIND(1D0)), INTENT(IN)::SnowLimPaved
       REAL(KIND(1D0)), INTENT(IN)::snowFrac_obs
       REAL(KIND(1D0)), INTENT(IN)::SurfaceArea
       REAL(KIND(1D0)), INTENT(IN)::tau_a
       REAL(KIND(1D0)), INTENT(IN)::tau_f
       REAL(KIND(1D0)), INTENT(IN)::tau_r
       REAL(KIND(1D0)), INTENT(IN)::Temp_C
       REAL(KIND(1D0)), INTENT(IN)::TempMeltFact
       REAL(KIND(1D0)), INTENT(IN)::TH
       REAL(KIND(1D0)), INTENT(IN)::timezone
       REAL(KIND(1D0)), INTENT(IN)::TL
       REAL(KIND(1D0)), INTENT(IN)::TrafficUnits
       REAL(KIND(1D0)), INTENT(IN)::wu_m3
       REAL(KIND(1D0)), INTENT(IN)::xsmd
       REAL(KIND(1D0)), INTENT(IN)::Z
       REAL(KIND(1D0)), INTENT(IN)::z0m_in
       REAL(KIND(1D0)), INTENT(IN)::zdm_in
       INTEGER, DIMENSION(NVEGSURF), INTENT(IN)::LAIType
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::AH_MIN
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::AH_SLOPE_Cooling
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::AH_SLOPE_Heating
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::FcEF_v_kgkm
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::QF0_BEU
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::Qf_A
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::Qf_B
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::Qf_C
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::NumCapita
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::PopDensDaytime
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::T_CRITIC_Cooling
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::T_CRITIC_Heating
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::TrafficRate
       REAL(KIND(1D0)), DIMENSION(3), INTENT(IN)               ::Ie_a
       REAL(KIND(1D0)), DIMENSION(3), INTENT(IN)               ::Ie_m
       REAL(KIND(1D0)), DIMENSION(3), INTENT(IN)               ::MaxConductance
       REAL(KIND(1D0)), DIMENSION(7), INTENT(IN)               ::DayWat
       REAL(KIND(1D0)), DIMENSION(7), INTENT(IN)               ::DayWatPer
       REAL(KIND(1D0)), DIMENSION(nsurf + 1), INTENT(IN)         ::OHM_threshSW
       REAL(KIND(1D0)), DIMENSION(nsurf + 1), INTENT(IN)         ::OHM_threshWD
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::chAnOHM
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::cpAnOHM
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::emis
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::kkAnOHM
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SatHydraulicConduct
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::sfr
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SnowPackLimit
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SoilDepth
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SoilStoreCap
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::StateLimit
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::WetThresh
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::alpha_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::alpha_enh_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::BaseT
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::BaseTe
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::beta_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::beta_enh_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::GDDFull
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::LAIMax
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::LAIMin
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::min_res_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::resp_a
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::resp_b
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::SDDFull
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN)          ::SnowProf_24hr
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::theta_bioCO2
       REAL(KIND(1D0)), DIMENSION(4, NVEGSURF), INTENT(IN)      ::LAIPower
       REAL(KIND(1D0)), DIMENSION(nsurf + 1, 4, 3), INTENT(IN)     ::OHM_coef
       REAL(KIND(1D0)), DIMENSION(NSURF + 1, NSURF - 1), INTENT(IN) ::WaterDist
       REAL(KIND(1d0)), DIMENSION(:), INTENT(IN)               ::Ts5mindata_ir
       REAL(KIND(1D0)), DIMENSION(:, :), INTENT(IN)             ::MetForcingData_grid
       ! diurnal profile values for 24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::AHProf_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::HumActivity_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::PopProf_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::TraffProf_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::WUProfA_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::WUProfM_24hr
       ! ########################################################################################
       ! ########################################################################################
       ! inout variables
       ! OHM related:
       REAL(KIND(1d0)), INTENT(INOUT) ::qn1_av
       REAL(KIND(1d0)), INTENT(INOUT) ::dqndt
       REAL(KIND(1d0)), INTENT(INOUT) ::qn1_s_av
       REAL(KIND(1d0)), INTENT(INOUT) ::dqnsdt
       ! snow related:
       REAL(KIND(1D0)), INTENT(INOUT)                  ::SnowfallCum
       REAL(KIND(1D0)), INTENT(INOUT)                  ::SnowAlb
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::IceFrac
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::SnowWater
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::SnowDens
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::snowFrac
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::SnowPack
       ! water balance related:
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT)   ::soilstore_id
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT)   ::state_id
       REAL(KIND(1D0)), DIMENSION(6, NSURF), INTENT(INOUT) ::StoreDrainPrm
       ! phenology related:
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT)   ::alb
       REAL(KIND(1d0)), DIMENSION(5), INTENT(INOUT)       ::GDD_id !Growing Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(INOUT)::LAI_id !LAI for each veg surface [m2 m-2]
       REAL(KIND(1d0)), INTENT(INOUT)                    :: DecidCap_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: albDecTr_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: albEveTr_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: albGrass_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: porosity_id
       ! anthropogenic heat related:
       REAL(KIND(1d0)), DIMENSION(12), INTENT(INOUT) ::HDD_id !Heating Degree Days (see SUEWS_DailyState.f95)
       ! water use related:
       REAL(KIND(1d0)), DIMENSION(9), INTENT(INOUT)  ::WUDay_id
       ! ESTM related:
       REAL(KIND(1d0)), DIMENSION(24*3600/tstep), INTENT(INOUT)    ::Tair24HR ! TODO: this can be merged as one value rather than a vector, TS 20180906
       ! ########################################################################################
       ! ########################################################################################
       ! output variables
       REAL(KIND(1D0)), DIMENSION(5), INTENT(OUT)                           ::datetimeLine
       REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutSUEWS - 5), INTENT(OUT)      ::dataOutLineSUEWS
       REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutSnow - 5), INTENT(OUT)       ::dataOutLineSnow
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutESTM - 5), INTENT(OUT)       ::dataOutLineESTM
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutRSL - 5), INTENT(OUT):: dataoutLineRSL ! Wind speed array
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutDailyState - 5), INTENT(OUT) ::DailyStateLine
       ! ########################################################################################
       ! ########################################################################################
       ! local variables
       REAL(KIND(1D0))::a1
       REAL(KIND(1D0))::a2
       REAL(KIND(1D0))::a3
       REAL(KIND(1D0))::AdditionalWater
       REAL(KIND(1D0))::avU10_ms
       REAL(KIND(1D0))::azimuth
       REAL(KIND(1D0))::chSnow_per_interval
       REAL(KIND(1D0))::dens_dry
       REAL(KIND(1d0))::deltaLAI
       REAL(KIND(1D0))::drain_per_tstep
       REAL(KIND(1D0))::Ea_hPa
       REAL(KIND(1D0))::E_mod
       REAL(KIND(1D0))::es_hPa
       REAL(KIND(1D0))::ev
       REAL(KIND(1D0))::ev_per_tstep
       REAL(KIND(1D0))::ext_wu
       REAL(KIND(1D0))::Fc
       REAL(KIND(1D0))::Fc_anthro
       REAL(KIND(1D0))::Fc_biogen
       REAL(KIND(1D0))::Fc_build
       REAL(KIND(1D0))::fcld
       REAL(KIND(1D0))::Fc_metab
       REAL(KIND(1D0))::Fc_photo
       REAL(KIND(1D0))::Fc_point
       REAL(KIND(1D0))::Fc_respi
       REAL(KIND(1D0))::Fc_traff
       REAL(KIND(1D0))::fwh
       REAL(KIND(1D0))::gfunc
       REAL(KIND(1D0))::gsc
       REAL(KIND(1D0))::H_mod
       REAL(KIND(1D0))::int_wu
       REAL(KIND(1D0))::kclear
       REAL(KIND(1D0))::kup
       REAL(KIND(1D0))::ldown
       REAL(KIND(1D0))::lup
       REAL(KIND(1D0))::L_mod
       REAL(KIND(1D0))::mwh
       REAL(KIND(1D0))::mwstore
       REAL(KIND(1D0))::NWstate_per_tstep
       REAL(KIND(1D0))::planF
       REAL(KIND(1D0))::p_mm
       REAL(KIND(1D0))::zL
       REAL(KIND(1D0))::q2_gkg
       REAL(KIND(1D0))::qeOut
       REAL(KIND(1D0))::qe_per_tstep
       REAL(KIND(1D0))::qf
       REAL(KIND(1D0))::QF_SAHP
       REAL(KIND(1D0))::qh
       REAL(KIND(1D0))::qh_residual
       REAL(KIND(1D0))::qh_resist
       REAL(KIND(1D0))::Qm
       REAL(KIND(1D0))::QmFreez
       REAL(KIND(1D0))::QmRain
       REAL(KIND(1D0))::qn1
       REAL(KIND(1D0))::qn1_S
       REAL(KIND(1D0))::qn1_snowfree
       REAL(KIND(1D0))::qs
       REAL(KIND(1D0))::RA
       REAL(KIND(1D0))::ResistSurf
       REAL(KIND(1D0))::RH2
       ! REAL(KIND(1D0))::rss
       REAL(KIND(1d0))::runoffAGveg
       REAL(KIND(1d0))::runoffAGimpervious
       REAL(KIND(1D0))::runoff_per_tstep
       REAL(KIND(1D0))::runoffPipes
       REAL(KIND(1D0))::runoffPipes_m3
       REAL(KIND(1D0))::runoffSoil_per_tstep
       REAL(KIND(1D0))::runoffwaterbody
       REAL(KIND(1D0))::runoffWaterBody_m3
       REAL(KIND(1D0))::smd
       REAL(KIND(1D0))::SoilState
       REAL(KIND(1D0))::state_per_tstep
       REAL(KIND(1D0))::surf_chang_per_tstep
       REAL(KIND(1D0))::swe
       REAL(KIND(1D0))::t2_C
       REAL(KIND(1D0))::tskin_C
       REAL(KIND(1D0))::TempVeg
       REAL(KIND(1D0))::tot_chang_per_tstep
       REAL(KIND(1D0))::TStar
       REAL(KIND(1D0))::tsurf
       REAL(KIND(1D0))::UStar
       REAL(KIND(1D0))::VPD_Pa
       REAL(KIND(1D0))::WUAreaDecTr_m2
       REAL(KIND(1D0))::WUAreaEveTr_m2
       REAL(KIND(1D0))::WUAreaGrass_m2
       REAL(KIND(1D0))::WUAreaTotal_m2
       REAL(KIND(1D0))::wu_DecTr
       REAL(KIND(1D0))::wu_EveTr
       REAL(KIND(1D0))::wu_Grass
       REAL(KIND(1D0))::z0m
       REAL(KIND(1D0))::zdm
       REAL(KIND(1D0))::ZENITH_deg
       REAL(KIND(1D0))::Zh
       REAL(KIND(1d0)), DIMENSION(nvegsurf):: LAI_id_prev !LAI for each veg surface [m2 m-2]
       REAL(KIND(1D0)), DIMENSION(2)::SnowRemoval
       REAL(KIND(1D0)), DIMENSION(NSURF)::chang
       REAL(KIND(1D0)), DIMENSION(NSURF)::changSnow
       REAL(KIND(1D0)), DIMENSION(NSURF)::evap
       REAL(KIND(1D0)), DIMENSION(NSURF)::ev_snow
       REAL(KIND(1D0)), DIMENSION(NSURF)::FreezMelt
       REAL(KIND(1d0)), DIMENSION(nsurf)::kup_ind_snow
       REAL(KIND(1D0)), DIMENSION(NSURF)::mw_ind
       REAL(KIND(1D0)), DIMENSION(NSURF)::Qm_freezState
       REAL(KIND(1D0)), DIMENSION(NSURF)::Qm_melt
       REAL(KIND(1D0)), DIMENSION(NSURF)::Qm_rain
       REAL(KIND(1D0)), DIMENSION(NSURF)::qn1_ind_snow
       REAL(KIND(1D0)), DIMENSION(NSURF)::rainOnSnow
       REAL(KIND(1D0)), DIMENSION(NSURF)::rss_nsurf
       REAL(KIND(1D0)), DIMENSION(NSURF)::runoff
       REAL(KIND(1D0)), DIMENSION(NSURF)::runoffSnow
       REAL(KIND(1D0)), DIMENSION(NSURF)::runoffSoil
       REAL(KIND(1D0)), DIMENSION(NSURF)::smd_nsurf
       REAL(KIND(1D0)), DIMENSION(NSURF)::SnowToSurf
       REAL(KIND(1D0)), DIMENSION(NSURF)::snowDepth
       REAL(KIND(1d0)), DIMENSION(nsurf)::Tsurf_ind_snow
       INTEGER, DIMENSION(NSURF)::snowCalcSwitch
       INTEGER, DIMENSION(3)    ::dayofWeek_id
       INTEGER::DLS
       REAL(KIND(1D0))::avcp
       REAL(KIND(1D0))::avdens
       REAL(KIND(1D0))::dq
       REAL(KIND(1D0))::lv_J_kg
       REAL(KIND(1D0))::lvS_J_kg
       REAL(KIND(1D0))::psyc_hPa
       REAL(KIND(1D0))::qe
       REAL(KIND(1D0))::RAsnow
       REAL(KIND(1D0))::rb
       REAL(KIND(1D0))::runoff_per_interval
       REAL(KIND(1D0))::s_hPa
       REAL(KIND(1D0))::sIce_hpa
       REAL(KIND(1D0))::SoilMoistCap
       REAL(KIND(1D0))::veg_fr
       REAL(KIND(1D0))::VegPhenLumps
       REAL(KIND(1D0))::VPd_hpa
       REAL(KIND(1D0))::vsmd
       REAL(KIND(1D0))::ZZD
       REAL(KIND(1D0)), DIMENSION(NSURF)::deltaQi
       REAL(KIND(1D0)), DIMENSION(NSURF)::drain
       REAL(KIND(1D0)), DIMENSION(NSURF)::FreezState
       REAL(KIND(1D0)), DIMENSION(NSURF)::FreezStateVol
       REAL(KIND(1D0)), DIMENSION(NSURF)::soilstoreOld
       REAL(KIND(1D0)), DIMENSION(NSURF)::stateOld
       REAL(KIND(1D0)), DIMENSION(NSURF)::tsurf_ind
       ! TODO: TS 25 Oct 2017
       ! the `add-*` variables are not used currently as grid-to-grid connection is NOT set up.
       ! set these variables as zero.
       REAL(KIND(1D0))::addImpervious = 0
       REAL(KIND(1D0))::addPipes = 0
       REAL(KIND(1D0))::addVeg = 0
       REAL(KIND(1D0))::addWaterBody = 0
       REAL(KIND(1D0)), DIMENSION(NSURF)::AddWater = 0
       REAL(KIND(1D0)), DIMENSION(NSURF)::AddWaterRunoff = 0
       ! values that are derived from tstep
       INTEGER::nsh ! number of timesteps per hour
       REAL(KIND(1D0))::nsh_real ! nsh in type real
       REAL(KIND(1D0))::tstep_real ! tstep in type real
       REAL(KIND(1D0))::dectime
       ! values that are derived from sfr (surface fractions)
       REAL(KIND(1D0))::VegFraction
       REAL(KIND(1D0))::ImpervFraction
       REAL(KIND(1D0))::PervFraction
       REAL(KIND(1D0))::NonWaterFraction
       ! Related to RSL wind profiles
       INTEGER, PARAMETER :: nz = 30   ! number of levels 10 levels in canopy plus 20 (3 x Zh) above the canopy
       REAL(KIND(1d0)), DIMENSION(nz):: zarray ! Height array
       ! ########################################################################################
       ! calculate dectime
       CALL suews_cal_dectime( &
          id, it, imin, isec, & ! input
          dectime) ! output
       ! calculate tstep related VARIABLES
       CALL suews_cal_tstep( &
          tstep, & ! input
          nsh, nsh_real, tstep_real) ! output
       ! calculate surface fraction related VARIABLES
       CALL suews_cal_surf( &
          sfr, & !input
          vegfraction, impervfraction, pervfraction, nonwaterfraction) ! output
       ! calculate dayofweek information
       CALL suews_cal_weekday( &
          iy, id, lat, & !input
          dayofweek_id) !output
       ! calculate dayofweek information
       CALL suews_cal_dls( &
          id, startdls, enddls, & !input
          dls) !output
       !==============main calculation start=======================
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_RoughnessParameters...'
       IF (diagnose == 1) print *, 'z0m_in =', z0m_in
       CALL suews_cal_roughnessparameters( &
          roughlenmommethod, sfr, &!input
          bldgh, evetreeh, dectreeh, &
          porosity_id, faibldg, faievetree, faidectree, &
          z0m_in, zdm_in, z, &
          planf, &!output
          zh, z0m, zdm, zzd)
       ! Calculate sun position
       IF (diagnose == 1) WRITE (*, *) 'Calling NARP_cal_SunPosition...'
       CALL narp_cal_sunposition( &
          REAL(iy, KIND(1d0)), &!input:
          dectime - tstep/2, &! sun position at middle of timestep before
          timezone, lat, lng, alt, &
          azimuth, zenith_deg)!output:
       !Call the SUEWS_cal_DailyState routine to get surface characteristics ready
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_DailyState...'
       CALL suews_cal_dailystate( &
          iy, id, it, imin, isec, tstep, tstep_prev, dt_since_start, dayofweek_id, &!input
          waterusemethod, snowuse, ie_start, ie_end, &
          laicalcyes, laitype, &
          nsh_real, avkdn, temp_c, precip, basethdd, &
          lat, faut, lai_obs, tau_a, tau_f, tau_r, &
          snowdensmax, snowdensmin, snowalbmax, snowalbmin, &
          albmax_dectr, albmax_evetr, albmax_grass, &
          albmin_dectr, albmin_evetr, albmin_grass, &
          capmax_dec, capmin_dec, pormax_dec, pormin_dec, &
          ie_a, ie_m, daywatper, daywat, snowpack, &
          baset, basete, gddfull, sddfull, laimin, laimax, laipower, &
          snowalb, snowdens, &!inout
          gdd_id, hdd_id, lai_id, lai_id_prev, wuday_id, &
          decidcap_id, albdectr_id, albevetr_id, albgrass_id, porosity_id, &
          deltalai)!output
       !Calculation of density and other water related parameters
       IF (diagnose == 1) WRITE (*, *) 'Calling LUMPS_cal_AtmMoist...'
       CALL lumps_cal_atmmoist( &
          temp_c, press_hpa, avrh, dectime, &! input:
          lv_j_kg, lvs_j_kg, &! output:
          es_hpa, ea_hpa, vpd_hpa, vpd_pa, dq, dens_dry, avcp, avdens)
       !======== Calculate soil moisture =========
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_update_SoilMoist...'
       CALL suews_update_soilmoist( &
          nonwaterfraction, &!input
          soilstorecap, sfr, soilstore_id, &
          soilmoistcap, soilstate, &!output
          vsmd, smd)
       ! ===================NET ALLWAVE RADIATION================================
       CALL suews_cal_qn( &
          netradiationmethod, snowuse, &!input
          diagnose, snowfrac_obs, ldown_obs, fcld_obs, &
          dectime, zenith_deg, avkdn, temp_c, avrh, ea_hpa, qn1_obs, &
          snowalb, diagqn, &
          narp_trans_site, narp_emis_snow, icefrac, sfr, emis, &
          alb, albdectr_id, decidcap_id, albevetr_id, albgrass_id, storedrainprm, snowfrac, &!inout
          ldown, fcld, &!output
          qn1, qn1_snowfree, qn1_s, kclear, kup, lup, tsurf, &
          qn1_ind_snow, kup_ind_snow, tsurf_ind_snow, tsurf_ind)
       ! ===================ANTHROPOGENIC HEAT AND CO2 FLUX======================
       CALL suews_cal_anthropogenicemission( &
          ah_min, ahprof_24hr, ah_slope_cooling, ah_slope_heating, co2pointsource, &! input:
          dayofweek_id, diagnose, dls, ef_umolco2perj, emissionsmethod, enef_v_jkm, &
          fcef_v_kgkm, frfossilfuel_heat, frfossilfuel_nonheat, hdd_id, humactivity_24hr, &
          id, imin, it, maxfcmetab, maxqfmetab, minfcmetab, minqfmetab, nsh, numcapita, &
          popdensdaytime, popdensnighttime, popprof_24hr, qf, qf0_beu, qf_a, qf_b, qf_c, &
          qf_obs, qf_sahp, sfr, snowfrac, surfacearea, t_critic_cooling, t_critic_heating, &
          temp_c, trafficrate, trafficunits, traffprof_24hr, &
          fc_anthro, fc_build, fc_metab, fc_point, fc_traff)! output:
       ! =================STORAGE HEAT FLUX=======================================
       CALL suews_cal_qs( &
          storageheatmethod, qs_obs, ohmincqf, gridiv, &!input
          id, tstep, dt_since_start, diagnose, sfr, &
          ohm_coef, ohm_threshsw, ohm_threshwd, &
          soilstore_id, soilstorecap, state_id, nsh, snowuse, diagqs, &
          hdd_id, metforcingdata_grid, ts5mindata_ir, qf, qn1, &
          avkdn, avu1, temp_c, zenith_deg, avrh, press_hpa, ldown, &
          bldgh, alb, emis, cpanohm, kkanohm, chanohm, emissionsmethod, &
          tair24hr, qn1_av, dqndt, qn1_s_av, dqnsdt, &!inout
          storedrainprm, &
          qn1_s, snowfrac, dataoutlineestm, qs, &!output
          deltaqi, a1, a2, a3)
       !==================Energy related to snow melting/freezing processes=======
       IF (diagnose == 1) WRITE (*, *) 'Calling MeltHeat'
       CALL snow_cal_meltheat( &
          snowuse, &!input
          lvs_j_kg, lv_j_kg, tstep_real, radmeltfact, tempmeltfact, snowalbmax, &
          snowdensmin, temp_c, precip, preciplimit, preciplimitalb, &
          nsh_real, sfr, tsurf_ind, tsurf_ind_snow, state_id, qn1_ind_snow, &
          kup_ind_snow, snowwater, deltaqi, &
          snowpack, snowfrac, snowalb, snowdens, snowfallcum, &!inout
          mwh, fwh, qm, qmfreez, qmrain, &! output
          veg_fr, snowcalcswitch, qm_melt, qm_freezstate, qm_rain, freezmelt, &
          freezstate, freezstatevol, rainonsnow, snowdepth, mw_ind, &
          dataoutlinesnow)!output
       !==========================Turbulent Fluxes================================
       IF (diagnose == 1) WRITE (*, *) 'Calling LUMPS_cal_QHQE...'
       !Calculate QH and QE from LUMPS
       CALL lumps_cal_qhqe( &
          veg_type, & !input
          snowuse, qn1, qf, qs, qm, temp_c, veg_fr, avcp, press_hpa, lv_j_kg, &
          tstep_real, drainrt, nsh_real, &
          precip, rainmaxres, raincover, sfr, lai_id, laimax, laimin, &
          h_mod, & !output
          e_mod, psyc_hpa, s_hpa, sice_hpa, tempveg, vegphenlumps)
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_WaterUse...'
       !Gives the external and internal water uses per timestep
       CALL suews_cal_wateruse( &
          nsh_real, & ! input:
          wu_m3, surfacearea, sfr, &
          irrfracconif, irrfracdecid, irrfracgrass, &
          dayofweek_id, wuprofa_24hr, wuprofm_24hr, &
          internalwateruse_h, hdd_id, wuday_id, &
          waterusemethod, nsh, it, imin, dls, &
          wuareaevetr_m2, wuareadectr_m2, & ! output:
          wuareagrass_m2, wuareatotal_m2, &
          wu_evetr, wu_dectr, wu_grass, int_wu, ext_wu)
       !===============Resistance Calculations=======================
       CALL suews_cal_resistance( &
          stabilitymethod, &!input:
          diagnose, aerodynamicresistancemethod, roughlenheatmethod, snowuse, &
          id, it, gsmodel, smdmethod, &
          qh_obs, avdens, avcp, h_mod, qn1, dectime, zzd, z0m, zdm, &
          avu1, temp_c, vegfraction, avkdn, &
          kmax, &
          g1, g2, g3, g4, &
          g5, g6, s1, s2, &
          th, tl, &
          dq, xsmd, vsmd, maxconductance, laimax, lai_id, snowfrac, sfr, &
          ustar, tstar, l_mod, &!output
          zl, gsc, resistsurf, ra, rasnow, rb)
       !============= calculate water balance =============
       CALL suews_cal_water( &
          diagnose, &!input
          snowuse, nonwaterfraction, addpipes, addimpervious, addveg, addwaterbody, &
          state_id, soilstore_id, sfr, storedrainprm, waterdist, nsh_real, &
          drain_per_tstep, &  !output
          drain, addwaterrunoff, &
          additionalwater, runoffpipes, runoff_per_interval, &
          addwater, stateold, soilstoreold)
       !============= calculate water balance end =============
       !======== Evaporation and surface state_id ========
       CALL suews_cal_qe( &
          diagnose, &!input
          tstep, imin, it, evapmethod, snowcalcswitch, dayofweek_id, crwmin, crwmax, &
          dectime, lvs_j_kg, lv_j_kg, avdens, avrh, press_hpa, temp_c, &
          rasnow, psyc_hpa, avcp, sice_hpa, &
          pervfraction, vegfraction, addimpervious, qn1_snowfree, qf, qs, vpd_hpa, s_hpa, &
          resistsurf, ra, rb, snowdensmin, precip, pipecapacity, runofftowater, &
          nonwaterfraction, wu_evetr, wu_dectr, wu_grass, addveg, addwaterbody, snowlimpaved, snowlimbldg, &
          surfacearea, flowchange, drain, wetthresh, stateold, mw_ind, soilstorecap, rainonsnow, &
          freezmelt, freezstate, freezstatevol, qm_melt, qm_rain, tsurf_ind, sfr, &
          statelimit, addwater, addwaterrunoff, storedrainprm, snowpacklimit, snowprof_24hr, &
          runoff_per_interval, state_id, & !inout:
          soilstore_id, snowpack, snowfrac, snowwater, icefrac, snowdens, &
          runoffsnow, runoff, runoffsoil, chang, changsnow, &! output:
          snowdepth, snowtosurf, ev_snow, snowremoval, &
          evap, rss_nsurf, p_mm, qe, state_per_tstep, nwstate_per_tstep, qeout, &
          swe, ev, chsnow_per_interval, ev_per_tstep, qe_per_tstep, runoff_per_tstep, &
          surf_chang_per_tstep, runoffpipes, mwstore, runoffwaterbody, &
          runoffagveg, runoffagimpervious, runoffwaterbody_m3, runoffpipes_m3)
       !======== Evaporation and surface state_id end========
       !============ Sensible heat flux ===============
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_QH...'
       CALL suews_cal_qh( &
          1, &
          qn1, qf, qmrain, qeout, qs, qmfreez, qm, avdens, avcp, tsurf, temp_c, ra, &
          qh, qh_residual, qh_resist)!output
       !============ Sensible heat flux end===============
       !=== Horizontal movement between soil stores ===
       ! Now water is allowed to move horizontally between the soil stores
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_HorizontalSoilWater...'
       CALL suews_cal_horizontalsoilwater( &
          sfr, &! input: ! surface fractions
          soilstorecap, &!Capacity of soil store for each surface [mm]
          soildepth, &!Depth of sub-surface soil store for each surface [mm]
          sathydraulicconduct, &!Saturated hydraulic conductivity for each soil subsurface [mm s-1]
          surfacearea, &!Surface area of the study area [m2]
          nonwaterfraction, &! sum of surface cover fractions for all except water surfaces
          tstep_real, & !tstep cast as a real for use in calculations
          soilstore_id, &! inout:!Soil moisture of each surface type [mm]
          runoffsoil, &!Soil runoff from each soil sub-surface [mm]
          runoffsoil_per_tstep &!  output:!Runoff to deep soil per timestep [mm] (for whole surface, excluding water body)
          )
       !========== Calculate soil moisture ============
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_SoilState...'
       CALL suews_cal_soilstate( &
          smdmethod, xsmd, nonwaterfraction, soilmoistcap, &!input
          soilstorecap, surf_chang_per_tstep, &
          soilstore_id, soilstoreold, sfr, &
          smd, smd_nsurf, tot_chang_per_tstep, soilstate)!output
       !============ surface-level diagonostics ===============
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_Diagnostics...'
       CALL suews_cal_diagnostics( &
          dectime, &!input
          avu1, temp_c, avrh, press_hpa, &
          qh, qe, &
          vegfraction, z, z0m, zdm, ra, avdens, avcp, lv_j_kg, tstep_real, &
          roughlenheatmethod, stabilitymethod, &
          avu10_ms, t2_c, q2_gkg, tskin_c, rh2)!output
       IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_cal_Diagnostics...'
       CALL windprofile( &
          ustar, &!input
          l_mod, sfr, zh, planf, &
          stabilitymethod, &
          zarray, dataoutlinersl)!output
       !============ surface-level diagonostics end ===============
       ! ============ BIOGENIC CO2 FLUX =======================
       CALL suews_cal_biogenco2( &
          alpha_bioco2, alpha_enh_bioco2, avkdn, avrh, beta_bioco2, beta_enh_bioco2, bsoilsurf, &! input:
          conifsurf, decidsurf, dectime, diagnose, emissionsmethod, fc_anthro, g1, g2, g3, g4, &
          g5, g6, gfunc, grasssurf, gsmodel, id, it, ivconif, ivdecid, ivgrass, kmax, lai_id, laimin, &
          laimax, maxconductance, min_res_bioco2, nsurf, nvegsurf, press_hpa, resp_a, &
          resp_b, s1, s2, sfr, smdmethod, snowfrac, t2_c, temp_c, theta_bioco2, th, tl, vsmd, xsmd, &
          fc, fc_biogen, fc_photo, fc_respi)! output:
       !==============main calculation end=======================
       !==============translation of  output variables into output array===========
       CALL suews_update_outputline( &
          additionalwater, alb, avkdn, avu10_ms, azimuth, &!input
          chsnow_per_interval, dectime, &
          drain_per_tstep, e_mod, ev_per_tstep, ext_wu, fc, fc_build, fcld, &
          fc_metab, fc_photo, fc_respi, fc_point, fc_traff, flowchange, &
          h_mod, id, imin, int_wu, it, iy, &
          kup, lai_id, ldown, l_mod, lup, mwh, &
          mwstore, &
          nsh_real, nwstate_per_tstep, precip, q2_gkg, &
          qeout, qf, qh, qh_resist, qm, qmfreez, &
          qmrain, qn1, qn1_s, qn1_snowfree, qs, ra, &
          resistsurf, rh2, runoffagimpervious, runoffagveg, &
          runoff_per_tstep, runoffpipes, runoffsoil_per_tstep, &
          runoffwaterbody, sfr, smd, smd_nsurf, snowalb, snowremoval, &
          state_id, state_per_tstep, surf_chang_per_tstep, swe, t2_c, tskin_c, &
          tot_chang_per_tstep, tsurf, ustar, wu_dectr, &
          wu_evetr, wu_grass, z0m, zdm, zenith_deg, &
          datetimeline, dataoutlinesuews)!output
       ! model state_id:
       ! daily state_id:
       CALL update_dailystate( &
          it, imin, nsh_real, &!input
          gdd_id, hdd_id, lai_id, &
          decidcap_id, &
          albdectr_id, &
          albevetr_id, &
          albgrass_id, &
          porosity_id, &
          wuday_id, &
          deltalai, vegphenlumps, &
          snowalb, snowdens, &
          a1, a2, a3, &
          dailystateline)!out
       !==============translation end ================
References allocatearray::bsoilsurf, allocatearray::conifsurf, allocatearray::decidsurf, allocatearray::grasssurf, allocatearray::ivconif, allocatearray::ivdecid, allocatearray::ivgrass, atmmoiststab_module::lumps_cal_atmmoist(), lumps_cal_qhqe(), narp_module::narp_cal_sunposition(), allocatearray::nsurf, allocatearray::nvegsurf, snow_module::snow_cal_meltheat(), suews_cal_anthropogenicemission(), suews_cal_biogenco2(), suews_cal_dectime(), suews_cal_diagnostics(), suews_cal_dls(), waterdist_module::suews_cal_horizontalsoilwater(), suews_cal_qe(), suews_cal_qh(), suews_cal_qn(), suews_cal_qs(), suews_cal_resistance(), suews_cal_roughnessparameters(), waterdist_module::suews_cal_soilstate(), suews_cal_surf(), suews_cal_tstep(), suews_cal_water(), waterdist_module::suews_cal_wateruse(), suews_cal_weekday(), suews_update_outputline(), waterdist_module::suews_update_soilmoist(), and windprofile().
Referenced by suews_cal_multitsteps(), suews_calculations(), and sumin_module::sumin().
suews_cal_multitsteps()
subroutine suews_driver::suews_cal_multitsteps (real(kind(1d0)), dimension(len_sim, 24), intent(in) MetForcingBlock, integer, intent(in) len_sim, integer, intent(in) AerodynamicResistanceMethod, real(kind(1d0)), dimension(2), intent(in) AH_MIN, real(kind(1d0)), dimension(0:23, 2), intent(in) AHProf_24hr, real(kind(1d0)), dimension(2), intent(in) AH_SLOPE_Cooling, real(kind(1d0)), dimension(2), intent(in) AH_SLOPE_Heating, real(kind(1d0)), dimension(nsurf), intent(inout) alb, real(kind(1d0)), intent(in) AlbMax_DecTr, real(kind(1d0)), intent(in) AlbMax_EveTr, real(kind(1d0)), intent(in) AlbMax_Grass, real(kind(1d0)), intent(in) AlbMin_DecTr, real(kind(1d0)), intent(in) AlbMin_EveTr, real(kind(1d0)), intent(in) AlbMin_Grass, real(kind(1d0)), dimension(nvegsurf), intent(in) alpha_bioCO2, real(kind(1d0)), dimension(nvegsurf), intent(in) alpha_enh_bioCO2, real(kind(1d0)), intent(in) alt, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseT, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseTe, real(kind(1d0)), intent(in) BaseTHDD, real(kind(1d0)), dimension(nvegsurf), intent(in) beta_bioCO2, real(kind(1d0)), dimension(nvegsurf), intent(in) beta_enh_bioCO2, real(kind(1d0)), intent(in) bldgH, real(kind(1d0)), intent(in) CapMax_dec, real(kind(1d0)), intent(in) CapMin_dec, real(kind(1d0)), dimension(nsurf), intent(in) chAnOHM, real(kind(1d0)), intent(in) CO2PointSource, real(kind(1d0)), dimension(nsurf), intent(in) cpAnOHM, real(kind(1d0)), intent(in) CRWmax, real(kind(1d0)), intent(in) CRWmin, real(kind(1d0)), dimension(7), intent(in) DayWat, real(kind(1d0)), dimension(7), intent(in) DayWatPer, real(kind(1d0)), intent(in) DecTreeH, integer, intent(in) Diagnose, integer, intent(in) DiagQN, integer, intent(in) DiagQS, real(kind(1d0)), intent(in) DRAINRT, integer, intent(in) dt_since_start, real(kind(1d0)), intent(inout) dqndt, real(kind(1d0)), intent(inout) qn1_av, real(kind(1d0)), intent(inout) dqnsdt, real(kind(1d0)), intent(inout) qn1_s_av, real(kind(1d0)), intent(in) EF_umolCO2perJ, real(kind(1d0)), dimension(nsurf), intent(in) emis, integer, intent(in) EmissionsMethod, real(kind(1d0)), intent(in) EnEF_v_Jkm, integer, intent(in) endDLS, real(kind(1d0)), intent(in) EveTreeH, real(kind(1d0)), intent(in) FAIBldg, real(kind(1d0)), intent(in) FAIDecTree, real(kind(1d0)), intent(in) FAIEveTree, real(kind(1d0)), intent(in) Faut, real(kind(1d0)), dimension(2), intent(in) FcEF_v_kgkm, real(kind(1d0)), intent(in) FlowChange, real(kind(1d0)), intent(in) FrFossilFuel_Heat, real(kind(1d0)), intent(in) FrFossilFuel_NonHeat, real(kind(1d0)), intent(in) G1, real(kind(1d0)), intent(in) G2, real(kind(1d0)), intent(in) G3, real(kind(1d0)), intent(in) G4, real(kind(1d0)), intent(in) G5, real(kind(1d0)), intent(in) G6, real(kind(1d0)), dimension(5), intent(inout) GDD_id, real(kind(1d0)), dimension(nvegsurf), intent(in) GDDFull, integer, intent(in) Gridiv, integer, intent(in) gsModel, real(kind(1d0)), dimension(12), intent(inout) HDD_id, real(kind(1d0)), dimension(0:23, 2), intent(in) HumActivity_24hr, real(kind(1d0)), dimension(nsurf), intent(inout) IceFrac, real(kind(1d0)), dimension(3), intent(in) Ie_a, integer, intent(in) Ie_end, real(kind(1d0)), dimension(3), intent(in) Ie_m, integer, intent(in) Ie_start, real(kind(1d0)), intent(in) InternalWaterUse_h, real(kind(1d0)), intent(in) IrrFracConif, real(kind(1d0)), intent(in) IrrFracDecid, real(kind(1d0)), intent(in) IrrFracGrass, integer, intent(in) EvapMethod, real(kind(1d0)), dimension(nsurf), intent(in) kkAnOHM, real(kind(1d0)), intent(in) Kmax, real(kind(1d0)), dimension(nvegsurf), intent(inout) LAI_id, integer, intent(in) LAICalcYes, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMax, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMin, real(kind(1d0)), dimension(4, nvegsurf), intent(in) LAIPower, integer, dimension(nvegsurf), intent(in) LAIType, real(kind(1d0)), intent(in) lat, real(kind(1d0)), intent(in) lng, real(kind(1d0)), dimension(3), intent(in) MaxConductance, real(kind(1d0)), intent(in) MaxFCMetab, real(kind(1d0)), intent(in) MaxQFMetab, real(kind(1d0)), dimension(nsurf), intent(inout) SnowWater, real(kind(1d0)), intent(in) MinFCMetab, real(kind(1d0)), intent(in) MinQFMetab, real(kind(1d0)), dimension(nvegsurf), intent(in) min_res_bioCO2, real(kind(1d0)), intent(in) NARP_EMIS_SNOW, real(kind(1d0)), intent(in) NARP_TRANS_SITE, integer, intent(in) NetRadiationMethod, real(kind(1d0)), dimension(2), intent(in) NumCapita, real(kind(1d0)), dimension(nsurf + 1, 4, 3), intent(in) OHM_coef, integer, intent(in) OHMIncQF, real(kind(1d0)), dimension(nsurf + 1), intent(in) OHM_threshSW, real(kind(1d0)), dimension(nsurf + 1), intent(in) OHM_threshWD, real(kind(1d0)), intent(in) PipeCapacity, real(kind(1d0)), dimension(2), intent(in) PopDensDaytime, real(kind(1d0)), intent(in) PopDensNighttime, real(kind(1d0)), dimension(0:23, 2), intent(in) PopProf_24hr, real(kind(1d0)), intent(in) PorMax_dec, real(kind(1d0)), intent(in) PorMin_dec, real(kind(1d0)), intent(in) PrecipLimit, real(kind(1d0)), intent(in) PrecipLimitAlb, real(kind(1d0)), dimension(2), intent(in) QF0_BEU, real(kind(1d0)), dimension(2), intent(in) Qf_A, real(kind(1d0)), dimension(2), intent(in) Qf_B, real(kind(1d0)), dimension(2), intent(in) Qf_C, real(kind(1d0)), intent(in) RadMeltFact, real(kind(1d0)), intent(in) RAINCOVER, real(kind(1d0)), intent(in) RainMaxRes, real(kind(1d0)), dimension(nvegsurf), intent(in) resp_a, real(kind(1d0)), dimension(nvegsurf), intent(in) resp_b, integer, intent(in) RoughLenHeatMethod, integer, intent(in) RoughLenMomMethod, real(kind(1d0)), intent(in) RunoffToWater, real(kind(1d0)), intent(in) S1, real(kind(1d0)), intent(in) S2, real(kind(1d0)), dimension(nsurf), intent(in) SatHydraulicConduct, real(kind(1d0)), dimension(nvegsurf), intent(in) SDDFull, real(kind(1d0)), dimension(nsurf), intent(in) sfr, integer, intent(in) SMDMethod, real(kind(1d0)), intent(inout) SnowAlb, real(kind(1d0)), intent(in) SnowAlbMax, real(kind(1d0)), intent(in) SnowAlbMin, real(kind(1d0)), dimension(nsurf), intent(in) SnowPackLimit, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens, real(kind(1d0)), intent(in) SnowDensMax, real(kind(1d0)), intent(in) SnowDensMin, real(kind(1d0)), intent(inout) SnowfallCum, real(kind(1d0)), dimension(nsurf), intent(inout) snowFrac, real(kind(1d0)), intent(in) SnowLimBldg, real(kind(1d0)), intent(in) SnowLimPaved, real(kind(1d0)), dimension(nsurf), intent(inout) SnowPack, real(kind(1d0)), dimension(0:23, 2), intent(in) SnowProf_24hr, integer, intent(in) snowUse, real(kind(1d0)), dimension(nsurf), intent(in) SoilDepth, real(kind(1d0)), dimension(nsurf), intent(inout) soilstore_id, real(kind(1d0)), dimension(nsurf), intent(in) SoilStoreCap, integer, intent(in) StabilityMethod, integer, intent(in) startDLS, real(kind(1d0)), dimension(nsurf), intent(inout) state_id, real(kind(1d0)), dimension(nsurf), intent(in) StateLimit, integer, intent(in) StorageHeatMethod, real(kind(1d0)), dimension(6, nsurf), intent(inout) StoreDrainPrm, real(kind(1d0)), intent(in) SurfaceArea, real(kind(1d0)), dimension(24*3600/tstep), intent(inout) Tair24HR, real(kind(1d0)), intent(in) tau_a, real(kind(1d0)), intent(in) tau_f, real(kind(1d0)), intent(in) tau_r, real(kind(1d0)), dimension(2), intent(in) T_CRITIC_Cooling, real(kind(1d0)), dimension(2), intent(in) T_CRITIC_Heating, real(kind(1d0)), intent(in) TempMeltFact, real(kind(1d0)), intent(in) TH, real(kind(1d0)), dimension(nvegsurf), intent(in) theta_bioCO2, real(kind(1d0)), intent(in) timezone, real(kind(1d0)), intent(in) TL, real(kind(1d0)), dimension(2), intent(in) TrafficRate, real(kind(1d0)), intent(in) TrafficUnits, real(kind(1d0)), dimension(0:23, 2), intent(in) TraffProf_24hr, real(kind(1d0)), dimension(:), intent(in) Ts5mindata_ir, integer, intent(in) tstep, integer, intent(in) tstep_prev, integer, intent(in) veg_type, real(kind(1d0)), dimension(nsurf + 1, nsurf - 1), intent(in) WaterDist, integer, intent(in) WaterUseMethod, real(kind(1d0)), dimension(nsurf), intent(in) WetThresh, real(kind(1d0)), dimension(9), intent(inout) WUDay_id, real(kind(1d0)), intent(inout) DecidCap_id, real(kind(1d0)), intent(inout) albDecTr_id, real(kind(1d0)), intent(inout) albEveTr_id, real(kind(1d0)), intent(inout) albGrass_id, real(kind(1d0)), intent(inout) porosity_id, real(kind(1d0)), dimension(0:23, 2), intent(in) WUProfA_24hr, real(kind(1d0)), dimension(0:23, 2), intent(in) WUProfM_24hr, real(kind(1d0)), intent(in) Z, real(kind(1d0)), intent(in) z0m_in, real(kind(1d0)), intent(in) zdm_in, real(kind(1d0)), dimension(len_sim, ncolumnsdataoutsuews), intent(out) dataOutBlockSUEWS, real(kind(1d0)), dimension(len_sim, ncolumnsdataoutsnow), intent(out) dataOutBlockSnow, real(kind(1d0)), dimension(len_sim, ncolumnsdataoutestm), intent(out) dataOutBlockESTM, real(kind(1d0)), dimension(len_sim, ncolumnsdataoutrsl), intent(out) dataOutBlockRSL, real(kind(1d0)), dimension(len_sim, ncolumnsdataoutdailystate), intent(out) DailyStateBlock)
Definition at line 2529 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       ! input:
       ! met forcing block
       REAL(KIND(1D0)), DIMENSION(len_sim, 24), INTENT(IN) ::MetForcingBlock
       INTEGER, INTENT(IN) :: len_sim
       ! input variables
       INTEGER, INTENT(IN)::AerodynamicResistanceMethod
       INTEGER, INTENT(IN)::Diagnose
       INTEGER, INTENT(IN)::DiagQN
       INTEGER, INTENT(IN)::DiagQS
       INTEGER, INTENT(IN)::startDLS
       INTEGER, INTENT(IN)::endDLS
       INTEGER, INTENT(IN)::EmissionsMethod
       INTEGER, INTENT(IN)::Gridiv
       INTEGER, INTENT(IN)::gsModel
       INTEGER, INTENT(IN)::Ie_end
       INTEGER, INTENT(IN)::Ie_start
       INTEGER, INTENT(IN)::EvapMethod
       INTEGER, INTENT(IN)::LAICalcYes
       INTEGER, INTENT(IN)::NetRadiationMethod
       INTEGER, INTENT(IN)::OHMIncQF
       INTEGER, INTENT(IN)::RoughLenHeatMethod
       INTEGER, INTENT(IN)::RoughLenMomMethod
       INTEGER, INTENT(IN)::SMDMethod
       INTEGER, INTENT(IN)::snowUse
       INTEGER, INTENT(IN)::StabilityMethod
       INTEGER, INTENT(IN)::StorageHeatMethod
       INTEGER, INTENT(IN)::tstep
       INTEGER, INTENT(IN)::tstep_prev ! tstep size of the previous step
       INTEGER, INTENT(in)::dt_since_start ! time since simulation starts [s]
       INTEGER, INTENT(IN)::veg_type
       INTEGER, INTENT(IN)::WaterUseMethod
       INTEGER, DIMENSION(NVEGSURF), INTENT(IN)::LAIType
       REAL(KIND(1D0)), INTENT(IN)::AlbMax_DecTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMax_EveTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMax_Grass
       REAL(KIND(1D0)), INTENT(IN)::AlbMin_DecTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMin_EveTr
       REAL(KIND(1D0)), INTENT(IN)::AlbMin_Grass
       REAL(KIND(1D0)), INTENT(IN)::alt
       ! REAL(KIND(1D0)),INTENT(IN)::avkdn
       ! REAL(KIND(1D0)),INTENT(IN)::avRh
       ! REAL(KIND(1D0)),INTENT(IN)::avU1
       REAL(KIND(1D0)), INTENT(IN)::BaseTHDD
       REAL(KIND(1D0)), INTENT(IN)::bldgH
       REAL(KIND(1D0)), INTENT(IN)::CapMax_dec
       REAL(KIND(1D0)), INTENT(IN)::CapMin_dec
       REAL(KIND(1D0)), INTENT(IN)::CO2PointSource
       REAL(KIND(1D0)), INTENT(IN)::CRWmax
       REAL(KIND(1D0)), INTENT(IN)::CRWmin
       REAL(KIND(1D0)), INTENT(IN)::DecTreeH
       REAL(KIND(1D0)), INTENT(IN)::DRAINRT
       REAL(KIND(1D0)), INTENT(IN)::EF_umolCO2perJ
       REAL(KIND(1D0)), INTENT(IN)::EnEF_v_Jkm
       REAL(KIND(1D0)), INTENT(IN)::EveTreeH
       REAL(KIND(1D0)), INTENT(IN)::FAIBldg
       REAL(KIND(1D0)), INTENT(IN)::FAIDecTree
       REAL(KIND(1D0)), INTENT(IN)::FAIEveTree
       REAL(KIND(1D0)), INTENT(IN)::Faut
       ! REAL(KIND(1D0)),INTENT(IN)::fcld_obs
       REAL(KIND(1D0)), INTENT(IN)::FlowChange
       REAL(KIND(1D0)), INTENT(IN)::FrFossilFuel_Heat
       REAL(KIND(1D0)), INTENT(IN)::FrFossilFuel_NonHeat
       REAL(KIND(1D0)), INTENT(IN)::G1
       REAL(KIND(1D0)), INTENT(IN)::G2
       REAL(KIND(1D0)), INTENT(IN)::G3
       REAL(KIND(1D0)), INTENT(IN)::G4
       REAL(KIND(1D0)), INTENT(IN)::G5
       REAL(KIND(1D0)), INTENT(IN)::G6
       REAL(KIND(1D0)), INTENT(IN)::InternalWaterUse_h
       REAL(KIND(1D0)), INTENT(IN)::IrrFracConif
       REAL(KIND(1D0)), INTENT(IN)::IrrFracDecid
       REAL(KIND(1D0)), INTENT(IN)::IrrFracGrass
       REAL(KIND(1D0)), INTENT(IN)::Kmax
       ! REAL(KIND(1D0)),INTENT(IN)::LAI_obs
       REAL(KIND(1D0)), INTENT(IN)::lat
       ! REAL(KIND(1D0)),INTENT(IN)::ldown_obs
       REAL(KIND(1D0)), INTENT(IN)::lng
       REAL(KIND(1D0)), INTENT(IN)::MaxFCMetab
       REAL(KIND(1D0)), INTENT(IN)::MaxQFMetab
       REAL(KIND(1D0)), INTENT(IN)::MinFCMetab
       REAL(KIND(1D0)), INTENT(IN)::MinQFMetab
       REAL(KIND(1D0)), INTENT(IN)::NARP_EMIS_SNOW
       REAL(KIND(1D0)), INTENT(IN)::NARP_TRANS_SITE
       REAL(KIND(1D0)), INTENT(IN)::PipeCapacity
       REAL(KIND(1D0)), INTENT(IN)::PopDensNighttime
       REAL(KIND(1D0)), INTENT(IN)::PorMax_dec
       REAL(KIND(1D0)), INTENT(IN)::PorMin_dec
       ! REAL(KIND(1D0)),INTENT(IN)::Precip
       REAL(KIND(1D0)), INTENT(IN)::PrecipLimit
       REAL(KIND(1D0)), INTENT(IN)::PrecipLimitAlb
       ! REAL(KIND(1D0)),INTENT(IN)::Press_hPa
       ! REAL(KIND(1D0)),INTENT(IN)::qh_obs
       ! REAL(KIND(1D0)),INTENT(IN)::qn1_obs
       ! REAL(KIND(1D0)),INTENT(IN)::qs_obs
       ! REAL(KIND(1D0)),INTENT(IN)::qf_obs
       REAL(KIND(1D0)), INTENT(IN)::RadMeltFact
       REAL(KIND(1D0)), INTENT(IN)::RAINCOVER
       REAL(KIND(1D0)), INTENT(IN)::RainMaxRes
       REAL(KIND(1D0)), INTENT(IN)::RunoffToWater
       REAL(KIND(1D0)), INTENT(IN)::S1
       REAL(KIND(1D0)), INTENT(IN)::S2
       REAL(KIND(1D0)), INTENT(IN)::SnowAlbMax
       REAL(KIND(1D0)), INTENT(IN)::SnowAlbMin
       REAL(KIND(1D0)), INTENT(IN)::SnowDensMax
       REAL(KIND(1D0)), INTENT(IN)::SnowDensMin
       REAL(KIND(1D0)), INTENT(IN)::SnowLimBldg
       REAL(KIND(1D0)), INTENT(IN)::SnowLimPaved
       ! REAL(KIND(1D0)),INTENT(IN)::snowFrac_obs
       REAL(KIND(1D0)), INTENT(IN)::SurfaceArea
       REAL(KIND(1D0)), INTENT(IN)::tau_a
       REAL(KIND(1D0)), INTENT(IN)::tau_f
       REAL(KIND(1D0)), INTENT(IN)::tau_r
       ! REAL(KIND(1D0)),INTENT(IN)::Temp_C
       REAL(KIND(1D0)), INTENT(IN)::TempMeltFact
       REAL(KIND(1D0)), INTENT(IN)::TH
       REAL(KIND(1D0)), INTENT(IN)::timezone
       REAL(KIND(1D0)), INTENT(IN)::TL
       REAL(KIND(1D0)), INTENT(IN)::TrafficUnits
       ! REAL(KIND(1D0)),INTENT(IN)::xsmd
       REAL(KIND(1D0)), INTENT(IN)::Z
       REAL(KIND(1D0)), INTENT(IN)::z0m_in
       REAL(KIND(1D0)), INTENT(IN)::zdm_in
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::AH_MIN
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::AH_SLOPE_Cooling
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::AH_SLOPE_Heating
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::FcEF_v_kgkm
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::QF0_BEU
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::Qf_A
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::Qf_B
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::Qf_C
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::Numcapita
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::PopDensDaytime
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::T_CRITIC_Cooling
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::T_CRITIC_Heating
       REAL(KIND(1D0)), DIMENSION(2), INTENT(IN)               ::TrafficRate
       REAL(KIND(1D0)), DIMENSION(3), INTENT(IN)               ::Ie_a
       REAL(KIND(1D0)), DIMENSION(3), INTENT(IN)               ::Ie_m
       REAL(KIND(1D0)), DIMENSION(3), INTENT(IN)               ::MaxConductance
       REAL(KIND(1D0)), DIMENSION(7), INTENT(IN)               ::DayWat
       REAL(KIND(1D0)), DIMENSION(7), INTENT(IN)               ::DayWatPer
       REAL(KIND(1D0)), DIMENSION(nsurf + 1), INTENT(IN)         ::OHM_threshSW
       REAL(KIND(1D0)), DIMENSION(nsurf + 1), INTENT(IN)         ::OHM_threshWD
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::chAnOHM
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::cpAnOHM
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::emis
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::kkAnOHM
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SatHydraulicConduct
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::sfr
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SnowPackLimit
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SoilDepth
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::SoilStoreCap
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::StateLimit
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)           ::WetThresh
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::alpha_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::alpha_enh_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::BaseT
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::BaseTe
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::beta_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::beta_enh_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::GDDFull
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::LAIMax
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::LAIMin
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::min_res_bioCO2
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::resp_a
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::resp_b
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::SDDFull
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN)          ::SnowProf_24hr
       REAL(KIND(1D0)), DIMENSION(NVEGSURF), INTENT(IN)        ::theta_bioCO2
       REAL(KIND(1D0)), DIMENSION(4, NVEGSURF), INTENT(IN)      ::LAIPower
       REAL(KIND(1D0)), DIMENSION(nsurf + 1, 4, 3), INTENT(IN)     ::OHM_coef
       REAL(KIND(1D0)), DIMENSION(NSURF + 1, NSURF - 1), INTENT(IN) ::WaterDist
       REAL(KIND(1d0)), DIMENSION(:), INTENT(IN)               ::Ts5mindata_ir
       ! diurnal profile values for 24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::AHProf_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::HumActivity_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::PopProf_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::TraffProf_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::WUProfA_24hr
       REAL(KIND(1D0)), DIMENSION(0:23, 2), INTENT(IN) ::WUProfM_24hr
       ! ########################################################################################
       ! ########################################################################################
       ! inout variables
       ! OHM related:
       REAL(KIND(1d0)), INTENT(INOUT) ::qn1_av
       REAL(KIND(1d0)), INTENT(INOUT) ::dqndt
       REAL(KIND(1d0)), INTENT(INOUT) ::qn1_s_av
       REAL(KIND(1d0)), INTENT(INOUT) ::dqnsdt
       ! snow related:
       REAL(KIND(1D0)), INTENT(INOUT)                  ::SnowfallCum
       REAL(KIND(1D0)), INTENT(INOUT)                  ::SnowAlb
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::IceFrac
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::SnowWater
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::SnowDens
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::snowFrac
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT) ::SnowPack
       ! water balance related:
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT)   ::soilstore_id
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT)   ::state_id
       REAL(KIND(1D0)), DIMENSION(6, NSURF), INTENT(INOUT) ::StoreDrainPrm
       ! phenology related:
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(INOUT)   ::alb
       REAL(KIND(1d0)), DIMENSION(5), INTENT(INOUT)       ::GDD_id !Growing Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(INOUT)::LAI_id !LAI for each veg surface [m2 m-2]
       REAL(KIND(1d0)), INTENT(INOUT)                    :: DecidCap_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: albDecTr_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: albEveTr_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: albGrass_id
       REAL(KIND(1d0)), INTENT(INOUT)                    :: porosity_id
       ! anthropogenic heat related:
       REAL(KIND(1d0)), DIMENSION(12), INTENT(INOUT) ::HDD_id !Heating Degree Days (see SUEWS_DailyState.f95)
       ! water use related:
       REAL(KIND(1d0)), DIMENSION(9), INTENT(INOUT)  ::WUDay_id
       ! ESTM related:
       REAL(KIND(1d0)), DIMENSION(24*3600/tstep), INTENT(INOUT)    ::Tair24HR ! TODO: this can be merged as one value rather than a vector, TS 20180906
       ! ########################################################################################
       ! ########################################################################################
       ! output variables
       ! REAL(KIND(1D0)),DIMENSION(:,:,:),ALLOCATABLE,INTENT(OUT) ::datetimeBlock
       REAL(KIND(1D0)), DIMENSION(len_sim, ncolumnsDataOutSUEWS), INTENT(OUT) ::dataOutBlockSUEWS
       REAL(KIND(1D0)), DIMENSION(len_sim, ncolumnsDataOutSnow), INTENT(OUT) ::dataOutBlockSnow
       REAL(KIND(1d0)), DIMENSION(len_sim, ncolumnsDataOutESTM), INTENT(OUT) ::dataOutBlockESTM
       REAL(KIND(1d0)), DIMENSION(len_sim, ncolumnsDataOutRSL), INTENT(OUT) ::dataOutBlockRSL
       REAL(KIND(1d0)), DIMENSION(len_sim, ncolumnsDataOutDailyState), INTENT(OUT) ::DailyStateBlock
       ! ########################################################################################
       ! internal temporal iteration related variables
       INTEGER::dt_since_start_x ! time since simulation starts [s]
       ! model output blocks of the same size as met forcing block
       ! local variables
       ! length of met forcing block
       INTEGER :: ir
       ! met forcing variables
       INTEGER :: iy
       INTEGER :: id
       INTEGER :: it
       INTEGER :: imin
       INTEGER :: isec
       INTEGER, PARAMETER :: gridiv_x = 1 ! a dummy gridiv as this routine is only one grid
       REAL(KIND(1D0))::qn1_obs
       REAL(KIND(1D0))::qh_obs
       REAL(KIND(1D0))::qe_obs
       REAL(KIND(1D0))::qs_obs
       REAL(KIND(1D0))::qf_obs
       REAL(KIND(1D0))::avu1
       REAL(KIND(1D0))::avrh
       REAL(KIND(1D0))::Temp_C
       REAL(KIND(1D0))::Press_hPa
       REAL(KIND(1D0))::Precip
       REAL(KIND(1D0))::avkdn
       REAL(KIND(1D0))::snowFrac_obs
       REAL(KIND(1D0))::ldown_obs
       REAL(KIND(1D0))::fcld_obs
       REAL(KIND(1D0))::wu_m3
       REAL(KIND(1D0))::xsmd
       REAL(KIND(1D0))::LAI_obs
       REAL(KIND(1D0))::kdiff
       REAL(KIND(1D0))::kdir
       REAL(KIND(1D0))::wdir
       REAL(KIND(1D0)), DIMENSION(5)::datetimeLine
       REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutSUEWS - 5)::dataOutLineSUEWS
       REAL(KIND(1D0)), DIMENSION(ncolumnsDataOutSnow - 5)::dataOutLineSnow
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutESTM - 5)::dataOutLineESTM
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutRSL - 5)::dataOutLineRSL
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutDailyState - 5)::DailyStateLine
       REAL(KIND(1D0)), DIMENSION(len_sim, ncolumnsDataOutSUEWS, 1) ::dataOutBlockSUEWS_X
       REAL(KIND(1D0)), DIMENSION(len_sim, ncolumnsDataOutSnow, 1) ::dataOutBlockSnow_X
       REAL(KIND(1d0)), DIMENSION(len_sim, ncolumnsDataOutESTM, 1) ::dataOutBlockESTM_X
       REAL(KIND(1d0)), DIMENSION(len_sim, ncolumnsDataOutRSL, 1) ::dataOutBlockRSL_X
       ! REAL(KIND(1d0)),DIMENSION(len_sim,ncolumnsDataOutDailyState,1) ::DailyStateBlock_X
       ! REAL(KIND(1D0)),DIMENSION(:,:)          ::MetForcingData_grid
       ! get initial dt_since_start_x from dt_since_start, dt_since_start_x is used for Qn averaging. TS 28 Nov 2018
       dt_since_start_x = dt_since_start
       DO ir = 1, len_sim, 1
          ! =============================================================================
          ! === Translate met data from MetForcingBlock to variable names used in model ==
          ! =============================================================================
          iy = int(metforcingblock(ir, 1)) !Integer variables
          id = int(metforcingblock(ir, 2))
          it = int(metforcingblock(ir, 3))
          imin = int(metforcingblock(ir, 4))
          isec = 0 ! NOT used by SUEWS but by WRF-SUEWS via the cal_main interface
          qn1_obs = metforcingblock(ir, 5)      !Real values (kind(1d0))
          qh_obs = metforcingblock(ir, 6)
          qe_obs = metforcingblock(ir, 7)
          qs_obs = metforcingblock(ir, 8)
          qf_obs = metforcingblock(ir, 9)
          avu1 = metforcingblock(ir, 10)
          avrh = metforcingblock(ir, 11)
          temp_c = metforcingblock(ir, 12)
          press_hpa = metforcingblock(ir, 13)
          precip = metforcingblock(ir, 14)
          avkdn = metforcingblock(ir, 15)
          snowfrac_obs = metforcingblock(ir, 16)
          ldown_obs = metforcingblock(ir, 17)
          fcld_obs = metforcingblock(ir, 18)
          wu_m3 = metforcingblock(ir, 19)
          xsmd = metforcingblock(ir, 20)
          lai_obs = metforcingblock(ir, 21)
          kdiff = metforcingblock(ir, 22)
          kdir = metforcingblock(ir, 23)
          wdir = metforcingblock(ir, 24)
          CALL suews_cal_main( &
             aerodynamicresistancemethod, ah_min, ahprof_24hr, ah_slope_cooling, & ! input&inout in alphabetical order
             ah_slope_heating, &
             alb, albmax_dectr, albmax_evetr, albmax_grass, &
             albmin_dectr, albmin_evetr, albmin_grass, &
             alpha_bioco2, alpha_enh_bioco2, alt, avkdn, avrh, avu1, baset, basete, &
             basethdd, beta_bioco2, beta_enh_bioco2, bldgh, capmax_dec, capmin_dec, &
             chanohm, co2pointsource, cpanohm, crwmax, crwmin, daywat, daywatper, &
             dectreeh, diagnose, diagqn, diagqs, drainrt, &
             dt_since_start_x, dqndt, qn1_av, dqnsdt, qn1_s_av, &
             ef_umolco2perj, emis, emissionsmethod, enef_v_jkm, enddls, evetreeh, faibldg, &
             faidectree, faievetree, faut, fcef_v_kgkm, fcld_obs, flowchange, &
             frfossilfuel_heat, frfossilfuel_nonheat, g1, g2, g3, g4, g5, g6, gdd_id, &
             gddfull, gridiv_x, gsmodel, hdd_id, humactivity_24hr, &
             icefrac, id, ie_a, ie_end, ie_m, ie_start, imin, &
             internalwateruse_h, irrfracconif, irrfracdecid, irrfracgrass, isec, it, evapmethod, &
             iy, kkanohm, kmax, lai_id, laicalcyes, laimax, laimin, lai_obs, &
             laipower, laitype, lat, ldown_obs, lng, maxconductance, maxfcmetab, maxqfmetab, &
             snowwater, metforcingblock, minfcmetab, minqfmetab, min_res_bioco2, &
             narp_emis_snow, narp_trans_site, netradiationmethod, &
             numcapita, ohm_coef, ohmincqf, ohm_threshsw, &
             ohm_threshwd, pipecapacity, popdensdaytime, &
             popdensnighttime, popprof_24hr, pormax_dec, pormin_dec, &
             precip, preciplimit, preciplimitalb, press_hpa, &
             qf0_beu, qf_a, qf_b, qf_c, &
             qn1_obs, qh_obs, qs_obs, qf_obs, &
             radmeltfact, raincover, rainmaxres, resp_a, resp_b, &
             roughlenheatmethod, roughlenmommethod, runofftowater, s1, s2, &
             sathydraulicconduct, sddfull, sfr, smdmethod, snowalb, snowalbmax, &
             snowalbmin, snowpacklimit, snowdens, snowdensmax, snowdensmin, snowfallcum, snowfrac, &
             snowlimbldg, snowlimpaved, snowfrac_obs, snowpack, snowprof_24hr, snowuse, soildepth, &
             soilstore_id, soilstorecap, stabilitymethod, startdls, state_id, statelimit, &
             storageheatmethod, storedrainprm, surfacearea, tair24hr, tau_a, tau_f, tau_r, &
             t_critic_cooling, t_critic_heating, temp_c, tempmeltfact, th, &
             theta_bioco2, timezone, tl, trafficrate, trafficunits, &
             traffprof_24hr, ts5mindata_ir, tstep, tstep_prev, veg_type, &
             waterdist, waterusemethod, wetthresh, wu_m3, &
             wuday_id, decidcap_id, albdectr_id, albevetr_id, albgrass_id, porosity_id, &
             wuprofa_24hr, wuprofm_24hr, xsmd, z, z0m_in, zdm_in, &
             datetimeline, dataoutlinesuews, dataoutlinesnow, dataoutlineestm, dataoutlinersl, &!output
             dailystateline)!output
          ! update dt_since_start_x for next iteration, dt_since_start_x is used for Qn averaging. TS 28 Nov 2018
          dt_since_start_x = dt_since_start_x + tstep
          !============ update and write out SUEWS_cal_DailyState ===============
          ! only works at the last timestep of a day
          ! CALL SUEWS_update_DailyState(&
          !      id, datetimeLine, &!input
          !      Gridiv, 1, &
          !      DailyStateLine, &
          !      DailyStateBlock_X)!inout
          dailystateblock(ir, :) = [datetimeline, dailystateline]
          !============ write out results ===============
          ! works at each timestep
          CALL suews_update_output( &
             snowuse, storageheatmethod, &!input
             len_sim, 1, &
             ir, gridiv_x, datetimeline, dataoutlinesuews, dataoutlinesnow, dataoutlineestm, dataoutlinersl, &!input
             dataoutblocksuews_x, dataoutblocksnow_x, dataoutblockestm_x, dataoutblockrsl_x)!inout
       END DO
       dataoutblocksuews = dataoutblocksuews_x(:, :, 1)
       dataoutblocksnow = dataoutblocksnow_x(:, :, 1)
       dataoutblockestm = dataoutblockestm_x(:, :, 1)
       dataoutblockrsl = dataoutblockrsl_x(:, :, 1)
       ! DailyStateBlock=DailyStateBlock_X(:,:,1)
References suews_cal_main(), and suews_update_output().
suews_cal_qe()
subroutine suews_driver::suews_cal_qe (integer, intent(in) Diagnose, integer, intent(in) tstep, integer, intent(in) imin, integer, intent(in) it, integer, intent(in) EvapMethod, integer, dimension(nsurf), intent(in) snowCalcSwitch, integer, dimension(3), intent(in) dayofWeek_id, real(kind(1d0)), intent(in) CRWmin, real(kind(1d0)), intent(in) CRWmax, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(in) lvS_J_kg, real(kind(1d0)), intent(in) lv_j_kg, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avRh, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) RAsnow, real(kind(1d0)), intent(in) psyc_hPa, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) sIce_hPa, real(kind(1d0)), intent(in) PervFraction, real(kind(1d0)), intent(in) vegfraction, real(kind(1d0)), intent(in) addimpervious, real(kind(1d0)), intent(in) qn1_snowfree, real(kind(1d0)), intent(in) qf, real(kind(1d0)), intent(in) qs, real(kind(1d0)), intent(in) vpd_hPa, real(kind(1d0)), intent(in) s_hPa, real(kind(1d0)), intent(in) ResistSurf, real(kind(1d0)), intent(in) RA, real(kind(1d0)), intent(in) rb, real(kind(1d0)), intent(in) snowdensmin, real(kind(1d0)), intent(in) precip, real(kind(1d0)), intent(in) PipeCapacity, real(kind(1d0)), intent(in) RunoffToWater, real(kind(1d0)), intent(in) NonWaterFraction, real(kind(1d0)), intent(in) wu_EveTr, real(kind(1d0)), intent(in) wu_DecTr, real(kind(1d0)), intent(in) wu_Grass, real(kind(1d0)), intent(in) addVeg, real(kind(1d0)), intent(in) addWaterBody, real(kind(1d0)), intent(in) SnowLimPaved, real(kind(1d0)), intent(in) SnowLimBldg, real(kind(1d0)), intent(in) SurfaceArea, real(kind(1d0)), intent(in) FlowChange, real(kind(1d0)), dimension(nsurf), intent(in) drain, real(kind(1d0)), dimension(nsurf), intent(in) WetThresh, real(kind(1d0)), dimension(nsurf), intent(in) stateOld, real(kind(1d0)), dimension(nsurf), intent(in) mw_ind, real(kind(1d0)), dimension(nsurf), intent(in) SoilStoreCap, real(kind(1d0)), dimension(nsurf), intent(in) rainonsnow, real(kind(1d0)), dimension(nsurf), intent(in) freezmelt, real(kind(1d0)), dimension(nsurf), intent(in) freezstate, real(kind(1d0)), dimension(nsurf), intent(in) freezstatevol, real(kind(1d0)), dimension(nsurf), intent(in) Qm_Melt, real(kind(1d0)), dimension(nsurf), intent(in) Qm_rain, real(kind(1d0)), dimension(nsurf), intent(in) Tsurf_ind, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(in) StateLimit, real(kind(1d0)), dimension(nsurf), intent(in) AddWater, real(kind(1d0)), dimension(nsurf), intent(in) addwaterrunoff, real(kind(1d0)), dimension(6, nsurf), intent(in) StoreDrainPrm, real(kind(1d0)), dimension(nsurf), intent(in) SnowPackLimit, real(kind(1d0)), dimension(0:23, 2), intent(in) SnowProf_24hr, real(kind(1d0)), intent(inout) runoff_per_interval, real(kind(1d0)), dimension(nsurf), intent(inout) state_id, real(kind(1d0)), dimension(nsurf), intent(inout) soilstore_id, real(kind(1d0)), dimension(nsurf), intent(inout) SnowPack, real(kind(1d0)), dimension(nsurf), intent(inout) snowFrac, real(kind(1d0)), dimension(nsurf), intent(inout) SnowWater, real(kind(1d0)), dimension(nsurf), intent(inout) iceFrac, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens, real(kind(1d0)), dimension(nsurf), intent(out) runoffSnow, real(kind(1d0)), dimension(nsurf), intent(out) runoff, real(kind(1d0)), dimension(nsurf), intent(out) runoffSoil, real(kind(1d0)), dimension(nsurf), intent(out) chang, real(kind(1d0)), dimension(nsurf), intent(out) changSnow, real(kind(1d0)), dimension(nsurf), intent(out) snowDepth, real(kind(1d0)), dimension(nsurf), intent(out) SnowToSurf, real(kind(1d0)), dimension(nsurf), intent(out) ev_snow, real(kind(1d0)), dimension(2), intent(out) SnowRemoval, real(kind(1d0)), dimension(nsurf), intent(out) evap, real(kind(1d0)), dimension(nsurf), intent(out) rss_nsurf, real(kind(1d0)), intent(out) p_mm, real(kind(1d0)), intent(out) qe, real(kind(1d0)), intent(out) state_per_tstep, real(kind(1d0)), intent(out) NWstate_per_tstep, real(kind(1d0)), intent(out) qeOut, real(kind(1d0)), intent(out) swe, real(kind(1d0)), intent(out) ev, real(kind(1d0)), intent(out) chSnow_per_interval, real(kind(1d0)), intent(out) ev_per_tstep, real(kind(1d0)), intent(out) qe_per_tstep, real(kind(1d0)), intent(out) runoff_per_tstep, real(kind(1d0)), intent(out) surf_chang_per_tstep, real(kind(1d0)), intent(out) runoffPipes, real(kind(1d0)), intent(out) mwstore, real(kind(1d0)), intent(out) runoffwaterbody, real(kind(1d0)), intent(out) runoffAGveg, real(kind(1d0)), intent(out) runoffAGimpervious, real(kind(1d0)), intent(out) runoffWaterBody_m3, real(kind(1d0)), intent(out) runoffPipes_m3)
Definition at line 1477 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in) ::Diagnose
       INTEGER, INTENT(in) ::tstep
       INTEGER, INTENT(in) ::imin
       INTEGER, INTENT(in) ::it
       INTEGER, INTENT(in) ::EvapMethod !Evaporation calculated according to Rutter (1) or Shuttleworth (2)
       INTEGER, DIMENSION(nsurf), INTENT(in)::snowCalcSwitch
       INTEGER, DIMENSION(3), INTENT(in)::dayofWeek_id
       REAL(KIND(1d0)), INTENT(in)::CRWmin
       REAL(KIND(1d0)), INTENT(in)::CRWmax
       REAL(KIND(1d0)), INTENT(in)::dectime
       REAL(KIND(1d0)), INTENT(in)::lvS_J_kg
       REAL(KIND(1d0)), INTENT(in)::lv_j_kg
       REAL(KIND(1d0)), INTENT(in)::avdens
       REAL(KIND(1d0)), INTENT(in)::avRh
       REAL(KIND(1d0)), INTENT(in)::Press_hPa
       REAL(KIND(1d0)), INTENT(in)::Temp_C
       REAL(KIND(1d0)), INTENT(in)::RAsnow
       REAL(KIND(1d0)), INTENT(in)::psyc_hPa
       REAL(KIND(1d0)), INTENT(in)::avcp
       REAL(KIND(1d0)), INTENT(in)::sIce_hPa
       REAL(KIND(1d0)), INTENT(in)::PervFraction
       REAL(KIND(1d0)), INTENT(in)::vegfraction
       REAL(KIND(1d0)), INTENT(in)::addimpervious
       REAL(KIND(1d0)), INTENT(in)::qn1_snowfree
       REAL(KIND(1d0)), INTENT(in)::qf
       REAL(KIND(1d0)), INTENT(in)::qs
       REAL(KIND(1d0)), INTENT(in)::vpd_hPa
       REAL(KIND(1d0)), INTENT(in)::s_hPa
       REAL(KIND(1d0)), INTENT(in)::ResistSurf
       REAL(KIND(1d0)), INTENT(in)::RA
       REAL(KIND(1d0)), INTENT(in)::rb
       REAL(KIND(1d0)), INTENT(in)::snowdensmin
       REAL(KIND(1d0)), INTENT(in)::precip
       REAL(KIND(1d0)), INTENT(in)::PipeCapacity
       REAL(KIND(1d0)), INTENT(in)::RunoffToWater
       REAL(KIND(1d0)), INTENT(in)::NonWaterFraction
       REAL(KIND(1d0)), INTENT(in)::wu_EveTr!Water use for evergreen trees/shrubs [mm]
       REAL(KIND(1d0)), INTENT(in)::wu_DecTr!Water use for deciduous trees/shrubs [mm]
       REAL(KIND(1d0)), INTENT(in)::wu_Grass!Water use for grass [mm]
       REAL(KIND(1d0)), INTENT(in)::addVeg!Water from vegetated surfaces of other grids [mm] for whole surface area
       REAL(KIND(1d0)), INTENT(in)::addWaterBody!Water from water surface of other grids [mm] for whole surface area
       REAL(KIND(1d0)), INTENT(in)::SnowLimPaved
       REAL(KIND(1d0)), INTENT(in)::SnowLimBldg
       REAL(KIND(1d0)), INTENT(in)::SurfaceArea
       REAL(KIND(1d0)), INTENT(in)::FlowChange
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::drain
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::WetThresh
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::stateOld
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::mw_ind
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::SoilStoreCap
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::rainonsnow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::freezmelt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::freezstate
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::freezstatevol
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Qm_Melt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Qm_rain
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Tsurf_ind
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::SnowPackLimit
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::StateLimit !Limit for state_id of each surface type [mm] (specified in input files)
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::AddWater
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::addwaterrunoff
       REAL(KIND(1d0)), DIMENSION(6, nsurf), INTENT(in)::StoreDrainPrm
       REAL(KIND(1d0)), DIMENSION(0:23, 2), INTENT(in):: SnowProf_24hr
       !Updated status: input and output
       REAL(KIND(1d0)), INTENT(inout)::runoff_per_interval! Total water transported to each grid for grid-to-grid connectivity
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::state_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::soilstore_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowPack
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::snowFrac
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowWater
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::iceFrac
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowDens
       ! output:
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::runoffSnow !Initialize for runoff caused by snowmelting
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::runoff
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::runoffSoil
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::chang
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::changSnow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::snowDepth
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::SnowToSurf
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::ev_snow
       REAL(KIND(1d0)), DIMENSION(2), INTENT(out)::SnowRemoval
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::evap
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::rss_nsurf
       REAL(KIND(1d0)), INTENT(out)::p_mm!Inputs to surface water balance
       ! REAL(KIND(1d0)),INTENT(out)::rss
       REAL(KIND(1d0)), INTENT(out)::qe ! latent heat flux [W m-2]
       REAL(KIND(1d0)), INTENT(out)::state_per_tstep
       REAL(KIND(1d0)), INTENT(out)::NWstate_per_tstep
       REAL(KIND(1d0)), INTENT(out)::qeOut
       REAL(KIND(1d0)), INTENT(out)::swe
       REAL(KIND(1d0)), INTENT(out)::ev
       REAL(KIND(1d0)), INTENT(out)::chSnow_per_interval
       REAL(KIND(1d0)), INTENT(out)::ev_per_tstep
       REAL(KIND(1d0)), INTENT(out)::qe_per_tstep
       REAL(KIND(1d0)), INTENT(out)::runoff_per_tstep
       REAL(KIND(1d0)), INTENT(out)::surf_chang_per_tstep
       REAL(KIND(1d0)), INTENT(out)::runoffPipes
       REAL(KIND(1d0)), INTENT(out)::mwstore
       REAL(KIND(1d0)), INTENT(out)::runoffwaterbody
       REAL(KIND(1d0)), INTENT(out)::runoffWaterBody_m3
       REAL(KIND(1d0)), INTENT(out)::runoffPipes_m3
       REAL(KIND(1d0)), INTENT(out)::runoffAGveg
       REAL(KIND(1d0)), INTENT(out)::runoffAGimpervious
       ! local:
       INTEGER:: is
       REAL(KIND(1d0)), DIMENSION(2)    ::SurplusEvap        !Surplus for evaporation in 5 min timestep
       REAL(KIND(1d0))::surplusWaterBody
       REAL(KIND(1d0))::pin!Rain per time interval
       ! REAL(KIND(1d0))::sae
       ! REAL(KIND(1d0))::vdrc
       ! REAL(KIND(1d0))::sp
       ! REAL(KIND(1d0))::numPM
       REAL(KIND(1d0))::qn_e
       REAL(KIND(1d0))::tlv
       REAL(KIND(1d0))::runoffAGimpervious_m3
       REAL(KIND(1d0))::runoffAGveg_m3
       REAL(KIND(1d0))::nsh_real
       REAL(KIND(1d0))::tstep_real
       REAL(KIND(1d0))::ev_tot
       REAL(KIND(1d0))::qe_tot
       REAL(KIND(1d0))::surf_chang_tot
       REAL(KIND(1d0))::runoff_tot
       REAL(KIND(1d0))::chSnow_tot
       REAL(KIND(1d0)), DIMENSION(7)::capStore ! current storage capacity [mm]
       tstep_real = tstep*1.d0
       nsh_real = 3600/tstep_real
       capstore = 0 !initialise capStore
       tlv = lv_j_kg/tstep_real !Latent heat of vapourisation per timestep
       pin = max(0., precip)!Initiate rain data [mm]
       ! Initialize the output variables
       qe = 0
       ev = 0
       qe_tot = 0
       ev_tot = 0
       swe = 0
       ev_snow = 0
       ev_per_tstep = 0
       qe_per_tstep = 0
       surf_chang_per_tstep = 0
       runoff_per_tstep = 0
       state_per_tstep = 0
       nwstate_per_tstep = 0
       qeout = 0
       runoffwaterbody = 0
       chsnow_per_interval = 0
       mwstore = 0
       runoffagveg = 0
       runoffagimpervious = 0
       surpluswaterbody = 0
       runoffsoil = 0
       runoff = 0
       chang = 0
       surplusevap = 0
       snowremoval = 0
       ! net available energy for evaporation
       qn_e = qn1_snowfree + qf - qs ! qn1 changed to qn1_snowfree, lj in May 2013
       IF (diagnose == 1) WRITE (*, *) 'Calling evap_SUEWS and SoilStore...'
       DO is = 1, nsurf   !For each surface in turn
          IF (snowcalcswitch(is) == 1) THEN ! snow calculation
             IF (sfr(is) /= 0) THEN
                IF (diagnose == 1) WRITE (*, *) 'Calling SnowCalc...'
                CALL snowcalc( &
                   tstep, imin, it, dectime, is, &!input
                   evapmethod, crwmin, crwmax, nsh_real, lvs_j_kg, lv_j_kg, avdens, &
                   avrh, press_hpa, temp_c, rasnow, psyc_hpa, avcp, sice_hpa, &
                   pervfraction, vegfraction, addimpervious, &
                   vpd_hpa, qn_e, s_hpa, resistsurf, ra, rb, tlv, snowdensmin, snowprof_24hr, precip, &
                   pipecapacity, runofftowater, &
                   addveg, snowlimpaved, snowlimbldg, flowchange, drain, &
                   wetthresh, stateold, mw_ind, soilstorecap, rainonsnow, &
                   freezmelt, freezstate, freezstatevol, &
                   qm_melt, qm_rain, tsurf_ind, sfr, dayofweek_id, storedrainprm, snowpacklimit, &
                   addwater, addwaterrunoff, &
                   soilstore_id, snowpack, surplusevap, &!inout
                   snowfrac, snowwater, icefrac, snowdens, &
                   runoffagimpervious, runoffagveg, surpluswaterbody, &
                   rss_nsurf, runoffsnow, & ! output
                   runoff, runoffsoil, chang, changsnow, snowtosurf, state_id, ev_snow, &
                   snowdepth, snowremoval, swe, ev, chsnow_tot, &
                   ev_tot, qe_tot, runoff_tot, surf_chang_tot, &
                   runoffpipes, mwstore, runoffwaterbody)
                !Actual updates here as xx_tstep variables not taken as input to snowcalc
                ev_per_tstep = ev_per_tstep + ev_tot
                qe_per_tstep = qe_per_tstep + qe_tot
                runoff_per_tstep = runoff_per_tstep + runoff_tot
                surf_chang_per_tstep = surf_chang_per_tstep + surf_chang_tot
                chsnow_per_interval = chsnow_per_interval + chsnow_tot
             ELSE
                snowfrac(is) = 0
                snowdens(is) = 0
                snowpack(is) = 0
             ENDIF
          ELSE ! snow-free calculation
             capstore(is) = storedrainprm(6, is)
             !Calculates ev [mm]
             CALL evap_suews( &
                evapmethod, state_id(is), wetthresh(is), capstore(is), &!input
                vpd_hpa, avdens, avcp, qn_e, s_hpa, psyc_hpa, resistsurf, ra, rb, tlv, &
                rss_nsurf(is), ev, qe) !output
             !Surface water balance and soil store updates (can modify ev, updates state_id)
             CALL soilstore( &
                is, sfr, pipecapacity, runofftowater, pin, & ! input:
                wu_evetr, wu_dectr, wu_grass, drain, addwater, addimpervious, nsh_real, stateold, addwaterrunoff, &
                pervfraction, addveg, soilstorecap, addwaterbody, flowchange, statelimit, runoffagimpervious, surpluswaterbody, &
                runoffagveg, runoffpipes, ev, soilstore_id, surplusevap, runoffwaterbody, &
                p_mm, chang, runoff, state_id)!output:
             !Store ev for each surface
             evap(is) = ev
             ! Sum evaporation from different surfaces to find total evaporation [mm]
             ev_per_tstep = ev_per_tstep + evap(is)*sfr(is)
             ! Sum latent heat flux from different surfaces to find total latent heat flux
             qe_per_tstep = qe_per_tstep + qe*sfr(is)
             ! Sum change from different surfaces to find total change to surface state_id
             surf_chang_per_tstep = surf_chang_per_tstep + (state_id(is) - stateold(is))*sfr(is)
             ! Sum runoff from different surfaces to find total runoff
             runoff_per_tstep = runoff_per_tstep + runoff(is)*sfr(is)
             ! Calculate total state_id (including water body)
             state_per_tstep = state_per_tstep + state_id(is)*sfr(is)
             ! sum The total runoff from the area !!Check (HCW)
             runoff_per_interval = runoff_per_interval + (runoff(is)*sfr(is))
             IF (nonwaterfraction /= 0 .AND. is /= watersurf) THEN
                nwstate_per_tstep = nwstate_per_tstep + (state_id(is)*sfr(is)/nonwaterfraction)
             ENDIF
             changsnow(is) = 0
             runoffsnow(is) = 0
          ENDIF
       ENDDO  !end loop over surfaces
       qeout = qe_per_tstep
       ! Calculate volume of water that will move between grids
       ! Volume [m3] = Depth relative to whole area [mm] / 1000 [mm m-1] * SurfaceArea [m2]
       ! Need to use these volumes when converting back to addImpervious, AddVeg and AddWater
       runoffagimpervious_m3 = runoffagimpervious/1000*surfacearea
       runoffagveg_m3 = runoffagveg/1000*surfacearea
       runoffwaterbody_m3 = runoffwaterbody/1000*surfacearea
       runoffpipes_m3 = runoffpipes/1000*surfacearea
References evap_suews(), allocatearray::nsurf, snow_module::snowcalc(), waterdist_module::soilstore(), and allocatearray::watersurf.
Referenced by suews_cal_main().
suews_cal_qh()
subroutine suews_driver::suews_cal_qh (integer, intent(in) QHMethod, real(kind(1d0)), intent(in) qn1, real(kind(1d0)), intent(in) qf, real(kind(1d0)), intent(in) QmRain, real(kind(1d0)), intent(in) qeOut, real(kind(1d0)), intent(in) qs, real(kind(1d0)), intent(in) QmFreez, real(kind(1d0)), intent(in) qm, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) tsurf, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) RA, real(kind(1d0)), intent(out) qh, real(kind(1d0)), intent(out) qh_residual, real(kind(1d0)), intent(out) qh_resist)
Definition at line 1758 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in) :: QHMethod ! option for QH calculation: 1, residual; 2, resistance-based
       REAL(KIND(1d0)), INTENT(in)::qn1
       REAL(KIND(1d0)), INTENT(in)::qf
       REAL(KIND(1d0)), INTENT(in)::QmRain
       REAL(KIND(1d0)), INTENT(in)::qeOut
       REAL(KIND(1d0)), INTENT(in)::qs
       REAL(KIND(1d0)), INTENT(in)::QmFreez
       REAL(KIND(1d0)), INTENT(in)::qm
       REAL(KIND(1d0)), INTENT(in)::avdens
       REAL(KIND(1d0)), INTENT(in)::avcp
       REAL(KIND(1d0)), INTENT(in)::tsurf
       REAL(KIND(1d0)), INTENT(in)::Temp_C
       REAL(KIND(1d0)), INTENT(in)::RA
       REAL(KIND(1d0)), INTENT(out)::qh
       REAL(KIND(1d0)), INTENT(out)::qh_resist
       REAL(KIND(1d0)), INTENT(out)::qh_residual
       REAL(KIND(1d0)), PARAMETER::NAN = -999
       ! Calculate sensible heat flux as a residual (Modified by LJ in Nov 2012)
       qh_residual = (qn1 + qf + qmrain) - (qeout + qs + qm + qmfreez)     !qh=(qn1+qf+QmRain+QmFreez)-(qeOut+qs+Qm)
       ! ! Calculate QH using resistance method (for testing HCW 06 Jul 2016)
       ! Aerodynamic-Resistance-based method
       IF (ra /= 0) THEN
          qh_resist = avdens*avcp*(tsurf - temp_c)/ra
       ELSE
          qh_resist = nan
       ENDIF
       ! choose output QH
       SELECT CASE (qhmethod)
       CASE (1)
          qh = qh_residual
       CASE (2)
          qh = qh_resist
       END SELECT
Referenced by suews_cal_main().
suews_cal_qn()
subroutine suews_driver::suews_cal_qn (integer, intent(in) NetRadiationMethod, integer, intent(in) snowUse, integer, intent(in) Diagnose, real(kind(1d0)), intent(in) snowFrac_obs, real(kind(1d0)), intent(in) ldown_obs, real(kind(1d0)), intent(in) fcld_obs, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(in) ZENITH_deg, real(kind(1d0)), intent(in) avKdn, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) avRH, real(kind(1d0)), intent(in) ea_hPa, real(kind(1d0)), intent(in) qn1_obs, real(kind(1d0)), intent(in) SnowAlb, integer, intent(in) DiagQN, real(kind(1d0)), intent(in) NARP_TRANS_SITE, real(kind(1d0)), intent(in) NARP_EMIS_SNOW, real(kind(1d0)), dimension(nsurf), intent(in) IceFrac, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(in) emis, real(kind(1d0)), dimension(nsurf), intent(inout) alb, real(kind(1d0)), intent(in) albDecTr_id, real(kind(1d0)), intent(in) DecidCap_id, real(kind(1d0)), intent(in) albEveTr_id, real(kind(1d0)), intent(in) albGrass_id, real(kind(1d0)), dimension(6, nsurf), intent(inout) StoreDrainPrm, real(kind(1d0)), dimension(nsurf), intent(inout) snowFrac, real(kind(1d0)), intent(out) ldown, real(kind(1d0)), intent(out) fcld, real(kind(1d0)), intent(out) qn1, real(kind(1d0)), intent(out) qn1_snowfree, real(kind(1d0)), intent(out) qn1_S, real(kind(1d0)), intent(out) kclear, real(kind(1d0)), intent(out) kup, real(kind(1d0)), intent(out) lup, real(kind(1d0)), intent(out) tsurf, real(kind(1d0)), dimension(nsurf), intent(out) qn1_ind_snow, real(kind(1d0)), dimension(nsurf), intent(out) kup_ind_snow, real(kind(1d0)), dimension(nsurf), intent(out) Tsurf_ind_snow, real(kind(1d0)), dimension(nsurf), intent(out) Tsurf_ind)
Definition at line 1053 of file suews_ctrl_driver.f95.
       USE narp_module, ONLY: radmethod, narp
       IMPLICIT NONE
       ! INTEGER,PARAMETER ::nsurf     = 7 ! number of surface types
       ! INTEGER,PARAMETER ::ConifSurf = 3 !New surface classes: Grass = 5th/7 surfaces
       ! INTEGER,PARAMETER ::DecidSurf = 4 !New surface classes: Grass = 5th/7 surfaces
       ! INTEGER,PARAMETER ::GrassSurf = 5
       INTEGER, INTENT(in)::NetRadiationMethod
       INTEGER, INTENT(in)::snowUse
       INTEGER, INTENT(in)::Diagnose
       INTEGER, INTENT(in)::DiagQN
       REAL(KIND(1d0)), INTENT(in)::snowFrac_obs
       REAL(KIND(1d0)), INTENT(in)::ldown_obs
       REAL(KIND(1d0)), INTENT(in)::fcld_obs
       REAL(KIND(1d0)), INTENT(in)::dectime
       REAL(KIND(1d0)), INTENT(in)::ZENITH_deg
       REAL(KIND(1d0)), INTENT(in)::avKdn
       REAL(KIND(1d0)), INTENT(in)::Temp_C
       REAL(KIND(1d0)), INTENT(in)::avRH
       REAL(KIND(1d0)), INTENT(in)::ea_hPa
       REAL(KIND(1d0)), INTENT(in)::qn1_obs
       REAL(KIND(1d0)), INTENT(in)::SnowAlb
       REAL(KIND(1d0)), INTENT(in)::NARP_EMIS_SNOW
       REAL(KIND(1d0)), INTENT(in)::NARP_TRANS_SITE
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in):: IceFrac
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in):: sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in):: emis
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)  ::alb
       REAL(KIND(1d0)), INTENT(in)  ::albDecTr_id
       REAL(KIND(1d0)), INTENT(in)  ::DecidCap_id
       REAL(KIND(1d0)), INTENT(in)  ::albEveTr_id
       REAL(KIND(1d0)), INTENT(in)  ::albGrass_id
       REAL(KIND(1d0)), DIMENSION(6, nsurf), INTENT(inout)::StoreDrainPrm
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::snowFrac
       REAL(KIND(1d0)), INTENT(out)::ldown
       REAL(KIND(1d0)), INTENT(out)::fcld
       REAL(KIND(1d0)), INTENT(out)::qn1
       REAL(KIND(1d0)), INTENT(out)::qn1_snowfree
       REAL(KIND(1d0)), INTENT(out)::qn1_S
       REAL(KIND(1d0)), INTENT(out)::kclear
       REAL(KIND(1d0)), INTENT(out)::kup
       REAL(KIND(1d0)), INTENT(out)::lup
       REAL(KIND(1d0)), INTENT(out)::tsurf
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out) ::qn1_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out) ::kup_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out) ::Tsurf_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out):: tsurf_ind
       REAL(KIND(1d0)), DIMENSION(nsurf):: lup_ind
       REAL(KIND(1d0)), DIMENSION(nsurf):: kup_ind
       REAL(KIND(1d0)), DIMENSION(nsurf):: qn1_ind
       REAL(KIND(1d0)), PARAMETER::NAN = -999
       INTEGER :: NetRadiationMethodX
       INTEGER::AlbedoChoice, ldown_option
       CALL radmethod( &
          netradiationmethod, &!inout
          snowuse, &!input
          netradiationmethodx, albedochoice, ldown_option)!output
       IF (netradiationmethodx > 0) THEN
          ! IF (snowUse==0) snowFrac=snowFrac_obs
          IF (snowuse == 0) snowfrac = 0
          IF (ldown_option == 1) THEN !Observed ldown provided as forcing
             ldown = ldown_obs
          ELSE
             ldown = -9              !to be filled in NARP
          ENDIF
          IF (ldown_option == 2) THEN !observed cloud fraction provided as forcing
             fcld = fcld_obs
          ENDIF
          !write(*,*) DecidCap(id), id, it, imin, 'Calc - near start'
          ! Update variables that change daily and represent seasonal variability
          alb(decidsurf) = albdectr_id !Change deciduous albedo
          storedrainprm(6, decidsurf) = decidcap_id !Change current storage capacity of deciduous trees
          ! Change EveTr and Grass albedo too
          alb(conifsurf) = albevetr_id
          alb(grasssurf) = albgrass_id
          IF (diagnose == 1) WRITE (*, *) 'Calling NARP...'
          CALL narp( &
             nsurf, sfr, snowfrac, alb, emis, icefrac, &! input:
             narp_trans_site, narp_emis_snow, &
             dectime, zenith_deg, avkdn, temp_c, avrh, ea_hpa, qn1_obs, &
             snowalb, &
             albedochoice, ldown_option, netradiationmethodx, diagqn, &
             qn1, qn1_snowfree, qn1_s, kclear, kup, ldown, lup, fcld, tsurf, &! output:
             qn1_ind_snow, kup_ind_snow, tsurf_ind_snow, tsurf_ind)
       ELSE ! NetRadiationMethod==0
          snowfrac = snowfrac_obs
          qn1 = qn1_obs
          qn1_snowfree = qn1_obs
          qn1_s = qn1_obs
          ldown = nan
          lup = nan
          kup = nan
          tsurf = nan
          lup_ind = nan
          kup_ind = nan
          tsurf_ind = nan
          qn1_ind = nan
          fcld = nan
       ENDIF
       IF (ldown_option == 1) THEN
          fcld = nan
       ENDIF
References allocatearray::conifsurf, allocatearray::decidsurf, allocatearray::grasssurf, narp_module::narp(), allocatearray::nsurf, and narp_module::radmethod().
Referenced by suews_cal_main().
suews_cal_qs()
subroutine suews_driver::suews_cal_qs (integer, intent(in) StorageHeatMethod, real(kind(1d0)), intent(in) qs_obs, integer, intent(in) OHMIncQF, integer, intent(in) Gridiv, integer, intent(in) id, integer, intent(in) tstep, integer, intent(in) dt_since_start, integer, intent(in) Diagnose, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf + 1, 4, 3), intent(in) OHM_coef, real(kind(1d0)), dimension(nsurf + 1), intent(in) OHM_threshSW, real(kind(1d0)), dimension(nsurf + 1), intent(in) OHM_threshWD, real(kind(1d0)), dimension(nsurf), intent(in) soilstore_id, real(kind(1d0)), dimension(nsurf), intent(in) SoilStoreCap, real(kind(1d0)), dimension(nsurf), intent(in) state_id, integer, intent(in) nsh, integer, intent(in) SnowUse, integer, intent(in) DiagQS, real(kind(1d0)), dimension(12), intent(in) HDD_id, real(kind(1d0)), dimension(:, :), intent(in) MetForcingData_grid, real(kind(1d0)), dimension(:), intent(in) Ts5mindata_ir, real(kind(1d0)), intent(in) qf, real(kind(1d0)), intent(in) qn1, real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) avu1, real(kind(1d0)), intent(in) temp_c, real(kind(1d0)), intent(in) zenith_deg, real(kind(1d0)), intent(in) avrh, real(kind(1d0)), intent(in) press_hpa, real(kind(1d0)), intent(in) ldown, real(kind(1d0)), intent(in) bldgh, real(kind(1d0)), dimension(nsurf), intent(in) alb, real(kind(1d0)), dimension(nsurf), intent(in) emis, real(kind(1d0)), dimension(nsurf), intent(in) cpAnOHM, real(kind(1d0)), dimension(nsurf), intent(in) kkAnOHM, real(kind(1d0)), dimension(nsurf), intent(in) chAnOHM, integer, intent(in) EmissionsMethod, real(kind(1d0)), dimension(24*nsh), intent(inout) Tair24HR, real(kind(1d0)), intent(inout) qn1_av, real(kind(1d0)), intent(inout) dqndt, real(kind(1d0)), intent(inout) qn1_s_av, real(kind(1d0)), intent(inout) dqnsdt, real(kind(1d0)), dimension(6, nsurf), intent(inout) StoreDrainPrm, real(kind(1d0)), intent(out) qn1_S, real(kind(1d0)), dimension(nsurf), intent(in) snowFrac, real(kind(1d0)), dimension(27), intent(out) dataOutLineESTM, real(kind(1d0)), intent(out) qs, real(kind(1d0)), dimension(nsurf), intent(out) deltaQi, real(kind(1d0)), intent(out) a1, real(kind(1d0)), intent(out) a2, real(kind(1d0)), intent(out) a3)
Parameters
[in] emissionsmethod AnthropHeat option [-]
[in] alb albedo [-]
[in] emis emissivity [-]
[in] cpanohm heat capacity [J m-3 K-1]
[in] kkanohm thermal conductivity [W m-1 K-1]
[in] chanohm bulk transfer coef [J m-3 K-1]
[in] metforcingdata_grid met forcing array of grid
[out] a1 AnOHM coefficients of grid [-]
[out] a2 AnOHM coefficients of grid [h]
[out] a3 AnOHM coefficients of grid [W m-2]
Definition at line 1192 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in)  ::StorageHeatMethod
       INTEGER, INTENT(in)  ::OHMIncQF
       INTEGER, INTENT(in)  ::Gridiv
       INTEGER, INTENT(in)  ::id
       INTEGER, INTENT(in)  ::tstep ! time step [s]
       INTEGER, INTENT(in) ::dt_since_start  ! time since simulation starts [s]
       INTEGER, INTENT(in)  ::Diagnose
       INTEGER, INTENT(in)  ::nsh              ! number of timesteps in one hour
       INTEGER, INTENT(in)  ::SnowUse          ! option for snow related calculations
       INTEGER, INTENT(in)  ::DiagQS           ! diagnostic option
       INTEGER, INTENT(in)  :: EmissionsMethod
       REAL(KIND(1d0)), INTENT(in)::OHM_coef(nsurf + 1, 4, 3)                 ! OHM coefficients
       REAL(KIND(1d0)), INTENT(in)::OHM_threshSW(nsurf + 1) ! OHM thresholds
       REAL(KIND(1d0)), INTENT(in)::OHM_threshWD(nsurf + 1) ! OHM thresholds
       REAL(KIND(1d0)), INTENT(in)::soilstore_id(nsurf)                ! soil moisture
       REAL(KIND(1d0)), INTENT(in)::SoilStoreCap(nsurf)             ! capacity of soil store
       REAL(KIND(1d0)), INTENT(in)::state_id(nsurf) ! wetness status
       REAL(KIND(1d0)), DIMENSION(12), INTENT(in)::HDD_id
       REAL(KIND(1d0)), INTENT(in)::qf
       REAL(KIND(1d0)), INTENT(in)::qn1
       REAL(KIND(1d0)), INTENT(in)::qs_obs
       REAL(KIND(1d0)), INTENT(in)::avkdn, avu1, temp_c, zenith_deg, avrh, press_hpa, ldown
       REAL(KIND(1d0)), INTENT(in)::bldgh
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::alb
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::emis
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::cpAnOHM
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::kkAnOHM
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::chAnOHM
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::snowFrac
       REAL(KIND(1d0)), DIMENSION(:, :), INTENT(in)::MetForcingData_grid
       REAL(KIND(1d0)), DIMENSION(:), INTENT(in)::Ts5mindata_ir
       REAL(KIND(1d0)), DIMENSION(24*nsh), INTENT(inout)::Tair24HR
       REAL(KIND(1d0)), INTENT(inout)                  ::qn1_av
       REAL(KIND(1d0)), INTENT(inout)                  ::dqndt!Rate of change of net radiation [W m-2 h-1] at t-1
       REAL(KIND(1d0)), INTENT(inout)                  ::qn1_s_av
       REAL(KIND(1d0)), INTENT(inout)                  ::dqnsdt !Rate of change of net radiation [W m-2 h-1] at t-1
       ! REAL(KIND(1d0)),DIMENSION(nsh),INTENT(inout)   ::qn1_store_grid
       ! REAL(KIND(1d0)),DIMENSION(nsh),INTENT(inout)   ::qn1_S_store_grid !< stored qn1 [W m-2]
       ! REAL(KIND(1d0)),DIMENSION(2*nsh+1),INTENT(inout)::qn1_av_store_grid
       ! REAL(KIND(1d0)),DIMENSION(2*nsh+1),INTENT(inout)::qn1_S_av_store_grid !< average net radiation over previous hour [W m-2]
       REAL(KIND(1d0)), DIMENSION(6, nsurf), INTENT(inout)::StoreDrainPrm
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::deltaQi ! storage heat flux of snow surfaces
       REAL(KIND(1d0)), DIMENSION(27), INTENT(out):: dataOutLineESTM
       REAL(KIND(1d0)), INTENT(out)::qn1_S
       REAL(KIND(1d0)), INTENT(out):: qs ! storage heat flux
       REAL(KIND(1d0)), INTENT(out):: a1
       REAL(KIND(1d0)), INTENT(out):: a2
       REAL(KIND(1d0)), INTENT(out):: a3
       REAL(KIND(1d0))::Tair_mav_5d ! Tair_mav_5d=HDD(id-1,4) HDD at the begining of today (id-1)
       REAL(KIND(1d0))::qn1_use ! qn used in OHM calculations
       ! initialise output variables
       !deltaQi = 0
       !snowFrac = 0
       !qn1_S = 0
       dataoutlineestm = -999
       qs = -999
       a1 = -999
       a2 = -999
       a3 = -999
       ! calculate qn if qf should be included
       IF (ohmincqf == 1) THEN
          qn1_use = qf + qn1
       ELSEIF (ohmincqf == 0) THEN
          qn1_use = qn1
       ENDIF
       IF (storageheatmethod == 0) THEN           !Use observed QS
          qs = qs_obs
       ELSEIF (storageheatmethod == 1) THEN           !Use OHM to calculate QS
          tair_mav_5d = hdd_id(10)
          IF (diagnose == 1) WRITE (*, *) 'Calling OHM...'
          CALL ohm(qn1, qn1_av, dqndt, &
                   qn1_s, qn1_s_av, dqnsdt, &
                   tstep, dt_since_start, &
                   sfr, nsurf, &
                   tair_mav_5d, &
                   ohm_coef, &
                   ohm_threshsw, ohm_threshwd, &
                   soilstore_id, soilstorecap, state_id, &
                   bldgsurf, watersurf, &
                   snowuse, snowfrac, &
                   diagqs, &
                   a1, a2, a3, qs, deltaqi)
          ! use AnOHM to calculate QS, TS 14 Mar 2016
       ELSEIF (storageheatmethod == 3) THEN
          IF (diagnose == 1) WRITE (*, *) 'Calling AnOHM...'
          ! CALL AnOHM(qn1_use,qn1_store_grid,qn1_av_store_grid,qf,&
          !      MetForcingData_grid,state_id/StoreDrainPrm(6,:),&
          !      alb, emis, cpAnOHM, kkAnOHM, chAnOHM,&
          !      sfr,nsurf,nsh,EmissionsMethod,id,Gridiv,&
          !      a1,a2,a3,qs,deltaQi)
          CALL anohm( &
             tstep, dt_since_start, &
             qn1_use, qn1_av, dqndt, qf, &
             metforcingdata_grid, state_id/storedrainprm(6, :), &
             alb, emis, cpanohm, kkanohm, chanohm, &! input
             sfr, nsurf, emissionsmethod, id, gridiv, &
             a1, a2, a3, qs, deltaqi)! output
          ! !Calculate QS using ESTM
       ELSEIF (storageheatmethod == 4 .OR. storageheatmethod == 14) THEN
          !    !CALL ESTM(QSestm,iMB)
          IF (diagnose == 1) WRITE (*, *) 'Calling ESTM...'
          CALL estm( &
             gridiv, &!input
             nsh, tstep, &
             avkdn, avu1, temp_c, zenith_deg, avrh, press_hpa, ldown, &
             bldgh, ts5mindata_ir, &
             tair24hr, &!inout
             dataoutlineestm, qs)!output
          !    CALL ESTM(QSestm,Gridiv,ir)  ! iMB corrected to Gridiv, TS 09 Jun 2016
          !    QS=QSestm   ! Use ESTM qs
       ENDIF
References anohm_module::anohm(), allocatearray::bldgsurf, estm_module::estm(), ohm(), and allocatearray::watersurf.
Referenced by suews_cal_main().
suews_cal_resistance()
subroutine suews_driver::suews_cal_resistance (integer, intent(in) StabilityMethod, integer, intent(in) Diagnose, integer, intent(in) AerodynamicResistanceMethod, integer, intent(in) RoughLenHeatMethod, integer, intent(in) snowUse, integer, intent(in) id, integer, intent(in) it, integer, intent(in) gsModel, integer, intent(in) SMDMethod, real(kind(1d0)), intent(in) qh_obs, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) h_mod, real(kind(1d0)), intent(in) qn1, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(in) zzd, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) zdm, real(kind(1d0)), intent(in) avU1, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) VegFraction, real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) Kmax, real(kind(1d0)), intent(in) G1, real(kind(1d0)), intent(in) G2, real(kind(1d0)), intent(in) G3, real(kind(1d0)), intent(in) G4, real(kind(1d0)), intent(in) G5, real(kind(1d0)), intent(in) G6, real(kind(1d0)), intent(in) S1, real(kind(1d0)), intent(in) S2, real(kind(1d0)), intent(in) TH, real(kind(1d0)), intent(in) TL, real(kind(1d0)), intent(in) dq, real(kind(1d0)), intent(in) xsmd, real(kind(1d0)), intent(in) vsmd, real(kind(1d0)), dimension(3), intent(in) MaxConductance, real(kind(1d0)), dimension(3), intent(in) LAIMax, real(kind(1d0)), dimension(3), intent(in) LAI_id, real(kind(1d0)), dimension(nsurf), intent(in) snowFrac, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), intent(out) UStar, real(kind(1d0)), intent(out) TStar, real(kind(1d0)), intent(out) L_mod, real(kind(1d0)), intent(out) zL, real(kind(1d0)), intent(out) gsc, real(kind(1d0)), intent(out) ResistSurf, real(kind(1d0)), intent(out) RA, real(kind(1d0)), intent(out) RAsnow, real(kind(1d0)), intent(out) rb)
Definition at line 1814 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in)::StabilityMethod
       INTEGER, INTENT(in)::Diagnose
       INTEGER, INTENT(in)::AerodynamicResistanceMethod
       INTEGER, INTENT(in)::RoughLenHeatMethod
       INTEGER, INTENT(in)::snowUse
       INTEGER, INTENT(in)::id
       INTEGER, INTENT(in)::it       !time: day of year and hour
       INTEGER, INTENT(in)::gsModel  !Choice of gs parameterisation (1 = Ja11, 2 = Wa16)
       INTEGER, INTENT(in)::SMDMethod!Method of measured soil moisture
       REAL(KIND(1d0)), INTENT(in)::qh_obs
       REAL(KIND(1d0)), INTENT(in)::avdens
       REAL(KIND(1d0)), INTENT(in)::avcp
       REAL(KIND(1d0)), INTENT(in)::h_mod
       REAL(KIND(1d0)), INTENT(in)::qn1
       REAL(KIND(1d0)), INTENT(in)::dectime    !Decimal time
       REAL(KIND(1d0)), INTENT(in)::zzd        !Active measurement height (meas. height-displac. height)
       REAL(KIND(1d0)), INTENT(in)::z0m        !Aerodynamic roughness length
       REAL(KIND(1d0)), INTENT(in)::zdm        !Displacement height
       REAL(KIND(1d0)), INTENT(in)::avU1       !Average wind speed
       REAL(KIND(1d0)), INTENT(in)::Temp_C     !Air temperature
       REAL(KIND(1d0)), INTENT(in)::VegFraction!Fraction of vegetation
       REAL(KIND(1d0)), INTENT(in)::avkdn      !Average downwelling shortwave radiation
       REAL(KIND(1d0)), INTENT(in)::Kmax       !Annual maximum hourly solar radiation
       REAL(KIND(1d0)), INTENT(in)::G1         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::G2         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::G3         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::G4         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::G5         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::G6         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::S1         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::S2         !Fitted parameters related to surface res. calculations
       REAL(KIND(1d0)), INTENT(in)::TH         !Maximum temperature limit
       REAL(KIND(1d0)), INTENT(in)::TL         !Minimum temperature limit
       REAL(KIND(1d0)), INTENT(in)::dq         !Specific humidity deficit
       REAL(KIND(1d0)), INTENT(in)::xsmd       !Measured soil moisture deficit
       REAL(KIND(1d0)), INTENT(in)::vsmd       !Soil moisture deficit for vegetated surfaces only (QUESTION: what about BSoil?)
       REAL(KIND(1d0)), DIMENSION(3), INTENT(in) ::MaxConductance!Max conductance [mm s-1]
       REAL(KIND(1d0)), DIMENSION(3), INTENT(in) ::LAIMax        !Max LAI [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(3), INTENT(in) ::LAI_id        !=LAI_id(id-1,:), LAI for each veg surface [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::snowFrac      !Surface fraction of snow cover
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr           !Surface fractions [-]
       REAL(KIND(1d0)), INTENT(out)::TStar     !T*
       REAL(KIND(1d0)), INTENT(out)  ::UStar     !Friction velocity
       ! REAL(KIND(1d0)),INTENT(out)::psim      !Stability function of momentum
       REAL(KIND(1d0)), INTENT(out)  ::zL        !
       REAL(KIND(1d0)), INTENT(out)  ::gsc       !Surface Layer Conductance
       REAL(KIND(1d0)), INTENT(out)  ::ResistSurf!Surface resistance
       REAL(KIND(1d0)), INTENT(out)  ::RA        !Aerodynamic resistance [s m^-1]
       REAL(KIND(1d0)), INTENT(out)  ::RAsnow    !Aerodynamic resistance for snow [s m^-1]
       REAL(KIND(1d0)), INTENT(out)  ::rb        !boundary layer resistance shuttleworth
       REAL(KIND(1d0)), INTENT(out)  ::L_mod     !Obukhov length
       REAL(KIND(1d0))              ::gfunc     !gdq*gtemp*gs*gq for photosynthesis calculations
       REAL(KIND(1d0))              ::H_init    !Kinematic sensible heat flux [K m s-1] used to calculate friction velocity
       ! Get first estimate of sensible heat flux. Modified by HCW 26 Feb 2015
       CALL suews_init_qh( &
          qh_obs, avdens, avcp, h_mod, qn1, dectime, &
          h_init)
       IF (diagnose == 1) WRITE (*, *) 'Calling STAB_lumps...'
       !u* and Obukhov length out
       CALL stab_lumps( &
          stabilitymethod, &  ! input
          dectime, & !Decimal time
          zzd, &     !Active measurement height (meas. height-displac. height)
          z0m, &     !Aerodynamic roughness length
          zdm, &     !Displacement height
          avu1, &    !Average wind speed
          temp_c, &  !Air temperature
          h_init, & !Kinematic sensible heat flux [K m s-1] used to calculate friction velocity
          l_mod, &! output: !Obukhov length
          tstar, & !T*
          ustar, & !Friction velocity
          zl)!Stability scale
       IF (diagnose == 1) WRITE (*, *) 'Calling AerodynamicResistance...'
       CALL aerodynamicresistance( &
          zzd, &! input:
          z0m, &
          avu1, &
          l_mod, &
          ustar, &
          vegfraction, &
          aerodynamicresistancemethod, &
          stabilitymethod, &
          roughlenheatmethod, &
          ra) ! output:
       IF (snowuse == 1) THEN
          IF (diagnose == 1) WRITE (*, *) 'Calling AerodynamicResistance for snow...'
          CALL aerodynamicresistance( &
             zzd, &! input:
             z0m, &
             avu1, &
             l_mod, &
             ustar, &
             vegfraction, &
             aerodynamicresistancemethod, &
             stabilitymethod, &
             3, &
             rasnow)     ! output:
       ENDIF
       IF (diagnose == 1) WRITE (*, *) 'Calling SurfaceResistance...'
       ! CALL SurfaceResistance(id,it)   !qsc and surface resistance out
       CALL surfaceresistance( &
          id, it, &! input:
          smdmethod, snowfrac, sfr, avkdn, temp_c, dq, xsmd, vsmd, maxconductance, &
          laimax, lai_id, gsmodel, kmax, &
          g1, g2, g3, g4, g5, g6, th, tl, s1, s2, &
          gfunc, gsc, resistsurf)! output:
       IF (diagnose == 1) WRITE (*, *) 'Calling BoundaryLayerResistance...'
       CALL boundarylayerresistance( &
          zzd, &! input:     !Active measurement height (meas. height-displac. height)
          z0m, &     !Aerodynamic roughness length
          avu1, &    !Average wind speed
          ustar, &  ! input/output:
          rb)  ! output:
References aerodynamicresistance(), boundarylayerresistance(), atmmoiststab_module::stab_lumps(), suews_init_qh(), and surfaceresistance().
Referenced by suews_cal_main().
suews_cal_sunposition()
subroutine suews_driver::suews_cal_sunposition (real(kind(1d0)), intent(in) year, real(kind(1d0)), intent(in) idectime, real(kind(1d0)), intent(in) UTC, real(kind(1d0)), intent(in) locationlatitude, real(kind(1d0)), intent(in) locationlongitude, real(kind(1d0)), intent(in) locationaltitude, real(kind(1d0)), intent(out) sunazimuth, real(kind(1d0)), intent(out) sunzenith)
Definition at line 2928 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: year, idectime, UTC, &
                                      locationlatitude, locationlongitude, locationaltitude
       REAL(KIND(1D0)), INTENT(out) ::sunazimuth, sunzenith
       CALL narp_cal_sunposition( &
          year, idectime, utc, locationlatitude, locationlongitude, locationaltitude, &
          sunazimuth, sunzenith)
References narp_module::narp_cal_sunposition().
suews_cal_surf()
subroutine suews_driver::suews_cal_surf (real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), intent(out) vegfraction, real(kind(1d0)), intent(out) ImpervFraction, real(kind(1d0)), intent(out) PervFraction, real(kind(1d0)), intent(out) NonWaterFraction)
Definition at line 2262 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), DIMENSION(NSURF), INTENT(IN)::sfr
       REAL(KIND(1D0)), INTENT(OUT)::VegFraction
       REAL(KIND(1D0)), INTENT(OUT)::ImpervFraction
       REAL(KIND(1D0)), INTENT(OUT)::PervFraction
       REAL(KIND(1D0)), INTENT(OUT)::NonWaterFraction
       vegfraction = sfr(conifsurf) + sfr(decidsurf) + sfr(grasssurf)
       impervfraction = sfr(pavsurf) + sfr(bldgsurf)
       pervfraction = 1 - impervfraction
       nonwaterfraction = 1 - sfr(watersurf)
References allocatearray::bldgsurf, allocatearray::conifsurf, allocatearray::decidsurf, allocatearray::grasssurf, allocatearray::pavsurf, and allocatearray::watersurf.
Referenced by suews_cal_main().
suews_cal_water()
subroutine suews_driver::suews_cal_water (integer, intent(in) Diagnose, integer, intent(in) snowUse, real(kind(1d0)), intent(in) NonWaterFraction, real(kind(1d0)), intent(in) addPipes, real(kind(1d0)), intent(in) addImpervious, real(kind(1d0)), intent(in) addVeg, real(kind(1d0)), intent(in) addWaterBody, real(kind(1d0)), dimension(nsurf), intent(in) state_id, real(kind(1d0)), dimension(nsurf), intent(in) soilstore_id, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(6, nsurf), intent(in) StoreDrainPrm, real(kind(1d0)), dimension(nsurf + 1, nsurf - 1), intent(in) WaterDist, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), intent(out) drain_per_tstep, real(kind(1d0)), dimension(nsurf), intent(out) drain, real(kind(1d0)), dimension(nsurf), intent(out) AddWaterRunoff, real(kind(1d0)), intent(out) AdditionalWater, real(kind(1d0)), intent(out) runoffPipes, real(kind(1d0)), intent(out) runoff_per_interval, real(kind(1d0)), dimension(nsurf), intent(out) AddWater, real(kind(1d0)), dimension(nsurf), intent(out) stateOld, real(kind(1d0)), dimension(nsurf), intent(out) soilstoreOld)
Definition at line 1336 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       ! INTEGER,PARAMETER :: nsurf=7! number of surface types
       ! INTEGER,PARAMETER ::WaterSurf = 7
       INTEGER, INTENT(in) ::Diagnose
       INTEGER, INTENT(in) ::snowUse
       REAL(KIND(1d0)), INTENT(in)::NonWaterFraction
       REAL(KIND(1d0)), INTENT(in)::addPipes
       REAL(KIND(1d0)), INTENT(in)::addImpervious
       REAL(KIND(1d0)), INTENT(in)::addVeg
       REAL(KIND(1d0)), INTENT(in)::addWaterBody
       REAL(KIND(1d0)), INTENT(in)::nsh_real !nsh cast as a real for use in calculations
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)          ::state_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)          ::soilstore_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)          ::sfr
       REAL(KIND(1d0)), DIMENSION(6, nsurf), INTENT(in)        ::StoreDrainPrm
       REAL(KIND(1d0)), DIMENSION(nsurf + 1, nsurf - 1), INTENT(in)::WaterDist
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out):: drain         !Drainage of surface type "is" [mm]
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out):: AddWaterRunoff!Fraction of water going to runoff/sub-surface soil (WGWaterDist) [-]
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out):: AddWater      !water from other surfaces (WGWaterDist in SUEWS_ReDistributeWater.f95) [mm]
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out):: stateOld
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out):: soilstoreOld
       REAL(KIND(1d0)), INTENT(out)::drain_per_tstep
       REAL(KIND(1d0)), INTENT(out)::AdditionalWater
       REAL(KIND(1d0)), INTENT(out)::runoffPipes
       REAL(KIND(1d0)), INTENT(out)::runoff_per_interval
       INTEGER:: is
       ! Retain previous surface state_id and soil moisture state_id
       stateold = state_id     !state_id of each surface [mm] for the previous timestep
       soilstoreold = soilstore_id !Soil moisture of each surface [mm] for the previous timestep
       !============= Grid-to-grid runoff =============
       ! Calculate additional water coming from other grids
       ! i.e. the variables addImpervious, addVeg, addWaterBody, addPipes
       !call RunoffFromGrid(GridFromFrac)  !!Need to code between-grid water transfer
       ! Sum water coming from other grids (these are expressed as depths over the whole surface)
       additionalwater = addpipes + addimpervious + addveg + addwaterbody  ![mm]
       ! Initialise runoff in pipes
       runoffpipes = addpipes !Water flowing in pipes from other grids. QUESTION: No need for scaling?
       !! CHECK p_i
       runoff_per_interval = addpipes !pipe plor added to total runoff.
       !================== Drainage ===================
       ! Calculate drainage for each soil subsurface (excluding water body)
       IF (diagnose == 1) WRITE (*, *) 'Calling Drainage...'
       IF (nonwaterfraction /= 0) THEN !Soil states only calculated if soil exists. LJ June 2017
          DO is = 1, nsurf - 1
             CALL drainage( &
                is, &! input:
                state_id(is), &
                storedrainprm(6, is), &
                storedrainprm(2, is), &
                storedrainprm(3, is), &
                storedrainprm(4, is), &
                nsh_real, &
                drain(is))! output
             ! !HCW added and changed to StoreDrainPrm(6,is) here 20 Feb 2015
             ! drain_per_tstep=drain_per_tstep+(drain(is)*sfr(is)/NonWaterFraction)   !No water body included
          ENDDO
          drain_per_tstep = dot_product(drain(1:nsurf - 1), sfr(1:nsurf - 1))/nonwaterfraction !No water body included
       ELSE
          drain(1:nsurf - 1) = 0
          drain_per_tstep = 0
       ENDIF
       drain(watersurf) = 0  ! Set drainage from water body to zero
       ! Distribute water within grid, according to WithinGridWaterDist matrix (Cols 1-7)
       IF (diagnose == 1) WRITE (*, *) 'Calling ReDistributeWater...'
       ! CALL ReDistributeWater
       !Calculates AddWater(is)
       CALL redistributewater( &
          snowuse, waterdist, sfr, drain, &! input:
          addwaterrunoff, addwater)! output
References waterdist_module::drainage(), allocatearray::nsurf, waterdist_module::redistributewater(), and allocatearray::watersurf.
Referenced by suews_cal_main().
suews_init_qh()
subroutine suews_driver::suews_init_qh (real(kind(1d0)), intent(in) qh_obs, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) h_mod, real(kind(1d0)), intent(in) qn1, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(out) H_init)
Definition at line 1428 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL(KIND(1d0)), INTENT(in)::qh_obs
       REAL(KIND(1d0)), INTENT(in)::avdens
       REAL(KIND(1d0)), INTENT(in)::avcp
       REAL(KIND(1d0)), INTENT(in)::h_mod
       REAL(KIND(1d0)), INTENT(in)::qn1
       REAL(KIND(1d0)), INTENT(in)::dectime
       REAL(KIND(1d0)), INTENT(out)::H_init
       REAL(KIND(1d0)), PARAMETER::NAN = -999
       INTEGER, PARAMETER::notUsedI = -999
       ! Calculate kinematic heat flux (w'T') from sensible heat flux [W m-2] from observed data (if available) or LUMPS
       IF (qh_obs /= nan) THEN   !if(qh_obs/=NAN) qh=qh_obs   !Commented out by HCW 04 Mar 2015
          h_init = qh_obs/(avdens*avcp)  !Use observed value
       ELSE
          IF (h_mod /= nan) THEN
             h_init = h_mod/(avdens*avcp)   !Use LUMPS value
          ELSE
             h_init = (qn1*0.2)/(avdens*avcp)   !If LUMPS has had a problem, we still need a value
             CALL errorhint(38, 'LUMPS unable to calculate realistic value for H_mod.', h_mod, dectime, notusedi)
          ENDIF
       ENDIF
References errorhint().
Referenced by diagsfc(), and suews_cal_resistance().
suews_update_output()
subroutine suews_driver::suews_update_output (integer, intent(in) SnowUse, integer, intent(in) storageheatmethod, integer, intent(in) ReadLinesMetdata, integer, intent(in) NumberOfGrids, integer, intent(in) ir, integer, intent(in) gridiv, real(kind(1d0)), dimension(5), intent(in) datetimeLine, real(kind(1d0)), dimension(ncolumnsdataoutsuews - 5), intent(in) dataOutLineSUEWS, real(kind(1d0)), dimension(ncolumnsdataoutsnow - 5), intent(in) dataOutLineSnow, real(kind(1d0)), dimension(ncolumnsdataoutestm - 5), intent(in) dataOutLineESTM, real(kind(1d0)), dimension(ncolumnsdataoutrsl - 5), intent(in) dataoutLineURSL, real(kind(1d0)), dimension(readlinesmetdata, ncolumnsdataoutsuews, numberofgrids), intent(inout) dataOutSUEWS, real(kind(1d0)), dimension(readlinesmetdata, ncolumnsdataoutsnow, numberofgrids), intent(inout) dataOutSnow, real(kind(1d0)), dimension(readlinesmetdata, ncolumnsdataoutestm, numberofgrids), intent(inout) dataOutESTM, real(kind(1d0)), dimension(readlinesmetdata, ncolumnsdataoutrsl, numberofgrids), intent(inout) dataOutRSL)
Definition at line 2149 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in) ::ReadLinesMetdata
       INTEGER, INTENT(in) ::NumberOfGrids
       INTEGER, INTENT(in) ::Gridiv
       INTEGER, INTENT(in) ::SnowUse
       INTEGER, INTENT(in) ::storageheatmethod
       INTEGER, INTENT(in) ::ir
       REAL(KIND(1d0)), DIMENSION(5), INTENT(in) :: datetimeLine
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutSUEWS - 5), INTENT(in) :: dataOutLineSUEWS
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutESTM - 5), INTENT(in) :: dataOutLineESTM
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutSnow - 5), INTENT(in) :: dataOutLineSnow
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutRSL - 5), INTENT(in) :: dataoutLineURSL
       REAL(KIND(1d0)), INTENT(inout) :: dataOutSUEWS(ReadLinesMetdata, ncolumnsDataOutSUEWS, NumberOfGrids)
       REAL(KIND(1d0)), INTENT(inout) :: dataOutSnow(ReadLinesMetdata, ncolumnsDataOutSnow, NumberOfGrids)
       REAL(KIND(1d0)), INTENT(inout) :: dataOutESTM(ReadLinesMetdata, ncolumnsDataOutESTM, NumberOfGrids)
       REAL(KIND(1d0)), INTENT(inout) :: dataOutRSL(ReadLinesMetdata, ncolumnsDataOutRSL, NumberOfGrids)
       !====================== update output arrays ==============================
       !Define the overall output matrix to be printed out step by step
       dataoutsuews(ir, 1:ncolumnsdataoutsuews, gridiv) = [datetimeline, set_nan(dataoutlinesuews)]
       dataoutrsl(ir, 1:ncolumnsdataoutrsl, gridiv) = [datetimeline, set_nan(dataoutlineursl)]
       ! ! set invalid values to NAN
       ! dataOutSUEWS(ir,6:ncolumnsDataOutSUEWS,Gridiv)=set_nan(dataOutSUEWS(ir,6:ncolumnsDataOutSUEWS,Gridiv))
       IF (snowuse == 1) THEN
          dataoutsnow(ir, 1:ncolumnsdataoutsnow, gridiv) = [datetimeline, set_nan(dataoutlinesnow)]
       END IF
       IF (storageheatmethod == 4) THEN
          dataoutestm(ir, 1:ncolumnsdataoutestm, gridiv) = [datetimeline, set_nan(dataoutlineestm)]
       END IF
       !====================update output arrays end==============================
References set_nan().
Referenced by suews_cal_multitsteps(), and suews_calculations().
suews_update_outputline()
subroutine suews_driver::suews_update_outputline (real(kind(1d0)), intent(in) AdditionalWater, real(kind(1d0)), dimension(nsurf), intent(in) alb, real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) avU10_ms, real(kind(1d0)), intent(in) azimuth, real(kind(1d0)), intent(in) chSnow_per_interval, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(in) drain_per_tstep, real(kind(1d0)), intent(in) E_mod, real(kind(1d0)), intent(in) ev_per_tstep, real(kind(1d0)), intent(in) ext_wu, real(kind(1d0)), intent(in) Fc, real(kind(1d0)), intent(in) Fc_build, real(kind(1d0)), intent(in) fcld, real(kind(1d0)), intent(in) Fc_metab, real(kind(1d0)), intent(in) Fc_photo, real(kind(1d0)), intent(in) Fc_respi, real(kind(1d0)), intent(in) Fc_point, real(kind(1d0)), intent(in) Fc_traff, real(kind(1d0)), intent(in) FlowChange, real(kind(1d0)), intent(in) h_mod, integer, intent(in) id, integer, intent(in) imin, real(kind(1d0)), intent(in) int_wu, integer, intent(in) it, integer, intent(in) iy, real(kind(1d0)), intent(in) kup, real(kind(1d0)), dimension(nvegsurf), intent(in) LAI_id, real(kind(1d0)), intent(in) ldown, real(kind(1d0)), intent(in) l_mod, real(kind(1d0)), intent(in) lup, real(kind(1d0)), intent(in) mwh, real(kind(1d0)), intent(in) MwStore, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), intent(in) NWstate_per_tstep, real(kind(1d0)), intent(in) Precip, real(kind(1d0)), intent(in) q2_gkg, real(kind(1d0)), intent(in) qeOut, real(kind(1d0)), intent(in) qf, real(kind(1d0)), intent(in) qh, real(kind(1d0)), intent(in) qh_resist, real(kind(1d0)), intent(in) Qm, real(kind(1d0)), intent(in) QmFreez, real(kind(1d0)), intent(in) QmRain, real(kind(1d0)), intent(in) qn1, real(kind(1d0)), intent(in) qn1_S, real(kind(1d0)), intent(in) qn1_snowfree, real(kind(1d0)), intent(in) qs, real(kind(1d0)), intent(in) RA, real(kind(1d0)), intent(in) resistsurf, real(kind(1d0)), intent(in) RH2, real(kind(1d0)), intent(in) runoffAGimpervious, real(kind(1d0)), intent(in) runoffAGveg, real(kind(1d0)), intent(in) runoff_per_tstep, real(kind(1d0)), intent(in) runoffPipes, real(kind(1d0)), intent(in) runoffSoil_per_tstep, real(kind(1d0)), intent(in) runoffWaterBody, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), intent(in) smd, real(kind(1d0)), dimension(nsurf), intent(in) smd_nsurf, real(kind(1d0)), intent(in) SnowAlb, real(kind(1d0)), dimension(2), intent(in) SnowRemoval, real(kind(1d0)), dimension(nsurf), intent(in) state_id, real(kind(1d0)), intent(in) state_per_tstep, real(kind(1d0)), intent(in) surf_chang_per_tstep, real(kind(1d0)), intent(in) swe, real(kind(1d0)), intent(in) t2_C, real(kind(1d0)), intent(in) tskin_C, real(kind(1d0)), intent(in) tot_chang_per_tstep, real(kind(1d0)), intent(in) tsurf, real(kind(1d0)), intent(in) UStar, real(kind(1d0)), intent(in) wu_DecTr, real(kind(1d0)), intent(in) wu_EveTr, real(kind(1d0)), intent(in) wu_Grass, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) zdm, real(kind(1d0)), intent(in) zenith_deg, real(kind(1d0)), dimension(5), intent(out) datetimeLine, real(kind(1d0)), dimension(ncolumnsdataoutsuews - 5), intent(out) dataOutLineSUEWS)
Definition at line 1963 of file suews_ctrl_driver.f95.
       IMPLICIT NONE
       REAL(KIND(1d0)), PARAMETER :: NAN = -999
       INTEGER, INTENT(in) :: iy
       ! INTEGER,INTENT(in) :: iy_prev_t
       INTEGER, INTENT(in) :: id
       ! INTEGER,INTENT(in) :: id_prev_t
       INTEGER, INTENT(in) :: it
       INTEGER, INTENT(in) :: imin
       REAL(KIND(1d0)), INTENT(in) :: AdditionalWater
       REAL(KIND(1d0)), INTENT(in) :: alb(nsurf)
       REAL(KIND(1d0)), INTENT(in) :: avkdn
       REAL(KIND(1d0)), INTENT(in) :: avU10_ms
       REAL(KIND(1d0)), INTENT(in) :: azimuth
       REAL(KIND(1d0)), INTENT(in) :: chSnow_per_interval
       REAL(KIND(1d0)), INTENT(in) :: dectime
       REAL(KIND(1d0)), INTENT(in) :: drain_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: E_mod
       REAL(KIND(1d0)), INTENT(in) :: ev_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: ext_wu
       REAL(KIND(1d0)), INTENT(in) :: Fc
       REAL(KIND(1d0)), INTENT(in) :: Fc_build
       REAL(KIND(1d0)), INTENT(in) :: Fc_metab
       REAL(KIND(1d0)), INTENT(in) :: Fc_photo
       REAL(KIND(1d0)), INTENT(in) :: Fc_respi
       REAL(KIND(1d0)), INTENT(in) :: Fc_point
       REAL(KIND(1d0)), INTENT(in) :: Fc_traff
       REAL(KIND(1d0)), INTENT(in) :: fcld
       REAL(KIND(1d0)), INTENT(in) :: FlowChange
       REAL(KIND(1d0)), INTENT(in) :: h_mod
       REAL(KIND(1d0)), INTENT(in) :: int_wu
       REAL(KIND(1d0)), INTENT(in) :: kup
       REAL(KIND(1d0)), INTENT(in) :: l_mod
       REAL(KIND(1d0)), INTENT(in) :: LAI_id(nvegsurf)
       REAL(KIND(1d0)), INTENT(in) :: ldown
       REAL(KIND(1d0)), INTENT(in) :: lup
       REAL(KIND(1d0)), INTENT(in) :: mwh
       REAL(KIND(1d0)), INTENT(in) :: MwStore
       REAL(KIND(1d0)), INTENT(in) :: nsh_real
       REAL(KIND(1d0)), INTENT(in) :: NWstate_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: Precip
       REAL(KIND(1d0)), INTENT(in) :: q2_gkg
       REAL(KIND(1d0)), INTENT(in) :: qeOut
       REAL(KIND(1d0)), INTENT(in) :: qf
       REAL(KIND(1d0)), INTENT(in) :: qh
       REAL(KIND(1d0)), INTENT(in) :: qh_resist
       REAL(KIND(1d0)), INTENT(in) :: Qm
       REAL(KIND(1d0)), INTENT(in) :: QmFreez
       REAL(KIND(1d0)), INTENT(in) :: QmRain
       REAL(KIND(1d0)), INTENT(in) :: qn1
       REAL(KIND(1d0)), INTENT(in) :: qn1_S
       REAL(KIND(1d0)), INTENT(in) :: qn1_snowfree
       REAL(KIND(1d0)), INTENT(in) :: qs
       REAL(KIND(1d0)), INTENT(in) :: RA
       REAL(KIND(1d0)), INTENT(in) :: resistsurf
       REAL(KIND(1d0)), INTENT(in) :: RH2
       REAL(KIND(1d0)), INTENT(in) :: runoff_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: runoffAGimpervious
       REAL(KIND(1d0)), INTENT(in) :: runoffAGveg
       REAL(KIND(1d0)), INTENT(in) :: runoffPipes
       REAL(KIND(1d0)), INTENT(in) :: runoffSoil_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: runoffWaterBody
       REAL(KIND(1d0)), INTENT(in) :: sfr(nsurf)
       REAL(KIND(1d0)), INTENT(in) :: smd
       REAL(KIND(1d0)), INTENT(in) :: smd_nsurf(nsurf)
       REAL(KIND(1d0)), INTENT(in) :: SnowAlb
       REAL(KIND(1d0)), INTENT(in) :: SnowRemoval(2)
       REAL(KIND(1d0)), INTENT(in) :: state_id(nsurf)
       REAL(KIND(1d0)), INTENT(in) :: state_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: surf_chang_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: swe
       REAL(KIND(1d0)), INTENT(in) :: t2_C
       REAL(KIND(1d0)), INTENT(in) :: tskin_C
       REAL(KIND(1d0)), INTENT(in) :: tot_chang_per_tstep
       REAL(KIND(1d0)), INTENT(in) :: tsurf
       REAL(KIND(1d0)), INTENT(in) :: UStar
       REAL(KIND(1d0)), INTENT(in) :: wu_DecTr
       REAL(KIND(1d0)), INTENT(in) :: wu_EveTr
       REAL(KIND(1d0)), INTENT(in) :: wu_Grass
       REAL(KIND(1d0)), INTENT(in) :: z0m
       REAL(KIND(1d0)), INTENT(in) :: zdm
       REAL(KIND(1d0)), INTENT(in) :: zenith_deg
       REAL(KIND(1D0)), DIMENSION(5), INTENT(OUT)::datetimeLine
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutSUEWS - 5), INTENT(out) :: dataOutLineSUEWS
       ! REAL(KIND(1d0)),DIMENSION(ncolumnsDataOutSnow-5),INTENT(out) :: dataOutLineSnow
       ! REAL(KIND(1d0)),DIMENSION(ncolumnsDataOutESTM-5),INTENT(out) :: dataOutLineESTM
       ! INTEGER:: is
       REAL(KIND(1d0)):: LAI_wt
       REAL(KIND(1d0)):: RH2_pct ! RH2 in percentage
       ! the variables below with '_x' endings stand for 'exported' values
       REAL(KIND(1d0))::ResistSurf_x
       REAL(KIND(1d0))::l_mod_x
       REAL(KIND(1d0))::bulkalbedo
       REAL(KIND(1d0))::smd_nsurf_x(nsurf)
       REAL(KIND(1d0))::state_x(nsurf)
       !=====================================================================
       !====================== Prepare data for output ======================
       ! values outside of reasonable range are set as NAN-like numbers. TS 10 Jun 2018
       ! Remove non-existing surface type from surface and soil outputs   ! Added back in with NANs by HCW 24 Aug 2016
       state_x = unpack(spread(nan, dim=1, ncopies=SIZE(sfr)), mask=(sfr < 0.00001), field=state_id)
       smd_nsurf_x = unpack(spread(nan, dim=1, ncopies=SIZE(sfr)), mask=(sfr < 0.00001), field=smd_nsurf)
       resistsurf_x = min(9999., resistsurf)
       l_mod_x = max(min(9999., l_mod), -9999.)
       ! Calculate areally-weighted LAI
       ! IF(iy == (iy_prev_t  +1) .AND. (id-1) == 0) THEN   !Check for start of next year and avoid using LAI(id-1) as this is at the start of the year
       !    LAI_wt=DOT_PRODUCT(LAI(id_prev_t,:),sfr(1+2:nvegsurf+2))
       ! ELSE
       !    LAI_wt=DOT_PRODUCT(LAI(id-1,:),sfr(1+2:nvegsurf+2))
       ! ENDIF
       lai_wt = dot_product(lai_id(:), sfr(1 + 2:nvegsurf + 2))
       ! Calculate areally-weighted albedo
       bulkalbedo = dot_product(alb, sfr)
       ! convert RH2 to a percentage form
       rh2_pct = rh2*100.0
       ! NB: this part needs to be reconsidered for calculation logic. TS, 27 Sep 2018
       ! TODO: this part should be reconnected to an improved CBL interface. TS 10 Jun 2018
       ! ! Save qh and qe for CBL in next iteration
       ! IF(Qh_choice==1) THEN   !use QH and QE from SUEWS
       !    qhforCBL(Gridiv) = qh
       !    qeforCBL(Gridiv) = qeOut
       ! ELSEIF(Qh_choice==2)THEN   !use QH and QE from LUMPS
       !    qhforCBL(Gridiv) = h_mod
       !    qeforCBL(Gridiv) = e_mod
       ! ELSEIF(qh_choice==3)THEN  !use QH and QE from OBS
       !    qhforCBL(Gridiv) = qh_obs
       !    qeforCBL(Gridiv) = qe_obs
       !    IF(qh_obs<-900.OR.qe_obs<-900)THEN  ! observed data has a problem
       !       CALL ErrorHint(22,'Unrealistic observed qh or qe_value.',qh_obs,qe_obs,qh_choice)
       !    ENDIF
       ! ENDIF
       !====================== update output line ==============================
       ! date & time:
       datetimeline = [ &
                      REAL(iy, KIND(1D0)), REAL(id, KIND(1D0)), &
                      REAL(it, KIND(1D0)), REAL(imin, KIND(1D0)), dectime]
       !Define the overall output matrix to be printed out step by step
       dataoutlinesuews = [ &
                          avkdn, kup, ldown, lup, tsurf, &
                          qn1, qf, qs, qh, qeout, &
                          h_mod, e_mod, qh_resist, &
                          precip, ext_wu, ev_per_tstep, runoff_per_tstep, tot_chang_per_tstep, &
                          surf_chang_per_tstep, state_per_tstep, nwstate_per_tstep, drain_per_tstep, smd, &
                          flowchange/nsh_real, additionalwater, &
                          runoffsoil_per_tstep, runoffpipes, runoffagimpervious, runoffagveg, runoffwaterbody, &
                          int_wu, wu_evetr, wu_dectr, wu_grass, &
                          smd_nsurf_x(1:nsurf - 1), &
                          state_x(1:nsurf), &
                          zenith_deg, azimuth, bulkalbedo, fcld, &
                          lai_wt, z0m, zdm, &
                          ustar, l_mod, ra, resistsurf, &
                          fc, &
                          fc_photo, fc_respi, fc_metab, fc_traff, fc_build, fc_point, &
                          qn1_snowfree, qn1_s, snowalb, &
                          qm, qmfreez, qmrain, swe, mwh, mwstore, chsnow_per_interval, &
                          snowremoval(1:2), &
                          tskin_c, t2_c, q2_gkg, avu10_ms, rh2_pct & ! surface-level diagonostics
                          ]
       ! set invalid values to NAN
       ! dataOutLineSUEWS = set_nan(dataOutLineSUEWS)
       !====================update output line end==============================
Referenced by suews_cal_main().