SUEWS: wherewhen Module Reference
wherewhen Module Reference
Variables
integer gridid
character(len=10) gridid_text
character(len=15) datetime
Variable Documentation
datetime
character(len=15) wherewhen::datetime
Definition at line 2280 of file suews_ctrl_const.f95.
    CHARACTER(LEN=15):: datetime  ! YYYY DOY HH MM
Referenced by suews_program().
gridid
integer wherewhen::gridid
Definition at line 2278 of file suews_ctrl_const.f95.
    INTEGER:: GridID   !Grid number (as specified in SUEWS_SiteSelect.txt)
Referenced by suews_program(), and suews_translate().
gridid_text
character(len=10) wherewhen::gridid_text
Definition at line 2279 of file suews_ctrl_const.f95.
    CHARACTER(LEN=10):: GridID_text !Grid number as a text string
Referenced by suews_program(), and suews_translate().