SUEWS: snow_module Module Reference
snow_module Module Reference
Functions/Subroutines
subroutine snow_cal_meltheat (snowUse, lvS_J_kg, lv_J_kg, tstep_real, RadMeltFact, TempMeltFact, SnowAlbMax, SnowDensMin, Temp_C, Precip, PrecipLimit, PrecipLimitAlb, nsh_real, sfr, Tsurf_ind, Tsurf_ind_snow, state_id, qn1_ind_snow, kup_ind_snow, SnowWater, deltaQi, SnowPack, snowFrac, SnowAlb, SnowDens, SnowfallCum, mwh, fwh, Qm, QmFreez, QmRain, veg_fr, snowCalcSwitch, Qm_melt, Qm_freezState, Qm_rain, FreezMelt, FreezState, FreezStateVol, rainOnSnow, SnowDepth, mw_ind, dataOutLineSnow)
subroutine meltheat (bldgsurf, nsurf, PavSurf, WaterSurf, lvS_J_kg, lv_J_kg, tstep_real, RadMeltFact, TempMeltFact, SnowAlbMax, SnowDensMin, Temp_C, Precip, PrecipLimit, PrecipLimitAlb, nsh_real, waterdens, sfr, Tsurf_ind, state_id, qn1_ind_snow, SnowWater, deltaQi, SnowPack, snowFrac, SnowAlb, SnowDens, SnowfallCum, mwh, fwh, Qm, QmFreez, QmRain, snowCalcSwitch, Qm_melt, Qm_freezState, Qm_rain, FreezMelt, FreezState, FreezStateVol, rainOnSnow, SnowDepth, mw_ind)
subroutine snowcalc (tstep, imin, it, dectime, is, EvapMethod, CRWmin, CRWmax, nsh_real, lvS_J_kg, lv_j_kg, avdens, avRh, Press_hPa, Temp_C, RAsnow, psyc_hPa, avcp, sIce_hPa, PervFraction, vegfraction, addimpervious, vpd_hPa, qn_e, s_hPa, ResistSurf, RA, rb, tlv, snowdensmin, SnowProf_24hr, precip, PipeCapacity, RunoffToWater, addVeg, SnowLimPaved, SnowLimBldg, FlowChange, drain, WetThresh, stateOld, mw_ind, SoilStoreCap, rainonsnow, freezmelt, freezstate, freezstatevol, Qm_Melt, Qm_rain, Tsurf_ind, sfr, dayofWeek_id, StoreDrainPrm, SnowPackLimit, AddWater, addwaterrunoff, soilstore_id, SnowPack, SurplusEvap, snowFrac, SnowWater, iceFrac, SnowDens, runoffAGimpervious, runoffAGveg, surplusWaterBody, rss_nsurf, runoffSnow, runoff, runoffSoil, chang, changSnow, SnowToSurf, state_id, ev_snow, SnowDepth, SnowRemoval, swe, ev, chSnow_tot, ev_tot, qe_tot, runoff_tot, surf_chang_tot, runoffPipes, mwstore, runoffwaterbody)
subroutine evap_suews_snow (Qm, QP, lvS_J_kg, avdens, avRh, Press_hPa, Temp_C, RAsnow, psyc_hPa, tstep, avcp, sIce_hPa, dectime, ev_snow, tlv_sub)
subroutine snowrem (is, PavSurf, BldgSurf, nsurf, snowfrac, sfr, SnowPack, SnowRemoval, SnowLimPaved, SnowLimBldg)
real(kind(1d0)) function snowdepletioncurve (is, swe, sweD)
subroutine veg_fr_snow (sfr, snowFrac, nsurf, veg_fr)
subroutine snowupdate (nsurf, tstep, Temp_C_hr, tau_a, tau_f, tau_r, SnowDensMax, SnowDensMin, SnowAlbMax, SnowAlbMin, SnowPack, SnowAlb, SnowDens)
Function/Subroutine Documentation
evap_suews_snow()
subroutine snow_module::evap_suews_snow (real(kind(1d0)), intent(in) Qm, real(kind(1d0)), intent(in) QP, real(kind(1d0)), intent(in) lvS_J_kg, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avRh, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) RAsnow, real(kind(1d0)), intent(in) psyc_hPa, integer, intent(in) tstep, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) sIce_hPa, real(kind(1d0)), intent(in) dectime, real(kind(1d0)), intent(out) ev_snow, real(kind(1d0)), intent(out) tlv_sub)
Definition at line 1128 of file suews_phys_snow.f95.
       USE meteo, ONLY: sat_vap_pressice
       IMPLICIT NONE
       !INPUT
       REAL(KIND(1d0)), INTENT(in)::Qm        !melt heat,
       REAL(KIND(1d0)), INTENT(in)::QP        !advect. heat
       REAL(KIND(1d0)), INTENT(in)::lvS_J_kg  !latent heat of sublimation
       REAL(KIND(1d0)), INTENT(in)::avdens    !air density
       REAL(KIND(1d0)), INTENT(in)::avRh      !relative humidity
       REAL(KIND(1d0)), INTENT(in)::Press_hPa !air pressure
       REAL(KIND(1d0)), INTENT(in)::Temp_C    !air temperature
       REAL(KIND(1d0)), INTENT(in)::RAsnow    !aerodyn res snow
       REAL(KIND(1d0)), INTENT(in)::psyc_hPa  !psychometric constant
       REAL(KIND(1d0)), INTENT(in)::avcp      !spec. heat,
       REAL(KIND(1d0)), INTENT(in)::sIce_hPa  !satured curve on snow
       REAL(KIND(1d0)), INTENT(in)::dectime
       INTEGER, INTENT(in):: tstep
       REAL(KIND(1d0)), INTENT(out)::ev_snow    !Evaporation
       REAL(KIND(1d0)), INTENT(out)::tlv_sub    !Latent heat for sublimation
       !OTHER VARIABLES
       REAL(KIND(1d0))::e_snow, &     !PM equation obe line
                         sae_snow, &   !s * (Available energy)
                         qe_snow, &    !Latent heat flux
                         vdrcice, &    !Vapour pressure deficit
                         esice_hpa, &  !Saturation vapor pressure over ice
                         eaice_hpa, &  !Vapour pressure
                         tstep_real   !timestep as real
       INTEGER::from = 1
       !-----------------------------------------------------
       tstep_real = real(tstep, kind(1d0))
       sae_snow = sice_hpa*(qp - qm)   !Calculate the driving parameter in calculation of evaporation. Järvi et al. (2015)
       esice_hpa = sat_vap_pressice(temp_c, press_hpa, from, dectime) !Saturation vapor pressure over ice
       eaice_hpa = avrh/100*esice_hpa                       !Vapour pressure of water
       vdrcice = (esice_hpa - eaice_hpa)*avdens*avcp          !Vapour pressure deficit
       tlv_sub = lvs_j_kg/tstep_real                        !Latent heat for sublimation
       e_snow = sae_snow + vdrcice/rasnow                     !PM equation
       qe_snow = e_snow/(sice_hpa + psyc_hpa)                 !Latent heat (W/m^2)
       ev_snow = qe_snow/tlv_sub                            !Evaporation (in mm)
       RETURN
References meteo::sat_vap_pressice().
Referenced by snowcalc().
meltheat()
subroutine snow_module::meltheat (integer, intent(in) bldgsurf, integer, intent(in) nsurf, integer, intent(in) PavSurf, integer, intent(in) WaterSurf, real(kind(1d0)), intent(in) lvS_J_kg, real(kind(1d0)), intent(in) lv_J_kg, real(kind(1d0)), intent(in) tstep_real, real(kind(1d0)), intent(in) RadMeltFact, real(kind(1d0)), intent(in) TempMeltFact, real(kind(1d0)), intent(in) SnowAlbMax, real(kind(1d0)), intent(in) SnowDensMin, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) Precip, real(kind(1d0)), intent(in) PrecipLimit, real(kind(1d0)), intent(in) PrecipLimitAlb, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), intent(in) waterdens, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(in) Tsurf_ind, real(kind(1d0)), dimension(nsurf), intent(in) state_id, real(kind(1d0)), dimension(nsurf), intent(in) qn1_ind_snow, real(kind(1d0)), dimension(nsurf), intent(in) SnowWater, real(kind(1d0)), dimension(nsurf), intent(in) deltaQi, real(kind(1d0)), dimension(nsurf), intent(inout) SnowPack, real(kind(1d0)), dimension(nsurf), intent(inout) snowFrac, real(kind(1d0)), intent(inout) SnowAlb, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens, real(kind(1d0)), intent(inout) SnowfallCum, real(kind(1d0)), intent(out) mwh, real(kind(1d0)), intent(out) fwh, real(kind(1d0)), intent(out) Qm, real(kind(1d0)), intent(out) QmFreez, real(kind(1d0)), intent(out) QmRain, integer, dimension(nsurf), intent(out) snowCalcSwitch, real(kind(1d0)), dimension(nsurf), intent(out) Qm_melt, real(kind(1d0)), dimension(nsurf), intent(out) Qm_freezState, real(kind(1d0)), dimension(nsurf), intent(out) Qm_rain, real(kind(1d0)), dimension(nsurf), intent(out) FreezMelt, real(kind(1d0)), dimension(nsurf), intent(out) FreezState, real(kind(1d0)), dimension(nsurf), intent(out) FreezStateVol, real(kind(1d0)), dimension(nsurf), intent(out) rainOnSnow, real(kind(1d0)), dimension(nsurf), intent(out) SnowDepth, real(kind(1d0)), dimension(nsurf), intent(out) mw_ind)
Definition at line 207 of file suews_phys_snow.f95.
       IMPLICIT NONE
       !These are input to the module
       INTEGER, INTENT(in)::bldgsurf
       INTEGER, INTENT(in)::nsurf
       INTEGER, INTENT(in)::PavSurf
       INTEGER, INTENT(in)::WaterSurf
       REAL(KIND(1d0)), INTENT(in)::lvS_J_kg
       REAL(KIND(1d0)), INTENT(in)::lv_J_kg
       REAL(KIND(1d0)), INTENT(in)::tstep_real
       REAL(KIND(1d0)), INTENT(in)::RadMeltFact
       REAL(KIND(1d0)), INTENT(in)::TempMeltFact
       REAL(KIND(1d0)), INTENT(in)::SnowAlbMax
       REAL(KIND(1d0)), INTENT(in)::SnowDensMin
       REAL(KIND(1d0)), INTENT(in)::Temp_C
       REAL(KIND(1d0)), INTENT(in)::Precip
       REAL(KIND(1d0)), INTENT(in)::PrecipLimit
       REAL(KIND(1d0)), INTENT(in)::PrecipLimitAlb
       REAL(KIND(1d0)), INTENT(in)::nsh_real
       REAL(KIND(1d0)), INTENT(in)::waterdens
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Tsurf_ind
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::state_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::qn1_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::SnowWater
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::deltaQi
       !Input and output as this is updated in this subroutine
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowPack
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::snowFrac
       REAL(KIND(1d0)), INTENT(inout)::SnowAlb
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowDens
       REAL(KIND(1d0)), INTENT(inout)::SnowfallCum
       !Output:
       REAL(KIND(1d0)), INTENT(out)::mwh
       REAL(KIND(1d0)), INTENT(out)::fwh
       REAL(KIND(1d0)), INTENT(out)::Qm
       REAL(KIND(1d0)), INTENT(out)::QmFreez
       REAL(KIND(1d0)), INTENT(out)::QmRain
       !Output, dimension nsurf
       INTEGER, DIMENSION(nsurf), INTENT(out)::snowCalcSwitch
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::Qm_melt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::Qm_freezState
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::Qm_rain
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::FreezMelt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::FreezState
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::FreezStateVol
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::rainOnSnow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::SnowDepth
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::mw_ind
       ! local variables:
       REAL(KIND(1d0))::AdjMeltFact
       REAL(KIND(1d0))::Watfreeze
       REAL(KIND(1d0)), PARAMETER::cw = 4190  !,ci=2090   !Specific heat capacity of water
       INTEGER::is, xx
       !Initialize snow variables
       mwh = 0 !Initialize snow melt and heat related to snowmelt
       fwh = 0
       qm = 0
       qmfreez = 0
       qmrain = 0
       snowcalcswitch = 0
       qm_melt = 0
       qm_freezstate = 0
       qm_rain = 0
       freezmelt = 0
       freezstate = 0
       freezstatevol = 0
       rainonsnow = 0
       snowdepth = 0
       mw_ind = 0
       !===dummy calculations===
       xx = bldgsurf
       xx = pavsurf
       !===dummy calculations end===
       !=========================================================================================
       DO is = 1, nsurf  !Go each surface type through
          IF (sfr(is) /= 0) THEN  !If surface type existing,
             IF (snowpack(is) > 0) THEN  !If SnowPack existing, calculate meltwater related water flows
                snowdepth(is) = (snowpack(is)/1000)*waterdens/snowdens(is) !Snow depth in m
                !Calculate meltwater related water flows with hourly degree-day method.
                !These are for snow melting
                IF (temp_c >= 0) THEN
                   IF (qn1_ind_snow(is) < 0) THEN
                      mw_ind(is) = tempmeltfact*temp_c             !(mm C−1 h−1)*(C) = in mm h-1
                   ELSE
                      mw_ind(is) = radmeltfact*(qn1_ind_snow(is))  !(mm m2 W−1 h−1)*(W m-2)= mm h-1 ??
                   ENDIF
                ELSE  !Freezing equations
                   adjmeltfact = 1  !Relationship between the temperature melt and freezing factors
                   mw_ind(is) = tempmeltfact*temp_c*adjmeltfact ! in mm h-1
                ENDIF
                !Previous equation give the hourly values, divide these with the timestep number
                mw_ind(is) = mw_ind(is)/nsh_real
                IF (mw_ind(is) > snowpack(is)) mw_ind(is) = snowpack(is)!Limited by the previous timestep SnowPack
                !-----------------------------------------------------
                ! Heat consumed to snowmelt/refreezing within Tstep.
                ! Converted from mm nsh-1 to mm nsh-1 and to m s-1
                qm_melt(is) = waterdens*((mw_ind(is)/tstep_real)/1000)*(lvs_j_kg - lv_j_kg)
                !If melt is negative this means freezing water in the SnowPack
                IF (mw_ind(is) < 0) THEN
                   freezmelt(is) = -mw_ind(is) !Save this to variable FreezMelt
                   mw_ind(is) = 0
                   !Freezing water cannot exceed meltwater store
                   IF (freezmelt(is) > snowwater(is)) freezmelt(is) = snowwater(is)
                   !Recalculate melt related energy
                   qm_melt(is) = waterdens*((-freezmelt(is)/tstep_real)/1000)*(lvs_j_kg - lv_j_kg)
                ENDIF
                !-----------------------------------------------------
                ! If air temperature is above zero, precipitation causes advective heat to the
                ! SnowPack. Eq (23) in Sun et al., 1999
                ! Calculation done at resolution of the model timestep
                IF (temp_c >= preciplimit .AND. precip > 0) THEN
                   qm_rain(is) = waterdens*cw*(temp_c - preciplimit)*(precip*0.001/tstep_real)  !in W m-2
                   IF (qm_rain(is) < 0) THEN !Can only be positive
                      qm_rain(is) = 0
                   ELSE
                      rainonsnow(is) = precip !Save information on the rain on snow event
                   ENDIF
                ENDIF
             ENDIF !End if SnowPack
             !=================================================================
             !Freeze surface water state_id if cold enough.
             IF (tsurf_ind(is) < 0 .AND. state_id(is) > 0) THEN
                snowcalcswitch(is) = 1 !If water on ground this forms ice and snow calculations are made
                !Other surfaces than water treated first
                IF (is /= watersurf) THEN
                   !FreezState(is) = state_id(is)
                   !Previously all state_id could freeze in 5-min timestep. Now we calculate how much water
                   !can freeze in a timestep based on the same temperature freezing fraction.
                   freezstate(is) = -tempmeltfact*tsurf_ind(is)/nsh_real
                   !The amount of freezing water cannot be greater than the surface state_id
                   IF (freezstate(is) > state_id(is)) freezstate(is) = state_id(is)
                   IF (snowpack(is) == 0 .OR. snowfrac(is) == 0) THEN !SnowPack forms
                      freezstatevol(is) = freezstate(is)
                   ELSE                                         !There is snow already on ground
                      freezstatevol(is) = freezstate(is)*(1 - snowfrac(is))/snowfrac(is)
                   ENDIF
                   ! If the amount of freezing water is very small and there is state_id left to the ground
                   ! no freezing of water will take place
                   IF (freezstatevol(is) < 0.00000000001 .AND. freezstate(is) < state_id(is)) THEN
                      freezstate(is) = 0
                      freezstatevol(is) = 0
                   ENDIF
                   !Calculate the heat exchange in W m-2
                   qm_freezstate(is) = -waterdens*(freezstate(is)/tstep_real/1000)*(lvs_j_kg - lv_j_kg)
                   !Water surface separately
                ELSE
                   !Calculate average value how much water can freeze above the water areas
                   !Equation is -hA(T-T0) = rhoV(Cp+dT +Lf) in 5-min timestep
                   !h=convective heat trasnfer,A, area of water,rwo water density,V volume, dT temperature difference
                   !before and end of the 5-min period. dT equals zero, h=100 and when multiplied with Area, the equation
                   !simplyfies to the this. LJ 14 July 2015
                   watfreeze = 100*(0 - temp_c)/(waterdens*(lvs_j_kg - lv_j_kg))
                   freezstate(is) = watfreeze
                   qm_freezstate(is) = -waterdens*(watfreeze/tstep_real/1000)*(lvs_j_kg - lv_j_kg)
                ENDIF
             ENDIF
             !======================================================================
             ! Define if any snowmelt calculations are made: SnowPack existing,
             ! freezing occuring on ground or from precip
             IF (is /= watersurf) THEN
                IF (snowpack(is) > 0 .OR. (precip > 0 .AND. tsurf_ind(is) < 0)) THEN
                   snowcalcswitch(is) = 1
                ENDIF
             ELSE       !Water surface separately
                IF (snowpack(watersurf) > 0 .OR. freezstate(watersurf) > 0) THEN
                   snowcalcswitch(watersurf) = 1
                ENDIF
             ENDIF
             !Update snow density of each surface
             IF (precip > 0 .AND. tsurf_ind(is) < 0 .AND. snowpack(is) > 0) THEN
                snowdens(is) = snowdens(is)*snowpack(is)/(snowpack(is) + precip) + snowdensmin*precip/(snowpack(is) + precip)
             ENDIF
             !Weighted variables for the whole area
             mwh = mwh + mw_ind(is)*sfr(is)*snowfrac(is)        !Snowmelt
             fwh = fwh + freezmelt(is)*sfr(is)*snowfrac(is)     !Freezing water
             qm = qm + qm_melt(is)*sfr(is)*snowfrac(is)         !Energy consumed to the melt/freezing.
             qmrain = qmrain + qm_rain(is)*sfr(is)*snowfrac(is) !Rain on snow
             qmfreez = qmfreez + deltaqi(is)*sfr(is)*snowfrac(is) + qm_freezstate(is)*sfr(is)*(1 - snowfrac(is)) !Freezing water
          ENDIF
       ENDDO !End surface type
       !Update snow albedo to its maximum value if precipitation exists
       IF (precip > 0 .AND. sum(snowpack) > 0 .AND. temp_c < 0) THEN
          snowfallcum = snowfallcum + precip
          IF (snowfallcum > preciplimitalb) THEN
             snowalb = snowalbmax
             snowfallcum = 0
          ENDIF
       ELSE
          snowfallcum = 0
       ENDIF
Referenced by snow_cal_meltheat().
snow_cal_meltheat()
subroutine snow_module::snow_cal_meltheat (integer, intent(in) snowUse, real(kind(1d0)), intent(in) lvS_J_kg, real(kind(1d0)), intent(in) lv_J_kg, real(kind(1d0)), intent(in) tstep_real, real(kind(1d0)), intent(in) RadMeltFact, real(kind(1d0)), intent(in) TempMeltFact, real(kind(1d0)), intent(in) SnowAlbMax, real(kind(1d0)), intent(in) SnowDensMin, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) Precip, real(kind(1d0)), intent(in) PrecipLimit, real(kind(1d0)), intent(in) PrecipLimitAlb, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(in) Tsurf_ind, real(kind(1d0)), dimension(nsurf), intent(in) Tsurf_ind_snow, real(kind(1d0)), dimension(nsurf), intent(in) state_id, real(kind(1d0)), dimension(nsurf), intent(in) qn1_ind_snow, real(kind(1d0)), dimension(nsurf), intent(in) kup_ind_snow, real(kind(1d0)), dimension(nsurf), intent(in) SnowWater, real(kind(1d0)), dimension(nsurf), intent(in) deltaQi, real(kind(1d0)), dimension(nsurf), intent(inout) SnowPack, real(kind(1d0)), dimension(nsurf), intent(inout) snowFrac, real(kind(1d0)), intent(inout) SnowAlb, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens, real(kind(1d0)), intent(inout) SnowfallCum, real(kind(1d0)), intent(out) mwh, real(kind(1d0)), intent(out) fwh, real(kind(1d0)), intent(out) Qm, real(kind(1d0)), intent(out) QmFreez, real(kind(1d0)), intent(out) QmRain, real(kind(1d0)), intent(out) veg_fr, integer, dimension(nsurf), intent(out) snowCalcSwitch, real(kind(1d0)), dimension(nsurf), intent(out) Qm_melt, real(kind(1d0)), dimension(nsurf), intent(out) Qm_freezState, real(kind(1d0)), dimension(nsurf), intent(out) Qm_rain, real(kind(1d0)), dimension(nsurf), intent(out) FreezMelt, real(kind(1d0)), dimension(nsurf), intent(out) FreezState, real(kind(1d0)), dimension(nsurf), intent(out) FreezStateVol, real(kind(1d0)), dimension(nsurf), intent(out) rainOnSnow, real(kind(1d0)), dimension(nsurf), intent(out) SnowDepth, real(kind(1d0)), dimension(nsurf), intent(out) mw_ind, real(kind(1d0)), dimension(ncolumnsdataoutsnow), intent(out) dataOutLineSnow)
Definition at line 40 of file suews_phys_snow.f95.
       IMPLICIT NONE
       INTEGER, PARAMETER::nsurf = 7
       INTEGER, PARAMETER::PavSurf = 1
       INTEGER, PARAMETER::BldgSurf = 2
       INTEGER, PARAMETER::WaterSurf = 7
       INTEGER, PARAMETER::ncolumnsDataOutSnow = 102 - 5
       REAL(KIND(1d0)), PARAMETER::waterDens = 999.8395 !Density of water in 0 cel deg
       !These are input to the module
       INTEGER, INTENT(in)::snowUse
       ! INTEGER,INTENT(in)::bldgsurf
       ! INTEGER,INTENT(in)::nsurf
       ! INTEGER,INTENT(in)::PavSurf
       ! INTEGER,INTENT(in)::WaterSurf
       REAL(KIND(1d0)), INTENT(in)::lvS_J_kg
       REAL(KIND(1d0)), INTENT(in)::lv_J_kg
       REAL(KIND(1d0)), INTENT(in)::tstep_real
       REAL(KIND(1d0)), INTENT(in)::RadMeltFact
       REAL(KIND(1d0)), INTENT(in)::TempMeltFact
       REAL(KIND(1d0)), INTENT(in)::SnowAlbMax
       REAL(KIND(1d0)), INTENT(in)::SnowDensMin
       REAL(KIND(1d0)), INTENT(in)::Temp_C
       REAL(KIND(1d0)), INTENT(in)::Precip
       REAL(KIND(1d0)), INTENT(in)::PrecipLimit
       REAL(KIND(1d0)), INTENT(in)::PrecipLimitAlb
       REAL(KIND(1d0)), INTENT(in)::nsh_real
       ! REAL(KIND(1d0)),INTENT(in)::waterdens
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Tsurf_ind
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Tsurf_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::state_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::qn1_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::kup_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::SnowWater
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::deltaQi
       !Input and output as this is updated in this subroutine
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowPack
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::snowFrac
       REAL(KIND(1d0)), INTENT(inout)::SnowAlb
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowDens
       REAL(KIND(1d0)), INTENT(inout)::SnowfallCum
       !Output:
       REAL(KIND(1d0)), INTENT(out)::mwh
       REAL(KIND(1d0)), INTENT(out)::fwh
       REAL(KIND(1d0)), INTENT(out)::Qm
       REAL(KIND(1d0)), INTENT(out)::QmFreez
       REAL(KIND(1d0)), INTENT(out)::QmRain
       REAL(KIND(1d0)), INTENT(out)::veg_fr
       INTEGER, DIMENSION(nsurf), INTENT(out)::snowCalcSwitch
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::Qm_melt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::Qm_freezState
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::Qm_rain
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::FreezMelt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::FreezState
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::FreezStateVol
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::rainOnSnow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::SnowDepth
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::mw_ind
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutSnow), INTENT(out) :: dataOutLineSnow
       IF (snowuse == 1) THEN
          CALL meltheat( &
             bldgsurf, nsurf, pavsurf, watersurf, &
             lvs_j_kg, lv_j_kg, tstep_real, radmeltfact, tempmeltfact, &
             snowalbmax, snowdensmin, temp_c, precip, preciplimit, preciplimitalb, &
             nsh_real, waterdens, sfr, tsurf_ind, state_id, qn1_ind_snow, &
             snowwater, deltaqi, snowpack, snowfrac, snowalb, snowdens, snowfallcum, &
             mwh, fwh, qm, qmfreez, qmrain, snowcalcswitch, &
             qm_melt, qm_freezstate, qm_rain, freezmelt, freezstate, freezstatevol, &
             rainonsnow, snowdepth, mw_ind)
          CALL veg_fr_snow( &
             sfr, snowfrac, nsurf, &!input
             veg_fr)!output
       ELSE ! no snow calculation
          mwh = 0
          fwh = 0
          qm = 0
          qmfreez = 0
          qmrain = 0
          snowfallcum = 0
          snowcalcswitch = 0
          qm_melt = 0
          qm_freezstate = 0
          qm_rain = 0
          freezmelt = 0
          freezstate = 0
          freezstatevol = 0
          rainonsnow = 0
          snowdepth = 0
          mw_ind = 0
          ! update veg_fr when snowFrac=0
          snowfrac = 0
          CALL veg_fr_snow( &
             sfr, snowfrac, nsurf, &!input
             veg_fr)!output
       END IF
       ! pack output into one line
       dataoutlinesnow = [ &
                         snowpack(1:nsurf), mw_ind(1:nsurf), qm_melt(1:nsurf), & !26
                         qm_rain(1:nsurf), qm_freezstate(1:nsurf), snowfrac(1:(nsurf - 1)), & !46
                         rainonsnow(1:nsurf), & !53
                         qn1_ind_snow(1:nsurf), kup_ind_snow(1:nsurf), freezmelt(1:nsurf), & !74
                         snowwater(1:nsurf), snowdens(1:nsurf), & !88
                         snowdepth(1:nsurf), tsurf_ind_snow(1:nsurf)]
       ! dataOutLineSnow=set_nan(dataOutLineSnow)
References meltheat(), and veg_fr_snow().
Referenced by suews_driver::suews_cal_main().
snowcalc()
subroutine snow_module::snowcalc (integer, intent(in) tstep, integer, intent(in) imin, integer, intent(in) it, real(kind(1d0)), intent(in) dectime, integer, intent(in) is, integer, intent(in) EvapMethod, real(kind(1d0)), intent(in) CRWmin, real(kind(1d0)), intent(in) CRWmax, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), intent(in) lvS_J_kg, real(kind(1d0)), intent(in) lv_j_kg, real(kind(1d0)), intent(in) avdens, real(kind(1d0)), intent(in) avRh, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) RAsnow, real(kind(1d0)), intent(in) psyc_hPa, real(kind(1d0)), intent(in) avcp, real(kind(1d0)), intent(in) sIce_hPa, real(kind(1d0)), intent(in) PervFraction, real(kind(1d0)), intent(in) vegfraction, real(kind(1d0)), intent(in) addimpervious, real(kind(1d0)), intent(in) vpd_hPa, real(kind(1d0)), intent(in) qn_e, real(kind(1d0)), intent(in) s_hPa, real(kind(1d0)), intent(in) ResistSurf, real(kind(1d0)), intent(in) RA, real(kind(1d0)), intent(in) rb, real(kind(1d0)), intent(in) tlv, real(kind(1d0)), intent(in) snowdensmin, real(kind(1d0)), dimension(0:23, 2), intent(in) SnowProf_24hr, real(kind(1d0)), intent(in) precip, real(kind(1d0)), intent(in) PipeCapacity, real(kind(1d0)), intent(in) RunoffToWater, real(kind(1d0)), intent(in) addVeg, real(kind(1d0)), intent(in) SnowLimPaved, real(kind(1d0)), intent(in) SnowLimBldg, real(kind(1d0)), intent(in) FlowChange, real(kind(1d0)), dimension(nsurf), intent(in) drain, real(kind(1d0)), dimension(nsurf), intent(in) WetThresh, real(kind(1d0)), dimension(nsurf), intent(in) stateOld, real(kind(1d0)), dimension(nsurf), intent(in) mw_ind, real(kind(1d0)), dimension(nsurf), intent(in) SoilStoreCap, real(kind(1d0)), dimension(nsurf), intent(in) rainonsnow, real(kind(1d0)), dimension(nsurf), intent(in) freezmelt, real(kind(1d0)), dimension(nsurf), intent(in) freezstate, real(kind(1d0)), dimension(nsurf), intent(in) freezstatevol, real(kind(1d0)), dimension(nsurf), intent(in) Qm_Melt, real(kind(1d0)), dimension(nsurf), intent(in) Qm_rain, real(kind(1d0)), dimension(nsurf), intent(in) Tsurf_ind, real(kind(1d0)), dimension(nsurf), intent(in) sfr, integer, dimension(3), intent(in) dayofWeek_id, real(kind(1d0)), dimension(6, nsurf), intent(in) StoreDrainPrm, real(kind(1d0)), dimension(nsurf), intent(in) SnowPackLimit, real(kind(1d0)), dimension(nsurf), intent(in) AddWater, real(kind(1d0)), dimension(nsurf), intent(in) addwaterrunoff, real(kind(1d0)), dimension(nsurf), intent(inout) soilstore_id, real(kind(1d0)), dimension(nsurf), intent(inout) SnowPack, real(kind(1d0)), dimension(2), intent(inout) SurplusEvap, real(kind(1d0)), dimension(nsurf), intent(inout) snowFrac, real(kind(1d0)), dimension(nsurf), intent(inout) SnowWater, real(kind(1d0)), dimension(nsurf), intent(inout) iceFrac, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens, real(kind(1d0)), intent(inout) runoffAGimpervious, real(kind(1d0)), intent(inout) runoffAGveg, real(kind(1d0)), intent(inout) surplusWaterBody, real(kind(1d0)), dimension(nsurf), intent(out) rss_nsurf, real(kind(1d0)), dimension(nsurf), intent(out) runoffSnow, real(kind(1d0)), dimension(nsurf), intent(out) runoff, real(kind(1d0)), dimension(nsurf), intent(out) runoffSoil, real(kind(1d0)), dimension(nsurf), intent(out) chang, real(kind(1d0)), dimension(nsurf), intent(out) changSnow, real(kind(1d0)), dimension(nsurf), intent(out) SnowToSurf, real(kind(1d0)), dimension(nsurf), intent(out) state_id, real(kind(1d0)), dimension(nsurf), intent(out) ev_snow, real(kind(1d0)), dimension(nsurf), intent(out) SnowDepth, real(kind(1d0)), dimension(2), intent(out) SnowRemoval, real(kind(1d0)), intent(out) swe, real(kind(1d0)), intent(out) ev, real(kind(1d0)), intent(out) chSnow_tot, real(kind(1d0)), intent(out) ev_tot, real(kind(1d0)), intent(out) qe_tot, real(kind(1d0)), intent(out) runoff_tot, real(kind(1d0)), intent(out) surf_chang_tot, real(kind(1d0)), intent(out) runoffPipes, real(kind(1d0)), intent(out) mwstore, real(kind(1d0)), intent(out) runoffwaterbody)
Definition at line 469 of file suews_phys_snow.f95.
       !Calculation of snow and water balance on 5 min timestep. Treats snowfree and snow covered
       !areas separately. Weighting is taken into account in the overall values.
       !Last modified:
       !  LJ in 6 May 2015 - Modified to run with timestep
       !  HCW 06 Mar 2015 - Unused variable 'i' removed.
       !  HCW 26 Jan 2015 - Added weekday/weekend option for snow clearing profiles
       !  LJ in 24 May 2013
       !========================================================================
       USE waterdist_module, ONLY: updateflood
       IMPLICIT NONE
       INTEGER, PARAMETER::nsurf = 7! number of surface types
       INTEGER, PARAMETER::PavSurf = 1  !New surface classes: Grass = 5th/7 surfaces
       INTEGER, PARAMETER::BldgSurf = 2  !New surface classes: Grass = 5th/7 surfaces
       INTEGER, PARAMETER::ConifSurf = 3  !New surface classes: Grass = 5th/7 surfaces
       ! INTEGER,PARAMETER::DecidSurf = 4  !New surface classes: Grass = 5th/7 surfaces
       ! INTEGER,PARAMETER::GrassSurf = 5
       INTEGER, PARAMETER::BSoilSurf = 6!New surface classes: Grass = 5th/7 surfaces
       INTEGER, PARAMETER::WaterSurf = 7
       INTEGER, PARAMETER::snowfractionchoice = 2 ! this PARAMETER is used all through the model
       REAL(KIND(1d0)), PARAMETER::waterDens = 999.8395 !Density of water in 0 cel deg
       ! INTEGER,INTENT(in)::id
       ! INTEGER,INTENT(in)::nsurf
       INTEGER, INTENT(in)::tstep
       INTEGER, INTENT(in)::imin
       INTEGER, INTENT(in)::it
       INTEGER, INTENT(in)::is
       ! INTEGER,INTENT(in)::ConifSurf
       ! INTEGER,INTENT(in)::BSoilSurf
       ! INTEGER,INTENT(in)::BldgSurf
       ! INTEGER,INTENT(in)::PavSurf
       ! INTEGER,INTENT(in)::WaterSurf
       INTEGER, INTENT(in)::EvapMethod!Evaporation calculated according to Rutter (1) or Shuttleworth (2)
       INTEGER, DIMENSION(3), INTENT(in)  ::DayofWeek_id
       REAL(KIND(1d0)), INTENT(in)::dectime
       REAL(KIND(1d0)), INTENT(in)::CRWmin
       REAL(KIND(1d0)), INTENT(in)::CRWmax
       REAL(KIND(1d0)), INTENT(in)::nsh_real
       REAL(KIND(1d0)), INTENT(in)::lvS_J_kg
       REAL(KIND(1d0)), INTENT(in)::lv_j_kg
       REAL(KIND(1d0)), INTENT(in)::avdens
       REAL(KIND(1d0)), INTENT(in)::vpd_hPa ! vapour pressure deficit [hPa]
       REAL(KIND(1d0)), INTENT(in)::qn_e !net available energy for evaporation
       REAL(KIND(1d0)), INTENT(in)::avRh
       REAL(KIND(1d0)), INTENT(in)::Press_hPa
       REAL(KIND(1d0)), INTENT(in)::Temp_C
       REAL(KIND(1d0)), INTENT(in)::RAsnow
       REAL(KIND(1d0)), INTENT(in)::psyc_hPa
       REAL(KIND(1d0)), INTENT(in)::avcp
       REAL(KIND(1d0)), INTENT(in)::sIce_hPa
       REAL(KIND(1d0)), INTENT(in)::PervFraction
       REAL(KIND(1d0)), INTENT(in)::vegfraction
       REAL(KIND(1d0)), INTENT(in)::addimpervious
       ! REAL(KIND(1d0)),INTENT(in)::numPM
       REAL(KIND(1d0)), INTENT(in)::s_hPa
       REAL(KIND(1d0)), INTENT(in)::ResistSurf
       ! REAL(KIND(1d0)),INTENT(in)::sp
       REAL(KIND(1d0)), INTENT(in)::RA
       REAL(KIND(1d0)), INTENT(in)::rb
       REAL(KIND(1d0)), INTENT(in)::tlv
       REAL(KIND(1d0)), INTENT(in)::snowdensmin
       REAL(KIND(1d0)), INTENT(in)::precip
       REAL(KIND(1d0)), INTENT(in)::PipeCapacity
       REAL(KIND(1d0)), INTENT(in)::RunoffToWater
       REAL(KIND(1d0)), INTENT(in)::addVeg
       REAL(KIND(1d0)), INTENT(in)::SnowLimPaved
       REAL(KIND(1d0)), INTENT(in)::SnowLimBldg
       REAL(KIND(1d0)), INTENT(in)::FlowChange
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::drain
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::WetThresh
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::stateOld
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::mw_ind
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::SoilStoreCap
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::rainonsnow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::freezmelt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::freezstate
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::freezstatevol
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Qm_Melt
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Qm_rain
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::Tsurf_ind
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::SnowPackLimit
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::AddWater
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::addwaterrunoff
       REAL(KIND(1d0)), DIMENSION(6, nsurf), INTENT(in)::StoreDrainPrm
       REAL(KIND(1d0)), DIMENSION(0:23, 2), INTENT(in)::SnowProf_24hr
       !Updated status: input and output
       REAL(KIND(1d0)), INTENT(inout)::runoffAGveg
       REAL(KIND(1d0)), INTENT(inout)::runoffAGimpervious
       REAL(KIND(1d0)), INTENT(inout)::surplusWaterBody
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::soilstore_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowPack
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::snowFrac
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowWater
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::iceFrac
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowDens
       REAL(KIND(1d0)), DIMENSION(2), INTENT(inout):: SurplusEvap
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::rss_nsurf
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::runoffSnow !Initialize for runoff caused by snowmelting
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::runoff
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::runoffSoil
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::chang
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::changSnow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::SnowToSurf
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::state_id
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::SnowDepth
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out)::ev_snow
       REAL(KIND(1d0)), DIMENSION(2), INTENT(out)::SnowRemoval
       REAL(KIND(1d0)), INTENT(out)::swe
       REAL(KIND(1d0)), INTENT(out)::ev
       REAL(KIND(1d0)), INTENT(out)::ev_tot
       REAL(KIND(1d0)), INTENT(out)::chSnow_tot
       REAL(KIND(1d0)), INTENT(out)::qe_tot
       REAL(KIND(1d0)), INTENT(out)::runoff_tot
       REAL(KIND(1d0)), INTENT(out)::surf_chang_tot
       REAL(KIND(1d0)), INTENT(out)::runoffPipes
       REAL(KIND(1d0)), INTENT(out)::mwstore
       REAL(KIND(1d0)), INTENT(out)::runoffwaterbody
       REAL(KIND(1d0))::qe
       ! REAL(KIND(1d0))::Evap_SUEWS_Snow
       REAL(KIND(1d0))::MeltExcess      !Excess melt water that needs to leave SnowPack
       REAL(KIND(1d0))::snowTotInit
       REAL(KIND(1d0))::EvPart
       REAL(KIND(1d0))::runoffTest
       REAL(KIND(1d0))::snowFracFresh1   !Snow fraction for newly formed SnowPack
       REAL(KIND(1d0))::snowFracFresh2   !Snow fraction for newly formed SnowPack from state_id only
       REAL(KIND(1d0))::snowFracOld
       REAL(KIND(1d0))::WaterHoldCapFrac
       REAL(KIND(1d0))::FWC                !Water holding capacity of snow in mm
       REAL(KIND(1d0))::tlv_sub
       ! REAL(KIND(1d0)):: SnowDepletionCurve
       INTEGER:: iu                        !1=weekday OR 2=weekend
       REAL(KIND(1d0)), PARAMETER :: IPThreshold_mmhr = 10   !Threshold for intense precipitation [mm hr-1]
       REAL(KIND(1d0)), DIMENSION(7)::capStore ! current storage capacity [mm]
       !========================================================================
       !Initialize variables for the calculation of water storages and evaporation
       ev_tot = 0
       qe_tot = 0
       runoff_tot = 0
       surf_chang_tot = 0
       !swe = 0
       chsnow_tot = 0
       !runoffPipes = 0
       !mwstore = 0
       !runoffwaterbody = 0
       rss_nsurf = 0
       !state_id = 0
       snowdepth = 0
       ev_snow = 0
       !SnowRemoval = 0
       tlv_sub = 0
       ! Use weekday or weekend snow clearing profile
       iu = 1     !Set to 1=weekday
       IF (dayofweek_id(1) == 1 .OR. dayofweek_id(1) == 7) iu = 2  !Set to 2=weekend
       !write(*,*) is
       runoffsnow(is) = 0 !Initialize for runoff caused by snowmelting
       runoff(is) = 0
       runoffsoil(is) = 0
       chang(is) = 0
       changsnow(is) = 0
       runofftest = 0
       snowtosurf(is) = 0
       evpart = 0
       ev = 0
       snowfracfresh1 = 0
       snowfracfresh2 = 0
       snowfracold = 0
       !Initial SnowPack + meltwater in it
       snowtotinit = snowpack(is) + snowwater(is)
       !Calculate water holding capacity (Jin et al. 1999)
       IF (snowdens(is) >= 200) THEN
          waterholdcapfrac = crwmin
       ELSE
          waterholdcapfrac = crwmin + (crwmax - crwmin)*(200 - snowdens(is))/200
       ENDIF
       !======================================================================
       ! Calculate evaporation from SnowPack and snow free surfaces (in mm)
       ! IF (snowFrac(is)<1) CALL Evap_SUEWS !ev and qe for snow free surface out
       capstore(is) = storedrainprm(6, is)
       IF (snowfrac(is) < 1) CALL evap_suews( &
          evapmethod, state_id(is), wetthresh(is), capstore(is), &!input
          vpd_hpa, avdens, avcp, qn_e, s_hpa, psyc_hpa, resistsurf, ra, rb, tlv, &
          rss_nsurf(is), ev, qe) !output
       IF (snowfrac(is) > 0) THEN
          call evap_suews_snow(qm_melt(is), qm_rain(is), lvs_j_kg, avdens, avrh, press_hpa, temp_c, rasnow, &
                               psyc_hpa, tstep, avcp, sice_hpa, dectime, ev_snow(is), tlv_sub)
       ENDIF
       !If not enough water for evaporation in impervious surfaces,
       !evaporation is taken from pervious surfaces
       IF (is > 2) THEN
          IF (pervfraction /= 0) THEN
             evpart = (surplusevap(pavsurf)*sfr(pavsurf) + surplusevap(bldgsurf)*sfr(bldgsurf))/pervfraction
          ENDIF
       ENDIF
       !============================================================================
       !Water surface is treated separately
       IF (is == watersurf .AND. sfr(watersurf) > 0) GO TO 606
       !The calculations are divided into 2 main parts
       ! 1) Surface is fully covered with snow at the beginning of the time step
       ! 2) Surface is not fully covered with snow but rather part is snow free OR
       !    surface not orginally covered with snow, but the snow forms at the current timestep
       !1)------------------------------------------------------------------
       !  ------------------------------------------------------------------
       IF (snowpack(is) > 0 .AND. snowfrac(is) == 1) THEN
          ev_snow(is) = ev_snow(is) + evpart !Evaporation surplus
          !(Snowfall per interval+freezing of melt water and surface state_id) - (meltwater+evaporation from SnowPack)
          changsnow(is) = (precip + freezmelt(is)) - (mw_ind(is) + ev_snow(is)) !Calculate change in SnowPack (in mm)
          !If rain on snow event, add this water to SnowWater
          IF (rainonsnow(is) > 0) THEN
             changsnow(is) = changsnow(is) - precip
             snowwater(is) = snowwater(is) + rainonsnow(is)
          ENDIF
          snowpack(is) = snowpack(is) + changsnow(is)  !Update SnowPack
          !---------If SnowPack exists after the state_id calculations
          IF (snowpack(is) > 0) THEN
             !Add melted water to meltstore and freeze water according to freezMelt(is)
             snowwater(is) = snowwater(is) + mw_ind(is) - freezmelt(is)
             !Calculate water holding capacity (FWC: Valeo and Ho, 2004) of the SnowPack
             fwc = waterholdcapfrac*snowpack(is)
             !If FWC is exceeded, excess meltwater (MeltExcess) will leave from the SnowPack
             IF (snowwater(is) >= fwc) THEN
                meltexcess = 0                      !Initialize the excess meltwater
                meltexcess = snowwater(is) - fwc !Calculate the exceess water
                snowwater(is) = fwc            !Update the SnowWater to the maximum it can hold
                runoffsnow(is) = runoffsnow(is) + meltexcess
             ENDIF
             !At the end of the hour calculate possible snow removal
             IF (snowprof_24hr(it, iu) == 1 .AND. is < 3 .AND. (imin == (nsh_real - 1)/nsh_real*60)) &
                CALL snowrem( &
                is, pavsurf, bldgsurf, nsurf, &
                snowfrac, sfr, &
                snowpack, snowremoval, &
                snowlimpaved, snowlimbldg)
             !----------If SnowPack is negative, it melts at this timestep
          ELSEIF (snowpack(is) < 0) THEN
             !If freezing meltwater inside this timestep, remove it from the SnowWater
             snowwater(is) = snowwater(is) - freezmelt(is) + mw_ind(is) + snowpack(is)
             snowpack(is) = 0.0   !Set the snow pack and snow
             snowfracold = 1
             snowfrac(is) = 0
             snowdens(is) = 0
             IF (snowwater(is) < 0) THEN !Not enough water in the meltwater store,
                ev_snow(is) = ev_snow(is) + snowwater(is) !QUESTION: evaporation from snow is decreased?
                IF (ev_snow(is) < 0) ev_snow(is) = 0
                changsnow(is) = changsnow(is) + snowwater(is)
                snowwater(is) = 0
             ELSE
                chang(is) = snowwater(is)  !Meltwater goes to surface state_id as no snow exists anymore
                state_id(is) = state_id(is) + chang(is)
                snowwater(is) = 0
             ENDIF
          ENDIF !SnowPack negative or positive
          !2)------Surface not fully covered with snow-------------------------------------------
          !  ------------------------------------------------------------------------------------
       ELSEIF (snowfrac(is) < 1) THEN
          !Snow calculations: SnowPack can either exist or form at the current timestep
          IF (snowpack(is) > 0) THEN
             ev_snow(is) = ev_snow(is) + evpart !Evaporation surplus
             !----SnowPack water balance for the whole surface area. In reality snow depth = SnowPack/snowFrac(is)
             !(Snowfall per interval+freezing of melt water and surface state_id) - (meltwater+evaporation from SnowPack)
             changsnow(is) = (precip + freezmelt(is) + freezstatevol(is)) - (mw_ind(is) + ev_snow(is)) !Calculate change in SnowPack (in mm)
             !If rain on snow event, add this water to SnowWater
             IF (rainonsnow(is) > 0) THEN
                changsnow(is) = changsnow(is) - precip
                snowwater(is) = snowwater(is) + rainonsnow(is)
             ENDIF
             snowpack(is) = snowpack(is) + changsnow(is)
             !The fraction of snow will update when:
             !a) Surface state_id is dry but precipitation occurs =1
             !b) There is both precipitation and all surface state_id freezes =1
             !c) No precipitation but all state_id freezes at a single timestep =2
             !d) Part of the surface freezes
             IF (precip > 0 .AND. freezstate(is) == state_id(is)) THEN !both a) and b)
                snowfracfresh1 = 1
             ELSEIF (precip == 0 .AND. freezstate(is) > 0 .AND. freezstate(is) == state_id(is)) THEN
                snowfracfresh1 = 1
                !snowFracFresh1=SnowDepletionCurve(is,SnowPack(is),SnowPackLimit(is))
                !if (snowFracFresh1<0.001) snowFracFresh1=0.001
             ELSEIF (freezstate(is) > 0 .AND. freezstate(is) < state_id(is)) THEN !This if not all water freezes
                snowfracfresh1 = 0.95 !Now this fraction set to something close to one. Should be improved in the future at some point
                !if (is==1)then
                ! write(*,*) id,it,imin,snowfrac(is),FreezState(is),state_id(is)
                ! pause
                !endif
             ENDIF
             !SnowPack can also form at the current timestep (2). If this forms purely from snowfall or/and all water at surface freezes,
             !the whole surface will be covered with snow. If there is water on ground this snowfall can immediately melt
             !and in this case the snow fraction is not necessarily 1 but its information is saved to snowFracFresh that
             !is taken into account in snow fraction after calculation of state_id.
          ELSEIF (snowpack(is) == 0 .AND. tsurf_ind(is) < 0) THEN
             !The fraction of snow will get a value of 1 (ie full snow cover):
             !Surface state_id is dry but precipitation occurs, no precipitation but all state_id freezes at a single timestep,
             !There is both precipitation and all surface state_id freezes
             IF ((precip > 0 .AND. state_id(is) == 0) .OR. (precip == 0 .AND. freezstate(is) == state_id(is)) .OR. &
                 (precip > 0 .AND. freezstate(is) == state_id(is))) THEN
                !ev=ev+EvPart
                changsnow(is) = precip + freezstatevol(is)
                snowpack(is) = snowpack(is) + changsnow(is)  !Update SnowPack
                snowfracfresh1 = 1
                icefrac(is) = freezstate(is)/(freezstate(is) + precip)
                snowdens(is) = snowdensmin
             ENDIF
             IF (freezstate(is) > 0 .AND. freezstate(is) < state_id(is)) THEN
                changsnow(is) = precip + freezstatevol(is)
                snowpack(is) = snowpack(is) + changsnow(is)  !Update SnowPack
                snowfracfresh2 = 0.95 !Now this fraction set to something close to one. Should be improved in the future at some point
                !snowFracFresh2=SnowDepletionCurve(is,SnowPack(is),SnowPackLimit(is))
                !if (snowFracFresh2<0.001) snowFracFresh2=0.001
                icefrac(is) = 1
                snowdens(is) = snowdensmin
                !write(*,*) 2,is,id,it,imin,snowfrac(is),FreezState(is),state_id(is),state_id(is)+Precip
                !pause
             ENDIF
          ENDIF
          !---------If SnowPack exists after the state_id calculations
          IF (snowpack(is) > 0) THEN
             !Add melted water to meltstore and freeze water according to freezMelt(is)
             snowwater(is) = snowwater(is) + mw_ind(is) - freezmelt(is)
             !Calculate water holding capacity (FWC: Valeo and Ho, 2004) of the SnowPack
             fwc = waterholdcapfrac*snowpack(is)
             !If FWC is exceeded, excess meltwater (MeltExcess) will leave from the SnowPack
             IF (snowwater(is) >= fwc) THEN
                meltexcess = 0                      !Initialize the excess meltwater
                meltexcess = snowwater(is) - fwc !Calculate the exceess water
                snowwater(is) = fwc            !Update the SnowWater to the maximum it can hold
                !If the fraction of snow is greater than 0.8 or if the surface is is buildings,
                !the excess water will directly go to runoff. Otherwise it will flow to the
                !snow free area via SnowToSurf(is)
                IF ((snowfrac(is) > 0.9 .AND. is /= bldgsurf) .OR. (is == bldgsurf)) THEN
                   runoffsnow(is) = runoffsnow(is) + meltexcess
                ELSE
                   snowtosurf(is) = snowtosurf(is) + meltexcess*snowfrac(is)/(1 - snowfrac(is))
                ENDIF
             ENDIF
             !At the end of the hour calculate possible snow removal
             IF (snowprof_24hr(it, iu) == 1 .AND. is < 3 .AND. (imin == (nsh_real - 1)/nsh_real*60)) &
                CALL snowrem( &
                is, pavsurf, bldgsurf, nsurf, &
                snowfrac, sfr, &
                snowpack, snowremoval, &
                snowlimpaved, snowlimbldg)
             !----------If SnowPack is negative, it melts at this timestep
          ELSEIF (snowpack(is) < 0) THEN
             !If freezing meltwater inside this timestep, remove it from the SnowWater
             snowwater(is) = snowwater(is) - freezmelt(is) + mw_ind(is) + snowpack(is)
             snowpack(is) = 0.0   !Set the snow pack and snow
             snowfracfresh1 = 0
             snowfracfresh2 = 0
             snowdens(is) = 0
             IF (snowwater(is) < 0) THEN !Not enough water in the meltwater store,
                ev_snow(is) = ev_snow(is) + snowwater(is) !QUESTION: evaporation from snow is decreased.?
                IF (ev_snow(is) < 0) ev_snow(is) = 0
                changsnow(is) = changsnow(is) + snowwater(is)
                snowwater(is) = 0
             ELSE
                snowtosurf(is) = snowtosurf(is) + snowwater(is)*snowfrac(is)/(1 - snowfrac(is))
                snowwater(is) = 0
             ENDIF
          ENDIF !SnowPack negative or positive
          !--------
          !Next the snow free surface (3). Calculations only done if snowfraction is smaller than 1
          IF ((is == pavsurf .OR. is == bldgsurf) .AND. snowfrac(is) < 1) THEN  !Impervious surfaces (paved, buildings)
             !Surface store update. If precipitation is greater than the threshold, the exceeding water
             !goes directly to runoff
             IF (precip > ipthreshold_mmhr/nsh_real) THEN
                !runoff = runoff + (precipitation+water from the snow surface+water from other surfaces-the thereshold limit)
                runoff(is) = runoff(is) + (precip + snowtosurf(is) + addwater(is) - ipthreshold_mmhr/nsh_real)
                chang(is) = ipthreshold_mmhr/nsh_real - (drain(is) + ev + freezstate(is))
             ELSE
                !Add precip and water from other surfaces and remove drainage, evap and freezing of state_id
                chang(is) = precip + snowtosurf(is) + addwater(is) - (drain(is) + ev + freezstate(is))
             ENDIF
             state_id(is) = state_id(is) + chang(is) !Change in state_id (for whole surface area areasfr(is))
             !Add water from impervious grids
             ! Check sfr/=0 added HCW 08 Dec 2015
             IF (is == pavsurf .AND. sfr(pavsurf) > 0) state_id(is) = state_id(is) + (addimpervious)/sfr(pavsurf)
             runoff(is) = runoff(is) + drain(is)*addwaterrunoff(is) !Drainage (not flowing to other surfaces) goes to runoff
             IF (state_id(is) < 0.0) THEN  !Surface state_id cannot be negative
                surplusevap(is) = abs(state_id(is)) !take evaporation from other surfaces in mm
                ev = ev - surplusevap(is)
                state_id(is) = 0.0
             ENDIF
          ELSEIF (is >= 3 .AND. snowfrac(is) < 1) THEN ! Pervious surfaces (conif, decid, grass unirr, grass irr)
             ev = ev + evpart
             !Change in water stores
             IF (vegfraction > 0) THEN
                IF (precip + addveg*(sfr(is)/vegfraction) > (ipthreshold_mmhr/nsh_real)) THEN !if 5min precipitation is larger than 10 mm
                   runoff(is) = runoff(is) + (precip + addveg*(sfr(is)/vegfraction) + &
                                              snowtosurf(is) + addwater(is) - (ipthreshold_mmhr/nsh_real))
                   chang(is) = (ipthreshold_mmhr/nsh_real) - (drain(is) + ev + freezstate(is))
                ELSE
                   chang(is) = precip + addveg*(sfr(is)/vegfraction) + snowtosurf(is) + &
                               addwater(is) - (drain(is) + ev + freezstate(is))
                ENDIF
             ELSE
                chang(is) = precip + snowtosurf(is) + addwater(is) - (drain(is) + ev + freezstate(is))
             END IF
             state_id(is) = state_id(is) + chang(is)
             !Add water in soil store only if ground is not frozen
             IF (temp_c > 0) THEN
                soilstore_id(is) = soilstore_id(is) + drain(is)*addwaterrunoff(is)*(1 - snowfrac(is))
             ELSE
                runoff(is) = runoff(is) + drain(is)*addwaterrunoff(is)
             ENDIF
             !If state_id of the surface is negative, remove water from soilstore
             IF (state_id(is) < 0.0) THEN
                IF ((soilstore_id(is) + state_id(is)) >= 0 .AND. temp_c > 0) THEN !If water in soilstore, water is removed
                   soilstore_id(is) = soilstore_id(is) + state_id(is)*(1 - snowfrac(is))
                   state_id(is) = 0.0
                ELSE !If not water in the soilstore evaporation does not occur
                   chang(is) = chang(is) + state_id(is)
                   ev = ev + state_id(is)
                   state_id(is) = 0.0
                ENDIF
             ENDIF !state_id is negative
             !If soilstorage is full at this point, excess will go to surface runoff
             IF (soilstore_id(is) > soilstorecap(is)) THEN
                runofftest = runofftest + (soilstore_id(is) - soilstorecap(is))
                soilstore_id(is) = soilstorecap(is)
             ELSEIF (soilstore_id(is) < 0) THEN
                soilstore_id(is) = 0
             ENDIF
          ENDIF !Surface type
       ENDIF !Surface fraction
       !-------------------------------------------------------------------------------------------------------------------
       !Calculate change in SnowPack and state_id for the respective surface areas
       !Here the case where not all surface state_id freezes is handled
       IF (snowfracfresh2 > 0) THEN
          surf_chang_tot = (state_id(is) - stateold(is))*sfr(is)*(1 - snowfrac(is)) - precip*sfr(is)*(1 - snowfracfresh2)
          chsnow_tot = ((snowpack(is) + snowwater(is)) - snowtotinit)*sfr(is)*(1 - snowfrac(is)) - precip*sfr(is)*snowfracfresh2
       ELSE
          surf_chang_tot = (state_id(is) - stateold(is))*sfr(is)*(1 - snowfrac(is))
          chsnow_tot = ((snowpack(is) + snowwater(is)) - snowtotinit)*sfr(is)*max(snowfrac(is), snowfracold)
       ENDIF
       !Add evaporation to total
       IF (is == bldgsurf .OR. is == pavsurf) THEN
          ev_tot = ev*sfr(is)*(1 - snowfrac(is)) + ev_snow(is)*sfr(is)*max(snowfrac(is), snowfracold)
          qe_tot = ev_snow(is)*tlv_sub*sfr(is)*snowfrac(is) + ev*tlv*sfr(is)*(1 - snowfrac(is))
       ELSE
          ev_tot = ev*sfr(is)*(1 - snowfrac(is)) + ev_snow(is)*sfr(is)*max(snowfrac(is), snowfracold)
          qe_tot = ev_snow(is)*tlv_sub*sfr(is)*max(snowfrac(is), snowfracold) + ev*tlv*sfr(is)*(1 - snowfrac(is))
       ENDIF
       !========RUNOFF=======================
       !Add runoff to pipes
       runoffpipes = runoffpipes + runoffsnow(is)*sfr(is)*max(snowfrac(is), snowfracold) + runoff(is)*sfr(is)*(1 - snowfrac(is)) &
                     + runofftest*sfr(is)
       CALL updateflood( &
          is, runoff, &! input:
          sfr, pipecapacity, runofftowater, &
          runoffagimpervious, surpluswaterbody, runoffagveg, runoffpipes)! inout:
       runoff_tot = runoffsnow(is)*sfr(is)*max(snowfrac(is), snowfracold) + runoff(is)*sfr(is)*(1 - snowfrac(is)) &
                    + runofftest*sfr(is)
       !===Update snow depth, weighted SWE, and Mwstore
       IF (snowdens(is) /= 0) THEN
          snowdepth(is) = snowpack(is)*waterdens/snowdens(is)
       ENDIF
       ! Calculate overall snow water equivalent
       swe = swe + snowpack(is)*sfr(is)*max(snowfrac(is), snowfracold)
       mwstore = mwstore + snowwater(is)*sfr(is)*max(snowfrac(is), snowfracold)
       !if (id==6.and.it==13.and.imin==20) then!
       !if (id==85.and.it==3.and.imin==10) then!
       ! if (id==92.and.it==21.and.imin==35) then!
       !  write(*,*)  ((SnowPack(is)+SnowWater(is))-snowTotInit)*sfr(is)*(1-snowFrac(is)),&
       !              runoff(is)*sfr(is)*(1-snowFrac(is)),&
       !              ev*sfr(is)*(1-snowFrac(is)),&
       !              (state_id(is)-stateOld(is))*sfr(is)*(1-snowFrac(is)),Precip*sfr(is)
       !  write(*,*)  changSnow(is),runoff(is),ev,chang(is),runoffTest,FreezState(is) !changSnow(is)-freezMelt(is)
       !  write(*,*)  is,Precip,runoff_per_tstep,ev_per_tstep,surf_chang_per_tstep,chSnow_per_interval
       !  write(*,*)  is,Precip-runoff_per_tstep-ev_per_tstep,surf_chang_per_tstep+chSnow_per_interval
       !  write(*,*)  is,snowFrac(is),sfr(is),sfr(is)*ev_snow(is)
       !  pause
       ! endif
       !Only now update the new snow fractions both in the case that snow existing already on ground
       !and snow forms at the current timestep
       IF (snowfracfresh1 > 0) snowfrac(is) = snowfracfresh1
       IF (snowfracfresh2 > 0) snowfrac(is) = snowfracfresh2
       !Calculate new snow fraction here.
       !Tässä ongelmana että snow fraction muuttuu vain kun on sulamisvettä ja on vika tunti.
       !Tämä ei juuri koskaan toteudu johtuen lämpötilan vuorokausisyklistä
       !Kokeile tässä ajaa kahdella tavalla 1) ei tarvita Mw:tä
       !                                    2) päivitys voi tapahtua millon vain
       !if (SnowFractionChoice==2.and.imin==(nsh_real-1)/nsh_real*60) then
       IF (snowfractionchoice == 2) THEN
          IF (snowpack(is) > 0 .AND. mw_ind(is) > 0) THEN
             snowfrac(is) = snowdepletioncurve(is, snowpack(is), snowpacklimit(is))
             IF (snowfrac(is) < 0.001) snowfrac(is) = 0.001  !The snow fraction minimum is 1% of the surface
          ELSEIF (snowpack(is) == 0) THEN
             snowfrac(is) = 0
          ENDIF
       ENDIF
       RETURN
       !==========================================================================
       !WATERBODY is treated separately as state_id always below ice if ice existing
       !Calculate change in SnowPack
 606   changsnow(watersurf) = (precip + freezmelt(watersurf) + freezstate(watersurf)) - &
                              (mw_ind(watersurf) + ev_snow(watersurf))
       snowpack(watersurf) = snowpack(watersurf) + changsnow(watersurf) !Update SnowPack
       state_id(watersurf) = state_id(watersurf) + flowchange - freezstate(watersurf)  !Update state_id below ice
       !If SnowPack exists
       IF (snowpack(watersurf) > 0) THEN
          !Add melted water to meltstore and freeze water according to freezMelt(is)
          snowwater(watersurf) = snowwater(watersurf) + mw_ind(watersurf) - freezmelt(watersurf)
          !Calculate water holding capacity (FWC: Valeo and Ho, 2004) of the SnowPack
          fwc = waterholdcapfrac*snowpack(watersurf)
          !If FWC is exceeded, add meltwater to state_id
          IF (snowwater(watersurf) >= fwc .AND. temp_c >= 0) THEN
             state_id(watersurf) = state_id(watersurf) + (snowwater(watersurf) - fwc)
             snowwater(watersurf) = fwc
          ENDIF
          !If SnowPack is negative, it melts at this timestep
       ELSEIF (snowpack(is) < 0) THEN
          !Add water to the meltwater store
          !If freezing meltwater inside this hour, remove it from the SnowWater
          snowwater(watersurf) = snowwater(watersurf) - freezmelt(watersurf) &
                                 + mw_ind(watersurf)
          state_id(watersurf) = state_id(watersurf) + snowwater(watersurf) + snowpack(watersurf) !Add meltwater to state_id
          snowpack(watersurf) = 0
          IF (state_id(watersurf) < 0) ev_snow(watersurf) = ev_snow(watersurf) + state_id(watersurf)
       ENDIF !SnowPack negative or positive
       !Check water state_id separately
       IF (state_id(watersurf) > storedrainprm(5, watersurf)) THEN
          runoff(watersurf) = runoff(watersurf) + (state_id(watersurf) - storedrainprm(5, watersurf))
          state_id(watersurf) = storedrainprm(5, watersurf)
          runoffwaterbody = runoffwaterbody + runoff(watersurf)*sfr(watersurf)
       ELSE
          state_id(watersurf) = state_id(watersurf) + surpluswaterbody
          IF (state_id(watersurf) > storedrainprm(5, watersurf)) THEN
             runoffwaterbody = runoffwaterbody + (state_id(watersurf) - storedrainprm(5, watersurf))*sfr(watersurf)
             state_id(watersurf) = storedrainprm(5, watersurf)
          ENDIF
       ENDIF
       !Change state_id of snow and surface
       chsnow_tot = ((snowpack(watersurf) + snowwater(watersurf)) - snowtotinit)*sfr(watersurf)
       !ch_per_interval=ch_per_interval+(state_id(WaterSurf)-stateOld(WaterSurf))*sfr(WaterSurf)
       surf_chang_tot = (state_id(watersurf) - stateold(watersurf))*sfr(watersurf)
       !Evaporation
       ev_tot = ev*sfr(watersurf) + ev_snow(watersurf)*sfr(watersurf)
       qe_tot = ev_snow(watersurf)*tlv_sub*sfr(watersurf) + ev*tlv*sfr(watersurf)
       runoff_tot = runoff(is) !The total runoff from the area
       IF (snowpack(watersurf) > 0) THEN     !Fraction only 1 or 0
          snowfrac(watersurf) = 1
       ELSE
          snowfrac(watersurf) = 0
       ENDIF
References evap_suews(), evap_suews_snow(), snowdepletioncurve(), snowrem(), and waterdist_module::updateflood().
Referenced by suews_driver::suews_cal_qe().
snowdepletioncurve()
real(kind(1d0)) function snow_module::snowdepletioncurve (integer is, real(kind(1d0)) swe, real(kind(1d0)) sweD)
Definition at line 1216 of file suews_phys_snow.f95.
       !This function calculates surface coverage of snow according to the
       !depletion curves in Valeo and Ho (2004).
       !INPUT: is   Surface type number
       !       swe  Snow water content
       !       sweD Limit for
       USE allocatearray
       IMPLICIT NONE
       INTEGER::is
       REAL(KIND(1d0))::asc, sweD, swe
       !Impervious surface
       IF (is == pavsurf) THEN
          IF (swe <= swed) THEN      !Snow water equivalent below threshold
             asc = ((swe/swed))**2
          ELSE
             asc = 1
          ENDIF
          !Bldgs surface
       ELSEIF (is == bldgsurf) THEN
          IF (swe <= swed) THEN
             IF ((swe/swed) < 0.9) THEN
                asc = (swe/swed)*0.5
             ELSE
                asc = (swe/swed)**8
             ENDIF
          ELSE
             asc = 1
          ENDIF
       ELSEIF (is == watersurf) THEN
          IF (swe > 0) asc = 1
          !Vegetion surfaces
       ELSE
          IF (swe <= swed) THEN
             asc = 1 - ((1/3.1416)*acos(2*(swe/swed) - 1))**1.7
          ELSE
             asc = 1
          ENDIF
       ENDIF
       !asc=real(int(10000.*asc))/10000  !4 decimal precision
       RETURN
References allocatearray::bldgsurf, allocatearray::pavsurf, and allocatearray::watersurf.
Referenced by snowcalc().
snowrem()
subroutine snow_module::snowrem (integer, intent(in) is, integer, intent(in) PavSurf, integer, intent(in) BldgSurf, integer, intent(in) nsurf, real(kind(1d0)), dimension(nsurf), intent(in) snowfrac, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(out) SnowPack, real(kind(1d0)), dimension(nsurf), intent(out) SnowRemoval, real(kind(1d0)), intent(in) SnowLimPaved, real(kind(1d0)), intent(in) SnowLimBldg)
Definition at line 1187 of file suews_phys_snow.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in)                          :: is, PavSurf, BldgSurf, nsurf
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in) :: snowfrac, sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out):: SnowPack, SnowRemoval
       REAL(KIND(1d0)), INTENT(in)                  :: SnowLimPaved, SnowLimBldg
       !write(*,*) is, SnowPack(is),SnowLimPaved,SnowLimBldg
       IF (is == pavsurf) THEN
          IF (snowpack(pavsurf) > snowlimpaved) THEN
             snowremoval(pavsurf) = (snowpack(pavsurf) - snowlimpaved)*sfr(pavsurf)*snowfrac(pavsurf)
             snowpack(pavsurf) = snowlimpaved
             !SnowPack(PavSurf)=SnowPack(PavSurf)/snowFrac(PavSurf)
          ENDIF
       ENDIF
       IF (is == bldgsurf) THEN
          IF (snowpack(bldgsurf) > snowlimbldg) THEN
             snowremoval(2) = (snowpack(bldgsurf) - snowlimbldg)*sfr(bldgsurf)*snowfrac(bldgsurf)
             snowpack(bldgsurf) = snowlimbldg
             !SnowPack(BldgSurf)=SnowPack(BldgSurf)/snowFrac(BldgSurf)
          ENDIF
       ENDIF
       !write(*,*) is, SnowPack(is),SnowLimPaved,SnowLimBldg
       !pause
Referenced by snowcalc().
snowupdate()
subroutine snow_module::snowupdate (integer, intent(in) nsurf, integer, intent(in) tstep, real(kind(1d0)), intent(in) Temp_C_hr, real(kind(1d0)), intent(in) tau_a, real(kind(1d0)), intent(in) tau_f, real(kind(1d0)), intent(in) tau_r, real(kind(1d0)), intent(in) SnowDensMax, real(kind(1d0)), intent(in) SnowDensMin, real(kind(1d0)), intent(in) SnowAlbMax, real(kind(1d0)), intent(in) SnowAlbMin, real(kind(1d0)), dimension(nsurf), intent(in) SnowPack, real(kind(1d0)), intent(inout) SnowAlb, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens)
Definition at line 1309 of file suews_phys_snow.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in)::nsurf
       INTEGER, INTENT(in)::tstep
       REAL(KIND(1D0)), INTENT(in)::Temp_C_hr        !Air temperature
       REAL(KIND(1D0)), INTENT(in)::tau_a
       REAL(KIND(1D0)), INTENT(in)::tau_f
       REAL(KIND(1D0)), INTENT(in)::tau_r
       REAL(KIND(1D0)), INTENT(in)::SnowDensMax
       REAL(KIND(1D0)), INTENT(in)::SnowDensMin
       REAL(KIND(1D0)), INTENT(in)::SnowAlbMax
       REAL(KIND(1D0)), INTENT(in)::SnowAlbMin
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::SnowPack
       REAL(KIND(1d0)), INTENT(inout)::SnowAlb
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(inout)::SnowDens
       INTEGER::is
       REAL(KIND(1D0))::alb_change, &     !Change in snow albedo
                         dens_change, &    !Change in snow density
                         tau_1         !Number of seconds in a day
       !Initialize
       alb_change = 0
       dens_change = 0
       tau_1 = 24*60*60
       !==========================================================
       !Calculation of snow albedo by Lemonsu et al. 2010
       !(org: Verseghy (1991)&Baker et al.(1990))
       IF (sum(snowpack) > 0) THEN !Check if snow on any of the surfaces
          IF (temp_c_hr < 0) THEN
             !alb_change = tau_a*(60*60)/tau_1
             alb_change = tau_a*(tstep)/tau_1
             snowalb = snowalb - alb_change
          ELSE
             !alb_change = exp(-tau_f*(60*60)/tau_1)
             alb_change = exp(-tau_f*(tstep)/tau_1)
             snowalb = (snowalb - snowalbmin)*alb_change + snowalbmin
          ENDIF
          IF (snowalb < snowalbmin) snowalb = snowalbmin !Albedo cannot be smaller than the min albedo
          IF (snowalb > snowalbmax) snowalb = snowalbmax !Albedo cannot be larger than the max albedo
          if (snowalb < 0) print *, 'SnowAlbMin/max in SnowUpdate', snowalbmin, snowalbmax, snowalb
       ELSE
          snowalb = 0
       ENDIF
       if (snowalb < 0) print *, 'SnowAlb in SnowUpdate', snowalb
       !Update snow density: There is a mistake in Järvi et al. (2014): tau_h should be tau_1
       DO is = 1, nsurf
          !If SnowPack existing
          IF (snowpack(is) > 0) THEN
             dens_change = exp(-tau_r*(tstep)/tau_1)
             IF (snowpack(is) > 0) snowdens(is) = (snowdens(is) - snowdensmax)*dens_change + snowdensmax
             IF (snowdens(is) > snowdensmax) snowdens(is) = snowdensmax
          ELSE
             snowdens(is) = snowdensmin
          ENDIF
       ENDDO
Referenced by dailystate_module::suews_cal_dailystate().
veg_fr_snow()
subroutine snow_module::veg_fr_snow (real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(in) snowFrac, integer, intent(in) nsurf, real(kind(1d0)), intent(out) veg_fr)
Parameters
[in] nsurf number of surface types
[in] sfr surface fractions
[in] snowfrac snowy surface fractions [-]
[out] veg_fr vegetated surface fractions [-]
Definition at line 1272 of file suews_phys_snow.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in) :: nsurf
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in) :: sfr
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in) :: snowFrac
       REAL(KIND(1d0)), INTENT(out) :: veg_fr
       veg_fr = dot_product(sfr(3:7), 1 - snowfrac(3:7))
Referenced by snow_cal_meltheat().