SUEWS: physconstants Module Reference
physconstants Module Reference
Variables
real(kind(1d0)), parameter c2k = 273.15
real(kind(1d0)), parameter sbconst = 5.67051e-8
real(kind(1d0)), parameter jtoumolpar = 4.6
real(kind(1d0)), parameter kdntopar = 0.46
Variable Documentation
c2k
real(kind(1d0)), parameter physconstants::c2k = 273.15
Definition at line 2295 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER :: C2K = 273.15   !Celsius to Kelvin
Referenced by estm_module::estm(), estm_module::estm_initials(), and estm_module::estm_translate().
jtoumolpar
real(kind(1d0)), parameter physconstants::jtoumolpar = 4.6
Definition at line 2297 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER :: JtoumolPAR = 4.6   ! Convert PAR from W m-2 to umol m-2 s-1
kdntopar
real(kind(1d0)), parameter physconstants::kdntopar = 0.46
Definition at line 2298 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER :: KdntoPAR = 0.46    ! Conversion from Kdn to PAR, originally from Tsubo and Walker (2005), used in Bellucco et al. (2017)
sbconst
real(kind(1d0)), parameter physconstants::sbconst = 5.67051e-8
Definition at line 2296 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER :: SBConst = 5.67051e-8   !Stefan Boltzmann constant [W m-2 K-4]
Referenced by estm_module::estm(), and estm_module::estm_translate().