SUEWS: qsort_c_module Module Reference
qsort_c_module Module Reference
Functions/Subroutines
recursive subroutine, public qsortc (A)
subroutine, private partition (A, marker)
Function/Subroutine Documentation
partition()
subroutine, private qsort_c_module::partition (real, dimension(:), intent(inout) A, integer, intent(out) marker) private
Definition at line 29 of file suews_util_qsort.f95.
       REAL, INTENT(in out), DIMENSION(:) :: A
       INTEGER, INTENT(out) :: marker
       INTEGER :: i, j
       REAL :: temp
       REAL :: x      ! pivot point
       x = a(1)
       i = 0
       j = SIZE(a) + 1
       DO
          j = j - 1
          DO
             IF (a(j) <= x) EXIT
             j = j - 1
          END DO
          i = i + 1
          DO
             IF (a(i) >= x) EXIT
             i = i + 1
          END DO
          IF (i < j) THEN
             ! exchange A(i) and A(j)
             temp = a(i)
             a(i) = a(j)
             a(j) = temp
          ELSEIF (i == j) THEN
             marker = i + 1
             RETURN
          ELSE
             marker = i
             RETURN
          ENDIF
       END DO
Referenced by qsortc().
qsortc()
recursive subroutine, public qsort_c_module::qsortc (real, dimension(:), intent(inout) A)
Definition at line 18 of file suews_util_qsort.f95.
       REAL, INTENT(in out), DIMENSION(:) :: A
       INTEGER :: iq
       IF (SIZE(a) > 1) THEN
          CALL partition(a, iq)
          CALL qsortc(a(:iq - 1))
          CALL qsortc(a(iq:))
       ENDIF
References partition().
Referenced by ctrl_output::sortgrid(), and ctrl_output::sortseqreal().