SUEWS: mod_timedelta Module Reference
mod_timedelta Module Reference
Data Types
interface timedelta
Functions/Subroutines
pure elemental type(timedelta) function timedelta_constructor (days, hours, minutes, seconds, milliseconds)
pure elemental integer function getdays (self)
pure elemental integer function gethours (self)
pure elemental integer function getminutes (self)
pure elemental integer function getseconds (self)
pure elemental integer function getmilliseconds (self)
pure elemental real(kind=real64) function total_seconds (self)
pure elemental type(timedelta) function timedelta_plus_timedelta (t0, t1)
pure elemental type(timedelta) function timedelta_minus_timedelta (t0, t1)
pure elemental type(timedelta) function unary_minus_timedelta (t0)
pure elemental logical function eq (td0, td1)
pure elemental logical function neq (td0, td1)
pure elemental logical function gt (td0, td1)
pure elemental logical function ge (td0, td1)
pure elemental logical function lt (td0, td1)
pure elemental logical function le (td0, td1)
Function/Subroutine Documentation
eq()
pure elemental logical function mod_timedelta::eq (class(timedelta), intent(in) td0, type(timedelta), intent(in) td1) private
Definition at line 359 of file suews_util_datetime.f95.
       !! `timedelta` object comparison operator. Returns `.true.` if `td0`
       !! is equal to `td1` and `.false.` otherwise. Overloads the operator
       !! `==`.
       class(timedelta), intent(in) :: td0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: td1 !! rhs `timedelta` instance
       eq = td0%total_seconds() == td1%total_seconds()
Referenced by mod_timedelta::timedelta::operator().
ge()
pure elemental logical function mod_timedelta::ge (class(timedelta), intent(in) td0, type(timedelta), intent(in) td1) private
Definition at line 398 of file suews_util_datetime.f95.
       !! `timedelta` object comparison operator. Returns `.true.` if `td0`
       !! is greater than or equal to `td1` and `.false.` otherwise.
       !! Overloads the operator >=.
       class(timedelta), intent(in) :: td0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: td1 !! rhs `timedelta` instance
       ge = td0%total_seconds() >= td1%total_seconds()
Referenced by mod_timedelta::timedelta::operator().
getdays()
pure elemental integer function mod_timedelta::getdays (class(timedelta), intent(in) self) private
Definition at line 268 of file suews_util_datetime.f95.
       !! Returns the number of days.
       class(timedelta), intent(in) :: self !! `timedelta` instance
       getdays = self%days
gethours()
pure elemental integer function mod_timedelta::gethours (class(timedelta), intent(in) self) private
Definition at line 274 of file suews_util_datetime.f95.
       !! Returns the number of hours.
       class(timedelta), intent(in) :: self !! `timedelta` instance
       gethours = self%hours
getmilliseconds()
pure elemental integer function mod_timedelta::getmilliseconds (class(timedelta), intent(in) self) private
Definition at line 292 of file suews_util_datetime.f95.
       !! Returns the number of milliseconds.
       class(timedelta), intent(in) :: self !! `timedelta` instance
       getmilliseconds = self%milliseconds
getminutes()
pure elemental integer function mod_timedelta::getminutes (class(timedelta), intent(in) self) private
Definition at line 280 of file suews_util_datetime.f95.
       !! Returns the number of minutes.
       class(timedelta), intent(in) :: self !! `timedelta` instance
       getminutes = self%minutes
getseconds()
pure elemental integer function mod_timedelta::getseconds (class(timedelta), intent(in) self) private
Definition at line 286 of file suews_util_datetime.f95.
       !! Returns the number of seconds.
       class(timedelta), intent(in) :: self !! `timedelta` instance
       getseconds = self%seconds
gt()
pure elemental logical function mod_timedelta::gt (class(timedelta), intent(in) td0, type(timedelta), intent(in) td1) private
Definition at line 385 of file suews_util_datetime.f95.
       !! `timedelta` object comparison operator. Returns `.true.` if
       !! `td0` is greater than `td1` and `.false.` otherwise. Overloads the
       !! operator `>`.
       class(timedelta), intent(in) :: td0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: td1 !! rhs `timedelta` instance
       gt = td0%total_seconds() > td1%total_seconds()
Referenced by mod_timedelta::timedelta::operator().
le()
pure elemental logical function mod_timedelta::le (class(timedelta), intent(in) td0, type(timedelta), intent(in) td1) private
Definition at line 424 of file suews_util_datetime.f95.
       !! `timedelta` object comparison operator. Returns `.true.` if `td0`
       !! is less than or equal to `td1` and `.false.` otherwise. Overloads
       !! the operator `<=`.
       class(timedelta), intent(in) :: td0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: td1 !! rhs `timedelta` instance
       le = td0%total_seconds() <= td1%total_seconds()
Referenced by mod_timedelta::timedelta::operator().
lt()
pure elemental logical function mod_timedelta::lt (class(timedelta), intent(in) td0, type(timedelta), intent(in) td1) private
Definition at line 411 of file suews_util_datetime.f95.
       !! `timedelta` object comparison operator. Returns `.true.` if `td0`
       !! is less than `td1` and `.false.` otherwise. Overloads the operator
       !! `<`.
       class(timedelta), intent(in) :: td0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: td1 !! rhs `timedelta` instance
       lt = td0%total_seconds() < td1%total_seconds()
Referenced by mod_timedelta::timedelta::operator().
neq()
pure elemental logical function mod_timedelta::neq (class(timedelta), intent(in) td0, type(timedelta), intent(in) td1) private
Definition at line 372 of file suews_util_datetime.f95.
       !! `timedelta` object comparison operator. Returns `.true.` if `td0`
       !! is not equal to `td1` and `.false.` otherwise. Overloads the
       !! operator `/=`.
       class(timedelta), intent(in) :: td0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: td1 !! rhs `timedelta` instance
       neq = .not. (td0%total_seconds() == td1%total_seconds())
Referenced by mod_timedelta::timedelta::operator().
timedelta_constructor()
pure elemental type(timedelta) function mod_timedelta::timedelta_constructor (integer, intent(in), optional days, integer, intent(in), optional hours, integer, intent(in), optional minutes, integer, intent(in), optional seconds, integer, intent(in), optional milliseconds) private
Definition at line 223 of file suews_util_datetime.f95.
       !! Constructor function for the `timedelta` class.
       integer, intent(in), optional :: days         !! number of days
       integer, intent(in), optional :: hours        !! number of hours
       integer, intent(in), optional :: minutes      !! number of minutes
       integer, intent(in), optional :: seconds      !! number of seconds
       integer, intent(in), optional :: milliseconds !! number of milliseconds
       if (present(days)) then
          timedelta_constructor%days = days
       else
          timedelta_constructor%days = 0
       endif
       if (present(hours)) then
          timedelta_constructor%hours = hours
       else
          timedelta_constructor%hours = 0
       endif
       if (present(minutes)) then
          timedelta_constructor%minutes = minutes
       else
          timedelta_constructor%minutes = 0
       endif
       if (present(seconds)) then
          timedelta_constructor%seconds = seconds
       else
          timedelta_constructor%seconds = 0
       endif
       if (present(milliseconds)) then
          timedelta_constructor%milliseconds = milliseconds
       else
          timedelta_constructor%milliseconds = 0
       endif
Referenced by mod_timedelta::timedelta::operator().
timedelta_minus_timedelta()
pure elemental type(timedelta) function mod_timedelta::timedelta_minus_timedelta (class(timedelta), intent(in) t0, type(timedelta), intent(in) t1) private
Definition at line 330 of file suews_util_datetime.f95.
       !! Subtracts a `timedelta` instance from another. Returns a
       !! `timedelta` instance. Overloads the operator `-`.
       class(timedelta), intent(in) :: t0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: t1 !! lhs `timedelta` instance
       type(timedelta)             :: t  !! result
       t = t0 + (-t1)
Referenced by mod_timedelta::timedelta::operator().
timedelta_plus_timedelta()
pure elemental type(timedelta) function mod_timedelta::timedelta_plus_timedelta (class(timedelta), intent(in) t0, type(timedelta), intent(in) t1) private
Definition at line 313 of file suews_util_datetime.f95.
       !! Adds two `timedelta` instances together and returns a `timedelta`
       !! instance. Overloads the operator `+`.
       class(timedelta), intent(in) :: t0 !! lhs `timedelta` instance
       type(timedelta), intent(in) :: t1 !! rhs `timedelta` instance
       type(timedelta)             :: t  !! result
       t = timedelta(days=t0%days + t1%days, &
                     hours=t0%hours + t1%hours, &
                     minutes=t0%minutes + t1%minutes, &
                     seconds=t0%seconds + t1%seconds, &
                     milliseconds=t0%milliseconds + t1%milliseconds)
Referenced by mod_timedelta::timedelta::operator().
total_seconds()
pure elemental real(kind=real64) function mod_timedelta::total_seconds (class(timedelta), intent(in) self) private
Definition at line 298 of file suews_util_datetime.f95.
       !! Returns a total number of seconds contained in a `timedelta`
       !! instance.
       class(timedelta), intent(in) :: self !! `timedelta` instance
       total_seconds = self%days*86400._real64 &
                       + self%hours*3600._real64 &
                       + self%minutes*60._real64 &
                       + self%seconds &
                       + self%milliseconds*1e-3_real64
unary_minus_timedelta()
pure elemental type(timedelta) function mod_timedelta::unary_minus_timedelta (class(timedelta), intent(in) t0) private
Definition at line 343 of file suews_util_datetime.f95.
       !! Takes a negative of a `timedelta` instance. Overloads the operator
       !! `-`.
       class(timedelta), intent(in) :: t0 !! `timedelta` instance
       type(timedelta)             :: t  !! result
       t%days = -t0%days
       t%hours = -t0%hours
       t%minutes = -t0%minutes
       t%seconds = -t0%seconds
       t%milliseconds = -t0%milliseconds
Referenced by mod_timedelta::timedelta::operator().