SUEWS: metdisagg Module Reference
metdisagg Module Reference
Functions/Subroutines
subroutine disaggregatemet (iBlock, igrid)
subroutine disaggregateestm (iBlock)
subroutine disaggregatedatetime (DateTimeForDisagg, tstep, Nper, ReadLinesOrigMetDataMax, DateTimeDscd)
real(kind(1d0)) function, dimension(readlinesorig_loc *nper_loc) disagg_lin (Slow, SlowPrev, SlowNext, DisaggType, Nper_loc, ReadLinesOrig_loc, ReadLinesOrigMax_loc, iBlock)
real(kind(1d0)) function, dimension(readlinesorig_loc *nper_loc) disaggp_amongn (Slow, amongN, Nper_loc, ReadLinesOrig_loc, ReadLinesOrigMax_loc)
real(kind(1d0)) function, dimension(readlinesorig_loc *nper_loc) disaggp_amongnmult (Slow, multupperI, multamongN, Nper_loc, ReadLinesOrig_loc, ReadLinesOrigMax_loc)
integer function, dimension(:), allocatable randomsamples (N, OutOf)
Function/Subroutine Documentation
disagg_lin()
real(kind(1d0)) function, dimension(readlinesorig_loc*nper_loc) metdisagg::disagg_lin (real(kind(1d0)), dimension(readlinesorig_loc) Slow, real(kind(1d0)) SlowPrev, real(kind(1d0)) SlowNext, integer DisaggType, integer Nper_loc, integer ReadLinesOrig_loc, integer ReadLinesOrigMax_loc, integer iBlock)
Definition at line 1908 of file suews_ctrl_input.f95.
       USE defaultnotused
       USE sues_data
       IMPLICIT NONE
       INTEGER:: DisaggType   !Type of disaggregation: 10 for averaged variables; 20 for instantaneous variables
       INTEGER:: Nper_loc     !Number of subintervals per interval (local Nper)
       INTEGER:: ReadLinesOrig_loc, ReadLinesOrigMax_loc   !Number of lines to read in original file (local)
       INTEGER:: iBlock
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrig_loc*Nper_loc):: Fast  !Array to receive disaggregated data
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrig_loc):: Slow   !Array to disaggregate
       REAL(KIND(1d0)):: SlowPrev, SlowNext
       INTEGER, DIMENSION(Nper_loc):: FastRows   !Group of rows that are filled with each iteration
       INTEGER, DIMENSION(FLOOR(Nper_loc/2.0)):: FirstRows10   !Rows at the beginning that are not filled during iteration (for averages)
       INTEGER, DIMENSION(Nper_loc - FLOOR(Nper_loc/2.0)):: LastRows10    !Rows at the end that are not filled during iteration
       INTEGER, DIMENSION(Nper_loc):: FirstRows20   !Rows at the beginning that are not filled during iteration (for instantaneous)
       INTEGER, DIMENSION(Nper_loc):: seq1Nper_loc   !1 to Nper_loc
       INTEGER:: XNper_loc   !XNper_loc = 2 for even Nper_loc; XNper_loc=1 for odd Nper_loc
       INTEGER:: i, ii   !counters
       ! Calculate XNper_loc (differentiates between disaggregations with odd and even Nper_loc)
       IF (mod(nper_loc, 2) == 0) xnper_loc = 2
       IF (mod(nper_loc, 2) == 1) xnper_loc = 1
       seq1nper_loc = (/(i, i=1, nper_loc, 1)/)
       ! Setup counters for iteration
       IF (disaggtype == 10) THEN
          fastrows = floor(nper_loc/2.0) + seq1nper_loc  ! Rows to create at model time-step
          firstrows10 = (/(i, i=1, (fastrows(1) - 1), 1)/)   !For start of dataset
          lastrows10 = &
             (/(i, i=nper_loc*(readlinesorigmax_loc - 1 - 1) + fastrows(nper_loc) + 1, &
                (readlinesorigmax_loc*nper_loc), 1)/)  ! For end of dataset
       ELSEIF (disaggtype == 20) THEN
          fastrows = nper_loc + seq1nper_loc   !Rows to create at model time-step
          firstrows20 = (/(i, i=1, (fastrows(1) - 1), 1)/)   !For start of dataset
       ENDIF
       ! Initialise fast array to -999
       fast = -999
       ! Linearly disaggregate
       IF (disaggtype == 10) THEN   !Averaged variables
          IF (diagnosedisagg == 1) WRITE (*, *) 'Linearly disaggregating averaged variable'
          DO i = 1, (readlinesorigmax_loc - 1)
             fast(nper_loc*(i - 1) + fastrows) = slow(i) - &
                                                 (slow(i + 1) - slow(i))/(xnper_loc*nper_loc) + &
                                                 (slow(i + 1) - slow(i))/nper_loc*(/(ii, ii=1, nper_loc, 1)/)
          ENDDO
          ! For first few rows, use previous met block
          IF (iblock == 1) THEN
             fast(firstrows10) = fast(fastrows(1))   !Use repeat values at the start of the year
          ELSE
             fast(firstrows10) = slowprev - &
                                 (slow(1) - slowprev)/(xnper_loc*nper_loc) + &
                                 (slow(1) - slowprev)/nper_loc* &
                                 (/(ii, ii=(nper_loc - SIZE(firstrows10) + 1), nper_loc, 1)/)
          ENDIF
          ! For last few rows, use next met block
          IF (iblock == readblocksorigmetdata) THEN
             fast(lastrows10) = fast(nper_loc*(readlinesorigmax_loc - 1 - 1) + fastrows(nper_loc))   !Use repeat values at the end of the year
          ELSE
             fast(lastrows10) = slow(readlinesorigmax_loc) - &
                                (slownext - slow(readlinesorigmax_loc))/(xnper_loc*nper_loc) + &
                                (slownext - slow(readlinesorigmax_loc))/nper_loc* &
                                (/(ii, ii=1, SIZE(lastrows10), 1)/)
          ENDIF
       ELSEIF (disaggtype == 20) THEN   !Instantaneous variables
          IF (diagnosedisagg == 1) WRITE (*, *) 'Linearly disaggregating instantaneous variable'
          DO i = 1, (readlinesorigmax_loc - 1)
             fast(nper_loc*(i - 1) + fastrows) = (slow(i) + &
                                                  (slow(i + 1) - slow(i))/nper_loc*2*(seq1nper_loc - 1) + &
                                                  slow(i))/2
          ENDDO
          ! For first few rows, use previous met block
          IF (iblock == 1) THEN
             fast(firstrows20) = fast(fastrows(1))   !Use repeat values at the start of the year
          ELSE
             fast(firstrows20) = (slowprev + &
                                  (slow(1) - slowprev)/nper_loc*2* &
                                  ((/(ii, ii=(nper_loc - SIZE(firstrows20) + 1), nper_loc, 1)/) - 1) + &
                                  slowprev)/2
          ENDIF
          !! Last few rows are already filled for the instantaneous value disaggregation
          !IF(iBlock==ReadBlocksOrigMetData) THEN
          !   Fast(LastRows20) = Fast(Nper_loc*(ReadLinesOrigMax_loc-1-1)+FastRows(Nper_loc))   !Use repeat values at the end of the year
          !ELSE
          !   Fast(LastRows20) = (Slow(ReadLinesOrigMax_loc) + &
          !                     (SlowNext-Slow(ReadLinesOrigMax_loc))/Nper_loc*2 * &
          !                        ((/(ii, ii=1,SIZE(LastRows20), 1)/)-1) + &
          !                       Slow(ReadLinesOrigMax_loc))/2
          !ENDIF
       ENDIF
       IF (any(fast(1:readlinesorigmax_loc*nper_loc) == -999)) THEN
          WRITE (*, *) 'Problem: -999s (', count(fast(1:readlinesorigmax_loc*nper_loc) == -999), ') in disaggregated data.'
          CALL errorhint(13, 'Problem in SUEWS_MetDisagg: -999 values in disaggregated data.', notused, notused, notusedi)
       ENDIF
References data_in::diagnosedisagg, errorhint(), defaultnotused::notused, defaultnotused::notusedi, and initial::readblocksorigmetdata.
Referenced by disaggregateestm(), and disaggregatemet().
disaggp_amongn()
real(kind(1d0)) function, dimension(readlinesorig_loc*nper_loc) metdisagg::disaggp_amongn (real(kind(1d0)), dimension(readlinesorig_loc) Slow, integer amongN, integer Nper_loc, integer ReadLinesOrig_loc, integer ReadLinesOrigMax_loc)
Definition at line 2013 of file suews_ctrl_input.f95.
       ! Subroutine to disaggregate precipitation by evenly distributing among N subintervals
       !  (i.e. equal intensity in N subintervals)
       ! See Ward et al. (in review), meanN, 0.5N or 0.25N approach
       ! HCW 10 Feb 2017
       !======================================================================================
       USE defaultnotused
       USE sues_data
       IMPLICIT NONE
       INTEGER:: amongN       !Number of subintervals over which rain will be distributed
       INTEGER:: Nper_loc     !Number of subintervals per interval (local Nper)
       INTEGER:: ReadLinesOrig_loc, ReadLinesOrigMax_loc   !Number of lines to read in original file (local)
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrig_loc*Nper_loc):: Fast  !Array to receive disaggregated data
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrig_loc):: Slow   !Array to disaggregate
       INTEGER, DIMENSION(:), ALLOCATABLE:: Subintervals  !Array of subintervals that contain rain
       INTEGER, DIMENSION(Nper_loc):: seq1Nper_loc   !1 to Nper_loc
       INTEGER:: i
       ! For each averaging period, get subintervals which will receive rain
       ALLOCATE (subintervals(amongn))
       subintervals(:) = -999
       seq1nper_loc = (/(i, i=1, nper_loc, 1)/)
       IF (diagnosedisagg == 1) WRITE (*, *) 'Distributing over ', amongn, ' subintervals for variable'
       ! If all subintervals are to contain rain, don't need to generate random numbers
       IF (amongn == nper_loc) THEN
          subintervals(:) = seq1nper_loc
       ENDIF
       IF (amongn > nper_loc) &
          CALL errorhint(2, 'Problem in SUEWS_MetDisagg: no. of rainy periods cannot exceed number of subintervals', &
                         REAL(Nper_loc, KIND(1d0)), NotUsed, amongN)
       ! Initialise fast array to -999
       fast = -999
       DO i = 1, readlinesorigmax_loc
          fast(nper_loc*(i - 1) + seq1nper_loc) = 0   !Fill all subintervals with zeros initially
          IF (slow(i) > 0) THEN   !If there is some rainfall during this interval...
             IF (amongn < nper_loc) THEN
                subintervals(:) = -999
                subintervals = randomsamples(amongn, nper_loc)
             ENDIF
             fast(nper_loc*(i - 1) + subintervals) = slow(i)/amongn
          ENDIF
       ENDDO
       IF (any(fast(1:readlinesorigmax_loc*nper_loc) == -999)) THEN
          WRITE (*, *) 'Problem: -999s (', count(fast(1:readlinesorigmax_loc*nper_loc) == -999), ') in disaggregated data'
          CALL errorhint(13, 'Problem in SUEWS_MetDisagg: -999 values in disaggregated data.', notused, notused, notusedi)
       ENDIF
References data_in::diagnosedisagg, errorhint(), defaultnotused::notused, defaultnotused::notusedi, and randomsamples().
Referenced by disaggregatemet().
disaggp_amongnmult()
real(kind(1d0)) function, dimension(readlinesorig_loc*nper_loc) metdisagg::disaggp_amongnmult (real(kind(1d0)), dimension(readlinesorig_loc) Slow, real(kind(1d0)), dimension(5) multupperI, integer, dimension(5) multamongN, integer Nper_loc, integer ReadLinesOrig_loc, integer ReadLinesOrigMax_loc)
Definition at line 2071 of file suews_ctrl_input.f95.
       ! Subroutine to disaggregate precipitation by evenly distributing among N subintervals
       !  (i.e. equal intensity in N subintervals) for different intensity bins
       ! Based on analsysis by Wen Gu
       ! HCW 21 Apr 2017
       !======================================================================================
       USE defaultnotused
       USE sues_data
       IMPLICIT NONE
       REAL(KIND(1d0)), DIMENSION(5):: multupperI     !Upper bound of intensity bin
       INTEGER, DIMENSION(5):: multamongN       !Number of subintervals over which rain will be distributed (array)
       INTEGER:: thisamongN       !Number of subintervals over which rain will be distributed
       INTEGER:: Nper_loc     !Number of subintervals per interval (local Nper)
       INTEGER:: ReadLinesOrig_loc, ReadLinesOrigMax_loc   !Number of lines to read in original file (local)
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrig_loc*Nper_loc):: Fast  !Array to receive disaggregated data
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrig_loc):: Slow   !Array to disaggregate
       INTEGER, DIMENSION(:), ALLOCATABLE:: Subintervals  !Array of subintervals that contain rain
       INTEGER, DIMENSION(Nper_loc):: seq1Nper_loc   !1 to Nper_loc
       INTEGER:: i
       seq1nper_loc = (/(i, i=1, nper_loc, 1)/)
       IF (diagnosedisagg == 1) WRITE (*, *) 'Distributing over variable subintervals depending on intensity for variable'
       ! Initialise fast array to -999
       fast = -999
       DO i = 1, readlinesorigmax_loc
          fast(nper_loc*(i - 1) + seq1nper_loc) = 0   !Fill all subintervals with zeros initially
          IF (slow(i) > 0) THEN   !If there is some rainfall during this interval...
             !Use intensity in this interval to decide number of subintervals to fill with rain
             IF (slow(i) <= multupperi(1)) THEN
                thisamongn = multamongn(1)
             ELSEIF (slow(i) > multupperi(1) .AND. slow(i) <= multupperi(2)) THEN
                thisamongn = multamongn(2)
             ELSEIF (slow(i) > multupperi(2) .AND. slow(i) <= multupperi(3)) THEN
                thisamongn = multamongn(3)
             ELSEIF (slow(i) > multupperi(3) .AND. slow(i) <= multupperi(4)) THEN
                thisamongn = multamongn(4)
             ELSEIF (slow(i) > multupperi(4) .AND. slow(i) <= multupperi(5)) THEN
                thisamongn = multamongn(5)
             ELSEIF (slow(i) > multupperi(5)) THEN
                thisamongn = multamongn(5)
                CALL errorhint(4, 'Precip in met forcing file exceeds maxiumum MultRainAmongNUpperI', &
                               slow(i), multrainamongnupperi(5), notusedi)
             ENDIF
             ! For each averaging period, get subintervals which will receive rain
             ALLOCATE (subintervals(thisamongn))
             subintervals(:) = -999
             IF (thisamongn > nper_loc) CALL errorhint(2, 'Problem in SUEWS_MetDisagg: no. of rainy periods cannot exceed '// &
                                                       'number of subintervals', real(nper_loc, kind(1d0)), notused, thisamongn)
             IF (thisamongn == nper_loc) THEN   ! If all subintervals are to contain rain, don't need to generate random numbers
                subintervals(:) = seq1nper_loc
             ELSEIF (thisamongn < nper_loc) THEN
                subintervals = randomsamples(thisamongn, nper_loc)
             ENDIF
             fast(nper_loc*(i - 1) + subintervals) = slow(i)/thisamongn
             !write(*,*) Slow(i), thisamongN
             DEALLOCATE (subintervals)
          ENDIF
       ENDDO
       IF (any(fast(1:readlinesorigmax_loc*nper_loc) == -999)) THEN
          WRITE (*, *) 'Problem: -999s (', count(fast(1:readlinesorigmax_loc*nper_loc) == -999), ') in disaggregated data'
          CALL errorhint(13, 'Problem in SUEWS_MetDisagg: -999 values in disaggregated data.', notused, notused, notusedi)
       ENDIF
References data_in::diagnosedisagg, errorhint(), data_in::multrainamongnupperi, defaultnotused::notused, defaultnotused::notusedi, and randomsamples().
Referenced by disaggregatemet().
disaggregatedatetime()
subroutine metdisagg::disaggregatedatetime (real(kind(1d0)), dimension(readlinesorigmetdata, 4), intent(in) DateTimeForDisagg, integer, intent(in) tstep, integer, intent(in) Nper, integer, intent(in) ReadLinesOrigMetDataMax, real(kind(1d0)), dimension(readlinesorigmetdata*nper, 4), intent(out) DateTimeDscd)
Definition at line 1854 of file suews_ctrl_input.f95.
       USE datetime_module, ONLY: daysinyear
       IMPLICIT NONE
       INTEGER, INTENT(in) :: tstep, Nper, ReadLinesOrigMetDataMax
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigMetData, 4), INTENT(in):: DateTimeForDisagg
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigMetData*Nper, 4), INTENT(out):: DateTimeDscd
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigMetData):: dectimeOrig
       REAL(KIND(1d0)), DIMENSION(Nper) :: temp_dectime  !temorary varaibles for disaggragation
       INTEGER, DIMENSION(Nper):: temp_iy, temp_id, temp_ih, temp_im, temp_ihm ! temorary varaibles for disaggragation
       INTEGER, DIMENSION(Nper)::ndays_iy ! number of days in iy
       INTEGER :: i, ii
       INTEGER, DIMENSION(Nper):: seq1Nper
       ! Generate useful sequences
       seq1nper = (/(i, i=1, nper, 1)/)
       ! Convert to dectime
       ! dectimeOrig = MetForDisagg(:,2) + MetForDisagg(:,3)/24.0 + MetForDisagg(:,4)/(60.0*24.0)
       ! correct to dectime(year_start)=0 and dectime(year_end)=days of year (i.e., 365 or 366 if leap year) ! TS 09 May 2018
       dectimeorig = (datetimefordisagg(:, 2) - 1) + datetimefordisagg(:, 3)/24.0 + datetimefordisagg(:, 4)/(60.0*24.0)
       DO i = 1, readlinesorigmetdatamax
          ! Downscale dectime using dectimeOrig(i) [becomes timestamp of last subinterval]
          temp_dectime = dectimeorig(i) - (tstep/60.0)/(60.0*24.0)*(/(ii, ii=(nper - 1), 0, -1)/)
          temp_dectime = nint(temp_dectime*60*60*24)/(60*60*24*1.)
          ! Convert to required formats
          ! get year: year-1 if dectime <0, copy `year` from metforcing otherwise
          temp_iy = merge(int(datetimefordisagg(i, 1)) - 1, int(datetimefordisagg(i, 1)), temp_dectime < 0)
          ! get day of year:
          ndays_iy = daysinyear(temp_iy) ! get days of year for DOY correction when temp_dectime<0 during year-crossing
          temp_dectime = merge(temp_dectime + ndays_iy, temp_dectime, temp_dectime < 0) ! correct minus temp_dectime to positive values
          temp_id = floor(temp_dectime) + 1 !DOY
          temp_ihm = nint((temp_dectime + 1 - temp_id/1.0)*60.0*24.0)  !Minutes of the day (1440 max)
          temp_ih = (temp_ihm - mod(temp_ihm, 60))/60   !Hours
          temp_ih = merge(temp_ih, 0, mask=(temp_ih < 24))
          temp_im = mod(temp_ihm, 60)   !Minutes
          ! Copy to Met_tt array
          datetimedscd(nper*(i - 1) + seq1nper, 1) = temp_iy
          datetimedscd(nper*(i - 1) + seq1nper, 2) = temp_id
          datetimedscd(nper*(i - 1) + seq1nper, 3) = temp_ih
          datetimedscd(nper*(i - 1) + seq1nper, 4) = temp_im
       ENDDO
Referenced by disaggregateestm(), and disaggregatemet().
disaggregateestm()
subroutine metdisagg::disaggregateestm (integer iBlock)
Definition at line 1650 of file suews_ctrl_input.f95.
       ! Subroutine to disaggregate met forcing data to model time-step
       ! HCW 10 Feb 2017
       !======================================================================================
       USE sues_data
       USE defaultnotused
       IMPLICIT NONE
       INTEGER:: lunit = 101
       INTEGER:: tdiff   !Time difference (in minutes) between first and second rows of original met forcing file
       INTEGER:: i, ii  !counter
       INTEGER:: iBlock
       INTEGER, DIMENSION(NperESTM):: seq1NperESTM
       INTEGER, DIMENSION(nsd):: seq1nsd
       INTEGER, DIMENSION(ncolsESTMdata):: ESTMDisaggMethod   ! Stores method to use for disaggregating met data
       REAL(KIND(1d0)), DIMENSION(ncolsESTMdata):: ESTMArrayOrig
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigESTMData*NperESTM, ncolsESTMdata):: ESTM_tt
       CHARACTER(LEN=9), DIMENSION(ncolsESTMdata):: HeaderESTM
       CHARACTER(LEN=10*ncolsESTMdata):: HeaderESTMOut
       ! REAL(KIND(1d0)),DIMENSION(ReadLinesOrigESTMData):: dectimeOrig
       ! REAL(KIND(1d0)),DIMENSION(ReadLinesOrigESTMData*NperESTM):: dectimeDscd
       INTEGER::iostat_var
       ! INTEGER, DIMENSION(NperESTM):: temp_iy, temp_id, temp_ih, temp_im, temp_ihm
       ! Allocate and initialise arrays to receive original forcing data --------------------
       ALLOCATE (estmfordisagg(readlinesorigestmdata, ncolsestmdata))
       ALLOCATE (estmfordisaggprev(ncolsestmdata))
       ALLOCATE (estmfordisaggnext(ncolsestmdata))
       estmfordisagg(:, :) = -999
       estmfordisaggprev(:) = -999
       estmfordisaggnext(:) = -999
       ! Initialise array to receive disaggregated data
       estm_tt = -999
       ! Intialise disaggregation method
       estmdisaggmethod = -999
       ! Generate useful sequences
       seq1nperestm = (/(i, i=1, nperestm, 1)/)
       seq1nsd = (/(i, i=1, nsd, 1)/)
       ! Get methods to use for disaggregation from RunControl
       ! (N.B.DisaggMethodESTM is set as 1 or 2 in RunControl; ESTMDisaggMethod is array of ncolsESTMdata used here)
       IF (disaggmethodestm == 1) THEN
          estmdisaggmethod(:) = 10   !linear disaggregation of averages
       ELSEIF (disaggmethodestm == 2) THEN
          estmdisaggmethod(:) = 20   !linear disaggregation of instantaneous values
       ELSE
          CALL errorhint(2, 'Problem in SUEWS_ESTMDisagg: DisaggMethodESTM value should be 1 or 2', &
                         notused, notused, disaggmethodestm)
       ENDIF
       ! Read data ---------------------------------------------------------------------
       IF (diagnosedisaggestm == 1) WRITE (*, *) 'Reading file: ', trim(fileorigestm)
       OPEN (lunit, file=trim(fileorigestm), status='old')
       ! CALL skipHeader(lunit,SkipHeaderMet)  !Skip header -> read header instead
       READ (lunit, *) headerestm
       !write(*,*) HeaderMet
       ! Skip over lines that have already been read and downscaled
       IF (skippedlinesorigestm > 0) THEN
          DO i = 1, skippedlinesorigestm - 1   ! minus 1 here because last line of last block needs to be read again
             READ (lunit, *)
          ENDDO
          ! Read in last line of previous block
          READ (lunit, *, iostat=iostat_var) estmarrayorig
          estmfordisaggprev(1:ncolsestmdata) = estmarrayorig
       ENDIF
       ! Read in current block
       DO i = 1, readlinesorigestmdatamax
          READ (lunit, *, iostat=iostat_var) estmarrayorig
          estmfordisagg(i, 1:ncolsestmdata) = estmarrayorig
       ENDDO
       ! Read in first line of next block (except for last block)
       IF (iblock /= readblocksorigmetdata) THEN
          READ (lunit, *, iostat=iostat_var) estmarrayorig
          estmfordisaggnext(1:ncolsestmdata) = estmarrayorig
       ENDIF
       CLOSE (lunit)
       ! Check resolution of original met forcing data -------------------------------------
       ! Find time difference (in minutes) between first and second row
       tdiff = int(estmfordisagg(2, 4) - estmfordisagg(1, 4))   !Try using minutes
       IF (tdiff == 0) tdiff = int(estmfordisagg(2, 3) - estmfordisagg(1, 3))*60   !If no difference in minutes, try using hours
       IF (tdiff < 0) THEN   !If time difference is negative (e.g. change of day), instead use second and third row
          tdiff = int(estmfordisagg(3, 4) - estmfordisagg(2, 4))
          IF (tdiff == 0) tdiff = int(estmfordisagg(3, 3) - estmfordisagg(2, 3))*60   !If no difference in minutes, try using hours
       ENDIF
       ! Check actual resolution matches specified input resolution
       IF (tdiff /= resolutionfilesinestm/60) THEN
          CALL errorhint(2, 'Problem in SUEWS_ESTMDisagg: timestamps in ESTM forcing file inconsistent with ResolutionFilesInESTM', &
                         REAL(ResolutionFilesInESTM, KIND(1d0)), NotUsed, tdiff*60)
       ENDIF
       ! Disaggregate time columns ---------------------------------------------------------
       IF (diagnose == 1) THEN
          WRITE (*, *) 'Disaggregating ESTM forcing data (', trim(fileorigestm), ') to model time-step...'
       END IF
       CALL disaggregatedatetime(estmfordisagg(:, 1:4), tstep, nperestm, readlinesorigmetdatamax, estm_tt(:, 1:4))
       ! ! Convert to dectime
       ! dectimeOrig = ESTMForDisagg(:,2) + ESTMForDisagg(:,3)/24.0 + ESTMForDisagg(:,4)/(60.0*24.0)
       !
       ! DO i=1,ReadLinesOrigESTMDataMax
       !    ! Downscale dectime using dectimeOrig(i) [becomes timestamp of last subinterval]
       !    dectimeDscd(NperESTM*(i-1)+Seq1NperESTM) = dectimeOrig(i) - (tstep/60.0)/(60.0*24.0)*(/(ii, ii=(NperESTM-1),0, -1)/)
       !    ! Convert to required formats
       !    temp_iy   = INT(ESTMForDisagg(i,1))   !Copy year
       !    temp_id   = FLOOR(dectimeDscd(NperESTM*(i-1)+Seq1NperESTM))   !DOY
       !    ! To avoid precision errors, round here
       !    !  - this should not be a problem as a difference of 1 = 1 min, so a difference of 0.001 << 1 min
       !    temp_ihm  = NINT(((dectimeDscd(NperESTM*(i-1)+Seq1NperESTM) - temp_id/1.0)*60.0*24.0)*1000.0)/1000   !Minutes of the day (1440 max)
       !    temp_ih = (temp_ihm-MOD(temp_ihm,60))/60   !Hours
       !    temp_im = MOD(temp_ihm,60)   !Minutes
       !
       !    IF(dectimeOrig(i) == 1.0000 .AND. i > 1) THEN   !If year changes and it is not the beginning of the dataset
       !       WRITE(*,*) 'Year change encountered: ', dectimeOrig(i), dectimeOrig(i-1)
       !       ! Re-downscale dectime using dectimeOrig(i-1)
       !       dectimeDscd(NperESTM*(i-1)+Seq1NperESTM) = dectimeOrig(i-1) + (tstep/60.0)/(60.0*24.0)*Seq1NperESTM
       !       ! Convert to required formats
       !       temp_iy   = INT(ESTMForDisagg(i,1))   !Copy year
       !       temp_id   = FLOOR(dectimeDscd(NperESTM*(i-1)+Seq1NperESTM))   !DOY
       !       temp_ihm  = NINT(((dectimeDscd(NperESTM*(i-1)+Seq1NperESTM) - temp_id/1.0)*60.0*24.0)*1000.0)/1000   !Mins of the day (1440 max)
       !       temp_ih = (temp_ihm-MOD(temp_ihm,60))/60   !Hours
       !       temp_im = MOD(temp_ihm,60)   !Minutes
       !       ! Adjust year and DOY to account for year change
       !       temp_iy(1:(NperESTM-1)) = temp_iy(1:(NperESTM-1)) - 1  !Subtract 1 from year for all except final timestamp
       !       temp_id(NperESTM) = 1  !Set day for final timestamp to 1
       !    ENDIF
       !
       !    !IF(i==1 .or. i== ReadlinesOrigESTMDataMax) THEN
       !    !   write(*,*) temp_iy
       !    !   write(*,*) temp_id
       !    !   !write(*,*) temp_ihm
       !    !   write(*,*) temp_ih
       !    !   write(*,*) temp_im
       !    !ENDIF
       !
       !    ! Copy to ESTM_tt array
       !    ESTM_tt(NperESTM*(i-1)+Seq1NperESTM,1) = temp_iy
       !    ESTM_tt(NperESTM*(i-1)+Seq1NperESTM,2) = temp_id
       !    ESTM_tt(NperESTM*(i-1)+Seq1NperESTM,3) = temp_ih
       !    ESTM_tt(NperESTM*(i-1)+Seq1NperESTM,4) = temp_im
       !
       ! ENDDO
       ! Disaggregate other columns --------------------------------------------------------
       ! All other columns are temperatures
       DO ii = 5, ncolsestmdata
          IF (all(estmfordisagg(:, ii) == -999)) THEN
             !IF(DiagnoseDisaggESTM==1) write(*,*) 'No data for col.', ii
             estm_tt(:, ii) = -999
          ELSE
             estm_tt(:, ii) = disagg_lin(estmfordisagg(:, ii), estmfordisaggprev(ii), estmfordisaggnext(ii), estmdisaggmethod(ii), &
                                         nperestm, readlinesorigestmdata, readlinesorigestmdatamax, iblock)
          ENDIF
       ENDDO
       ! Copy disaggregated data to MetForcingDataArray
       estmforcingdata(:, 1:ncolsestmdata, gridcounter) = estm_tt(:, 1:ncolsestmdata)
       ! Write out disaggregated file ------------------------------------------------------
       IF (keeptstepfilesin == 1) THEN
          IF (iblock == 1) THEN
             ! Prepare header
             DO i = 1, ncolsestmdata
                IF (i == 1) THEN
                   headerestmout = adjustl(headerestm(i))
                ELSE
                   headerestmout = trim(headerestmout)//' '//adjustl(headerestm(i))
                ENDIF
             ENDDO
             ! Write out header
             OPEN (78, file=trim(filedscdestm), err=113)
             WRITE (78, '(a)') headerestmout
          ELSE
             OPEN (78, file=trim(filedscdestm), position='append')!,err=113)
          ENDIF
          ! Write out data
          DO i = 1, (readlinesorigestmdatamax*nperestm)
             WRITE (78, 304) (int(estm_tt(i, ii)), ii=1, 4), estm_tt(i, 5:ncolsestmdata)
          ENDDO
          !IF(iBlock == ReadBlocksOrigMetData) THEN
          !   WRITE(78,'(i2)') -9
          !   WRITE(78,'(i2)') -9
          !ENDIF
          CLOSE (78)   !Close output file
       ENDIF
 304   FORMAT((i4, 1x), 3(i3, 1x), 9(f9.4, 1x))
       ! Deallocate arrays -----------------------------------------------------------------
       DEALLOCATE (estmfordisagg)
       DEALLOCATE (estmfordisaggprev)
       DEALLOCATE (estmfordisaggnext)
       RETURN
 113   CALL errorhint(52, trim(filedscdestm), notused, notused, notusedi)
References data_in::diagnose, data_in::diagnosedisaggestm, disagg_lin(), data_in::disaggmethodestm, disaggregatedatetime(), errorhint(), allocatearray::estmforcingdata, allocatearray::estmfordisagg, allocatearray::estmfordisaggnext, allocatearray::estmfordisaggprev, data_in::filedscdestm, data_in::fileorigestm, initial::gridcounter, data_in::keeptstepfilesin, allocatearray::ncolsestmdata, defaultnotused::notused, defaultnotused::notusedi, sues_data::nperestm, sues_data::nsd, initial::readblocksorigmetdata, initial::readlinesorigestmdata, initial::readlinesorigestmdatamax, initial::readlinesorigmetdatamax, data_in::resolutionfilesinestm, initial::skippedlinesorigestm, and sues_data::tstep.
Referenced by suews_program().
disaggregatemet()
subroutine metdisagg::disaggregatemet (integer iBlock, integer igrid)
Definition at line 1380 of file suews_ctrl_input.f95.
       ! Subroutine to disaggregate met forcing data to model time-step
       ! HCW 10 Feb 2017
       !======================================================================================
       USE sues_data
       USE defaultnotused
       IMPLICIT NONE
       INTEGER:: lunit = 100
       INTEGER:: tdiff   !Time difference (in minutes) between first and second rows of original met forcing file
       INTEGER:: i, ii  !counter
       INTEGER:: iBlock, igrid
       INTEGER, DIMENSION(Nper):: seq1Nper
       INTEGER, DIMENSION(nsd):: seq1nsd
       INTEGER, DIMENSION(nColumnsMetForcingData):: MetDisaggMethod   ! Stores method to use for disaggregating met data
       REAL(KIND(1d0)), DIMENSION(nColumnsMetForcingData):: MetArrayOrig
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigMetData*Nper, ncolumnsMetForcingData):: Met_tt
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigMetData*Nper):: Met_tt_kdownAdj
       CHARACTER(LEN=9), DIMENSION(ncolumnsMetForcingData):: HeaderMet
       CHARACTER(LEN=10*ncolumnsMetForcingData):: HeaderMetOut
       ! REAL(KIND(1d0)),DIMENSION(ReadLinesOrigMetData):: dectimeOrig
       ! REAL(KIND(1d0)),DIMENSION(ReadLinesOrigMetData*Nper):: dectimeDscd, dectimeFast
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigMetData*Nper):: dectimeFast
       REAL(KIND(1d0)), DIMENSION(ReadLinesOrigMetData*Nper):: idectime ! sun position at middle of time-step before
       ! INTEGER, DIMENSION(Nper):: temp_iy, temp_id, temp_ih, temp_im, temp_ihm ! temorary varaibles for disaggragation
       ! REAL(KIND(1d0)), DIMENSION(Nper):: temp_dectime ! temorary varaibles for disaggragation
       ! INTEGER :: Days_of_Year
       ! INTEGER, DIMENSION(Nper)::ndays_iy ! number of days in iy
       ! Allocate and initialise arrays to receive original forcing data --------------------
       ALLOCATE (metfordisagg(readlinesorigmetdata, ncolumnsmetforcingdata))
       ALLOCATE (metfordisaggprev(ncolumnsmetforcingdata))
       ALLOCATE (metfordisaggnext(ncolumnsmetforcingdata))
       metfordisagg(:, :) = -999
       metfordisaggprev(:) = -999
       metfordisaggnext(:) = -999
       ! Initialise array to receive disaggregated data
       met_tt = -999
       ! Intialise disaggregation method
       metdisaggmethod = -999
       ! Generate useful sequences
       seq1nper = (/(i, i=1, nper, 1)/)
       seq1nsd = (/(i, i=1, nsd, 1)/)
       ! Get methods to use for disaggregation from RunControl
       IF (diagnosedisagg == 1) WRITE (*, *) 'DisaggMethod: ', disaggmethod, 'RainDisaggMethod:', raindisaggmethod
       IF (disaggmethod == 1) THEN
          metdisaggmethod(:) = 10   !linear disaggregation of averages
       ELSEIF (disaggmethod == 2) THEN
          metdisaggmethod(:) = 20   !linear disaggregation of instantaneous values
       ELSEIF (disaggmethod == 3) THEN   !WFDEI set up, where T, Q, pres, U are instantaneous
          metdisaggmethod(:) = 10   !linear disaggregation of averages
          metdisaggmethod(10:13) = 20   !linear disagg instantaneous values for U, RH, Tair, pres
       ELSE
          CALL errorhint(2, 'Problem in SUEWS_MetDisagg: DisaggMethod value should be 1, 2, or 3', &
                         notused, notused, disaggmethod)
       ENDIF
       ! Set rainfall
       metdisaggmethod(14) = raindisaggmethod
       ! Read data ---------------------------------------------------------------------
       IF (diagnosedisagg == 1) WRITE (*, *) 'Reading file: ', trim(fileorigmet)
       OPEN (lunit, file=trim(fileorigmet), status='old')
       ! CALL skipHeader(lunit,SkipHeaderMet)  !Skip header -> read header instead
       READ (lunit, *) headermet
       !write(*,*) HeaderMet
       ! Skip over lines that have already been read and downscaled
       IF (skippedlinesorig > 0) THEN
          DO i = 1, skippedlinesorig - 1   ! minus 1 here because last line of last block needs to be read again
             READ (lunit, *)
          ENDDO
          ! Read in last line of previous block
          CALL metread(lunit, metarrayorig, inputmetformat, ldown_option, netradiationmethod, &
                       snowuse, smdmethod, soildepthmeas, soilrocks, soildensity, smcap)
          metfordisaggprev(1:ncolumnsmetforcingdata) = metarrayorig
       ENDIF
       ! print*, 'MetForDisagg',MetForDisagg(1:3,1:4)
       ! print*, 'ReadLinesOrigMetDataMax',ReadLinesOrigMetDataMax
       ! Read in current block
       DO i = 1, readlinesorigmetdatamax
          CALL metread(lunit, metarrayorig, inputmetformat, ldown_option, netradiationmethod, &
                       snowuse, smdmethod, soildepthmeas, soilrocks, soildensity, smcap)
          metfordisagg(i, 1:ncolumnsmetforcingdata) = metarrayorig
       ENDDO
       ! print*, 'MetForDisagg',MetForDisagg(1:3,1:4)
       ! Read in first line of next block (except for last block)
       IF (iblock /= readblocksorigmetdata) THEN
          CALL metread(lunit, metarrayorig, inputmetformat, ldown_option, netradiationmethod, &
                       snowuse, smdmethod, soildepthmeas, soilrocks, soildensity, smcap)
          metfordisaggnext(1:ncolumnsmetforcingdata) = metarrayorig
       ENDIF
       CLOSE (lunit)
       ! Check resolution of original met forcing data -------------------------------------
       ! Find time difference (in minutes) between first and second row
       tdiff = int(metfordisagg(2, 4) - metfordisagg(1, 4))   !Try using minutes
       IF (tdiff == 0) tdiff = int(metfordisagg(2, 3) - metfordisagg(1, 3))*60   !If no difference in minutes, try using hours
       IF (tdiff < 0) THEN   !If time difference is negative (e.g. change of day), instead use second and third row
          tdiff = int(metfordisagg(3, 4) - metfordisagg(2, 4))
          IF (tdiff == 0) tdiff = int(metfordisagg(3, 3) - metfordisagg(2, 3))*60   !If no difference in minutes, try using hours
       ENDIF
       ! Check actual resolution matches specified input resolution
       IF (tdiff /= resolutionfilesin/60) THEN
          CALL errorhint(2, 'Problem in SUEWS_MetDisagg: timestamps in met forcing file inconsistent with ResolutionFilesIn', &
                         REAL(ResolutionFilesIn, KIND(1d0)), NotUsed, tdiff*60)
       ENDIF
       ! Check file only contains a single year --------------------------------------------
       ! Very last data point is allowed to be (should be) timestamped with following year
       IF (any(metfordisagg(1:(readlinesorigmetdatamax - 1), 1) /= metfordisagg(1, 1))) THEN
          CALL errorhint(3, 'Problem in SUEWS_MetDisagg: multiple years found in original met forcing file.', &
                         metfordisagg(1, 1), notused, notusedi)
       ENDIF
       ! Disaggregate time columns ---------------------------------------------------------
       IF (diagnose == 1) WRITE (*, *) 'Disaggregating met forcing data (', trim(fileorigmet), ') to model time-step...'
       CALL disaggregatedatetime(metfordisagg(:, 1:4), tstep, nper, readlinesorigmetdatamax, met_tt(:, 1:4))
       ! Disaggregate other columns --------------------------------------------------------
       DO ii = 5, ncolumnsmetforcingdata
          IF (ii == 14) THEN  !Do something different for rainfall and snowfall (if present)
             IF (metdisaggmethod(14) == 100) THEN
                met_tt(:, 14) = disaggp_amongn(metfordisagg(:, 14), nper, nper, readlinesorigmetdata, readlinesorigmetdatamax)
                IF (all(metfordisagg(:, 16) == -999)) THEN
                   met_tt(:, 16) = -999
                ELSE
                   met_tt(:, 16) = disaggp_amongn(metfordisagg(:, 16), nper, nper, readlinesorigmetdata, readlinesorigmetdatamax)
                ENDIF
             ELSEIF (metdisaggmethod(14) == 101) THEN
                IF (rainamongn == -999) THEN
                   CALL errorhint(2, 'Problem in SUEWS_MetDisagg: RainDisaggMethod requires RainAmongN', &
                                  REAL(RainAmongN, KIND(1d0)), NotUsed, RainDisaggMethod)
                ELSEIF (rainamongn > nper) THEN
                   CALL errorhint(2, 'Problem in SUEWS_MetDisagg: RainAmongN > Nper', real(nper, kind(1d0)), notused, rainamongn)
                ELSE
                   met_tt(:, 14) = disaggp_amongn(metfordisagg(:, 14), &
                                                  rainamongn, nper, readlinesorigmetdata, readlinesorigmetdatamax)
                   IF (all(metfordisagg(:, 16) == -999)) THEN
                      met_tt(:, 16) = -999
                   ELSE
                      met_tt(:, 16) = disaggp_amongn(metfordisagg(:, 16), &
                                                     rainamongn, nper, readlinesorigmetdata, readlinesorigmetdatamax)
                   ENDIF
                ENDIF
             ELSEIF (metdisaggmethod(14) == 102) THEN
                IF (all(multrainamongn == -999)) THEN
                   CALL errorhint(2, 'Problem in SUEWS_MetDisagg: RainDisaggMethod requires MultRainAmongN', &
                                  REAL(MultRainAmongN(1), KIND(1d0)), NotUsed, RainDisaggMethod)
                ELSEIF (all(multrainamongnupperi == -999)) THEN
                   CALL errorhint(2, 'Problem in SUEWS_MetDisagg: RainDisaggMethod requires MultRainAmongNUpperI', &
                                  multrainamongnupperi(1), notused, raindisaggmethod)
                ELSEIF (any(multrainamongn > nper)) THEN
                   CALL errorhint(2, 'Problem in SUEWS_MetDisagg: MultRainAmongN > Nper', real(nper, kind(1d0)), notused, &
                                  maxval(multrainamongn))
                ELSE
                   met_tt(:, 14) = disaggp_amongnmult(metfordisagg(:, 14), multrainamongnupperi, multrainamongn, nper, &
                                                      readlinesorigmetdata, readlinesorigmetdatamax)
                   IF (all(metfordisagg(:, 16) == -999)) THEN
                      met_tt(:, 16) = -999
                   ELSE
                      met_tt(:, 16) = disaggp_amongnmult(metfordisagg(:, 16), multrainamongnupperi, multrainamongn, nper, &
                                                         readlinesorigmetdata, readlinesorigmetdatamax)
                   ENDIF
                ENDIF
             ELSE
                WRITE (*, *) 'Disaggregation code for rain not recognised'
             ENDIF
          ELSEIF (ii == 24) THEN  !wind direction disaggregation not coded yet...
             IF (any(metfordisagg(:, ii) /= -999)) THEN
                WRITE (*, *) 'Disaggregation of wind direction not currently implemented!'
             ENDIF
          ELSE
             IF (all(metfordisagg(:, ii) == -999)) THEN
                !IF(DiagnoseDisagg==1) write(*,*) 'No data for col.', ii
                met_tt(:, ii) = -999
             ELSE
                met_tt(:, ii) = disagg_lin(metfordisagg(:, ii), metfordisaggprev(ii), metfordisaggnext(ii), metdisaggmethod(ii), &
                                           nper, readlinesorigmetdata, readlinesorigmetdatamax, iblock)
             ENDIF
          ENDIF
       ENDDO
       ! Adjust kdown disaggregation using zenith angle
       IF (kdownzen == 1) THEN
          IF (diagnosedisagg == 1) WRITE (*, *) 'Adjusting disaggregated kdown using zenith angle'
          met_tt_kdownadj(:) = met_tt(:, 15)
          ! Translate location data from SurfaceChar to find solar angles
          lat = surfacechar(igrid, c_lat)
          lng = surfacechar(igrid, c_lng)
          timezone = surfacechar(igrid, c_tz)
          alt = surfacechar(igrid, c_alt)
          ! Calculate dectime at downscaled time-step
          dectimefast(:) = met_tt(:, 2) + met_tt(:, 3)/24.0 + met_tt(:, 4)/(60.0*24.0)
          idectime = dectimefast - halftimestep! sun position at middle of timestep before
          DO i = 1, (readlinesorigmetdatamax*nper)
             CALL narp_cal_sunposition(met_tt(i, 2), idectime(i), timezone, lat, lng, alt, azimuth, zenith_deg)
             ! If sun below horizon, set disaggregated kdown to zero
             IF (zenith_deg > 90) THEN
                !write(*,*) Met_tt(i,1:4)
                met_tt_kdownadj(i) = 0.0
             ENDIF
          ENDDO
          ! Redistribute kdown over each day
          DO i = 1, (readlinesorigmetdatamax*nper/nsd) ! Loop over each day
             met_tt_kdownadj((i - 1)*nsd + seq1nsd) = &
                met_tt_kdownadj((i - 1)*nsd + seq1nsd) &
                *sum(met_tt((i - 1)*nsd + seq1nsd, 15)) &
                /sum(met_tt_kdownadj((i - 1)*nsd + seq1nsd))
          ENDDO
          ! Copy adjusted kdown back to Met_tt array
          met_tt(:, 15) = met_tt_kdownadj(:)
       ENDIF
       ! Copy disaggregated data to MetForcingDataArray
       metforcingdata(:, 1:24, gridcounter) = met_tt(:, 1:24)
       ! If snow is -999, set to zero (also in LUMPS_metRead.f95)
       IF (all(metforcingdata(:, 16, gridcounter) == -999)) metforcingdata(:, 16, gridcounter) = 0
       ! Undo pressure conversion again for writing out
       met_tt(:, 13) = met_tt(:, 13)/10.0
       ! Write out disaggregated file ------------------------------------------------------
       IF (keeptstepfilesin == 1) THEN
          IF (iblock == 1) THEN
             ! Prepare header
             DO i = 1, ncolumnsmetforcingdata
                IF (i == 1) THEN
                   headermetout = adjustl(headermet(i))
                ELSE
                   headermetout = trim(headermetout)//' '//adjustl(headermet(i))
                ENDIF
             ENDDO
             ! Write out header
             OPEN (78, file=trim(filedscdmet), err=112)
             WRITE (78, '(a)') headermetout
          ELSE
             OPEN (78, file=trim(filedscdmet), position='append')!,err=112)
          ENDIF
          ! Write out data
          DO i = 1, (readlinesorigmetdatamax*nper)
             WRITE (78, 303) (int(met_tt(i, ii)), ii=1, 4), met_tt(i, 5:ncolumnsmetforcingdata)
          ENDDO
          !IF(iBlock == ReadBlocksOrigMetData) THEN
          !   WRITE(78,'(i2)') -9
          !   WRITE(78,'(i2)') -9
          !ENDIF
          CLOSE (78)   !Close output file
       ENDIF
 303   FORMAT((i4, 1x), 3(i3, 1x), 9(f12.6, 1x), (f9.4, 1x), 10(f9.4, 1x))  !Allows 4 dp for rainfall
       ! Deallocate arrays -----------------------------------------------------------------
       DEALLOCATE (metfordisagg)
       DEALLOCATE (metfordisaggprev)
       DEALLOCATE (metfordisaggnext)
       RETURN
 112   CALL errorhint(52, trim(filedscdmet), notused, notused, notusedi)
References data_in::alt, data_in::azimuth, colnamesinputfiles::c_alt, colnamesinputfiles::c_lat, colnamesinputfiles::c_lng, colnamesinputfiles::c_tz, data_in::diagnose, data_in::diagnosedisagg, disagg_lin(), data_in::disaggmethod, disaggp_amongn(), disaggp_amongnmult(), disaggregatedatetime(), errorhint(), data_in::filedscdmet, data_in::fileorigmet, initial::gridcounter, sues_data::halftimestep, data_in::inputmetformat, data_in::kdownzen, data_in::keeptstepfilesin, data_in::lat, data_in::ldown_option, data_in::lng, allocatearray::metforcingdata, allocatearray::metfordisagg, allocatearray::metfordisaggnext, allocatearray::metfordisaggprev, metread(), data_in::multrainamongn, data_in::multrainamongnupperi, narp_module::narp_cal_sunposition(), allocatearray::ncolumnsmetforcingdata, data_in::netradiationmethod, defaultnotused::notused, defaultnotused::notusedi, sues_data::nper, sues_data::nsd, data_in::rainamongn, data_in::raindisaggmethod, initial::readblocksorigmetdata, initial::readlinesorigmetdata, initial::readlinesorigmetdatamax, data_in::resolutionfilesin, initial::skippedlinesorig, sues_data::smcap, data_in::smdmethod, data_in::snowuse, sues_data::soildensity, sues_data::soildepthmeas, sues_data::soilrocks, allocatearray::surfacechar, data_in::timezone, sues_data::tstep, and data_in::zenith_deg.
Referenced by suews_program().
randomsamples()
integer function, dimension(:), allocatable metdisagg::randomsamples (integer N, integer OutOf)
Definition at line 2147 of file suews_ctrl_input.f95.
       ! Generates N/OutOf random samples without repeats
       !   e.g. for N = 3 and OutOf = 12, a possibility for Samples = 7,3,11
       ! HCW 10 Feb 2017
       !======================================================================================
       IMPLICIT NONE
       INTEGER:: i   !counter
       INTEGER:: N   !number of samples to return
       INTEGER:: OutOf   !number to sample from
       INTEGER:: X   !next sample to be added
       REAL(KIND(1D0)):: r   !random number
       INTEGER, DIMENSION(:), ALLOCATABLE:: Samples   !Array to receive random samples
       ! Allocate and initialise Samples
       ALLOCATE (samples(n))
       samples(:) = -999
       ! Generate random sample (no repeats)
       i = 0 !Set counter to zero initially
       DO WHILE (any(samples == -999))
          CALL random_number(r)
          x = int(r*outof) + 1
          !write(*,*) X
          !write(*,*) COUNT(Samples == X)
          IF (count(samples == x) == 0) THEN
             ! Only keep if this subinterval has not already been selected
             i = i + 1
             samples(i) = x
          ENDIF
          !write(*,*) Samples
       ENDDO
Referenced by disaggp_amongn(), and disaggp_amongnmult().