SUEWS: dailystate_module Module Reference
dailystate_module Module Reference
Functions/Subroutines
subroutine suews_cal_dailystate (iy, id, it, imin, isec, tstep, tstep_prev, dt_since_start, DayofWeek_id, WaterUseMethod, snowUse, Ie_start, Ie_end, LAICalcYes, LAIType, nsh_real, avkdn, Temp_C, Precip, BaseTHDD, lat, Faut, LAI_obs, tau_a, tau_f, tau_r, SnowDensMax, SnowDensMin, SnowAlbMax, SnowAlbMin, AlbMax_DecTr, AlbMax_EveTr, AlbMax_Grass, AlbMin_DecTr, AlbMin_EveTr, AlbMin_Grass, CapMax_dec, CapMin_dec, PorMax_dec, PorMin_dec, Ie_a, Ie_m, DayWatPer, DayWat, SnowPack, BaseT, BaseTe, GDDFull, SDDFull, LAIMin, LAIMax, LAIPower, SnowAlb, SnowDens, GDD_id, HDD_id, LAI_id, LAI_id_prev, WUDay_id, DecidCap_id, albDecTr_id, albEveTr_id, albGrass_id, porosity_id, deltaLAI)
subroutine update_dailystate_end (id, it, imin, tstep, dt_since_start, LAIType, Ie_end, Ie_start, LAICalcYes, WaterUseMethod, DayofWeek_id, AlbMax_DecTr, AlbMax_EveTr, AlbMax_Grass, AlbMin_DecTr, AlbMin_EveTr, AlbMin_Grass, BaseT, BaseTe, CapMax_dec, CapMin_dec, DayWat, DayWatPer, Faut, GDDFull, Ie_a, Ie_m, LAIMax, LAIMin, LAIPower, lat, PorMax_dec, PorMin_dec, SDDFull, LAI_obs, GDD_id, HDD_id, LAI_id, LAI_id_prev, WUDay_id, DecidCap_id, albDecTr_id, albEveTr_id, albGrass_id, porosity_id, deltaLAI)
subroutine update_dailystate_day (avkdn, Temp_C, Precip, BaseTHDD, nsh_real, GDD_id, HDD_id)
subroutine update_veg_x (LAImax, LAIMin, AlbMax_DecTr, AlbMax_EveTr, AlbMax_Grass, AlbMin_DecTr, AlbMin_EveTr, AlbMin_Grass, CapMax_dec, CapMin_dec, PorMax_dec, PorMin_dec, LAI_id, LAI_id_prev, DecidCap_id, albDecTr_id, albEveTr_id, albGrass_id, porosity_id, deltaLAI)
subroutine update_gddlai_x (id, LAICalcYes, lat, LAI_obs, BaseT, BaseTe, GDDFull, SDDFull, LAIMin, LAIMax, LAIPower, LAIType, GDD_id, LAI_id, LAI_id_prev)
subroutine update_wateruse_x (id, WaterUseMethod, DayofWeek_id, lat, Faut, HDD_id, Ie_a, Ie_m, Ie_start, Ie_end, DayWatPer, DayWat, WUDay_id)
subroutine update_hdd_x (dt_since_start, it, imin, tstep, HDD_id)
subroutine update_dailystate_start (it, imin, HDD_id)
subroutine suews_update_dailystate (id, datetimeline, Gridiv, NumberOfGrids, DailyStateLine, dataOutDailyState)
subroutine update_dailystate (it, imin, nsh_real, GDD_id, HDD_id, LAI_id, DecidCap_id, albDecTr_id, albEveTr_id, albGrass_id, porosity_id, WUDay_id, deltaLAI, VegPhenLumps, SnowAlb, SnowDens, a1, a2, a3, DailyStateLine)
Function/Subroutine Documentation
suews_cal_dailystate()
subroutine dailystate_module::suews_cal_dailystate (integer, intent(in) iy, integer, intent(in) id, integer, intent(in) it, integer, intent(in) imin, integer, intent(in) isec, integer, intent(in) tstep, integer, intent(in) tstep_prev, integer, intent(in) dt_since_start, integer, dimension(3), intent(in) DayofWeek_id, integer, intent(in) WaterUseMethod, integer, intent(in) snowUse, integer, intent(in) Ie_start, integer, intent(in) Ie_end, integer, intent(in) LAICalcYes, integer, dimension(nvegsurf), intent(in) LAIType, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) Precip, real(kind(1d0)), intent(in) BaseTHDD, real(kind(1d0)), intent(in) lat, real(kind(1d0)), intent(in) Faut, real(kind(1d0)), intent(in) LAI_obs, real(kind(1d0)), intent(in) tau_a, real(kind(1d0)), intent(in) tau_f, real(kind(1d0)), intent(in) tau_r, real(kind(1d0)), intent(in) SnowDensMax, real(kind(1d0)), intent(in) SnowDensMin, real(kind(1d0)), intent(in) SnowAlbMax, real(kind(1d0)), intent(in) SnowAlbMin, real(kind(1d0)), intent(in) AlbMax_DecTr, real(kind(1d0)), intent(in) AlbMax_EveTr, real(kind(1d0)), intent(in) AlbMax_Grass, real(kind(1d0)), intent(in) AlbMin_DecTr, real(kind(1d0)), intent(in) AlbMin_EveTr, real(kind(1d0)), intent(in) AlbMin_Grass, real(kind(1d0)), intent(in) CapMax_dec, real(kind(1d0)), intent(in) CapMin_dec, real(kind(1d0)), intent(in) PorMax_dec, real(kind(1d0)), intent(in) PorMin_dec, real(kind(1d0)), dimension(3), intent(in) Ie_a, real(kind(1d0)), dimension(3), intent(in) Ie_m, real(kind(1d0)), dimension(7), intent(in) DayWatPer, real(kind(1d0)), dimension(7), intent(in) DayWat, real(kind(1d0)), dimension(nsurf), intent(in) SnowPack, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseT, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseTe, real(kind(1d0)), dimension(nvegsurf), intent(in) GDDFull, real(kind(1d0)), dimension(nvegsurf), intent(in) SDDFull, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMin, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMax, real(kind(1d0)), dimension(4, nvegsurf), intent(in) LAIPower, real(kind(1d0)), intent(inout) SnowAlb, real(kind(1d0)), dimension(nsurf), intent(inout) SnowDens, real(kind(1d0)), dimension(5), intent(inout) GDD_id, real(kind(1d0)), dimension(12), intent(inout) HDD_id, real(kind(1d0)), dimension(3), intent(inout) LAI_id, real(kind(1d0)), dimension(nvegsurf), intent(inout) LAI_id_prev, real(kind(1d0)), dimension(9), intent(out) WUDay_id, real(kind(1d0)), intent(inout) DecidCap_id, real(kind(1d0)), intent(inout) albDecTr_id, real(kind(1d0)), intent(inout) albEveTr_id, real(kind(1d0)), intent(inout) albGrass_id, real(kind(1d0)), intent(inout) porosity_id, real(kind(1d0)), intent(out) deltaLAI)
Definition at line 73 of file suews_phys_dailystate.f95.
       USE snow_module, ONLY: snowupdate
       USE datetime_module, ONLY: datetime, timedelta
       IMPLICIT NONE
       INTEGER, INTENT(IN)::iy
       INTEGER, INTENT(IN)::id
       INTEGER, INTENT(IN)::it
       INTEGER, INTENT(IN)::imin
       INTEGER, INTENT(IN)::isec
       INTEGER, INTENT(IN)::tstep
       INTEGER, INTENT(IN)::tstep_prev
       INTEGER, INTENT(IN)::dt_since_start
       INTEGER, INTENT(IN)::WaterUseMethod
       INTEGER, INTENT(IN)::snowUse
       INTEGER, INTENT(IN)::Ie_start   !Starting time of water use (DOY)
       INTEGER, INTENT(IN)::Ie_end       !Ending time of water use (DOY)
       INTEGER, INTENT(IN)::LAICalcYes
       INTEGER, DIMENSION(nvegsurf), INTENT(IN):: LAIType                  !LAI equation to use: original (0) or new (1)
       REAL(KIND(1d0)), INTENT(IN)::nsh_real
       REAL(KIND(1d0)), INTENT(IN)::avkdn
       REAL(KIND(1d0)), INTENT(IN)::Temp_C
       REAL(KIND(1d0)), INTENT(IN)::Precip
       REAL(KIND(1d0)), INTENT(IN)::BaseTHDD
       REAL(KIND(1d0)), INTENT(IN)::lat
       REAL(KIND(1d0)), INTENT(IN)::Faut
       REAL(KIND(1d0)), INTENT(IN)::LAI_obs
       REAL(KIND(1D0)), INTENT(IN)::tau_a
       REAL(KIND(1D0)), INTENT(IN)::tau_f
       REAL(KIND(1D0)), INTENT(IN)::tau_r
       REAL(KIND(1D0)), INTENT(IN)::SnowDensMax
       REAL(KIND(1D0)), INTENT(IN)::SnowDensMin
       REAL(KIND(1D0)), INTENT(in)::SnowAlbMax
       REAL(KIND(1D0)), INTENT(IN)::SnowAlbMin
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_DecTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_EveTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_Grass
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_DecTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_EveTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_Grass
       REAL(KIND(1d0)), INTENT(IN)::CapMax_dec
       REAL(KIND(1d0)), INTENT(IN)::CapMin_dec
       REAL(KIND(1d0)), INTENT(IN)::PorMax_dec
       REAL(KIND(1d0)), INTENT(IN)::PorMin_dec
       ! REAL(KIND(1d0)),INTENT(IN) ::VegPhenLumps
       REAL(KIND(1d0)), DIMENSION(3), INTENT(IN) ::Ie_a
       REAL(KIND(1d0)), DIMENSION(3), INTENT(IN) ::Ie_m !Coefficients for automatic and manual irrigation models
       REAL(KIND(1d0)), DIMENSION(7), INTENT(IN) ::DayWatPer !% of houses following daily water
       REAL(KIND(1d0)), DIMENSION(7), INTENT(IN) ::DayWat !Days of watering allowed
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(IN)      ::SnowPack
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)   ::BaseT !Base temperature for growing degree days [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)   ::BaseTe !Base temperature for senescence degree days [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)   ::GDDFull !Growing degree days needed for full capacity [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)   ::SDDFull !Senescence degree days needed to initiate leaf off [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)   ::LAIMin !Min LAI [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)   ::LAIMax !Max LAI [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(4, nvegsurf), INTENT(IN) ::LAIPower !Coeffs for LAI equation: 1,2 - leaf growth; 3,4 - leaf off
       REAL(KIND(1d0)), INTENT(INOUT)::SnowAlb
       REAL(KIND(1d0)), DIMENSION(5), INTENT(INOUT) :: GDD_id   ! Growing Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(3), INTENT(INOUT) :: LAI_id   ! LAI for each veg surface [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(12), INTENT(INOUT) :: HDD_id   ! Heating Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(9), INTENT(OUT)   :: WUDay_id ! Water use related array
       ! --------------------------------------------------------------------------------
       ! ------------- Key to daily arrays ----------------------------------------------
       ! TS, 27 Dec 2018: updated the annotation for 2018b and WRF-SUEWS coupling
       !
       ! HDD_id:
       ! first half used for update through the day
       ! HDD_id(1) ---- Heating [degC]: used for accumulation during calculation
       ! HDD_id(2) ---- Cooling [degC]: used for accumulation during calculation
       ! HDD_id(3) ---- Daily mean temp [degC]: used for accumulation during calculation
       ! HDD_id(4) ---- 5-day running mean temp [degC]: used for actual calculation
       ! HDD_id(5) ---- Daily precip total [mm]
       ! HDD_id(6) ---- Days since rain [d]
       ! second half used for storage of the first half for the prevous day
       ! HDD_id(6+1) ---- Heating [degC]: used for accumulation during calculation
       ! HDD_id(6+2) ---- Cooling [degC]: used for accumulation during calculation
       ! HDD_id(6+3) ---- Daily mean temp [degC]: used for accumulation during calculation
       ! HDD_id(6+4) ---- 5-day running mean temp [degC]: used for actual calculation
       ! HDD_id(6+5) ---- Daily precip total [mm]
       ! HDD_id(6+6) ---- Days since rain [d]
       !
       ! GDD_id:
       ! GDD_id(1) ---- Growing [degC]
       ! GDD_id(2) ---- Senescence [degC]
       ! GDD_id(3) ---- Daily min temp [degC]
       ! GDD_id(4) ---- Daily max temp [degC]
       ! GDD_id(5) ---- Daytime hours [h]
       !
       ! LAI_id:
       ! LAI_id(1:3) -- LAI for each veg surface [m2 m-2]
       !
       ! WUDay_id:
       ! WUDay_id(1) - Daily water use total for Irr EveTr (automatic+manual) [mm]
       ! WUDay_id(2) - Automatic irrigation for Irr EveTr [mm]
       ! WUDay_id(3) - Manual irrigation for Irr EveTr [mm]
       ! WUDay_id(4) - Daily water use total for Irr DecTr (automatic+manual) [mm]
       ! WUDay_id(5) - Automatic irrigation for Irr DecTr [mm]
       ! WUDay_id(6) - Manual irrigation for Irr DecTr [mm]
       ! WUDay_id(7) - Daily water use total for Irr Grass (automatic+manual) [mm]
       ! WUDay_id(8) - Automatic irrigation for Irr Grass [mm]
       ! WUDay_id(9) - Manual irrigation for Irr Grass [mm]
       ! --------------------------------------------------------------------------------
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(INOUT)::SnowDens
       INTEGER, DIMENSION(3), INTENT(in)::DayofWeek_id
       !Daily water use for EveTr, DecTr, Grass [mm] (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), INTENT(OUT)::deltaLAI
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(INOUT):: LAI_id_prev !LAI for each veg surface [m2 m-2]
       REAL(KIND(1d0)), INTENT(INOUT):: DecidCap_id
       REAL(KIND(1d0)), INTENT(INOUT):: albDecTr_id
       REAL(KIND(1d0)), INTENT(INOUT):: albEveTr_id
       REAL(KIND(1d0)), INTENT(INOUT):: albGrass_id
       REAL(KIND(1d0)), INTENT(INOUT):: porosity_id
       LOGICAL :: first_tstep_Q ! if this is the first tstep of a day
       LOGICAL :: last_tstep_Q ! if this is the last tstep of a day
       TYPE(datetime) :: time_now, time_prev, time_next
       ! get timestamps
       time_now = datetime(year=iy) + timedelta(days=id - 1, hours=it, minutes=imin, seconds=isec)
       time_prev = time_now - timedelta(seconds=tstep_prev)
       time_next = time_now + timedelta(seconds=tstep)
       ! test if time at now is the first/last tstep of today
       first_tstep_q = time_now%getDay() /= time_prev%getDay()
       last_tstep_q = time_now%getDay() /= time_next%getDay()
       ! --------------------------------------------------------------------------------
       ! On first timestep of each day, define whether the day each a workday or weekend
       IF (first_tstep_q) THEN
          CALL update_dailystate_start( &
             it, imin, &!input
             hdd_id)!inout
          ! reset certain GDD columns
          gdd_id(3) = temp_c   !Daily min T in column 3
          gdd_id(4) = temp_c   !Daily max T in column 4
          gdd_id(5) = 0        !Cumulate daytime hours
       ENDIF
       ! --------------------------------------------------------------------------------
       ! regular update at all timesteps of a day
       CALL update_dailystate_day( &
          avkdn, &!input
          temp_c, &
          precip, &
          basethdd, &
          nsh_real, &
          gdd_id, &!inout
          hdd_id)
       ! Update snow density, albedo surface fraction
       IF (snowuse == 1) CALL snowupdate( &
          nsurf, tstep, temp_c, tau_a, tau_f, tau_r, &!input
          snowdensmax, snowdensmin, snowalbmax, snowalbmin, snowpack, &
          snowalb, snowdens)!inout
       ! --------------------------------------------------------------------------------
       ! On last timestep, perform the daily calculations -------------------------------
       ! Daily values not correct until end of each day,
       !  so main program should use values from the previous day
       IF (last_tstep_q) THEN
          CALL update_dailystate_end( &
             id, it, imin, tstep, dt_since_start, &!input
             laitype, ie_end, ie_start, laicalcyes, &
             waterusemethod, dayofweek_id, &
             albmax_dectr, albmax_evetr, albmax_grass, albmin_dectr, albmin_evetr, albmin_grass, &
             baset, basete, capmax_dec, capmin_dec, daywat, daywatper, faut, gddfull, &
             ie_a, ie_m, laimax, laimin, laipower, lat, pormax_dec, pormin_dec, sddfull, lai_obs, &
             gdd_id, & !inout
             hdd_id, &
             lai_id, lai_id_prev, &
             wuday_id, &
             decidcap_id, &
             albdectr_id, &
             albevetr_id, &
             albgrass_id, &
             porosity_id, &
             deltalai)!output
          ! ,xBo)!output
       ENDIF   !End of section done only at the end of each day (i.e. only once per day)
       ! PRINT*, 'after_DailyState', iy,id,it,imin
       ! PRINT*, 'HDD(id)', HDD(id,:)
       ! PRINT*, 'HDD_id', HDD_id
       RETURN
References allocatearray::nsurf, snow_module::snowupdate(), update_dailystate_day(), update_dailystate_end(), and update_dailystate_start().
suews_update_dailystate()
subroutine dailystate_module::suews_update_dailystate (integer, intent(in) id, real(kind(1d0)), dimension(5), intent(in) datetimeline, integer, intent(in) Gridiv, integer, intent(in) NumberOfGrids, real(kind(1d0)), dimension(ncolumnsdataoutdailystate - 5), intent(in) DailyStateLine, real(kind(1d0)), dimension(ndays, ncolumnsdataoutdailystate, numberofgrids), intent(inout) dataOutDailyState)
Definition at line 1351 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       ! INTEGER,INTENT(IN) ::iy
       INTEGER, INTENT(IN) ::id
       ! INTEGER,INTENT(IN) ::it
       ! INTEGER,INTENT(IN) ::imin
       REAL(KIND(1d0)), DIMENSION(5), INTENT(IN)::datetimeline
       INTEGER, INTENT(IN)::Gridiv
       INTEGER, INTENT(IN)::NumberOfGrids
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutDailyState - 5), INTENT(IN) :: DailyStateLine
       REAL(KIND(1d0)), DIMENSION(ndays, ncolumnsDataOutDailyState, NumberOfGrids), INTENT(INOUT):: dataOutDailyState
       ! write out to dataOutDailyState
       dataoutdailystate(id, 1:5, gridiv) = datetimeline
       ! dataOutDailyState(id,5,Gridiv)=dectime
       ! DailyStateLine will be -999 unless realistic values are calculated at the last timestep of each day
       dataoutdailystate(id, 6:ncolumnsdataoutdailystate, gridiv) = dailystateline
References allocatearray::ncolumnsdataoutdailystate.
Referenced by suews_calculations().
update_dailystate()
subroutine dailystate_module::update_dailystate (integer, intent(in) it, integer, intent(in) imin, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), dimension(5), intent(in) GDD_id, real(kind(1d0)), dimension(6), intent(in) HDD_id, real(kind(1d0)), dimension(nvegsurf), intent(in) LAI_id, real(kind(1d0)), intent(in) DecidCap_id, real(kind(1d0)), intent(in) albDecTr_id, real(kind(1d0)), intent(in) albEveTr_id, real(kind(1d0)), intent(in) albGrass_id, real(kind(1d0)), intent(in) porosity_id, real(kind(1d0)), dimension(9), intent(in) WUDay_id, real(kind(1d0)), intent(in) deltaLAI, real(kind(1d0)), intent(in) VegPhenLumps, real(kind(1d0)), intent(in) SnowAlb, real(kind(1d0)), dimension(7), intent(in) SnowDens, real(kind(1d0)), intent(in) a1, real(kind(1d0)), intent(in) a2, real(kind(1d0)), intent(in) a3, real(kind(1d0)), dimension(ncolumnsdataoutdailystate - 5), intent(out) DailyStateLine)
Definition at line 1388 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       ! INTEGER,INTENT(IN) ::iy
       ! INTEGER,INTENT(IN) ::id
       INTEGER, INTENT(IN) ::it
       INTEGER, INTENT(IN) ::imin
       REAL(KIND(1d0)), INTENT(IN) ::nsh_real
       REAL(KIND(1d0)), DIMENSION(5), INTENT(IN):: GDD_id          !Growing Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(6), INTENT(IN):: HDD_id          !Heating Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN):: LAI_id   !LAI for each veg surface [m2 m-2]
       REAL(KIND(1d0)), INTENT(IN) ::DecidCap_id
       REAL(KIND(1d0)), INTENT(IN) ::albDecTr_id
       REAL(KIND(1d0)), INTENT(IN) ::albEveTr_id
       REAL(KIND(1d0)), INTENT(IN) ::albGrass_id
       REAL(KIND(1d0)), INTENT(IN) ::porosity_id
       REAL(KIND(1d0)), DIMENSION(9), INTENT(IN):: WUDay_id !Daily water use for EveTr, DecTr, Grass [mm] (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), INTENT(IN) ::deltaLAI
       REAL(KIND(1d0)), INTENT(IN) ::VegPhenLumps
       REAL(KIND(1d0)), INTENT(IN) ::SnowAlb
       REAL(KIND(1d0)), DIMENSION(7), INTENT(IN)::SnowDens
       REAL(KIND(1d0)), INTENT(IN) ::a1
       REAL(KIND(1d0)), INTENT(IN) ::a2
       REAL(KIND(1d0)), INTENT(IN) ::a3
       REAL(KIND(1d0)), DIMENSION(ncolumnsDataOutDailyState - 5), INTENT(OUT) :: DailyStateLine
       ! initialise DailyStateLine
       dailystateline = -999
       IF (it == 23 .AND. imin == (nsh_real - 1)/nsh_real*60) THEN
          ! Write actual data only at the last timesstep of each day
          ! DailyStateLine(1:2)   = [iy,id]
          dailystateline(1:6) = hdd_id
          dailystateline(6 + 1:6 + 5) = gdd_id
          dailystateline(11 + 1:11 + 3) = lai_id
          dailystateline(14 + 1:14 + 5) = [decidcap_id, porosity_id, albevetr_id, albdectr_id, albgrass_id]
          dailystateline(19 + 1:19 + 9) = wuday_id(1:9)
          dailystateline(28 + 1) = deltalai
          dailystateline(29 + 1) = vegphenlumps
          dailystateline(30 + 1:30 + 8) = [snowalb, snowdens(1:7)]
          dailystateline(38 + 1:38 + 3) = [a1, a2, a3]
       END IF
update_dailystate_day()
subroutine dailystate_module::update_dailystate_day (real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) Precip, real(kind(1d0)), intent(in) BaseTHDD, real(kind(1d0)), intent(in) nsh_real, real(kind(1d0)), dimension(5), intent(inout) GDD_id, real(kind(1d0)), dimension(12), intent(inout) HDD_id)
Definition at line 437 of file suews_phys_dailystate.f95.
       ! use time, only: id, id_prev_t
       IMPLICIT NONE
       ! INTEGER,INTENT(IN)::id
       REAL(KIND(1d0)), INTENT(IN)::avkdn
       REAL(KIND(1d0)), INTENT(IN)::Temp_C
       REAL(KIND(1d0)), INTENT(IN)::Precip
       REAL(KIND(1d0)), INTENT(IN)::BaseTHDD
       REAL(KIND(1d0)), INTENT(IN)::nsh_real
       ! REAL(KIND(1d0))::tstepcount
       ! REAL(KIND(1d0)),DIMENSION(-4:366,6),INTENT(INOUT):: HDD
       REAL(KIND(1d0)), DIMENSION(5), INTENT(INOUT):: GDD_id !Growing Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(12), INTENT(INOUT):: HDD_id          !Heating Degree Days (see SUEWS_DailyState.f95)
       ! REAL(KIND(1d0)),DIMENSION(5),INTENT(OUT):: GDD_id_prev !Growing Degree Days (see SUEWS_DailyState.f95)
       INTEGER::gamma1
       INTEGER::gamma2
       ! Daily min and max temp (these get updated through the day) ---------------------
       gdd_id(3) = min(temp_c, gdd_id(3))     !Daily min T in column 3
       gdd_id(4) = max(temp_c, gdd_id(4))     !Daily max T in column 4
       IF (avkdn > 10) THEN
          gdd_id(5) = gdd_id(5) + 1/nsh_real   !Cumulate daytime hours !Divide by nsh (HCW 01 Dec 2014)
       ENDIF
       ! Calculations related to heating and cooling degree days (HDD) ------------------
       ! See Sailor & Vasireddy (2006) EMS Eq 1,2 (theirs is hourly timestep)
       gamma1 = merge(1, 0, (basethdd - temp_c) >= 0)
       gamma2 = merge(1, 0, (temp_c - basethdd) >= 0)
       ! HDD(id,1)=HDD(id,1) + gamma1*(BaseTHDD-Temp_C)   !Heating
       ! HDD(id,2)=HDD(id,2) + gamma2*(Temp_C-BaseTHDD)   !Cooling
       ! HDD(id,3)=HDD(id,3) + Temp_C                     !Will become daily average temperature
       ! !      4 ------------------------------------!   !5-day running mean
       ! HDD(id,5)=HDD(id,5) + Precip                     !Daily precip total
       !      6 ------------------------------------!   !Days since rain
       hdd_id(1) = hdd_id(1) + gamma1*(basethdd - temp_c)   !Heating
       hdd_id(2) = hdd_id(2) + gamma2*(temp_c - basethdd)   !Cooling
       hdd_id(3) = hdd_id(3) + temp_c                     !Will become daily average temperature
       !      4 ------------------------------------!   !5-day running mean
       hdd_id(5) = hdd_id(5) + precip                     !Daily precip total
       !      6 ------------------------------------!   !Days since rain
Referenced by suews_cal_dailystate().
update_dailystate_end()
subroutine dailystate_module::update_dailystate_end (integer, intent(in) id, integer, intent(in) it, integer, intent(in) imin, integer, intent(in) tstep, integer, intent(in) dt_since_start, integer, dimension(nvegsurf), intent(in) LAIType, integer, intent(in) Ie_end, integer, intent(in) Ie_start, integer, intent(in) LAICalcYes, integer, intent(in) WaterUseMethod, integer, dimension(3), intent(in) DayofWeek_id, real(kind(1d0)), intent(in) AlbMax_DecTr, real(kind(1d0)), intent(in) AlbMax_EveTr, real(kind(1d0)), intent(in) AlbMax_Grass, real(kind(1d0)), intent(in) AlbMin_DecTr, real(kind(1d0)), intent(in) AlbMin_EveTr, real(kind(1d0)), intent(in) AlbMin_Grass, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseT, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseTe, real(kind(1d0)), intent(in) CapMax_dec, real(kind(1d0)), intent(in) CapMin_dec, real(kind(1d0)), dimension(7), intent(in) DayWat, real(kind(1d0)), dimension(7), intent(in) DayWatPer, real(kind(1d0)), intent(in) Faut, real(kind(1d0)), dimension(nvegsurf), intent(in) GDDFull, real(kind(1d0)), dimension(3), intent(in) Ie_a, real(kind(1d0)), dimension(3), intent(in) Ie_m, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMax, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMin, real(kind(1d0)), dimension(4, nvegsurf), intent(in) LAIPower, real(kind(1d0)), intent(in) lat, real(kind(1d0)), intent(in) PorMax_dec, real(kind(1d0)), intent(in) PorMin_dec, real(kind(1d0)), dimension(nvegsurf), intent(in) SDDFull, real(kind(1d0)), intent(in) LAI_obs, real(kind(1d0)), dimension(5), intent(inout) GDD_id, real(kind(1d0)), dimension(12), intent(inout) HDD_id, real(kind(1d0)), dimension(nvegsurf), intent(inout) LAI_id, real(kind(1d0)), dimension(nvegsurf), intent(inout) LAI_id_prev, real(kind(1d0)), dimension(9), intent(out) WUDay_id, real(kind(1d0)), intent(inout) DecidCap_id, real(kind(1d0)), intent(inout) albDecTr_id, real(kind(1d0)), intent(inout) albEveTr_id, real(kind(1d0)), intent(inout) albGrass_id, real(kind(1d0)), intent(inout) porosity_id, real(kind(1d0)), intent(out) deltaLAI)
Definition at line 291 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       INTEGER, INTENT(IN)::id
       INTEGER, INTENT(IN)::it
       INTEGER, INTENT(IN)::imin
       INTEGER, INTENT(IN)::tstep
       INTEGER, INTENT(IN)::dt_since_start
       INTEGER, INTENT(IN)::LAIType(nvegsurf)
       INTEGER, INTENT(IN)::Ie_end
       INTEGER, INTENT(IN)::Ie_start
       INTEGER, INTENT(IN)::LAICalcYes
       INTEGER, INTENT(IN)::WaterUseMethod
       INTEGER, INTENT(in)::DayofWeek_id(3)
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_DecTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_EveTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_Grass
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_DecTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_EveTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_Grass
       REAL(KIND(1d0)), INTENT(IN)::BaseT(nvegsurf)
       REAL(KIND(1d0)), INTENT(IN)::BaseTe(nvegsurf)
       REAL(KIND(1d0)), INTENT(IN)::CapMax_dec
       REAL(KIND(1d0)), INTENT(IN)::CapMin_dec
       REAL(KIND(1d0)), INTENT(IN)::DayWat(7)
       REAL(KIND(1d0)), INTENT(IN)::DayWatPer(7)
       REAL(KIND(1d0)), INTENT(IN)::Faut
       REAL(KIND(1d0)), INTENT(IN)::GDDFull(nvegsurf)
       REAL(KIND(1d0)), INTENT(IN)::Ie_a(3)
       REAL(KIND(1d0)), INTENT(IN)::Ie_m(3)
       REAL(KIND(1d0)), INTENT(IN)::LAIMax(nvegsurf)
       REAL(KIND(1d0)), INTENT(IN)::LAIMin(nvegsurf)
       REAL(KIND(1d0)), INTENT(IN)::LAIPower(4, nvegsurf)
       REAL(KIND(1d0)), INTENT(IN)::lat
       REAL(KIND(1d0)), INTENT(IN)::PorMax_dec
       REAL(KIND(1d0)), INTENT(IN)::PorMin_dec
       REAL(KIND(1d0)), INTENT(IN)::SDDFull(nvegsurf)
       REAL(KIND(1d0)), INTENT(IN)::LAI_obs
       REAL(KIND(1d0)), DIMENSION(5), INTENT(INOUT)       ::GDD_id !Growing Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(12), INTENT(INOUT)     ::HDD_id
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(INOUT)::LAI_id !LAI for each veg surface [m2 m-2]
       ! REAL(KIND(1d0)),DIMENSION(6),INTENT(INOUT)::HDD_id_use ! HDD of previous day
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(INOUT)::LAI_id_prev ! LAI of previous day
       REAL(KIND(1d0)), DIMENSION(9), INTENT(OUT):: WUDay_id
       REAL(KIND(1d0)), INTENT(OUT)::deltaLAI
       REAL(KIND(1d0)), INTENT(INOUT):: DecidCap_id
       REAL(KIND(1d0)), INTENT(INOUT):: albDecTr_id
       REAL(KIND(1d0)), INTENT(INOUT):: albEveTr_id
       REAL(KIND(1d0)), INTENT(INOUT):: albGrass_id
       REAL(KIND(1d0)), INTENT(INOUT):: porosity_id
       ! CALL update_HDD(&
       !      id,it,imin,tstep,& !input
       !      HDD) !inout
       CALL update_hdd_x( &
          dt_since_start, it, imin, tstep, & !input
          hdd_id)!inout
       ! Calculate modelled daily water use ------------------------------------------
       ! CALL update_WaterUse(&
       !      id,WaterUseMethod,DayofWeek_id,lat,Faut,HDD_id,&!input
       !      Ie_a,Ie_m,Ie_start,Ie_end,DayWatPer,DayWat,&
       !      WUDay) !inout
       CALL update_wateruse_x( &
          id, waterusemethod, dayofweek_id, lat, faut, hdd_id, &!input
          ie_a, ie_m, ie_start, ie_end, daywatper, daywat, &
          wuday_id) !output
       ! PRINT*, ''
       ! PRINT*, 'WUDay(id)',WUDay(id,:)
       ! PRINT*, 'WUDay_id',WUDay_id
       !------------------------------------------------------------------------------
       ! Calculation of LAI from growing degree days
       ! This was revised and checked on 16 Feb 2014 by LJ
       !------------------------------------------------------------------------------
       ! CALL update_GDDLAI(&
       !      id,LAICalcYes,& !input
       !      lat,LAI_obs,&
       !      BaseT,&
       !      BaseTe,&
       !      GDDFull,&
       !      SDDFull,&
       !      LAIMin,&
       !      LAIMax,&
       !      LAIPower,LAIType,&
       !      GDD,LAI) !inout
       CALL update_gddlai_x( &
          id, laicalcyes, & !input
          lat, lai_obs, &
          baset, basete, &
          gddfull, sddfull, &
          laimin, laimax, laipower, laitype, &
          gdd_id, lai_id, &!inout
          lai_id_prev) !output
       ! CALL update_Veg(&
       !      id,&!input
       !      LAImax,LAIMin,&
       !      AlbMax_DecTr,AlbMax_EveTr,AlbMax_Grass,&
       !      AlbMin_DecTr,AlbMin_EveTr,AlbMin_Grass,&
       !      CapMax_dec,CapMin_dec,&
       !      PorMax_dec,PorMin_dec,&
       !      LAI_id,LAI_id_prev,&
       !      DecidCap,&!inout
       !      albDecTr,albEveTr,albGrass,&
       !      porosity,&
       !      deltaLAI)!output
       CALL update_veg_x( &
          laimax, laimin, &!input
          albmax_dectr, albmax_evetr, albmax_grass, &
          albmin_dectr, albmin_evetr, albmin_grass, &
          capmax_dec, capmin_dec, &
          pormax_dec, pormin_dec, &
          lai_id, lai_id_prev, &
          decidcap_id, &!inout
          albdectr_id, &
          albevetr_id, &
          albgrass_id, &
          porosity_id, &
          deltalai)!output
       ! PRINT*, 'DecidCap',DecidCap(id),DecidCap_id
       ! PRINT*, 'albDecTr',albDecTr(id),albDecTr_id
       ! PRINT*, 'albEveTr',albEveTr(id),albEveTr_id
       ! PRINT*, 'albGrass',albGrass(id),albGrass_id
       ! PRINT*, 'porosity',porosity(id),porosity_id
References update_gddlai_x(), update_hdd_x(), update_veg_x(), and update_wateruse_x().
Referenced by suews_cal_dailystate().
update_dailystate_start()
subroutine dailystate_module::update_dailystate_start (integer, intent(in) it, integer, intent(in) imin, real(kind(1d0)), dimension(6), intent(inout) HDD_id)
Definition at line 1326 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: it
       INTEGER, INTENT(IN) ::imin
       REAL(KIND(1d0)), DIMENSION(6), INTENT(INOUT) ::HDD_id
       REAL(KIND(1d0))::HDD_id_mav, HDD_id_daysSR
       ! reset HDD_id to ZERO except for:
       ! 5-day moving average
       hdd_id_mav = hdd_id(4)
       ! Days Since Rain
       hdd_id_dayssr = hdd_id(6)
       IF (it == 0 .AND. imin == 0) THEN
          hdd_id = 0
          hdd_id(4) = hdd_id_mav
          hdd_id(6) = hdd_id_dayssr
       END IF
Referenced by suews_cal_dailystate().
update_gddlai_x()
subroutine dailystate_module::update_gddlai_x (integer, intent(in) id, integer, intent(in) LAICalcYes, real(kind(1d0)), intent(in) lat, real(kind(1d0)), intent(in) LAI_obs, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseT, real(kind(1d0)), dimension(nvegsurf), intent(in) BaseTe, real(kind(1d0)), dimension(nvegsurf), intent(in) GDDFull, real(kind(1d0)), dimension(nvegsurf), intent(in) SDDFull, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMin, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMax, real(kind(1d0)), dimension(4, nvegsurf), intent(in) LAIPower, integer, dimension(nvegsurf), intent(in) LAIType, real(kind(1d0)), dimension(5), intent(inout) GDD_id, real(kind(1d0)), dimension(nvegsurf), intent(inout) LAI_id, real(kind(1d0)), dimension(nvegsurf), intent(out) LAI_id_prev)
Definition at line 901 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       !------------------------------------------------------------------------------
       ! Calculation of LAI from growing degree days
       ! This was revised and checked on 16 Feb 2014 by LJ
       !------------------------------------------------------------------------------
       INTEGER, INTENT(IN)::id
       INTEGER, INTENT(IN)::LAICalcYes
       REAL(KIND(1d0)), INTENT(IN)::lat
       REAL(KIND(1d0)), INTENT(IN)::LAI_obs
       ! --- Vegetation phenology ---------------------------------------------------------------------
       ! Parameters provided in input information for each vegetation surface (SUEWS_Veg.txt)
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)  :: BaseT          !Base temperature for growing degree days [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)  :: BaseTe         !Base temperature for senescence degree days [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)  :: GDDFull        !Growing degree days needed for full capacity [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)  :: SDDFull        !Senescence degree days needed to initiate leaf off [degC]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)  :: LAIMin         !Min LAI [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)  :: LAIMax         !Max LAI [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(4, nvegsurf), INTENT(IN):: LAIPower       !Coeffs for LAI equation: 1,2 - leaf growth; 3,4 - leaf off
       !! N.B. currently DecTr only, although input provided for all veg types
       INTEGER, DIMENSION(nvegsurf), INTENT(IN):: LAIType                  !LAI equation to use: original (0) or new (1)
       REAL(KIND(1d0)), DIMENSION(5), INTENT(INOUT)       :: GDD_id !Growing Degree Days (see SUEWS_DailyState.f95)
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(INOUT):: LAI_id !LAI for each veg surface [m2 m-2]
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(OUT)::LAI_id_prev ! LAI of previous day
       REAL(KIND(1d0)):: no   !Switches and checks for GDD
       REAL(KIND(1d0))::yes   !Switches and checks for GDD
       REAL(KIND(1d0))::indHelp   !Switches and checks for GDD
       REAL(KIND(1d0)), DIMENSION(5)::GDD_id_prev ! GDD of previous day
       INTEGER:: critDays
       INTEGER::iv
       ! translate values of previous day to local variables
       gdd_id_prev = gdd_id
       lai_id_prev = lai_id
       critdays = 50   !Critical limit for GDD when GDD or SDD is set to zero
       ! Loop through vegetation types (iv)
       DO iv = 1, nvegsurf
          ! Calculate GDD for each day from the minimum and maximum air temperature
          yes = ((gdd_id_prev(3) + gdd_id_prev(4))/2 - baset(iv))    !Leaf on
          no = ((gdd_id_prev(3) + gdd_id_prev(4))/2 - basete(iv))   !Leaf off
          indhelp = 0   !Help switch to allow GDD to go to zero in sprint-time !! QUESTION: What does this mean? HCW
          IF (yes < 0) THEN   !GDD cannot be negative
             indhelp = yes   !Amount of negative GDD
             yes = 0
          ENDIF
          IF (no > 0) no = 0    !SDD cannot be positive
          ! Calculate cumulative growing and senescence degree days
          gdd_id(1) = gdd_id_prev(1) + yes
          gdd_id(2) = gdd_id_prev(2) + no
          ! Possibility for cold spring
          IF (gdd_id(2) <= sddfull(iv) .AND. indhelp < 0) THEN
             gdd_id(1) = 0
          ENDIF
          IF (gdd_id(1) >= gddfull(iv)) THEN   !Start senescence
             gdd_id(1) = gddfull(iv)          !Leaves should not grow so delete yes from earlier
             IF (gdd_id(2) < -critdays) gdd_id(1) = 0
          ENDIF
          IF (gdd_id(2) <= sddfull(iv)) THEN   !After senescence now start growing leaves
             gdd_id(2) = sddfull(iv)           !Leaves off so add back earlier
             IF (gdd_id(1) > critdays) gdd_id(2) = 0
          ENDIF
          ! With these limits SDD, GDD is set to zero
          IF (gdd_id(2) < -critdays .AND. gdd_id(2) > sddfull(iv)) gdd_id(1) = 0
          IF (gdd_id(1) > critdays .AND. gdd_id(1) < gddfull(iv)) gdd_id(2) = 0
          ! Now calculate LAI itself
          IF (lat >= 0) THEN   !Northern hemispere
             !If SDD is not zero by mid May, this is forced
             IF (id == 140 .AND. gdd_id(2) /= 0) gdd_id(2) = 0
             ! Set SDD to zero in summer time
             IF (gdd_id(1) > critdays .AND. id < 170) gdd_id(2) = 0
             ! Set GDD zero in winter time
             IF (gdd_id(2) < -critdays .AND. id > 170) gdd_id(1) = 0
             IF (laitype(iv) < 0.5) THEN   !Original LAI type
                IF (gdd_id(1) > 0 .AND. gdd_id(1) < gddfull(iv)) THEN       !Leaves can still grow
                   lai_id(iv) = (lai_id_prev(iv)**laipower(1, iv)*gdd_id(1)*laipower(2, iv)) + lai_id_prev(iv)
                ELSEIF (gdd_id(2) < 0 .AND. gdd_id(2) > sddfull(iv)) THEN   !Start senescence
                   lai_id(iv) = (lai_id_prev(iv)**laipower(3, iv)*gdd_id(2)*laipower(4, iv)) + lai_id_prev(iv)
                ELSE
                   lai_id(iv) = lai_id_prev(iv)
                ENDIF
             ELSEIF (laitype(iv) >= 0.5) THEN
                IF (gdd_id(1) > 0 .AND. gdd_id(1) < gddfull(iv)) THEN        !Leaves can still grow
                   lai_id(iv) = (lai_id_prev(iv)**laipower(1, iv)*gdd_id(1)*laipower(2, iv)) + lai_id_prev(iv)
                   !! Use day length to start senescence at high latitudes (N hemisphere)
                ELSEIF (gdd_id(5) <= 12 .AND. gdd_id(2) > sddfull(iv)) THEN !Start senescence
                   lai_id(iv) = (lai_id_prev(iv)*laipower(3, iv)*(1 - gdd_id(2))*laipower(4, iv)) + lai_id_prev(iv)
                ELSE
                   lai_id(iv) = lai_id_prev(iv)
                ENDIF
             ENDIF
          ELSEIF (lat < 0) THEN   !Southern hemisphere !! N.B. not identical to N hemisphere - return to later
             !If SDD is not zero by late Oct, this is forced
             IF (id == 300 .AND. gdd_id(2) /= 0) gdd_id(2) = 0
             ! Set SDD to zero in summer time
             IF (gdd_id(1) > critdays .AND. id > 250) gdd_id(2) = 0
             ! Set GDD zero in winter time
             IF (gdd_id(2) < -critdays .AND. id < 250) gdd_id(1) = 0
             IF (laitype(iv) < 0.5) THEN   !Original LAI type
                IF (gdd_id(1) > 0 .AND. gdd_id(1) < gddfull(iv)) THEN
                   lai_id(iv) = (lai_id_prev(iv)**laipower(1, iv)*gdd_id(1)*laipower(2, iv)) + lai_id_prev(iv)
                ELSEIF (gdd_id(2) < 0 .AND. gdd_id(2) > sddfull(iv)) THEN
                   lai_id(iv) = (lai_id_prev(iv)**laipower(3, iv)*gdd_id(2)*laipower(4, iv)) + lai_id_prev(iv)
                ELSE
                   lai_id(iv) = lai_id_prev(iv)
                ENDIF
             ELSE
                IF (gdd_id(1) > 0 .AND. gdd_id(1) < gddfull(iv)) THEN
                   lai_id(iv) = (lai_id_prev(iv)**laipower(1, iv)*gdd_id(1)*laipower(2, iv)) + lai_id_prev(iv)
                   !! Day length not used to start senescence in S hemisphere (not much land)
                ELSEIF (gdd_id(2) < 0 .AND. gdd_id(2) > sddfull(iv)) THEN
                   lai_id(iv) = (lai_id_prev(iv)*laipower(3, iv)*(1 - gdd_id(2))*laipower(4, iv)) + lai_id_prev(iv)
                ELSE
                   lai_id(iv) = lai_id_prev(iv)
                ENDIF
             ENDIF
          ENDIF   !N or S hemisphere
          ! Check LAI within limits; if not set to limiting value
          IF (lai_id(iv) > laimax(iv)) THEN
             lai_id(iv) = laimax(iv)
          ELSEIF (lai_id(iv) < laimin(iv)) THEN
             lai_id(iv) = laimin(iv)
          ENDIF
       ENDDO   !End of loop over veg surfaces
       IF (laicalcyes == 0) THEN ! moved to SUEWS_cal_DailyState, TS 18 Sep 2017
          ! LAI(id-1,:)=LAI_obs ! check -- this is going to be a problem as it is not for each vegetation class
          lai_id = lai_obs
       ENDIF
       !------------------------------------------------------------------------------
References allocatearray::nvegsurf.
Referenced by update_dailystate_end().
update_hdd_x()
subroutine dailystate_module::update_hdd_x (integer, intent(in) dt_since_start, integer, intent(in) it, integer, intent(in) imin, integer, intent(in) tstep, real(kind(1d0)), dimension(12), intent(inout) HDD_id)
Definition at line 1290 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       INTEGER, INTENT(IN)::dt_since_start, it, imin, tstep
       REAL(KIND(1d0)), DIMENSION(12), INTENT(INOUT):: HDD_id
       ! REAL(KIND(1d0)),DIMENSION(6),INTENT(OUT):: HDD_id_use
       INTEGER:: days_prev
       REAL(KIND(1d0))::tstepcount
       ! count of timesteps performed during day `id`
       tstepcount = (it*60 + imin)*60/tstep*1.
       ! Heating degree days (HDD) -------------
       hdd_id(1) = hdd_id(1)/tstepcount   !Heating
       hdd_id(2) = hdd_id(2)/tstepcount   !Cooling
       hdd_id(3) = hdd_id(3)/tstepcount   !Average temp
       ! Calculate a quasi-5-day-running-mean temp
       days_prev = min(4, & ! dt_since_start >= 4 days
                       floor(dt_since_start/(24*60*60)*1.)) ! dt_since_start < 4 days
       hdd_id(4) = (hdd_id(4)*days_prev + hdd_id(3))/(days_prev + 1)
       ! Calculate number of days since rain
       IF (hdd_id(5) > 0) THEN        !Rain occurred
          hdd_id(6) = 0
       ELSE
          hdd_id(6) = hdd_id(6) + 1  !Days since rain
       ENDIF
       ! save updated HDD_id(1:6) values to the last-half part (i.e., HDD_id(7:12))
       hdd_id(6 + 1:6 + 6) = hdd_id(1:6)
Referenced by update_dailystate_end().
update_veg_x()
subroutine dailystate_module::update_veg_x (real(kind(1d0)), dimension(nvegsurf), intent(in) LAImax, real(kind(1d0)), dimension(nvegsurf), intent(in) LAIMin, real(kind(1d0)), intent(in) AlbMax_DecTr, real(kind(1d0)), intent(in) AlbMax_EveTr, real(kind(1d0)), intent(in) AlbMax_Grass, real(kind(1d0)), intent(in) AlbMin_DecTr, real(kind(1d0)), intent(in) AlbMin_EveTr, real(kind(1d0)), intent(in) AlbMin_Grass, real(kind(1d0)), intent(in) CapMax_dec, real(kind(1d0)), intent(in) CapMin_dec, real(kind(1d0)), intent(in) PorMax_dec, real(kind(1d0)), intent(in) PorMin_dec, real(kind(1d0)), dimension(nvegsurf), intent(in) LAI_id, real(kind(1d0)), dimension(nvegsurf), intent(in) LAI_id_prev, real(kind(1d0)), intent(inout) DecidCap_id, real(kind(1d0)), intent(inout) albDecTr_id, real(kind(1d0)), intent(inout) albEveTr_id, real(kind(1d0)), intent(inout) albGrass_id, real(kind(1d0)), intent(inout) porosity_id, real(kind(1d0)), intent(out) deltaLAI)
Definition at line 651 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       ! INTEGER,INTENT(IN)::id
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)::LAImax
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)::LAIMin
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_DecTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_EveTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMax_Grass
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_DecTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_EveTr
       REAL(KIND(1d0)), INTENT(IN)::AlbMin_Grass
       REAL(KIND(1d0)), INTENT(IN)::CapMax_dec
       REAL(KIND(1d0)), INTENT(IN)::CapMin_dec
       REAL(KIND(1d0)), INTENT(IN)::PorMax_dec
       REAL(KIND(1d0)), INTENT(IN)::PorMin_dec
       REAL(KIND(1d0)), DIMENSION(nvegsurf), INTENT(IN)::LAI_id, LAI_id_prev
       REAL(KIND(1d0)), INTENT(INOUT)::DecidCap_id
       REAL(KIND(1d0)), INTENT(INOUT)::albDecTr_id
       REAL(KIND(1d0)), INTENT(INOUT)::albEveTr_id
       REAL(KIND(1d0)), INTENT(INOUT)::albGrass_id
       REAL(KIND(1d0)), INTENT(INOUT)::porosity_id
       REAL(KIND(1d0)), INTENT(OUT)::deltaLAI
       INTEGER::iv
       REAL(KIND(1d0))::albChangeDecTr
       REAL(KIND(1d0))::albChangeEveTr
       REAL(KIND(1d0))::albChangeGrass
       REAL(KIND(1d0))::CapChange
       REAL(KIND(1d0))::deltaLAIEveTr
       REAL(KIND(1d0))::deltaLAIGrass
       REAL(KIND(1d0))::porChange
       !::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
       ! Calculate the development of vegetation cover
       ! Albedo changes with LAI for each vegetation type
       ! Storage capacity and porosity are updated based on DecTr LAI only (seasonal variation in Grass and EveTr assumed small)
       ! If only LUMPS is used, set deciduous capacities to 0
       ! QUESTION: Assume porosity Change based on GO99- Heisler?
       deltalai = 0
       deltalaievetr = 0
       deltalaigrass = 0
       capchange = 0
       porchange = 0
       albchangedectr = 0
       albchangeevetr = 0
       albchangegrass = 0
       iv = ivdecid
       IF ((lai_id(iv) - lai_id_prev(iv)) /= 0) THEN
          deltalai = (lai_id(iv) - lai_id_prev(iv))/(laimax(iv) - laimin(iv))
          albchangedectr = (albmax_dectr - albmin_dectr)*deltalai
          capchange = (capmin_dec - capmax_dec)*deltalai
          porchange = (pormin_dec - pormax_dec)*deltalai
       ENDIF
       iv = ivconif
       IF ((lai_id(iv) - lai_id_prev(iv)) /= 0) THEN
          deltalaievetr = (lai_id(iv) - lai_id_prev(iv))/(laimax(iv) - laimin(iv))
          albchangeevetr = (albmax_evetr - albmin_evetr)*deltalaievetr    !!N.B. Currently uses deltaLAI for deciduous trees only!!
       ENDIF
       iv = ivgrass
       IF ((lai_id(iv) - lai_id_prev(iv)) /= 0) THEN
          deltalaigrass = (lai_id(iv) - lai_id_prev(iv))/(laimax(iv) - laimin(iv))
          albchangegrass = (albmax_grass - albmin_grass)*deltalaigrass    !!N.B. Currently uses deltaLAI for deciduous trees only!!
       ENDIF
       iv = ivdecid
       !write(*,*) deltaLAI, deltaLAIEveTr, deltaLAIGrass
       decidcap_id = decidcap_id - capchange
       albdectr_id = albdectr_id + albchangedectr
       porosity_id = porosity_id + porchange !- changed to + by HCW 20 Aug 2015 (porosity greatest when LAI smallest)
       !Also update albedo of EveTr and Grass surfaces
       albevetr_id = albevetr_id + albchangeevetr
       albgrass_id = albgrass_id + albchangegrass
References allocatearray::ivconif, allocatearray::ivdecid, and allocatearray::ivgrass.
Referenced by update_dailystate_end().
update_wateruse_x()
subroutine dailystate_module::update_wateruse_x (integer, intent(in) id, integer, intent(in) WaterUseMethod, integer, dimension(3), intent(in) DayofWeek_id, real(kind(1d0)), intent(in) lat, real(kind(1d0)), intent(in) Faut, real(kind(1d0)), dimension(12), intent(in) HDD_id, real(kind(1d0)), dimension(3), intent(in) Ie_a, real(kind(1d0)), dimension(3), intent(in) Ie_m, integer, intent(in) Ie_start, integer, intent(in) Ie_end, real(kind(1d0)), dimension(7), intent(in) DayWatPer, real(kind(1d0)), dimension(7), intent(in) DayWat, real(kind(1d0)), dimension(9), intent(out) WUDay_id)
Definition at line 1154 of file suews_phys_dailystate.f95.
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: id
       INTEGER, INTENT(IN) :: WaterUseMethod
       INTEGER, INTENT(IN)::Ie_start   !Starting time of water use (DOY)
       INTEGER, INTENT(IN)::Ie_end       !Ending time of water use (DOY)
       INTEGER, DIMENSION(3), INTENT(IN)::DayofWeek_id
       REAL(KIND(1d0)), INTENT(IN)::lat
       REAL(KIND(1d0)), INTENT(IN)::Faut          !Fraction of irrigated area using automatic irrigation
       REAL(KIND(1d0)), DIMENSION(12), INTENT(IN)::HDD_id
       REAL(KIND(1d0)), DIMENSION(3), INTENT(IN)::Ie_a
       REAL(KIND(1d0)), DIMENSION(3), INTENT(IN)::Ie_m   !Coefficients for automatic and manual irrigation models
       REAL(KIND(1d0)), DIMENSION(7), INTENT(IN)::DayWatPer  !% of houses following daily water
       REAL(KIND(1d0)), DIMENSION(7), INTENT(IN)::DayWat       !Days of watering allowed
       REAL(KIND(1d0)), DIMENSION(9), INTENT(OUT):: WUDay_id       !Daily water use for EveTr, DecTr, Grass [mm] (see SUEWS_DailyState.f95)
       INTEGER::wd        !Water use calculation is done when calc = 1
       INTEGER::calc        !Water use calculation is done when calc = 1
       REAL(KIND(1d0))::temp_avg
       REAL(KIND(1d0))::days_since_rain
       ! transfer HDD values
       temp_avg = hdd_id(9)
       days_since_rain = hdd_id(12)
       ! initialise WUDay_id
       wuday_id = 0
       IF (waterusemethod == 0) THEN   !If water use is to be modelled (rather than observed)
          wd = dayofweek_id(1)
          IF (daywat(wd) == 1.0) THEN      !1 indicates watering permitted on this day
             calc = 0
             IF (lat >= 0) THEN            !Northern Hemisphere
                IF (id >= ie_start - 1 .AND. id <= ie_end + 1) calc = 1   !Day between irrigation period
             ELSE                        !Southern Hemisphere
                calc = 1
                IF (id >= ie_end .AND. id <= ie_start) calc = 0       !Day between irrigation period
             ENDIF
             IF (calc == 1) THEN
                ! Model daily water use based on days_since_rain (days since rain) and temp_avg (average temp)
                ! WUDay is the amount of water [mm] per day, applied to each of the irrigated areas
                ! N.B. These are the same for each vegetation type at the moment
                ! ---- Automatic irrigation (evergreen trees) ----
                wuday_id(2) = faut*(ie_a(1) + ie_a(2)*temp_avg + ie_a(3)*days_since_rain)*daywatper(wd)
                IF (wuday_id(2) < 0) wuday_id(2) = 0   !If modelled WU is negative -> 0
                ! ---- Manual irrigation (evergreen trees) ----
                wuday_id(3) = (1 - faut)*(ie_m(1) + ie_m(2)*temp_avg + ie_m(3)*days_since_rain)*daywatper(wd)
                IF (wuday_id(3) < 0) wuday_id(3) = 0   !If modelled WU is negative -> 0
                ! ---- Total evergreen trees water use (automatic + manual) ----
                wuday_id(1) = (wuday_id(2) + wuday_id(3))
                ! ---- Automatic irrigation (deciduous trees) ----
                wuday_id(5) = faut*(ie_a(1) + ie_a(2)*temp_avg + ie_a(3)*days_since_rain)*daywatper(wd)
                IF (wuday_id(5) < 0) wuday_id(5) = 0   !If modelled WU is negative -> 0
                ! ---- Manual irrigation (deciduous trees) ----
                wuday_id(6) = (1 - faut)*(ie_m(1) + ie_m(2)*temp_avg + ie_m(3)*days_since_rain)*daywatper(wd)
                IF (wuday_id(6) < 0) wuday_id(6) = 0   !If modelled WU is negative -> 0
                ! ---- Total deciduous trees water use (automatic + manual) ----
                wuday_id(4) = (wuday_id(5) + wuday_id(6))
                ! ---- Automatic irrigation (grass) ----
                wuday_id(8) = faut*(ie_a(1) + ie_a(2)*temp_avg + ie_a(3)*days_since_rain)*daywatper(wd)
                IF (wuday_id(8) < 0) wuday_id(8) = 0   !If modelled WU is negative -> 0
                ! ---- Manual irrigation (grass) ----
                wuday_id(9) = (1 - faut)*(ie_m(1) + ie_m(2)*temp_avg + ie_m(3)*days_since_rain)*daywatper(wd)
                IF (wuday_id(9) < 0) wuday_id(9) = 0   !If modelled WU is negative -> 0
                ! ---- Total grass water use (automatic + manual) ----
                wuday_id(7) = (wuday_id(8) + wuday_id(9))
             ELSE   !If no irrigation on this day
                wuday_id(1) = 0
                wuday_id(2) = 0
                wuday_id(3) = 0
                wuday_id(4) = 0
                wuday_id(5) = 0
                wuday_id(6) = 0
                wuday_id(7) = 0
                wuday_id(8) = 0
                wuday_id(9) = 0
             ENDIF
          ENDIF
       ENDIF
Referenced by initialstate(), and update_dailystate_end().