SUEWS: resist Module Reference
resist Module Reference
Variables
real(kind(1d0)) th
real(kind(1d0)) tl
real(kind(1d0)) kmax
real(kind(1d0)) g1
real(kind(1d0)) g2
real(kind(1d0)) g3
real(kind(1d0)) g4
real(kind(1d0)) g5
real(kind(1d0)) g6
real(kind(1d0)) s1
real(kind(1d0)) s2
real(kind(1d0)) tc
real(kind(1d0)) tc2
integer gsmodel
Variable Documentation
g1
real(kind(1d0)) resist::g1
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
g2
real(kind(1d0)) resist::g2
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
g3
real(kind(1d0)) resist::g3
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
g4
real(kind(1d0)) resist::g4
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
g5
real(kind(1d0)) resist::g5
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
g6
real(kind(1d0)) resist::g6
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
gsmodel
integer resist::gsmodel
Definition at line 1364 of file suews_ctrl_const.f95.
    INTEGER:: gsModel     !Choice of gs parameterisation (1 = Ja11, 2 = Wa16)
Referenced by suews_calculations(), and suews_translate().
kmax
real(kind(1d0)) resist::kmax
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
s1
real(kind(1d0)) resist::s1
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
s2
real(kind(1d0)) resist::s2
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
tc
real(kind(1d0)) resist::tc
Definition at line 1357 of file suews_ctrl_const.f95.
tc2
real(kind(1d0)) resist::tc2
Definition at line 1357 of file suews_ctrl_const.f95.
th
real(kind(1d0)) resist::th
Definition at line 1357 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: th, &             !Maximum temperature limit
                      tl, &             !Minimum temperature limit
                      Kmax, &           !Annual maximum hourly solar radiation
                      g1, g2, g3, g4, &    !Fitted parameters related to
                      g5, g6, s1, s2, &    !surface res. calculations
                      tc, &             !Temperature parameter 1
                      tc2              !Temperature parameter 2
Referenced by suews_calculations(), and suews_translate().
tl
real(kind(1d0)) resist::tl
Definition at line 1357 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().