SUEWS: mathconstants Module Reference
mathconstants Module Reference
Variables
real(kind(1d0)), parameter pi = 3.14159265359
real(kind(1d0)), parameter dtr = 0.0174532925
real(kind(1d0)), parameter rtd = 57.2957795
Variable Documentation
dtr
real(kind(1d0)), parameter mathconstants::dtr = 0.0174532925
Definition at line 2288 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER ::dtr = 0.0174532925, rtd = 57.2957795
Referenced by modsolarcalc::min_zenith(), modsolarcalc::solar_times(), and modsolarcalc::transmissivity_cd().
pi
real(kind(1d0)), parameter mathconstants::pi = 3.14159265359
Definition at line 2287 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER ::pi = 3.14159265359
Referenced by estm_module::estm(), modsolarcalc::kdown_surface(), modsolarcalc::local_apparent_time(), modsolarcalc::min_zenith(), modsolarcalc::solar_angles(), modsolarcalc::solar_esdist(), and modsolarcalc::solar_times().
rtd
real(kind(1d0)), parameter mathconstants::rtd = 57.2957795
Definition at line 2288 of file suews_ctrl_const.f95.
Referenced by modsolarcalc::solar_times().