SUEWS: estm_data Module Reference
estm_data Module Reference
Variables
integer evolvetibld
integer tsurfchoice
integer ibldchmod
real(kind(1d0)) lbc_soil
real(kind(1d0)) theat_on
real(kind(1d0)) theat_off
real(kind(1d0)) theat_fix
real(kind(1d0)) ivf_iw
real(kind(1d0)) ivf_ir
real(kind(1d0)) ivf_ii
real(kind(1d0)) ivf_if
real(kind(1d0)) ivf_ww
real(kind(1d0)) ivf_wr
real(kind(1d0)) ivf_wi
real(kind(1d0)) ivf_wf
real(kind(1d0)) ivf_rw
real(kind(1d0)) ivf_ri
real(kind(1d0)) ivf_rf
real(kind(1d0)) ivf_fw
real(kind(1d0)) ivf_fr
real(kind(1d0)) ivf_fi
integer nibld
integer nwall
integer nroof
integer nground
real(kind(1d0)), dimension(5) zibld
real(kind(1d0)), dimension(5) zwall
real(kind(1d0)), dimension(5) zroof
real(kind(1d0)), dimension(5) zground
real(kind(1d0)), dimension(5) kibld
real(kind(1d0)), dimension(5) kwall
real(kind(1d0)), dimension(5) kroof
real(kind(1d0)), dimension(5) kground
real(kind(1d0)), dimension(5) ribld
real(kind(1d0)), dimension(5) rwall
real(kind(1d0)), dimension(5) rroof
real(kind(1d0)), dimension(5) rground
real(kind(1d0)), dimension(5, 3) zsurf_paved
real(kind(1d0)), dimension(5, 3) ksurf_paved
real(kind(1d0)), dimension(5, 3) rsurf_paved
real(kind(1d0)), dimension(5, 5) zsurf_bldgs
real(kind(1d0)), dimension(5, 5) ksurf_bldgs
real(kind(1d0)), dimension(5, 5) rsurf_bldgs
real(kind(1d0)), dimension(5, 5) zwall_bldgs
real(kind(1d0)), dimension(5, 5) kwall_bldgs
real(kind(1d0)), dimension(5, 5) rwall_bldgs
real(kind(1d0)), dimension(5, 5) zibld_bldgs
real(kind(1d0)), dimension(5, 5) kibld_bldgs
real(kind(1d0)), dimension(5, 5) ribld_bldgs
real(kind(1d0)), dimension(5) nroom_bldgs
real(kind(1d0)), dimension(5) alb_ibld_bldgs
real(kind(1d0)), dimension(5) em_ibld_bldgs
real(kind(1d0)), dimension(5) ch_iwall_bldgs
real(kind(1d0)), dimension(5) ch_iroof_bldgs
real(kind(1d0)), dimension(5) ch_ibld_bldgs
real(kind(1d0)) nroom
real(kind(1d0)) alb_ibld
real(kind(1d0)) em_ibld
real(kind(1d0)) ch_iroof
real(kind(1d0)) ch_iwall
real(kind(1d0)) ch_ibld
real(kind(1d0)) fwall
real(kind(1d0)) areawall
real(kind(1d0)), dimension(:), allocatable tibld
real(kind(1d0)), dimension(:), allocatable twall
real(kind(1d0)), dimension(:), allocatable troof
real(kind(1d0)), dimension(:), allocatable tground
real(kind(1d0)), dimension(:, :), allocatable tw_4
real(kind(1d0)), dimension(:, :), allocatable tibld_grids
real(kind(1d0)), dimension(:, :), allocatable twall_grids
real(kind(1d0)), dimension(:, :), allocatable troof_grids
real(kind(1d0)), dimension(:, :), allocatable tground_grids
real(kind(1d0)), dimension(:, :, :), allocatable tw_4_grids
real(kind(1d0)) alb_avg
real(kind(1d0)) alb_ground
real(kind(1d0)) alb_roof
real(kind(1d0)) alb_veg
real(kind(1d0)) chair
real(kind(1d0)) chr
real(kind(1d0)) em_ground
real(kind(1d0)) em_roof
real(kind(1d0)) em_veg
real(kind(1d0)) em_r
real(kind(1d0)) em_w
real(kind(1d0)) em_i
real(kind(1d0)) em_f
real(kind(1d0)) fair
real(kind(1d0)) fground
real(kind(1d0)) fibld
real(kind(1d0)) finternal
real(kind(1d0)) froof
real(kind(1d0)) fveg
real(kind(1d0)) hw
real(kind(1d0)) lup_ground
real(kind(1d0)) lup_roof
real(kind(1d0)) lup_veg
real(kind(1d0)) lup_wall
real(kind(1d0)) minshc_airbld
real(kind(1d0)), dimension(5) pcoeff
real(kind(1d0)) qsground
real(kind(1d0)) qsroof
real(kind(1d0)) qswall
real(kind(1d0)), dimension(4) qs_4
real(kind(1d0)) qsair
real(kind(1d0)) qsibld
real(kind(1d0)) rvf_ground
real(kind(1d0)) rvf_wall
real(kind(1d0)) rvf_roof
real(kind(1d0)) rvf_canyon
real(kind(1d0)) rvf_veg
real(kind(1d0)) shc_air
real(kind(1d0)) svf_ground
real(kind(1d0)) svf_wall
real(kind(1d0)) svf_roof
real(kind(1d0)) tanzenith
real(kind(1d0)) tair1
real(kind(1d0)) tair2
real(kind(1d0)) tairday
real(kind(1d0)) tfloor
real(kind(1d0)) tievolve
real(kind(1d0)) tn_roof
real(kind(1d0)) tn_wall
real(kind(1d0)) t0_wall
real(kind(1d0)) t0_roof
real(kind(1d0)) t0_ground
real(kind(1d0)) t0_ibld
real(kind(1d0)) ws
real(kind(1d0)) xvf_wall
real(kind(1d0)) zref
real(kind(1d0)) zvf_ground
real(kind(1d0)) zvf_wall
real(kind(1d0)), dimension(:), allocatable tair2_grids
real(kind(1d0)), dimension(:), allocatable lup_ground_grids
real(kind(1d0)), dimension(:), allocatable lup_wall_grids
real(kind(1d0)), dimension(:), allocatable lup_roof_grids
real(kind(1d0)), dimension(:), allocatable tievolve_grids
real(kind(1d0)), dimension(:), allocatable t0_wall_grids
real(kind(1d0)), dimension(:), allocatable t0_roof_grids
real(kind(1d0)), dimension(:), allocatable t0_ground_grids
real(kind(1d0)), dimension(:), allocatable t0_ibld_grids
real(kind(1d0)), dimension(:), allocatable tn_roof_grids
real(kind(1d0)), dimension(:), allocatable tn_wall_grids
real(kind(1d0)), dimension(3) estmsfr_paved
real(kind(1d0)), dimension(5) estmsfr_bldgs
logical, dimension(2) bctype
logical cflfail = .FALSE.
logical diagnoseti = .FALSE.
logical first
logical hvac = .FALSE.
logical spindone = .FALSE.
real(kind(1d0)), parameter alb_wall = 0.23
real(kind(1d0)), parameter em_wall = 0.9
integer, parameter maxiter = 100
real(kind(1d0)), parameter conv = 0.0001
integer nalb
integer nemis
real(kind(1d0)) sumalb
real(kind(1d0)) sumemis
Variable Documentation
alb_avg
real(kind(1d0)) estm_data::alb_avg
Definition at line 2179 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))                           ::  alb_avg, &
                                                 alb_ground, &   !albedo value of ground
                                                 alb_roof, &     !albedo value of roof
                                                 alb_veg, &      !albedo value of veg
                                                 CHAIR, &
                                                 CHR, &
                                                 em_ground, &    !emissivity of ground
                                                 em_roof, &      !emissivity of roof
                                                 em_veg, &       !emissivity of veg
                                                 em_r, &         !emissivity of roof inside building
                                                 em_w, &         !emissivity of internal wall
                                                 em_i, &         !QUESTION: emissivity of ?
                                                 em_f, &         !emissivity of floor
                                                 fair, &         !fraction of air (or ratio of outdoor air volume to indoor air volume)
                                                 fground, &      !fraction of ground
                                                 fibld, &        !QUESTION: fraction of internal elements (?)
                                                 finternal, &    !sum of froof, fibld and fwall
                                                 froof, &        !fraction of roof
                                                 fveg, &         !fraction of veg
                                                 HW, &           !Height Width ratio
                                                 LUP_ground, &
                                                 LUP_ROOF, &
                                                 LUP_VEG, &
                                                 LUP_WALL, &
                                                 minshc_airbld, &
                                                 Pcoeff(5), &
                                                 Qsground, &     !Storage heat flux into ground
                                                 Qsroof, &       !Storage heat flux into roof
                                                 Qswall, &       !Storage heat flux into wall
                                                 Qs_4(4), &      !Storage heat flux into each external wall (N,E,S and W direction)
                                                 Qsair, &        !Storage heat flux into air
                                                 Qsibld, &       !Storage heat flux into internal building elements
                                                 RVF_ground, &
                                                 RVF_WALL, &
                                                 RVF_ROOF, &
                                                 RVF_CANYON, &
                                                 RVF_VEG, &
                                                 SHC_air, &
                                                 SVF_ground, &   !Sky view factor from ground
                                                 SVF_wall, &     !Sky view factor from wall
                                                 SVF_roof, &     !Sky view factor from roof
                                                 TANZENITH, &    !
                                                 Tair1, &
                                                 Tair2, &
                                                 Tairday, &      !24hour average air temperature
                                                 Tfloor, &
                                                 Tievolve, &
                                                 TN_roof, &
                                                 TN_wall, &
                                                 T0_wall, &
                                                 T0_roof, &
                                                 T0_ground, &
                                                 T0_ibld, &
                                                 WS, &           !Wind speed used in ESTM
                                                 xvf_wall, &
                                                 ZREF, &         !local scale reference height
                                                 zvf_ground, &   !wall view factor from ground
                                                 zvf_WALL     !wall view factor from ground
Referenced by estm_module::estm(), and estm_module::estm_translate().
alb_ground
real(kind(1d0)) estm_data::alb_ground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
alb_ibld
real(kind(1d0)) estm_data::alb_ibld
Definition at line 2162 of file suews_ctrl_const.f95.
Referenced by suews_translate().
alb_ibld_bldgs
real(kind(1d0)), dimension(5) estm_data::alb_ibld_bldgs
Definition at line 2156 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: alb_ibld_Bldgs
Referenced by suews_translate().
alb_roof
real(kind(1d0)) estm_data::alb_roof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
alb_veg
real(kind(1d0)) estm_data::alb_veg
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
alb_wall
real(kind(1d0)), parameter estm_data::alb_wall = 0.23
Definition at line 2262 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER::alb_wall = 0.23, em_wall = 0.9  ! used only when radforce = T but radforce is always set to F.
Referenced by estm_module::estm(), and estm_module::estm_translate().
areawall
real(kind(1d0)) estm_data::areawall
Definition at line 2162 of file suews_ctrl_const.f95.
Referenced by suews_translate().
bctype
logical, dimension(2) estm_data::bctype
Definition at line 2255 of file suews_ctrl_const.f95.
    LOGICAL             ::bctype(2), &
                           CFLfail = .false., &
                           diagnoseti = .false., &
                           first, &
                           hvac = .false., &
                           spindone = .false.
Referenced by estm_module::estm().
cflfail
logical estm_data::cflfail = .FALSE.
Definition at line 2255 of file suews_ctrl_const.f95.
ch_ibld
real(kind(1d0)) estm_data::ch_ibld
Definition at line 2162 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
ch_ibld_bldgs
real(kind(1d0)), dimension(5) estm_data::ch_ibld_bldgs
Definition at line 2160 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: CH_ibld_Bldgs
Referenced by suews_translate().
ch_iroof
real(kind(1d0)) estm_data::ch_iroof
Definition at line 2162 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
ch_iroof_bldgs
real(kind(1d0)), dimension(5) estm_data::ch_iroof_bldgs
Definition at line 2159 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: CH_iroof_Bldgs
Referenced by suews_translate().
ch_iwall
real(kind(1d0)) estm_data::ch_iwall
Definition at line 2162 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
ch_iwall_bldgs
real(kind(1d0)), dimension(5) estm_data::ch_iwall_bldgs
Definition at line 2158 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: CH_iwall_Bldgs
Referenced by suews_translate().
chair
real(kind(1d0)) estm_data::chair
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
chr
real(kind(1d0)) estm_data::chr
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
conv
real(kind(1d0)), parameter estm_data::conv = 0.0001
Definition at line 2264 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), PARAMETER:: conv = 0.0001
Referenced by estm_module::estm().
diagnoseti
logical estm_data::diagnoseti = .FALSE.
Definition at line 2255 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
em_f
real(kind(1d0)) estm_data::em_f
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
em_ground
real(kind(1d0)) estm_data::em_ground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
em_i
real(kind(1d0)) estm_data::em_i
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
em_ibld
real(kind(1d0)) estm_data::em_ibld
Definition at line 2162 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
em_ibld_bldgs
real(kind(1d0)), dimension(5) estm_data::em_ibld_bldgs
Definition at line 2157 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: em_ibld_Bldgs
Referenced by suews_translate().
em_r
real(kind(1d0)) estm_data::em_r
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
em_roof
real(kind(1d0)) estm_data::em_roof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
em_veg
real(kind(1d0)) estm_data::em_veg
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
em_w
real(kind(1d0)) estm_data::em_w
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
em_wall
real(kind(1d0)), parameter estm_data::em_wall = 0.9
Definition at line 2262 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
estmsfr_bldgs
real(kind(1d0)), dimension(5) estm_data::estmsfr_bldgs
Definition at line 2253 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: ESTMsfr_Bldgs
Referenced by suews_translate().
estmsfr_paved
real(kind(1d0)), dimension(3) estm_data::estmsfr_paved
Definition at line 2252 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(3):: ESTMsfr_Paved
Referenced by suews_translate().
evolvetibld
integer estm_data::evolvetibld
Definition at line 2098 of file suews_ctrl_const.f95.
    INTEGER ::        evolveTibld, &
               TsurfChoice, &
               ibldCHmod
Referenced by estm_module::estm(), and estm_module::estm_initials().
fair
real(kind(1d0)) estm_data::fair
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
fground
real(kind(1d0)) estm_data::fground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
fibld
real(kind(1d0)) estm_data::fibld
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
finternal
real(kind(1d0)) estm_data::finternal
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
first
logical estm_data::first
Definition at line 2255 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate().
froof
real(kind(1d0)) estm_data::froof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
fveg
real(kind(1d0)) estm_data::fveg
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate(), and suews_translate().
fwall
real(kind(1d0)) estm_data::fwall
Definition at line 2162 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
hvac
logical estm_data::hvac = .FALSE.
Definition at line 2255 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
hw
real(kind(1d0)) estm_data::hw
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ibldchmod
integer estm_data::ibldchmod
Definition at line 2098 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_initials().
ivf_fi
real(kind(1d0)) estm_data::ivf_fi
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate().
ivf_fr
real(kind(1d0)) estm_data::ivf_fr
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate().
ivf_fw
real(kind(1d0)) estm_data::ivf_fw
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate().
ivf_if
real(kind(1d0)) estm_data::ivf_if
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_ii
real(kind(1d0)) estm_data::ivf_ii
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_ir
real(kind(1d0)) estm_data::ivf_ir
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_iw
real(kind(1d0)) estm_data::ivf_iw
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_rf
real(kind(1d0)) estm_data::ivf_rf
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_ri
real(kind(1d0)) estm_data::ivf_ri
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_rw
real(kind(1d0)) estm_data::ivf_rw
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_wf
real(kind(1d0)) estm_data::ivf_wf
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_wi
real(kind(1d0)) estm_data::ivf_wi
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_wr
real(kind(1d0)) estm_data::ivf_wr
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ivf_ww
real(kind(1d0)) estm_data::ivf_ww
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
kground
real(kind(1d0)), dimension(5) estm_data::kground
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
kibld
real(kind(1d0)), dimension(5) estm_data::kibld
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
kibld_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::kibld_bldgs
Definition at line 2153 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: kibld_Bldgs
Referenced by suews_translate().
kroof
real(kind(1d0)), dimension(5) estm_data::kroof
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
ksurf_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::ksurf_bldgs
Definition at line 2147 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: kSurf_Bldgs
Referenced by suews_translate().
ksurf_paved
real(kind(1d0)), dimension(5, 3) estm_data::ksurf_paved
Definition at line 2143 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 3):: kSurf_Paved
Referenced by suews_translate().
kwall
real(kind(1d0)), dimension(5) estm_data::kwall
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
kwall_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::kwall_bldgs
Definition at line 2150 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: kwall_Bldgs
Referenced by suews_translate().
lbc_soil
real(kind(1d0)) estm_data::lbc_soil
Definition at line 2102 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: LBC_soil, &        !Lowest boundary condition in soil
                      THEAT_ON, &
                      THEAT_OFF, &
                      THEAT_fix, &
                      ivf_iw, &    !Internal view factors : im
                      ivf_ir, &
                      ivf_ii, &
                      ivf_if, &
                      ivf_ww, &    !Internal view factors : wall
                      ivf_wr, &
                      ivf_wi, &
                      ivf_wf, &
                      ivf_rw, &    !Internal view factors : roof
                      ivf_ri, &
                      ivf_rf, &
                      ivf_fw, &    !Internal view factors : floor
                      ivf_fr, &
                      ivf_fi
Referenced by estm_module::estm(), estm_module::estm_initials(), and estm_module::estm_translate().
lup_ground
real(kind(1d0)) estm_data::lup_ground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
lup_ground_grids
real(kind(1d0)), dimension(:), allocatable estm_data::lup_ground_grids
Definition at line 2240 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: lup_ground_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
lup_roof
real(kind(1d0)) estm_data::lup_roof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
lup_roof_grids
real(kind(1d0)), dimension(:), allocatable estm_data::lup_roof_grids
Definition at line 2242 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: lup_roof_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
lup_veg
real(kind(1d0)) estm_data::lup_veg
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
lup_wall
real(kind(1d0)) estm_data::lup_wall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
lup_wall_grids
real(kind(1d0)), dimension(:), allocatable estm_data::lup_wall_grids
Definition at line 2241 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: lup_wall_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
maxiter
integer, parameter estm_data::maxiter = 100
Definition at line 2263 of file suews_ctrl_const.f95.
    INTEGER, PARAMETER::        maxiter = 100
Referenced by estm_module::estm().
minshc_airbld
real(kind(1d0)) estm_data::minshc_airbld
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
nalb
integer estm_data::nalb
Definition at line 2267 of file suews_ctrl_const.f95.
    INTEGER             ::nalb, &
                           nemis
Referenced by estm_module::estm(), and estm_module::estm_translate().
nemis
integer estm_data::nemis
Definition at line 2267 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
nground
integer estm_data::nground
Definition at line 2122 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
nibld
integer estm_data::nibld
Definition at line 2122 of file suews_ctrl_const.f95.
    INTEGER:: Nibld, &           !Number of layers in an internal element in buildings, calculated when the file is read.
              Nwall, &           !Number of layers in external wall
              Nroof, &           !Number of layers in roof
              Nground           !Number of layers in ground
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
nroof
integer estm_data::nroof
Definition at line 2122 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
nroom
real(kind(1d0)) estm_data::nroom
Definition at line 2162 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::   nroom, &      !Number of rooms in internal building  (changed from integer to real HCW 16 Jun 2016)
                      alb_ibld, & !albedo value of internal elements
                      em_ibld, &  !emissivity of internal elements
                      CH_iroof, & !bulk transfer coefficient of internal roof
                      CH_iwall, & !bulk transfer coefficient of internal wall
                      CH_ibld, &  !bulk transfer coefficient of internal building element
                      fwall, &    !fraction of wall
                      AreaWall   ! Area of wall within grid [m2]
Referenced by estm_module::estm_translate(), and suews_translate().
nroom_bldgs
real(kind(1d0)), dimension(5) estm_data::nroom_bldgs
Definition at line 2155 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: nroom_Bldgs
Referenced by suews_translate().
nwall
integer estm_data::nwall
Definition at line 2122 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), estm_module::estm_translate(), and suews_translate().
pcoeff
real(kind(1d0)), dimension(5) estm_data::pcoeff
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
qs_4
real(kind(1d0)), dimension(4) estm_data::qs_4
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
qsair
real(kind(1d0)) estm_data::qsair
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
qsground
real(kind(1d0)) estm_data::qsground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
qsibld
real(kind(1d0)) estm_data::qsibld
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
qsroof
real(kind(1d0)) estm_data::qsroof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
qswall
real(kind(1d0)) estm_data::qswall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
rground
real(kind(1d0)), dimension(5) estm_data::rground
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by suews_translate().
ribld
real(kind(1d0)), dimension(5) estm_data::ribld
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
ribld_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::ribld_bldgs
Definition at line 2154 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: ribld_Bldgs
Referenced by suews_translate().
rroof
real(kind(1d0)), dimension(5) estm_data::rroof
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
rsurf_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::rsurf_bldgs
Definition at line 2148 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: rSurf_Bldgs
Referenced by suews_translate().
rsurf_paved
real(kind(1d0)), dimension(5, 3) estm_data::rsurf_paved
Definition at line 2144 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 3):: rSurf_Paved
Referenced by suews_translate().
rvf_canyon
real(kind(1d0)) estm_data::rvf_canyon
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate().
rvf_ground
real(kind(1d0)) estm_data::rvf_ground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
rvf_roof
real(kind(1d0)) estm_data::rvf_roof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
rvf_veg
real(kind(1d0)) estm_data::rvf_veg
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
rvf_wall
real(kind(1d0)) estm_data::rvf_wall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
rwall
real(kind(1d0)), dimension(5) estm_data::rwall
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
rwall_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::rwall_bldgs
Definition at line 2151 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: rwall_Bldgs
Referenced by suews_translate().
shc_air
real(kind(1d0)) estm_data::shc_air
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
spindone
logical estm_data::spindone = .FALSE.
Definition at line 2255 of file suews_ctrl_const.f95.
sumalb
real(kind(1d0)) estm_data::sumalb
Definition at line 2269 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))     ::sumalb, &
                           sumemis
Referenced by estm_module::estm(), and estm_module::estm_translate().
sumemis
real(kind(1d0)) estm_data::sumemis
Definition at line 2269 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
svf_ground
real(kind(1d0)) estm_data::svf_ground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
svf_roof
real(kind(1d0)) estm_data::svf_roof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
svf_wall
real(kind(1d0)) estm_data::svf_wall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
t0_ground
real(kind(1d0)) estm_data::t0_ground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
t0_ground_grids
real(kind(1d0)), dimension(:), allocatable estm_data::t0_ground_grids
Definition at line 2246 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: T0_ground_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
t0_ibld
real(kind(1d0)) estm_data::t0_ibld
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
t0_ibld_grids
real(kind(1d0)), dimension(:), allocatable estm_data::t0_ibld_grids
Definition at line 2247 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: T0_ibld_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
t0_roof
real(kind(1d0)) estm_data::t0_roof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
t0_roof_grids
real(kind(1d0)), dimension(:), allocatable estm_data::t0_roof_grids
Definition at line 2245 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: T0_roof_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
t0_wall
real(kind(1d0)) estm_data::t0_wall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
t0_wall_grids
real(kind(1d0)), dimension(:), allocatable estm_data::t0_wall_grids
Definition at line 2244 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: T0_wall_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
tair1
real(kind(1d0)) estm_data::tair1
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
tair2
real(kind(1d0)) estm_data::tair2
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
tair2_grids
real(kind(1d0)), dimension(:), allocatable estm_data::tair2_grids
Definition at line 2239 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: Tair2_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
tairday
real(kind(1d0)) estm_data::tairday
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
tanzenith
real(kind(1d0)) estm_data::tanzenith
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
tfloor
real(kind(1d0)) estm_data::tfloor
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
tground
real(kind(1d0)), dimension(:), allocatable estm_data::tground
Definition at line 2172 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
tground_grids
real(kind(1d0)), dimension(:, :), allocatable estm_data::tground_grids
Definition at line 2175 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
theat_fix
real(kind(1d0)) estm_data::theat_fix
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_initials().
theat_off
real(kind(1d0)) estm_data::theat_off
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_initials().
theat_on
real(kind(1d0)) estm_data::theat_on
Definition at line 2102 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_initials().
tibld
real(kind(1d0)), dimension(:), allocatable estm_data::tibld
Definition at line 2172 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), ALLOCATABLE, DIMENSION(:)::  Tibld, Twall, Troof, Tground
Referenced by estm_module::estm(), and estm_module::estm_translate().
tibld_grids
real(kind(1d0)), dimension(:, :), allocatable estm_data::tibld_grids
Definition at line 2175 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), ALLOCATABLE, DIMENSION(:, :)  ::  Tibld_grids, Twall_grids, Troof_grids, Tground_grids
Referenced by estm_module::estm(), and estm_module::estm_translate().
tievolve
real(kind(1d0)) estm_data::tievolve
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
tievolve_grids
real(kind(1d0)), dimension(:), allocatable estm_data::tievolve_grids
Definition at line 2243 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: Tievolve_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
tn_roof
real(kind(1d0)) estm_data::tn_roof
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
tn_roof_grids
real(kind(1d0)), dimension(:), allocatable estm_data::tn_roof_grids
Definition at line 2248 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: TN_roof_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
tn_wall
real(kind(1d0)) estm_data::tn_wall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
tn_wall_grids
real(kind(1d0)), dimension(:), allocatable estm_data::tn_wall_grids
Definition at line 2249 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(:), ALLOCATABLE:: TN_wall_grids
Referenced by estm_module::estm(), and estm_module::estm_initials().
troof
real(kind(1d0)), dimension(:), allocatable estm_data::troof
Definition at line 2172 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
troof_grids
real(kind(1d0)), dimension(:, :), allocatable estm_data::troof_grids
Definition at line 2175 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
tsurfchoice
integer estm_data::tsurfchoice
Definition at line 2098 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_initials().
tw_4
real(kind(1d0)), dimension(:, :), allocatable estm_data::tw_4
Definition at line 2173 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), ALLOCATABLE, DIMENSION(:, :)::  Tw_4
Referenced by estm_module::estm(), and estm_module::estm_translate().
tw_4_grids
real(kind(1d0)), dimension(:, :, :), allocatable estm_data::tw_4_grids
Definition at line 2176 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), ALLOCATABLE, DIMENSION(:, :, :)::  Tw_4_grids
Referenced by estm_module::estm(), and estm_module::estm_translate().
twall
real(kind(1d0)), dimension(:), allocatable estm_data::twall
Definition at line 2172 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
twall_grids
real(kind(1d0)), dimension(:, :), allocatable estm_data::twall_grids
Definition at line 2175 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
ws
real(kind(1d0)) estm_data::ws
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm().
xvf_wall
real(kind(1d0)) estm_data::xvf_wall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
zground
real(kind(1d0)), dimension(5) estm_data::zground
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
zibld
real(kind(1d0)), dimension(5) estm_data::zibld
Definition at line 2127 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: zibld, &    !Thickness of layers in internal building
                                    zwall, &    !Thickness of layers in external wall
                                    zroof, &    !Thickness of layers in roof
                                    zground, &  !Thickness of layers in ground
                                    kibld, &    !Thermal conductivity of layers in internal building
                                    kwall, &    !Thermal conductivity of layers in external wall
                                    kroof, &    !Thermal conductivity of layers in roof
                                    kground, &  !Thermal conductivity of layers in ground
                                    ribld, &    !Volumetric heat capacity of layers in internal building
                                    rwall, &    !Volumetric heat capacity of layers in external wall
                                    rroof, &    !Volumetric heat capacity of layers in roof
                                    rground    !Volumetric heat capacity of layers in ground
Referenced by estm_module::estm(), and suews_translate().
zibld_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::zibld_bldgs
Definition at line 2152 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: zibld_Bldgs
Referenced by suews_translate().
zref
real(kind(1d0)) estm_data::zref
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm_translate().
zroof
real(kind(1d0)), dimension(5) estm_data::zroof
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
zsurf_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::zsurf_bldgs
Definition at line 2146 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: zSurf_Bldgs
Referenced by suews_translate().
zsurf_paved
real(kind(1d0)), dimension(5, 3) estm_data::zsurf_paved
Definition at line 2142 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 3):: zSurf_Paved
Referenced by suews_translate().
zvf_ground
real(kind(1d0)) estm_data::zvf_ground
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
zvf_wall
real(kind(1d0)) estm_data::zvf_wall
Definition at line 2179 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and estm_module::estm_translate().
zwall
real(kind(1d0)), dimension(5) estm_data::zwall
Definition at line 2127 of file suews_ctrl_const.f95.
Referenced by estm_module::estm(), and suews_translate().
zwall_bldgs
real(kind(1d0)), dimension(5, 5) estm_data::zwall_bldgs
Definition at line 2149 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5, 5):: zwall_Bldgs
Referenced by suews_translate().