SUEWS: data_in Module Reference
data_in Module Reference
Variables
character(len=90) progname = 'SUEWS_V2019a'
character(len=20) filecode
character(len=150) fileinputpath
character(len=150) fileoutputpath
character(len=150) fileout
character(len=150) filechoices
character(len=150) filemet
character(len=150) fileorigmet
character(len=150) fileorigestm
character(len=150) filedscdmet
character(len=150) filedscdestm
character(len=150) filedaily
character(len=150) fileestmts
character(len=150) solweigpoiout
character(len=150) blout
character(len=150) fileout_tt
character(len=150) estmout_tt
integer skipheadersiteinfo = 2
integer skipheadermet = 1
integer emissionsmethod
integer cbluse
integer multiplemetfiles
integer multipleinitfiles
integer multipleestmfiles
integer keeptstepfilesin
integer keeptstepfilesout
integer resolutionfilesin
integer resolutionfilesout
integer resolutionfilesinestm
integer writeoutoption
integer netradiationmethod
integer ohmincqf
integer storageheatmethod
integer snowuse
integer solweiguse
integer smdmethod
integer waterusemethod
integer roughlenmommethod
integer disaggmethod
integer disaggmethodestm
integer raindisaggmethod
integer rainamongn
integer kdownzen
integer suppresswarnings = 1
integer diagnose
integer diagnosedisagg
integer ncmode
integer nrow
integer ncol
integer diagnosedisaggestm
integer diagqn
integer diagqs
integer, dimension(5) multrainamongn
real(kind(1d0)), dimension(5) multrainamongnupperi
integer albedochoice
integer inputmetformat
integer evapmethod
integer laicalcyes
integer writedailystate
integer ldown_option
integer lfnout
integer lfnoutc
integer lfnold
integer outputformats
real(kind(1d0)) timezone
real(kind(1d0)) alpha_qhqe
real(kind(1d0)) alt
real(kind(1d0)) avdens
real(kind(1d0)) avkdn
real(kind(1d0)) avrh
real(kind(1d0)) avts
real(kind(1d0)) avu1
real(kind(1d0)) avu10_ms
real(kind(1d0)) azimuth
real(kind(1d0)) basethdd
real(kind(1d0)) buildenergyuse
real(kind(1d0)) co2mwd
real(kind(1d0)) co2mwe
real(kind(1d0)) co2pointsource
real(kind(1d0)) e_mod
real(kind(1d0)) ef_umolco2perj
real(kind(1d0)) emis_snow
real(kind(1d0)) enef_v_jkm
real(kind(1d0)) enprofwd
real(kind(1d0)) enprofwe
real(kind(1d0)) fc
real(kind(1d0)) fc_anthro
real(kind(1d0)) fc_biogen
real(kind(1d0)) fc_build
real(kind(1d0)) fc_metab
real(kind(1d0)) fc_photo
real(kind(1d0)) fc_point
real(kind(1d0)) fc_respi
real(kind(1d0)) fc_traff
real(kind(1d0)) fcld
real(kind(1d0)) fcld_obs
real(kind(1d0)) frfossilfuel_heat
real(kind(1d0)) frfossilfuel_nonheat
real(kind(1d0)) frpddwe
real(kind(1d0)) h_mod
real(kind(1d0)) kclear
real(kind(1d0)) kdiff
real(kind(1d0)) kdir
real(kind(1d0)) kup
real(kind(1d0)) lai_obs
real(kind(1d0)) lat
real(kind(1d0)) ldown
real(kind(1d0)) ldown_obs
real(kind(1d0)) lng
real(kind(1d0)) lup
real(kind(1d0)) maxfcmetab
real(kind(1d0)) maxqfmetab
real(kind(1d0)) minfcmetab
real(kind(1d0)) minqfmetab
real(kind(1d0)) popdensnighttime
real(kind(1d0)) popprofwd
real(kind(1d0)) popprofwe
real(kind(1d0)) precip
real(kind(1d0)) precip_hr
real(kind(1d0)) press_hpa
real(kind(1d0)) pres_kpa
real(kind(1d0)) q2_gkg
real(kind(1d0)) qe
real(kind(1d0)) qe_obs
real(kind(1d0)) qf_build
real(kind(1d0)) qf_metab
real(kind(1d0)) qf_traff
real(kind(1d0)) qf_obs
real(kind(1d0)) qf_sahp
real(kind(1d0)) qf_sahp_base
real(kind(1d0)) qf_sahp_heat
real(kind(1d0)) qf_sahp_ac
real(kind(1d0)) qh
real(kind(1d0)) qh_obs
real(kind(1d0)) qh_r
real(kind(1d0)) qn1
real(kind(1d0)) qn1_bup
real(kind(1d0)) qn1_obs
real(kind(1d0)) qn1_s
real(kind(1d0)) qn1_snowfree
real(kind(1d0)) qs_obs
real(kind(1d0)) qsanohm
real(kind(1d0)) qsestm
real(kind(1d0)) snow
real(kind(1d0)) snowfrac_obs
real(kind(1d0)) temp_c
real(kind(1d0)) t2_c
real(kind(1d0)) trafficunits
real(kind(1d0)) traffprofwd
real(kind(1d0)) traffprofwe
real(kind(1d0)) trans_site
real(kind(1d0)) tsurf
real(kind(1d0)) wdir
real(kind(1d0)) wu_m3
real(kind(1d0)) xsmd
real(kind(1d0)) year
real(kind(1d0)) zenith_deg
real(kind(1d0)), dimension(2) qf_a
real(kind(1d0)), dimension(2) qf_b
real(kind(1d0)), dimension(2) qf_c
real(kind(1d0)), dimension(2) ah_min
real(kind(1d0)), dimension(2) ah_slope_heating
real(kind(1d0)), dimension(2) ah_slope_cooling
real(kind(1d0)), dimension(2) fcef_v_kgkm
real(kind(1d0)), dimension(2) numcapita
real(kind(1d0)), dimension(2) popdensdaytime
real(kind(1d0)), dimension(2) t_critic_heating
real(kind(1d0)), dimension(2) t_critic_cooling
real(kind(1d0)), dimension(2) trafficrate
real(kind(1d0)), dimension(2) qf0_beu
integer startdls
integer enddls
integer ncblstep
real(kind(1d0)) drainrt
real(kind(1d0)) rainbucket
real(kind(1d0)) raincover
real(kind(1d0)) rainmaxres
real(kind(1d0)) rainres
real(kind(1d0)) tempveg
real(kind(1d0)) absl
real(kind(1d0)) absk
real(kind(1d0)) heightgravity
real(kind(1d0)) transmin
real(kind(1d0)) transmax
integer posture
integer usevegdem
integer row
integer col
integer onlyglobal
integer solweigpoi_out
integer tmrt_out
integer lup2d_out
integer ldown2d_out
integer kup2d_out
integer kdown2d_out
integer gvf_out
integer solweig_ldown
integer outinterval
integer runforgrid
character(len=150) dsmpath
character(len=150) dsmname
character(len=150) cdsmname
character(len=150) tdsmname
character(len=150) svfpath
character(len=150) svfsuffix
character(len=150) buildingsname
Variable Documentation
absk
real(kind(1d0)) data_in::absk
Definition at line 1147 of file suews_ctrl_const.f95.
absl
real(kind(1d0)) data_in::absl
Definition at line 1147 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)):: absL, &             ! Absorption coefficient of longwave radiation of a person
                      absK, &             ! Absorption coefficient of shortwave radiation of a person
                      heightgravity, &    ! Centre of gravity for a standing person
                      TransMin, &         ! Tranmissivity of K through decidious vegetation (leaf on)
                      TransMax           ! Tranmissivity of K through decidious vegetation (leaf off)
ah_min
real(kind(1d0)), dimension(2) data_in::ah_min
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
ah_slope_cooling
real(kind(1d0)), dimension(2) data_in::ah_slope_cooling
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
ah_slope_heating
real(kind(1d0)), dimension(2) data_in::ah_slope_heating
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
albedochoice
integer data_in::albedochoice
Definition at line 1001 of file suews_ctrl_const.f95.
    INTEGER:: AlbedoChoice, &         !No additional albedo varaition (0); zenith angle calculation (1)
              !Currently set to 0 in SUEWS_Initial
              inputmetformat, &       !Defines format for met input data: LUMPS format(1) or SUEWS format(10)
              !Currently set to 10 in SUEWS_Initial
              evapmethod, &                  !Evaporation calculated according to Rutter (1) or Shuttleworth (2)
              !Currently set to 2 in OverallRunControl
              laicalcyes, &           !Use observed (0) or modelled (1) LAI
              !Currently set to 1 in OverallRunControl
              writedailystate        !Daily state file written (1)
alpha_qhqe
real(kind(1d0)) data_in::alpha_qhqe
Definition at line 1027 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  alpha_qhqe, & !Alpha parameter used in LUMPS QH and QE calculations [-]
                      alt, &       !Altitude in m
                      avdens, &    !Average air density
                      avkdn, &     !Average downwelling shortwave radiation
                      avrh, &      !Average relative humidity
                      avts, &      !Average surface temperature
                      avu1, &      !Average wind speed
                      avU10_ms, &  !Average wind speed at 10 m
                      azimuth, &   !Sun azimuth in degrees
                      BaseTHDD, &  !Base temperature for QF
                      BuildEnergyUse, &  ! Building energy use
                      CO2mWD, &    !Diurnal activity profile (weekday)
                      CO2mWE, &    !Diurnal activity profile (weekend)
                      CO2PointSource, & !CO2 point source [kg C day-1]
                      E_mod, &     !Modelled latent heat flux with LUMPS  [W m-2]
                      EF_umolCO2perJ, &!CO2 emission factor for fuels used for building heating [umol CO2 J-1]
                      emis_snow, & !Emissivity of snow
                      EnEF_v_Jkm, &!Heat release per vehicle per meter of travel [J km-1 veh-1]
                      EnProfWD, &  !Diurnal energy use profile (weekday)
                      EnProfWE, &  !Diurnal energy use profile (weekend)
                      Fc, &        !CO2 flux [umol m-2 s-1]
                      Fc_anthro, & !CO2 flux (anthropogenic part) [umol m-2 s-1]
                      Fc_biogen, & !CO2 flux (biogenic part) [umol m-2 s-1]
                      Fc_build, &  !CO2 flux (building energy use component) [umol m-2 s-1]
                      Fc_metab, &  !CO2 flux (human metabolism component) [umol m-2 s-1]
                      Fc_photo, &  !CO2 flux (photosynthesis component) [umol m-2 s-1]
                      Fc_point, &  !CO2 flux (Point source component) [umol m-2 s-1]
                      Fc_respi, &  !CO2 flux (non-human respiration component) [umol m-2 s-1]
                      Fc_traff, &  !CO2 flux (traffic component) [umol m-2 s-1]
                      fcld, &      !Cloud fraction modelled
                      fcld_obs, &  !Cloud fraction observed
                      FrFossilFuel_Heat, & !Fraction of fossil fuels used for building heating relative to district heating
                      FrFossilFuel_NonHeat, & !Fraction of fossil fuels used for energy consumption relative to district heating
                      FrPDDwe, &   !Fraction of weekend population to weekday population
                      h_mod, &     !Modelled sensible heat flux with LUMPS [W m-2]
                      kclear, &    !Theoretical downward shortwave radiation
                      kdiff, &     !Diffuse shortwave radiation
                      kdir, &      !Direct shortwave radiation
                      kup, &       !Upward shortwave radiation
                      LAI_obs, &   !LAI for study area provided in met forcing file
                      lat, &       !Latitude
                      ldown, &     !Downward longwave radiation
                      ldown_obs, & !Downwelling longwave radiation
                      lng, &       !Longitude
                      lup, &       !Upward longwave radiation
                      MaxFCMetab, &!Maximum (day) CO2 from human metabolism
                      MaxQFMetab, &!Maximum (day) anthropogenic heat from human metabolism
                      MinFCMetab, &!Minimum (night) CO2 from human metabolism
                      MinQFMetab, &!Minimum (night) anthropogenic heat from human metabolism
                      PopDensNighttime, & ! Nighttime population density [ha-1] (i.e. residents)
                      PopProfWD, & !Diurnal profile for population density (weekday)
                      PopProfWE, & !Diurnal profile for population density (weekend)
                      Precip, &    !Precipitation per timestep [mm]
                      Precip_hr, &    !Precipitation [mm hr-1]
                      Press_hPa, &  !Station air pressure in hPa
                      Pres_kPa, &   !Station air pressure in kPa
                      q2_gkg, &    ! Specific humidity at 2 m
                      qe, &        !Observed latent heat flux
                      qe_obs, &
                      QF_build, &  !Anthropogenic heat flux from building [W m-2]
                      QF_metab, &  !Anthropogenic heat flux from human metabolism [W m-2]
                      QF_traff, &  !Anthropogenic heat flux from traffic [W m-2]
                      qf_obs, &     !Observed anthropogenic heat flux
                      QF_SAHP, &    !Anthropogenic heat flux calculated by SAHP
                      QF_SAHP_base, &!Anthropogenic heat flux calculated by SAHP (temp independent part)
                      QF_SAHP_heat, &!Anthropogenic heat flux calculated by SAHP (heating part only)
                      QF_SAHP_ac, & !AC contribution
                      qh, &         !Observed sensible heat flux
                      qh_obs, &
                      QH_r, &      !Sensible heat flux calculated using resistance method
                      qn1, &       !Net all-wave radiation for the study area
                      qn1_bup, &
                      qn1_obs, &   !Observed new all-wave radiation
                      qn1_S, &     !Total net all-wave radiation for the SnowPack
                      qn1_snowfree, &    !Total net all-wave radiation for the snowfree surface
                      qs_obs, &        !Observed storage heat flux
                      QSanOHM, &   !Simulated storage heat flux by AnOHM, TS 30 May 2016
                      QSestm, &    !Simulated storage heat flux by ESTM, TS 30 May 2016
                      snow, &      !snow cover
                      snowFrac_obs, &!Observed snow cover
                      Temp_C, &    !Air temperature
                      t2_C, &      !Air temperature at 2 m, TS 20 May 2017
                      TrafficUnits, & !Option for traffic units (1=[veh km m-2 day-1] 2=[veh km cap-1 day-1])
                      TraffProfWD, &!Diurnal traffic profile (weekday)
                      TraffProfWE, &!Diurnal traffic profile (weekend)
                      trans_site, &  !Atmospheric transmissivity
                      tsurf, &   !Surface temperature
                      wdir, &      ! Wind direction
                      wu_m3, &     !Water use provided in met forcing file [m3]
                      xsmd, &      !Measured soil moisture deficit
                      year, &      !Year of the measurements
                      zenith_deg  !Sun zenith angle in degrees
alt
real(kind(1d0)) data_in::alt
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), suews_calculations(), and suews_translate().
avdens
real(kind(1d0)) data_in::avdens
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
avkdn
real(kind(1d0)) data_in::avkdn
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), suews_calculations(), and suews_translate().
avrh
real(kind(1d0)) data_in::avrh
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::nbl(), suews_calculations(), and suews_translate().
avts
real(kind(1d0)) data_in::avts
Definition at line 1027 of file suews_ctrl_const.f95.
avu1
real(kind(1d0)) data_in::avu1
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::nbl(), suews_calculations(), and suews_translate().
avu10_ms
real(kind(1d0)) data_in::avu10_ms
Definition at line 1027 of file suews_ctrl_const.f95.
azimuth
real(kind(1d0)) data_in::azimuth
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet().
basethdd
real(kind(1d0)) data_in::basethdd
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
blout
character(len=150) data_in::blout
Definition at line 945 of file suews_ctrl_const.f95.
buildenergyuse
real(kind(1d0)) data_in::buildenergyuse
Definition at line 1027 of file suews_ctrl_const.f95.
buildingsname
character(len=150) data_in::buildingsname
Definition at line 1169 of file suews_ctrl_const.f95.
cbluse
integer data_in::cbluse
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), ctrl_output::suews_output(), and suews_program().
cdsmname
character(len=150) data_in::cdsmname
Definition at line 1169 of file suews_ctrl_const.f95.
co2mwd
real(kind(1d0)) data_in::co2mwd
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
co2mwe
real(kind(1d0)) data_in::co2mwe
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
co2pointsource
real(kind(1d0)) data_in::co2pointsource
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
col
integer data_in::col
Definition at line 1153 of file suews_ctrl_const.f95.
diagnose
integer data_in::diagnose
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), metdisagg::disaggregatemet(), initialstate(), overallruncontrol(), suews_calculations(), ctrl_output::suews_output_agg(), suews_program(), and ctrl_output::suews_write_txt().
diagnosedisagg
integer data_in::diagnosedisagg
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disagg_lin(), metdisagg::disaggp_amongn(), metdisagg::disaggp_amongnmult(), metdisagg::disaggregatemet(), and overallruncontrol().
diagnosedisaggestm
integer data_in::diagnosedisaggestm
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), and overallruncontrol().
diagqn
integer data_in::diagqn
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_calculations().
diagqs
integer data_in::diagqs
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_calculations().
disaggmethod
integer data_in::disaggmethod
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), and overallruncontrol().
disaggmethodestm
integer data_in::disaggmethodestm
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), and overallruncontrol().
drainrt
real(kind(1d0)) data_in::drainrt
Definition at line 1139 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)):: DRAINRT, &      !Drainage rate of the water bucket [mm hr-1]
                      RAINBUCKET, &   !RAINFALL RESERVOIR [mm]
                      RAINCOVER, &
                      RAINMAXRES, &   !Maximum water bucket reservoir [mm]
                      RAINRES, &      ! [mm]
                      TEMPVEG        !TEMPORARY VEGETATIVE SURFACE FRACTION ADJUSTED BY RAINFALL
Referenced by suews_calculations(), and suews_translate().
dsmname
character(len=150) data_in::dsmname
Definition at line 1169 of file suews_ctrl_const.f95.
dsmpath
character(len=150) data_in::dsmpath
Definition at line 1169 of file suews_ctrl_const.f95.
    CHARACTER(len=150):: DSMPath, &    ! Path to DSMs
                         DSMname, &    ! Ground and building DSM
                         CDSMname, &   ! Canopy DSM
                         TDSMname, &   ! Trunk zone DSM
                         SVFPath, &    ! Path to SVFs
                         SVFsuffix, &  !
                         buildingsname! Boolean matrix for locations of building pixels
e_mod
real(kind(1d0)) data_in::e_mod
Definition at line 1027 of file suews_ctrl_const.f95.
ef_umolco2perj
real(kind(1d0)) data_in::ef_umolco2perj
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
emis_snow
real(kind(1d0)) data_in::emis_snow
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
emissionsmethod
integer data_in::emissionsmethod
Definition at line 963 of file suews_ctrl_const.f95.
    INTEGER:: EmissionsMethod, & !
              CBLuse, &               !CBL slab model used (1) or not used (0)
              MultipleMetFiles, &     !Indicates whether a single met file is used for all grids (0) or one for each grid (1)
              MultipleInitFiles, &      !Indicates whether a single initial conditions file is used for all grids (0) or one for each grid (1)
              MultipleESTMFiles, &    !Indicates whether a single ESTM input data file is used for all grids (0) or one for each grid (1)
              KeepTstepFilesIn, &     !Delete (0) or keep (1) input met files at resolution of tstep (used by python, not fortran)
              KeepTstepFilesOut, &    !Delete (0) or keep (1) output files at resolution of tstep (used by python, not fortran)
              ResolutionFilesIn, &    !Specify resolution of input file  [s]
              ResolutionFilesOut, &   !Specify resolution of output file [s]
              ResolutionFilesInESTM, &!Specify resolution of ESTM input file  [s]
              WriteOutOption, &         !Choose variables to include in main output file
              NetRadiationMethod, &   !Options for net all-wave radiation calculation
              OHMIncQF, &             !OHM calculation uses Q* only (0) or Q*+QF (1)
              StorageHeatMethod, &             !OHM (1); QS in met file (2); AnOHM(3); ESTM(4)
              SNOWuse, &              !Snow part used (1) or not used (0)
              SOLWEIGuse, &           !SOLWEIG part used (calculates Tmrt and other fluxes on a grid, FL)
              SMDMethod, &           !Use modelled (0) or observed(1,2) soil moisture
              WaterUseMethod, &            !Use modelled (0) or observed (1) water use
              RoughLenMomMethod, &              !Defines method for calculating z0 & zd
              DisaggMethod, &         ! Sets disaggregation method for original met forcing data
              DisaggMethodESTM, &         ! Sets disaggregation method for original met forcing data
              RainDisaggMethod, &     ! Sets disaggregation method for original met forcing data for rainfall
              RainAmongN, &           ! Number of subintervals over which to disaggregate rainfall
              KdownZen, &             ! Controls whether Kdown disaggregation uses zenith angle (1) or not (0)
              SuppressWarnings = 1, &     ! Set to 1 to prevent warnings.txt file from being written
              diagnose, &             !Set to 1 to get print-out of model progress
              diagnosedisagg, &       !Set to 1 to get print-out of met forcing disaggregation progress
              ncmode, &               !Write output file in netCDF (1) or not (0) , TS, 09 Dec 2016
              nrow, &                 !number of rows of checker board layout in the netCDF output, TS, 09 Dec 2016
              ncol, &                 !number of columns of checker board layout in the netCDF output, TS, 09 Dec 2016
              diagnosedisaggestm, &   !Set to 1 to get print-out of ESTM forcing disaggregation progress
              diagqn, diagqs         !Set to 1 to print values/components
Referenced by initialstate(), overallruncontrol(), suews_calculations(), and suews_translate().
enddls
integer data_in::enddls
Definition at line 1134 of file suews_ctrl_const.f95.
    INTEGER::endDLS   !DOY when daylight saving ends
Referenced by initialstate(), suews_calculations(), and suews_translate().
enef_v_jkm
real(kind(1d0)) data_in::enef_v_jkm
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
enprofwd
real(kind(1d0)) data_in::enprofwd
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
enprofwe
real(kind(1d0)) data_in::enprofwe
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
estmout_tt
character(len=150) data_in::estmout_tt
Definition at line 945 of file suews_ctrl_const.f95.
evapmethod
integer data_in::evapmethod
Definition at line 1001 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_calculations().
fc
real(kind(1d0)) data_in::fc
Definition at line 1027 of file suews_ctrl_const.f95.
fc_anthro
real(kind(1d0)) data_in::fc_anthro
Definition at line 1027 of file suews_ctrl_const.f95.
fc_biogen
real(kind(1d0)) data_in::fc_biogen
Definition at line 1027 of file suews_ctrl_const.f95.
fc_build
real(kind(1d0)) data_in::fc_build
Definition at line 1027 of file suews_ctrl_const.f95.
fc_metab
real(kind(1d0)) data_in::fc_metab
Definition at line 1027 of file suews_ctrl_const.f95.
fc_photo
real(kind(1d0)) data_in::fc_photo
Definition at line 1027 of file suews_ctrl_const.f95.
fc_point
real(kind(1d0)) data_in::fc_point
Definition at line 1027 of file suews_ctrl_const.f95.
fc_respi
real(kind(1d0)) data_in::fc_respi
Definition at line 1027 of file suews_ctrl_const.f95.
fc_traff
real(kind(1d0)) data_in::fc_traff
Definition at line 1027 of file suews_ctrl_const.f95.
fcef_v_kgkm
real(kind(1d0)), dimension(2) data_in::fcef_v_kgkm
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
fcld
real(kind(1d0)) data_in::fcld
Definition at line 1027 of file suews_ctrl_const.f95.
fcld_obs
real(kind(1d0)) data_in::fcld_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
filechoices
character(len=150) data_in::filechoices
Definition at line 945 of file suews_ctrl_const.f95.
Referenced by initialstate(), overallruncontrol(), and suews_translate().
filecode
character(len=20) data_in::filecode
Definition at line 941 of file suews_ctrl_const.f95.
    CHARACTER(len=20)::  FileCode   !Set in RunControl
Referenced by ctrl_output::filename_gen(), initialstate(), overallruncontrol(), suews_program(), and suews_translate().
filedaily
character(len=150) data_in::filedaily
Definition at line 945 of file suews_ctrl_const.f95.
filedscdestm
character(len=150) data_in::filedscdestm
Definition at line 945 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), and suews_program().
filedscdmet
character(len=150) data_in::filedscdmet
Definition at line 945 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), and suews_program().
fileestmts
character(len=150) data_in::fileestmts
Definition at line 945 of file suews_ctrl_const.f95.
Referenced by estm_module::suews_getestmdata(), and suews_program().
fileinputpath
character(len=150) data_in::fileinputpath
Definition at line 942 of file suews_ctrl_const.f95.
    CHARACTER(len=150):: FileInputPath, &   !Filepath for input files (set in RunControl)
                         FileOutputPath    !Filepath for output files (set in RunControl)
Referenced by bluews_module::cbl_readinputdata(), estm_module::estm_initials(), initialstate(), nextinitial(), numberrows(), overallruncontrol(), readcoeff(), bluews_module::sonde(), and suews_program().
filemet
character(len=150) data_in::filemet
Definition at line 945 of file suews_ctrl_const.f95.
Referenced by suews_initializemetdata(), and suews_program().
fileorigestm
character(len=150) data_in::fileorigestm
Definition at line 945 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), and suews_program().
fileorigmet
character(len=150) data_in::fileorigmet
Definition at line 945 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), and suews_program().
fileout
character(len=150) data_in::fileout
Definition at line 945 of file suews_ctrl_const.f95.
    CHARACTER(len=150):: FileOut, &         !Output file name
                         FileChoices, &     !Run characteristics file name
                         FileMet, &         !Meteorological forcing file name
                         FileOrigMet, &     !Original meteorological forcing file name (i.e. before downscaling)
                         FileOrigESTM, &    !Original ESTM forcing file name (i.e. before downscaling)
                         FileDscdMet, &     !Downscaled meteorological forcing file name
                         FileDscdESTM, &    !Downscaled ESTM forcing file name
                         FileDaily, &       !Daily State output file name
                         FileESTMTs, &      !ESTM input file name
                         SOLWEIGpoiOut, &   !SOLWEIG poi file name
                         BLout, &             !CLB output file name
                         FileOut_tt, &        !Output file name (for resolution at model time-step)
                         ESTMOut_tt
fileout_tt
character(len=150) data_in::fileout_tt
Definition at line 945 of file suews_ctrl_const.f95.
fileoutputpath
character(len=150) data_in::fileoutputpath
Definition at line 942 of file suews_ctrl_const.f95.
Referenced by ctrl_output::filename_gen(), initialstate(), overallruncontrol(), and suews_translate().
frfossilfuel_heat
real(kind(1d0)) data_in::frfossilfuel_heat
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
frfossilfuel_nonheat
real(kind(1d0)) data_in::frfossilfuel_nonheat
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
frpddwe
real(kind(1d0)) data_in::frpddwe
Definition at line 1027 of file suews_ctrl_const.f95.
gvf_out
integer data_in::gvf_out
Definition at line 1153 of file suews_ctrl_const.f95.
h_mod
real(kind(1d0)) data_in::h_mod
Definition at line 1027 of file suews_ctrl_const.f95.
heightgravity
real(kind(1d0)) data_in::heightgravity
Definition at line 1147 of file suews_ctrl_const.f95.
inputmetformat
integer data_in::inputmetformat
Definition at line 1001 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), overallruncontrol(), and suews_initializemetdata().
kclear
real(kind(1d0)) data_in::kclear
Definition at line 1027 of file suews_ctrl_const.f95.
kdiff
real(kind(1d0)) data_in::kdiff
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
kdir
real(kind(1d0)) data_in::kdir
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
kdown2d_out
integer data_in::kdown2d_out
Definition at line 1153 of file suews_ctrl_const.f95.
kdownzen
integer data_in::kdownzen
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), and overallruncontrol().
keeptstepfilesin
integer data_in::keeptstepfilesin
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), metdisagg::disaggregatemet(), and overallruncontrol().
keeptstepfilesout
integer data_in::keeptstepfilesout
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and ctrl_output::suews_output().
kup
real(kind(1d0)) data_in::kup
Definition at line 1027 of file suews_ctrl_const.f95.
kup2d_out
integer data_in::kup2d_out
Definition at line 1153 of file suews_ctrl_const.f95.
lai_obs
real(kind(1d0)) data_in::lai_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
laicalcyes
integer data_in::laicalcyes
Definition at line 1001 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_calculations().
lat
real(kind(1d0)) data_in::lat
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by checkinitial(), metdisagg::disaggregatemet(), initialstate(), suews_calculations(), and suews_translate().
ldown
real(kind(1d0)) data_in::ldown
Definition at line 1027 of file suews_ctrl_const.f95.
ldown2d_out
integer data_in::ldown2d_out
Definition at line 1153 of file suews_ctrl_const.f95.
ldown_obs
real(kind(1d0)) data_in::ldown_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
ldown_option
integer data_in::ldown_option
Definition at line 1013 of file suews_ctrl_const.f95.
    INTEGER:: ldown_option           !Parameterisation used for downward longwave radiation (1/2/3)
Referenced by metdisagg::disaggregatemet(), and suews_initializemetdata().
lfnold
integer data_in::lfnold
Definition at line 1016 of file suews_ctrl_const.f95.
lfnout
integer data_in::lfnout
Definition at line 1016 of file suews_ctrl_const.f95.
    INTEGER:: lfnout, &               !Error Output write units
              lfnoutC, &              !Clean output write units
              lfnOld                 !!Was used for GridConnections
lfnoutc
integer data_in::lfnoutc
Definition at line 1016 of file suews_ctrl_const.f95.
lng
real(kind(1d0)) data_in::lng
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), suews_calculations(), and suews_translate().
lup
real(kind(1d0)) data_in::lup
Definition at line 1027 of file suews_ctrl_const.f95.
lup2d_out
integer data_in::lup2d_out
Definition at line 1153 of file suews_ctrl_const.f95.
maxfcmetab
real(kind(1d0)) data_in::maxfcmetab
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
maxqfmetab
real(kind(1d0)) data_in::maxqfmetab
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
minfcmetab
real(kind(1d0)) data_in::minfcmetab
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
minqfmetab
real(kind(1d0)) data_in::minqfmetab
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
multipleestmfiles
integer data_in::multipleestmfiles
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_program().
multipleinitfiles
integer data_in::multipleinitfiles
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by initialstate(), and overallruncontrol().
multiplemetfiles
integer data_in::multiplemetfiles
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_program().
multrainamongn
integer, dimension(5) data_in::multrainamongn
Definition at line 997 of file suews_ctrl_const.f95.
    INTEGER, DIMENSION(5):: MultRainAmongN           ! RainAmongN for each intensity bin
Referenced by metdisagg::disaggregatemet(), and overallruncontrol().
multrainamongnupperi
real(kind(1d0)), dimension(5) data_in::multrainamongnupperi
Definition at line 998 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(5):: MultRainAmongNUpperI   ! Upper bound of intensity bin for which to apply MultRainAmongN
Referenced by metdisagg::disaggp_amongnmult(), metdisagg::disaggregatemet(), and overallruncontrol().
ncblstep
integer data_in::ncblstep
Definition at line 1136 of file suews_ctrl_const.f95.
    INTEGER::nCBLstep  !number of time steps of Runge-kutta methods in one hour
ncmode
integer data_in::ncmode
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by ctrl_output::filename_gen(), overallruncontrol(), and suews_program().
ncol
integer data_in::ncol
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_program().
netradiationmethod
integer data_in::netradiationmethod
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), overallruncontrol(), suews_calculations(), suews_initializemetdata(), and suews_translate().
nrow
integer data_in::nrow
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_program().
numcapita
real(kind(1d0)), dimension(2) data_in::numcapita
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
ohmincqf
integer data_in::ohmincqf
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_calculations().
onlyglobal
integer data_in::onlyglobal
Definition at line 1153 of file suews_ctrl_const.f95.
outinterval
integer data_in::outinterval
Definition at line 1153 of file suews_ctrl_const.f95.
outputformats
integer data_in::outputformats
Definition at line 1020 of file suews_ctrl_const.f95.
    INTEGER:: OutputFormats   !Used to control writing out of output file format
Referenced by suews_program().
popdensdaytime
real(kind(1d0)), dimension(2) data_in::popdensdaytime
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
popdensnighttime
real(kind(1d0)) data_in::popdensnighttime
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
popprofwd
real(kind(1d0)) data_in::popprofwd
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
popprofwe
real(kind(1d0)) data_in::popprofwe
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
posture
integer data_in::posture
Definition at line 1153 of file suews_ctrl_const.f95.
    INTEGER:: Posture, &                ! 1.Standing, 2.Sitting
              usevegdem, &          ! With vegetation (1)
              row, &                    ! Y coordinate for point of interest
              col, &                    ! X coordinate for point of interest
              onlyglobal, &             ! if no diffuse and direct SW, then =1
              SOLWEIGpoi_out, &         ! write output variables at point of interest
              Tmrt_out, &               ! write output Tmrt grid
              Lup2d_out, &              ! write output Lup grid
              Ldown2d_out, &            ! write output Ldown grid
              Kup2d_out, &              ! write output Kup grid
              Kdown2d_out, &            ! write output Kdown grid
              GVF_out, &                ! write output GroundViewFActor grid
              SOLWEIG_ldown, &          ! 1= use SOLWEIG code to estimate Ldown, 0=use SEUWS
              OutInterval, &            ! Output interval in minutes
              RunForGrid               ! If only one grid should be run. All grids -999
precip
real(kind(1d0)) data_in::precip
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
precip_hr
real(kind(1d0)) data_in::precip_hr
Definition at line 1027 of file suews_ctrl_const.f95.
pres_kpa
real(kind(1d0)) data_in::pres_kpa
Definition at line 1027 of file suews_ctrl_const.f95.
press_hpa
real(kind(1d0)) data_in::press_hpa
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), bluews_module::nbl(), suews_calculations(), and suews_translate().
progname
character(len=90) data_in::progname = 'SUEWS_V2019a'
Definition at line 938 of file suews_ctrl_const.f95.
    CHARACTER(len=90)::progname = 'SUEWS_V2019a'
Referenced by suews_program().
q2_gkg
real(kind(1d0)) data_in::q2_gkg
Definition at line 1027 of file suews_ctrl_const.f95.
qe
real(kind(1d0)) data_in::qe
Definition at line 1027 of file suews_ctrl_const.f95.
qe_obs
real(kind(1d0)) data_in::qe_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
qf0_beu
real(kind(1d0)), dimension(2) data_in::qf0_beu
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qf_a
real(kind(1d0)), dimension(2) data_in::qf_a
Definition at line 1120 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(2)::Qf_A, Qf_B, Qf_C, &   !Qf coefficients
                                    AH_MIN, &    !Minimum anthropogenic heat flux (AnthropHeatMethod = 1)
                                    AH_SLOPE_Heating, &  !Slope of the antrhropogenic heat flux calculation (AnthropHeatMethod = 1)
                                    AH_SLOPE_Cooling, &
                                    FcEF_v_kgkm, &
                                    NumCapita, &
                                    PopDensDaytime, &
                                    T_CRITIC_Heating, & !Critical temperature
                                    T_CRITIC_Cooling, & !Critical cooling temperature
                                    TrafficRate, & !Traffic rate
                                    QF0_BEU
Referenced by suews_calculations(), and suews_translate().
qf_b
real(kind(1d0)), dimension(2) data_in::qf_b
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qf_build
real(kind(1d0)) data_in::qf_build
Definition at line 1027 of file suews_ctrl_const.f95.
qf_c
real(kind(1d0)), dimension(2) data_in::qf_c
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qf_metab
real(kind(1d0)) data_in::qf_metab
Definition at line 1027 of file suews_ctrl_const.f95.
qf_obs
real(kind(1d0)) data_in::qf_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qf_sahp
real(kind(1d0)) data_in::qf_sahp
Definition at line 1027 of file suews_ctrl_const.f95.
qf_sahp_ac
real(kind(1d0)) data_in::qf_sahp_ac
Definition at line 1027 of file suews_ctrl_const.f95.
qf_sahp_base
real(kind(1d0)) data_in::qf_sahp_base
Definition at line 1027 of file suews_ctrl_const.f95.
qf_sahp_heat
real(kind(1d0)) data_in::qf_sahp_heat
Definition at line 1027 of file suews_ctrl_const.f95.
qf_traff
real(kind(1d0)) data_in::qf_traff
Definition at line 1027 of file suews_ctrl_const.f95.
qh
real(kind(1d0)) data_in::qh
Definition at line 1027 of file suews_ctrl_const.f95.
qh_obs
real(kind(1d0)) data_in::qh_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qh_r
real(kind(1d0)) data_in::qh_r
Definition at line 1027 of file suews_ctrl_const.f95.
qn1
real(kind(1d0)) data_in::qn1
Definition at line 1027 of file suews_ctrl_const.f95.
qn1_bup
real(kind(1d0)) data_in::qn1_bup
Definition at line 1027 of file suews_ctrl_const.f95.
qn1_obs
real(kind(1d0)) data_in::qn1_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qn1_s
real(kind(1d0)) data_in::qn1_s
Definition at line 1027 of file suews_ctrl_const.f95.
qn1_snowfree
real(kind(1d0)) data_in::qn1_snowfree
Definition at line 1027 of file suews_ctrl_const.f95.
qs_obs
real(kind(1d0)) data_in::qs_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qsanohm
real(kind(1d0)) data_in::qsanohm
Definition at line 1027 of file suews_ctrl_const.f95.
qsestm
real(kind(1d0)) data_in::qsestm
Definition at line 1027 of file suews_ctrl_const.f95.
rainamongn
integer data_in::rainamongn
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), and overallruncontrol().
rainbucket
real(kind(1d0)) data_in::rainbucket
Definition at line 1139 of file suews_ctrl_const.f95.
raincover
real(kind(1d0)) data_in::raincover
Definition at line 1139 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
raindisaggmethod
integer data_in::raindisaggmethod
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), and overallruncontrol().
rainmaxres
real(kind(1d0)) data_in::rainmaxres
Definition at line 1139 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
rainres
real(kind(1d0)) data_in::rainres
Definition at line 1139 of file suews_ctrl_const.f95.
resolutionfilesin
integer data_in::resolutionfilesin
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), overallruncontrol(), and suews_program().
resolutionfilesinestm
integer data_in::resolutionfilesinestm
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregateestm(), overallruncontrol(), and suews_program().
resolutionfilesout
integer data_in::resolutionfilesout
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and ctrl_output::suews_output().
roughlenmommethod
integer data_in::roughlenmommethod
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by initialstate(), overallruncontrol(), suews_calculations(), and suews_translate().
row
integer data_in::row
Definition at line 1153 of file suews_ctrl_const.f95.
runforgrid
integer data_in::runforgrid
Definition at line 1153 of file suews_ctrl_const.f95.
skipheadermet
integer data_in::skipheadermet = 1
Definition at line 960 of file suews_ctrl_const.f95.
    INTEGER:: SkipHeaderMet = 1        !Number of header lines to skip in met forcing file
Referenced by estm_module::suews_getestmdata(), and suews_initializemetdata().
skipheadersiteinfo
integer data_in::skipheadersiteinfo = 2
Definition at line 959 of file suews_ctrl_const.f95.
    INTEGER:: SkipHeaderSiteInfo = 2   !Number of header lines to skip in SiteInfo files
Referenced by overallruncontrol(), and readcoeff().
smdmethod
integer data_in::smdmethod
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet(), overallruncontrol(), suews_calculations(), and suews_initializemetdata().
snow
real(kind(1d0)) data_in::snow
Definition at line 1027 of file suews_ctrl_const.f95.
snowfrac_obs
real(kind(1d0)) data_in::snowfrac_obs
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowuse
integer data_in::snowuse
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by checkinitial(), metdisagg::disaggregatemet(), initialstate(), nextinitial(), overallruncontrol(), suews_calculations(), suews_initializemetdata(), ctrl_output::suews_output(), suews_translate(), and suews_translateback().
solweig_ldown
integer data_in::solweig_ldown
Definition at line 1153 of file suews_ctrl_const.f95.
solweigpoi_out
integer data_in::solweigpoi_out
Definition at line 1153 of file suews_ctrl_const.f95.
Referenced by ctrl_output::suews_output().
solweigpoiout
character(len=150) data_in::solweigpoiout
Definition at line 945 of file suews_ctrl_const.f95.
solweiguse
integer data_in::solweiguse
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and suews_program().
startdls
integer data_in::startdls
Definition at line 1133 of file suews_ctrl_const.f95.
    INTEGER::startDLS   !DOY when daylight saving starts
Referenced by initialstate(), suews_calculations(), and suews_translate().
storageheatmethod
integer data_in::storageheatmethod
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), suews_calculations(), ctrl_output::suews_output(), suews_program(), and suews_translate().
suppresswarnings
integer data_in::suppresswarnings = 1
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by errorhint(), and overallruncontrol().
svfpath
character(len=150) data_in::svfpath
Definition at line 1169 of file suews_ctrl_const.f95.
svfsuffix
character(len=150) data_in::svfsuffix
Definition at line 1169 of file suews_ctrl_const.f95.
t2_c
real(kind(1d0)) data_in::t2_c
Definition at line 1027 of file suews_ctrl_const.f95.
t_critic_cooling
real(kind(1d0)), dimension(2) data_in::t_critic_cooling
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
t_critic_heating
real(kind(1d0)), dimension(2) data_in::t_critic_heating
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
tdsmname
character(len=150) data_in::tdsmname
Definition at line 1169 of file suews_ctrl_const.f95.
temp_c
real(kind(1d0)) data_in::temp_c
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), checkinitial(), bluews_module::nbl(), suews_calculations(), and suews_translate().
tempveg
real(kind(1d0)) data_in::tempveg
Definition at line 1139 of file suews_ctrl_const.f95.
timezone
real(kind(1d0)) data_in::timezone
Definition at line 1023 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: timezone      !Timezone (GMT=0)
Referenced by metdisagg::disaggregatemet(), suews_calculations(), and suews_translate().
tmrt_out
integer data_in::tmrt_out
Definition at line 1153 of file suews_ctrl_const.f95.
trafficrate
real(kind(1d0)), dimension(2) data_in::trafficrate
Definition at line 1120 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
trafficunits
real(kind(1d0)) data_in::trafficunits
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
traffprofwd
real(kind(1d0)) data_in::traffprofwd
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
traffprofwe
real(kind(1d0)) data_in::traffprofwe
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
trans_site
real(kind(1d0)) data_in::trans_site
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
transmax
real(kind(1d0)) data_in::transmax
Definition at line 1147 of file suews_ctrl_const.f95.
transmin
real(kind(1d0)) data_in::transmin
Definition at line 1147 of file suews_ctrl_const.f95.
tsurf
real(kind(1d0)) data_in::tsurf
Definition at line 1027 of file suews_ctrl_const.f95.
usevegdem
integer data_in::usevegdem
Definition at line 1153 of file suews_ctrl_const.f95.
waterusemethod
integer data_in::waterusemethod
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by initialstate(), overallruncontrol(), and suews_calculations().
wdir
real(kind(1d0)) data_in::wdir
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_translate().
writedailystate
integer data_in::writedailystate
Definition at line 1001 of file suews_ctrl_const.f95.
Referenced by overallruncontrol().
writeoutoption
integer data_in::writeoutoption
Definition at line 963 of file suews_ctrl_const.f95.
Referenced by overallruncontrol(), and ctrl_output::suews_output().
wu_m3
real(kind(1d0)) data_in::wu_m3
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
xsmd
real(kind(1d0)) data_in::xsmd
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
year
real(kind(1d0)) data_in::year
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by nextinitial().
zenith_deg
real(kind(1d0)) data_in::zenith_deg
Definition at line 1027 of file suews_ctrl_const.f95.
Referenced by metdisagg::disaggregatemet().