SUEWS: gas Module Reference
gas Module Reference
Variables
real(kind(1d0)) comp = 0.9995
real(kind(1d0)) epsil = 0.62197
real(kind(1d0)) epsil_gkg = 621.97
real(kind(1d0)) dry_gas = 8.31451
real(kind(1d0)) gas_ct_wat = 461.05
real(kind(1d0)) molar = 0.028965
real(kind(1d0)) molar_wat_vap = 0.0180153
real(kind(1d0)) gas_ct_dry = 8.31451/0.028965
real(kind(1d0)) gas_ct_wv = 8.31451/0.0180153
Variable Documentation
comp
real(kind(1d0)) gas::comp = 0.9995
Definition at line 1332 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  comp = 0.9995
dry_gas
real(kind(1d0)) gas::dry_gas = 8.31451
Definition at line 1335 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  dry_gas = 8.31451 !Dry gas constant (J/k/mol)
epsil
real(kind(1d0)) gas::epsil = 0.62197
Definition at line 1333 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  epsil = 0.62197   !ratio molecular weight of water vapor/dry air (kg/mol/kg/mol)
Referenced by meteo::psyc_const().
epsil_gkg
real(kind(1d0)) gas::epsil_gkg = 621.97
Definition at line 1334 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  epsil_gkg = 621.97   !ratio molecular weight of water vapor/dry air in g/kg
gas_ct_dry
real(kind(1d0)) gas::gas_ct_dry = 8.31451/0.028965
Definition at line 1339 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  gas_ct_dry = 8.31451/0.028965 !j/kg/k=dry_gas/molar
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
gas_ct_wat
real(kind(1d0)) gas::gas_ct_wat = 461.05
Definition at line 1336 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  gas_ct_wat = 461.05 !Gas constant for water (J/kg/K)
gas_ct_wv
real(kind(1d0)) gas::gas_ct_wv = 8.31451/0.0180153
Definition at line 1340 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  gas_ct_wv = 8.31451/0.0180153 !j/kg/kdry_gas/molar_wat_vap
molar
real(kind(1d0)) gas::molar = 0.028965
Definition at line 1337 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  molar = 0.028965 !Dry air molar fraction in kg/mol
molar_wat_vap
real(kind(1d0)) gas::molar_wat_vap = 0.0180153
Definition at line 1338 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::  molar_wat_vap = 0.0180153 !Molar fraction of water vapor in kg/mol