SUEWS: defaultnotused Module Reference
defaultnotused Module Reference
Variables
real(kind(1d0)) notused = -55.55
real(kind(1d0)) reall
real(kind(1d0)) nan = -999
real(kind(1d0)) pnan = 999
integer notusedi = -55
integer ios_out
integer errorchoice
integer warningchoice
Variable Documentation
errorchoice
integer defaultnotused::errorchoice
Definition at line 1287 of file suews_ctrl_const.f95.
    INTEGER:: errorChoice, warningChoice  !errorChoice/warningChoice defines if problems.txt/warnings.txt is opened for the first time
Referenced by errorhint(), and suews_program().
ios_out
integer defaultnotused::ios_out
Definition at line 1286 of file suews_ctrl_const.f95.
Referenced by initialstate(), skipheader(), estm_module::suews_getestmdata(), and suews_initializemetdata().
nan
real(kind(1d0)) defaultnotused::nan = -999
Definition at line 1285 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), estm_module::estm_translate(), initialstate(), metread(), and suews_program().
notused
real(kind(1d0)) defaultnotused::notused = -55.55
Definition at line 1285 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)):: notUsed = -55.55, reall, nan = -999, pnan = 999
Referenced by codematchanthropogenic(), codematchbiogen(), codematchconductance(), codematchdist(), codematchestm(), codematchestm_class(), codematchirrigation(), codematchnonveg(), codematchohm(), codematchprof(), codematchsnow(), codematchsoil(), codematchveg(), codematchwater(), bluews_module::diff(), metdisagg::disagg_lin(), metdisagg::disaggp_amongn(), metdisagg::disaggp_amongnmult(), metdisagg::disaggregateestm(), metdisagg::disaggregatemet(), initialstate(), inputheadercheck(), metread(), nextinitial(), numberrows(), overallruncontrol(), readcoeff(), skipheader(), narp_module::smithlambda(), estm_module::suews_getestmdata(), suews_initializemetdata(), suews_program(), and suews_translate().
notusedi
integer defaultnotused::notusedi = -55
Definition at line 1286 of file suews_ctrl_const.f95.
    INTEGER:: notUsedI = -55, ios_out
Referenced by checkinitial(), codematchanthropogenic(), codematchbiogen(), codematchconductance(), codematchdist(), codematchestm(), codematchestm_class(), codematchirrigation(), codematchnonveg(), codematchohm(), codematchprof(), codematchsnow(), codematchsoil(), codematchveg(), codematchwater(), bluews_module::diff(), metdisagg::disagg_lin(), metdisagg::disaggp_amongn(), metdisagg::disaggp_amongnmult(), metdisagg::disaggregateestm(), metdisagg::disaggregatemet(), initialstate(), inputheadercheck(), metread(), nextinitial(), numberrows(), overallruncontrol(), readcoeff(), suews_initializemetdata(), and suews_translate().
pnan
real(kind(1d0)) defaultnotused::pnan = 999
Definition at line 1285 of file suews_ctrl_const.f95.
reall
real(kind(1d0)) defaultnotused::reall
Definition at line 1285 of file suews_ctrl_const.f95.
Referenced by skipheader().
warningchoice
integer defaultnotused::warningchoice
Definition at line 1287 of file suews_ctrl_const.f95.
Referenced by errorhint(), and suews_program().