SUEWS: mod_z Module Reference
mod_z Module Reference
Variables
real(kind(1d0)) zzd
real(kind(1d0)) z0m
real(kind(1d0)) zdm
real(kind(1d0)) z0m_in
real(kind(1d0)) zdm_in
real(kind(1d0)) z
real(kind(1e10)) z0v
Variable Documentation
z
real(kind(1d0)) mod_z::z
Definition at line 1345 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
z0m
real(kind(1d0)) mod_z::z0m
Definition at line 1345 of file suews_ctrl_const.f95.
Referenced by initialstate(), and suews_translate().
z0m_in
real(kind(1d0)) mod_z::z0m_in
Definition at line 1345 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
z0v
real(kind(1e10)) mod_z::z0v
Definition at line 1351 of file suews_ctrl_const.f95.
    REAL(KIND(1E10))::z0V      !Roughness length for vapour
zdm
real(kind(1d0)) mod_z::zdm
Definition at line 1345 of file suews_ctrl_const.f95.
Referenced by initialstate(), and suews_translate().
zdm_in
real(kind(1d0)) mod_z::zdm_in
Definition at line 1345 of file suews_ctrl_const.f95.
Referenced by initialstate(), suews_calculations(), and suews_translate().
zzd
real(kind(1d0)) mod_z::zzd
Definition at line 1345 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)) :: zzd, &  !Active measurement height (meas. height-displac. height)
                       z0m, &  !Aerodynamic roughness length
                       zdm, &  !Displacement height
                       z0m_in, &  !Aerodynamic roughness length set in SiteSelect
                       zdm_in, &  !Displacement height set in SiteSelect
                       z      !Windspeed height
Referenced by initialstate(), and suews_translate().