SUEWS: mod_datetime Module Reference
mod_datetime Module Reference
Data Types
interface datetime
Functions/Subroutines
pure elemental type(datetime) function datetime_constructor (year, month, day, hour, minute, second, millisecond, tz)
pure elemental integer function getyear (self)
pure elemental integer function getmonth (self)
pure elemental integer function getday (self)
pure elemental integer function gethour (self)
pure elemental integer function getminute (self)
pure elemental integer function getsecond (self)
pure elemental integer function getmillisecond (self)
pure elemental real(kind=real64) function gettz (self)
pure elemental subroutine addmilliseconds (self, ms)
pure elemental subroutine addseconds (self, s)
pure elemental subroutine addminutes (self, m)
pure elemental subroutine addhours (self, h)
pure elemental subroutine adddays (self, d)
pure elemental character(len=23) function isoformat (self, sep)
pure elemental logical function isvalid (self)
type(datetime) function now ()
pure elemental integer function weekday (self)
pure elemental integer function isoweekday (self)
pure elemental character(len=9) function weekdaylong (self)
pure elemental character(len=9) function isoweekdaylong (self)
pure elemental character(len=3) function weekdayshort (self)
pure elemental character(len=3) function isoweekdayshort (self)
integer function, dimension(3) isocalendar (self)
integer function secondssinceepoch (self)
character(len=:) function, allocatable strftime (self, format)
pure elemental type(tm_struct) function tm (self)
pure elemental character(len=5) function tzoffset (self)
pure elemental type(datetime) function utc (self)
pure elemental integer function yearday (self)
pure elemental type(datetime) function datetime_plus_timedelta (d0, t)
pure elemental type(datetime) function timedelta_plus_datetime (t, d0)
pure elemental type(datetime) function datetime_minus_timedelta (d0, t)
pure elemental type(timedelta) function datetime_minus_datetime (d0, d1)
pure elemental logical function gt (d0, d1)
pure elemental logical function lt (d0, d1)
pure elemental logical function eq (d0, d1)
pure elemental logical function neq (d0, d1)
pure elemental logical function ge (d0, d1)
pure elemental logical function le (d0, d1)
pure elemental logical function, public isleapyear (year)
pure type(datetime) function, dimension(:), allocatable, public datetimerange (d0, d1, t)
pure elemental integer function, public daysinmonth (month, year)
pure elemental integer function, public daysinyear (year)
pure elemental real(kind=real64) function, public date2num (d)
pure elemental type(datetime) function, public num2date (num)
type(datetime) function, public strptime (str, format)
pure elemental type(datetime) function, public tm2date (ctime)
pure character(len=length) function int2str (i, length)
Function/Subroutine Documentation
adddays()
pure elemental subroutine mod_datetime::adddays (class(datetime), intent(inout) self, integer, intent(in) d) private
Definition at line 775 of file suews_util_datetime.f95.
       !! Adds an integer number of dayss to self. Called by `datetime`
       !! addition (`+`) and subtraction (`-`) operators.
       class(datetime), intent(inout) :: self !! `datetime` instance
       integer, intent(in)    :: d    !! number of days to add
       integer :: daysInCurrentMonth
       self%day = self%day + d
       do
          daysincurrentmonth = daysinmonth(self%month, self%year)
          if (self%day > daysincurrentmonth) then
             self%day = self%day - daysincurrentmonth
             self%month = self%month + 1
             if (self%month > 12) then
                self%year = self%year + self%month/12
                self%month = mod(self%month, 12)
             endif
          elseif (self%day < 1) then
             self%month = self%month - 1
             if (self%month < 1) then
                self%year = self%year + self%month/12 - 1
                self%month = 12 + mod(self%month, 12)
             endif
             self%day = self%day + daysinmonth(self%month, self%year)
          else
             exit
          endif
       enddo
References daysinmonth().
addhours()
pure elemental subroutine mod_datetime::addhours (class(datetime), intent(inout) self, integer, intent(in) h) private
Definition at line 751 of file suews_util_datetime.f95.
       !! Adds an integer number of hours to self. Called by `datetime`
       !! addition (`+`) and subtraction (`-`) operators.
       class(datetime), intent(inout) :: self !! `datetime` instance
       integer, intent(in)    :: h    !! number of hours to add
       self%hour = self%hour + h
       do
          if (self%hour >= 24) then
             call self%addDays(self%hour/24)
             self%hour = mod(self%hour, 24)
          elseif (self%hour < 0) then
             call self%addDays(self%hour/24 - 1)
             self%hour = mod(self%hour, 24) + 24
          else
             exit
          endif
       enddo
addmilliseconds()
pure elemental subroutine mod_datetime::addmilliseconds (class(datetime), intent(inout) self, integer, intent(in) ms) private
Definition at line 676 of file suews_util_datetime.f95.
       !! Adds an integer number of milliseconds to self. Called by `datetime`
       !! addition (`+`) and subtraction (`-`) operators.
       class(datetime), intent(inout) :: self !! `datetime` instance
       integer, intent(in)    :: ms   !! number of milliseconds to add
       self%millisecond = self%millisecond + ms
       do
          if (self%millisecond >= 1000) then
             call self%addSeconds(self%millisecond/1000)
             self%millisecond = mod(self%millisecond, 1000)
          elseif (self%millisecond < 0) then
             call self%addSeconds(self%millisecond/1000 - 1)
             self%millisecond = mod(self%millisecond, 1000) + 1000
          else
             exit
          endif
       enddo
addminutes()
pure elemental subroutine mod_datetime::addminutes (class(datetime), intent(inout) self, integer, intent(in) m) private
Definition at line 727 of file suews_util_datetime.f95.
       !! Adds an integer number of minutes to self. Called by `datetime`
       !! addition (`+`) and subtraction (`-`) operators.
       class(datetime), intent(inout) :: self !! `datetime` instance
       integer, intent(in)    :: m    !! number of minutes to add
       self%minute = self%minute + m
       do
          if (self%minute >= 60) then
             call self%addHours(self%minute/60)
             self%minute = mod(self%minute, 60)
          elseif (self%minute < 0) then
             call self%addHours(self%minute/60 - 1)
             self%minute = mod(self%minute, 60) + 60
          else
             exit
          endif
       enddo
addseconds()
pure elemental subroutine mod_datetime::addseconds (class(datetime), intent(inout) self, integer, intent(in) s) private
Definition at line 703 of file suews_util_datetime.f95.
       !! Adds an integer number of seconds to self. Called by `datetime`
       !! addition (`+`) and subtraction (`-`) operators.
       class(datetime), intent(inout) :: self !! `datetime` instance
       integer, intent(in)    :: s    !! number of seconds to add
       self%second = self%second + s
       do
          if (self%second >= 60) then
             call self%addMinutes(self%second/60)
             self%second = mod(self%second, 60)
          elseif (self%second < 0) then
             call self%addMinutes(self%second/60 - 1)
             self%second = mod(self%second, 60) + 60
          else
             exit
          endif
       enddo
date2num()
pure elemental real(kind=real64) function, public mod_datetime::date2num (type(datetime), intent(in) d)
Definition at line 1505 of file suews_util_datetime.f95.
       !! Given a datetime instance d, returns number of days since
       !! `0001-01-01 00:00:00`, taking into account the timezone offset.
       type(datetime), intent(in) :: d !! `datetime` instance
       type(datetime) :: d_utc
       integer :: year
       ! Convert to UTC first
       d_utc = d%utc()
       ! d_utc % year must be positive:
       if (d_utc%year < 1) then
          date2num = 0
          return
       endif
       date2num = 0
       do year = 1, d_utc%year - 1
          date2num = date2num + daysinyear(year)
       enddo
       date2num = date2num &
                  + d_utc%yearday() &
                  + d_utc%hour*h2d &
                  +d_utc%minute*m2d &
                  +(d_utc%second + 1e-3_real64*d_utc%millisecond)*s2d
References daysinyear().
Referenced by datetime_minus_datetime(), and datetimerange().
datetime_constructor()
pure elemental type(datetime) function mod_datetime::datetime_constructor (integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, real(kind=real64), intent(in), optional tz) private
Definition at line 562 of file suews_util_datetime.f95.
       !! Constructor function for the `datetime` class.
       integer, intent(in), optional :: year        !! year
       integer, intent(in), optional :: month       !! month
       integer, intent(in), optional :: day         !! day
       integer, intent(in), optional :: hour        !! hour
       integer, intent(in), optional :: minute      !! minute
       integer, intent(in), optional :: second      !! second
       integer, intent(in), optional :: millisecond !! millisecond
       real(kind=real64), intent(in), optional :: tz          !! timezone offset in hours
       if (present(year)) then
          datetime_constructor%year = year
       else
          datetime_constructor%year = 1
       endif
       if (present(month)) then
          datetime_constructor%month = month
       else
          datetime_constructor%month = 1
       endif
       if (present(day)) then
          datetime_constructor%day = day
       else
          datetime_constructor%day = 1
       endif
       if (present(hour)) then
          datetime_constructor%hour = hour
       else
          datetime_constructor%hour = 0
       endif
       if (present(minute)) then
          datetime_constructor%minute = minute
       else
          datetime_constructor%minute = 0
       endif
       if (present(second)) then
          datetime_constructor%second = second
       else
          datetime_constructor%second = 0
       endif
       if (present(millisecond)) then
          datetime_constructor%millisecond = millisecond
       else
          datetime_constructor%millisecond = 0
       endif
       if (present(tz)) then
          datetime_constructor%tz = tz
       else
          datetime_constructor%tz = 0
       endif
Referenced by mod_datetime::datetime::operator().
datetime_minus_datetime()
pure elemental type(timedelta) function mod_datetime::datetime_minus_datetime (class(datetime), intent(in) d0, class(datetime), intent(in) d1) private
Definition at line 1234 of file suews_util_datetime.f95.
       !! Subtracts a `datetime` instance from another `datetime` instance,
       !! and returns a `timedelta` instance. Overloads the operator `-`.
       class(datetime), intent(in) :: d0 !! lhs `datetime` instance
       class(datetime), intent(in) :: d1 !! rhs `datetime` instance
       type(timedelta)            :: t
       real(kind=real64) :: daysdiff
       integer :: days, hours, minutes, seconds, milliseconds
       integer :: sign_
       daysdiff = date2num(d0) - date2num(d1)
       if (daysdiff < 0) then
          sign_ = -1
          daysdiff = abs(daysdiff)
       else
          sign_ = 1
       endif
       days = int(daysdiff)
       hours = int((daysdiff - days)*d2h)
       minutes = int((daysdiff - days - hours*h2d)*d2m)
       seconds = int((daysdiff - days - hours*h2d-minutes*m2d)*d2s)
       milliseconds = nint((daysdiff - days - hours*h2d-minutes*m2d &
                            -seconds*s2d)*d2s*1e3_real64)
       t = timedelta(sign_*days, sign_*hours, sign_*minutes, sign_*seconds, &
                     sign_*milliseconds)
References date2num().
Referenced by mod_datetime::datetime::operator().
datetime_minus_timedelta()
pure elemental type(datetime) function mod_datetime::datetime_minus_timedelta (class(datetime), intent(in) d0, class(timedelta), intent(in) t) private
Definition at line 1221 of file suews_util_datetime.f95.
       !! Subtracts a `timedelta` instance from a `datetime` instance and
       !! returns a new `datetime` instance. Overloads the operator `-`.
       class(datetime), intent(in) :: d0 !! `datetime` instance
       class(timedelta), intent(in) :: t  !! `timedelta` instance
       type(datetime)              :: d
       d = d0 + (-t)
Referenced by mod_datetime::datetime::operator().
datetime_plus_timedelta()
pure elemental type(datetime) function mod_datetime::datetime_plus_timedelta (class(datetime), intent(in) d0, class(timedelta), intent(in) t) private
Definition at line 1174 of file suews_util_datetime.f95.
       !! Adds a `timedelta` instance to a `datetime` instance, and returns a
       !! new `datetime` instance. Overloads the operator `+`.
       class(datetime), intent(in) :: d0 !! `datetime` instance
       class(timedelta), intent(in) :: t  !! `timedelta` instance
       type(datetime)              :: d
       integer :: milliseconds, seconds, minutes, hours, days
       d = datetime(year=d0%getYear(), &
                    month=d0%getMonth(), &
                    day=d0%getDay(), &
                    hour=d0%getHour(), &
                    minute=d0%getMinute(), &
                    second=d0%getSecond(), &
                    millisecond=d0%getMillisecond(), &
                    tz=d0%getTz())
       milliseconds = t%getMilliseconds()
       seconds = t%getSeconds()
       minutes = t%getMinutes()
       hours = t%getHours()
       days = t%getDays()
       if (milliseconds /= 0) call d%addMilliseconds(milliseconds)
       if (seconds /= 0) call d%addSeconds(seconds)
       if (minutes /= 0) call d%addMinutes(minutes)
       if (hours /= 0) call d%addHours(hours)
       if (days /= 0) call d%addDays(days)
Referenced by mod_datetime::datetime::operator().
datetimerange()
pure type(datetime) function, dimension(:), allocatable, public mod_datetime::datetimerange (type(datetime), intent(in) d0, type(datetime), intent(in) d1, type(timedelta), intent(in) t)
Definition at line 1429 of file suews_util_datetime.f95.
       !! Given start and end `datetime` instances `d0` and `d1` and time
       !! increment as `timedelta` instance `t`, returns an array of
       !! `datetime` instances. The number of elements is the number of whole
       !! time increments contained between datetimes `d0` and `d1`.
       type(datetime), intent(in) :: d0 !! start time
       type(datetime), intent(in) :: d1 !! end time
       type(timedelta), intent(in) :: t  !! time increment
       real(kind=real64) :: datenum0, datenum1, increment
       real(kind=real64) :: eps
       type(datetime), dimension(:), allocatable :: datetimeRange
       integer :: n, nm
       eps = 1e-10_real64
       datenum0 = date2num(d0)
       datenum1 = date2num(d1)
       increment = t%total_seconds()*s2d
       nm = floor((datenum1 - datenum0 + eps)/increment) + 1
       allocate (datetimerange(nm))
       do n = 1, nm
          datetimerange(n) = num2date(datenum0 + (n - 1)*increment)
       enddo
References date2num(), and num2date().
daysinmonth()
pure elemental integer function, public mod_datetime::daysinmonth (integer, intent(in) month, integer, intent(in) year)
Definition at line 1464 of file suews_util_datetime.f95.
       !! Given integer month and year, returns an integer number
       !! of days in that particular month.
       integer, intent(in) :: month !! month
       integer, intent(in) :: year  !! year
       integer, parameter, dimension(12) :: &
          days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
       if (month < 1 .or. month > 12) then
          ! Should raise an error and abort here, however we want to keep
          ! the pure and elemental attributes. Make sure this function is
          ! called with the month argument in range.
          daysinmonth = 0
          return
       endif
       if (month == 2 .and. isleapyear(year)) then
          daysinmonth = 29
       else
          daysinmonth = days(month)
       endif
References isleapyear().
Referenced by adddays(), isvalid(), num2date(), and yearday().
daysinyear()
pure elemental integer function, public mod_datetime::daysinyear (integer, intent(in) year)
Definition at line 1491 of file suews_util_datetime.f95.
       !! Returns the number of days in year.
       integer, intent(in) :: year !! year
       if (isleapyear(year)) then
          daysinyear = 366
       else
          daysinyear = 365
       endif
References isleapyear().
Referenced by date2num(), and num2date().
eq()
pure elemental logical function mod_datetime::eq (class(datetime), intent(in) d0, class(datetime), intent(in) d1) private
Definition at line 1353 of file suews_util_datetime.f95.
       !! `datetime` comparison operator that returns `.true.` if `d0` is
       !! equal to `d1` and `.false.` otherwise. Overloads the operator `==`.
       class(datetime), intent(in) :: d0 !! lhs `datetime` instance
       class(datetime), intent(in) :: d1 !! rhs `datetime` instance
       type(datetime) :: d0_utc, d1_utc
       ! Convert to UTC before making comparison
       d0_utc = d0%utc()
       d1_utc = d1%utc()
       eq = d0_utc%year == d1_utc%year .and. &
            d0_utc%month == d1_utc%month .and. &
            d0_utc%day == d1_utc%day .and. &
            d0_utc%hour == d1_utc%hour .and. &
            d0_utc%minute == d1_utc%minute .and. &
            d0_utc%second == d1_utc%second .and. &
            d0_utc%millisecond == d1_utc%millisecond
Referenced by mod_datetime::datetime::operator().
ge()
pure elemental logical function mod_datetime::ge (class(datetime), intent(in) d0, class(datetime), intent(in) d1) private
Definition at line 1389 of file suews_util_datetime.f95.
       !! `datetime` comparison operator. Returns `.true.` if `d0` is greater
       !! than or equal to `d1` and `.false.` otherwise. Overloads the
       !! operator `>=`.
       class(datetime), intent(in) :: d0 !! lhs `datetime` instance
       class(datetime), intent(in) :: d1 !! rhs `datetime` instance
       ge = d0 > d1 .or. d0 == d1
Referenced by mod_datetime::datetime::operator().
getday()
pure elemental integer function mod_datetime::getday (class(datetime), intent(in) self) private
Definition at line 640 of file suews_util_datetime.f95.
       !! Returns the year component
       class(datetime), intent(in) :: self !! `datetime` instance
       getday = self%day
gethour()
pure elemental integer function mod_datetime::gethour (class(datetime), intent(in) self) private
Definition at line 646 of file suews_util_datetime.f95.
       !! Returns the year component
       class(datetime), intent(in) :: self !! `datetime` instance
       gethour = self%hour
getmillisecond()
pure elemental integer function mod_datetime::getmillisecond (class(datetime), intent(in) self) private
Definition at line 664 of file suews_util_datetime.f95.
       !! Returns the year component
       class(datetime), intent(in) :: self !! `datetime` instance
       getmillisecond = self%millisecond
getminute()
pure elemental integer function mod_datetime::getminute (class(datetime), intent(in) self) private
Definition at line 652 of file suews_util_datetime.f95.
       !! Returns the year component
       class(datetime), intent(in) :: self !! `datetime` instance
       getminute = self%minute
getmonth()
pure elemental integer function mod_datetime::getmonth (class(datetime), intent(in) self) private
Definition at line 634 of file suews_util_datetime.f95.
       !! Returns the year component
       class(datetime), intent(in) :: self !! `datetime` instance
       getmonth = self%month
getsecond()
pure elemental integer function mod_datetime::getsecond (class(datetime), intent(in) self) private
Definition at line 658 of file suews_util_datetime.f95.
       !! Returns the year component
       class(datetime), intent(in) :: self !! `datetime` instance
       getsecond = self%second
gettz()
pure elemental real(kind=real64) function mod_datetime::gettz (class(datetime), intent(in) self) private
Definition at line 670 of file suews_util_datetime.f95.
       !! Returns the timezone offset component
       class(datetime), intent(in) :: self !! `datetime` instance
       gettz = self%tz
getyear()
pure elemental integer function mod_datetime::getyear (class(datetime), intent(in) self) private
Definition at line 628 of file suews_util_datetime.f95.
       !! Returns the year component
       class(datetime), intent(in) :: self !! `datetime` instance
       getyear = self%year
gt()
pure elemental logical function mod_datetime::gt (class(datetime), intent(in) d0, class(datetime), intent(in) d1) private
Definition at line 1268 of file suews_util_datetime.f95.
       !! `datetime` comparison operator that eturns `.true.` if `d0` is
       !! greater than `d1` and `.false.` otherwise. Overloads the
       !! operator `>`.
       class(datetime), intent(in) :: d0 !! lhs `datetime` instance
       class(datetime), intent(in) :: d1 !! rhs `datetime` instance
       type(datetime) :: d0_utc, d1_utc
       ! Convert to UTC before making comparison
       d0_utc = d0%utc()
       d1_utc = d1%utc()
       ! Year comparison block
       if (d0_utc%year > d1_utc%year) then
          gt = .true.
       elseif (d0_utc%year < d1_utc%year) then
          gt = .false.
       else
          ! Month comparison block
          if (d0_utc%month > d1_utc%month) then
             gt = .true.
          elseif (d0_utc%month < d1_utc%month) then
             gt = .false.
          else
             ! Day comparison block
             if (d0_utc%day > d1_utc%day) then
                gt = .true.
             elseif (d0_utc%day < d1_utc%day) then
                gt = .false.
             else
                ! Hour comparison block
                if (d0_utc%hour > d1_utc%hour) then
                   gt = .true.
                elseif (d0_utc%hour < d1_utc%hour) then
                   gt = .false.
                else
                   ! Minute comparison block
                   if (d0_utc%minute > d1_utc%minute) then
                      gt = .true.
                   elseif (d0_utc%minute < d1_utc%minute) then
                      gt = .false.
                   else
                      ! Second comparison block
                      if (d0_utc%second > d1_utc%second) then
                         gt = .true.
                      elseif (d0_utc%second < d1_utc%second) then
                         gt = .false.
                      else
                         ! Millisecond comparison block
                         if (d0_utc%millisecond > d1_utc%millisecond) then
                            gt = .true.
                         else
                            gt = .false.
                         endif
                      endif
                   endif
                endif
             endif
          endif
       endif
Referenced by mod_datetime::datetime::operator().
int2str()
pure character(len=length) function mod_datetime::int2str (integer, intent(in) i, integer, intent(in) length) private
Definition at line 1637 of file suews_util_datetime.f95.
       !! Converts an integer `i` into a character string of requested length,
       !! pre-pending zeros if necessary.
       integer, intent(in) :: i      !! integer to convert to string
       integer, intent(in) :: length !! desired length of string
       character(len=length) :: int2str
       character(len=2)      :: string
       write (unit=string, fmt='(I2)') length
       write (unit=int2str, fmt='(I'//string//'.'//string//')') i
Referenced by isoformat().
isleapyear()
pure elemental logical function, public mod_datetime::isleapyear (integer, intent(in) year)
Definition at line 1418 of file suews_util_datetime.f95.
       !! Returns `.true.` if year is leap year and `.false.` otherwise.
       integer, intent(in) :: year !! year
       isleapyear = (mod(year, 4) == 0 .and. .not. mod(year, 100) == 0) &
                    .or. (mod(year, 400) == 0)
Referenced by daysinmonth(), and daysinyear().
isocalendar()
integer function, dimension(3) mod_datetime::isocalendar (class(datetime), intent(in) self) private
Definition at line 1032 of file suews_util_datetime.f95.
       !! Returns an array of 3 integers, year, week number, and week day,
       !! as defined by ISO 8601 week date. Essentially a wrapper around C
       !! `strftime` function.
       class(datetime), intent(in) :: self !! `datetime` instance
       integer, dimension(3) :: isocalendar
       integer              :: year, week, wday
       integer              :: rc
       character(len=20)    :: string
       rc = c_strftime(string, len(string), '%G %V %u'//c_null_char, &
                       self%tm())
       read (unit=string(1:4), fmt='(I4)') year
       read (unit=string(6:7), fmt='(I2)') week
       read (unit=string(9:9), fmt='(I1)') wday
       isocalendar = [year, week, wday]
isoformat()
pure elemental character(len=23) function mod_datetime::isoformat (class(datetime), intent(in) self, character(len=1), intent(in), optional sep) private
Definition at line 809 of file suews_util_datetime.f95.
       !! Returns character string with time in ISO 8601 format.
       class(datetime), intent(in)          :: self !! `datetime instance`
       character(len=1), intent(in), optional :: sep
       !! separator character, 'T' is default
       character(len=1) :: separator
       if (present(sep)) then
          separator = sep
       else
          separator = 'T'
       endif
       ! TODO below is a bit cumbersome and was implemented
       ! at a time before the interface to strftime. Now we
       ! could do something like:
       !
       ! isoformat = self % strftime('%Y-%m-%d'//separator//'%H:%M:%S')
       !
       isoformat = int2str(self%year, 4)//'-'// &
                   int2str(self%month, 2)//'-'// &
                   int2str(self%day, 2)//separator// &
                   int2str(self%hour, 2)//':'// &
                   int2str(self%minute, 2)//':'// &
                   int2str(self%second, 2)//'.'// &
                   int2str(self%millisecond, 3)
References int2str().
isoweekday()
pure elemental integer function mod_datetime::isoweekday (class(datetime), intent(in) self) private
Definition at line 953 of file suews_util_datetime.f95.
       !! Returns the day of the week per ISO 8601 returned from weekday().
       !! Returned value is an integer scalar in the range [1-7], such that:
       !!
       !! 1: Monday
       !! 2: Tuesday
       !! 3: Wednesday
       !! 4: Thursday
       !! 5: Friday
       !! 6: Saturday
       !! 7: Sunday
       class(datetime), intent(in) :: self !! `datetime` instance
       isoweekday = self%weekday()
       if (isoweekday == 0) then
          isoweekday = 7
       end if
isoweekdaylong()
pure elemental character(len=9) function mod_datetime::isoweekdaylong (class(datetime), intent(in) self) private
Definition at line 990 of file suews_util_datetime.f95.
       !! Returns the full name of the day of the week for ISO 8601
       !! ordered weekdays.
       class(datetime), intent(in) :: self !! `datetime` instance
       character(len=9), parameter, dimension(7) :: &
          days = ['Monday   ', 'Tuesday  ', 'Wednesday', 'Thursday ', &
                  'Friday   ', 'Saturday ', 'Sunday   ']
       isoweekdaylong = days(self%isoweekday())
isoweekdayshort()
pure elemental character(len=3) function mod_datetime::isoweekdayshort (class(datetime), intent(in) self) private
Definition at line 1018 of file suews_util_datetime.f95.
       !! Returns the short (3-letter) name of the day of the week
       !! based on ISO 8601 ordering.
       class(datetime), intent(in) :: self !! `datetime` instance
       character(len=3), parameter, dimension(7) :: &
          days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
       isoweekdayshort = days(self%isoweekday())
isvalid()
pure elemental logical function mod_datetime::isvalid (class(datetime), intent(in) self) private
Definition at line 841 of file suews_util_datetime.f95.
       !! Checks whether the `datetime` instance has valid component values.
       !! Returns `.true.` if the `datetime` instance is valid, and `.false.`
       !! otherwise.
       class(datetime), intent(in) :: self !! `datetime` instance
       ! assume valid
       isvalid = .true.
       if (self%year < 1) then
          isvalid = .false.
          return
       endif
       if (self%month < 1 .or. self%month > 12) then
          isvalid = .false.
          return
       endif
       if (self%day < 1 .or. &
           self%day > daysinmonth(self%month, self%year)) then
          isvalid = .false.
          return
       endif
       if (self%hour < 0 .or. self%hour > 23) then
          isvalid = .false.
          return
       endif
       if (self%minute < 0 .or. self%minute > 59) then
          isvalid = .false.
          return
       endif
       if (self%second < 0 .or. self%second > 59) then
          isvalid = .false.
          return
       endif
       if (self%millisecond < 0 .or. self%millisecond > 999) then
          isvalid = .false.
          return
       endif
References daysinmonth().
le()
pure elemental logical function mod_datetime::le (class(datetime), intent(in) d0, class(datetime), intent(in) d1) private
Definition at line 1402 of file suews_util_datetime.f95.
       !! `datetime` comparison operator. Returns `.true.` if `d0` is less
       !! than or equal to `d1`, and `.false.` otherwise. Overloads the
       !! operator `<=`.
       class(datetime), intent(in) :: d0 !! lhs `datetime` instance
       class(datetime), intent(in) :: d1 !! rhs `datetime` instance
       le = d1 > d0 .or. d0 == d1
Referenced by mod_datetime::datetime::operator().
lt()
pure elemental logical function mod_datetime::lt (class(datetime), intent(in) d0, class(datetime), intent(in) d1) private
Definition at line 1341 of file suews_util_datetime.f95.
       !! `datetime` comparison operator that returns `.true.` if `d0` is
       !! less than `d1` and `.false.` otherwise. Overloads the operator `<`.
       class(datetime), intent(in) :: d0 !! lhs `datetime` instance
       class(datetime), intent(in) :: d1 !! rhs `datetime` instance
       lt = d1 > d0
Referenced by mod_datetime::datetime::operator().
neq()
pure elemental logical function mod_datetime::neq (class(datetime), intent(in) d0, class(datetime), intent(in) d1) private
Definition at line 1377 of file suews_util_datetime.f95.
       !! `datetime` comparison operator that eturns `.true.` if `d0` is
       !! not equal to `d1` and `.false.` otherwise. Overloads the operator `/=`.
       class(datetime), intent(in) :: d0 !! lhs `datetime` instance
       class(datetime), intent(in) :: d1 !! rhs `datetime` instance
       neq = .not. d0 == d1
Referenced by mod_datetime::datetime::operator().
now()
type(datetime) function mod_datetime::now () private
Definition at line 890 of file suews_util_datetime.f95.
       !! Returns a `datetime` instance with current time.
       !! No input arguments.
       character(len=5)     :: zone
       integer, dimension(8) :: values
       integer :: hour, minute
       ! Obtain local machine time zone information
       call date_and_time(zone=zone, values=values)
       read (unit=zone(1:3), fmt='(I3)') hour
       read (unit=zone(4:5), fmt='(I2)') minute
       now = datetime(year=values(1), &
                      month=values(2), &
                      day=values(3), &
                      hour=values(5), &
                      minute=values(6), &
                      second=values(7), &
                      millisecond=values(8))
       now%tz = hour + minute*m2h
num2date()
pure elemental type(datetime) function, public mod_datetime::num2date (real(kind=real64), intent(in) num)
Definition at line 1537 of file suews_util_datetime.f95.
       !! Given number of days since `0001-01-01 00:00:00`, returns a
       !! correspoding `datetime` instance.
       real(kind=real64), intent(in) :: num
       !! number of days since `0001-01-01 00:00:00`
       integer :: year, month, day, hour, minute, second, millisecond
       real(kind=real64) :: days, totseconds
       ! num must be positive:
       if (num < 0) then
          num2date = datetime(1)
          return
       endif
       days = num
       year = 1
       do
          if (int(days) <= daysinyear(year)) exit
          days = days - daysinyear(year)
          year = year + 1
       enddo
       month = 1
       do
          if (int(days) <= daysinmonth(month, year)) exit
          days = days - daysinmonth(month, year)
          month = month + 1
       enddo
       day = int(days)
       totseconds = (days - day)*d2s
       hour = int(totseconds*s2h)
       minute = int((totseconds - hour*h2s)*s2m)
       second = int(totseconds - hour*h2s - minute*m2s)
       millisecond = nint((totseconds - int(totseconds))*1e3_real64)
       num2date = datetime(year, month, day, hour, minute, second, millisecond, tz=zero)
       ! Handle a special case caused by floating-point arithmethic:
       if (num2date%millisecond == 1000) then
          num2date%millisecond = 0
          call num2date%addSeconds(1)
       endif
       if (num2date%second == 60) then
          num2date%second = 0
          call num2date%addMinutes(1)
       endif
       if (num2date%minute == 60) then
          num2date%minute = 0
          call num2date%addHours(1)
       endif
       if (num2date%hour == 60) then
          num2date%hour = 0
          call num2date%addDays(1)
       endif
References daysinmonth(), and daysinyear().
Referenced by datetimerange().
secondssinceepoch()
integer function mod_datetime::secondssinceepoch (class(datetime), intent(in) self) private
Definition at line 1056 of file suews_util_datetime.f95.
       !! Returns an integer number of seconds since the UNIX Epoch,
       !! `1970-01-01 00:00:00`. Note that this is a wrapper around C's
       !! `strftime('%s')`, so the number of seconds will reflect the time
       !! zone of the local machine on which the function is being called.
       class(datetime), intent(in) :: self !! `datetime` instance
       character(len=11) :: string
       string = self%strftime('%s')
       read (unit=string, fmt='(I10)') secondssinceepoch
strftime()
character(len=:) function, allocatable mod_datetime::strftime (class(datetime), intent(in) self, character(len=*), intent(in) format) private
Definition at line 1072 of file suews_util_datetime.f95.
       !! Wrapper around C/C++ `strftime` function.
       class(datetime), intent(in)  :: self   !! `datetime` instance
       character(len=*), intent(in)  :: format !! format string
       character(len=:), allocatable :: strftime
       integer                  :: n, rc
       character(len=MAXSTRLEN) :: resultString
       resultstring = ""
       rc = c_strftime(resultstring, maxstrlen, trim(format)//c_null_char, &
                       self%tm())
       strftime = trim(resultstring)
       n = len(strftime)
       strftime = strftime(1:n - 1)
strptime()
type(datetime) function, public mod_datetime::strptime (character(len=*), intent(in) str, character(len=*), intent(in) format)
Definition at line 1600 of file suews_util_datetime.f95.
       !! A wrapper function around C/C++ strptime function.
       !! Returns a `datetime` instance.
       character(len=*), intent(in) :: str    !! time string
       character(len=*), intent(in) :: format !! time format
       integer         :: rc
       type(tm_struct) :: tm
       rc = c_strptime(trim(str)//c_null_char, trim(format)//c_null_char, tm)
       strptime = tm2date(tm)
References tm(), and tm2date().
timedelta_plus_datetime()
pure elemental type(datetime) function mod_datetime::timedelta_plus_datetime (class(timedelta), intent(in) t, class(datetime), intent(in) d0) private
Definition at line 1208 of file suews_util_datetime.f95.
       !! Adds a `timedelta` instance to a `datetime` instance, and returns a
       !! new `datetime` instance. Overloads the operator `+`.
       class(timedelta), intent(in) :: t  !! `timedelta` instance
       class(datetime), intent(in) :: d0 !! `datetime` instance
       type(datetime)              :: d
       d = d0 + t
Referenced by mod_datetime::datetime::operator().
tm()
pure elemental type(tm_struct) function mod_datetime::tm (class(datetime), intent(in) self) private
Definition at line 1093 of file suews_util_datetime.f95.
       !! Returns a `tm_struct` instance of the current `datetime`.
       class(datetime), intent(in) :: self !! `datetime` instance
       tm%tm_sec = self%second
       tm%tm_min = self%minute
       tm%tm_hour = self%hour
       tm%tm_mday = self%day
       tm%tm_mon = self%month - 1
       tm%tm_year = self%year - 1900
       tm%tm_wday = self%weekday()
       tm%tm_yday = self%yearday() - 1
       tm%tm_isdst = -1
Referenced by strptime().
tm2date()
pure elemental type(datetime) function, public mod_datetime::tm2date (type(tm_struct), intent(in) ctime)
Definition at line 1616 of file suews_util_datetime.f95.
       !! Given a `tm_struct` instance, returns a corresponding `datetime`
       !! instance.
       type(tm_struct), intent(in) :: ctime !! C-style time struct
       tm2date%millisecond = 0
       tm2date%second = ctime%tm_sec
       tm2date%minute = ctime%tm_min
       tm2date%hour = ctime%tm_hour
       tm2date%day = ctime%tm_mday
       tm2date%month = ctime%tm_mon + 1
       tm2date%year = ctime%tm_year + 1900
       tm2date%tz = 0
Referenced by strptime().
tzoffset()
pure elemental character(len=5) function mod_datetime::tzoffset (class(datetime), intent(in) self) private
Definition at line 1111 of file suews_util_datetime.f95.
       !! Returns a character string with timezone offset in hours from UTC,
       !! in format +/-[hh][mm].
       class(datetime), intent(in) :: self !! `datetime` instance
       integer :: hours, minutes
       if (self%tz < 0) then
          tzoffset(1:1) = '-'
       else
          tzoffset(1:1) = '+'
       endif
       hours = int(abs(self%tz))
       minutes = nint((abs(self%tz) - hours)*60)
       if (minutes == 60) then
          minutes = 0
          hours = hours + 1
       endif
       write (unit=tzoffset(2:5), fmt='(2I2.2)') hours, minutes
utc()
pure elemental type(datetime) function mod_datetime::utc (class(datetime), intent(in) self) private
Definition at line 1138 of file suews_util_datetime.f95.
       !! Returns the `datetime` instance at Coordinated Universal Time (UTC).
       class(datetime), intent(in) :: self !! `datetime` instance
       integer :: hours, minutes, sgn
       hours = int(abs(self%tz))
       minutes = nint((abs(self%tz) - hours)*60)
       sgn = int(sign(one, self%tz))
       utc = self - timedelta(hours=sgn*hours, minutes=sgn*minutes)
       utc%tz = 0
weekday()
pure elemental integer function mod_datetime::weekday (class(datetime), intent(in) self) private
Definition at line 918 of file suews_util_datetime.f95.
       !! Returns the day of the week calculated using Zeller's congruence.
       !! Returned value is an integer scalar in the range [0-6], such that:
       !!
       !! 0: Sunday
       !! 1: Monday
       !! 2: Tuesday
       !! 3: Wednesday
       !! 4: Thursday
       !! 5: Friday
       !! 6: Saturday
       class(datetime), intent(in) :: self !! `datetime` instance
       integer :: year, month
       integer :: j, k
       year = self%year
       month = self%month
       if (month <= 2) then
          month = month + 12
          year = year - 1
       endif
       j = year/100
       k = mod(year, 100)
       weekday = mod(self%day + ((month + 1)*26)/10 + k + k/4 + j/4 + 5*j, 7) - 1
       if (weekday < 0) weekday = 6
weekdaylong()
pure elemental character(len=9) function mod_datetime::weekdaylong (class(datetime), intent(in) self) private
Definition at line 976 of file suews_util_datetime.f95.
       !! Returns the full name of the day of the week.
       class(datetime), intent(in) :: self !! `datetime` instance
       character(len=9), parameter, dimension(7) :: &
          days = ['Sunday   ', 'Monday   ', 'Tuesday  ', 'Wednesday', &
                  'Thursday ', 'Friday   ', 'Saturday ']
       weekdaylong = days(self%weekday() + 1)
weekdayshort()
pure elemental character(len=3) function mod_datetime::weekdayshort (class(datetime), intent(in) self) private
Definition at line 1005 of file suews_util_datetime.f95.
       !! Returns the short (3-letter) name of the day of the week.
       class(datetime), intent(in) :: self !! `datetime` instance
       character(len=3), parameter, dimension(7) :: &
          days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
       weekdayshort = days(self%weekday() + 1)
yearday()
pure elemental integer function mod_datetime::yearday (class(datetime), intent(in) self) private
Definition at line 1155 of file suews_util_datetime.f95.
       !! Returns the integer day of the year (ordinal date).
       class(datetime), intent(in) :: self !! `datetime` instance
       integer :: month
       yearday = 0
       do month = 1, self%month - 1
          yearday = yearday + daysinmonth(month, self%year)
       enddo
       yearday = yearday + self%day
References daysinmonth().