SUEWS: precision Module Reference
precision Module Reference
Variables
integer, parameter kr4 = selected_real_kind(6, 37)
integer, parameter kr8 = selected_real_kind(15, 307)
integer, parameter ki4 = selected_int_kind(9)
integer, parameter ki8 = selected_int_kind(18)
integer, parameter kc4 = kr4
integer, parameter kc8 = kr8
Variable Documentation
kc4
integer, parameter precision::kc4 = kr4
Definition at line 17 of file suews_util_stringmod.f95.
    integer, parameter :: kc4 = kr4                            ! single precision complex
kc8
integer, parameter precision::kc8 = kr8
Definition at line 18 of file suews_util_stringmod.f95.
    integer, parameter :: kc8 = kr8                            ! double precision complex
ki4
integer, parameter precision::ki4 = selected_int_kind(9)
Definition at line 12 of file suews_util_stringmod.f95.
    integer, parameter :: ki4 = selected_int_kind(9)           ! single precision integer
Referenced by strings::value_si().
ki8
integer, parameter precision::ki8 = selected_int_kind(18)
Definition at line 13 of file suews_util_stringmod.f95.
    integer, parameter :: ki8 = selected_int_kind(18)          ! double precision integer
Referenced by strings::value_di().
kr4
integer, parameter precision::kr4 = selected_real_kind(6, 37)
Definition at line 7 of file suews_util_stringmod.f95.
    integer, parameter :: kr4 = selected_real_kind(6, 37)       ! single precision real
Referenced by strings::value_sr().
kr8
integer, parameter precision::kr8 = selected_real_kind(15, 307)
Definition at line 8 of file suews_util_stringmod.f95.
    integer, parameter :: kr8 = selected_real_kind(15, 307)     ! double precision real
Referenced by strings::value_di().