SUEWS: narp_module Module Reference
narp_module Module Reference
Functions/Subroutines
subroutine radmethod (NetRadiationMethod, snowUse, NetRadiationMethodX, AlbedoChoice, ldown_option)
subroutine narp (nsurf, sfr, snowFrac, alb, emis, IceFrac, NARP_TRANS_SITE, NARP_EMIS_SNOW, DTIME, ZENITH_deg, kdown, Temp_C, RH, Press_hPa, qn1_obs, SnowAlb, AlbedoChoice, ldown_option, NetRadiationMethodX, DiagQN, QSTARall, QSTAR_SF, QSTAR_S, kclear, KUPall, LDOWN, LUPall, fcld, TSURFall, qn1_ind_snow, kup_ind_snow, Tsurf_ind_snow, Tsurf_ind)
subroutine narp_cal_sunposition (year, idectime, UTC, locationlatitude, locationlongitude, locationaltitude, sunazimuth, sunzenith)
subroutine julian_calculation (year, month, day, hour, min, sec, UTC, juliancentury, julianday, julianephemeris_century, julianephemeris_day, julianephemeris_millenium)
subroutine earth_heliocentric_position_calculation (julianephemeris_millenium, earth_heliocentric_positionlatitude, earth_heliocentric_positionlongitude, earth_heliocentric_positionradius)
subroutine sun_geocentric_position_calculation (earth_heliocentric_positionlongitude, earth_heliocentric_positionlatitude, sun_geocentric_positionlatitude, sun_geocentric_positionlongitude)
subroutine nutation_calculation (julianephemeris_century, nutationlongitude, nutationobliquity)
subroutine corr_obliquity_calculation (julianephemeris_millenium, nutationobliquity, corr_obliquity)
subroutine abberation_correction_calculation (earth_heliocentric_positionradius, aberration_correction)
subroutine apparent_sun_longitude_calculation (sun_geocentric_positionlongitude, nutationlongitude, aberration_correction, apparent_sun_longitude)
subroutine apparent_stime_at_greenwich_calculation (julianday, juliancentury, nutationlongitude, corr_obliquity, apparent_stime_at_greenwich)
subroutine sun_rigth_ascension_calculation (apparent_sun_longitude, corr_obliquity, sun_geocentric_positionlatitude, sun_rigth_ascension)
subroutine sun_geocentric_declination_calculation (apparent_sun_longitude, corr_obliquity, sun_geocentric_positionlatitude, sun_geocentric_declination)
subroutine observer_local_hour_calculation (apparent_stime_at_greenwich, locationlongitude, sun_rigth_ascension, observer_local_hour)
subroutine topocentric_sun_position_calculate (topocentric_sun_positionrigth_ascension, topocentric_sun_positionrigth_ascension_parallax, topocentric_sun_positiondeclination, locationaltitude, locationlatitude, observer_local_hour, sun_rigth_ascension, sun_geocentric_declination, earth_heliocentric_positionradius)
subroutine topocentric_local_hour_calculate (observer_local_hour, topocentric_sun_positionrigth_ascension_parallax, topocentric_local_hour)
subroutine sun_topocentric_zenith_angle_calculate (locationlatitude, topocentric_sun_positiondeclination, topocentric_local_hour, sunazimuth, sunzenith)
real(kind(1d0)) function set_to_range (var)
real(kind(1d0)) function dewpoint (Temp_C, rh)
real(kind(1d0)) function prata_emis (Temp_K, EA_hPa)
real(kind(1d0)) function emis_cloud (EMIS_A, FCLD)
real(kind(1d0)) function emis_cloud_sq (EMIS_A, FCLD)
real(kind(1d0)) function cloud_fraction (KDOWN, KCLEAR)
real(kind(1d0)) function wc_fraction (RH, Temp)
real(kind(1d0)) function isurface (doy, zenith)
real(kind(1d0)) function solar_esdist (doy)
real(kind(1d0)) function, dimension(365) smithlambda (lat)
real(kind(1d0)) function transmissivity (Press_hPa, Temp_C_dew, G, zenith)
Function/Subroutine Documentation
abberation_correction_calculation()
subroutine narp_module::abberation_correction_calculation (real(kind(1d0)), intent(in) earth_heliocentric_positionradius, real(kind(1d0)), intent(out) aberration_correction)
Definition at line 951 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(out) :: aberration_correction
       REAL(KIND(1D0)), INTENT(in) :: earth_heliocentric_positionradius
       ! This function compute the aberration_correction, as a function of the
       ! earth-sun distance.
       aberration_correction = -20.4898/(3600*earth_heliocentric_positionradius)
Referenced by narp_cal_sunposition().
apparent_stime_at_greenwich_calculation()
subroutine narp_module::apparent_stime_at_greenwich_calculation (real(kind(1d0)), intent(in) julianday, real(kind(1d0)), intent(in) juliancentury, real(kind(1d0)), intent(in) nutationlongitude, real(kind(1d0)), intent(in) corr_obliquity, real(kind(1d0)), intent(out) apparent_stime_at_greenwich)
Definition at line 980 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(out) :: apparent_stime_at_greenwich
       REAL(KIND(1D0)), INTENT(in) :: corr_obliquity
       REAL(KIND(1D0)), INTENT(in) :: julianday
       REAL(KIND(1D0)), INTENT(in) :: juliancentury
       REAL(KIND(1D0)), INTENT(in) :: nutationlongitude
       REAL(KIND(1D0)) :: JC
       REAL(KIND(1D0)) :: JD
       REAL(KIND(1D0)) :: mean_stime
       REAL(KIND(1D0)), PARAMETER       :: pi = 3.14159265358979d+0
       ! This function compute the apparent sideral time at Greenwich.
       jd = julianday
       jc = juliancentury
       ! Mean sideral time, in degrees
       mean_stime = 280.46061837d+0 + (360.98564736629d+0*(jd - 2451545.0d+0)) + (0.000387933d+0*jc**2) - (jc**3/38710000.0d+0)
       ! Limit the range to [0-360];
       mean_stime = set_to_range(mean_stime)
       apparent_stime_at_greenwich = mean_stime + (nutationlongitude*cos(corr_obliquity*pi/180))
References set_to_range().
Referenced by narp_cal_sunposition().
apparent_sun_longitude_calculation()
subroutine narp_module::apparent_sun_longitude_calculation (real(kind(1d0)), intent(in) sun_geocentric_positionlongitude, real(kind(1d0)), intent(in) nutationlongitude, real(kind(1d0)), intent(in) aberration_correction, real(kind(1d0)), intent(out) apparent_sun_longitude)
Definition at line 965 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: aberration_correction
       REAL(KIND(1D0)), INTENT(out) :: apparent_sun_longitude
       REAL(KIND(1D0)), INTENT(in) :: nutationlongitude
       REAL(KIND(1D0)), INTENT(in) :: sun_geocentric_positionlongitude
       ! This function compute the sun apparent longitude
       apparent_sun_longitude = sun_geocentric_positionlongitude + nutationlongitude + aberration_correction
Referenced by narp_cal_sunposition().
cloud_fraction()
real(kind(1d0)) function narp_module::cloud_fraction (real(kind(1d0)) KDOWN, real(kind(1d0)) KCLEAR)
Definition at line 1241 of file suews_phys_narp.f95.
       REAL(KIND(1d0))::KDOWN, KCLEAR, FCLD
       fcld = 1.-kdown/kclear
       IF (fcld > 1.) fcld = 1.
       IF (fcld < 0.) fcld = 0.
Referenced by narp().
corr_obliquity_calculation()
subroutine narp_module::corr_obliquity_calculation (real(kind(1d0)), intent(in) julianephemeris_millenium, real(kind(1d0)), intent(in) nutationobliquity, real(kind(1d0)), intent(out) corr_obliquity)
Definition at line 928 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(out) :: corr_obliquity
       REAL(KIND(1D0)), INTENT(in) :: julianephemeris_millenium
       REAL(KIND(1D0)), INTENT(in) :: nutationobliquity
       REAL(KIND(1D0)) :: mean_obliquity
       REAL(KIND(1D0)), DIMENSION(11) :: p
       REAL(KIND(1D0)) :: U
       ! This function compute the true obliquity of the ecliptic.
       p = (/2.45, 5.79, 27.87, 7.12, -39.05, -249.67, -51.38, 1999.25, -1.55, -4680.93, 84381.448/)
       ! mean_obliquity = polyval(p, julian.ephemeris_millenium/10);
       u = julianephemeris_millenium/10
       mean_obliquity =&
            &p(1)*u**10 + p(2)*u**9 + p(3)*u**8 + p(4)*u**7 + p(5)*u**6 + p(6)*u**5 + p(7)*u**4 + &
            &p(8)*u**3 + p(9)*u**2 + p(10)*u + p(11)
       corr_obliquity = (mean_obliquity/3600) + nutationobliquity
Referenced by narp_cal_sunposition().
dewpoint()
real(kind(1d0)) function narp_module::dewpoint (real(kind(1d0)) Temp_C, real(kind(1d0)) rh)
Definition at line 1204 of file suews_phys_narp.f95.
       ! ea = vapor pressure (hPa)
       ! td = dewpoint (oC)
       ! calculates dewpoint in degC from
       ! http://www.atd.ucar.edu/weather_fl/dewpoint.html
       ! dewpoint = (237.3 * ln(e_vp/6.1078)) / (17.27 - (ln(e_vp/6.1078)))
       REAL(KIND(1d0))::rh, td, Temp_C, g
       !http://en.wikipedia.org/wiki/Dew_point
       g = ((17.27*temp_c)/(237.7 + temp_c)) + log(rh/100)
       td = (237.7*g)/(17.27 - g)
       !td = (237.3 * LOG(ea_hPa/6.1078)) / (17.27 - (LOG(ea_hPa/6.1078)))
Referenced by narp().
earth_heliocentric_position_calculation()
subroutine narp_module::earth_heliocentric_position_calculation (real(kind(1d0)) julianephemeris_millenium, real(kind(1d0)) earth_heliocentric_positionlatitude, real(kind(1d0)) earth_heliocentric_positionlongitude, real(kind(1d0)) earth_heliocentric_positionradius)
Definition at line 605 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)) :: julianephemeris_millenium
       REAL(KIND(1D0)), DIMENSION(64) :: A0
       REAL(KIND(1D0)), DIMENSION(34) :: A1
       REAL(KIND(1D0)), DIMENSION(20) :: A2
       REAL(KIND(1D0)), DIMENSION(7) :: A3
       REAL(KIND(1D0)), DIMENSION(3) :: A4
       REAL(KIND(1D0)) :: A5
       REAL(KIND(1D0)), DIMENSION(64) :: B0
       REAL(KIND(1D0)), DIMENSION(34) :: B1
       REAL(KIND(1D0)), DIMENSION(20) :: B2
       REAL(KIND(1D0)), DIMENSION(7) :: B3
       REAL(KIND(1D0)), DIMENSION(3) :: B4
       REAL(KIND(1D0)) :: B5
       REAL(KIND(1D0)), DIMENSION(64) :: C0
       REAL(KIND(1D0)), DIMENSION(34) :: C1
       REAL(KIND(1D0)), DIMENSION(20) :: C2
       REAL(KIND(1D0)), DIMENSION(7) :: C3
       REAL(KIND(1D0)), DIMENSION(3) :: C4
       REAL(KIND(1D0)) :: C5
       REAL(KIND(1D0)), DIMENSION(40) :: A0j
       REAL(KIND(1D0)), DIMENSION(10) :: A1j
       REAL(KIND(1D0)), DIMENSION(6) :: A2j
       REAL(KIND(1D0)), DIMENSION(2) :: A3j
       REAL(KIND(1D0)) :: A4j
       REAL(KIND(1D0)), DIMENSION(40) :: B0j
       REAL(KIND(1D0)), DIMENSION(10) :: B1j
       REAL(KIND(1D0)), DIMENSION(6) :: B2j
       REAL(KIND(1D0)), DIMENSION(2) :: B3j
       REAL(KIND(1D0)) :: B4j
       REAL(KIND(1D0)), DIMENSION(40) :: C0j
       REAL(KIND(1D0)), DIMENSION(10) :: C1j
       REAL(KIND(1D0)), DIMENSION(6) :: C2j
       REAL(KIND(1D0)), DIMENSION(2) :: C3j
       REAL(KIND(1D0)) :: C4j
       REAL(KIND(1D0)), DIMENSION(5) ::  A0i
       REAL(KIND(1D0)), DIMENSION(5) ::  B0i
       REAL(KIND(1D0)), DIMENSION(5) ::  C0i
       REAL(KIND(1D0)), DIMENSION(2) ::  A1i
       REAL(KIND(1D0)), DIMENSION(2) ::  B1i
       REAL(KIND(1D0)), DIMENSION(2) ::   C1i
       REAL(KIND(1D0)) :: earth_heliocentric_positionlatitude
       REAL(KIND(1D0)) :: earth_heliocentric_positionlongitude
       REAL(KIND(1D0)) :: earth_heliocentric_positionradius
       REAL(KIND(1D0)) :: JME
       REAL(KIND(1D0)) :: L0
       !REAL(KIND(1D0)) :: L0_terms      !>
       REAL(KIND(1D0)) :: L1
       !REAL(KIND(1D0)) :: L1_terms      !>
       REAL(KIND(1D0)) :: L2
       !REAL(KIND(1D0)) :: L2_terms      !>
       REAL(KIND(1D0)) :: L3
       !REAL(KIND(1D0)) :: L3_terms      !>
       REAL(KIND(1D0)) :: L4
       !REAL(KIND(1D0)) :: L4_terms      !>
       REAL(KIND(1D0)) :: L5
       !REAL(KIND(1D0)), dimension(3) :: L5_terms      !>
       !REAL(KIND(1D0)) :: R0_terms      !>
       !REAL(KIND(1D0)) :: R1_terms      !>
       !REAL(KIND(1D0)) :: R2_terms      !>
       !REAL(KIND(1D0)) :: R3_terms      !>
       !REAL(KIND(1D0)), dimension(3) :: R4_terms      !>
       REAL(KIND(1D0)), PARAMETER       :: pi = 3.141592653589793d+0
       ! This function compute the earth position relative to the sun, using
       ! tabulated values.
       a0 = (/175347046, 3341656, 34894, 3497, 3418, 3136, 2676, 2343, 1324, 1273, 1199, 990, 902, 857, 780, 753, 505,&
            &492, 357, 317, 284, 271, 243, 206, 205, 202, 156, 132, 126, 115, 103, 102, 102, 99, 98, 86, 85, 85, 80, 79, 71,&
            &74, 74, 70, 62, 61, 57, 56, 56, 52, 52, 51, 49, 41, 41, 39, 37, 37, 36, 36, 33, 30, 30, 25/)
       b0 = (/0., 4.669256800, 4.626100, 2.744100, 2.828900, 3.627700, 4.418100, 6.135200, 0.7425000, 2.037100,&
            &1.109600, 5.233000, 2.045000, 3.508000, 1.179000, 2.533000, 4.583000, 4.205000, 2.92, 5.849000,&
            &1.899000, 0.315, 0.345, 4.806000, 1.869000, 2.445800, 0.833, 3.411000, 1.083000, 0.645, 0.636, 0.976,&
            &4.267000, 6.21, 0.68, 5.98, 1.3, 3.67, 1.81, 3.04, 1.76, 3.5, 4.68, 0.83, 3.98, 1.82, 2.78, 4.39, 3.47, 0.19,&
            &1.33, 0.28, 0.49, 5.37, 2.4, 6.17, 6.04, 2.57, 1.71, 1.78, 0.59, 0.44, 2.74, 3.16/)
       c0 = (/0., 6283.075850, 12566.15170, 5753.384900, 3.523100, 77713.77150, 7860.419400, 3930.209700,&
            &11506.76980, 529.6910, 1577.343500, 5884.927, 26.29800, 398.1490, 5223.694, 5507.553,&
            &18849.22800, 775.5230, 0.067, 11790.62900, 796.2980, 10977.07900, 5486.778, 2544.314,&
            &5573.143, 6069.777, 213.2990, 2942.463, 20.77500, 0.98, 4694.003, 15720.83900, 7.114000,&
            &2146.170, 155.4200, 161000.6900, 6275.960, 71430.70, 17260.15, 12036.46, 5088.630, 3154.690,&
            &801.8200, 9437.760, 8827.390, 7084.900, 6286.600, 14143.50, 6279.550, 12139.55, 1748.020,&
            &5856.480, 1194.450, 8429.240, 19651.05, 10447.39, 10213.29, 1059.380, 2352.870, 6812.770,&
            &17789.85, 83996.85, 1349.870, 4690.480/)
       a1 = (/628331966747.000, 206059., 4303., 425., 119., 109., &
              93., 72., 68., 67., 59., 56., 45., 36., 29., 21., 19., 19., 17., 16., &
              16., 15., 12., 12., 12., 12., 11., 10., 10., 9., 9., 8., 6., 6./)
       b1 = (/0., 2.678235, 2.635100, 1.59, 5.796000, 2.966000, 2.59, 1.14, 1.87, 4.41, 2.89, 2.17, 0.40, 0.47,&
            &2.65, 5.34, 1.85, 4.97, 2.99, 0.030, 1.43, 1.21, 2.83, 3.26, 5.27, 2.08, 0.77, 1.3, 4.24, 2.7, 5.64,&
            &5.3, 2.65, 4.67/)
       c1 = (/0., 6283.075850, 12566.15170, 3.523000, 26.29800, 1577.344, 18849.23, 529.6900, 398.1500,&
            &5507.550, 5223.690, 155.4200, 796.3000, 775.5200, 7.11, 0.98, 5486.780, 213.3000, 6275.960,&
            &2544.310, 2146.170, 10977.08, 1748.020, 5088.630, 1194.450, 4694., 553.5700, 3286.600,&
            &1349.870, 242.7300, 951.7200, 2352.870, 9437.760, 4690.480/)
       a2 = (/52919, 8720, 309, 27, 16, 16, 10, 9, 7, 5, 4, 4, 3, 3, 3, 3, 3, 3, 2, 2/)
       b2 = (/0., 1.072100, 0.867, 0.050, 5.19, 3.68, 0.76, 2.06, 0.83, 4.66, 1.03, 3.44, 5.14, 6.05, 1.19,&
            &6.12, 0.31, 2.28, 4.38, 3.75/)
       c2 = (/0., 6283.075800, 12566.15200, 3.52, 26.3, 155.4200, 18849.23, 77713.77, 775.5200, 1577.340,&
            &7.11, 5573.140, 796.3000, 5507.550, 242.7300, 529.6900, 398.1500, 553.5700, 5223.690, 0.98/)
       a3 = (/289, 35, 17, 3, 1, 1, 1/)
       b3 = (/5.8440, 0., 5.4900, 5.2000, 4.7200, 5.3000, 5.9700/)
       c3 = (/6283.076, 0., 12566.15, 155.4200, 3.52, 18849.23, 242.7300/)
       a4 = (/114, 8, 1/)
       b4 = (/3.1420, 4.1300, 3.8400/)
       c4 = (/0., 6283.08, 12566.15/)
       a5 = 1.
       b5 = 3.1400
       c5 = 0.
       jme = julianephemeris_millenium
       ! Compute the Earth Heliochentric longitude from the tabulated values.
       l0 = sum(a0*cos(b0 + (c0*jme)))
       l1 = sum(a1*cos(b1 + (c1*jme)))
       l2 = sum(a2*cos(b2 + (c2*jme)))
       l3 = sum(a3*cos(b3 + (c3*jme)))
       l4 = sum(a4*cos(b4 + (c4*jme)))
       l5 = a5*cos(b5 + (c5*jme))
       earth_heliocentric_positionlongitude = &
            &(l0 + (l1*jme) + (l2*jme**2) + (l3*jme**3) + (l4*jme**4) + (l5*jme**5))/1e8
       ! Convert the longitude to degrees.
       earth_heliocentric_positionlongitude = earth_heliocentric_positionlongitude*180./pi
       ! Limit the range to [0,360[;
       earth_heliocentric_positionlongitude = set_to_range(earth_heliocentric_positionlongitude)
       a0i = (/280, 102, 80, 44, 32/)
       b0i = (/3.19900000000000, 5.42200000000000, 3.88000000000000, 3.70000000000000, 4./)
       c0i = (/84334.6620000000, 5507.55300000000, 5223.69000000000, 2352.87000000000, 1577.34000000000/)
       a1i = (/9, 6/)
       b1i = (/3.90000000000000, 1.73000000000000/)
       c1i = (/5507.55000000000, 5223.69000000000/)
       l0 = sum(a0i*cos(b0i + (c0i*jme)))
       l1 = sum(a1i*cos(b1i + (c1i*jme)))
       earth_heliocentric_positionlatitude = (l0 + (l1*jme))/1e8
       ! Convert the latitude to degrees.
       earth_heliocentric_positionlatitude = earth_heliocentric_positionlatitude*180/pi
       ! Limit the range to [0,360];
       earth_heliocentric_positionlatitude = set_to_range(earth_heliocentric_positionlatitude)
       a0j = (/100013989, 1670700, 13956, 3084, 1628, 1576, 925, 542, 472, 346, 329, 307, 243, 212, 186, 175, 110,&
            &98, 86, 86, 85, 63, 57, 56, 49, 47, 45, 43, 39, 38, 37, 37, 36, 35, 33, 32, 32, 28, 28, 26/)
       b0j = (/0., 3.09846350, 3.05525000, 5.1985, 1.1739, 2.8469, 5.453, 4.564, 3.661, 0.964, 5.90, 0.299,&
            &4.273, 5.847, 5.022, 3.012, 5.055, 0.890, 5.69, 1.27, 0.270, 0.920, 2.01, 5.24, 3.25, 2.58, 5.54,&
            &6.01, 5.36, 2.39, 0.830, 4.90, 1.67, 1.84, 0.240, 0.180, 1.78, 1.21, 1.90, 4.59/)
       c0j = (/0., 6283.07585, 12566.1517, 77713.7715, 5753.38490, 7860.41940, 11506.7700, 3930.21000,&
            &5884.92700, 5507.55300, 5223.69400, 5573.14300, 11790.6290, 1577.34400, 10977.0790, 18849.2280,&
            &5486.77800, 6069.78000, 15720.8400, 161000.690, 17260.1500, 529.69, 83996.8500, 71430.7000,&
            &2544.31000, 775.52, 9437.76000, 6275.96000, 4694., 8827.39000, 19651.0500, 12139.5500,&
            &12036.4600, 2942.46000, 7084.9, 5088.63000, 398.15, 6286.6, 6279.55000, 10447.3900/)
       a1j = (/103019, 1721, 702, 32, 31, 25, 18, 10, 9, 9/)
       b1j = (/1.10749000, 1.0644, 3.142, 1.02, 2.84, 1.32, 1.42, 5.91, 1.42, 0.270/)
       c1j = (/6283.07585, 12566.1517, 0., 18849.2300, 5507.55000, 5223.69000, 1577.34000, 10977.0800,&
            &6275.96000, 5486.78000/)
       a2j = (/4359, 124, 12, 9, 6, 3/)
       b2j = (/5.7846, 5.579, 3.14, 3.63, 1.87, 5.47/)
       c2j = (/6283.07580, 12566.1520, 0., 77713.7700, 5573.14000, 18849./)
       a3j = (/145, 7/)
       b3j = (/4.273, 3.92/)
       c3j = (/6283.07600, 12566.1500/)
       a4j = 4
       b4j = 2.56
       c4j = 6283.08000
       ! Compute the Earth heliocentric radius vector
       l0 = sum(a0j*cos(b0j + (c0j*jme)))
       l1 = sum(a1j*cos(b1j + (c1j*jme)))
       l2 = sum(a2j*cos(b2j + (c2j*jme)))
       l3 = sum(a3j*cos(b3j + (c3j*jme)))
       l4 = a4j*cos(b4j + (c4j*jme))
       ! Units are in AU
       earth_heliocentric_positionradius = &
            &(l0 + (l1*jme) + (l2*jme**2) + (l3*jme**3) + (l4*jme**4))/1e8
References set_to_range().
Referenced by narp_cal_sunposition().
emis_cloud()
real(kind(1d0)) function narp_module::emis_cloud (real(kind(1d0)) EMIS_A, real(kind(1d0)) FCLD)
Definition at line 1227 of file suews_phys_narp.f95.
       !calculates adjusted emissivity due to clouds
       REAL(KIND(1d0))::EMIS_A, FCLD, em_adj
       !T. Loridan, removing the square for FCLD in the emissivity correction
       !em_adj=EMIS_A+(1.-EMIS_A)*FCLD*FCLD
       em_adj = emis_a + (1.-emis_a)*fcld
Referenced by narp().
emis_cloud_sq()
real(kind(1d0)) function narp_module::emis_cloud_sq (real(kind(1d0)) EMIS_A, real(kind(1d0)) FCLD)
Definition at line 1235 of file suews_phys_narp.f95.
       !calculates adjusted emissivity due to clouds
       REAL(KIND(1d0))::EMIS_A, FCLD, em_adj
       em_adj = emis_a + (1.-emis_a)*fcld*fcld
Referenced by narp().
isurface()
real(kind(1d0)) function narp_module::isurface (integer doy, real(kind(1d0)) zenith)
Definition at line 1292 of file suews_phys_narp.f95.
       ! Calculates ground level solar irradiance clear sky
       ! assuming transmissivity = 1
       ! let it report zero if zenith >= 90
       REAL(KIND(1d0))::zenith, Isurf
       INTEGER::doy
       REAL(KIND(1d0))::Rmean, Rse, cosZ, Itoa
       REAL(KIND(1D0)), PARAMETER   :: DEG2RAD = 0.017453292
       rmean = 149.6                 !Stull 1998
       rse = solar_esdist(doy)
       IF (zenith < 90.*deg2rad) THEN
          cosz = cos(zenith)
          itoa = 1370.*(rmean/rse)**2  !top of the atmosphere
          isurf = itoa*cosz            !ground level solar irradiance in W/m2
       ELSE
          isurf = 0.
       ENDIF
References solar_esdist().
Referenced by narp().
julian_calculation()
subroutine narp_module::julian_calculation (real(kind(1d0)) year, integer month, integer day, integer hour, integer min, real(kind(1d0)) sec, real(kind(1d0)) UTC, real(kind(1d0)) juliancentury, real(kind(1d0)) julianday, real(kind(1d0)) julianephemeris_century, real(kind(1d0)) julianephemeris_day, real(kind(1d0)) julianephemeris_millenium)
Definition at line 535 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)) :: A, B, D, delta_t
       REAL(KIND(1D0)) :: juliancentury
       REAL(KIND(1D0)) :: julianday
       REAL(KIND(1D0)) :: julianephemeris_century
       REAL(KIND(1D0)) :: julianephemeris_day
       REAL(KIND(1D0)) :: julianephemeris_millenium
       REAL(KIND(1D0)) :: M, sec, year, UTC
       INTEGER :: day, hour, min, month
       !REAL(KIND(1D0)) :: time      !>
       REAL(KIND(1D0)) :: ut_time, Y !tt,
       !
       ! This function compute the julian day and julian century from the local
       ! time and timezone information. Ephemeris are calculated with a delta_t=0
       ! seconds.
       IF (month == 1 .OR. month == 2) THEN
          y = year - 1.
          m = month + 12
       ELSE
          y = year
          m = month
       END IF
       ut_time = ((float(hour) - utc)/24.) + (float(min)/(60.*24.)) + (sec/(60.*60.*24.)) ! time of day in UT time.
       d = day + ut_time ! Day of month in decimal time, ex. 2sd day of month at 12:30:30UT, D=2.521180556
       ! In 1582, the gregorian calendar was adopted
       IF (year == 1582.) THEN
          IF (month == 10) THEN
             IF (day <= 4) THEN ! The Julian calendar ended on October 4, 1582
                b = 0
             ELSE IF (day >= 15) THEN ! The Gregorian calendar started on October 15, 1582
                a = floor(y/100)
                b = 2 - a + floor(a/4)
             ELSE
                !disp('This date never existed!. Date automatically set to October 4, 1582')
                month = 10
                day = 4
                b = 0
             END IF
          ELSE IF (month < 10) THEN ! Julian calendar
             b = 0
          ELSE ! Gregorian calendar
             a = floor(y/100)
             b = 2 - a + floor(a/4)
          END IF
       ELSE IF (year < 1582.) THEN ! Julian calendar
          b = 0
       ELSE
          a = floor(y/100) ! Gregorian calendar
          b = 2 - a + floor(a/4)
       END IF
       julianday = floor(365.25*(y + 4716.)) + floor(30.6001*(m + 1)) + d + b - 1524.5
       delta_t = 0. ! 33.184;
       julianephemeris_day = julianday + (delta_t/86400)
       juliancentury = (julianday - 2451545.)/36525.
       julianephemeris_century = (julianephemeris_day - 2451545.)/36525.
       julianephemeris_millenium = julianephemeris_century/10.
Referenced by narp_cal_sunposition().
narp()
subroutine narp_module::narp (integer, intent(in) nsurf, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), dimension(nsurf), intent(in) snowFrac, real(kind(1d0)), dimension(nsurf), intent(in) alb, real(kind(1d0)), dimension(nsurf), intent(in) emis, real(kind(1d0)), dimension(nsurf), intent(in) IceFrac, real(kind(1d0)), intent(in) NARP_TRANS_SITE, real(kind(1d0)), intent(in) NARP_EMIS_SNOW, real(kind(1d0)), intent(in) DTIME, real(kind(1d0)), intent(in) ZENITH_deg, real(kind(1d0)), intent(in) kdown, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) RH, real(kind(1d0)), intent(in) Press_hPa, real(kind(1d0)), intent(in) qn1_obs, real(kind(1d0)), intent(in) SnowAlb, integer, intent(in) AlbedoChoice, integer, intent(in) ldown_option, integer, intent(in) NetRadiationMethodX, integer, intent(in) DiagQN, real(kind(1d0)), intent(out) QSTARall, real(kind(1d0)), intent(out) QSTAR_SF, real(kind(1d0)), intent(out) QSTAR_S, real(kind(1d0)), intent(out) kclear, real(kind(1d0)), intent(out) KUPall, real(kind(1d0)), intent(out) LDOWN, real(kind(1d0)), intent(out) LUPall, real(kind(1d0)), intent(out) fcld, real(kind(1d0)), intent(out) TSURFall, real(kind(1d0)), dimension(nsurf), intent(out) qn1_ind_snow, real(kind(1d0)), dimension(nsurf), intent(out) kup_ind_snow, real(kind(1d0)), dimension(nsurf), intent(out) Tsurf_ind_snow, real(kind(1d0)), dimension(nsurf), intent(out) Tsurf_ind)
Definition at line 106 of file suews_phys_narp.f95.
       !KCLEAR,FCLD,DTIME,KDOWN,QSTARall,KUPall,LDOWN,LUPall,TSURFall,&
       !AlbedoChoice,ldown_option,Temp_C,Press_hPa,Ea_hPa,qn1_obs,RH,&
       !,zenith_degnetRadiationChoice,
       !SUBROUTINE NARP(QSTAR,DTIME,KDOWN,LDOWN,T,RH,PRESS,FCLD,SNOW)
       !returns estimate of Q* given the meteorological fields and prior
       !configuration call.
       !OUTPUT FIELDS
       !QSTARall (W/m2) = net all wave radiation
       !KCLEAR          = clear sky incoming solar radiation
       !KUPall          = reflect solar radiation
       !LDOWN           = incoming longwave radiation (observed or modelled depending on ldown_option)
       !LUPall          = outgoing longwaver radiation
       !FCLD            = estimated cloud fraction (used only for emissivity estimate)
       !                  FCLD USED AS INPUT ALSO
       !TSURFall (DEG C)= estimated surface temperature
       !QSTAR_SF        = net all wave radiation for snow free surface
       !QSTAR_S         = net all wave radiation for SnowPack
       !INPUT FIELDS
       !DTIME (days) = local time, not daylight savings
       !KDOWN (W/m2) = incoming solar radiation
       !T (DEG C)    = air temperature near model height
       !RH (%)       = relative humidity near model height
       !PRESS (mb)   = station pressure, use estimate if unavailable
       !qn1_obs      = Observed Q*
       !INTERNAL FIELDS
       ! TemP_K = air temperature in K
       ! ES_hPs = saturation vapor pressure (hPa)
       ! EA_Pa = vapor pressure (hPa)
       ! TD = dewpoint (C)
       ! ZENITH = solar zenith angle
       ! ALB0 = surface albedo
       ! EMIS0 = surface emissivity
       ! EMIS_A = atmospheric emissivity
       ! TRANS = atmospheric transmissivity
       ! LUPCORR = correction for surface heating by kdown (W/m2)
       ! SIGMATK4 = energy flux density
       ! KDOWN_HR = hourly average insolation
       ! DOY = day of year
       !Modified by LJ to calcuate snow free and SnowPack components (May 2013)
       !Modified to define variables in data_in module
       !-------------------------------------------------------------------------------
       ! USE allocateArray
       ! use gis_data
       ! use data_in ! Included 20140701, FL
       ! use moist   ! Included 20140701, FL
       ! use time    ! Included 20140701, FL
       REAL(KIND(1D0)), DIMENSION(nsurf), INTENT(in) ::sfr
       REAL(KIND(1D0)), DIMENSION(nsurf), INTENT(in) ::snowFrac
       REAL(KIND(1D0)), DIMENSION(nsurf), INTENT(in) ::alb
       REAL(KIND(1D0)), DIMENSION(nsurf), INTENT(in) ::emis
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in) ::IceFrac
       ! REAL(KIND(1D0)),DIMENSION(365),INTENT(in) ::NARP_G
       REAL(KIND(1D0)), INTENT(in) ::DTIME
       REAL(KIND(1D0)), INTENT(in) ::ZENITH_deg
       REAL(KIND(1D0)), INTENT(in) ::kdown
       REAL(KIND(1D0)), INTENT(in) ::Temp_C
       REAL(KIND(1D0)), INTENT(in) ::RH
       REAL(KIND(1D0)), INTENT(in) ::Press_hPa
       REAL(KIND(1D0)), INTENT(in) ::qn1_obs
       REAL(KIND(1D0)), INTENT(in) ::SnowAlb
       REAL(KIND(1D0)), INTENT(in) ::NARP_TRANS_SITE
       REAL(KIND(1D0)), INTENT(in) ::NARP_EMIS_SNOW
       INTEGER, INTENT(in) ::nsurf
       INTEGER, INTENT(in) ::NetRadiationMethodX ! the one processed by RadMethod
       INTEGER, INTENT(in) ::AlbedoChoice
       INTEGER, INTENT(in) ::ldown_option
       INTEGER, INTENT(in) ::DiagQN
       REAL(KIND(1D0)), INTENT(out) ::QSTARall
       REAL(KIND(1D0)), INTENT(out) ::QSTAR_SF
       REAL(KIND(1D0)), INTENT(out) ::QSTAR_S
       REAL(KIND(1D0)), INTENT(out) ::kclear
       REAL(KIND(1D0)), INTENT(out) ::KUPall
       REAL(KIND(1D0)), INTENT(out) ::LDOWN
       REAL(KIND(1D0)), INTENT(out) ::LUPall
       REAL(KIND(1D0)), INTENT(out) ::fcld
       REAL(KIND(1D0)), INTENT(out) ::TSURFall
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out) ::qn1_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out) ::kup_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out) ::Tsurf_ind_snow
       REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(out) ::Tsurf_ind
       REAL(KIND(1d0)), DIMENSION(nsurf) ::qn1_ind
       REAL(KIND(1d0)), DIMENSION(nsurf) ::kup_ind
       REAL(KIND(1d0)), DIMENSION(nsurf) ::lup_ind
       REAL(KIND(1d0)), DIMENSION(nsurf) ::qn1_ind_nosnow
       REAL(KIND(1d0)), DIMENSION(nsurf) ::kup_ind_nosnow
       REAL(KIND(1d0)), DIMENSION(nsurf) ::lup_ind_nosnow
       REAL(KIND(1d0)), DIMENSION(nsurf) ::Tsurf_ind_nosnow
       REAL(KIND(1d0)), DIMENSION(nsurf) ::lup_ind_snow
       REAL(KIND(1D0)) ::Temp_K, TD, ZENITH, QSTAR, QSTAR_SNOW, KUP_SNOW, LUP_SNOW, TSURF_SNOW, KUP, LUP, TSURF
       REAL(KIND(1D0)) ::ALB0, EMIS0, EMIS_A, TRANS!,RH,DTIME,KDOWN
       REAL(KIND(1D0)) ::LUPCORR, SIGMATK4, KDOWN_HR = 0.
       INTEGER         ::DOY, is
       REAL(KIND(1D0))::qn1_cum, kup_cum, lup_cum, tsurf_cum, &   !Cumulative radiation components
                         qn1_is, kup_is, lup_is, tsurf_is, &       !Sub-surface radiation components
                         sf_all, alb1
       REAL(KIND(1D0)), PARAMETER   :: DEG2RAD = 0.017453292
       ! REAL(KIND(1D0)),PARAMETER   ::RAD2DEG=57.29577951
       REAL(KIND(1D0)), PARAMETER   :: SIGMA_SB = 5.67e-8
       ! NB: NARP_G is not assigned with a value in SUEWS_translate.
       ! 3.0 is used here as annual average for mid-latitude areas. TS 24 Oct 2017
       REAL(KIND(1D0)), DIMENSION(365), PARAMETER ::  NARP_G = 3.0
       !Initialize variables
       ! RH=avrh
       ! DTIME=dectime
       ! KDOWN=avkdn
       temp_k = temp_c + 273.16
       sigmatk4 = sigma_sb*temp_k**4
       td = dewpoint(temp_c, rh)
       ! Sun postition is now calculated in the main loop, FL
       !ZENITH=SOLAR_ZENITH(NARP_LAT,NARP_LONG,NARP_TZ,DTIME)
       !call NARP_cal_SunPosition(NARP_YEAR,DTIME,NARP_TZ,NARP_LAT,NARP_LONG,Alt,AZIMUTH,ZENITH)
       zenith = zenith_deg*deg2rad
       doy = int(dtime)
       IF (doy == 366) doy = 365
       !===================================================================================
       !Calculate radiation for each sub-surface
       qn1_cum = 0
       kup_cum = 0
       lup_cum = 0
       tsurf_cum = 0
       qstar_sf = 0
       qstar_s = 0
       !Total snowfree surface fraction
       sf_all = 0
       DO is = 1, nsurf
          IF (sfr(is) /= 0) sf_all = sf_all + sfr(is)*(1 - snowfrac(is))
       ENDDO
       DO is = 1, nsurf
          IF (diagqn == 1) WRITE (*, *) 'is ', is
          emis_a = prata_emis(temp_k, press_hpa)
          !--------------------------------------------------
          !-------SNOW FREE SURFACE--------------------------
          IF (albedochoice == 1 .AND. 180*zenith/acos(0.0) < 90) THEN
             alb0 = alb(is) + 0.5e-16*(180*zenith/acos(0.0))**8 !AIDA 1982
          ELSE
             alb0 = alb(is)
          ENDIF
          emis0 = emis(is)
          !Downward longwave radiation
          IF ((ldown_option == 4) .OR. (ldown_option == 5)) THEN !Estimate FCLD from Kdown (Offerle et al. 2003)
             IF (zenith < 1.5) THEN !DAYTIME CALCULATIONS
                trans = transmissivity(press_hpa, td, narp_g(doy), zenith)
                kclear = isurface(doy, zenith)*trans*narp_trans_site
                IF (kclear > 50.) THEN
                   fcld = cloud_fraction(kdown, kclear)
                   emis_a = emis_cloud_sq(emis_a, fcld)
                ELSE
                   IF (ldown_option == 5) THEN ! Use RH when Kdown can not be used
                      fcld = wc_fraction(rh, temp_c)
                      emis_a = emis_cloud(emis_a, fcld)
                   ELSE
                      !FCLD is left to the latest calculable value
                      emis_a = emis_cloud_sq(emis_a, fcld)
                   ENDIF
                ENDIF
             ELSE !NIGHT TIME CALCULATIONS
                IF (ldown_option == 4) THEN
                   !FCLD is left to the latest calculable value
                   emis_a = emis_cloud_sq(emis_a, fcld)
                ELSEIF ((ldown_option == 5)) THEN ! Use RH
                   fcld = wc_fraction(rh, temp_c)
                   emis_a = emis_cloud(emis_a, fcld)
                ENDIF
             ENDIF
          ELSEIF (ldown_option == 3) THEN !Always use RH
             fcld = wc_fraction(rh, temp_c)
             emis_a = emis_cloud(emis_a, fcld)
          ELSEIF (ldown_option == 2) THEN ! FCLD obs, came from input
             emis_a = emis_cloud(emis_a, fcld)
          ENDIF
          IF (diagqn == 1) WRITE (*, *) 'ldown_option: ', ldown_option, 'FCLD:', fcld
          IF (ldown_option > 1) THEN ! Forcing available if ldown_option=1, model otherwise
             ldown = emis_a*sigmatk4
             IF (diagqn == 1) WRITE (*, *) 'EMIS_A: ', emis_a, 'SIGMATK4:', sigmatk4, 'LDOWN: ', ldown
          ENDIF
          !----------------------------------------------------------------------------
          !Note that this is not averaged over the hour for cases where time step < 1hr
          kdown_hr = kdown
          IF (kdown_hr > 0) THEN
             lupcorr = (1 - alb0)*(0.08*kdown_hr)
          ELSE
             lupcorr = 0.
          ENDIF
          kup = alb0*kdown
          tsurf = ((emis0*sigmatk4 + lupcorr)/(emis0*sigma_sb))**0.25 !Eqs. (14) and (15),
          lup = emis0*sigmatk4 + lupcorr + (1 - emis0)*ldown              !Eq (16) in Offerle et al. (2002)
          qstar = kdown - kup + ldown - lup
          tsurf = tsurf - 273.16
          !======================================================================
          !Snow related parameters if snow pack existing
          IF (snowfrac(is) > 0) THEN
             IF (albedochoice == 1 .AND. 180*zenith/acos(0.0) < 90) THEN
                alb1 = snowalb + 0.5e-16*(180*zenith/acos(0.0))**8 !AIDA 1982
             ELSE
                alb1 = snowalb
             ENDIF
             kup_snow = (alb1*(snowfrac(is) - snowfrac(is)*icefrac(is)) + alb0*snowfrac(is)*icefrac(is))*kdown
             tsurf_snow = ((narp_emis_snow*sigmatk4)/(narp_emis_snow*sigma_sb))**0.25 !Snow surface temperature
             !IF (TSURF_SNOW>273.16) TSURF_SNOW=min(273.16,Temp_K)!Set this to 2 degrees (melted water on top)
             !open(34,file='TestingSnowFrac.txt',position='append')
             !write(34,*) dectime,is,alb1,alb0,snowFrac(is),IceFrac(is),KDOWN,KUP_snow
             !close(34)
             lup_snow = narp_emis_snow*sigma_sb*tsurf_snow**4 + (1 - narp_emis_snow)*ldown
             qstar_snow = kdown - kup_snow + ldown - lup_snow
             tsurf_snow = tsurf_snow - 273.16
          ELSE
             kup_snow = 0
             lup_snow = 0
             tsurf_snow = 0
             qstar_snow = 0
             !QSTAR_ICE = 0
             !KUP_ICE = 0
          ENDIF
          qn1_ind_nosnow(is) = qstar          !Define sub-surface radiation components
          kup_ind_nosnow(is) = kup
          lup_ind_nosnow(is) = lup
          tsurf_ind_nosnow(is) = tsurf
          qn1_ind_snow(is) = qstar_snow        !Define snow sub-surface radiation components
          kup_ind_snow(is) = kup_snow
          lup_ind_snow(is) = lup_snow
          tsurf_ind_snow(is) = tsurf_snow
          IF (sf_all /= 0) THEN
             qstar_sf = qstar_sf + qstar*sfr(is)*(1 - snowfrac(is))/sf_all
          ELSE
             qstar_sf = qstar_sf + qstar*sfr(is)*(1 - snowfrac(is))
          ENDIF
          IF ((1 - sf_all) /= 0) THEN
             qstar_s = qstar_s + qstar_snow*sfr(is)*snowfrac(is)/(1 - sf_all)
          ELSE
             qstar_s = qstar_s + qstar_snow*sfr(is)*snowfrac(is)
          ENDIF
          !---------------------------------------------------------------------
          !Calculate weighted variables for each subsurface
          qn1_is = qstar*(1 - snowfrac(is)) + qstar_snow*snowfrac(is)
          kup_is = kup*(1 - snowfrac(is)) + kup_snow*snowfrac(is)
          lup_is = lup*(1 - snowfrac(is)) + lup_snow*snowfrac(is)
          tsurf_is = tsurf*(1 - snowfrac(is)) + tsurf_snow*snowfrac(is)
          IF (diagqn == 1) WRITE (*, *) 'QSTAR', qstar, 'QSTAR_SNOW', qstar_snow, 'snowFrac', snowfrac(is)
          qn1_cum = qn1_cum + (qn1_is*sfr(is))  !Calculate cumulative radiation components
          kup_cum = kup_cum + (kup_is*sfr(is))
          lup_cum = lup_cum + (lup_is*sfr(is))
          tsurf_cum = tsurf_cum + (tsurf_is*sfr(is))
          qn1_ind(is) = qn1_is                !Define sub-surface radiation components
          kup_ind(is) = kup_is
          lup_ind(is) = lup_is
          tsurf_ind(is) = tsurf_is
          IF (diagqn == 1) WRITE (*, *) 'qn1_is: ', qn1_is
       ENDDO !End of the surface types
       !Set overall radiation components
       IF (netradiationmethodx /= 3000) THEN !Observed Q* used and snow is modeled
          qstarall = qn1_cum
       ELSE
          qstarall = qn1_obs
       ENDIF
       kupall = kup_cum
       lupall = lup_cum
       tsurfall = tsurf_cum
       ! qn1=QSTARall
       ! kup=KUPall
       !LDOWN has same name
       ! LUP=LUPall
       tsurf = tsurfall
       !if (kup>500) then
       ! write(*,*) Kdown, kup, kup_ind(1),kup_ind(2),kup_ind(3),kup_ind(4),kup_ind(5),kup_ind(6),SnowAlb
       ! pause
       !endif
       IF (diagqn == 1) WRITE (*, *) 'kdown: ', kdown, 'kup:', kup, 'LDOWN: ', ldown, 'LUP: ', lup
       IF (diagqn == 1) WRITE (*, *) 'Qn: ', qstarall
References cloud_fraction(), dewpoint(), emis_cloud(), emis_cloud_sq(), isurface(), prata_emis(), transmissivity(), and wc_fraction().
Referenced by suews_driver::suews_cal_qn().
narp_cal_sunposition()
subroutine narp_module::narp_cal_sunposition (real(kind(1d0)), intent(in) year, real(kind(1d0)), intent(in) idectime, real(kind(1d0)), intent(in) UTC, real(kind(1d0)), intent(in) locationlatitude, real(kind(1d0)), intent(in) locationlongitude, real(kind(1d0)), intent(in) locationaltitude, real(kind(1d0)), intent(out) sunazimuth, real(kind(1d0)), intent(out) sunzenith)
Definition at line 427 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: year, idectime, UTC, locationlatitude, locationlongitude, locationaltitude
       REAL(KIND(1D0)), INTENT(out) ::sunazimuth, sunzenith
       REAL(KIND(1D0)):: sec
       INTEGER :: month, day, hour, min, seas, dayofyear, year_int
       REAL(KIND(1D0)) :: juliancentury, julianday, julianephemeris_century, julianephemeris_day, &
                          julianephemeris_millenium
       REAL(KIND(1D0)) :: earth_heliocentric_positionlatitude, earth_heliocentric_positionlongitude, &
                          earth_heliocentric_positionradius
       REAL(KIND(1D0)) :: sun_geocentric_positionlatitude, sun_geocentric_positionlongitude
       REAL(KIND(1D0)) :: nutationlongitude, nutationobliquity
       REAL(KIND(1D0)) :: corr_obliquity
       REAL(KIND(1D0)) :: aberration_correction
       REAL(KIND(1D0)) :: apparent_sun_longitude
       REAL(KIND(1D0)) :: apparent_stime_at_greenwich
       REAL(KIND(1D0)) :: sun_rigth_ascension
       REAL(KIND(1D0)) :: sun_geocentric_declination
       REAL(KIND(1D0)) :: observer_local_hour
       REAL(KIND(1D0)) :: topocentric_sun_positionrigth_ascension, topocentric_sun_positionrigth_ascension_parallax
       REAL(KIND(1D0)) :: topocentric_sun_positiondeclination
       REAL(KIND(1D0)) :: topocentric_local_hour
       ! REAL(KIND(1D0)) :: sunazimuth,sunzenith
       ! This function compute the sun position (zenith and azimuth angle (in degrees) at the observer
       ! location) as a function of the observer local time and position.
       !
       ! Input lat and lng should be in degrees, alt in meters.
       !
       ! It is an implementation of the algorithm presented by Reda et Andreas in:
       ! Reda, I., Andreas, A. (2003) Solar position algorithm for solar
       ! radiation application. National Renewable Energy Laboratory (NREL)
       ! Technical report NREL/TP-560-34302.
       ! This document is avaLAIble at www.osti.gov/bridge
       ! Code is translated from matlab code by Fredrik Lindberg (fredrikl@gvc.gu.se)
       ! Last modified: LJ 27 Jan 2016 - Tabs removed
       ! Convert to timevectors from dectime and year
       CALL dectime_to_timevec(idectime, hour, min, sec)
       dayofyear = floor(idectime)
       year_int = int(year)
       CALL day2month(dayofyear, month, day, seas, year_int, locationlatitude)
       ! 1. Calculate the Julian Day, and Century. Julian Ephemeris day, century
       ! and millenium are calculated using a mean delta_t of 33.184 seconds.
       CALL julian_calculation(year, month, day, hour, min, sec, utc, juliancentury, julianday, julianephemeris_century, &
                               julianephemeris_day, julianephemeris_millenium)
       ! 2. Calculate the Earth heliocentric longitude, latitude, and radius
       ! vector (L, B, and R)
       CALL earth_heliocentric_position_calculation(julianephemeris_millenium, earth_heliocentric_positionlatitude,&
            &earth_heliocentric_positionlongitude, earth_heliocentric_positionradius)
       ! 3. Calculate the geocentric longitude and latitude
       CALL sun_geocentric_position_calculation(earth_heliocentric_positionlongitude, earth_heliocentric_positionlatitude,&
            & sun_geocentric_positionlatitude, sun_geocentric_positionlongitude)
       ! 4. Calculate the nutation in longitude and obliquity (in degrees).
       CALL nutation_calculation(julianephemeris_century, nutationlongitude, nutationobliquity)
       ! 5. Calculate the true obliquity of the ecliptic (in degrees).
       CALL corr_obliquity_calculation(julianephemeris_millenium, nutationobliquity, corr_obliquity)
       ! 6. Calculate the aberration correction (in degrees)
       CALL abberation_correction_calculation(earth_heliocentric_positionradius, aberration_correction)
       ! 7. Calculate the apparent sun longitude in degrees)
       CALL apparent_sun_longitude_calculation(sun_geocentric_positionlongitude, nutationlongitude,&
            & aberration_correction, apparent_sun_longitude)
       ! 8. Calculate the apparent sideral time at Greenwich (in degrees)
       CALL apparent_stime_at_greenwich_calculation(julianday, juliancentury, nutationlongitude, &
            &corr_obliquity, apparent_stime_at_greenwich)
       ! 9. Calculate the sun rigth ascension (in degrees)
       CALL sun_rigth_ascension_calculation(apparent_sun_longitude, corr_obliquity, sun_geocentric_positionlatitude, &
            &sun_rigth_ascension)
       ! 10. Calculate the geocentric sun declination (in degrees). Positive or
       ! negative if the sun is north or south of the celestial equator.
       CALL sun_geocentric_declination_calculation(apparent_sun_longitude, corr_obliquity, sun_geocentric_positionlatitude, &
            &sun_geocentric_declination)
       ! 11. Calculate the observer local hour angle (in degrees, westward from south).
       CALL observer_local_hour_calculation(apparent_stime_at_greenwich, locationlongitude, sun_rigth_ascension, observer_local_hour)
       ! 12. Calculate the topocentric sun position (rigth ascension, declination and
       ! rigth ascension parallax in degrees)
       CALL topocentric_sun_position_calculate(topocentric_sun_positionrigth_ascension,&
            &topocentric_sun_positionrigth_ascension_parallax, topocentric_sun_positiondeclination, locationaltitude,&
            &locationlatitude, observer_local_hour, sun_rigth_ascension, sun_geocentric_declination,&
            &earth_heliocentric_positionradius)
       ! 13. Calculate the topocentric local hour angle (in degrees)
       CALL topocentric_local_hour_calculate(observer_local_hour, topocentric_sun_positionrigth_ascension_parallax,&
            & topocentric_local_hour)
       ! 14. Calculate the topocentric zenith and azimuth angle (in degrees)
       CALL sun_topocentric_zenith_angle_calculate(locationlatitude, topocentric_sun_positiondeclination,&
            & topocentric_local_hour, sunazimuth, sunzenith)
References abberation_correction_calculation(), apparent_stime_at_greenwich_calculation(), apparent_sun_longitude_calculation(), corr_obliquity_calculation(), day2month(), dectime_to_timevec(), earth_heliocentric_position_calculation(), julian_calculation(), nutation_calculation(), observer_local_hour_calculation(), sun_geocentric_declination_calculation(), sun_geocentric_position_calculation(), sun_rigth_ascension_calculation(), sun_topocentric_zenith_angle_calculate(), topocentric_local_hour_calculate(), and topocentric_sun_position_calculate().
Referenced by metdisagg::disaggregatemet(), suews_driver::suews_cal_main(), and suews_driver::suews_cal_sunposition().
nutation_calculation()
subroutine narp_module::nutation_calculation (real(kind(1d0)), intent(in) julianephemeris_century, real(kind(1d0)) nutationlongitude, real(kind(1d0)) nutationobliquity)
Definition at line 807 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: julianephemeris_century
       REAL(KIND(1D0)), DIMENSION(63) :: delta_longitude
       REAL(KIND(1D0)), DIMENSION(63) :: delta_obliquity
       REAL(KIND(1D0)) :: JCE
       REAL(KIND(1D0)) :: nutationlongitude
       REAL(KIND(1D0)) :: nutationobliquity
       REAL(KIND(1D0)), DIMENSION(4) :: p0, p1, p2, p3, p4
       REAL(KIND(1D0)), DIMENSION(63) ::tabulated_argument
       REAL(KIND(1D0)) :: X0
       REAL(KIND(1D0)) :: X1
       REAL(KIND(1D0)) :: X2
       REAL(KIND(1D0)) :: X3
       REAL(KIND(1D0)) :: X4
       REAL(KIND(1D0)), DIMENSION(5) :: Xi
       INTEGER, DIMENSION(315) :: Y_terms1
       INTEGER, DIMENSION(5, 63) ::Y_terms
       REAL(KIND(1D0)), DIMENSION(252) :: nutation_terms1
       REAL(KIND(1D0)), DIMENSION(4, 63) ::nutation_terms
       INTEGER :: i
       REAL(KIND(1D0)), PARAMETER       :: pi = 3.141592653589793d+0
       ! This function compute the nutation in longtitude and in obliquity, in
       ! degrees.
       ! All Xi are in degrees.
       jce = julianephemeris_century
       ! 1. Mean elongation of the moon from the sun
       p0 = (/(1/189474.), -0.0019142, 445267.11148, 297.85036/)
       ! X0 = polyval(p, JCE);
       x0 = p0(1)*jce**3 + p0(2)*jce**2 + p0(3)*jce + p0(4) ! This is faster than polyval...
       ! 2. Mean anomaly of the sun (earth)
       p1 = (/-(1/300000.), -0.0001603, 35999.05034, 357.52772/)
       ! X1 = polyval(p, JCE);
       x1 = p1(1)*jce**3 + p1(2)*jce**2 + p1(3)*jce + p1(4)
       ! 3. Mean anomaly of the moon
       p2 = (/(1/56250.), 0.0086972, 477198.867398, 134.96298/)
       ! X2 = polyval(p, JCE);
       x2 = p2(1)*jce**3 + p2(2)*jce**2 + p2(3)*jce + p2(4)
       ! 4. Moon argument of latitude
       p3 = (/(1/327270.), -0.0036825, 483202.017538, 93.27191/)
       ! X3 = polyval(p, JCE);
       x3 = p3(1)*jce**3 + p3(2)*jce**2 + p3(3)*jce + p3(4)
       ! 5. Longitude of the ascending node of the moon's mean orbit on the
       ! ecliptic, measured from the mean equinox of the date
       p4 = (/(1/450000.), 0.0020708, -1934.136261, 125.04452/)
       ! X4 = polyval(p, JCE);
       x4 = p4(1)*jce**3 + p4(2)*jce**2 + p4(3)*jce + p4(4)
       ! Y tabulated terms from the original code
       y_terms1 = (/0, 0, 0, 0, 1, -2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, &
                    0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, -2, 1, 0, 2, 2, 0, 0, 0, 2, 1, &
                    0, 0, 1, 2, 2, -2, -1, 0, 2, 2, -2, 0, 1, 0, 0, -2, 0, 0, 2, 1, 0, 0, -1, 2, 2, 2, 0, &
                    0, 0, 0, 0, 0, &
                    1, 0, 1, 2, 0, -1, 2, 2, &
                    0, 0, -1, 0, 1, 0, 0, 1, 2, 1, -2, 0, 2, 0, 0, 0, 0, -2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, &
                    2, 2, 0, 0, 2, &
                    0, 0, -2, 0, 1, 2, 2, 0, &
                    0, 0, 2, 0, -2, 0, 0, 2, 0, 0, 0, -1, 2, 1, 0, 2, 0, 0, 0, &
                    2, 0, -1, 0, 1, -2, 2, 0, 2, 2, 0, 1, 0, 0, 1, &
                    -2, 0, 1, 0, 1, 0, -1, 0, 0, 1, 0, 0, &
                    2, -2, 0, 2, 0, -1, 2, 1, 2, 0, 1, 2, 2, 0, 1, 0, 2, 2, -2, &
                    1, 1, 0, 0, 0, -1, 0, 2, 2, 2, 0, 0, 2, 1, 2, &
                    0, 1, 0, 0, -2, 0, 2, 2, 2, -2, 0, 1, &
                    2, 1, 2, 0, -2, 0, 1, 2, 0, 0, 0, 1, 0, -1, 1, 0, 0, -2, -1, &
                    0, 2, 1, -2, 0, 0, 0, 1, 0, 0, 2, 2, 1, -2, &
                    0, 2, 0, 1, -2, 1, 0, 2, 1, 0, 0, 1, -2, &
                    0, -1, 0, 1, 0, 0, -2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, &
                    0, 0, 0, -2, 2, 2, -1, -1, 1, 0, 0, 0, 1, &
                    1, 0, 0, 0, -1, 1, 2, 2, 2, -1, -1, 2, 2, &
                    0, 0, 3, 2, 2, 2, -1, 0, 2, 2/)
       y_terms = reshape(y_terms1, (/5, 63/))
       nutation_terms1 = (/-171996., -174.2, 92025., 8.9, -13187., -1.6, 5736., -3.1, -2274., -0.2, 977., -0.5, 2062., &
                           0.2, -895., 0.5, &
                           1426., -3.4, 54., -0.1, 712., 0.1, -7., 0., -517., 1.2, 224., -0.6, -386., -0.4, 200., 0., -301., &
                           0., 129., -0.1, &
                           217., -0.5, -95., 0.3, -158., 0., 0., 0., 129., 0.1, -70., 0., 123., 0., -53., 0., 63., 0., 0., 0., &
                           63., 0.1, -33., 0., -59., 0., 26., 0., &
                           -58., -0.1, 32., 0., -51., 0., 27., 0., 48., 0., 0., 0., 46., 0., -24., 0., -38., &
                           0., 16., 0., -31., 0., 13., 0., 29., 0., &
                           0., 0., 29., 0., -12., 0., 26., 0., 0., 0., -22., 0., 0., 0., 21., 0., -10., 0., 17., -0.1, 0., 0., 16., &
                           0., -8., 0., -16., 0.1, 7., 0., &
                           -15., 0., 9., 0., -13., 0., 7., 0., -12., 0., 6., 0., 11., 0., 0., 0., &
                           -10., 0., 5., 0., -8., 0., 3., 0., 7., &
                           0., -3., 0., -7., 0., 0., 0., &
                           -7., 0., 3., 0., -7., 0., 3., 0., 6., 0., 0., 0., 6., 0., -3., 0., 6., 0., &
                           -3., 0., -6., 0., 3., 0., -6., 0., 3., &
                           0., 5., 0., 0., 0., -5., 0., &
                           3., 0., -5., 0., 3., 0., -5., 0., 3., 0., 4., 0., 0., 0., 4., 0., 0., 0., 4., 0., 0., 0., -4., 0., 0., &
                           0., -4., 0., 0., 0., -4., 0., 0., 0., &
                           3., 0., 0., 0., -3., 0., 0., 0., -3., 0., 0., 0., -3., 0., 0., 0., -3., 0., 0., 0., -3., 0., 0., &
                           0., -3., 0., 0., 0., -3., 0., 0., 0./)
       nutation_terms = reshape(nutation_terms1, (/4, 63/))
       ! Using the tabulated values, compute the delta_longitude and
       ! delta_obliquity.
       xi = (/x0, x1, x2, x3, x4/)
       DO i = 1, 63
          tabulated_argument(i) = ((y_terms(1, i)*xi(1)) &
                                   + (y_terms(2, i)*xi(2)) + (y_terms(3, i)*xi(3)) &
                                   + (y_terms(4, i)*xi(4)) + (y_terms(5, i)*xi(5)))*pi/180
       END DO
       delta_longitude = ((nutation_terms(1, :) + (nutation_terms(2, :)*jce)))*sin(tabulated_argument)
       delta_obliquity = ((nutation_terms(3, :) + (nutation_terms(4, :)*jce)))*cos(tabulated_argument)
       ! Nutation in longitude
       nutationlongitude = sum(delta_longitude)/36000000.0
       ! Nutation in obliquity
       nutationobliquity = sum(delta_obliquity)/36000000.0
Referenced by narp_cal_sunposition().
observer_local_hour_calculation()
subroutine narp_module::observer_local_hour_calculation (real(kind(1d0)), intent(in) apparent_stime_at_greenwich, real(kind(1d0)), intent(in) locationlongitude, real(kind(1d0)), intent(in) sun_rigth_ascension, real(kind(1d0)), intent(out) observer_local_hour)
Definition at line 1048 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: apparent_stime_at_greenwich
       REAL(KIND(1D0)), INTENT(in) :: locationlongitude
       REAL(KIND(1D0)), INTENT(out) :: observer_local_hour
       REAL(KIND(1D0)), INTENT(in) :: sun_rigth_ascension
       observer_local_hour = apparent_stime_at_greenwich + locationlongitude - sun_rigth_ascension
       ! Set the range to [0-360]
       observer_local_hour = set_to_range(observer_local_hour)
References set_to_range().
Referenced by narp_cal_sunposition().
prata_emis()
real(kind(1d0)) function narp_module::prata_emis (real(kind(1d0)) Temp_K, real(kind(1d0)) EA_hPa)
Definition at line 1218 of file suews_phys_narp.f95.
       ! clear sky emissivity function Prata 1996
       REAL(KIND(1d0))::Temp_K, ea_hPa, EMIS_A
       REAL(KIND(1d0))::W
       w = 46.5*(ea_hpa/temp_k)
       emis_a = 1.-(1.+w)*exp(-sqrt(1.2 + 3.*w))
Referenced by narp().
radmethod()
subroutine narp_module::radmethod (integer, intent(in) NetRadiationMethod, integer, intent(in) snowUse, integer, intent(out) NetRadiationMethodX, integer, intent(out) AlbedoChoice, integer, intent(out) ldown_option)
Definition at line 48 of file suews_phys_narp.f95.
       IMPLICIT NONE
       INTEGER, INTENT(in) :: NetRadiationMethod ! the one from RunControl setting
       INTEGER, INTENT(in) ::snowUse
       INTEGER, INTENT(out)::NetRadiationMethodX ! processed NetRadiationMethod to be used for other radiation calculations
       INTEGER, INTENT(out)::AlbedoChoice, ldown_option
       !Determine what should be done with respect to radiation
       ! TODO: this can be wrapped into a subroutine, TS 20 Oct 2017
       albedochoice = 0
       ldown_option = 0
       IF (netradiationmethod == 0) THEN    !Observed Q* from the met input file will be used
          netradiationmethodx = 0
          !  ldown_option is not required if NetRadiationMethodX=0 as LDOWN calculations are skipped
          IF (snowuse == 1) THEN            !If snow is modelled, NARP is needed for surface temperature
             ! NetRadiationMethod=3000
             netradiationmethodx = 3000
             ldown_option = 3              !LDOWN will be modelled
             !NetRadiationMethod=NetRadiationMethod/1000
          ENDIF
       ELSEIF (netradiationmethod > 0) THEN  !Modelled Q* is used (NARP)
          albedochoice = -9
          IF (netradiationmethod < 10) THEN
             albedochoice = 0
             IF (netradiationmethod == 1) ldown_option = 1
             IF (netradiationmethod == 2) ldown_option = 2
             IF (netradiationmethod == 3) ldown_option = 3
             netradiationmethodx = netradiationmethod
          ELSEIF (netradiationmethod >= 100 .AND. netradiationmethod < 1000) THEN
             albedochoice = 1
             IF (netradiationmethod == 100) ldown_option = 1
             IF (netradiationmethod == 200) ldown_option = 2
             IF (netradiationmethod == 300) ldown_option = 3
             ! NetRadiationMethod=NetRadiationMethod/100
             netradiationmethodx = netradiationmethod/100
          ENDIF
          !If bad NetRadiationMethod value
          IF (netradiationmethodx > 3 .OR. albedochoice == -9) THEN
             WRITE (*, *) 'NetRadiationMethod=', netradiationmethodx
             WRITE (*, *) 'Value not usable'
             stop
          ENDIF
       ENDIF
Referenced by suews_driver::suews_cal_qn().
set_to_range()
real(kind(1d0)) function narp_module::set_to_range (real(kind(1d0)) var)
Definition at line 1184 of file suews_phys_narp.f95.
       ! This function make sure the variable is in the specified range.
       REAL(KIND(1D0)) :: max_interval
       REAL(KIND(1D0)) :: min_interval
       REAL(KIND(1D0)) :: var
       REAL(KIND(1D0)) :: vari
       !
       max_interval = 360.0
       min_interval = 0.0
       vari = var - max_interval*floor(var/max_interval)
       IF (vari < min_interval) THEN
          vari = vari + max_interval
       END IF
Referenced by apparent_stime_at_greenwich_calculation(), earth_heliocentric_position_calculation(), observer_local_hour_calculation(), sun_geocentric_position_calculation(), sun_rigth_ascension_calculation(), and sun_topocentric_zenith_angle_calculate().
smithlambda()
real(kind(1d0)) function, dimension(365) narp_module::smithlambda (integer lat)
Definition at line 1330 of file suews_phys_narp.f95.
       USE filename
       USE defaultnotused
       !read kriged data based on Smith 1966 (JAM)
       ! Smith, William L.
       ! "Note on the relationship between total precipitable water and surface dew point."
       ! Journal of Applied Meteorology 5.5 (1966): 726-727.
       INTEGER :: lat, ios, ilat
       REAL(KIND(1d0)), DIMENSION(365):: G
       !open(99,file="Smith1966.grd",access="direct",action="read",recl=365*4,iostat=ios)
       !read(99,rec=lat+1,iostat=ios) G
       OPEN (99, file=smithfile, iostat=ios)
       DO ilat = 1, lat
          READ (99, *)
       ENDDO
       READ (99, *, iostat=ios) ilat, g
       IF (ios /= 0) THEN
          CALL errorhint(11, 'reading Smith1966.grd (ios).', notused, notused, ios)
       ENDIF
       CLOSE (99)
References errorhint(), defaultnotused::notused, and filename::smithfile.
solar_esdist()
real(kind(1d0)) function narp_module::solar_esdist (integer doy)
Definition at line 1314 of file suews_phys_narp.f95.
       !from Stull, 1998   Keep! called from SOLWEIG_clearnessindex_2013b
       INTEGER          ::doy
       REAL(KIND(1d0))             ::Rse
       REAL(KIND(1d0)) ::MA, nu, e, a
       e = 0.0167
       a = 146.457
       ma = 2.*3.141592654*(doy - 3)/365.25463 !Mean anomaly
       nu = ma + 0.0333988*sin(ma) + .0003486*sin(2.*ma) + 5e-6*sin(3.*ma) !true anomaly
       rse = a*(1 - e*e)/(1 + e*cos(nu))
Referenced by isurface().
sun_geocentric_declination_calculation()
subroutine narp_module::sun_geocentric_declination_calculation (real(kind(1d0)), intent(in) apparent_sun_longitude, real(kind(1d0)), intent(in) corr_obliquity, real(kind(1d0)), intent(in) sun_geocentric_positionlatitude, real(kind(1d0)), intent(out) sun_geocentric_declination)
Definition at line 1031 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: apparent_sun_longitude
       REAL(KIND(1D0)), INTENT(in) :: corr_obliquity
       REAL(KIND(1D0)), INTENT(out) :: sun_geocentric_declination
       REAL(KIND(1D0)), INTENT(in) :: sun_geocentric_positionlatitude
       REAL(KIND(1D0)) :: argument
       REAL(KIND(1D0)), PARAMETER       :: pi = 3.141592653589793d+0
       argument = (sin(sun_geocentric_positionlatitude*pi/180.0)*cos(corr_obliquity*pi/180.0)) + &
                  (cos(sun_geocentric_positionlatitude*pi/180.0)*sin(corr_obliquity*pi/180)*sin(apparent_sun_longitude*pi/180.0))
       sun_geocentric_declination = asin(argument)*180.0/pi
Referenced by narp_cal_sunposition().
sun_geocentric_position_calculation()
subroutine narp_module::sun_geocentric_position_calculation (real(kind(1d0)), intent(in) earth_heliocentric_positionlongitude, real(kind(1d0)), intent(in) earth_heliocentric_positionlatitude, real(kind(1d0)) sun_geocentric_positionlatitude, real(kind(1d0)) sun_geocentric_positionlongitude)
Definition at line 788 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: earth_heliocentric_positionlongitude
       REAL(KIND(1D0)), INTENT(in) :: earth_heliocentric_positionlatitude
       REAL(KIND(1D0)) :: sun_geocentric_positionlatitude
       REAL(KIND(1D0)) :: sun_geocentric_positionlongitude
       ! This function compute the sun position relative to the earth.
       sun_geocentric_positionlongitude = earth_heliocentric_positionlongitude + 180.0
       ! Limit the range to [0,360];
       sun_geocentric_positionlongitude = set_to_range(sun_geocentric_positionlongitude)
       sun_geocentric_positionlatitude = -earth_heliocentric_positionlatitude
       ! Limit the range to [0,360]
       sun_geocentric_positionlatitude = set_to_range(sun_geocentric_positionlatitude)
References set_to_range().
Referenced by narp_cal_sunposition().
sun_rigth_ascension_calculation()
subroutine narp_module::sun_rigth_ascension_calculation (real(kind(1d0)), intent(in) apparent_sun_longitude, real(kind(1d0)), intent(in) corr_obliquity, real(kind(1d0)), intent(in) sun_geocentric_positionlatitude, real(kind(1d0)), intent(out) sun_rigth_ascension)
Definition at line 1008 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: apparent_sun_longitude
       REAL(KIND(1D0)), INTENT(in) :: corr_obliquity
       REAL(KIND(1D0)), INTENT(in) :: sun_geocentric_positionlatitude
       REAL(KIND(1D0)), INTENT(out) :: sun_rigth_ascension
       REAL(KIND(1D0)) :: argument_denominator
       REAL(KIND(1D0)) :: argument_numerator
       REAL(KIND(1D0)), PARAMETER       :: pi = 3.141592653589793d+0
       ! This function compute the sun rigth ascension.
       argument_numerator = (sin(apparent_sun_longitude*pi/180.0)*cos(corr_obliquity*pi/180.0)) - &
                            (tan(sun_geocentric_positionlatitude*pi/180.0)*sin(corr_obliquity*pi/180.0))
       argument_denominator = cos(apparent_sun_longitude*pi/180.0)
       sun_rigth_ascension = atan2(argument_numerator, argument_denominator)*180.0/pi
       ! Limit the range to [0,360];
       sun_rigth_ascension = set_to_range(sun_rigth_ascension)
References set_to_range().
Referenced by narp_cal_sunposition().
sun_topocentric_zenith_angle_calculate()
subroutine narp_module::sun_topocentric_zenith_angle_calculate (real(kind(1d0)), intent(in) locationlatitude, real(kind(1d0)), intent(in) topocentric_sun_positiondeclination, real(kind(1d0)), intent(in) topocentric_local_hour, real(kind(1d0)) sunazimuth, real(kind(1d0)) sunzenith)
Definition at line 1134 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: locationlatitude
       REAL(KIND(1D0)), INTENT(in) :: topocentric_local_hour
       REAL(KIND(1D0)), INTENT(in) :: topocentric_sun_positiondeclination
       REAL(KIND(1D0)) :: corr_elevation
       REAL(KIND(1D0)) :: apparent_elevation
       REAL(KIND(1D0)) :: argument
       REAL(KIND(1D0)) :: denominator
       REAL(KIND(1D0)) :: nominator
       REAL(KIND(1D0)) :: refraction_corr
       REAL(KIND(1D0)) :: sunazimuth
       REAL(KIND(1D0)) :: sunzenith
       REAL(KIND(1D0)), PARAMETER       :: pi = 3.141592653589793d+0
       ! This function compute the sun zenith angle, taking into account the
       ! atmospheric refraction. A default temperature of 283K and a
       ! default pressure of 1010 mbar are used.
       ! Topocentric elevation, without atmospheric refraction
       argument = (sin(locationlatitude*pi/180.0)*sin(topocentric_sun_positiondeclination*pi/180.0)) + &
            (cos(locationlatitude*pi/180.0)*cos(topocentric_sun_positiondeclination*pi/180.0)* &
            &cos(topocentric_local_hour*pi/180.0))
       corr_elevation = asin(argument)*180.0/pi
       ! Atmospheric refraction correction (in degrees)
       argument = corr_elevation + (10.3/(corr_elevation + 5.11))
       refraction_corr = 1.02/(60*tan(argument*pi/180.0))
       ! For exact pressure and temperature correction, use this,
       ! with P the pressure in mbar amd T the temperature in Kelvins:
       ! refraction_corr = (P/1010) * (283/T) * 1.02 / (60 * tan(argument * pi/180));
       ! Apparent elevation
       apparent_elevation = corr_elevation + refraction_corr
       sunzenith = 90.0 - apparent_elevation
       ! Topocentric azimuth angle. The +180 conversion is to pass from astronomer
       ! notation (westward from south) to navigation notation (eastward from
       ! north);
       nominator = sin(topocentric_local_hour*pi/180.0)
       denominator = (cos(topocentric_local_hour*pi/180.0)*sin(locationlatitude*pi/180.0)) - &
                     (tan(topocentric_sun_positiondeclination*pi/180.0)*cos(locationlatitude*pi/180.0))
       sunazimuth = (atan2(nominator, denominator)*180.0/pi) + 180.0
       ! Set the range to [0-360]
       sunazimuth = set_to_range(sunazimuth)
References set_to_range().
Referenced by narp_cal_sunposition().
topocentric_local_hour_calculate()
subroutine narp_module::topocentric_local_hour_calculate (real(kind(1d0)), intent(in) observer_local_hour, real(kind(1d0)), intent(in) topocentric_sun_positionrigth_ascension_parallax, real(kind(1d0)), intent(out) topocentric_local_hour)
Definition at line 1121 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: observer_local_hour
       REAL(KIND(1D0)), INTENT(out) :: topocentric_local_hour
       REAL(KIND(1D0)), INTENT(in) :: topocentric_sun_positionrigth_ascension_parallax
       ! This function compute the topocentric local jour angle in degrees
       topocentric_local_hour = observer_local_hour - topocentric_sun_positionrigth_ascension_parallax
Referenced by narp_cal_sunposition().
topocentric_sun_position_calculate()
subroutine narp_module::topocentric_sun_position_calculate (real(kind(1d0)) topocentric_sun_positionrigth_ascension, real(kind(1d0)) topocentric_sun_positionrigth_ascension_parallax, real(kind(1d0)) topocentric_sun_positiondeclination, real(kind(1d0)), intent(in) locationaltitude, real(kind(1d0)), intent(in) locationlatitude, real(kind(1d0)), intent(in) observer_local_hour, real(kind(1d0)), intent(in) sun_rigth_ascension, real(kind(1d0)), intent(in) sun_geocentric_declination, real(kind(1d0)), intent(in) earth_heliocentric_positionradius)
Definition at line 1064 of file suews_phys_narp.f95.
       IMPLICIT NONE
       REAL(KIND(1D0)), INTENT(in) :: earth_heliocentric_positionradius
       REAL(KIND(1D0)), INTENT(in) :: locationlatitude
       REAL(KIND(1D0)), INTENT(in) :: locationaltitude
       REAL(KIND(1D0)), INTENT(in) :: observer_local_hour
       REAL(KIND(1D0)), INTENT(in) :: sun_geocentric_declination
       REAL(KIND(1D0)), INTENT(in) :: sun_rigth_ascension
       REAL(KIND(1D0)) :: denominator
       REAL(KIND(1D0)) :: eq_horizontal_parallax
       REAL(KIND(1D0)) :: nominator
       REAL(KIND(1D0)) :: sun_rigth_ascension_parallax
       REAL(KIND(1D0)) :: topocentric_sun_positiondeclination
       REAL(KIND(1D0)) :: topocentric_sun_positionrigth_ascension
       REAL(KIND(1D0)) :: topocentric_sun_positionrigth_ascension_parallax
       REAL(KIND(1D0)) :: u
       REAL(KIND(1D0)) :: x
       REAL(KIND(1D0)) :: y
       REAL(KIND(1D0)), PARAMETER       :: pi = 3.141592653589793d+0
       ! topocentric_sun_positionrigth_ascension_parallax
       ! This function compute the sun position (rigth ascension and declination)
       ! with respect to the observer local position at the Earth surface.
       ! Equatorial horizontal parallax of the sun in degrees
       eq_horizontal_parallax = 8.794/(3600*earth_heliocentric_positionradius)
       ! Term u, used in the following calculations (in radians)
       u = atan(0.99664719*tan(locationlatitude*pi/180))
       ! Term x, used in the following calculations
       x = cos(u) + ((locationaltitude/6378140)*cos(locationaltitude*pi/180))
       ! Term y, used in the following calculations
       y = (0.99664719d+0*sin(u)) + ((locationaltitude/6378140)*sin(locationlatitude*pi/180))
       ! Parallax in the sun rigth ascension (in radians)
       nominator = -x*sin(eq_horizontal_parallax*pi/180.0)*sin(observer_local_hour*pi/180.0)
       denominator = cos(sun_geocentric_declination*pi/180.0) - &
                     (x*sin(eq_horizontal_parallax*pi/180.0)*cos(observer_local_hour*pi/180.0))
       sun_rigth_ascension_parallax = atan2(nominator, denominator)
       ! Conversion to degrees.
       topocentric_sun_positionrigth_ascension_parallax = sun_rigth_ascension_parallax*180.0/pi
       ! Topocentric sun rigth ascension (in degrees)
       topocentric_sun_positionrigth_ascension = sun_rigth_ascension + (sun_rigth_ascension_parallax*180.0/pi)
       ! Topocentric sun declination (in degrees)
       nominator = (sin(sun_geocentric_declination*pi/180.0) - (y*sin(eq_horizontal_parallax*pi/180.0)))&
                  & *cos(sun_rigth_ascension_parallax)
       denominator = cos(sun_geocentric_declination*pi/180.0) - (y*sin(eq_horizontal_parallax*pi/180.0))&
                    & *cos(observer_local_hour*pi/180.0)
       topocentric_sun_positiondeclination = atan2(nominator, denominator)*180.0/pi
Referenced by narp_cal_sunposition().
transmissivity()
real(kind(1d0)) function narp_module::transmissivity (real(kind(1d0)) Press_hPa, real(kind(1d0)) Temp_C_dew, real(kind(1d0)) G, real(kind(1d0)) zenith)
Definition at line 1354 of file suews_phys_narp.f95.
       ! bulk atmospheric transmissivity (Crawford and Duchon, 1999)
       ! P = pressure (hPa)
       ! Td = dewpoint (C)
       ! G parameter is empirical value from Smith 1966 (JAM)
       ! zenith in radians
       ! if zenith > 80 use the value for 80.
       REAL(KIND(1d0)) ::Press_hPa, TemP_C_dew, zenith, G, trans
       REAL(KIND(1d0))::m, TrTpg, u, Tw, Ta, cosZ
       REAL(KIND(1d0))::Tdf
       REAL(KIND(1D0)), PARAMETER   :: DEG2RAD = 0.017453292
       IF (zenith > 80.*deg2rad) THEN
          cosz = cos(80.*deg2rad)
       ELSE
          cosz = cos(zenith)
       ENDIF
       tdf = temp_c_dew*1.8 + 32. !celsius to fahrenheit
       !        Transmission coefficients
       m = 35*cosz/sqrt(1224.*cosz*cosz + 1)            !optical air mass at p=1013 mb
       !Rayleigh & permanent gases
       trtpg = 1.021 - 0.084*sqrt(m*(0.000949*press_hpa + 0.051)) !first two trans coeff
       u = exp(0.113 - log(g + 1) + 0.0393*tdf)             !precipitable water
       tw = 1 - 0.077*(u*m)**0.3             !vapor transmission coe3ff.
       ta = 0.935**m                       !4th trans coeff
       trans = trtpg*tw*ta                 !bulk atmospheric transmissivity
Referenced by narp().
wc_fraction()
real(kind(1d0)) function narp_module::wc_fraction (real(kind(1d0)), intent(in) RH, real(kind(1d0)), intent(in) Temp)
Definition at line 1249 of file suews_phys_narp.f95.
       ! Thomas Loridan, King's College London: June 2009
       ! Parameterisation of fraction water content using the relative humidity
       REAL(KIND(1d0)), INTENT(in)   :: RH      !Relative Humidity in %
       REAL(KIND(1d0)), INTENT(in)   :: Temp    !Temperature in degre C
       REAL(KIND(1d0))              :: FWC     !Fraction water content between 0 and 1
       REAL(KIND(1d0))              :: A, B    !Parameters in the expo
       !Parameters
       !A=0.078
       !B=0.026
       a = 0.185
       b = 0.00019*temp + 0.015
       !FWC parameterization
       fwc = a*(exp(b*rh) - 1)
       IF (fwc > 1.) fwc = 1.
       IF (fwc < 0.) fwc = 0.
Referenced by narp().