SUEWS: moist Module Reference
moist Module Reference
Variables
real(kind(1d0)) avcp
real(kind(1d0)) dens_dry
real(kind(1d0)) dq
real(kind(1d0)) ea_hpa
real(kind(1d0)) es_hpa
real(kind(1d0)) lv_j_kg
real(kind(1d0)) tlv
real(kind(1d0)) psyc_hpa
real(kind(1d0)) psycice_hpa
real(kind(1d0)) s_pa
real(kind(1d0)) s_hpa
real(kind(1d0)) sice_hpa
real(kind(1d0)) vpd_hpa
real(kind(1d0)) vpd_pa
real(kind(1d0)) waterdens = 999.8395
Variable Documentation
avcp
real(kind(1d0)) moist::avcp
Definition at line 1371 of file suews_ctrl_const.f95.
    REAL(KIND(1d0))::avcp, &        !Specific heat capacity
                      dens_dry, &    !Dry air density kg m-3
                      dq, &          !Specific humidity deficit
                      Ea_hPa, &      !Water vapour pressure in hPa
                      Es_hPa, &      !Saturation vapour pressure in hPa
                      lv_J_kg, &     !Latent heat of vaporization in [J kg-1]
                      tlv, &         !Latent heat of vaporization per timestep
                      ![J kg-1 s-1] (tlv=lv_J_kg/tstep_real)
                      psyc_hpa, &    !Psychometric constant in hPa
                      psycice_hpa, & !Psychometric constant in hPa for snow
                      s_pa, &        !Vapour pressure versus temperature slope in Pa
                      s_hpa, &       !Vapour pressure versus temperature slope in hPa
                      sice_hpa, &    !Vapour pressure versus temperature slope in hPa above ice/snow
                      vpd_hpa, &     !Vapour pressure deficit in hPa
                      vpd_pa, &      !Vapour pressure deficit in Pa
                      waterdens = 999.8395 !Density of water in 0 cel deg
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
dens_dry
real(kind(1d0)) moist::dens_dry
Definition at line 1371 of file suews_ctrl_const.f95.
dq
real(kind(1d0)) moist::dq
Definition at line 1371 of file suews_ctrl_const.f95.
ea_hpa
real(kind(1d0)) moist::ea_hpa
Definition at line 1371 of file suews_ctrl_const.f95.
es_hpa
real(kind(1d0)) moist::es_hpa
Definition at line 1371 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), bluews_module::cbl_initial(), and bluews_module::nbl().
lv_j_kg
real(kind(1d0)) moist::lv_j_kg
Definition at line 1371 of file suews_ctrl_const.f95.
Referenced by bluews_module::cbl(), and bluews_module::nbl().
psyc_hpa
real(kind(1d0)) moist::psyc_hpa
Definition at line 1371 of file suews_ctrl_const.f95.
psycice_hpa
real(kind(1d0)) moist::psycice_hpa
Definition at line 1371 of file suews_ctrl_const.f95.
s_hpa
real(kind(1d0)) moist::s_hpa
Definition at line 1371 of file suews_ctrl_const.f95.
s_pa
real(kind(1d0)) moist::s_pa
Definition at line 1371 of file suews_ctrl_const.f95.
sice_hpa
real(kind(1d0)) moist::sice_hpa
Definition at line 1371 of file suews_ctrl_const.f95.
tlv
real(kind(1d0)) moist::tlv
Definition at line 1371 of file suews_ctrl_const.f95.
vpd_hpa
real(kind(1d0)) moist::vpd_hpa
Definition at line 1371 of file suews_ctrl_const.f95.
vpd_pa
real(kind(1d0)) moist::vpd_pa
Definition at line 1371 of file suews_ctrl_const.f95.
waterdens
real(kind(1d0)) moist::waterdens = 999.8395
Definition at line 1371 of file suews_ctrl_const.f95.