SUEWS: snowmod Module Reference
snowmod Module Reference
Variables
real(kind(1d0)) adjmeltfact
real(kind(1d0)) snowfallcum
real(kind(1d0)) fwh
real(kind(1d0)) lvs_j_kg
real(kind(1d0)) mwh
real(kind(1d0)) mwstore
real(kind(1d0)) preciplimit
real(kind(1d0)) preciplimitalb
real(kind(1d0)) qm
real(kind(1d0)) qmfreez
real(kind(1d0)) qmrain
real(kind(1d0)) qn1_snow
real(kind(1d0)) qn1_nosnow
real(kind(1d0)) radmeltfact
real(kind(1d0)) snowalb
real(kind(1d0)) snowalbmin
real(kind(1d0)) snowalbmax
real(kind(1d0)) snowdensmin
real(kind(1d0)) snowdensmax
real(kind(1d0)) snowlimbldg
real(kind(1d0)) snowlimpaved
real(kind(1d0)) swe
real(kind(1d0)) tau_a
real(kind(1d0)) tau_f
real(kind(1d0)) tau_r
real(kind(1d0)) tempmeltfact
real(kind(1d0)) volday
real(kind(1d0)) zf
real(kind(1d0)) waterholdcapfrac
real(kind(1d0)) crwmin
real(kind(1d0)) crwmax
real(kind(1d0)), dimension(2) snowremoval = 0
real(kind(1d0)), dimension(0:23, 2) snowprof_24hr
integer snowfractionchoice = 2
Variable Documentation
adjmeltfact
real(kind(1d0)) snowmod::adjmeltfact
Definition at line 1242 of file suews_ctrl_const.f95.
    REAL(KIND(1D0))::AdjMeltFact, &    !Factor between melt and freezing factors
                      SnowfallCum, &        !Cumulative snowfall
                      fwh, &              !Weighted freezing water
                      lvS_J_kg, &         !Latent heat of sublimation in J/kg
                      mwh, &              !Weighted hourly water melt
                      MwStore, &              !Meltwater storage
                      PrecipLimit, &      !Temperature limit when precipitation occurs as snow
                      PrecipLimitAlb, &   !Precipitation limit for albedo change (in mm)
                      Qm, &               !Snow melt associated heat flux
                      QmFreez, &          !Energy released in freezing of meltwater or surface state
                      QmRain, &
                      qn1_snow, &         !Net all-wave radiation of SnowPack
                      qn1_nosnow, &       !Same for the snow free surface
                      RadMeltFact, &      !Radiation melt factor
                      SnowAlb, &          !Snow albedo
                      SnowAlbMin, &       !Minimum snow albedo
                      SnowAlbMax, &       !Maximum snow albedo
                      SnowDensMin, &      !Minimum density of snow
                      SnowDensMax, &      !Maximum density of snow
                      SnowLimBldg, &     !Snow removal limits for roofs in mm)
                      SnowLimPaved, &     !Snow removal limits for paved surfaces in mm)
                      swe, &        !Weighted snow water equivalent (in mm)
                      tau_a, &            !Time constans related to albedo change
                      tau_f, &
                      tau_r, &            !Time constant for density increase.
                      TempMeltFact, &     !Temperature melt factor
                      volDay, &           !Volume of the melted water per day
                      zf, &
                      WaterHoldCapFrac, & !Water holding capacity factor
                      CRWmin, & !Free water holding capacity of deep SnowPack
                      CRWmax  !Free water holding capacity of shallow SnowPack
crwmax
real(kind(1d0)) snowmod::crwmax
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by checkinitial(), suews_calculations(), and suews_translate().
crwmin
real(kind(1d0)) snowmod::crwmin
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
fwh
real(kind(1d0)) snowmod::fwh
Definition at line 1242 of file suews_ctrl_const.f95.
lvs_j_kg
real(kind(1d0)) snowmod::lvs_j_kg
Definition at line 1242 of file suews_ctrl_const.f95.
mwh
real(kind(1d0)) snowmod::mwh
Definition at line 1242 of file suews_ctrl_const.f95.
mwstore
real(kind(1d0)) snowmod::mwstore
Definition at line 1242 of file suews_ctrl_const.f95.
preciplimit
real(kind(1d0)) snowmod::preciplimit
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
preciplimitalb
real(kind(1d0)) snowmod::preciplimitalb
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
qm
real(kind(1d0)) snowmod::qm
Definition at line 1242 of file suews_ctrl_const.f95.
qmfreez
real(kind(1d0)) snowmod::qmfreez
Definition at line 1242 of file suews_ctrl_const.f95.
qmrain
real(kind(1d0)) snowmod::qmrain
Definition at line 1242 of file suews_ctrl_const.f95.
qn1_nosnow
real(kind(1d0)) snowmod::qn1_nosnow
Definition at line 1242 of file suews_ctrl_const.f95.
qn1_snow
real(kind(1d0)) snowmod::qn1_snow
Definition at line 1242 of file suews_ctrl_const.f95.
radmeltfact
real(kind(1d0)) snowmod::radmeltfact
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowalb
real(kind(1d0)) snowmod::snowalb
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by nextinitial(), suews_calculations(), suews_translate(), and suews_translateback().
snowalbmax
real(kind(1d0)) snowmod::snowalbmax
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowalbmin
real(kind(1d0)) snowmod::snowalbmin
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowdensmax
real(kind(1d0)) snowmod::snowdensmax
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowdensmin
real(kind(1d0)) snowmod::snowdensmin
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowfallcum
real(kind(1d0)) snowmod::snowfallcum
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), suews_translate(), and suews_translateback().
snowfractionchoice
integer snowmod::snowfractionchoice = 2
Definition at line 1277 of file suews_ctrl_const.f95.
    INTEGER::SnowFractionChoice = 2   !Choice how fraction of snow is calculated
snowlimbldg
real(kind(1d0)) snowmod::snowlimbldg
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowlimpaved
real(kind(1d0)) snowmod::snowlimpaved
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
snowprof_24hr
real(kind(1d0)), dimension(0:23, 2) snowmod::snowprof_24hr
Definition at line 1275 of file suews_ctrl_const.f95.
    REAL(KIND(1d0)), DIMENSION(0:23, 2):: SnowProf_24hr  ! Timing of snow removal (0 or 1) Hourly, WD/WE
Referenced by suews_calculations(), and suews_translate().
snowremoval
real(kind(1d0)), dimension(2) snowmod::snowremoval = 0
Definition at line 1274 of file suews_ctrl_const.f95.
    REAL(KIND(1D0)), DIMENSION(2)::  SnowRemoval = 0 ! Removal of snow in mm
swe
real(kind(1d0)) snowmod::swe
Definition at line 1242 of file suews_ctrl_const.f95.
tau_a
real(kind(1d0)) snowmod::tau_a
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
tau_f
real(kind(1d0)) snowmod::tau_f
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
tau_r
real(kind(1d0)) snowmod::tau_r
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
tempmeltfact
real(kind(1d0)) snowmod::tempmeltfact
Definition at line 1242 of file suews_ctrl_const.f95.
Referenced by suews_calculations(), and suews_translate().
volday
real(kind(1d0)) snowmod::volday
Definition at line 1242 of file suews_ctrl_const.f95.
waterholdcapfrac
real(kind(1d0)) snowmod::waterholdcapfrac
Definition at line 1242 of file suews_ctrl_const.f95.
zf
real(kind(1d0)) snowmod::zf
Definition at line 1242 of file suews_ctrl_const.f95.