SUEWS: mod_timedelta::timedelta Interface Reference
mod_timedelta::timedelta Interface Reference
Public Member Functions
procedure, pass, public getdays
procedure, pass, public gethours
procedure, pass, public getminutes
procedure, pass, public getseconds
procedure, pass, public getmilliseconds
procedure, public total_seconds
Private Member Functions
procedure, private timedelta_plus_timedelta
procedure, private timedelta_minus_timedelta
procedure, private unary_minus_timedelta
procedure, private eq
procedure, private neq
procedure, private gt
procedure, private ge
procedure, private lt
procedure, private le
generic operator => timedelta_plus_timedelta
generic operator => timedelta_minus_timedelta, unary_minus_timedelta
generic operator => eq
generic operator => neq
generic operator => gt
generic operator => ge
generic operator => lt
generic operator => le
pure elemental type(timedelta) function timedelta_constructor (days, hours, minutes, seconds, milliseconds)
Private Attributes
integer days = 0
integer hours = 0
integer minutes = 0
integer seconds = 0
integer milliseconds = 0
Detailed Description
Definition at line 166 of file suews_util_datetime.f95.
Member Function/Subroutine Documentation
eq()
procedure, private mod_timedelta::timedelta::eq () private
Definition at line 195 of file suews_util_datetime.f95.
ge()
procedure, private mod_timedelta::timedelta::ge () private
Definition at line 198 of file suews_util_datetime.f95.
getdays()
procedure, pass, public mod_timedelta::timedelta::getdays ()
Definition at line 182 of file suews_util_datetime.f95.
gethours()
procedure, pass, public mod_timedelta::timedelta::gethours ()
Definition at line 183 of file suews_util_datetime.f95.
getmilliseconds()
procedure, pass, public mod_timedelta::timedelta::getmilliseconds ()
Definition at line 186 of file suews_util_datetime.f95.
getminutes()
procedure, pass, public mod_timedelta::timedelta::getminutes ()
Definition at line 184 of file suews_util_datetime.f95.
getseconds()
procedure, pass, public mod_timedelta::timedelta::getseconds ()
Definition at line 185 of file suews_util_datetime.f95.
gt()
procedure, private mod_timedelta::timedelta::gt () private
Definition at line 197 of file suews_util_datetime.f95.
le()
procedure, private mod_timedelta::timedelta::le () private
Definition at line 200 of file suews_util_datetime.f95.
lt()
procedure, private mod_timedelta::timedelta::lt () private
Definition at line 199 of file suews_util_datetime.f95.
neq()
procedure, private mod_timedelta::timedelta::neq () private
Definition at line 196 of file suews_util_datetime.f95.
operator() [1/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 205 of file suews_util_datetime.f95.
References mod_timedelta::eq().
operator() [2/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 208 of file suews_util_datetime.f95.
References mod_timedelta::ge().
operator() [3/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 207 of file suews_util_datetime.f95.
References mod_timedelta::gt().
operator() [4/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 210 of file suews_util_datetime.f95.
References mod_timedelta::le(), and mod_timedelta::timedelta_constructor().
operator() [5/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 209 of file suews_util_datetime.f95.
References mod_timedelta::lt().
operator() [6/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 206 of file suews_util_datetime.f95.
References mod_timedelta::neq().
operator() [7/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 203 of file suews_util_datetime.f95.
References mod_timedelta::timedelta_minus_timedelta(), and mod_timedelta::unary_minus_timedelta().
operator() [8/8]
generic mod_timedelta::timedelta::operator () private
Definition at line 202 of file suews_util_datetime.f95.
References mod_timedelta::timedelta_plus_timedelta().
timedelta_constructor()
pure elemental type(timedelta) function mod_timedelta::timedelta::timedelta_constructor (integer, intent(in), optional days, integer, intent(in), optional hours, integer, intent(in), optional minutes, integer, intent(in), optional seconds, integer, intent(in), optional milliseconds) private
Definition at line 223 of file suews_util_datetime.f95.
       !! Constructor function for the `timedelta` class.
       integer, intent(in), optional :: days         !! number of days
       integer, intent(in), optional :: hours        !! number of hours
       integer, intent(in), optional :: minutes      !! number of minutes
       integer, intent(in), optional :: seconds      !! number of seconds
       integer, intent(in), optional :: milliseconds !! number of milliseconds
       if (present(days)) then
          timedelta_constructor%days = days
       else
          timedelta_constructor%days = 0
       endif
       if (present(hours)) then
          timedelta_constructor%hours = hours
       else
          timedelta_constructor%hours = 0
       endif
       if (present(minutes)) then
          timedelta_constructor%minutes = minutes
       else
          timedelta_constructor%minutes = 0
       endif
       if (present(seconds)) then
          timedelta_constructor%seconds = seconds
       else
          timedelta_constructor%seconds = 0
       endif
       if (present(milliseconds)) then
          timedelta_constructor%milliseconds = milliseconds
       else
          timedelta_constructor%milliseconds = 0
       endif
timedelta_minus_timedelta()
procedure, private mod_timedelta::timedelta::timedelta_minus_timedelta () private
Definition at line 193 of file suews_util_datetime.f95.
timedelta_plus_timedelta()
procedure, private mod_timedelta::timedelta::timedelta_plus_timedelta () private
Definition at line 192 of file suews_util_datetime.f95.
total_seconds()
procedure, public mod_timedelta::timedelta::total_seconds ()
Definition at line 189 of file suews_util_datetime.f95.
unary_minus_timedelta()
procedure, private mod_timedelta::timedelta::unary_minus_timedelta () private
Definition at line 194 of file suews_util_datetime.f95.
Member Data Documentation
days
integer mod_timedelta::timedelta::days = 0 private
Definition at line 173 of file suews_util_datetime.f95.
       integer :: days = 0 !! number of days
hours
integer mod_timedelta::timedelta::hours = 0 private
Definition at line 174 of file suews_util_datetime.f95.
       integer :: hours = 0 !! number of hours
milliseconds
integer mod_timedelta::timedelta::milliseconds = 0 private
Definition at line 177 of file suews_util_datetime.f95.
       integer :: milliseconds = 0 !! number of milliseconds
minutes
integer mod_timedelta::timedelta::minutes = 0 private
Definition at line 175 of file suews_util_datetime.f95.
       integer :: minutes = 0 !! number of minutes
seconds
integer mod_timedelta::timedelta::seconds = 0 private
Definition at line 176 of file suews_util_datetime.f95.
       integer :: seconds = 0 !! number of seconds
The documentation for this interface was generated from the following file:
/Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_util_datetime.f95