SUEWS: mod_datetime::datetime Interface Reference
mod_datetime::datetime Interface Reference
Public Member Functions
procedure, pass, public getyear
procedure, pass, public getmonth
procedure, pass, public getday
procedure, pass, public gethour
procedure, pass, public getminute
procedure, pass, public getsecond
procedure, pass, public getmillisecond
procedure, pass, public gettz
procedure, pass, public isocalendar
procedure, pass, public isoformat
procedure, pass, public isvalid
procedure, nopass, public now
procedure, pass, public secondssinceepoch
procedure, pass, public strftime
procedure, pass, public tm
procedure, pass, public tzoffset
procedure, pass, public utc
procedure, pass, public weekday
procedure, pass, public isoweekday
procedure, pass, public weekdaylong
procedure, pass, public isoweekdaylong
procedure, pass, public weekdayshort
procedure, pass, public isoweekdayshort
procedure, pass, public yearday
Private Member Functions
procedure, pass, private addmilliseconds
procedure, pass, private addseconds
procedure, pass, private addminutes
procedure, pass, private addhours
procedure, pass, private adddays
procedure, pass, private datetime_plus_timedelta
procedure, pass, private timedelta_plus_datetime
procedure, pass, private datetime_minus_datetime
procedure, pass, private datetime_minus_timedelta
procedure, pass, private eq
procedure, pass, private neq
procedure, pass, private gt
procedure, pass, private ge
procedure, pass, private lt
procedure, pass, private le
generic operator => datetime_plus_timedelta, timedelta_plus_datetime
generic operator => datetime_minus_datetime, datetime_minus_timedelta
generic operator => eq
generic operator => neq
generic operator => gt
generic operator => ge
generic operator => lt
generic operator => le
pure elemental type(datetime) function datetime_constructor (year, month, day, hour, minute, second, millisecond, tz)
Private Attributes
integer year = 1
integer month = 1
integer day = 1
integer hour = 0
integer minute = 0
integer second = 0
integer millisecond = 0
real(kind=real64) tz = 0
Detailed Description
Definition at line 475 of file suews_util_datetime.f95.
Member Function/Subroutine Documentation
adddays()
procedure, pass, private mod_datetime::datetime::adddays () private
Definition at line 526 of file suews_util_datetime.f95.
addhours()
procedure, pass, private mod_datetime::datetime::addhours () private
Definition at line 525 of file suews_util_datetime.f95.
addmilliseconds()
procedure, pass, private mod_datetime::datetime::addmilliseconds () private
Definition at line 522 of file suews_util_datetime.f95.
addminutes()
procedure, pass, private mod_datetime::datetime::addminutes () private
Definition at line 524 of file suews_util_datetime.f95.
addseconds()
procedure, pass, private mod_datetime::datetime::addseconds () private
Definition at line 523 of file suews_util_datetime.f95.
datetime_constructor()
pure elemental type(datetime) function mod_datetime::datetime::datetime_constructor (integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, real(kind=real64), intent(in), optional tz) private
Definition at line 562 of file suews_util_datetime.f95.
       !! Constructor function for the `datetime` class.
       integer, intent(in), optional :: year        !! year
       integer, intent(in), optional :: month       !! month
       integer, intent(in), optional :: day         !! day
       integer, intent(in), optional :: hour        !! hour
       integer, intent(in), optional :: minute      !! minute
       integer, intent(in), optional :: second      !! second
       integer, intent(in), optional :: millisecond !! millisecond
       real(kind=real64), intent(in), optional :: tz          !! timezone offset in hours
       if (present(year)) then
          datetime_constructor%year = year
       else
          datetime_constructor%year = 1
       endif
       if (present(month)) then
          datetime_constructor%month = month
       else
          datetime_constructor%month = 1
       endif
       if (present(day)) then
          datetime_constructor%day = day
       else
          datetime_constructor%day = 1
       endif
       if (present(hour)) then
          datetime_constructor%hour = hour
       else
          datetime_constructor%hour = 0
       endif
       if (present(minute)) then
          datetime_constructor%minute = minute
       else
          datetime_constructor%minute = 0
       endif
       if (present(second)) then
          datetime_constructor%second = second
       else
          datetime_constructor%second = 0
       endif
       if (present(millisecond)) then
          datetime_constructor%millisecond = millisecond
       else
          datetime_constructor%millisecond = 0
       endif
       if (present(tz)) then
          datetime_constructor%tz = tz
       else
          datetime_constructor%tz = 0
       endif
datetime_minus_datetime()
procedure, pass, private mod_datetime::datetime::datetime_minus_datetime () private
Definition at line 531 of file suews_util_datetime.f95.
datetime_minus_timedelta()
procedure, pass, private mod_datetime::datetime::datetime_minus_timedelta () private
Definition at line 532 of file suews_util_datetime.f95.
datetime_plus_timedelta()
procedure, pass, private mod_datetime::datetime::datetime_plus_timedelta () private
Definition at line 529 of file suews_util_datetime.f95.
eq()
procedure, pass, private mod_datetime::datetime::eq () private
Definition at line 533 of file suews_util_datetime.f95.
ge()
procedure, pass, private mod_datetime::datetime::ge () private
Definition at line 536 of file suews_util_datetime.f95.
getday()
procedure, pass, public mod_datetime::datetime::getday ()
Definition at line 496 of file suews_util_datetime.f95.
gethour()
procedure, pass, public mod_datetime::datetime::gethour ()
Definition at line 497 of file suews_util_datetime.f95.
getmillisecond()
procedure, pass, public mod_datetime::datetime::getmillisecond ()
Definition at line 500 of file suews_util_datetime.f95.
getminute()
procedure, pass, public mod_datetime::datetime::getminute ()
Definition at line 498 of file suews_util_datetime.f95.
getmonth()
procedure, pass, public mod_datetime::datetime::getmonth ()
Definition at line 495 of file suews_util_datetime.f95.
getsecond()
procedure, pass, public mod_datetime::datetime::getsecond ()
Definition at line 499 of file suews_util_datetime.f95.
gettz()
procedure, pass, public mod_datetime::datetime::gettz ()
Definition at line 501 of file suews_util_datetime.f95.
getyear()
procedure, pass, public mod_datetime::datetime::getyear ()
Definition at line 494 of file suews_util_datetime.f95.
gt()
procedure, pass, private mod_datetime::datetime::gt () private
Definition at line 535 of file suews_util_datetime.f95.
isocalendar()
procedure, pass, public mod_datetime::datetime::isocalendar ()
Definition at line 504 of file suews_util_datetime.f95.
isoformat()
procedure, pass, public mod_datetime::datetime::isoformat ()
Definition at line 505 of file suews_util_datetime.f95.
isoweekday()
procedure, pass, public mod_datetime::datetime::isoweekday ()
Definition at line 514 of file suews_util_datetime.f95.
isoweekdaylong()
procedure, pass, public mod_datetime::datetime::isoweekdaylong ()
Definition at line 516 of file suews_util_datetime.f95.
isoweekdayshort()
procedure, pass, public mod_datetime::datetime::isoweekdayshort ()
Definition at line 518 of file suews_util_datetime.f95.
isvalid()
procedure, pass, public mod_datetime::datetime::isvalid ()
Definition at line 506 of file suews_util_datetime.f95.
le()
procedure, pass, private mod_datetime::datetime::le () private
Definition at line 538 of file suews_util_datetime.f95.
lt()
procedure, pass, private mod_datetime::datetime::lt () private
Definition at line 537 of file suews_util_datetime.f95.
neq()
procedure, pass, private mod_datetime::datetime::neq () private
Definition at line 534 of file suews_util_datetime.f95.
now()
procedure, nopass, public mod_datetime::datetime::now ()
Definition at line 507 of file suews_util_datetime.f95.
operator() [1/8]
generic mod_datetime::datetime::operator () private
Definition at line 542 of file suews_util_datetime.f95.
References mod_datetime::datetime_minus_datetime(), and mod_datetime::datetime_minus_timedelta().
operator() [2/8]
generic mod_datetime::datetime::operator () private
Definition at line 540 of file suews_util_datetime.f95.
References mod_datetime::datetime_plus_timedelta(), and mod_datetime::timedelta_plus_datetime().
operator() [3/8]
generic mod_datetime::datetime::operator () private
Definition at line 544 of file suews_util_datetime.f95.
References mod_datetime::eq().
operator() [4/8]
generic mod_datetime::datetime::operator () private
Definition at line 547 of file suews_util_datetime.f95.
References mod_datetime::ge().
operator() [5/8]
generic mod_datetime::datetime::operator () private
Definition at line 546 of file suews_util_datetime.f95.
References mod_datetime::gt().
operator() [6/8]
generic mod_datetime::datetime::operator () private
Definition at line 549 of file suews_util_datetime.f95.
References mod_datetime::datetime_constructor(), and mod_datetime::le().
operator() [7/8]
generic mod_datetime::datetime::operator () private
Definition at line 548 of file suews_util_datetime.f95.
References mod_datetime::lt().
operator() [8/8]
generic mod_datetime::datetime::operator () private
Definition at line 545 of file suews_util_datetime.f95.
References mod_datetime::neq().
secondssinceepoch()
procedure, pass, public mod_datetime::datetime::secondssinceepoch ()
Definition at line 508 of file suews_util_datetime.f95.
strftime()
procedure, pass, public mod_datetime::datetime::strftime ()
Definition at line 509 of file suews_util_datetime.f95.
timedelta_plus_datetime()
procedure, pass, private mod_datetime::datetime::timedelta_plus_datetime () private
Definition at line 530 of file suews_util_datetime.f95.
tm()
procedure, pass, public mod_datetime::datetime::tm ()
Definition at line 510 of file suews_util_datetime.f95.
tzoffset()
procedure, pass, public mod_datetime::datetime::tzoffset ()
Definition at line 511 of file suews_util_datetime.f95.
utc()
procedure, pass, public mod_datetime::datetime::utc ()
Definition at line 512 of file suews_util_datetime.f95.
weekday()
procedure, pass, public mod_datetime::datetime::weekday ()
Definition at line 513 of file suews_util_datetime.f95.
weekdaylong()
procedure, pass, public mod_datetime::datetime::weekdaylong ()
Definition at line 515 of file suews_util_datetime.f95.
weekdayshort()
procedure, pass, public mod_datetime::datetime::weekdayshort ()
Definition at line 517 of file suews_util_datetime.f95.
yearday()
procedure, pass, public mod_datetime::datetime::yearday ()
Definition at line 519 of file suews_util_datetime.f95.
Member Data Documentation
day
integer mod_datetime::datetime::day = 1 private
Definition at line 483 of file suews_util_datetime.f95.
       integer :: day = 1 !! day in month [1-31]
hour
integer mod_datetime::datetime::hour = 0 private
Definition at line 484 of file suews_util_datetime.f95.
       integer :: hour = 0 !! hour in day [0-23]
millisecond
integer mod_datetime::datetime::millisecond = 0 private
Definition at line 487 of file suews_util_datetime.f95.
       integer :: millisecond = 0 !! milliseconds in second [0-999]
minute
integer mod_datetime::datetime::minute = 0 private
Definition at line 485 of file suews_util_datetime.f95.
       integer :: minute = 0 !! minute in hour [0-59]
month
integer mod_datetime::datetime::month = 1 private
Definition at line 482 of file suews_util_datetime.f95.
       integer :: month = 1 !! month in year [1-12]
second
integer mod_datetime::datetime::second = 0 private
Definition at line 486 of file suews_util_datetime.f95.
       integer :: second = 0 !! second in minute [0-59]
tz
real(kind=real64) mod_datetime::datetime::tz = 0 private
Definition at line 489 of file suews_util_datetime.f95.
       real(kind=real64) :: tz = 0 !! timezone offset from UTC [hours]
year
integer mod_datetime::datetime::year = 1 private
Definition at line 481 of file suews_util_datetime.f95.
       integer :: year = 1 !! year [1-HUGE(year)]
The documentation for this interface was generated from the following file:
/Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_util_datetime.f95