SUEWS: /Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_phys_RSLwind.f95 File Reference
suews_phys_RSLwind.f95 File Reference
Functions/Subroutines
subroutine windprofile (UStar, L_MOD, sfr, Zh, planF, StabilityMethod, zarray, dataoutLineURSL)
Function/Subroutine Documentation
windprofile()
subroutine windprofile (real(kind(1d0)), intent(in) UStar, real(kind(1d0)), intent(in) L_MOD, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), intent(in) Zh, real(kind(1d0)), intent(in) planF, integer, intent(in) StabilityMethod, real(kind(1d0)), dimension(nz), intent(out) zarray, real(kind(1d0)), dimension(nz), intent(out) dataoutLineURSL)
Definition at line 4 of file suews_phys_RSLwind.f95.
    !-----------------------------------------------------
    ! calculates windprofiles using MOST with a RSL-correction
    ! based on Harman & Finnigan 2007
    !
    ! last modified by:
    ! NT 03/2019
    !
    !-----------------------------------------------------
    USE atmmoiststab_module, ONLY: stab_lumps, stab_fn_mom, stab_phi_mom
    IMPLICIT NONE
    INTEGER, PARAMETER:: nsurf = 7 ! number of surface types
    INTEGER, PARAMETER:: BldgSurf = 2
    INTEGER, PARAMETER:: ConifSurf = 3
    INTEGER, PARAMETER:: DecidSurf = 4
    REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in) ::sfr! surface fractions
    REAL(KIND(1d0)), INTENT(in):: UStar ! Friction velocity [m s-1]
    REAL(KIND(1d0)), INTENT(in):: L_MOD  ! Obukhov length [m]
    REAL(KIND(1d0)), INTENT(in):: Zh    ! Mean building height [m]
    REAL(KIND(1d0)), INTENT(in):: planF ! Frontal area index [-]
    INTEGER, INTENT(in)::StabilityMethod
    REAL(KIND(1d0)), PARAMETER:: cd_tree = 1.2, & ! drag coefficient tree canopy !!!!needs adjusting!!!
                                 a_tree = 0.05, & ! the foliage area per unit volume !!!!needs adjusting!!!
                                 kappa = 0.40, &! von karman constant
                                 beta_n = 0.40, &  ! H&F beta coefficient in neutral conditions from Theeuwes et al., 2019 BLM
                                 pi = 4.*atan(1.0), &
                                 a1 = 4., a2 = -0.1, a3 = 1.5, a4 = -1. ! constraints to determine beta
    INTEGER, PARAMETER :: nz = 30   ! number of levels 10 levels in canopy plus 20 (3 x Zh) above the canopy
    REAL(KIND(1d0)), INTENT(out), DIMENSION(nz):: zarray ! Height array
    REAL(KIND(1d0)), INTENT(out), DIMENSION(nz):: dataoutLineURSL ! Wind speed array
    REAL(KIND(1d0)), DIMENSION(nz)::dif, psihat_z
    REAL(KIND(1d0)):: zd, & ! displacement height
                      Lc_build, Lc_tree, Lc, & ! canopy drag length scale
                      dz, & ! height steps
                      phim, psimz, psimZh, psimz0, phi_hatmZh, phimzp, phimz, &  ! stability function for momentum
                      betaHF, betaNL, beta, betaN2, &  ! beta coefficient from Harman 2012
                      elm, & ! mixing length
                      xx1, xx1_2, err, z01, dphi, &  ! dummy variables for stability functions
                      z0, &  ! roughness length from H&F
                      cm, c2 ! H&F'07 'constants'
    INTEGER :: I, z, it, idx_can
    ! Start setting up the parameters
    ! calculate Lc for tree grid fraction using eq 1 H&F'07 and rest of grid using C&B'04
    lc_build = (1.-sfr(bldgsurf))/planf*zh  ! Coceal and Belcher 2004 assuming Cd = 2
    lc_tree = 1./(cd_tree*a_tree)
    lc = (1.-(sfr(bldgsurf) + sfr(conifsurf) + sfr(conifsurf)))/planf*zh
    IF ((3.*zh) < 10.) THEN
       dz = 1./3.      ! if canopy height is small use steps of 0.33333 m to get to 10 m
       zarray = (/(i, i=1, nz)/)*dz
    ELSE
       dz = zh/10.
       zarray = (/(i, i=1, nz)/)*dz
    ENDIF
    DO z = 1, nz
       dif(z) = abs(zarray(z) - zh)
    ENDDO
    idx_can = minloc(dif, dim=1)
    phim = stab_phi_mom(stabilitymethod, lc/l_mod, lc/l_mod)
    ! betaN for trees found to be 0.3 and for urban 0.4 linearly interpolate between the two using surface fractions
    betan2 = 0.30 + (1.-sfr(conifsurf) - sfr(conifsurf))*0.1
    betahf = betan2/phim
    betanl = (kappa/2.)/phim
    IF (lc/l_mod > a2) THEN
       beta = betahf
    ELSE
       beta = betanl + ((betahf - betanl)/(1.+a1*abs(lc/l_mod - a2)**a3))
    ENDIF
    IF (beta > 0.5) THEN
       beta = 0.5
    ENDIF
    zd = zh - (beta**2.)*lc
    elm = 2.*beta**3*lc
    ! start calculations for above roof height
    ! start with stability at canopy top for z0 and phihat
    psimzh = stab_fn_mom(stabilitymethod, (zh - zd)/l_mod, (zh - zd)/l_mod)
    ! calculate phihatM according to H&F '07
    xx1 = stab_phi_mom(stabilitymethod, (zh - zd)/l_mod, (zh - zd)/l_mod)
    xx1_2 = stab_phi_mom(stabilitymethod, (zh - zd + 1.)/l_mod, (zh - zd + 1.)/l_mod)
    phi_hatmzh = kappa/(2.*beta*xx1)
    dphi = xx1_2 - xx1
    IF (phi_hatmzh > 1.) THEN
       c2 = 0.5 ! more stable but less correct
    ELSE
       c2 = (kappa*(3.-(2.*beta**2.*lc/xx1*dphi)))/(2.*beta*xx1 - kappa)  ! if very unstable this might cause some high values of psihat_z
    ENDIF
    cm = (1.-phi_hatmzh)*exp(c2/2.)
    psihat_z = 0.*zarray
    DO z = idx_can, nz - 1
       phimz = stab_phi_mom(stabilitymethod, (zarray(z) - zh + zd)/l_mod, (zarray(z) - zh + zd)/l_mod)
       phimzp = stab_phi_mom(stabilitymethod, (zarray(z + 1) - zh + zd)/l_mod, (zarray(z + 1) - zh + zd)/l_mod)
       psihat_z(z) = psihat_z(z + 1) + dz/2.*phimzp*(cm*exp(-1.*c2*beta*(zarray(z + 1) - zh + zd)/elm)) &  !Taylor's approximation for integral
                     /(zarray(z + 1) - zh + zd)
       psihat_z(z) = psihat_z(z) + dz/2.*phimz*(cm*exp(-1.*c2*beta*(zarray(z) - zh + zd)/elm)) &
                     /(zarray(z) - zh + zd)
    ENDDO
    ! calculate z0 iteratively
    z0 = 0.5  !first guess
    err = 10.
    it = 1
    DO WHILE ((err > 0.001) .AND. (it < 10))
       psimz0 = stab_fn_mom(stabilitymethod, z0/l_mod, z0/l_mod)
       z01 = z0
       z0 = (zh - zd)*exp(-1.*kappa/beta)*exp(-1.*psimzh + psimz0)*exp(psihat_z(idx_can))
       err = abs(z01 - z0)
       it = it + 1
    ENDDO
    psimz0 = stab_fn_mom(stabilitymethod, z0/l_mod, z0/l_mod)
    ! calculate above canopy wind speed
    DO z = idx_can, nz
       psimz = stab_fn_mom(stabilitymethod, (zarray(z) - zd)/l_mod, (zarray(z) - zd)/l_mod)
       dataoutlineursl(z) = ustar/kappa*(log((zarray(z) - zd)/z0) - psimz + psimz0 - psihat_z(z) + psihat_z(idx_can))
    ENDDO
    ! calculate in canopy wind speed
    DO z = 1, idx_can
       dataoutlineursl(z) = dataoutlineursl(idx_can)*exp(beta*(zarray(z) - zh)/elm)
    ENDDO
References atmmoiststab_module::stab_fn_mom(), atmmoiststab_module::stab_lumps(), and atmmoiststab_module::stab_phi_mom().
Referenced by suews_driver::suews_cal_main().