SUEWS: /Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_phys_resist.f95 File Reference
suews_phys_resist.f95 File Reference
Functions/Subroutines
subroutine aerodynamicresistance (ZZD, z0m, AVU1, L_mod, UStar, VegFraction, AerodynamicResistanceMethod, StabilityMethod, RoughLenHeatMethod, RA)
subroutine surfaceresistance (id, it, SMDMethod, snowFrac, sfr, avkdn, Temp_C, dq, xsmd, vsmd, MaxConductance, LAIMax, LAI_id, gsModel, Kmax, G1, G2, G3, G4, G5, G6, TH, TL, S1, S2, gfunc, gsc, ResistSurf)
subroutine boundarylayerresistance (zzd, z0m, avU1, UStar, rb)
subroutine suews_cal_roughnessparameters (RoughLenMomMethod, sfr, bldgH, EveTreeH, DecTreeH, porosity_id, FAIBldg, FAIEveTree, FAIDecTree, z0m_in, zdm_in, Z, planF, Zh, z0m, zdm, ZZD)
real(kind(1d0)) function cal_z0v (RoughLenHeatMethod, z0m, VegFraction, UStar)
Function/Subroutine Documentation
aerodynamicresistance()
subroutine aerodynamicresistance (real(kind(1d0)), intent(in) ZZD, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) AVU1, real(kind(1d0)), intent(in) L_mod, real(kind(1d0)), intent(in) UStar, real(kind(1d0)), intent(in) VegFraction, integer, intent(in) AerodynamicResistanceMethod, integer, intent(in) StabilityMethod, integer, intent(in) RoughLenHeatMethod, real(kind(1d0)), intent(out) RA)
Definition at line 14 of file suews_phys_resist.f95.
    ! Returns Aerodynamic resistance (RA) to the main program SUEWS_Calculations
    ! All RA equations reported in Thom & Oliver (1977)
    ! Modified by TS 08 Aug 2017 - interface modified
    ! Modified by LJ
    !   -Removal of tabs and cleaning the code
    ! Modified by HCW 03 Dec 2015 - changed lower limit on RA from 2 s m-1 to 10 s m-1 (to avoid unrealistically high evaporation rates)
    ! Modified by LJ in 12 April to not to be used with global variables
    ! To Do:
    !       - Check whether the thresholds 2-200 s m-1 are suitable over a range of z0!! HCW 04 Mar 2015
    ! OUTPUT: RA - Aerodynamic resistance [s m^-1]
    ! INPUT:  AerodynamicResistanceMethod = Method to calculate RA
    !         StabilityMethod = defines the method to calculate atmospheric stability
    !         RoughLenHeatMethod = Method to calculate heat roughness length
    !         *Measurement height minus* Displacement height (m) (was incorrectly labelled, corrected HCW 25 May 2016
    !         z0m = Aerodynamic roughness length (m)
    !         k2 = Power of Van Karman's constant (= 0.16 = 0.4^2)
    !         AVU1 = Mean wind speed
    !         L_mod = Obukhov length (m)
    !         UStar = Friction velocity (m s-1)
    !         VegFraction = Fraction of vegetation
    !               (changed from veg_fr which also includes water surface by HCW 05 Nov 2015)
    USE atmmoiststab_module, ONLY: stab_fn_heat, stab_fn_mom
    IMPLICIT NONE
    REAL(KIND(1d0)), INTENT(in)::ZZD!Active measurement height (meas. height-displac. height)
    REAL(KIND(1d0)), INTENT(in)::z0m!Aerodynamic roughness length
    REAL(KIND(1d0)), INTENT(in)::AVU1!Average wind speed
    REAL(KIND(1d0)), INTENT(in)::L_mod!Monin-Obukhov length (either measured or modelled)
    REAL(KIND(1d0)), INTENT(in)::UStar!Friction velocity
    REAL(KIND(1d0)), INTENT(in)::VegFraction!Fraction of vegetation
    INTEGER, INTENT(in)::AerodynamicResistanceMethod
    INTEGER, INTENT(in)::StabilityMethod
    INTEGER, INTENT(in)::RoughLenHeatMethod
    REAL(KIND(1d0)), INTENT(out)::RA !Aerodynamic resistance [s m^-1]
    INTEGER, PARAMETER :: notUsedI = -55
    REAL(KIND(1d0)), PARAMETER :: &
       notUsed = -55.5, &
       k2 = 0.16, & !Power of Van Karman's constant (= 0.16 = 0.4^2)
       muu = 1.46e-5 !molecular viscosity
    REAL(KIND(1d0)):: &
       psym, &
       psyh, z0V, cal_z0V
    !1)Monteith (1965)-neutral stability
    IF (aerodynamicresistancemethod == 1) THEN
       ra = (log(zzd/z0m)**2)/(k2*avu1)
       !2) Non-neutral stability
       !    PSIM - stability function for momentum
       !     PSYH - stability function for heat
       !    assuming stability functions the same for heat and water
    ELSEIF (aerodynamicresistancemethod == 2) THEN  !Dyer (1974)
       psym = stab_fn_mom(stabilitymethod, zzd/l_mod, zzd/l_mod)
       psyh = stab_fn_heat(stabilitymethod, zzd/l_mod, zzd/l_mod)
       !Z0V roughness length for vapour
       z0v = cal_z0v(roughlenheatmethod, z0m, vegfraction, ustar)
       ! IF (RoughLenHeatMethod==1) THEN !Brutasert (1982) Z0v=z0/10(see Grimmond & Oke, 1986)
       !    z0V=z0m/10
       ! ELSEIF (RoughLenHeatMethod==2) THEN ! Kawai et al. (2007)
       !           !z0V=z0m*exp(2-(1.2-0.9*veg_fr**0.29)*(UStar*z0m/muu)**0.25)
       !    ! Changed by HCW 05 Nov 2015 (veg_fr includes water; VegFraction = veg + bare soil)
       !    z0V=z0m*EXP(2-(1.2-0.9*VegFraction**0.29)*(UStar*z0m/muu)**0.25)
       ! ELSEIF (RoughLenHeatMethod==3) THEN
       !    z0V=z0m*EXP(-20.) ! Voogt and Grimmond, JAM, 2000
       ! ELSEIF (RoughLenHeatMethod==4) THEN
       !    z0V=z0m*EXP(2-1.29*(UStar*z0m/muu)**0.25) !See !Kanda and Moriwaki (2007),Loridan et al. (2010)
       ! ENDIF
       IF (zzd/l_mod == 0 .OR. ustar == 0) THEN
          ra = (log(zzd/z0m)*log(zzd/z0v))/(k2*avu1) !Use neutral equation
       ELSE
          ra = ((log(zzd/z0m) - psym)*(log(zzd/z0v) - psyh))/(k2*avu1)
       ENDIF
       !3) Thom and Oliver (1977)
    ELSEIF (aerodynamicresistancemethod == 3) THEN
       ra = (4.72*log(zzd/z0m)**2)/(1 + 0.54*avu1)
    ENDIF
    !If RA outside permitted range, adjust extreme values !!Check whether these thresholds are suitable over a range of z0
    IF (ra > 200) THEN   !was 175
       CALL errorhint(7, 'In AerodynamicResistance.f95, calculated RA > 200 s m-1; RA set to 200 s m-1', ra, notused, notusedi)
       ra = 200
    ELSEIF (ra < 10) THEN   !found  By Shiho - fix Dec 2012  !Threshold changed from 2 to 10 s m-1 (HCW 03 Dec 2015)
       CALL errorhint(7, 'In AerodynamicResistance.f95, calculated RA < 10 s m-1; RA set to 10 s m-1', ra, notused, notusedi)
       ra = 10
       ! RA=(log(ZZD/z0m))**2/(k2*AVU1)
       IF (avu1 < 0) WRITE (*, *) avu1, ra
    ENDIF
    RETURN
References errorhint(), atmmoiststab_module::stab_fn_heat(), and atmmoiststab_module::stab_fn_mom().
Referenced by suews_driver::suews_cal_resistance().
boundarylayerresistance()
subroutine boundarylayerresistance (real(kind(1d0)), intent(in) zzd, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) avU1, real(kind(1d0)), intent(inout) UStar, real(kind(1d0)), intent(out) rb)
Definition at line 377 of file suews_phys_resist.f95.
    IMPLICIT NONE
    REAL(KIND(1d0)), INTENT(in)::zzd     !Active measurement height (meas. height-displac. height)
    REAL(KIND(1d0)), INTENT(in)::z0m     !Aerodynamic roughness length
    REAL(KIND(1d0)), INTENT(in)::avU1    !Average wind speed
    REAL(KIND(1d0)), INTENT(inout)::UStar!Friction velocity
    REAL(KIND(1d0)), INTENT(out)::rb   !boundary layer resistance shuttleworth
    REAL(KIND(1d0)), PARAMETER :: k = 0.4
    IF (ustar < 0.01) THEN
       ustar = avu1/log(zzd/z0m)*k
    END IF
    rb = (1.1/ustar) + (5.6*(ustar**0.333333))!rb - boundary layer resistance shuttleworth
    RETURN
Referenced by suews_driver::suews_cal_resistance().
cal_z0v()
real(kind(1d0)) function cal_z0v (integer, intent(in) RoughLenHeatMethod, real(kind(1d0)), intent(in) z0m, real(kind(1d0)), intent(in) VegFraction, real(kind(1d0)), intent(in) UStar)
Definition at line 514 of file suews_phys_resist.f95.
    ! TS 31 Jul 2018: make this a separate funciton for reuse
    !Z0V roughness length for vapour
    IMPLICIT NONE
    INTEGER, INTENT(in)::RoughLenHeatMethod
    REAL(KIND(1d0)), INTENT(in)::z0m!Aerodynamic roughness length
    REAL(KIND(1d0)), INTENT(in)::VegFraction!Fraction of vegetation
    REAL(KIND(1d0)), INTENT(in)::UStar!Friction velocity
    REAL(KIND(1d0))::z0V!roughness length for vapor/heat
    REAL(KIND(1d0)), PARAMETER:: muu = 1.46e-5 !molecular viscosity
    z0v = 0.01 ! initialise as 0.01
    !Z0V roughness length for vapour
    IF (roughlenheatmethod == 1) THEN !Brutasert (1982) Z0v=z0/10(see Grimmond & Oke, 1986)
       z0v = z0m/10
    ELSEIF (roughlenheatmethod == 2) THEN ! Kawai et al. (2007)
       !z0V=z0m*exp(2-(1.2-0.9*veg_fr**0.29)*(UStar*z0m/muu)**0.25)
       ! Changed by HCW 05 Nov 2015 (veg_fr includes water; VegFraction = veg + bare soil)
       z0v = z0m*exp(2 - (1.2 - 0.9*vegfraction**0.29)*(ustar*z0m/muu)**0.25)
    ELSEIF (roughlenheatmethod == 3) THEN
       z0v = z0m*exp(-20.) ! Voogt and Grimmond, JAM, 2000
    ELSEIF (roughlenheatmethod == 4) THEN
       z0v = z0m*exp(2 - 1.29*(ustar*z0m/muu)**0.25) !See !Kanda and Moriwaki (2007),Loridan et al. (2010)
    ENDIF
suews_cal_roughnessparameters()
subroutine suews_cal_roughnessparameters (integer, intent(in) RoughLenMomMethod, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), intent(in) bldgH, real(kind(1d0)), intent(in) EveTreeH, real(kind(1d0)), intent(in) DecTreeH, real(kind(1d0)), intent(in) porosity_id, real(kind(1d0)), intent(in) FAIBldg, real(kind(1d0)), intent(in) FAIEveTree, real(kind(1d0)), intent(in) FAIDecTree, real(kind(1d0)), intent(in) z0m_in, real(kind(1d0)), intent(in) zdm_in, real(kind(1d0)), intent(in) Z, real(kind(1d0)), intent(out) planF, real(kind(1d0)), intent(out) Zh, real(kind(1d0)), intent(out) z0m, real(kind(1d0)), intent(out) zdm, real(kind(1d0)), intent(out) ZZD)
Definition at line 407 of file suews_phys_resist.f95.
    ! Get surface covers and frontal area fractions (LJ 11/2010)
    ! Last modified:
    ! TS  18 Sep 2017 - added explicit interface
    ! HCW 08 Feb 2017 - fixed bug in Zh between grids, added default z0m, zdm
    ! HCW 03 Mar 2015
    ! sg feb 2012 - made separate subroutine
    !--------------------------------------------------------------------------------
    IMPLICIT NONE
    INTEGER, PARAMETER:: nsurf = 7 ! number of surface types
    INTEGER, PARAMETER:: PavSurf = 1 !When all surfaces considered together (1-7)
    INTEGER, PARAMETER:: BldgSurf = 2
    INTEGER, PARAMETER:: ConifSurf = 3
    INTEGER, PARAMETER:: DecidSurf = 4
    INTEGER, PARAMETER:: GrassSurf = 5 !New surface classes: Grass = 5th/7 surfaces
    INTEGER, PARAMETER:: BSoilSurf = 6 !New surface classes: Bare soil = 6th/7 surfaces
    INTEGER, PARAMETER:: WaterSurf = 7
    INTEGER, INTENT(in) ::RoughLenMomMethod
    REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in) ::sfr! surface fractions
    REAL(KIND(1d0)), INTENT(in) ::bldgH
    REAL(KIND(1d0)), INTENT(in) ::EveTreeH
    REAL(KIND(1d0)), INTENT(in) ::DecTreeH
    REAL(KIND(1d0)), INTENT(in) ::porosity_id
    REAL(KIND(1d0)), INTENT(in) ::FAIBldg
    REAL(KIND(1d0)), INTENT(in) ::FAIEveTree
    REAL(KIND(1d0)), INTENT(in) ::FAIDecTree
    REAL(KIND(1d0)), INTENT(in) ::z0m_in ! z0m set in SiteSelect
    REAL(KIND(1d0)), INTENT(in) ::zdm_in ! zdm set in SiteSelect
    REAL(KIND(1d0)), INTENT(in) ::Z
    REAL(KIND(1d0)), INTENT(out) ::planF
    REAL(KIND(1d0)), INTENT(out) ::Zh
    REAL(KIND(1d0)), INTENT(out) ::z0m
    REAL(KIND(1d0)), INTENT(out) ::zdm
    REAL(KIND(1d0)), INTENT(out) ::ZZD
    REAL(KIND(1d0)) ::areaZh
    INTEGER, PARAMETER :: notUsedI = -55
    REAL(KIND(1d0)), PARAMETER:: notUsed = -55.5
    REAL(KIND(1D0)):: z0m4Paved, z0m4Grass, z0m4BSoil, z0m4Water   !Default values for roughness lengths [m]
    areazh = (sfr(bldgsurf) + sfr(conifsurf) + sfr(decidsurf)) !Total area of buildings and trees
    ! Set default values (using Moene & van Dam 2013, Atmos-Veg-Soil Interactions, Table 3.3)
    z0m4paved = 0.003 !estimate
    z0m4grass = 0.02
    z0m4bsoil = 0.002
    z0m4water = 0.0005
    !------------------------------------------------------------------------------
    !If total area of buildings and trees is larger than zero, use tree heights and building heights to calculate zH and FAI
    IF (areazh /= 0) THEN
       zh = bldgh*sfr(bldgsurf)/areazh + evetreeh*sfr(conifsurf)/areazh + dectreeh*(1 - porosity_id)*sfr(decidsurf)/areazh
       planf = faibldg*sfr(bldgsurf)/areazh + faievetree*sfr(conifsurf)/areazh + faidectree*(1 - porosity_id)*sfr(decidsurf)/areazh  ! NT: added calculation of FAI here
    ELSE
       zh = 0   !Set Zh to zero if areaZh = 0
       planf = 0.00001
    ENDIF
    IF (zh /= 0) THEN
       !Calculate z0m and zdm depending on the Z0 method
       IF (roughlenmommethod == 2) THEN  !Rule of thumb (G&O 1999)
          z0m = 0.1*zh
          zdm = 0.7*zh
       ELSEIF (roughlenmommethod == 3) THEN !MacDonald 1998
          IF (areazh /= 0) THEN  !Plan area fraction
             !planF=FAIBldg*sfr(BldgSurf)/areaZh+FAItree*sfr(ConifSurf)/areaZh+FAItree*(1-porosity_id)*sfr(DecidSurf)/areaZh
             !   planF = FAIBldg*sfr(BldgSurf)/areaZh + FAIEveTree*sfr(ConifSurf)/areaZh + FAIDecTree*(1 - porosity_id)*sfr(DecidSurf)/areaZh
          ELSE
             ! planF = 0.00001
             zh = 1
          ENDIF
          zdm = (1 + 4.43**(-sfr(bldgsurf))*(sfr(bldgsurf) - 1))*zh
          z0m = ((1 - zdm/zh)*exp(-(0.5*1.0*1.2/0.4**2*(1 - zdm/zh)*planf)**(-0.5)))*zh
       ENDIF
    ELSEIF (zh == 0) THEN   !If zh calculated to be zero, set default roughness length and displacement height
       IF (areazh /= 0) CALL errorhint(15, 'In SUEWS_RoughnessParameters.f95, zh = 0 m but areaZh > 0', zh, areazh, notusedi)
       !Estimate z0 and zd using default values and surfaces that do not contribute to areaZh
       IF (areazh /= 1) THEN
         z0m = (z0m4paved*sfr(pavsurf) + z0m4grass*sfr(grasssurf) + z0m4bsoil*sfr(bsoilsurf) + z0m4water*sfr(watersurf))/(1 - areazh)
          zdm = 0
          CALL errorhint(15, 'Setting z0m and zdm using default values', z0m, zdm, notusedi)
       ELSEIF (areazh == 1) THEN  !If, for some reason, Zh = 0 and areaZh == 1, assume height of 10 m and use rule-of-thumb
          z0m = 1
          zdm = 7
          CALL errorhint(15, 'Assuming mean height = 10 m, Setting z0m and zdm to default value', z0m, zdm, notusedi)
       ENDIF
    ENDIF
    IF (roughlenmommethod == 1) THEN  !use values set in SiteSelect
       z0m = z0m_in
       zdm = zdm_in
    ENDIF
    zzd = z - zdm
    ! Error messages if aerodynamic parameters negative
    IF (z0m < 0) CALL errorhint(14, 'In SUEWS_cal_RoughnessParameters, z0 < 0 m.', z0m, notused, notusedi)
    IF (zdm < 0) CALL errorhint(14, 'In SUEWS_cal_RoughnessParameters, zd < 0 m.', zdm, notused, notusedi)
    IF (zzd < 0) CALL errorhint(14, 'In SUEWS_cal_RoughnessParameters, (z-zd) < 0 m.', zzd, notused, notusedi)
References errorhint().
Referenced by initialstate(), and suews_driver::suews_cal_main().
surfaceresistance()
subroutine surfaceresistance (integer, intent(in) id, integer, intent(in) it, integer, intent(in) SMDMethod, real(kind(1d0)), dimension(nsurf), intent(in) snowFrac, real(kind(1d0)), dimension(nsurf), intent(in) sfr, real(kind(1d0)), intent(in) avkdn, real(kind(1d0)), intent(in) Temp_C, real(kind(1d0)), intent(in) dq, real(kind(1d0)), intent(in) xsmd, real(kind(1d0)), intent(in) vsmd, real(kind(1d0)), dimension(3), intent(in) MaxConductance, real(kind(1d0)), dimension(3), intent(in) LAIMax, real(kind(1d0)), dimension(3), intent(in) LAI_id, integer, intent(in) gsModel, real(kind(1d0)), intent(in) Kmax, real(kind(1d0)), intent(in) G1, real(kind(1d0)), intent(in) G2, real(kind(1d0)), intent(in) G3, real(kind(1d0)), intent(in) G4, real(kind(1d0)), intent(in) G5, real(kind(1d0)), intent(in) G6, real(kind(1d0)), intent(in) TH, real(kind(1d0)), intent(in) TL, real(kind(1d0)), intent(in) S1, real(kind(1d0)), intent(in) S2, real(kind(1d0)), intent(out) gfunc, real(kind(1d0)), intent(out) gsc, real(kind(1d0)), intent(out) ResistSurf)
Definition at line 122 of file suews_phys_resist.f95.
    ! Calculates bulk surface resistance (ResistSurf [s m-1]) based on Jarvis 1976 approach
    ! Last modified -----------------------------------------------------
    ! MH  01 Feb 2019: gsModel choices to model with air temperature or 2 meter temperature. Added gfunc for photosynthesis calculations
    ! HCW 21 Jul 2016: If no veg surfaces, vsmd = NaN so QE & QH = NaN; if water surfaces only, smd = NaN so QE & QH = NaN.
    !                  Add checks here so that gs (soil part) = 0 in either of these situations.
    !                  This shouldn't change results but handles NaN error.
    ! HCW 01 Mar 2016: SM dependence is now on modelled smd for vegetated surfaces only (vsmd) (Note: obs smd still not operational!)
    ! HCW 18 Jun 2015: Alternative gs parameterisation added using different functional forms and new coefficients
    ! HCW 31 Jul 2014: Modified condition on g6 part to select meas/mod smd
    ! LJ  24 Apr 2013: Added impact of snow fraction in LAI and in soil moisture deficit
    ! -------------------------------------------------------------------
    ! USE allocateArray
    ! USE data_in
    ! USE defaultNotUsed
    ! USE gis_data
    ! USE moist
    ! USE resist
    ! USE sues_data
    IMPLICIT NONE
    ! INTEGER,PARAMETER::BldgSurf=2
    INTEGER, PARAMETER::ConifSurf = 3
    INTEGER, PARAMETER::DecidSurf = 4
    INTEGER, PARAMETER::GrassSurf = 5
    ! INTEGER,PARAMETER::ivConif=1
    ! INTEGER,PARAMETER::ivGrass=3
    ! INTEGER,PARAMETER::MaxNumberOfGrids=2000
    ! INTEGER,PARAMETER::ndays=366
    INTEGER, PARAMETER::nsurf = 7
    ! INTEGER,PARAMETER::NVegSurf=3
    ! INTEGER,PARAMETER::PavSurf=1
    INTEGER, PARAMETER::WaterSurf = 7
    INTEGER, INTENT(in)::id
    INTEGER, INTENT(in)::it ! time: day of year and hour
    INTEGER, INTENT(in)::gsModel!Choice of gs parameterisation (1 = Ja11, 2 = Wa16)
    INTEGER, INTENT(in)::SMDMethod!Method of measured soil moisture
    ! INTEGER,INTENT(in)::ConifSurf!= 3, surface code
    ! INTEGER,INTENT(in)::DecidSurf!= 4, surface code
    ! INTEGER,INTENT(in)::GrassSurf!= 5, surface code
    ! INTEGER,INTENT(in)::WaterSurf!= 7, surface code
    ! INTEGER,INTENT(in)::nsurf!= 7, Total number of surfaces
    REAL(KIND(1d0)), INTENT(in)::avkdn!Average downwelling shortwave radiation
    REAL(KIND(1d0)), INTENT(in)::Temp_C!Air temperature
    REAL(KIND(1d0)), INTENT(in)::Kmax!Annual maximum hourly solar radiation
    REAL(KIND(1d0)), INTENT(in)::G1!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::G2!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::G3!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::G4!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::G5!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::G6!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::S1!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::S2!Fitted parameters related to surface res. calculations
    REAL(KIND(1d0)), INTENT(in)::TH!Maximum temperature limit
    REAL(KIND(1d0)), INTENT(in)::TL!Minimum temperature limit
    REAL(KIND(1d0)), INTENT(in)::dq!Specific humidity deficit
    REAL(KIND(1d0)), INTENT(in)::xsmd!Measured soil moisture deficit
    REAL(KIND(1d0)), INTENT(in)::vsmd!QUESTION: Soil moisture deficit for vegetated surfaces only (what about BSoil?)
    REAL(KIND(1d0)), DIMENSION(3), INTENT(in)    ::MaxConductance!Max conductance [mm s-1]
    REAL(KIND(1d0)), DIMENSION(3), INTENT(in)    ::LAIMax        !Max LAI [m2 m-2]
    REAL(KIND(1d0)), DIMENSION(3), INTENT(in)    ::LAI_id        !=LAI(id-1,:), LAI for each veg surface [m2 m-2]
    REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::snowFrac      !Surface fraction of snow cover
    REAL(KIND(1d0)), DIMENSION(nsurf), INTENT(in)::sfr           !Surface fractions [-]
    REAL(KIND(1d0)), INTENT(out)::gfunc!gdq*gtemp*gs*gq for photosynthesis calculations
    REAL(KIND(1d0)), INTENT(out)::gsc!Surface Layer Conductance
    REAL(KIND(1d0)), INTENT(out)::ResistSurf!Surface resistance
    REAL(KIND(1d0)):: &
       gl, &!G(LAI)
       QNM, &!QMAX/(QMAX+G2)
       gq, &!G(Q*)
       gdq, &!G(dq)
       TC, &!Temperature parameter 1
       TC2, &!Temperature parameter 2
       gtemp, &!G(T)
       sdp, &!S1/G6+S2
       gs!G(Soil moisture deficit)
    INTEGER:: iv
    REAL(KIND(1d0)):: id_real
    REAL(KIND(1d0)), PARAMETER :: notUsed = -55
    ! REAL(KIND(1d0)),PARAMETER :: notUsedi=-55.5
    id_real = real(id) !Day of year in real number
    !gsModel = 1 - original parameterisation (Jarvi et al. 2011)
    !gsModel = 2 - new parameterisation (Ward et al. 2016)
    !gsModel = 3 - original parameterisation (Jarvi et al. 2011) with 2 m temperature
    !gsModel = 4 - new parameterisation (Ward et al. 2016) with 2 m temperature
    IF (gsmodel == 1 .OR. gsmodel == 3) THEN
      ! kdown ----
      qnm = kmax/(kmax + g2)
      !gq=(qn1/(g2+qn1))/qnm !With net all-wave radiation
      gq = (avkdn/(g2 + avkdn))/qnm !With Kdown
      ! specific humidity deficit ----
      IF (dq < g4) THEN
         gdq = 1 - g3*dq
      ELSE
          gdq = 1 - g3*g4
      ENDIF
       ! air temperature ----
      tc = (th - g5)/(g5 - tl)
      tc2 = (g5 - tl)*(th - g5)**tc
      !If air temperature below TL or above TH, fit it to TL+0.1/TH-0.1
      IF (temp_c <= tl) THEN
         gtemp = (tl + 0.1 - tl)*(th - (tl + 0.1))**tc/tc2
         !Call error only if no snow on ground
         !  IF (MIN(snowFrac(1),snowFrac(2),snowFrac(3),snowFrac(4),snowFrac(5),snowFrac(6))/=1) THEN
         IF (minval(snowfrac(1:6)) /= 1) THEN
            CALL errorhint(29, 'subroutine SurfaceResistance.f95: T changed to fit limits TL=0.1,Temp_c,id,it', &
                           REAL(Temp_c, KIND(1d0)), id_real, it)
         ENDIF
       ELSEIF (temp_c >= th) THEN
         gtemp = ((th - 0.1) - tl)*(th - (th - 0.1))**tc/tc2
         CALL errorhint(29, 'subroutine SurfaceResistance.f95: T changed to fit limits TH=39.9,Temp_c,id,it', &
                        REAL(Temp_c, KIND(1d0)), id_real, it)
      ELSE
         gtemp = (temp_c - tl)*(th - temp_c)**tc/tc2
      ENDIF
      ! soil moisture deficit ----
      sdp = s1/g6 + s2
      IF (smdmethod > 0) THEN         !Modified from ==1 to > 0 by HCW 31/07/2014
         gs = 1 - exp(g6*(xsmd - sdp))  !Measured soil moisture deficit is used
      ELSE
         gs = 1 - exp(g6*(vsmd - sdp))   !Modelled is used
         IF (sfr(conifsurf) + sfr(decidsurf) + sfr(grasssurf) == 0 .OR. sfr(watersurf) == 1) THEN
            gs = 0   !If no veg so no vsmd, or all water so no smd, set gs=0 (HCW 21 Jul 2016)
         ENDIF
      ENDIF
      !gs = gs*(1 - SUM(snowFrac(1:6))/6)
      IF (gs < 0) THEN
         CALL errorhint(65, 'subroutine SurfaceResistance.f95 (gsModel=1): g(smd) < 0 calculated, setting to 0.0001', gs, id_real,it)
         gs = 0.0001
      ENDIF
      !LAI
      !Original way
      !gl=((LAI(id,2)*areaunir/lm)+areair)/(areair+areaunir)
      !New way
      gl = 0    !First initialize
      ! vegetated surfaces
      ! check basis for values koe - maximum surface conductance
      !  print*,id,it,sfr
      ! DO iv=ivConif,ivGrass
      DO iv = 1, 3
        ! gl=gl+(sfr(iv+2)*(1-snowFrac(iv+2)))*LAI(id-1,iv)/LAIMax(iv)*MaxConductance(iv)
         gl = gl + (sfr(iv + 2)*(1 - snowfrac(iv + 2)))*lai_id(iv)/laimax(iv)*maxconductance(iv)
      ENDDO
      IF (avkdn <= 0) THEN      !At nighttime set gsc at arbitrary low value: gsc=0.1 mm/s (Shuttleworth, 1988b)
         gsc = 0.1
      ELSE
         ! Multiply parts together
         gsc = (g1*gq*gdq*gtemp*gs*gl)
      ENDIF
      IF (gsc <= 0) THEN
         CALL errorhint(65, 'subroutine SurfaceResistance.f95 (gsModel=1): gs <= 0, setting to 0.1 mm s-1', gsc, id_real,it)
         gsc = 0.1
      ENDIF
    ELSEIF (gsmodel == 2 .OR. gsmodel == 4) THEN
      ! ---- g(kdown)----
      qnm = kmax/(kmax + g2)
      gq = (avkdn/(avkdn + g2))/qnm
      IF (avkdn >= kmax) THEN   !! Add proper error handling later - HCW!!
         WRITE (*, *) 'Kmax exceeds Kdn setting to g(Kdn) to 1'
         gq = 1
      ENDIF
      ! ---- g(delq) ----
      gdq = g3 + (1 - g3)*(g4**dq)   !Ogink-Hendriks (1995) Eq 12 (using G3 as Kshd and G4 as r)
      ! ---- g(Tair) ----
      tc = (th - g5)/(g5 - tl)
      tc2 = (g5 - tl)*(th - g5)**tc
      ! If air temperature below TL or above TH, then use value for TL+0.1 or TH-0.1
      IF (temp_c <= tl) THEN
         gtemp = (tl + 0.1 - tl)*(th - (tl + 0.1))**tc/tc2
         ! Call error only if no snow on ground
         IF (min(snowfrac(1), snowfrac(2), snowfrac(3), snowfrac(4), snowfrac(5), snowfrac(6)) /= 1) THEN
            CALL errorhint(29, 'subroutine SurfaceResistance.f95: T changed to fit limits TL+0.1,Temp_C,id,it', &
                           REAL(Temp_c, KIND(1d0)), id_real, it)
         ENDIF
      ELSEIF (temp_c >= th) THEN
         gtemp = ((th - 0.1) - tl)*(th - (th - 0.1))**tc/tc2
         CALL errorhint(29, 'subroutine SurfaceResistance.f95: T changed to fit limits TH-0.1,Temp_C,id,it', &
                        REAL(Temp_c, KIND(1d0)), id_real, it)
      ELSE
         gtemp = (temp_c - tl)*(th - temp_c)**tc/tc2
      ENDIF
      ! ---- g(smd) ----
      sdp = s1/g6 + s2
      IF (smdmethod > 0) THEN   !Modified from ==1 to > 0 by HCW 31/07/2014
         gs = (1 - exp(g6*(xsmd - sdp)))/(1 - exp(g6*(-sdp)))   !Use measured smd
      ELSE
         !gs=1-EXP(g6*(vsmd-sdp))   !Use modelled smd
         gs = (1 - exp(g6*(vsmd - sdp)))/(1 - exp(g6*(-sdp)))
         IF (sfr(conifsurf) + sfr(decidsurf) + sfr(grasssurf) == 0 .OR. sfr(watersurf) == 1) THEN
            gs = 0   !If no veg so no vsmd, or all water so no smd, set gs=0 HCW 21 Jul 2016
         ENDIF
      ENDIF
      !gs = gs*(1 - SUM(snowFrac(1:6))/6)
      IF (gs < 0) THEN
        CALL errorhint(65, 'subroutine SurfaceResistance.f95 (gsModel=2): gs < 0 calculated, setting to 0.0001', gs, id_real,it)
         gs = 0.0001
      ENDIF
      ! ---- g(LAI) ----
      gl = 0    !Initialise
      ! DO iv=ivConif,ivGrass   !For vegetated surfaces
      DO iv = 1, 3   !For vegetated surfaces
         !  gl=gl+(sfr(iv+2)*(1-snowFrac(iv+2)))*LAI(id-1,iv)/LAIMax(iv)*MaxConductance(iv)
         gl = gl + (sfr(iv + 2)*(1 - snowfrac(iv + 2)))*lai_id(iv)/laimax(iv)*maxconductance(iv)
      ENDDO
      IF (avkdn <= 0) THEN      !At nighttime set gsc at arbitrary low value: gsc=0.1 mm/s (Shuttleworth, 1988b)
         gsc = 0.1
      ELSE
         ! Multiply parts together
         gsc = (g1*gq*gdq*gtemp*gs*gl)
      ENDIF
      IF (gsc <= 0) THEN
         CALL errorhint(65, 'subroutine SurfaceResistance.f95 (gsModel=2): gsc <= 0, setting to 0.1 mm s-1', gsc, id_real,it)
         gsc = 0.1
      ENDIF
    ELSEIF (gsmodel < 1 .OR. gsmodel > 4) THEN
      CALL errorhint(71, 'Value of gsModel not recognised.', notused, notused, gsmodel)
    ENDIF
    resistsurf = 1/(gsc/1000)  ![s m-1]
    gfunc = gdq*gtemp*gs*gq
    RETURN
References errorhint().
Referenced by suews_driver::suews_cal_biogenco2(), and suews_driver::suews_cal_resistance().