SUEWS: /Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_program.f95 File Reference
suews_program.f95 File Reference
Functions/Subroutines
program suews_program
Function/Subroutine Documentation
suews_program()
program suews_program ()
Definition at line 32 of file suews_program.f95.
References colnamesinputfiles::c_grid, colnamesinputfiles::c_year, bluews_module::cbl_readinputdata(), data_in::cbluse, ctrl_output::count_lines(), allocatearray::dailystatefirstopen, allocatearray::dataoutbl, allocatearray::dataoutdailystate, allocatearray::dataoutestm, allocatearray::dataoutrsl, allocatearray::dataoutsnow, allocatearray::dataoutsol, allocatearray::dataoutsuews, wherewhen::datetime, data_in::diagnose, metdisagg::disaggregateestm(), metdisagg::disaggregatemet(), allocatearray::dqndt_grids, allocatearray::dqnsdt_grids, time::dt_since_start, defaultnotused::errorchoice, errorhint(), estm_module::estm_initials(), allocatearray::estmforcingdata, data_in::filecode, data_in::filedscdestm, data_in::filedscdmet, data_in::fileestmts, data_in::fileinputpath, data_in::filemet, data_in::fileorigestm, data_in::fileorigmet, initial::firstyear, initial::gridcounter, wherewhen::gridid, wherewhen::gridid_text, allocatearray::grididmatrix, allocatearray::grididmatrix0, time::id, time::id_prev_t, initializesurfacecharacteristics(), initialstate(), time::iy, time::iy_prev_t, initial::lastyear, leapyearcalc(), allocatearray::maxlinesmet, allocatearray::maxncols_c, allocatearray::maxncols_cmds, allocatearray::maxncols_cmod, allocatearray::maxnumberofgrids, allocatearray::metforcingdata, allocatearray::metforcingdata_grid, allocatearray::modeldailystate, allocatearray::modeloutputdata, data_in::multipleestmfiles, data_in::multiplemetfiles, defaultnotused::nan, data_in::ncmode, data_in::ncol, allocatearray::ncolsestmdata, allocatearray::ncolumnsdataoutbl, allocatearray::ncolumnsdataoutdailystate, allocatearray::ncolumnsdataoutrsl, allocatearray::ncolumnsdataoutsnow, allocatearray::ncolumnsdataoutsol, allocatearray::ncolumnsdataoutsuews, allocatearray::ncolumnsmetforcingdata, allocatearray::ndays, nextinitial(), initial::nlinesestmdata, initial::nlinesmetdata, initial::nlinesorigestmdata, initial::nlinesorigmetdata, initial::nlinessiteselect, time::nofdaysthisyear, defaultnotused::notused, sues_data::nper, sues_data::nper_real, sues_data::nperestm, sues_data::nperestm_real, data_in::nrow, sues_data::nsd, sues_data::nsdorig, sues_data::nsh, initial::numberofgrids, data_in::outputformats, overallruncontrol(), data_in::progname, allocatearray::qn1_av_grids, allocatearray::qn1_s_av_grids, initial::readblocksmetdata, initial::readblocksorigmetdata, initial::readlinesmetdata, initial::readlinesorigestmdata, initial::readlinesorigestmdatamax, initial::readlinesorigmetdata, initial::readlinesorigmetdatamax, data_in::resolutionfilesin, data_in::resolutionfilesinestm, allocatearray::siteselect, initial::skippedlines, initial::skippedlinesorig, initial::skippedlinesorigestm, data_in::solweiguse, ctrl_output::sortgrid(), data_in::storageheatmethod, suews_calculations(), estm_module::suews_getestmdata(), suews_initializemetdata(), ctrl_output::suews_output(), allocatearray::surfacechar, allocatearray::tair24hr, allocatearray::ts5mindata, allocatearray::ts5mindata_ir, sues_data::tstep, allocatearray::usecolumnsdataout, and defaultnotused::warningchoice.