SUEWS: /Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_ctrl_calculations.f95 File Reference
suews_ctrl_calculations.f95 File Reference
Functions/Subroutines
subroutine suews_calculations (Gridiv, ir, iMB, irMax)
Function/Subroutine Documentation
suews_calculations()
subroutine suews_calculations (integer Gridiv, integer ir, integer iMB, integer irMax)
Definition at line 37 of file suews_ctrl_calculations.f95.
    USE data_in, ONLY: diagnose, ah_min, ah_slope_cooling, ah_slope_heating, &
       alt, avkdn, avrh, avu1, basethdd, diagqn, diagqs, drainrt, co2pointsource, &
       ef_umolco2perj, emissionsmethod, enef_v_jkm, enddls, fcef_v_kgkm, fcld_obs, &
       frfossilfuel_heat, frfossilfuel_nonheat, evapmethod, &
       laicalcyes, lai_obs, lat, ldown_obs, lng, maxfcmetab, maxqfmetab, &
       minfcmetab, minqfmetab, netradiationmethod, numcapita, ohmincqf, &
       popdensdaytime, popdensnighttime, &
       precip, press_hpa, qf0_beu, qf_a, qf_b, qf_c, &
       qh_obs, qn1_obs, qs_obs, qf_obs, &
       raincover, rainmaxres, &
       roughlenmommethod, smdmethod, snowfrac_obs, snowuse, startdls, &
       storageheatmethod, t_critic_cooling, t_critic_heating, temp_c, &
       timezone, trafficrate, trafficunits, waterusemethod, wu_m3, xsmd
    USE time, ONLY: iy, id, it, imin, isec, dt_since_start
    USE allocatearray, ONLY: &
       alb, &
       albmax_dectr, albmax_evetr, albmax_grass, &
       albmin_dectr, albmin_evetr, albmin_grass, &
       alpha_bioco2, alpha_enh_bioco2, baset, basete, &
       beta_bioco2, beta_enh_bioco2, capmax_dec, capmin_dec, &
       chanohm, cpanohm, emis, gdd_id, gddfull, &
       hdd_id, &
       decidcap_id, porosity_id, &
       albdectr_id, albevetr_id, albgrass_id, &
       icefrac, kkanohm, &
       lai_id, laimax, laimin, laipower, laitype, maxconductance, &
       snowwater, metforcingdata_grid, min_res_bioco2, &
       narp_emis_snow, narp_trans_site, &
       ohm_coef, ohm_threshsw, ohm_threshwd, &
       pormax_dec, pormin_dec, &
       dqndt, qn1_av, &
       dqnsdt, qn1_s_av, &
       resp_a, resp_b, sathydraulicconduct, sddfull, &
       sfr, snowpacklimit, snowdens, snowfrac, snowpack, &
       soildepth, soilstore_id, soilstorecap, state_id, statelimit, &
       storedrainprm, tair24hr, theta_bioco2, ts5mindata_ir, &
       waterdist, wetthresh, &
       wuday_id, &
       ahprof_24hr, humactivity_24hr, popprof_24hr, traffprof_24hr, wuprofa_24hr, wuprofm_24hr, &
       datetimeline, dataoutlinesuews, dataoutlinesnow, &
       dataoutlineestm, dataoutlinersl, dailystateline, dataoutdailystate, &
       dataoutsuews, dataoutsnow, dataoutestm, dataoutrsl
    USE sues_data, ONLY: &
       aerodynamicresistancemethod, daywat, daywatper, faut, flowchange, &
       ie_a, ie_end, ie_m, ie_start, internalwateruse_h, &
       irrfracconif, irrfracdecid, irrfracgrass, &
       pipecapacity, roughlenheatmethod, runofftowater, stabilitymethod, &
       surfacearea, tstep, tstep_prev
    USE snowmod, ONLY: &
       crwmax, crwmin, preciplimit, preciplimitalb, radmeltfact, &
       snowalb, snowalbmax, snowalbmin, &
       snowdensmax, snowdensmin, snowfallcum, snowlimbldg, &
       snowlimpaved, snowprof_24hr, &
       tau_a, tau_f, tau_r, tempmeltfact
    USE gis_data, ONLY: &
       bldgh, dectreeh, evetreeh, faibldg, faidectree, faievetree, veg_type
    USE initial, ONLY: numberofgrids, readlinesmetdata
    USE mod_z, ONLY: z, z0m_in, zdm_in
    USE suews_driver, ONLY: suews_update_output
    USE resist, ONLY: g1, g2, g3, g4, g5, g6, gsmodel, kmax, s1, s2, th, tl
    USE dailystate_module, ONLY: suews_update_dailystate
    USE suews_driver, ONLY: suews_cal_main
    IMPLICIT NONE
    INTEGER :: Gridiv
    INTEGER :: ir
    INTEGER :: iMB
    INTEGER :: irMax
    !==================================================================
    !Translate all data to the variables used in the model calculations
    IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_Translate...'
    CALL suews_translate(gridiv, ir, imb)
    IF (diagnose == 1) print *, 'Calling SUEWS_cal_Main...'
    CALL suews_cal_main( &
       aerodynamicresistancemethod, ah_min, ahprof_24hr, ah_slope_cooling, & ! input&inout in alphabetical order
       ah_slope_heating, &
       alb, albmax_dectr, albmax_evetr, albmax_grass, &
       albmin_dectr, albmin_evetr, albmin_grass, &
       alpha_bioco2, alpha_enh_bioco2, alt, avkdn, avrh, avu1, baset, basete, &
       basethdd, beta_bioco2, beta_enh_bioco2, bldgh, capmax_dec, capmin_dec, &
       chanohm, co2pointsource, cpanohm, crwmax, crwmin, daywat, daywatper, &
       dectreeh, diagnose, diagqn, diagqs, drainrt, &
       dt_since_start, dqndt, qn1_av, dqnsdt, qn1_s_av, &
       ef_umolco2perj, emis, emissionsmethod, enef_v_jkm, enddls, evetreeh, faibldg, &
       faidectree, faievetree, faut, fcef_v_kgkm, fcld_obs, flowchange, &
       frfossilfuel_heat, frfossilfuel_nonheat, g1, g2, g3, g4, g5, g6, gdd_id, &
       gddfull, gridiv, gsmodel, hdd_id, humactivity_24hr, &
       icefrac, id, ie_a, ie_end, ie_m, ie_start, imin, &
       internalwateruse_h, irrfracconif, irrfracdecid, irrfracgrass, isec, it, evapmethod, &
       iy, kkanohm, kmax, lai_id, laicalcyes, laimax, laimin, lai_obs, &
       laipower, laitype, lat, ldown_obs, lng, maxconductance, maxfcmetab, maxqfmetab, &
       snowwater, metforcingdata_grid, minfcmetab, minqfmetab, min_res_bioco2, &
       narp_emis_snow, narp_trans_site, netradiationmethod, &
       numcapita, ohm_coef, ohmincqf, ohm_threshsw, &
       ohm_threshwd, pipecapacity, popdensdaytime, &
       popdensnighttime, popprof_24hr, pormax_dec, pormin_dec, &
       precip, preciplimit, preciplimitalb, press_hpa, &
       qf0_beu, qf_a, qf_b, qf_c, &
       qn1_obs, qh_obs, qs_obs, qf_obs, &
       radmeltfact, raincover, rainmaxres, resp_a, resp_b, &
       roughlenheatmethod, roughlenmommethod, runofftowater, s1, s2, &
       sathydraulicconduct, sddfull, sfr, smdmethod, snowalb, snowalbmax, &
       snowalbmin, snowpacklimit, snowdens, snowdensmax, snowdensmin, snowfallcum, snowfrac, &
       snowlimbldg, snowlimpaved, snowfrac_obs, snowpack, snowprof_24hr, snowuse, soildepth, &
       soilstore_id, soilstorecap, stabilitymethod, startdls, state_id, statelimit, &
       storageheatmethod, storedrainprm, surfacearea, tair24hr, tau_a, tau_f, tau_r, &
       t_critic_cooling, t_critic_heating, temp_c, tempmeltfact, th, &
       theta_bioco2, timezone, tl, trafficrate, trafficunits, &
       traffprof_24hr, ts5mindata_ir, tstep, tstep_prev, veg_type, &
       waterdist, waterusemethod, wetthresh, wu_m3, &
       wuday_id, decidcap_id, albdectr_id, albevetr_id, albgrass_id, porosity_id, &
       wuprofa_24hr, wuprofm_24hr, xsmd, z, z0m_in, zdm_in, &
       datetimeline, dataoutlinesuews, dataoutlinesnow, dataoutlineestm, dataoutlinersl, &!output
       dailystateline)!output
    !============ update and write out SUEWS_cal_DailyState ===============
    ! only works at the last timestep of a day
    CALL suews_update_dailystate( &
       id, datetimeline, &!input
       gridiv, numberofgrids, &
       dailystateline, &
       dataoutdailystate)!inout
    !============ write out results ===============
    ! works at each timestep
    CALL suews_update_output( &
       snowuse, storageheatmethod, &!input
       readlinesmetdata, numberofgrids, &
       ir, gridiv, datetimeline, dataoutlinesuews, dataoutlinesnow, dataoutlineestm, dataoutlinersl, &!input
       dataoutsuews, dataoutsnow, dataoutestm, dataoutrsl)!inout
    ! NB: CBL disabled for the moment for interface improvement
    ! NB: CBL be decoupled from SUEWS TS 10 Jun 2018
    ! IF(CBLuse>=1)THEN ! If CBL is used, calculated Temp_C and RH are replaced with the obs.
    !    IF(Diagnose==1) WRITE(*,*) 'Calling CBL...'
    !    CALL CBL(ir,iMB,Gridiv)   !ir=1 indicates first row of each met data block
    ! ENDIF
    ! NB: SOLWEIG can be treated as a separate part:
    ! NB: SOLWEIG is disabled for v2018a TS 10 Jun 2018
    ! ===================SOLWEIG OUTPUT ========================================
    ! IF (SOLWEIGuse==1) THEN
    !    IF (OutInterval==imin) THEN
    !       IF (RunForGrid==-999) THEN
    !          IF(Diagnose==1) WRITE(*,*) 'Calling SOLWEIG_2014a_core...'
    !          CALL SOLWEIG_2014a_core(iMB)
    !          SolweigCount=SolweigCount+1
    !       ELSE
    !          IF (Gridiv == RunForGrid) THEN
    !             IF(Diagnose==1) WRITE(*,*) 'Calling SOLWEIG_2014a_core...'
    !             CALL SOLWEIG_2014a_core(iMB)
    !             SolweigCount=SolweigCount+1
    !          ENDIF
    !       ENDIF
    !    ENDIF
    ! ELSE
    ! SOLWEIGpoi_out=0 ! NB: turn off SOLWEIG for the moment
    ! ENDIF
    ! ===================SOLWEIG END================================
    IF (diagnose == 1) WRITE (*, *) 'Calling SUEWS_TranslateBack...'
    CALL suews_translateback(gridiv, ir, irmax)
References sues_data::aerodynamicresistancemethod, data_in::ah_min, data_in::ah_slope_cooling, data_in::ah_slope_heating, allocatearray::ahprof_24hr, allocatearray::alb, allocatearray::albdectr_id, allocatearray::albevetr_id, allocatearray::albgrass_id, allocatearray::albmax_dectr, allocatearray::albmax_evetr, allocatearray::albmax_grass, allocatearray::albmin_dectr, allocatearray::albmin_evetr, allocatearray::albmin_grass, allocatearray::alpha_bioco2, allocatearray::alpha_enh_bioco2, data_in::alt, data_in::avkdn, data_in::avrh, data_in::avu1, allocatearray::baset, allocatearray::basete, data_in::basethdd, allocatearray::beta_bioco2, allocatearray::beta_enh_bioco2, gis_data::bldgh, allocatearray::capmax_dec, allocatearray::capmin_dec, allocatearray::chanohm, data_in::co2pointsource, allocatearray::cpanohm, snowmod::crwmax, snowmod::crwmin, allocatearray::dailystateline, allocatearray::dataoutdailystate, allocatearray::dataoutestm, allocatearray::dataoutlineestm, allocatearray::dataoutlinersl, allocatearray::dataoutlinesnow, allocatearray::dataoutlinesuews, allocatearray::dataoutrsl, allocatearray::dataoutsnow, allocatearray::dataoutsuews, allocatearray::datetimeline, sues_data::daywat, sues_data::daywatper, allocatearray::decidcap_id, gis_data::dectreeh, data_in::diagnose, data_in::diagqn, data_in::diagqs, allocatearray::dqndt, allocatearray::dqnsdt, data_in::drainrt, time::dt_since_start, data_in::ef_umolco2perj, allocatearray::emis, data_in::emissionsmethod, data_in::enddls, data_in::enef_v_jkm, data_in::evapmethod, gis_data::evetreeh, gis_data::faibldg, gis_data::faidectree, gis_data::faievetree, sues_data::faut, data_in::fcef_v_kgkm, data_in::fcld_obs, sues_data::flowchange, data_in::frfossilfuel_heat, data_in::frfossilfuel_nonheat, resist::g1, resist::g2, resist::g3, resist::g4, resist::g5, resist::g6, allocatearray::gdd_id, allocatearray::gddfull, resist::gsmodel, allocatearray::hdd_id, allocatearray::humactivity_24hr, allocatearray::icefrac, time::id, sues_data::ie_a, sues_data::ie_end, sues_data::ie_m, sues_data::ie_start, time::imin, sues_data::internalwateruse_h, sues_data::irrfracconif, sues_data::irrfracdecid, sues_data::irrfracgrass, time::isec, time::it, time::iy, allocatearray::kkanohm, resist::kmax, allocatearray::lai_id, data_in::lai_obs, data_in::laicalcyes, allocatearray::laimax, allocatearray::laimin, allocatearray::laipower, allocatearray::laitype, data_in::lat, data_in::ldown_obs, data_in::lng, allocatearray::maxconductance, data_in::maxfcmetab, data_in::maxqfmetab, allocatearray::metforcingdata_grid, allocatearray::min_res_bioco2, data_in::minfcmetab, data_in::minqfmetab, allocatearray::narp_emis_snow, allocatearray::narp_trans_site, data_in::netradiationmethod, initial::numberofgrids, data_in::numcapita, allocatearray::ohm_coef, allocatearray::ohm_threshsw, allocatearray::ohm_threshwd, data_in::ohmincqf, sues_data::pipecapacity, data_in::popdensdaytime, data_in::popdensnighttime, allocatearray::popprof_24hr, allocatearray::pormax_dec, allocatearray::pormin_dec, allocatearray::porosity_id, data_in::precip, snowmod::preciplimit, snowmod::preciplimitalb, data_in::press_hpa, data_in::qf0_beu, data_in::qf_a, data_in::qf_b, data_in::qf_c, data_in::qf_obs, data_in::qh_obs, allocatearray::qn1_av, data_in::qn1_obs, allocatearray::qn1_s_av, data_in::qs_obs, snowmod::radmeltfact, data_in::raincover, data_in::rainmaxres, initial::readlinesmetdata, allocatearray::resp_a, allocatearray::resp_b, sues_data::roughlenheatmethod, data_in::roughlenmommethod, sues_data::runofftowater, resist::s1, resist::s2, allocatearray::sathydraulicconduct, allocatearray::sddfull, allocatearray::sfr, data_in::smdmethod, snowmod::snowalb, snowmod::snowalbmax, snowmod::snowalbmin, allocatearray::snowdens, snowmod::snowdensmax, snowmod::snowdensmin, snowmod::snowfallcum, allocatearray::snowfrac, data_in::snowfrac_obs, snowmod::snowlimbldg, snowmod::snowlimpaved, allocatearray::snowpack, allocatearray::snowpacklimit, snowmod::snowprof_24hr, data_in::snowuse, allocatearray::snowwater, allocatearray::soildepth, allocatearray::soilstore_id, allocatearray::soilstorecap, sues_data::stabilitymethod, data_in::startdls, allocatearray::state_id, allocatearray::statelimit, data_in::storageheatmethod, allocatearray::storedrainprm, suews_driver::suews_cal_main(), suews_translate(), suews_translateback(), dailystate_module::suews_update_dailystate(), suews_driver::suews_update_output(), sues_data::surfacearea, data_in::t_critic_cooling, data_in::t_critic_heating, allocatearray::tair24hr, snowmod::tau_a, snowmod::tau_f, snowmod::tau_r, data_in::temp_c, snowmod::tempmeltfact, resist::th, allocatearray::theta_bioco2, data_in::timezone, resist::tl, data_in::trafficrate, data_in::trafficunits, allocatearray::traffprof_24hr, allocatearray::ts5mindata_ir, sues_data::tstep, sues_data::tstep_prev, gis_data::veg_type, allocatearray::waterdist, data_in::waterusemethod, allocatearray::wetthresh, data_in::wu_m3, allocatearray::wuday_id, allocatearray::wuprofa_24hr, allocatearray::wuprofm_24hr, data_in::xsmd, mod_z::z, mod_z::z0m_in, and mod_z::zdm_in.
Referenced by suews_program().