SUEWS: /Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_ctrl_input.f95 File Reference
suews_ctrl_input.f95 File Reference
Modules
module run_info
module metdisagg
Functions/Subroutines
subroutine metread (lfn, MetArray, InputmetFormat, ldown_option, NetRadiationMethod, snowUse, SMDMethod, SoilDepthMeas, SoilRocks, SoilDensity, SmCap)
subroutine run_control (eval, LowerLimit, Upperlimit)
subroutine skipheader (lfn, skip)
subroutine inputheadercheck (FileName)
real(kind(1d0)) function get_prof_spectime_inst (Hour, Min, Sec, Prof_24h)
real(kind(1d0)) function get_prof_spectime_mean (Hour, Min, Sec, Prof_24h)
real(kind(1d0)) function get_prof_spectime_sum (Hour, Min, Sec, Prof_24h, dt)
subroutine codematchohm (Gridiv, is, SWWD)
subroutine codematchestm (Gridiv, is)
subroutine codematchestm_class (Gridiv, is, ii)
subroutine codematchprof (Gridiv, SurfaceCharCodeCol)
subroutine codematchdist (rr, CodeCol, codeColSameSurf)
subroutine codematchnonveg (rr, CodeCol)
subroutine codematchveg (rr, CodeCol)
subroutine codematchwater (rr, CodeCol)
subroutine codematchsnow (rr, CodeCol)
subroutine codematchconductance (rr, CodeCol)
subroutine codematchanthropogenic (rr, CodeCol)
subroutine codematchirrigation (rr, CodeCol)
subroutine codematchsoil (Gridiv, SurfaceCharCodeCol)
subroutine codematchbiogen (Gridiv, SurfaceCharCodeCol)
subroutine metdisagg::disaggregatemet (iBlock, igrid)
subroutine metdisagg::disaggregateestm (iBlock)
subroutine metdisagg::disaggregatedatetime (DateTimeForDisagg, tstep, Nper, ReadLinesOrigMetDataMax, DateTimeDscd)
real(kind(1d0)) function, dimension(readlinesorig_loc *nper_loc) metdisagg::disagg_lin (Slow, SlowPrev, SlowNext, DisaggType, Nper_loc, ReadLinesOrig_loc, ReadLinesOrigMax_loc, iBlock)
real(kind(1d0)) function, dimension(readlinesorig_loc *nper_loc) metdisagg::disaggp_amongn (Slow, amongN, Nper_loc, ReadLinesOrig_loc, ReadLinesOrigMax_loc)
real(kind(1d0)) function, dimension(readlinesorig_loc *nper_loc) metdisagg::disaggp_amongnmult (Slow, multupperI, multamongN, Nper_loc, ReadLinesOrig_loc, ReadLinesOrigMax_loc)
integer function, dimension(:), allocatable metdisagg::randomsamples (N, OutOf)
Variables
character(len=90), dimension(14) run_info::text
integer run_info::lim0 = 0
integer run_info::lim1 = 1
integer run_info::lim2 = 2
integer run_info::lim4 = 4
integer run_info::lim3 = 3
integer run_info::lim6 = 6
integer run_info::lim8 = 8
integer run_info::lim12 = 12
integer run_info::lfn_us
logical run_info::file_qs
Function/Subroutine Documentation
codematchanthropogenic()
subroutine codematchanthropogenic (integer rr, integer CodeCol)
Definition at line 1228 of file suews_ctrl_input.f95.
    ! Matches AnthropogenicHeat characteristics via codes in SiteSelect
    ! HCW 20 Nov 2014
    ! MH 21 Jun 2017
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesanthropogenic
       IF (anthropogenic_coeff(iv5, ca_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinesanthropogenic) THEN
          WRITE (*, *) 'Program stopped! Anthropogenic code ', siteselect(rr, codecol), &
             'not found in SUEWS_AnthropogenicEmission.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_AnthropogenicEmission.txt', &
                         siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References allocatearray::anthropogenic_coeff, colnamesinputfiles::ca_code, errorhint(), initial::iv5, initial::nlinesanthropogenic, defaultnotused::notused, defaultnotused::notusedi, and allocatearray::siteselect.
Referenced by initializesurfacecharacteristics().
codematchbiogen()
subroutine codematchbiogen (integer Gridiv, integer SurfaceCharCodeCol)
Definition at line 1321 of file suews_ctrl_input.f95.
    ! Matches Biogen characteristics via codes in *SuraceChar*
    ! MH 16 Jun 2017
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: Gridiv
    INTEGER:: SurfaceCharCodeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesbiogen
       IF (biogen_coeff(iv5, cb_code) == surfacechar(gridiv, surfacecharcodecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinesbiogen) THEN
          WRITE (*, *) 'Program stopped! Biogen code ', surfacechar(gridiv, surfacecharcodecol), 'not found in SUEWS_BiogenCO2.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_BiogenCO2.txt', surfacechar(gridiv, surfacecharcodecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References allocatearray::biogen_coeff, colnamesinputfiles::cb_code, errorhint(), initial::iv5, initial::nlinesbiogen, defaultnotused::notused, defaultnotused::notusedi, and allocatearray::surfacechar.
Referenced by initializesurfacecharacteristics().
codematchconductance()
subroutine codematchconductance (integer rr, integer CodeCol)
Definition at line 1198 of file suews_ctrl_input.f95.
    ! Matches Conductance characteristics via codes in SiteSelect
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesconductance
       IF (conductance_coeff(iv5, cc_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinesconductance) THEN
          WRITE (*, *) 'Program stopped! Conductance code ', siteselect(rr, codecol), 'not found in SUEWS_Conductance.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_Conductance.txt', siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::cc_code, allocatearray::conductance_coeff, errorhint(), initial::iv5, initial::nlinesconductance, defaultnotused::notused, defaultnotused::notusedi, and allocatearray::siteselect.
Referenced by initializesurfacecharacteristics().
codematchdist()
subroutine codematchdist (integer rr, integer CodeCol, integer codeColSameSurf)
Definition at line 1019 of file suews_ctrl_input.f95.
    ! Matches within-grid water distribution via codes
    ! Checks water cannot flow from one surface to the same surface
    ! Checks water distribution fractions sum to 1.
    ! HCW 10 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol, codeColSameSurf
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlineswgwaterdist
       IF (wgwaterdist_coeff(iv5, cwg_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlineswgwaterdist) THEN
          WRITE (*, *) 'Program stopped! Within-grid water distribution code ', siteselect(rr, codecol), &
             'not found in SUEWS_WaterDistWithinGrid.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_WaterDistWithinGrid.txt', siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    ! Check water flow to same surface is zero (previously in RunControlByGridByYear in SUEWS_Initial.f95)
    IF (wgwaterdist_coeff(iv5, codecolsamesurf) /= 0) THEN
       CALL errorhint(8, 'Diagonal elements should be zero as water cannot move from one surface to the same surface.', &
                      wgwaterdist_coeff(iv5, codecolsamesurf), notused, notusedi)
    ENDIF
    !! QUESTION: MODIFY THIS?
    ! Check water either moves to runoff or soilstore, but not to both
    ! Model returns an error if both ToRunoff and ToSoilStore are non-zero.
    !! - Probably should remove this...
    !! - Also look at SUEWS_translate, as the non-zero value goes into WaterDist
    IF (wgwaterdist_coeff(iv5, cwg_torunoff) /= 0 .AND. wgwaterdist_coeff(iv5, cwg_tosoilstore) /= 0) THEN
       CALL errorhint(9, 'One of these (ToRunoff,ToSoilStore) should be zero.', &
                      wgwaterdist_coeff(iv5, cwg_torunoff), wgwaterdist_coeff(iv5, cwg_tosoilstore), notusedi)
    ENDIF
    !! Also do for water surface once implemented
    IF (codecol /= c_wgwatercode) THEN   ! Except for Water surface
       ! Check total water distribution from each surface adds up to 1
       IF (sum(wgwaterdist_coeff(iv5, cwg_topaved:cwg_tosoilstore)) > 1.0000001 &
           .OR. sum(wgwaterdist_coeff(iv5, cwg_topaved:cwg_tosoilstore)) < 0.9999999) THEN
          CALL errorhint(8, 'Total water distribution from each surface should add up to 1.', &
                         sum(wgwaterdist_coeff(iv5, cwg_topaved:cwg_tosoilstore)), notused, notusedi)
       ENDIF
    ENDIF
    RETURN
References colnamesinputfiles::c_wgwatercode, colnamesinputfiles::cwg_code, colnamesinputfiles::cwg_topaved, colnamesinputfiles::cwg_torunoff, colnamesinputfiles::cwg_tosoilstore, errorhint(), initial::iv5, initial::nlineswgwaterdist, defaultnotused::notused, defaultnotused::notusedi, allocatearray::siteselect, and allocatearray::wgwaterdist_coeff.
Referenced by initializesurfacecharacteristics().
codematchestm()
subroutine codematchestm (integer Gridiv, integer is)
Definition at line 909 of file suews_ctrl_input.f95.
    ! Matches ESTM coefficients via ESTM code
    ! Modified HCW 16 Jun 2016 - for SUEWS surface types
    !                          - removed summer/winter wet/dry option
    ! S.O. 04 Feb 2016
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: gridiv
    INTEGER:: is
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesestmcoefficients
       IF (estmcoefficients_coeff(iv5, ce_code) == surfacechar(gridiv, c_estmcode(is))) THEN
          EXIT
       ELSEIF (iv5 == nlinesestmcoefficients) THEN
          WRITE (*, *) 'Program stopped! ESTM code', surfacechar(gridiv, c_estmcode(is)), &
             'not found in ESTM_Coefficients.txt for surface', is, '.'
          CALL errorhint(57, 'Cannot find ESTM code', surfacechar(gridiv, c_estmcode(is)), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References allocatearray::c_estmcode, colnamesinputfiles::ce_code, errorhint(), allocatearray::estmcoefficients_coeff, initial::iv5, initial::nlinesestmcoefficients, defaultnotused::notused, defaultnotused::notusedi, and allocatearray::surfacechar.
Referenced by initializesurfacecharacteristics().
codematchestm_class()
subroutine codematchestm_class (integer Gridiv, integer is, integer ii)
Definition at line 942 of file suews_ctrl_input.f95.
    ! Matches ESTM coefficients via ESTM codes in SiteSelect for Paved and Bldgs ESTM classes
    ! HCW 16 Jun 2016
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: gridiv
    INTEGER:: is, ii
    iv5 = 0 ! Reset iv5 to zero
    IF (is == bldgsurf) THEN
       DO iv5 = 1, nlinesestmcoefficients
          IF (estmcoefficients_coeff(iv5, ce_code) == surfacechar(gridiv, c_code_estmclass_bldgs(ii))) THEN
             EXIT
          ELSEIF (iv5 == nlinesestmcoefficients) THEN
             WRITE (*, *) 'Program stopped! ESTM code', surfacechar(gridiv, c_code_estmclass_bldgs(ii)), &
                'not found in ESTM_Coefficients.txt for surface', is, '.'
             CALL errorhint(57, 'Cannot find ESTM code', surfacechar(gridiv, c_code_estmclass_bldgs(ii)), notused, notusedi)
          ENDIF
       ENDDO
    ELSEIF (is == pavsurf) THEN
       DO iv5 = 1, nlinesestmcoefficients
          IF (estmcoefficients_coeff(iv5, ce_code) == surfacechar(gridiv, c_code_estmclass_paved(ii))) THEN
             EXIT
          ELSEIF (iv5 == nlinesestmcoefficients) THEN
             WRITE (*, *) 'Program stopped! ESTM code', surfacechar(gridiv, c_code_estmclass_paved(ii)), &
                'not found in ESTM_Coefficients.txt for surface', is, '.'
             CALL errorhint(57, 'Cannot find ESTM code', surfacechar(gridiv, c_code_estmclass_paved(ii)), notused, notusedi)
          ENDIF
       ENDDO
    ELSE
       WRITE (*, *) 'Problem with CodeMatchESTM_Class (in SUEWS_CodeMatch.f95). ', is, ' not correct. Needs to be either ', &
          '1 = Paved surfaced, 2 = Bldgs surfaces.'
       stop
    ENDIF
    RETURN
References allocatearray::bldgsurf, colnamesinputfiles::c_code_estmclass_bldgs, colnamesinputfiles::c_code_estmclass_paved, colnamesinputfiles::ce_code, errorhint(), allocatearray::estmcoefficients_coeff, initial::iv5, initial::nlinesestmcoefficients, defaultnotused::notused, defaultnotused::notusedi, allocatearray::pavsurf, and allocatearray::surfacechar.
Referenced by initializesurfacecharacteristics().
codematchirrigation()
subroutine codematchirrigation (integer rr, integer CodeCol)
Definition at line 1261 of file suews_ctrl_input.f95.
    ! Matches Irrigation characteristics via codes in SiteSelect
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesirrigation
       IF (irrigation_coeff(iv5, cir_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinesirrigation) THEN
          WRITE (*, *) 'Program stopped! Irrigation code ', siteselect(rr, codecol), 'not found in SUEWS_Irrigation.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_Irrigation.txt', siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::cir_code, errorhint(), allocatearray::irrigation_coeff, initial::iv5, initial::nlinesirrigation, defaultnotused::notused, defaultnotused::notusedi, and allocatearray::siteselect.
Referenced by initializesurfacecharacteristics().
codematchnonveg()
subroutine codematchnonveg (integer rr, integer CodeCol)
Definition at line 1078 of file suews_ctrl_input.f95.
    ! Matches Impervious characteristics via codes in SiteSelect
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesnonveg
       IF (nonveg_coeff(iv5, ci_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinesnonveg) THEN
          WRITE (*, *) 'Program stopped! NonVeg code ', siteselect(rr, codecol), 'not found in SUEWS_NonVeg.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_NonVeg.txt', siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::ci_code, errorhint(), initial::iv5, initial::nlinesnonveg, allocatearray::nonveg_coeff, defaultnotused::notused, defaultnotused::notusedi, and allocatearray::siteselect.
Referenced by initializesurfacecharacteristics().
codematchohm()
subroutine codematchohm (integer Gridiv, integer is, character(len=4) SWWD)
Definition at line 832 of file suews_ctrl_input.f95.
    ! Matches OHM coefficients a1, a2, a3 via OHM codes
    ! for summer/winter wet/dry conditions
    ! HCW 03 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: gridiv
    INTEGER:: is
    CHARACTER(len=4):: SWWD
    iv5 = 0 ! Reset iv5 to zero
    IF (swwd == 'SWet') THEN
       DO iv5 = 1, nlinesohmcoefficients
          IF (ohmcoefficients_coeff(iv5, co_code) == surfacechar(gridiv, c_ohmcode_swet(is))) THEN
             EXIT
          ELSEIF (iv5 == nlinesohmcoefficients) THEN
             WRITE (*, *) 'Program stopped! OHM code (summer wet)', surfacechar(gridiv, c_ohmcode_swet(is)), &
                'not found in OHM_Coefficients.txt for surface', is, '.'
             CALL errorhint(57, 'Cannot find OHM code (summer wet)', surfacechar(gridiv, c_ohmcode_swet(is)), notused, notusedi)
          ENDIF
       ENDDO
    ELSEIF (swwd == 'SDry') THEN
       DO iv5 = 1, nlinesohmcoefficients
          IF (ohmcoefficients_coeff(iv5, co_code) == surfacechar(gridiv, c_ohmcode_sdry(is))) THEN
             EXIT
          ELSEIF (iv5 == nlinesohmcoefficients) THEN
             WRITE (*, *) 'Program stopped! OHM code (summer dry)', surfacechar(gridiv, c_ohmcode_sdry(is)), &
                'not found in OHM_Coefficients.txt for surface', is, '.'
             CALL errorhint(57, 'Cannot find OHM code (summer dry)', surfacechar(gridiv, c_ohmcode_sdry(is)), notused, notusedi)
          ENDIF
       ENDDO
    ELSEIF (swwd == 'WWet') THEN
       DO iv5 = 1, nlinesohmcoefficients
          IF (ohmcoefficients_coeff(iv5, co_code) == surfacechar(gridiv, c_ohmcode_wwet(is))) THEN
             EXIT
          ELSEIF (iv5 == nlinesohmcoefficients) THEN
             WRITE (*, *) 'Program stopped! OHM code (winter wet)', surfacechar(gridiv, c_ohmcode_wwet(is)), &
                'not found in OHM_Coefficients.txt for surface', is, '.'
             CALL errorhint(57, 'Cannot find OHM code (winter wet)', surfacechar(gridiv, c_ohmcode_wwet(is)), notused, notusedi)
          ENDIF
       ENDDO
    ELSEIF (swwd == 'WDry') THEN
       DO iv5 = 1, nlinesohmcoefficients
          IF (ohmcoefficients_coeff(iv5, co_code) == surfacechar(gridiv, c_ohmcode_wdry(is))) THEN
             EXIT
          ELSEIF (iv5 == nlinesohmcoefficients) THEN
             WRITE (*, *) 'Program stopped! OHM code (winter dry)', surfacechar(gridiv, c_ohmcode_wdry(is)), &
                'not found in OHM_Coefficients.txt for surface', is, '.'
             CALL errorhint(57, 'Cannot find OHM code (winter dry)', surfacechar(gridiv, c_ohmcode_wdry(is)), notused, notusedi)
          ENDIF
       ENDDO
    ELSE
       WRITE (*, *) 'Problem with CodeMatchOHM (in SUEWS_CodeMatch.f95). ', swwd, ' not recognised. Needs to be one of: ', &
          'SWet = Summer Wet, SDry = Summer Dry, WWet = WinterWet, WDry = Winter Dry. N.B. Case sensitive. '
       stop
    ENDIF
    RETURN
References allocatearray::c_ohmcode_sdry, allocatearray::c_ohmcode_swet, allocatearray::c_ohmcode_wdry, allocatearray::c_ohmcode_wwet, colnamesinputfiles::co_code, errorhint(), initial::iv5, initial::nlinesohmcoefficients, defaultnotused::notused, defaultnotused::notusedi, allocatearray::ohmcoefficients_coeff, and allocatearray::surfacechar.
Referenced by initializesurfacecharacteristics().
codematchprof()
subroutine codematchprof (integer Gridiv, integer SurfaceCharCodeCol)
Definition at line 988 of file suews_ctrl_input.f95.
    ! Matches Soil characteristics via codes in *SurfaceChar*
    ! for energy use/water use/snow clearing
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: Gridiv
    INTEGER:: SurfaceCharCodeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesprofiles
       IF (profiles_coeff(iv5, cpr_code) == surfacechar(gridiv, surfacecharcodecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinesprofiles) THEN
          WRITE (*, *) 'Program stopped! Profile code ', surfacechar(gridiv, surfacecharcodecol), 'not found in SUEWS_Profiles.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_Profiles.txt', surfacechar(gridiv, surfacecharcodecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::cpr_code, errorhint(), initial::iv5, initial::nlinesprofiles, defaultnotused::notused, defaultnotused::notusedi, allocatearray::profiles_coeff, and allocatearray::surfacechar.
Referenced by initializesurfacecharacteristics().
codematchsnow()
subroutine codematchsnow (integer rr, integer CodeCol)
Definition at line 1168 of file suews_ctrl_input.f95.
    ! Matches Snow characteristics via codes in SiteSelect
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinessnow
       IF (snow_coeff(iv5, cs_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinessnow) THEN
          WRITE (*, *) 'Program stopped! Snow code ', siteselect(rr, codecol), 'not found in SUEWS_Snow.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_Snow.txt', siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::cs_code, errorhint(), initial::iv5, initial::nlinessnow, defaultnotused::notused, defaultnotused::notusedi, allocatearray::siteselect, and allocatearray::snow_coeff.
Referenced by initializesurfacecharacteristics().
codematchsoil()
subroutine codematchsoil (integer Gridiv, integer SurfaceCharCodeCol)
Definition at line 1291 of file suews_ctrl_input.f95.
    ! Matches Soil characteristics via codes in *SurfaceChar*
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: Gridiv
    INTEGER:: SurfaceCharCodeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinessoil
       IF (soil_coeff(iv5, cso_code) == surfacechar(gridiv, surfacecharcodecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinessoil) THEN
          WRITE (*, *) 'Program stopped! Soil code ', surfacechar(gridiv, surfacecharcodecol), 'not found in SUEWS_Soil.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_Soil.txt', surfacechar(gridiv, surfacecharcodecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::cso_code, errorhint(), initial::iv5, initial::nlinessoil, defaultnotused::notused, defaultnotused::notusedi, allocatearray::soil_coeff, and allocatearray::surfacechar.
Referenced by initializesurfacecharacteristics().
codematchveg()
subroutine codematchveg (integer rr, integer CodeCol)
Definition at line 1108 of file suews_ctrl_input.f95.
    ! Matches Pervious characteristics via codes in SiteSelect
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlinesveg
       IF (veg_coeff(iv5, cp_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlinesveg) THEN
          WRITE (*, *) 'Program stopped! Veg code ', siteselect(rr, codecol), 'not found in SUEWS_Vegs.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_Veg.txt', siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::cp_code, errorhint(), initial::iv5, initial::nlinesveg, defaultnotused::notused, defaultnotused::notusedi, allocatearray::siteselect, and allocatearray::veg_coeff.
Referenced by initializesurfacecharacteristics().
codematchwater()
subroutine codematchwater (integer rr, integer CodeCol)
Definition at line 1138 of file suews_ctrl_input.f95.
    ! Matches Water characteristics via codes in SiteSelect
    ! HCW 20 Nov 2014
    ! ---------------------------------------------------------
    USE allocatearray
    USE initial
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    INTEGER:: rr
    INTEGER:: codeCol
    iv5 = 0 ! Reset iv5 to zero
    DO iv5 = 1, nlineswater
       IF (water_coeff(iv5, cw_code) == siteselect(rr, codecol)) THEN
          EXIT
       ELSEIF (iv5 == nlineswater) THEN
          WRITE (*, *) 'Program stopped! Water code ', siteselect(rr, codecol), 'not found in SUEWS_Water.txt.'
          CALL errorhint(57, 'Cannot find code in SUEWS_Water.txt', siteselect(rr, codecol), notused, notusedi)
       ENDIF
    ENDDO
    RETURN
References colnamesinputfiles::cw_code, errorhint(), initial::iv5, initial::nlineswater, defaultnotused::notused, defaultnotused::notusedi, allocatearray::siteselect, and allocatearray::water_coeff.
Referenced by initializesurfacecharacteristics().
get_prof_spectime_inst()
real(kind(1d0)) function get_prof_spectime_inst (integer, intent(in) Hour, integer, intent(in) Min, integer, intent(in) Sec, real(kind(1d0)), dimension(0:23), intent(in) Prof_24h)
Definition at line 743 of file suews_ctrl_input.f95.
    IMPLICIT NONE
    INTEGER :: i, j   !Used to count over hours and sub-hourly timesteps
    INTEGER, INTENT(IN) :: Hour, Min, Sec
    INTEGER :: total_sec, SecPerHour
    REAL(KIND(1d0)), DIMENSION(0:23), INTENT(IN) :: Prof_24h
    REAL(KIND(1d0)):: deltaProf   !Change in hourly profiles per model timestep
    REAL(KIND(1d0)) :: Prof_CurrTime
    total_sec = min*60 + sec
    secperhour = 3600
    i = hour
    j = i + 1
    IF (j == 24) j = 0
    deltaprof = (prof_24h(j) - prof_24h(i))/secperhour
    prof_currtime = prof_24h(hour) + deltaprof*total_sec
get_prof_spectime_mean()
real(kind(1d0)) function get_prof_spectime_mean (integer, intent(in) Hour, integer, intent(in) Min, integer, intent(in) Sec, real(kind(1d0)), dimension(0:23), intent(in) Prof_24h)
Definition at line 769 of file suews_ctrl_input.f95.
    IMPLICIT NONE
    INTEGER :: i, j   !Used to count over hours and sub-hourly timesteps
    INTEGER, INTENT(IN) :: Hour, Min, Sec
    INTEGER :: total_sec, SecPerHour
    REAL(KIND(1d0)), DIMENSION(0:23), INTENT(IN) :: Prof_24h
    REAL(KIND(1d0)), DIMENSION(0:23):: Prof_24h_mean
    REAL(KIND(1d0)):: deltaProf   !Change in hourly profiles per model timestep
    REAL(KIND(1d0)) :: Prof_CurrTime
    total_sec = min*60 + sec
    secperhour = 3600
    prof_24h_mean = merge(prof_24h/(sum(prof_24h)/size(prof_24h, dim=1)), 0.d0, sum(prof_24h) /= 0) ! prevent zero-division
    ! print*, Prof_24h_mean
    i = hour
    j = i + 1
    IF (j == 24) j = 0
    deltaprof = (prof_24h_mean(j) - prof_24h_mean(i))/secperhour
    ! print*, deltaProf,total_sec
    prof_currtime = prof_24h_mean(i) + deltaprof*total_sec
get_prof_spectime_sum()
real(kind(1d0)) function get_prof_spectime_sum (integer, intent(in) Hour, integer, intent(in) Min, integer, intent(in) Sec, real(kind(1d0)), dimension(0:23), intent(in) Prof_24h, integer, intent(in) dt)
Definition at line 801 of file suews_ctrl_input.f95.
    IMPLICIT NONE
    INTEGER :: i, j   !Used to count over hours and sub-hourly timesteps
    INTEGER, INTENT(IN) :: Hour, Min, Sec, dt
    INTEGER :: total_sec, SecPerHour
    REAL(KIND(1d0)), DIMENSION(0:23), INTENT(IN) :: Prof_24h
    REAL(KIND(1d0)), DIMENSION(0:23):: Prof_24h_sum
    REAL(KIND(1d0)):: deltaProf   !Change in hourly profiles per model timestep
    REAL(KIND(1d0)) :: Prof_CurrTime
    total_sec = min*60 + sec
    secperhour = 3600
    prof_24h_sum = merge(prof_24h/(sum(prof_24h)), 0.d0, sum(prof_24h) /= 0) ! prevent zero-division
    i = hour
    j = i + 1
    IF (j == 24) j = 0
    deltaprof = (prof_24h_sum(j) - prof_24h_sum(i))/secperhour
    prof_currtime = prof_24h_sum(hour) + deltaprof*total_sec
    prof_currtime = prof_currtime*dt/secperhour
inputheadercheck()
subroutine inputheadercheck (character(len=50) FileName)
Definition at line 256 of file suews_ctrl_input.f95.
    ! Checks columns in input files match the columns expected by model code
    ! Model code columns are defined here
    ! Latest update:
    !   MH 21 Jun 2017 - Added parameters to SUEWS_AnthropogenicEmissions.txt
    !   MH 16 Jun 2017 - Added SUEWS_BiogenCO2.txt
    !   TS 02 Mar 2016  - AnOHM related variables added
    !   LJ 27 Jan 2016  - Removal of tabs
    !   LJ 07 July 2015 - snow albedo removed
    !   HCW 12 Nov 2014
    !-------------------------------------------------------------------------
    USE allocatearray
    USE colnamesinputfiles
    USE defaultnotused
    IMPLICIT NONE
    CHARACTER(len=50):: FileName
    ! ========== Define expected column names here ==========
    ! =======================================================
    ! ========== SUEWS_NonVeg.txt =============
    headernonveg_reqd(ci_code) = "Code"
    headernonveg_reqd(ci_albmin) = "AlbedoMin"
    headernonveg_reqd(ci_albmax) = "AlbedoMax"
    headernonveg_reqd(ci_emis) = "Emissivity"
    headernonveg_reqd(ci_stormin) = "StorageMin"
    headernonveg_reqd(ci_stormax) = "StorageMax"
    headernonveg_reqd(ci_wetthresh) = "WetThreshold"
    headernonveg_reqd(ci_statelimit) = "StateLimit"
    headernonveg_reqd(ci_dreq) = "DrainageEq"
    headernonveg_reqd(ci_drcoef1) = "DrainageCoef1"
    headernonveg_reqd(ci_drcoef2) = "DrainageCoef2"
    headernonveg_reqd(ci_soiltcode) = "SoilTypeCode"
    headernonveg_reqd(ci_snowlimpat) = "SnowLimPatch"
    headernonveg_reqd(ci_snowlimrem) = "SnowLimRemove"
    headernonveg_reqd(ci_ohmcode_swet) = "OHMCode_SummerWet"
    headernonveg_reqd(ci_ohmcode_sdry) = "OHMCode_SummerDry"
    headernonveg_reqd(ci_ohmcode_wwet) = "OHMCode_WinterWet"
    headernonveg_reqd(ci_ohmcode_wdry) = "OHMCode_WinterDry"
    headernonveg_reqd(ci_ohmthresh_sw) = "OHMThresh_SW"
    headernonveg_reqd(ci_ohmthresh_wd) = "OHMThresh_WD"
    headernonveg_reqd(ci_estmcode) = "ESTMCode"
    headernonveg_reqd(ci_cpanohm) = "AnOHM_Cp" ! AnOHM TS
    headernonveg_reqd(ci_kkanohm) = "AnOHM_Kk" ! AnOHM TS
    headernonveg_reqd(ci_chanohm) = "AnOHM_Ch" ! AnOHM TS
    ! ========== SUEWS_Veg.txt ===============
    headerveg_reqd(cp_code) = "Code"
    headerveg_reqd(cp_albmin) = "AlbedoMin"
    headerveg_reqd(cp_albmax) = "AlbedoMax"
    headerveg_reqd(cp_emis) = "Emissivity"
    headerveg_reqd(cp_stormin) = "StorageMin"
    headerveg_reqd(cp_stormax) = "StorageMax"
    headerveg_reqd(cp_wetthresh) = "WetThreshold"
    headerveg_reqd(cp_statelimit) = "StateLimit"
    headerveg_reqd(cp_dreq) = "DrainageEq"
    headerveg_reqd(cp_drcoef1) = "DrainageCoef1"
    headerveg_reqd(cp_drcoef2) = "DrainageCoef2"
    headerveg_reqd(cp_soiltcode) = "SoilTypeCode"
    headerveg_reqd(cp_snowlimpat) = "SnowLimPatch"
    headerveg_reqd(cp_baset) = "BaseT"
    headerveg_reqd(cp_basete) = "BaseTe"
    headerveg_reqd(cp_gddfull) = "GDDFull"
    headerveg_reqd(cp_sddfull) = "SDDFull"
    headerveg_reqd(cp_laimin) = "LAIMin"
    headerveg_reqd(cp_laimax) = "LAIMax"
    headerveg_reqd(cp_porositymin) = "PorosityMin"
    headerveg_reqd(cp_porositymax) = "PorosityMax"
    headerveg_reqd(cp_gsmax) = "MaxConductance"
    headerveg_reqd(cp_laieq) = "LAIEq"
    headerveg_reqd(cp_leafgp1) = "LeafGrowthPower1"
    headerveg_reqd(cp_leafgp2) = "LeafGrowthPower2"
    headerveg_reqd(cp_leafop1) = "LeafOffPower1"
    headerveg_reqd(cp_leafop2) = "LeafOffPower2"
    headerveg_reqd(cp_ohmcode_swet) = "OHMCode_SummerWet"
    headerveg_reqd(cp_ohmcode_sdry) = "OHMCode_SummerDry"
    headerveg_reqd(cp_ohmcode_wwet) = "OHMCode_WinterWet"
    headerveg_reqd(cp_ohmcode_wdry) = "OHMCode_WinterDry"
    headerveg_reqd(cp_ohmthresh_sw) = "OHMThresh_SW"
    headerveg_reqd(cp_ohmthresh_wd) = "OHMThresh_WD"
    headerveg_reqd(cp_estmcode) = "ESTMCode"
    headerveg_reqd(cp_cpanohm) = "AnOHM_Cp" ! AnOHM TS
    headerveg_reqd(cp_kkanohm) = "AnOHM_Kk" ! AnOHM TS
    headerveg_reqd(cp_chanohm) = "AnOHM_Ch" ! AnOHM TS
    headerveg_reqd(cp_biogenco2code) = "BiogenCO2Code"
    ! ========== SUEWS_Water.txt ==================
    headerwater_reqd(cw_code) = "Code"
    headerwater_reqd(cw_albmin) = "AlbedoMin"
    headerwater_reqd(cw_albmax) = "AlbedoMax"
    headerwater_reqd(cw_emis) = "Emissivity"
    headerwater_reqd(cw_stormin) = "StorageMin"
    headerwater_reqd(cw_stormax) = "StorageMax"
    headerwater_reqd(cw_wetthresh) = "WetThreshold"
    headerwater_reqd(cw_statelimit) = "StateLimit"
    headerwater_reqd(cw_waterdepth) = "WaterDepth"
    headerwater_reqd(cw_dreq) = "DrainageEq"
    headerwater_reqd(cw_drcoef1) = "DrainageCoef1"
    headerwater_reqd(cw_drcoef2) = "DrainageCoef2"
    headerwater_reqd(cw_ohmcode_swet) = "OHMCode_SummerWet"
    headerwater_reqd(cw_ohmcode_sdry) = "OHMCode_SummerDry"
    headerwater_reqd(cw_ohmcode_wwet) = "OHMCode_WinterWet"
    headerwater_reqd(cw_ohmcode_wdry) = "OHMCode_WinterDry"
    headerwater_reqd(cw_ohmthresh_sw) = "OHMThresh_SW"
    headerwater_reqd(cw_ohmthresh_wd) = "OHMThresh_WD"
    headerwater_reqd(cw_estmcode) = "ESTMCode"
    headerwater_reqd(cw_cpanohm) = "AnOHM_Cp" ! AnOHM TS
    headerwater_reqd(cw_kkanohm) = "AnOHM_Kk" ! AnOHM TS
    headerwater_reqd(cw_chanohm) = "AnOHM_Ch" ! AnOHM TS
    ! ========== SUEWS_Snow.txt ===================
    headersnow_reqd(cs_code) = "Code"
    headersnow_reqd(cs_snowrmfactor) = "RadMeltFactor"
    headersnow_reqd(cs_snowtmfactor) = "TempMeltFactor"
    headersnow_reqd(cs_snowalbmin) = "AlbedoMin"
    headersnow_reqd(cs_snowalbmax) = "AlbedoMax"
    headersnow_reqd(cs_snowemis) = "Emissivity"
    headersnow_reqd(cs_snowtau_a) = "tau_a"
    headersnow_reqd(cs_snowtau_f) = "tau_f"
    headersnow_reqd(cs_snowplimalb) = "PrecipLimAlb"
    headersnow_reqd(cs_snowsdmin) = "SnowDensMin"
    headersnow_reqd(cs_snowsdmax) = "SnowDensMax"
    headersnow_reqd(cs_snowtau_r) = "tau_r"
    headersnow_reqd(cs_snowcrwmin) = "CRWMin"
    headersnow_reqd(cs_snowcrwmax) = "CRWMax"
    headersnow_reqd(cs_snowplimsnow) = "PrecipLimSnow"
    headersnow_reqd(cs_ohmcode_swet) = "OHMCode_SummerWet"
    headersnow_reqd(cs_ohmcode_sdry) = "OHMCode_SummerDry"
    headersnow_reqd(cs_ohmcode_wwet) = "OHMCode_WinterWet"
    headersnow_reqd(cs_ohmcode_wdry) = "OHMCode_WinterDry"
    headersnow_reqd(cs_ohmthresh_sw) = "OHMThresh_SW"
    headersnow_reqd(cs_ohmthresh_wd) = "OHMThresh_WD"
    headersnow_reqd(cs_estmcode) = "ESTMCode"
    headersnow_reqd(cs_cpanohm) = "AnOHM_Cp"    ! AnOHM TS
    headersnow_reqd(cs_kkanohm) = "AnOHM_Kk"    ! AnOHM TS
    headersnow_reqd(cs_chanohm) = "AnOHM_Ch"    ! AnOHM TS
    ! ========== SUEWS_Soil.txt ===================
    headersoil_reqd(cso_code) = "Code"
    headersoil_reqd(cso_soildepth) = "SoilDepth"
    headersoil_reqd(cso_soilstcap) = "SoilStoreCap"
    headersoil_reqd(cso_ksat) = "SatHydraulicCond"
    headersoil_reqd(cso_soildens) = "SoilDensity"
    headersoil_reqd(cso_soilinfrate) = "InfiltrationRate"
    headersoil_reqd(cso_obssmdepth) = "OBS_SMDepth"
    headersoil_reqd(cso_obssmmax) = "OBS_SMCap"
    headersoil_reqd(cso_obssnrfrac) = "OBS_SoilNotRocks"
    ! ========== SUEWS_Conductance.txt ============
    headercond_reqd(cc_code) = "Code"
    headercond_reqd(cc_gsg1) = "G1"
    headercond_reqd(cc_gsg2) = "G2"
    headercond_reqd(cc_gsg3) = "G3"
    headercond_reqd(cc_gsg4) = "G4"
    headercond_reqd(cc_gsg5) = "G5"
    headercond_reqd(cc_gsg6) = "G6"
    headercond_reqd(cc_gsth) = "TH"
    headercond_reqd(cc_gstl) = "TL"
    headercond_reqd(cc_gss1) = "S1"
    headercond_reqd(cc_gss2) = "S2"
    headercond_reqd(cc_gskmax) = "Kmax"
    headercond_reqd(cc_gsmodel) = "gsModel"
    ! ========== SUEWS_OHMCoefficients.txt ========
    headerohmcoefficients_reqd(co_code) = "Code"
    headerohmcoefficients_reqd(co_a1) = "a1"
    headerohmcoefficients_reqd(co_a2) = "a2"
    headerohmcoefficients_reqd(co_a3) = "a3"
    ! ========== SUEWS_ESTMCoefficients.txt ========
    headerestmcoefficients_reqd(ce_code) = "Code"
    headerestmcoefficients_reqd(ce_surf_thick1) = "Surf_thick1"
    headerestmcoefficients_reqd(ce_surf_k1) = "Surf_k1"
    headerestmcoefficients_reqd(ce_surf_rhocp1) = "Surf_rhoCp1"
    headerestmcoefficients_reqd(ce_surf_thick2) = "Surf_thick2"
    headerestmcoefficients_reqd(ce_surf_k2) = "Surf_k2"
    headerestmcoefficients_reqd(ce_surf_rhocp2) = "Surf_rhoCp2"
    headerestmcoefficients_reqd(ce_surf_thick3) = "Surf_thick3"
    headerestmcoefficients_reqd(ce_surf_k3) = "Surf_k3"
    headerestmcoefficients_reqd(ce_surf_rhocp3) = "Surf_rhoCp3"
    headerestmcoefficients_reqd(ce_surf_thick4) = "Surf_thick4"
    headerestmcoefficients_reqd(ce_surf_k4) = "Surf_k4"
    headerestmcoefficients_reqd(ce_surf_rhocp4) = "Surf_rhoCp4"
    headerestmcoefficients_reqd(ce_surf_thick5) = "Surf_thick5"
    headerestmcoefficients_reqd(ce_surf_k5) = "Surf_k5"
    headerestmcoefficients_reqd(ce_surf_rhocp5) = "Surf_rhoCp5"
    headerestmcoefficients_reqd(ce_wall_thick1) = "Wall_thick1"
    headerestmcoefficients_reqd(ce_wall_k1) = "Wall_k1"
    headerestmcoefficients_reqd(ce_wall_rhocp1) = "Wall_rhoCp1"
    headerestmcoefficients_reqd(ce_wall_thick2) = "Wall_thick2"
    headerestmcoefficients_reqd(ce_wall_k2) = "Wall_k2"
    headerestmcoefficients_reqd(ce_wall_rhocp2) = "Wall_rhoCp2"
    headerestmcoefficients_reqd(ce_wall_thick3) = "Wall_thick3"
    headerestmcoefficients_reqd(ce_wall_k3) = "Wall_k3"
    headerestmcoefficients_reqd(ce_wall_rhocp3) = "Wall_rhoCp3"
    headerestmcoefficients_reqd(ce_wall_thick4) = "Wall_thick4"
    headerestmcoefficients_reqd(ce_wall_k4) = "Wall_k4"
    headerestmcoefficients_reqd(ce_wall_rhocp4) = "Wall_rhoCp4"
    headerestmcoefficients_reqd(ce_wall_thick5) = "Wall_thick5"
    headerestmcoefficients_reqd(ce_wall_k5) = "Wall_k5"
    headerestmcoefficients_reqd(ce_wall_rhocp5) = "Wall_rhoCp5"
    headerestmcoefficients_reqd(ce_internal_thick1) = "Internal_thick1"
    headerestmcoefficients_reqd(ce_internal_k1) = "Internal_k1"
    headerestmcoefficients_reqd(ce_internal_rhocp1) = "Internal_rhoCp1"
    headerestmcoefficients_reqd(ce_internal_thick2) = "Internal_thick2"
    headerestmcoefficients_reqd(ce_internal_k2) = "Internal_k2"
    headerestmcoefficients_reqd(ce_internal_rhocp2) = "Internal_rhoCp2"
    headerestmcoefficients_reqd(ce_internal_thick3) = "Internal_thick3"
    headerestmcoefficients_reqd(ce_internal_k3) = "Internal_k3"
    headerestmcoefficients_reqd(ce_internal_rhocp3) = "Internal_rhoCp3"
    headerestmcoefficients_reqd(ce_internal_thick4) = "Internal_thick4"
    headerestmcoefficients_reqd(ce_internal_k4) = "Internal_k4"
    headerestmcoefficients_reqd(ce_internal_rhocp4) = "Internal_rhoCp4"
    headerestmcoefficients_reqd(ce_internal_thick5) = "Internal_thick5"
    headerestmcoefficients_reqd(ce_internal_k5) = "Internal_k5"
    headerestmcoefficients_reqd(ce_internal_rhocp5) = "Internal_rhoCp5"
    headerestmcoefficients_reqd(ce_nroom) = "nroom"
    headerestmcoefficients_reqd(ce_alb_ibld) = "Internal_albedo"
    headerestmcoefficients_reqd(ce_em_ibld) = "Internal_emissivity"
    headerestmcoefficients_reqd(ce_ch_iwall) = "Internal_CHwall"
    headerestmcoefficients_reqd(ce_ch_iroof) = "Internal_CHroof"
    headerestmcoefficients_reqd(ce_ch_ibld) = "Internal_CHbld"
    ! ========== SUEWS_AnthropogenicEmission.txt ======
    headeranthropogenic_reqd(ca_code) = "Code"
    headeranthropogenic_reqd(ca_basethdd) = "BaseTHDD"
    headeranthropogenic_reqd(ca_qf_a1) = "QF_A_WD"
    headeranthropogenic_reqd(ca_qf_b1) = "QF_B_WD"
    headeranthropogenic_reqd(ca_qf_c1) = "QF_C_WD"
    headeranthropogenic_reqd(ca_qf_a2) = "QF_A_WE"
    headeranthropogenic_reqd(ca_qf_b2) = "QF_B_WE"
    headeranthropogenic_reqd(ca_qf_c2) = "QF_C_WE"
    headeranthropogenic_reqd(ca_ahmin_wd) = "AHMin_WD"
    headeranthropogenic_reqd(ca_ahmin_we) = "AHMin_WE"
    headeranthropogenic_reqd(ca_ahslopeheating_wd) = "AHSlope_Heating_WD"
    headeranthropogenic_reqd(ca_ahslopeheating_we) = "AHSlope_Heating_WE"
    headeranthropogenic_reqd(ca_ahslopecooling_wd) = "AHSlope_Cooling_WD"
    headeranthropogenic_reqd(ca_ahslopecooling_we) = "AHSlope_Cooling_WE"
    headeranthropogenic_reqd(ca_tcriticheating_wd) = "TCritic_Heating_WD"
    headeranthropogenic_reqd(ca_tcriticheating_we) = "TCritic_Heating_WE"
    headeranthropogenic_reqd(ca_tcriticcooling_wd) = "TCritic_Cooling_WD"
    headeranthropogenic_reqd(ca_tcriticcooling_we) = "TCritic_Cooling_WE"
    headeranthropogenic_reqd(ca_enprofwd) = "EnergyUseProfWD"
    headeranthropogenic_reqd(ca_enprofwe) = "EnergyUseProfWE"
    headeranthropogenic_reqd(ca_co2mwd) = "ActivityProfWD"
    headeranthropogenic_reqd(ca_co2mwe) = "ActivityProfWE"
    headeranthropogenic_reqd(ca_traffprofwd) = "TraffProfWD"
    headeranthropogenic_reqd(ca_traffprofwe) = "TraffProfWE"
    headeranthropogenic_reqd(ca_popprofwd) = "PopProfWD"
    headeranthropogenic_reqd(ca_popprofwe) = "PopProfWE"
    headeranthropogenic_reqd(ca_minqfmetab) = "MinQFMetab"
    headeranthropogenic_reqd(ca_maxqfmetab) = "MaxQFMetab"
    headeranthropogenic_reqd(ca_minfcmetab) = "MinFCMetab"
    headeranthropogenic_reqd(ca_maxfcmetab) = "MaxFCMetab"
    headeranthropogenic_reqd(ca_frpddwe) = "FrPDDwe"
    headeranthropogenic_reqd(ca_frfossilfuel_heat) = "FrFossilFuel_Heat"
    headeranthropogenic_reqd(ca_frfossilfuel_nonheat) = "FrFossilFuel_NonHeat"
    headeranthropogenic_reqd(ca_ef_umolco2perj) = "EF_umolCO2perJ"
    headeranthropogenic_reqd(ca_enef_v_jkm) = "EnEF_v_Jkm"
    headeranthropogenic_reqd(ca_fcef_v_kgkmwd) = "FcEF_v_kgkmWD"
    headeranthropogenic_reqd(ca_fcef_v_kgkmwe) = "FcEF_v_kgkmWE"
    headeranthropogenic_reqd(ca_co2pointsource) = "CO2PointSource"
    headeranthropogenic_reqd(ca_trafficunits) = "TrafficUnits"
    ! ========== SUEWS_Irrigation.txt =============
    headerirrigation_reqd(cir_code) = "Code"
    headerirrigation_reqd(cir_iestart) = "Ie_start"
    headerirrigation_reqd(cir_ieend) = "Ie_end"
    headerirrigation_reqd(cir_intwu) = "InternalWaterUse"
    headerirrigation_reqd(cir_faut) = "Faut"
    headerirrigation_reqd(cir_ie_a1) = "Ie_a1"
    headerirrigation_reqd(cir_ie_a2) = "Ie_a2"
    headerirrigation_reqd(cir_ie_a3) = "Ie_a3"
    headerirrigation_reqd(cir_ie_m1) = "Ie_m1"
    headerirrigation_reqd(cir_ie_m2) = "Ie_m2"
    headerirrigation_reqd(cir_ie_m3) = "Ie_m3"
    headerirrigation_reqd(cir_daywat1) = "DayWat(1)"
    headerirrigation_reqd(cir_daywat2) = "DayWat(2)"
    headerirrigation_reqd(cir_daywat3) = "DayWat(3)"
    headerirrigation_reqd(cir_daywat4) = "DayWat(4)"
    headerirrigation_reqd(cir_daywat5) = "DayWat(5)"
    headerirrigation_reqd(cir_daywat6) = "DayWat(6)"
    headerirrigation_reqd(cir_daywat7) = "DayWat(7)"
    headerirrigation_reqd(cir_daywatper1) = "DayWatPer(1)"
    headerirrigation_reqd(cir_daywatper2) = "DayWatPer(2)"
    headerirrigation_reqd(cir_daywatper3) = "DayWatPer(3)"
    headerirrigation_reqd(cir_daywatper4) = "DayWatPer(4)"
    headerirrigation_reqd(cir_daywatper5) = "DayWatPer(5)"
    headerirrigation_reqd(cir_daywatper6) = "DayWatPer(6)"
    headerirrigation_reqd(cir_daywatper7) = "DayWatPer(7)"
    ! ========== SUEWS_Profiles.txt ===============
    headerprofiles_reqd(cpr_code) = "Code"
    headerprofiles_reqd(cpr_hours(1)) = "0"
    headerprofiles_reqd(cpr_hours(2)) = "1"
    headerprofiles_reqd(cpr_hours(3)) = "2"
    headerprofiles_reqd(cpr_hours(4)) = "3"
    headerprofiles_reqd(cpr_hours(5)) = "4"
    headerprofiles_reqd(cpr_hours(6)) = "5"
    headerprofiles_reqd(cpr_hours(7)) = "6"
    headerprofiles_reqd(cpr_hours(8)) = "7"
    headerprofiles_reqd(cpr_hours(9)) = "8"
    headerprofiles_reqd(cpr_hours(10)) = "9"
    headerprofiles_reqd(cpr_hours(11)) = "10"
    headerprofiles_reqd(cpr_hours(12)) = "11"
    headerprofiles_reqd(cpr_hours(13)) = "12"
    headerprofiles_reqd(cpr_hours(14)) = "13"
    headerprofiles_reqd(cpr_hours(15)) = "14"
    headerprofiles_reqd(cpr_hours(16)) = "15"
    headerprofiles_reqd(cpr_hours(17)) = "16"
    headerprofiles_reqd(cpr_hours(18)) = "17"
    headerprofiles_reqd(cpr_hours(19)) = "18"
    headerprofiles_reqd(cpr_hours(20)) = "19"
    headerprofiles_reqd(cpr_hours(21)) = "20"
    headerprofiles_reqd(cpr_hours(22)) = "21"
    headerprofiles_reqd(cpr_hours(23)) = "22"
    headerprofiles_reqd(cpr_hours(24)) = "23"
    ! ========== SUEWS_WithinGridWaterDist.txt ====
    headerwgwaterdist_reqd(cwg_code) = "Code"
    headerwgwaterdist_reqd(cwg_topaved) = "ToPaved"
    headerwgwaterdist_reqd(cwg_tobldgs) = "ToBldgs"
    headerwgwaterdist_reqd(cwg_toevetr) = "ToEveTr"
    headerwgwaterdist_reqd(cwg_todectr) = "ToDecTr"
    headerwgwaterdist_reqd(cwg_tograss) = "ToGrass"
    headerwgwaterdist_reqd(cwg_tobsoil) = "ToBSoil"
    headerwgwaterdist_reqd(cwg_towater) = "ToWater"
    headerwgwaterdist_reqd(cwg_torunoff) = "ToRunoff"
    headerwgwaterdist_reqd(cwg_tosoilstore) = "ToSoilStore"
    ! ========== SUEWS_BiogenCO2.txt ======
    headerbiogen_reqd(cb_code) = "Code"
    headerbiogen_reqd(cb_alpha) = "alpha"
    headerbiogen_reqd(cb_beta) = "beta"
    headerbiogen_reqd(cb_theta) = "theta"
    headerbiogen_reqd(cb_alpha_enh) = "alpha_enh"
    headerbiogen_reqd(cb_beta_enh) = "beta_enh"
    headerbiogen_reqd(cb_resp_a) = "resp_a"
    headerbiogen_reqd(cb_resp_b) = "resp_b"
    headerbiogen_reqd(cb_min_r) = "min_respi"
    ! =======================================================
    !write(*,*) 'Checking header for ', FileName
    ! Check columns in input files match model code
    IF (filename == 'SUEWS_NonVeg.txt') THEN
       IF (any(headernonveg_file /= headernonveg_reqd)) THEN
          WRITE (*, *) headernonveg_file == headernonveg_reqd
          WRITE (*, *) headernonveg_file
          WRITE (*, *) headernonveg_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_NonVeg.txt does not match model code.', notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_Veg.txt') THEN
       IF (any(headerveg_file /= headerveg_reqd)) THEN
          WRITE (*, *) headerveg_file == headerveg_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_Veg.txt does not match model code.', notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_Water.txt') THEN
       IF (any(headerwater_file /= headerwater_reqd)) THEN
          WRITE (*, *) headerwater_file == headerwater_reqd
          WRITE (*, *) headerwater_file
          WRITE (*, *) headerwater_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_Water.txt does not match model code.', notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_Snow.txt') THEN
       IF (any(headersnow_file /= headersnow_reqd)) THEN
          WRITE (*, *) headersnow_file == headersnow_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_Snow.txt does not match model code.', notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_Soil.txt') THEN
       IF (any(headersoil_file /= headersoil_reqd)) THEN
          WRITE (*, *) headersoil_file == headersoil_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_Soil.txt does not match model code.', notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_Conductance.txt') THEN
       IF (any(headercond_file /= headercond_reqd)) THEN
          WRITE (*, *) headercond_file == headercond_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_Cond.txt does not match model code.', notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_OHMCoefficients.txt') THEN
       IF (any(headerohmcoefficients_file /= headerohmcoefficients_reqd)) THEN
          WRITE (*, *) headerohmcoefficients_file == headerohmcoefficients_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_OHMCoefficients.txt does not match model code.', &
                         notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_ESTMCoefficients.txt') THEN
       IF (any(headerestmcoefficients_file /= headerestmcoefficients_reqd)) THEN
          WRITE (*, *) headerestmcoefficients_file == headerestmcoefficients_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_ESTMCoefficients.txt does not match model code.', &
                         notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_AnthropogenicEmission.txt') THEN
       IF (any(headeranthropogenic_file /= headeranthropogenic_reqd)) THEN
          WRITE (*, *) headeranthropogenic_file == headeranthropogenic_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_AnthropogenicEmission.txt does not match model code.', &
                         notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_Irrigation.txt') THEN
       IF (any(headerirrigation_file /= headerirrigation_reqd)) THEN
          WRITE (*, *) headerirrigation_file == headerirrigation_reqd
          WRITE (*, *) headerirrigation_file
          WRITE (*, *) headerirrigation_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_Irrigation.txt does not match model code.', &
                         notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_Profiles.txt') THEN
       IF (any(headerprofiles_file /= headerprofiles_reqd)) THEN
          WRITE (*, *) headerprofiles_file == headerprofiles_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_Profiles.txt does not match model code.', &
                         notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_WithinGridWaterDist.txt') THEN
       IF (any(headerwgwaterdist_file /= headerwgwaterdist_reqd)) THEN
          WRITE (*, *) headerwgwaterdist_file == headerwgwaterdist_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_WithinGridWaterDist.txt does not match model code.', &
                         notused, notused, notusedi)
       ENDIF
    ELSEIF (filename == 'SUEWS_BiogenCO2.txt') THEN
       IF (any(headerbiogen_file /= headerbiogen_reqd)) THEN
          WRITE (*, *) headerbiogen_file == headerbiogen_reqd
          CALL errorhint(56, 'Names or order of columns in SUEWS_BiogenCO2.txt does not match model code.', &
                         notused, notused, notusedi)
       ENDIF
    ELSE
       WRITE (*, *) 'Problem in subroutine InputHeaderCheck. File header not specified in model code for ', filename
       CALL errorhint(58, filename, notused, notused, notusedi)
    ENDIF
References colnamesinputfiles::ca_ahmin_wd, colnamesinputfiles::ca_ahmin_we, colnamesinputfiles::ca_ahslopecooling_wd, colnamesinputfiles::ca_ahslopecooling_we, colnamesinputfiles::ca_ahslopeheating_wd, colnamesinputfiles::ca_ahslopeheating_we, colnamesinputfiles::ca_basethdd, colnamesinputfiles::ca_co2mwd, colnamesinputfiles::ca_co2mwe, colnamesinputfiles::ca_co2pointsource, colnamesinputfiles::ca_code, colnamesinputfiles::ca_ef_umolco2perj, colnamesinputfiles::ca_enef_v_jkm, colnamesinputfiles::ca_enprofwd, colnamesinputfiles::ca_enprofwe, colnamesinputfiles::ca_fcef_v_kgkmwd, colnamesinputfiles::ca_fcef_v_kgkmwe, colnamesinputfiles::ca_frfossilfuel_heat, colnamesinputfiles::ca_frfossilfuel_nonheat, colnamesinputfiles::ca_frpddwe, colnamesinputfiles::ca_maxfcmetab, colnamesinputfiles::ca_maxqfmetab, colnamesinputfiles::ca_minfcmetab, colnamesinputfiles::ca_minqfmetab, colnamesinputfiles::ca_popprofwd, colnamesinputfiles::ca_popprofwe, colnamesinputfiles::ca_qf_a1, colnamesinputfiles::ca_qf_a2, colnamesinputfiles::ca_qf_b1, colnamesinputfiles::ca_qf_b2, colnamesinputfiles::ca_qf_c1, colnamesinputfiles::ca_qf_c2, colnamesinputfiles::ca_tcriticcooling_wd, colnamesinputfiles::ca_tcriticcooling_we, colnamesinputfiles::ca_tcriticheating_wd, colnamesinputfiles::ca_tcriticheating_we, colnamesinputfiles::ca_trafficunits, colnamesinputfiles::ca_traffprofwd, colnamesinputfiles::ca_traffprofwe, colnamesinputfiles::cb_alpha, colnamesinputfiles::cb_alpha_enh, colnamesinputfiles::cb_beta, colnamesinputfiles::cb_beta_enh, colnamesinputfiles::cb_code, colnamesinputfiles::cb_min_r, colnamesinputfiles::cb_resp_a, colnamesinputfiles::cb_resp_b, colnamesinputfiles::cb_theta, colnamesinputfiles::cc_code, colnamesinputfiles::cc_gsg1, colnamesinputfiles::cc_gsg2, colnamesinputfiles::cc_gsg3, colnamesinputfiles::cc_gsg4, colnamesinputfiles::cc_gsg5, colnamesinputfiles::cc_gsg6, colnamesinputfiles::cc_gskmax, colnamesinputfiles::cc_gsmodel, colnamesinputfiles::cc_gss1, colnamesinputfiles::cc_gss2, colnamesinputfiles::cc_gsth, colnamesinputfiles::cc_gstl, colnamesinputfiles::ce_alb_ibld, colnamesinputfiles::ce_ch_ibld, colnamesinputfiles::ce_ch_iroof, colnamesinputfiles::ce_ch_iwall, colnamesinputfiles::ce_code, colnamesinputfiles::ce_em_ibld, colnamesinputfiles::ce_internal_k1, colnamesinputfiles::ce_internal_k2, colnamesinputfiles::ce_internal_k3, colnamesinputfiles::ce_internal_k4, colnamesinputfiles::ce_internal_k5, colnamesinputfiles::ce_internal_rhocp1, colnamesinputfiles::ce_internal_rhocp2, colnamesinputfiles::ce_internal_rhocp3, colnamesinputfiles::ce_internal_rhocp4, colnamesinputfiles::ce_internal_rhocp5, colnamesinputfiles::ce_internal_thick1, colnamesinputfiles::ce_internal_thick2, colnamesinputfiles::ce_internal_thick3, colnamesinputfiles::ce_internal_thick4, colnamesinputfiles::ce_internal_thick5, colnamesinputfiles::ce_nroom, colnamesinputfiles::ce_surf_k1, colnamesinputfiles::ce_surf_k2, colnamesinputfiles::ce_surf_k3, colnamesinputfiles::ce_surf_k4, colnamesinputfiles::ce_surf_k5, colnamesinputfiles::ce_surf_rhocp1, colnamesinputfiles::ce_surf_rhocp2, colnamesinputfiles::ce_surf_rhocp3, colnamesinputfiles::ce_surf_rhocp4, colnamesinputfiles::ce_surf_rhocp5, colnamesinputfiles::ce_surf_thick1, colnamesinputfiles::ce_surf_thick2, colnamesinputfiles::ce_surf_thick3, colnamesinputfiles::ce_surf_thick4, colnamesinputfiles::ce_surf_thick5, colnamesinputfiles::ce_wall_k1, colnamesinputfiles::ce_wall_k2, colnamesinputfiles::ce_wall_k3, colnamesinputfiles::ce_wall_k4, colnamesinputfiles::ce_wall_k5, colnamesinputfiles::ce_wall_rhocp1, colnamesinputfiles::ce_wall_rhocp2, colnamesinputfiles::ce_wall_rhocp3, colnamesinputfiles::ce_wall_rhocp4, colnamesinputfiles::ce_wall_rhocp5, colnamesinputfiles::ce_wall_thick1, colnamesinputfiles::ce_wall_thick2, colnamesinputfiles::ce_wall_thick3, colnamesinputfiles::ce_wall_thick4, colnamesinputfiles::ce_wall_thick5, colnamesinputfiles::ci_albmax, colnamesinputfiles::ci_albmin, colnamesinputfiles::ci_chanohm, colnamesinputfiles::ci_code, colnamesinputfiles::ci_cpanohm, colnamesinputfiles::ci_drcoef1, colnamesinputfiles::ci_drcoef2, colnamesinputfiles::ci_dreq, colnamesinputfiles::ci_emis, colnamesinputfiles::ci_estmcode, colnamesinputfiles::ci_kkanohm, colnamesinputfiles::ci_ohmcode_sdry, colnamesinputfiles::ci_ohmcode_swet, colnamesinputfiles::ci_ohmcode_wdry, colnamesinputfiles::ci_ohmcode_wwet, colnamesinputfiles::ci_ohmthresh_sw, colnamesinputfiles::ci_ohmthresh_wd, colnamesinputfiles::ci_snowlimpat, colnamesinputfiles::ci_snowlimrem, colnamesinputfiles::ci_soiltcode, colnamesinputfiles::ci_statelimit, colnamesinputfiles::ci_stormax, colnamesinputfiles::ci_stormin, colnamesinputfiles::ci_wetthresh, colnamesinputfiles::cir_code, colnamesinputfiles::cir_daywat1, colnamesinputfiles::cir_daywat2, colnamesinputfiles::cir_daywat3, colnamesinputfiles::cir_daywat4, colnamesinputfiles::cir_daywat5, colnamesinputfiles::cir_daywat6, colnamesinputfiles::cir_daywat7, colnamesinputfiles::cir_daywatper1, colnamesinputfiles::cir_daywatper2, colnamesinputfiles::cir_daywatper3, colnamesinputfiles::cir_daywatper4, colnamesinputfiles::cir_daywatper5, colnamesinputfiles::cir_daywatper6, colnamesinputfiles::cir_daywatper7, colnamesinputfiles::cir_faut, colnamesinputfiles::cir_ie_a1, colnamesinputfiles::cir_ie_a2, colnamesinputfiles::cir_ie_a3, colnamesinputfiles::cir_ie_m1, colnamesinputfiles::cir_ie_m2, colnamesinputfiles::cir_ie_m3, colnamesinputfiles::cir_ieend, colnamesinputfiles::cir_iestart, colnamesinputfiles::cir_intwu, colnamesinputfiles::co_a1, colnamesinputfiles::co_a2, colnamesinputfiles::co_a3, colnamesinputfiles::co_code, colnamesinputfiles::cp_albmax, colnamesinputfiles::cp_albmin, colnamesinputfiles::cp_baset, colnamesinputfiles::cp_basete, colnamesinputfiles::cp_biogenco2code, colnamesinputfiles::cp_chanohm, colnamesinputfiles::cp_code, colnamesinputfiles::cp_cpanohm, colnamesinputfiles::cp_drcoef1, colnamesinputfiles::cp_drcoef2, colnamesinputfiles::cp_dreq, colnamesinputfiles::cp_emis, colnamesinputfiles::cp_estmcode, colnamesinputfiles::cp_gddfull, colnamesinputfiles::cp_gsmax, colnamesinputfiles::cp_kkanohm, colnamesinputfiles::cp_laieq, colnamesinputfiles::cp_laimax, colnamesinputfiles::cp_laimin, colnamesinputfiles::cp_leafgp1, colnamesinputfiles::cp_leafgp2, colnamesinputfiles::cp_leafop1, colnamesinputfiles::cp_leafop2, colnamesinputfiles::cp_ohmcode_sdry, colnamesinputfiles::cp_ohmcode_swet, colnamesinputfiles::cp_ohmcode_wdry, colnamesinputfiles::cp_ohmcode_wwet, colnamesinputfiles::cp_ohmthresh_sw, colnamesinputfiles::cp_ohmthresh_wd, colnamesinputfiles::cp_porositymax, colnamesinputfiles::cp_porositymin, colnamesinputfiles::cp_sddfull, colnamesinputfiles::cp_snowlimpat, colnamesinputfiles::cp_soiltcode, colnamesinputfiles::cp_statelimit, colnamesinputfiles::cp_stormax, colnamesinputfiles::cp_stormin, colnamesinputfiles::cp_wetthresh, colnamesinputfiles::cpr_code, colnamesinputfiles::cpr_hours, colnamesinputfiles::cs_chanohm, colnamesinputfiles::cs_code, colnamesinputfiles::cs_cpanohm, colnamesinputfiles::cs_estmcode, colnamesinputfiles::cs_kkanohm, colnamesinputfiles::cs_ohmcode_sdry, colnamesinputfiles::cs_ohmcode_swet, colnamesinputfiles::cs_ohmcode_wdry, colnamesinputfiles::cs_ohmcode_wwet, colnamesinputfiles::cs_ohmthresh_sw, colnamesinputfiles::cs_ohmthresh_wd, colnamesinputfiles::cs_snowalbmax, colnamesinputfiles::cs_snowalbmin, colnamesinputfiles::cs_snowcrwmax, colnamesinputfiles::cs_snowcrwmin, colnamesinputfiles::cs_snowemis, colnamesinputfiles::cs_snowplimalb, colnamesinputfiles::cs_snowplimsnow, colnamesinputfiles::cs_snowrmfactor, colnamesinputfiles::cs_snowsdmax, colnamesinputfiles::cs_snowsdmin, colnamesinputfiles::cs_snowtau_a, colnamesinputfiles::cs_snowtau_f, colnamesinputfiles::cs_snowtau_r, colnamesinputfiles::cs_snowtmfactor, colnamesinputfiles::cso_code, colnamesinputfiles::cso_ksat, colnamesinputfiles::cso_obssmdepth, colnamesinputfiles::cso_obssmmax, colnamesinputfiles::cso_obssnrfrac, colnamesinputfiles::cso_soildens, colnamesinputfiles::cso_soildepth, colnamesinputfiles::cso_soilinfrate, colnamesinputfiles::cso_soilstcap, colnamesinputfiles::cw_albmax, colnamesinputfiles::cw_albmin, colnamesinputfiles::cw_chanohm, colnamesinputfiles::cw_code, colnamesinputfiles::cw_cpanohm, colnamesinputfiles::cw_drcoef1, colnamesinputfiles::cw_drcoef2, colnamesinputfiles::cw_dreq, colnamesinputfiles::cw_emis, colnamesinputfiles::cw_estmcode, colnamesinputfiles::cw_kkanohm, colnamesinputfiles::cw_ohmcode_sdry, colnamesinputfiles::cw_ohmcode_swet, colnamesinputfiles::cw_ohmcode_wdry, colnamesinputfiles::cw_ohmcode_wwet, colnamesinputfiles::cw_ohmthresh_sw, colnamesinputfiles::cw_ohmthresh_wd, colnamesinputfiles::cw_statelimit, colnamesinputfiles::cw_stormax, colnamesinputfiles::cw_stormin, colnamesinputfiles::cw_waterdepth, colnamesinputfiles::cw_wetthresh, colnamesinputfiles::cwg_code, colnamesinputfiles::cwg_tobldgs, colnamesinputfiles::cwg_tobsoil, colnamesinputfiles::cwg_todectr, colnamesinputfiles::cwg_toevetr, colnamesinputfiles::cwg_tograss, colnamesinputfiles::cwg_topaved, colnamesinputfiles::cwg_torunoff, colnamesinputfiles::cwg_tosoilstore, colnamesinputfiles::cwg_towater, errorhint(), allocatearray::headeranthropogenic_file, allocatearray::headeranthropogenic_reqd, allocatearray::headerbiogen_file, allocatearray::headerbiogen_reqd, allocatearray::headercond_file, allocatearray::headercond_reqd, allocatearray::headerestmcoefficients_file, allocatearray::headerestmcoefficients_reqd, allocatearray::headerirrigation_file, allocatearray::headerirrigation_reqd, allocatearray::headernonveg_file, allocatearray::headernonveg_reqd, allocatearray::headerohmcoefficients_file, allocatearray::headerohmcoefficients_reqd, allocatearray::headerprofiles_file, allocatearray::headerprofiles_reqd, allocatearray::headersnow_file, allocatearray::headersnow_reqd, allocatearray::headersoil_file, allocatearray::headersoil_reqd, allocatearray::headerveg_file, allocatearray::headerveg_reqd, allocatearray::headerwater_file, allocatearray::headerwater_reqd, allocatearray::headerwgwaterdist_file, allocatearray::headerwgwaterdist_reqd, defaultnotused::notused, and defaultnotused::notusedi.
Referenced by readcoeff().
metread()
subroutine metread (integer lfn, real(kind(1d0)), dimension(24) MetArray, integer InputmetFormat, integer ldown_option, integer NetRadiationMethod, integer snowUse, integer SMDMethod, real(kind(1d0)) SoilDepthMeas, real(kind(1d0)) SoilRocks, real(kind(1d0)) SoilDensity, real(kind(1d0)) SmCap)
Definition at line 15 of file suews_ctrl_input.f95.
    USE defaultnotused
    IMPLICIT NONE
    !INPUT
    REAL(KIND(1d0)), DIMENSION(24)::MetArray !Array leaving the subroutine within
    !each INTERVAL (defined in RunControl.nml)
    ! - Met data now provided at a resolution of tstep, HCW Jan 2015
    REAL(KIND(1d0))::SmCap, &
                      SoilDepthMeas, &        !Measured soil depth
                      SoilRocks, &            !Rocks on ground
                      SoilDensity            !Density of soil
    INTEGER::InputmetFormat, &     !Format of the meteorological forcing file
              ldown_option, &       !Method of calculating Ldown
              NetRadiationMethod, & !Method of calculating Q*
              SMDMethod, &         !Method of measured soil moisture
              snowUse
    ! Variables read in
    REAL(KIND(1d0))::avkdn, &     !Average downwelling shortwave radiation
                      avrh, &      !Average relative humidity
                      avu1, &      !Average wind speed
                      dectime, &   !Decimal time
                      fcld_obs, &  !Cloud fraction observed
                      iy, &        !Year
                      id, &        !Day
                      it, &        !Hour
                      imin, &      !Minute
                      kdiff, &     !Diffuse shortwave radiation
                      kdir, &      !Direct shortwave radiation
                      LAI_obs, &   !Overall LAI of the study area
                      ldown_obs, & !Downwelling longwave radiation
                      Precip, & !Rainfall [mm]
                      Pres_hPa, &  !Station air pressure in hPa
                      Pres_kPa, &  !Station air pressure in kPa
                      snowFrac_obs, &  !Observed surface fraction of snow (between 0 and 1)
                      qe_obs, &    !Observed latent heat flux
                      qf_obs, &    !Observed antrhropogeni heat flux
                      qh_obs, &    !Observed sensible heat flux
                      qn1_obs, &   !Observed net all-wave radiation
                      qs_obs, &    !Observed storage heat flux
                      Temp_C, &    !Air temperature
                      wdir, &      !Wind direction
                      wu_m3, &     !Water use provided in met forcing file [m3]
                      xsmd        !Measured soil moisture deficit
    INTEGER::iostat_var, lfn
    !-----------------------------------------------------------------------------------
    !-----------------------------------------------------------------------------------
    IF (inputmetformat == 0) THEN   !Default format using LUMPS only
       READ (lfn, *, iostat=iostat_var) iy, id, it, imin, qn1_obs, avu1, avrh, &
          temp_c, wdir, pres_kpa, precip, avkdn, snowfrac_obs, ldown_obs, fcld_obs
       !Set other variables needed while running SUEWS to zero
       qf_obs = nan
       qs_obs = nan
       qh_obs = nan
       qe_obs = nan
       xsmd = -99999
       kdiff = nan
       kdir = nan
       wdir = nan
    ELSEIF (inputmetformat == 10) THEN !SUEWS reading
       READ (lfn, *, iostat=iostat_var) iy, id, it, imin, qn1_obs, qh_obs, qe_obs, qs_obs, qf_obs, avu1, avrh, &
          temp_c, pres_kpa, precip, avkdn, snowfrac_obs, ldown_obs, fcld_obs, &
          wu_m3, xsmd, lai_obs, kdiff, kdir, wdir
       !write(*,*) 'In LUMPS_MetRead (1)'
       !write(*,*) 'imin',imin
       !write(*,*) 'it',it
       !write(*,*) 'id',id
       !write(*,*) 'iy',iy
       !Calculate observed soil moisture deficits from either volumetric or gravimetric SoilStates
       IF (smdmethod == 1 .AND. xsmd /= -999) THEN !Soil moisture - volumetric
          xsmd = (smcap - xsmd)*soildepthmeas*soilrocks
       ELSEIF (smdmethod == 2 .AND. xsmd /= -999) THEN !Soil moisture -gravimetric
          xsmd = (smcap - xsmd)*soildensity*soildepthmeas*soilrocks
       ELSE
          xsmd = -999
       ENDIF
    ELSE
       CALL errorhint(55, 'RunControl.nml, InputMetFormat not usable.', notused, notused, inputmetformat)
    ENDIF
    !===============Meteorological variables reading done==========================
    pres_hpa = pres_kpa*10. ! convert to hPa
    IF (iostat_var < 0) THEN
       iostat_var = 0
       CLOSE (lfn)
       RETURN
    ENDIF
    IF (avkdn < 0) THEN
       CALL errorhint(27, 'Met Data: avKdn - needed for StoreDrainPrm. resistance, If present, check file not tab delimited', &
                      avkdn, dectime, notusedi)
       !sg removed this is causing the problems with resistances
       !  AvKdn=0 !Solar radiation cannot be lower than 1
    ENDIF
    IF ((ldown_option == 1) .AND. (ldown_obs < 0)) THEN
       CALL errorhint(27, 'Met Data: LWdn (ldown_obs) - impact Q* calc', ldown_obs, dectime, notusedi)
    ELSEIF (ldown_option == 2) THEN
       IF (fcld_obs == -999.0 .OR. fcld_obs < 0 .OR. fcld_obs > 1) THEN
          CALL errorhint(27, 'Met Data: flcd_obs - impacts LW & Q* radiation', fcld_obs, dectime, notusedi)
       ENDIF
    ENDIF
    IF (qn1_obs == -999 .AND. netradiationmethod == 0) THEN  !If measured Q* is used and it is -999
       CALL errorhint(27, 'Met Data: Q* - will impact everything', qn1_obs, dectime, notusedi)
    ENDIF
    IF (avu1 <= 0) THEN !If wind speed is negative
       CALL errorhint(27, 'Met Data: avU1 - impacts aeroydnamic resistances', avu1, dectime, notusedi)
    ENDIF
    IF (temp_c < -50 .OR. temp_c > 60) THEN !If temperature unrealistic
       CALL errorhint(27, 'Met Data: Temp_C - beyond what is expected', temp_c, dectime, notusedi)
    ENDIF
    IF (avrh > 100 .OR. avrh < 1) THEN !If relative humidity larger than 100%
       CALL errorhint(27, 'Met Data: avRH - beyond what is expected', avrh, dectime, notusedi)
    ENDIF
    IF (pres_kpa < 80) THEN  !If pressure too low
       CALL errorhint(27, 'Met Data: Pres_kPa - too low - this could be fixed in model', pres_kpa, dectime, notusedi)
    ENDIF
    IF (precip < 0) THEN  !If rain in negative, set it to zero
       CALL errorhint(27, 'Met Data: Precip - less than 0', precip, dectime, notusedi)
    ENDIF
    IF (snowfrac_obs == nan) snowfrac_obs = 0
    IF (snowuse == 0 .AND. (snowfrac_obs < 0 .OR. snowfrac_obs > 1)) THEN
       CALL errorhint(27, 'Met Data: snow not between [0  1]', snowfrac_obs, dectime, notusedi)
    ENDIF
    IF (xsmd < 0 .AND. smdmethod == 1) THEN  !If soil moisture deficit is zero
       CALL errorhint(27, 'Met Data: xsmd - less than 0', xsmd, dectime, notusedi)
    ENDIF
    !Create an array to be printed out.
    metarray(1:24) = (/iy, id, it, imin, qn1_obs, qh_obs, qe_obs, qs_obs, qf_obs, avu1, &
                       avrh, temp_c, pres_hpa, precip, avkdn, snowfrac_obs, ldown_obs, &
                       fcld_obs, wu_m3, xsmd, lai_obs, kdiff, kdir, wdir/)
    !write(*,*) 'In LUMPS_MetRead (2)'
    !write(*,*) 'imin',imin
    !write(*,*) 'it',it
    !write(*,*) 'id',id
    !write(*,*) 'iy',iy
    RETURN
References errorhint(), defaultnotused::nan, defaultnotused::notused, and defaultnotused::notusedi.
Referenced by metdisagg::disaggregatemet(), and suews_initializemetdata().
run_control()
subroutine run_control (integer eval, integer LowerLimit, integer Upperlimit)
Definition at line 201 of file suews_ctrl_input.f95.
    ! ver - determines if value to be read is an integer or real and returns the value
    ! if ver=-9 - then use integer
    USE run_info
    IMPLICIT NONE
    INTEGER::eval, i, lowerlimit, upperlimit
    CHARACTER(len=4)::check
    IF (file_qs) THEN
 101   READ (lfn_us, *) check
       WRITE (*, *) check
       DO i = 1, 3
          IF (check(i:i) == "#") THEN
             !   write(*,*)check(i:i),i,"check"
             GOTO 101
          ELSE
             backspace(lfn_us)
             READ (lfn_us, *) eval
             !write(*,*)eval, TEXT(1)
             EXIT
          ENDIF
       ENDDO
    ENDIF
    WRITE (12, 120) eval, text(1)
    IF (eval < lowerlimit .OR. eval > upperlimit) THEN
       WRITE (*, *) "Value out of range"
       WRITE (*, *) eval, text(1)
       stop
    ENDIF
    WRITE (*, 120) eval, text(1)
 120 FORMAT(i4, 2x, a90)
    RETURN
References run_info::file_qs, run_info::lfn_us, and run_info::text.
skipheader()
subroutine skipheader (integer lfn, integer skip)
Definition at line 240 of file suews_ctrl_input.f95.
    USE defaultnotused
    IMPLICIT NONE
    INTEGER::skip, lfn, i
    DO i = 1, skip
       READ (lfn, *, err=201, iostat=ios_out)
    END DO
    RETURN
 201 reall = real(skip)
    CALL errorhint(20, 'In SkipHeader subroutine.', reall, notused, ios_out)
References errorhint(), defaultnotused::ios_out, defaultnotused::notused, and defaultnotused::reall.
Referenced by estm_module::suews_getestmdata(), and suews_initializemetdata().