SUEWS: /Users/hamidrezaomidvar/Desktop/SUEWS/SUEWS-SourceCode/suews_util_time.f95 File Reference
suews_util_time.f95 File Reference
Functions/Subroutines
subroutine day2month (b, mb, md, seas, year, latitude)
subroutine month2day (mon, ne, k, b)
subroutine leapyearcalc (year_int, nroDays)
elemental integer function days_of_year (year_int)
subroutine day_of_week (DATE, MONTH, YEAR, DOW)
subroutine dectime_to_timevec (dectime, HOURS, MINS, SECS)
subroutine daylen (DOY, XLAT, DAYL, DEC, SNDN, SNUP)
subroutine suews_cal_dectime (id, it, imin, isec, dectime)
subroutine suews_cal_tstep (tstep, nsh, nsh_real, tstep_real)
subroutine suews_cal_weekday (iy, id, lat, dayofWeek_id)
subroutine suews_cal_dls (id, startDLS, endDLS, DLS)
Function/Subroutine Documentation
day2month()
subroutine day2month (integer, intent(in) b, integer, intent(out) mb, integer, intent(out) md, integer, intent(out) seas, integer, intent(in) year, real(kind(1d0)) latitude)
Definition at line 24 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER, INTENT(in) ::b  !b=doy   --IN
    INTEGER, INTENT(out) ::mb !month=mb  --OUT
    INTEGER, INTENT(out) ::md !date=md --OUT
    INTEGER, INTENT(out) ::seas
    INTEGER, INTENT(in) ::year
    INTEGER::t1, t2, t3
    INTEGER::k ! k- accounts for leap year
    REAL(KIND(1d0))::latitude
    !Corrected and calculation of date added LJ (Jun 2010)
    t1 = 4
    t2 = 100
    t3 = 400
    IF ((modulo(year, t1) == 0) .AND. (modulo(year, t2) /= 0) .OR. (modulo(year, t3) == 0)) THEN
       k = 1
    ELSE
       k = 0
    ENDIF
    IF (b <= 31) THEN !January
       mb = 1
       md = b
    ELSEIF (b > 31 .AND. b <= 59 + k) THEN
       mb = 2
       md = b - 31
    ELSEIF (b > 59 + k .AND. b <= 90 + k) THEN
       mb = 3
       md = b - (59 + k)
    ELSEIF (b > 90 + k .AND. b <= 120 + k) THEN
       mb = 4
       md = b - (90 + k)
    ELSEIF (b > 120 + k .AND. b <= 151 + k) THEN
       mb = 5
       md = b - (120 + k)
    ELSEIF (b > 151 + k .AND. b <= 181 + k) THEN
       mb = 6
       md = b - (151 + k)
    ELSEIF (b > 181 + k .AND. b <= 212 + k) THEN
       mb = 7
       md = b - (181 + k)
    ELSEIF (b > 212 + k .AND. b <= 243 + k) THEN
       mb = 8
       md = b - (212 + k)
    ELSEIF (b > 243 + k .AND. b <= 273 + k) THEN
       mb = 9
       md = b - (243 + k)
    ELSEIF (b > 273 + k .AND. b <= 304 + k) THEN
       mb = 10
       md = b - (273 + k)
    ELSEIF (b > 304 + k .AND. b <= 334 + k) THEN
       mb = 11
       md = b - (304 + k)
    ELSEIF (b > 334 + k) THEN
       mb = 12
       md = b - (334 + k)
    ENDIF
    !
    IF (latitude > 0) THEN  ! Northern Hemisphere
       IF (mb > 3 .AND. mb < 10) THEN !Summer is from Apr to Sep
          seas = 1
       ELSE
          seas = 2 !Winter rest of the months
       ENDIF
    ELSE  ! southern hemisphere
       IF (mb < 4 .OR. mb > 9) THEN !Summer is from Oct to Mar
          seas = 1
       ELSE
          seas = 2 !Winter rest of the months
       ENDIF
    ENDIF
    RETURN
Referenced by initialstate(), narp_module::narp_cal_sunposition(), and suews_cal_weekday().
day_of_week()
subroutine day_of_week (integer DATE, integer MONTH, integer YEAR, integer DOW)
Definition at line 171 of file suews_util_time.f95.
    ! Calculate weekday from year, month and day information.
    ! DOW: Sunday=1,...Saturday=7
    ! YEAR fixed to integer, LJ March 2015
    IMPLICIT NONE
    INTEGER DATE, MONTH, DAY, YR, MN, N1, N2, DOW, YEAR
    yr = year
    mn = month
    !C
    !C       IF JANUARY OR FEBRUARY, ADJUST MONTH AND YEAR
    !C
    IF (mn > 2) GO TO 10
    mn = mn + 12
    yr = yr - 1
 10 n1 = (26*(mn + 1))/10
    n2 = (125*yr)/100
    day = (date + n1 + n2 - (yr/100) + (yr/400) - 1)
    dow = mod(day, 7) + 1
    RETURN
Referenced by initialstate(), and suews_cal_weekday().
daylen()
subroutine daylen (integer DOY, real(kind(1d0)) XLAT, real(kind(1d0)) DAYL, real(kind(1d0)) DEC, real(kind(1d0)) SNDN, real(kind(1d0)) SNUP)
Definition at line 228 of file suews_util_time.f95.
    !-----------------------------------------------------------------------
    IMPLICIT NONE
    INTEGER :: DOY
    REAL(KIND(1d0)) :: DEC, DAYL, SOC, SNDN, SNUP, XLAT
    REAL(KIND(1d0)), PARAMETER :: PI = 3.14159, rad = pi/180.0
    !-----------------------------------------------------------------------
    !     Calculation of declination of sun (Eqn. 16). Amplitude= +/-23.45
    !     deg. Minimum = DOY 355 (DEC 21), maximum = DOY 172.5 (JUN 21/22).
    dec = -23.45*cos(2.0*pi*(doy + 10.0)/365.0)
    !     Sun angles.  SOC limited for latitudes above polar circles.
    soc = tan(rad*dec)*tan(rad*xlat)
    soc = min(max(soc, -1.0), 1.0)
    !     Calculate daylength, sunrise and sunset (Eqn. 17)
    dayl = 12.0 + 24.0*asin(soc)/pi
    snup = 12.0 - dayl/2.0
    sndn = 12.0 + dayl/2.0
days_of_year()
elemental integer function days_of_year (integer, intent(in) year_int)
Definition at line 154 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER, INTENT(in) :: year_int
    INTEGER :: nDays
    IF (mod(year_int, 100) /= 0 .AND. mod(year_int, 4) == 0) THEN
       ndays = 366
    ELSEIF (mod(year_int, 400) == 0) THEN
       ndays = 366
    ELSE
       ndays = 365
    ENDIF
dectime_to_timevec()
subroutine dectime_to_timevec (real(kind(1d0)) dectime, integer HOURS, integer MINS, real(kind(1d0)) SECS)
Definition at line 200 of file suews_util_time.f95.
    !This subroutine converts dectime to individual
    !hours, minutes and seconds
    INTEGER :: HOURS, MINS, doy
    REAL(KIND(1d0))    :: dectime, SECS, DH, DM, DS
    !INTEGER :: year
    doy = floor(dectime)
    dh = dectime - doy !Decimal hours
    hours = int(24*dh)
    dm = 24*dh - hours !Decimal minutes
    mins = int(60*dm)
    ds = 60*dm - mins
    secs = int(60*ds)
Referenced by narp_module::narp_cal_sunposition().
leapyearcalc()
subroutine leapyearcalc (integer year_int, integer nroDays)
Definition at line 136 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER :: nroDays, year_int
    IF (mod(year_int, 100) /= 0 .AND. mod(year_int, 4) == 0) THEN
       nrodays = 366
    ELSEIF (mod(year_int, 400) == 0) THEN
       nrodays = 366
    ELSE
       nrodays = 365
    ENDIF
Referenced by initialstate(), and suews_program().
month2day()
subroutine month2day (integer mon, integer ne, integer k, integer b)
Definition at line 103 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER:: mon, ne, k, b
    IF (mon == 1) THEN
       ne = 32 - b
    ELSE IF (mon == 2) THEN
       ne = 60 + k - b
    ELSE IF (mon == 3) THEN
       ne = 91 + k - b
    ELSE IF (mon == 4) THEN
       ne = 121 + k - b
    ELSE IF (mon == 5) THEN
       ne = 152 + k - b
    ELSE IF (mon == 6) THEN
       ne = 182 + k - b
    ELSE IF (mon == 7) THEN
       ne = 213 + k - b
    ELSE IF (mon == 8) THEN
       ne = 244 + k - b
       !**********PAGE 151 STARTS HERE**************
    ELSE IF (mon == 9) THEN
       ne = 274 + k - b
    ELSE IF (mon == 10) THEN
       ne = 305 + k - b
    ELSE IF (mon == 11) THEN
       ne = 335 + k - b
    ELSE IF (mon == 12) THEN
       ne = 366 + k - b
    END IF
suews_cal_dectime()
subroutine suews_cal_dectime (integer, intent(in) id, integer, intent(in) it, integer, intent(in) imin, integer, intent(in) isec, real(kind(1d0)), intent(out) dectime)
Definition at line 268 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER, INTENT(in)::id, it, imin, isec
    REAL(KIND(1D0)), INTENT(out)::dectime ! nsh in type real
    dectime = real(id - 1, kind(1d0)) &
              + real(it, kind(1d0))/24 &
              + real(imin, kind(1d0))/(60*24) &
              + real(isec, kind(1d0))/(60*60*24)
Referenced by suews_driver::suews_cal_main().
suews_cal_dls()
subroutine suews_cal_dls (integer, intent(in) id, integer, intent(in) startDLS, integer, intent(in) endDLS, integer, intent(out) DLS)
Definition at line 324 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER, INTENT(in) :: id, startDLS, endDLS
    INTEGER, INTENT(out) :: DLS
    dls = 0
    IF (id > startdls .AND. id < enddls) dls = 1
Referenced by suews_driver::suews_cal_main().
suews_cal_tstep()
subroutine suews_cal_tstep (integer, intent(in) tstep, integer, intent(out) nsh, real(kind(1d0)), intent(out) nsh_real, real(kind(1d0)), intent(out) tstep_real)
Definition at line 284 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER, INTENT(in)::tstep ! number of timesteps per hour
    ! values that are derived from tstep
    INTEGER, INTENT(out)::nsh ! number of timesteps per hour
    REAL(KIND(1D0)), INTENT(out)::nsh_real ! nsh in type real
    REAL(KIND(1D0)), INTENT(out)::tstep_real ! tstep in type real
    nsh = 3600/tstep
    nsh_real = nsh*1.0
    tstep_real = tstep*1.0
Referenced by suews_driver::suews_cal_main().
suews_cal_weekday()
subroutine suews_cal_weekday (integer, intent(in) iy, integer, intent(in) id, real(kind(1d0)), intent(in) lat, integer, dimension(3), intent(out) dayofWeek_id)
Definition at line 299 of file suews_util_time.f95.
    IMPLICIT NONE
    INTEGER, INTENT(in) :: iy  ! year
    INTEGER, INTENT(in) :: id  ! day of year
    REAL(KIND(1d0)), INTENT(in):: lat
    INTEGER, DIMENSION(3), INTENT(OUT) ::dayofWeek_id
    INTEGER::wd
    INTEGER::mb
    INTEGER::date
    INTEGER::seas
    CALL day2month(id, mb, date, seas, iy, lat) !Calculate real date from doy
    CALL day_of_week(date, mb, iy, wd)        !Calculate weekday (1=Sun, ..., 7=Sat)
    dayofweek_id(1) = wd      !Day of week
    dayofweek_id(2) = mb      !Month
    dayofweek_id(3) = seas    !Season
References day2month(), and day_of_week().
Referenced by initialstate(), and suews_driver::suews_cal_main().